import type { CuisineRecipeConfig } from './types';
import { generateCuisineRecipes } from './types';

const configs: CuisineRecipeConfig[] = [
  {
    title: 'Jollof Rice',
    description: 'One-pot West African tomato and pepper rice with smoky depth and spicy kick.',
    cuisine: 'African',
    prep_minutes: 20,
    cook_minutes: 45,
    servings: 6,
    calories: 350,
    ingredients: [
      { name: 'long grain rice', quantity: '3', unit: 'cups' },
      { name: 'tomato paste', quantity: '3', unit: 'tbsp' },
      { name: 'red bell pepper', quantity: '2', unit: 'blended' },
      { name: 'scotch bonnet pepper', quantity: '2', unit: 'whole' },
      { name: 'onion', quantity: '1', unit: 'large, diced' },
      { name: 'vegetable oil', quantity: '1/4', unit: 'cup' },
      { name: 'thyme', quantity: '1', unit: 'tsp' },
      { name: 'bay leaf', quantity: '2', unit: 'pieces' },
    ],
    steps: [
      'Blend red bell peppers and scotch bonnet peppers into a smooth paste.',
      'Heat oil and fry onion until translucent. Add tomato paste and pepper blend. Cook 15 minutes.',
      'Add thyme, bay leaf, and season with salt. Add washed rice and stir to coat.',
      'Add water to just above rice level. Cook covered on low heat for 25 minutes until rice is fluffy.',
    ],
    tags: ['jollof', 'rice', 'west african', 'one-pot', 'spicy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 350,
      protein_g: 6,
      carbs_g: 58,
      fat_g: 10,
      fiber_g: 3,
      sugar_g: 5,
      sodium_mg: 380,
    },
  },
  {
    title: 'Injera with Doro Wat',
    description: 'Ethiopian sour flatbread served with spicy chicken stew hard-boiled eggs.',
    cuisine: 'African',
    prep_minutes: 30,
    cook_minutes: 120,
    servings: 6,
    calories: 420,
    ingredients: [
      { name: 'teff flour', quantity: '2', unit: 'cups' },
      { name: 'water', quantity: '2', unit: 'cups' },
      { name: 'chicken thighs', quantity: '8', unit: 'pieces' },
      { name: 'red onion', quantity: '4', unit: 'large, finely diced' },
      { name: 'niter kibbeh', quantity: '1/4', unit: 'cup' },
      { name: 'berbere spice', quantity: '3', unit: 'tbsp' },
      { name: 'hard-boiled eggs', quantity: '4', unit: 'peeled' },
      { name: 'garlic', quantity: '4', unit: 'cloves, minced' },
    ],
    steps: [
      'Make injera batter: mix teff flour with water and let ferment 2-3 days. Cook like crepes on a hot griddle.',
      'Make doro wat: slowly cook onions without oil until deeply caramelized, about 40 minutes.',
      'Add niter kibbeh, berbere, and garlic. Cook 10 minutes. Add chicken and simmer 45 minutes.',
      'Add hard-boiled eggs in the last 10 minutes. Serve doro wat on injera.',
    ],
    tags: ['injera', 'doro wat', 'ethiopian', 'chicken', 'stew'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 28,
      carbs_g: 38,
      fat_g: 18,
      fiber_g: 5,
      sugar_g: 4,
      sodium_mg: 480,
    },
  },
  {
    title: 'Chicken Tagine',
    description: 'Moroccan slow-braised chicken with preserved lemons, olives, and warm spices.',
    cuisine: 'African',
    prep_minutes: 20,
    cook_minutes: 60,
    servings: 6,
    calories: 380,
    ingredients: [
      { name: 'chicken pieces', quantity: '3', unit: 'lbs' },
      { name: 'preserved lemon', quantity: '2', unit: 'quartered' },
      { name: 'green olives', quantity: '1/2', unit: 'cup' },
      { name: 'onion', quantity: '2', unit: 'large, sliced' },
      { name: 'ginger', quantity: '1', unit: 'tbsp, grated' },
      { name: 'saffron', quantity: '1', unit: 'pinch' },
      { name: 'cilantro', quantity: '1/4', unit: 'cup, chopped' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Brown chicken pieces in olive oil in a tagine or Dutch oven.',
      'Add onion, ginger, saffron, and enough water to cover. Simmer 40 minutes.',
      'Add preserved lemon and olives. Cook 15 more minutes.',
      'Garnish with cilantro and serve over couscous.',
    ],
    tags: ['tagine', 'moroccan', 'chicken', 'olive', 'preserved lemon'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 380,
      protein_g: 34,
      carbs_g: 8,
      fat_g: 24,
      fiber_g: 2,
      sugar_g: 2,
      sodium_mg: 520,
    },
  },
  {
    title: 'Bobotie',
    description: 'South African curried minced meat bake topped with a golden egg custard.',
    cuisine: 'African',
    prep_minutes: 25,
    cook_minutes: 45,
    servings: 6,
    calories: 400,
    ingredients: [
      { name: 'ground beef', quantity: '1.5', unit: 'lbs' },
      { name: 'onion', quantity: '1', unit: 'large, diced' },
      { name: 'curry powder', quantity: '2', unit: 'tbsp' },
      { name: 'raisins', quantity: '1/4', unit: 'cup' },
      { name: 'chutney', quantity: '2', unit: 'tbsp' },
      { name: 'eggs', quantity: '2', unit: 'beaten' },
      { name: 'milk', quantity: '1/2', unit: 'cup' },
      { name: 'bread', quantity: '1', unit: 'slice, soaked in milk' },
    ],
    steps: [
      'Soak bread in milk. Brown beef with onion and curry powder.',
      'Add raisins, chutney, and soaked bread. Press into a baking dish.',
      'Beat eggs with remaining milk and pour over meat mixture.',
      'Bake at 350°F for 30 minutes until custard is set and golden.',
    ],
    tags: ['bobotie', 'south african', 'curry', 'bake', 'comfort food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 400,
      protein_g: 28,
      carbs_g: 18,
      fat_g: 24,
      fiber_g: 2,
      sugar_g: 6,
      sodium_mg: 520,
    },
  },
  {
    title: 'Egusi Soup',
    description: 'Rich Nigerian melon seed soup with leafy greens and assorted meat.',
    cuisine: 'African',
    prep_minutes: 20,
    cook_minutes: 40,
    servings: 6,
    calories: 380,
    ingredients: [
      { name: 'egusi (melon seeds)', quantity: '1', unit: 'cup, ground' },
      { name: 'beef chunks', quantity: '1', unit: 'lb' },
      { name: 'stockfish', quantity: '4', unit: 'oz' },
      { name: 'palm oil', quantity: '1/4', unit: 'cup' },
      { name: 'spinach', quantity: '2', unit: 'cups, chopped' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'crayfish', quantity: '2', unit: 'tbsp, ground' },
      { name: 'scotch bonnet pepper', quantity: '1', unit: 'whole' },
    ],
    steps: [
      'Boil beef and stockfish until tender, about 20 minutes.',
      'Heat palm oil and fry onion. Add ground egusi and stir for 2 minutes.',
      'Add meat with its broth, crayfish, and pepper. Simmer 15 minutes.',
      'Add spinach and cook 5 more minutes. Serve with fufu or pounded yam.',
    ],
    tags: ['egusi', 'nigerian', 'soup', 'melon seed', 'palm oil'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 380,
      protein_g: 26,
      carbs_g: 10,
      fat_g: 28,
      fiber_g: 3,
      sugar_g: 2,
      sodium_mg: 440,
    },
  },
  {
    title: 'Fufu and Egusi',
    description: 'Pounded cassava and plantain dough served with egusi soup for dipping.',
    cuisine: 'African',
    prep_minutes: 15,
    cook_minutes: 30,
    servings: 4,
    calories: 340,
    ingredients: [
      { name: 'cassava', quantity: '2', unit: 'lbs, peeled and cubed' },
      { name: 'plantain', quantity: '1', unit: 'green, cubed' },
      { name: 'water', quantity: '4', unit: 'cups' },
      { name: 'egusi soup', quantity: '4', unit: 'cups' },
    ],
    steps: [
      'Boil cassava and plantain until very tender, about 20 minutes.',
      'Drain and pound in a mortar until smooth and stretchy, or use a potato masher.',
      'Form into smooth balls and serve alongside egusi soup.',
      'Pinch fufu with fingers and dip into the soup.',
    ],
    tags: ['fufu', 'cassava', 'nigerian', 'side', 'traditional'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 340,
      protein_g: 4,
      carbs_g: 72,
      fat_g: 2,
      fiber_g: 4,
      sugar_g: 3,
      sodium_mg: 120,
    },
  },
  {
    title: 'Suya',
    description: 'Spicy West African grilled beef skewers coated in peanut-spice rub.',
    cuisine: 'African',
    prep_minutes: 20,
    cook_minutes: 10,
    servings: 4,
    calories: 320,
    ingredients: [
      { name: 'beef sirloin', quantity: '1', unit: 'lb, sliced thin' },
      { name: 'roasted peanuts', quantity: '1/2', unit: 'cup, ground' },
      { name: 'cayenne pepper', quantity: '1', unit: 'tbsp' },
      { name: 'ginger powder', quantity: '1', unit: 'tsp' },
      { name: 'onion powder', quantity: '1', unit: 'tsp' },
      { name: 'vegetable oil', quantity: '2', unit: 'tbsp' },
      { name: 'onion', quantity: '1', unit: 'sliced for garnish' },
    ],
    steps: [
      'Mix ground peanuts, cayenne, ginger, onion powder, and salt for suya spice.',
      'Coat beef strips in oil, then press suya spice onto both sides.',
      'Thread onto skewers and grill over high heat 3-4 minutes per side.',
      'Serve with sliced onion and extra suya spice on the side.',
    ],
    tags: ['suya', 'grilled', 'skewer', 'west african', 'peanut'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 34,
      carbs_g: 6,
      fat_g: 18,
      fiber_g: 2,
      sugar_g: 2,
      sodium_mg: 380,
    },
  },
  {
    title: 'Lamb Tagine with Apricots',
    description: 'Moroccan lamb tagine with dried apricots, almonds, and honey.',
    cuisine: 'African',
    prep_minutes: 20,
    cook_minutes: 120,
    servings: 6,
    calories: 450,
    ingredients: [
      { name: 'lamb shoulder', quantity: '2', unit: 'lbs, cubed' },
      { name: 'dried apricots', quantity: '1/2', unit: 'cup' },
      { name: 'almonds', quantity: '1/4', unit: 'cup, toasted' },
      { name: 'onion', quantity: '2', unit: 'large, diced' },
      { name: 'honey', quantity: '2', unit: 'tbsp' },
      { name: 'cinnamon', quantity: '1', unit: 'tsp' },
      { name: 'ginger', quantity: '1', unit: 'tsp, grated' },
      { name: 'saffron', quantity: '1', unit: 'pinch' },
    ],
    steps: [
      'Brown lamb in a tagine or Dutch oven. Add onion, ginger, cinnamon, and saffron.',
      'Add water to cover and simmer 90 minutes until lamb is tender.',
      'Add apricots and honey. Cook 20 more minutes until sauce is thick.',
      'Top with toasted almonds and serve with couscous.',
    ],
    tags: ['tagine', 'moroccan', 'lamb', 'apricot', 'sweet and savory'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 450,
      protein_g: 32,
      carbs_g: 22,
      fat_g: 26,
      fiber_g: 3,
      sugar_g: 12,
      sodium_mg: 380,
    },
  },
  {
    title: 'Peanut Soup',
    description: 'Creamy West African groundnut soup with chicken and vegetables.',
    cuisine: 'African',
    prep_minutes: 15,
    cook_minutes: 40,
    servings: 6,
    calories: 360,
    ingredients: [
      { name: 'chicken thighs', quantity: '1.5', unit: 'lbs' },
      { name: 'peanut butter', quantity: '1', unit: 'cup' },
      { name: 'tomato', quantity: '2', unit: 'diced' },
      { name: 'onion', quantity: '1', unit: 'large, diced' },
      { name: 'sweet potato', quantity: '1', unit: 'cubed' },
      { name: 'spinach', quantity: '2', unit: 'cups' },
      { name: 'ginger', quantity: '1', unit: 'tbsp, grated' },
      { name: 'chicken broth', quantity: '4', unit: 'cups' },
    ],
    steps: [
      'Brown chicken in a large pot. Add onion, ginger, and tomato. Cook 5 minutes.',
      'Add chicken broth and sweet potato. Simmer 20 minutes.',
      'Stir in peanut butter until dissolved. Add spinach and cook 5 minutes.',
      'Serve with rice or fufu.',
    ],
    tags: ['peanut soup', 'groundnut', 'west african', 'chicken', 'creamy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 360,
      protein_g: 28,
      carbs_g: 20,
      fat_g: 20,
      fiber_g: 4,
      sugar_g: 5,
      sodium_mg: 480,
    },
  },
  {
    title: 'Chakalaka',
    description: 'Spicy South African vegetable relish with beans, peppers, and curry spices.',
    cuisine: 'African',
    prep_minutes: 15,
    cook_minutes: 30,
    servings: 6,
    calories: 160,
    ingredients: [
      { name: 'baked beans', quantity: '1', unit: 'can' },
      { name: 'onion', quantity: '1', unit: 'large, diced' },
      { name: 'green bell pepper', quantity: '1', unit: 'diced' },
      { name: 'carrot', quantity: '2', unit: 'grated' },
      { name: 'curry powder', quantity: '1', unit: 'tbsp' },
      { name: 'tomato paste', quantity: '2', unit: 'tbsp' },
      { name: 'garlic', quantity: '3', unit: 'cloves, minced' },
      { name: 'chili flakes', quantity: '1/2', unit: 'tsp' },
    ],
    steps: [
      'Sauté onion, pepper, and carrot in oil until softened.',
      'Add garlic, curry powder, and chili flakes. Cook 1 minute.',
      'Add tomato paste and a splash of water. Simmer 10 minutes.',
      'Add baked beans and cook 10 more minutes. Serve with bread or pap.',
    ],
    tags: ['chakalaka', 'south african', 'relish', 'beans', 'vegan'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 160,
      protein_g: 8,
      carbs_g: 24,
      fat_g: 4,
      fiber_g: 6,
      sugar_g: 6,
      sodium_mg: 420,
    },
  },
  {
    title: 'Doro Wat (Spicy Chicken Stew)',
    description:
      'Ethiopian berbere-spiced chicken stew with hard-boiled eggs and caramelized onions.',
    cuisine: 'African',
    prep_minutes: 20,
    cook_minutes: 90,
    servings: 6,
    calories: 380,
    ingredients: [
      { name: 'chicken pieces', quantity: '3', unit: 'lbs' },
      { name: 'red onion', quantity: '5', unit: 'large, finely diced' },
      { name: 'berbere spice', quantity: '3', unit: 'tbsp' },
      { name: 'niter kibbeh', quantity: '1/4', unit: 'cup' },
      { name: 'garlic', quantity: '4', unit: 'cloves, minced' },
      { name: 'ginger', quantity: '1', unit: 'tbsp, grated' },
      { name: 'hard-boiled eggs', quantity: '4', unit: 'peeled' },
      { name: 'lime juice', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Cook onions in a dry pot over low heat until deeply caramelized, about 30 minutes.',
      'Add niter kibbeh, berbere, garlic, and ginger. Cook 5 minutes.',
      'Add chicken pieces and enough water to cover. Simmer 45 minutes.',
      'Add hard-boiled eggs and lime juice. Cook 10 more minutes. Serve with injera.',
    ],
    tags: ['doro wat', 'ethiopian', 'chicken', 'berbere', 'stew'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 380,
      protein_g: 32,
      carbs_g: 12,
      fat_g: 22,
      fiber_g: 2,
      sugar_g: 4,
      sodium_mg: 440,
    },
  },
  {
    title: 'Bunny Chow',
    description:
      'South African curry served in a hollowed-out bread loaf — a Durban street food classic.',
    cuisine: 'African',
    prep_minutes: 15,
    cook_minutes: 45,
    servings: 4,
    calories: 480,
    ingredients: [
      { name: 'white bread loaf', quantity: '1', unit: 'whole' },
      { name: 'chicken pieces', quantity: '1.5', unit: 'lbs' },
      { name: 'onion', quantity: '2', unit: 'diced' },
      { name: 'curry powder', quantity: '2', unit: 'tbsp' },
      { name: 'tomato', quantity: '2', unit: 'diced' },
      { name: 'potato', quantity: '2', unit: 'cubed' },
      { name: 'garlic', quantity: '3', unit: 'cloves' },
      { name: 'ginger', quantity: '1', unit: 'tbsp, grated' },
    ],
    steps: [
      'Cook chicken curry: brown chicken, add onion, garlic, ginger, curry powder, tomato, and potato. Simmer 35 minutes.',
      'Hollow out the bread loaf, removing the soft center to create a bowl.',
      'Fill the bread bowl with hot curry.',
      'Use the removed bread center to scoop the curry.',
    ],
    tags: ['bunny chow', 'south african', 'curry', 'bread', 'street food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 480,
      protein_g: 30,
      carbs_g: 48,
      fat_g: 18,
      fiber_g: 4,
      sugar_g: 4,
      sodium_mg: 620,
    },
  },
  {
    title: 'Thieboudienne',
    description: 'Senegalese fish and rice dish with vegetables in a rich tomato sauce.',
    cuisine: 'African',
    prep_minutes: 30,
    cook_minutes: 60,
    servings: 6,
    calories: 420,
    ingredients: [
      { name: 'white fish fillets', quantity: '1.5', unit: 'lbs' },
      { name: 'broken rice', quantity: '3', unit: 'cups' },
      { name: 'tomato paste', quantity: '4', unit: 'tbsp' },
      { name: 'cassava', quantity: '1', unit: 'cup, cubed' },
      { name: 'sweet potato', quantity: '1', unit: 'cubed' },
      { name: 'eggplant', quantity: '1', unit: 'cubed' },
      { name: 'onion', quantity: '2', unit: 'diced' },
      { name: 'tamarind', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Stuff fish with a mix of garlic, parsley, and chili. Fry until golden.',
      'Make sauce: cook onion and tomato paste with tamarind and fish stock.',
      'Add cassava, sweet potato, and eggplant to the sauce. Simmer 30 minutes.',
      'Cook rice separately, then serve fish and vegetables over rice with sauce.',
    ],
    tags: ['thieboudienne', 'senegalese', 'fish', 'rice', 'one-pot'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 30,
      carbs_g: 52,
      fat_g: 8,
      fiber_g: 4,
      sugar_g: 4,
      sodium_mg: 380,
    },
  },
  {
    title: 'Ugali and Sukuma Wiki',
    description: 'Kenyan cornmeal porridge served with braised collard greens and tomatoes.',
    cuisine: 'African',
    prep_minutes: 15,
    cook_minutes: 25,
    servings: 4,
    calories: 300,
    ingredients: [
      { name: 'cornmeal', quantity: '2', unit: 'cups' },
      { name: 'water', quantity: '4', unit: 'cups' },
      { name: 'collard greens', quantity: '4', unit: 'cups, chopped' },
      { name: 'tomato', quantity: '2', unit: 'diced' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'vegetable oil', quantity: '2', unit: 'tbsp' },
      { name: 'salt', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Bring water to boil. Slowly whisk in cornmeal, stirring constantly.',
      'Cook ugali 10-15 minutes, stirring vigorously, until thick and pulling from sides.',
      'Sauté onion in oil, add tomato and collard greens (sukuma wiki). Cook 10 minutes.',
      'Serve ugali in a mound alongside sukuma wiki.',
    ],
    tags: ['ugali', 'sukuma wiki', 'kenyan', 'cornmeal', 'vegan'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 300,
      protein_g: 8,
      carbs_g: 52,
      fat_g: 6,
      fiber_g: 6,
      sugar_g: 3,
      sodium_mg: 320,
    },
  },
  {
    title: 'Biltong',
    description:
      'South African dried cured beef with coriander, pepper, and vinegar — a protein snack.',
    cuisine: 'African',
    prep_minutes: 15,
    cook_minutes: 0,
    servings: 8,
    calories: 150,
    ingredients: [
      { name: 'beef silverside', quantity: '2', unit: 'lbs' },
      { name: 'coriander seeds', quantity: '2', unit: 'tbsp, crushed' },
      { name: 'black pepper', quantity: '1', unit: 'tbsp, coarsely ground' },
      { name: 'salt', quantity: '1/4', unit: 'cup' },
      { name: 'brown sugar', quantity: '2', unit: 'tbsp' },
      { name: 'vinegar', quantity: '1/2', unit: 'cup' },
    ],
    steps: [
      'Slice beef into strips along the grain, about 1 inch thick.',
      'Sprinkle vinegar over meat, then coat with salt, sugar, coriander, and pepper.',
      'Layer in a dish and refrigerate 12-24 hours, turning occasionally.',
      'Hang strips to air-dry in a cool, well-ventilated area for 3-5 days until firm.',
    ],
    tags: ['biltong', 'south african', 'beef', 'dried', 'snack'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 150,
      protein_g: 28,
      carbs_g: 2,
      fat_g: 4,
      fiber_g: 0,
      sugar_g: 1,
      sodium_mg: 820,
    },
  },
  {
    title: 'Piri Piri Chicken',
    description: 'Mozambican-Portuguese grilled chicken marinated in fiery piri piri chili sauce.',
    cuisine: 'African',
    prep_minutes: 15,
    cook_minutes: 35,
    servings: 4,
    calories: 380,
    ingredients: [
      { name: 'whole chicken', quantity: '1', unit: 'about 3 lbs, spatchcocked' },
      { name: 'piri piri peppers', quantity: '6', unit: 'whole' },
      { name: 'garlic', quantity: '4', unit: 'cloves' },
      { name: 'lemon juice', quantity: '3', unit: 'tbsp' },
      { name: 'olive oil', quantity: '1/4', unit: 'cup' },
      { name: 'paprika', quantity: '1', unit: 'tbsp' },
      { name: 'oregano', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Blend piri piri peppers, garlic, lemon juice, olive oil, paprika, and oregano into a sauce.',
      'Marinate chicken in the sauce for at least 2 hours or overnight.',
      'Grill over medium-high heat 15 minutes per side, basting with remaining sauce.',
      'Serve with grilled lemon halves and a side salad.',
    ],
    tags: ['piri piri', 'mozambican', 'grilled', 'chicken', 'spicy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 380,
      protein_g: 38,
      carbs_g: 4,
      fat_g: 24,
      fiber_g: 1,
      sugar_g: 1,
      sodium_mg: 420,
    },
  },
];

export const africanRecipes = generateCuisineRecipes(configs);
