import type { CuisineRecipeConfig } from './types';
import { generateCuisineRecipes } from './types';

const configs: CuisineRecipeConfig[] = [
  {
    title: 'Jollof Rice',
    description: 'One-pot West African tomato and pepper rice with smoky depth and spicy kick.',
    cuisine: 'African',
    prep_minutes: 20,
    cook_minutes: 45,
    servings: 6,
    calories: 350,
    ingredients: [
      { name: 'long grain rice', quantity: '3', unit: 'cups' },
      { name: 'tomato paste', quantity: '3', unit: 'tbsp' },
      { name: 'red bell pepper', quantity: '2', unit: 'blended' },
      { name: 'scotch bonnet pepper', quantity: '2', unit: 'whole' },
      { name: 'onion', quantity: '1', unit: 'large, diced' },
      { name: 'vegetable oil', quantity: '1/4', unit: 'cup' },
      { name: 'thyme', quantity: '1', unit: 'tsp' },
      { name: 'bay leaf', quantity: '2', unit: 'pieces' },
    ],
    steps: [
      'Blend red bell peppers and scotch bonnet peppers into a smooth paste.',
      'Heat oil and fry onion until translucent. Add tomato paste and pepper blend. Cook 15 minutes.',
      'Add thyme, bay leaf, and season with salt. Add washed rice and stir to coat.',
      'Add water to just above rice level. Cook covered on low heat for 25 minutes until rice is fluffy.',
    ],
    tags: ['jollof', 'rice', 'west african', 'one-pot', 'spicy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 350,
      protein_g: 6,
      carbs_g: 58,
      fat_g: 10,
      fiber_g: 3,
      sugar_g: 5,
      sodium_mg: 380,
    },
  },
  {
    title: 'Injera with Doro Wat',
    description: 'Ethiopian sour flatbread served with spicy chicken stew hard-boiled eggs.',
    cuisine: 'African',
    prep_minutes: 30,
    cook_minutes: 120,
    servings: 6,
    calories: 420,
    ingredients: [
      { name: 'teff flour', quantity: '2', unit: 'cups' },
      { name: 'water', quantity: '2', unit: 'cups' },
      { name: 'chicken thighs', quantity: '8', unit: 'pieces' },
      { name: 'red onion', quantity: '4', unit: 'large, finely diced' },
      { name: 'niter kibbeh', quantity: '1/4', unit: 'cup' },
      { name: 'berbere spice', quantity: '3', unit: 'tbsp' },
      { name: 'hard-boiled eggs', quantity: '4', unit: 'peeled' },
      { name: 'garlic', quantity: '4', unit: 'cloves, minced' },
    ],
    steps: [
      'Make injera batter: mix teff flour with water and let ferment 2-3 days. Cook like crepes on a hot griddle.',
      'Make doro wat: slowly cook onions without oil until deeply caramelized, about 40 minutes.',
      'Add niter kibbeh, berbere, and garlic. Cook 10 minutes. Add chicken and simmer 45 minutes.',
      'Add hard-boiled eggs in the last 10 minutes. Serve doro wat on injera.',
    ],
    tags: ['injera', 'doro wat', 'ethiopian', 'chicken', 'stew'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 28,
      carbs_g: 38,
      fat_g: 18,
      fiber_g: 5,
      sugar_g: 4,
      sodium_mg: 480,
    },
  },
  {
    title: 'Chicken Tagine',
    description: 'Moroccan slow-braised chicken with preserved lemons, olives, and warm spices.',
    cuisine: 'African',
    prep_minutes: 20,
    cook_minutes: 60,
    servings: 6,
    calories: 380,
    ingredients: [
      { name: 'chicken pieces', quantity: '3', unit: 'lbs' },
      { name: 'preserved lemon', quantity: '2', unit: 'quartered' },
      { name: 'green olives', quantity: '1/2', unit: 'cup' },
      { name: 'onion', quantity: '2', unit: 'large, sliced' },
      { name: 'ginger', quantity: '1', unit: 'tbsp, grated' },
      { name: 'saffron', quantity: '1', unit: 'pinch' },
      { name: 'cilantro', quantity: '1/4', unit: 'cup, chopped' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Brown chicken pieces in olive oil in a tagine or Dutch oven.',
      'Add onion, ginger, saffron, and enough water to cover. Simmer 40 minutes.',
      'Add preserved lemon and olives. Cook 15 more minutes.',
      'Garnish with cilantro and serve over couscous.',
    ],
    tags: ['tagine', 'moroccan', 'chicken', 'olive', 'preserved lemon'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 380,
      protein_g: 34,
      carbs_g: 8,
      fat_g: 24,
      fiber_g: 2,
      sugar_g: 2,
      sodium_mg: 520,
    },
  },
  {
    title: 'Bobotie',
    description: 'South African curried minced meat bake topped with a golden egg custard.',
    cuisine: 'African',
    prep_minutes: 25,
    cook_minutes: 45,
    servings: 6,
    calories: 400,
    ingredients: [
      { name: 'ground beef', quantity: '1.5', unit: 'lbs' },
      { name: 'onion', quantity: '1', unit: 'large, diced' },
      { name: 'curry powder', quantity: '2', unit: 'tbsp' },
      { name: 'raisins', quantity: '1/4', unit: 'cup' },
      { name: 'chutney', quantity: '2', unit: 'tbsp' },
      { name: 'eggs', quantity: '2', unit: 'beaten' },
      { name: 'milk', quantity: '1/2', unit: 'cup' },
      { name: 'bread', quantity: '1', unit: 'slice, soaked in milk' },
    ],
    steps: [
      'Soak bread in milk. Brown beef with onion and curry powder.',
      'Add raisins, chutney, and soaked bread. Press into a baking dish.',
      'Beat eggs with remaining milk and pour over meat mixture.',
      'Bake at 350°F for 30 minutes until custard is set and golden.',
    ],
    tags: ['bobotie', 'south african', 'curry', 'bake', 'comfort food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 400,
      protein_g: 28,
      carbs_g: 18,
      fat_g: 24,
      fiber_g: 2,
      sugar_g: 6,
      sodium_mg: 520,
    },
  },
  {
    title: 'Egusi Soup',
    description: 'Rich Nigerian melon seed soup with leafy greens and assorted meat.',
    cuisine: 'African',
    prep_minutes: 20,
    cook_minutes: 40,
    servings: 6,
    calories: 380,
    ingredients: [
      { name: 'egusi (melon seeds)', quantity: '1', unit: 'cup, ground' },
      { name: 'beef chunks', quantity: '1', unit: 'lb' },
      { name: 'stockfish', quantity: '4', unit: 'oz' },
      { name: 'palm oil', quantity: '1/4', unit: 'cup' },
      { name: 'spinach', quantity: '2', unit: 'cups, chopped' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'crayfish', quantity: '2', unit: 'tbsp, ground' },
      { name: 'scotch bonnet pepper', quantity: '1', unit: 'whole' },
    ],
    steps: [
      'Boil beef and stockfish until tender, about 20 minutes.',
      'Heat palm oil and fry onion. Add ground egusi and stir for 2 minutes.',
      'Add meat with its broth, crayfish, and pepper. Simmer 15 minutes.',
      'Add spinach and cook 5 more minutes. Serve with fufu or pounded yam.',
    ],
    tags: ['egusi', 'nigerian', 'soup', 'melon seed', 'palm oil'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 380,
      protein_g: 26,
      carbs_g: 10,
      fat_g: 28,
      fiber_g: 3,
      sugar_g: 2,
      sodium_mg: 440,
    },
  },
  {
    title: 'Fufu and Egusi',
    description: 'Pounded cassava and plantain dough served with egusi soup for dipping.',
    cuisine: 'African',
    prep_minutes: 15,
    cook_minutes: 30,
    servings: 4,
    calories: 340,
    ingredients: [
      { name: 'cassava', quantity: '2', unit: 'lbs, peeled and cubed' },
      { name: 'plantain', quantity: '1', unit: 'green, cubed' },
      { name: 'water', quantity: '4', unit: 'cups' },
      { name: 'egusi soup', quantity: '4', unit: 'cups' },
    ],
    steps: [
      'Boil cassava and plantain until very tender, about 20 minutes.',
      'Drain and pound in a mortar until smooth and stretchy, or use a potato masher.',
      'Form into smooth balls and serve alongside egusi soup.',
      'Pinch fufu with fingers and dip into the soup.',
    ],
    tags: ['fufu', 'cassava', 'nigerian', 'side', 'traditional'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 340,
      protein_g: 4,
      carbs_g: 72,
      fat_g: 2,
      fiber_g: 4,
      sugar_g: 3,
      sodium_mg: 120,
    },
  },
  {
    title: 'Suya',
    description: 'Spicy West African grilled beef skewers coated in peanut-spice rub.',
    cuisine: 'African',
    prep_minutes: 20,
    cook_minutes: 10,
    servings: 4,
    calories: 320,
    ingredients: [
      { name: 'beef sirloin', quantity: '1', unit: 'lb, sliced thin' },
      { name: 'roasted peanuts', quantity: '1/2', unit: 'cup, ground' },
      { name: 'cayenne pepper', quantity: '1', unit: 'tbsp' },
      { name: 'ginger powder', quantity: '1', unit: 'tsp' },
      { name: 'onion powder', quantity: '1', unit: 'tsp' },
      { name: 'vegetable oil', quantity: '2', unit: 'tbsp' },
      { name: 'onion', quantity: '1', unit: 'sliced for garnish' },
    ],
    steps: [
      'Mix ground peanuts, cayenne, ginger, onion powder, and salt for suya spice.',
      'Coat beef strips in oil, then press suya spice onto both sides.',
      'Thread onto skewers and grill over high heat 3-4 minutes per side.',
      'Serve with sliced onion and extra suya spice on the side.',
    ],
    tags: ['suya', 'grilled', 'skewer', 'west african', 'peanut'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 34,
      carbs_g: 6,
      fat_g: 18,
      fiber_g: 2,
      sugar_g: 2,
      sodium_mg: 380,
    },
  },
  {
    title: 'Lamb Tagine with Apricots',
    description: 'Moroccan lamb tagine with dried apricots, almonds, and honey.',
    cuisine: 'African',
    prep_minutes: 20,
    cook_minutes: 120,
    servings: 6,
    calories: 450,
    ingredients: [
      { name: 'lamb shoulder', quantity: '2', unit: 'lbs, cubed' },
      { name: 'dried apricots', quantity: '1/2', unit: 'cup' },
      { name: 'almonds', quantity: '1/4', unit: 'cup, toasted' },
      { name: 'onion', quantity: '2', unit: 'large, diced' },
      { name: 'honey', quantity: '2', unit: 'tbsp' },
      { name: 'cinnamon', quantity: '1', unit: 'tsp' },
      { name: 'ginger', quantity: '1', unit: 'tsp, grated' },
      { name: 'saffron', quantity: '1', unit: 'pinch' },
    ],
    steps: [
      'Brown lamb in a tagine or Dutch oven. Add onion, ginger, cinnamon, and saffron.',
      'Add water to cover and simmer 90 minutes until lamb is tender.',
      'Add apricots and honey. Cook 20 more minutes until sauce is thick.',
      'Top with toasted almonds and serve with couscous.',
    ],
    tags: ['tagine', 'moroccan', 'lamb', 'apricot', 'sweet and savory'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 450,
      protein_g: 32,
      carbs_g: 22,
      fat_g: 26,
      fiber_g: 3,
      sugar_g: 12,
      sodium_mg: 380,
    },
  },
  {
    title: 'Peanut Soup',
    description: 'Creamy West African groundnut soup with chicken and vegetables.',
    cuisine: 'African',
    prep_minutes: 15,
    cook_minutes: 40,
    servings: 6,
    calories: 360,
    ingredients: [
      { name: 'chicken thighs', quantity: '1.5', unit: 'lbs' },
      { name: 'peanut butter', quantity: '1', unit: 'cup' },
      { name: 'tomato', quantity: '2', unit: 'diced' },
      { name: 'onion', quantity: '1', unit: 'large, diced' },
      { name: 'sweet potato', quantity: '1', unit: 'cubed' },
      { name: 'spinach', quantity: '2', unit: 'cups' },
      { name: 'ginger', quantity: '1', unit: 'tbsp, grated' },
      { name: 'chicken broth', quantity: '4', unit: 'cups' },
    ],
    steps: [
      'Brown chicken in a large pot. Add onion, ginger, and tomato. Cook 5 minutes.',
      'Add chicken broth and sweet potato. Simmer 20 minutes.',
      'Stir in peanut butter until dissolved. Add spinach and cook 5 minutes.',
      'Serve with rice or fufu.',
    ],
    tags: ['peanut soup', 'groundnut', 'west african', 'chicken', 'creamy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 360,
      protein_g: 28,
      carbs_g: 20,
      fat_g: 20,
      fiber_g: 4,
      sugar_g: 5,
      sodium_mg: 480,
    },
  },
  {
    title: 'Chakalaka',
    description: 'Spicy South African vegetable relish with beans, peppers, and curry spices.',
    cuisine: 'African',
    prep_minutes: 15,
    cook_minutes: 30,
    servings: 6,
    calories: 160,
    ingredients: [
      { name: 'baked beans', quantity: '1', unit: 'can' },
      { name: 'onion', quantity: '1', unit: 'large, diced' },
      { name: 'green bell pepper', quantity: '1', unit: 'diced' },
      { name: 'carrot', quantity: '2', unit: 'grated' },
      { name: 'curry powder', quantity: '1', unit: 'tbsp' },
      { name: 'tomato paste', quantity: '2', unit: 'tbsp' },
      { name: 'garlic', quantity: '3', unit: 'cloves, minced' },
      { name: 'chili flakes', quantity: '1/2', unit: 'tsp' },
    ],
    steps: [
      'Sauté onion, pepper, and carrot in oil until softened.',
      'Add garlic, curry powder, and chili flakes. Cook 1 minute.',
      'Add tomato paste and a splash of water. Simmer 10 minutes.',
      'Add baked beans and cook 10 more minutes. Serve with bread or pap.',
    ],
    tags: ['chakalaka', 'south african', 'relish', 'beans', 'vegan'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 160,
      protein_g: 8,
      carbs_g: 24,
      fat_g: 4,
      fiber_g: 6,
      sugar_g: 6,
      sodium_mg: 420,
    },
  },
  {
    title: 'Doro Wat (Spicy Chicken Stew)',
    description:
      'Ethiopian berbere-spiced chicken stew with hard-boiled eggs and caramelized onions.',
    cuisine: 'African',
    prep_minutes: 20,
    cook_minutes: 90,
    servings: 6,
    calories: 380,
    ingredients: [
      { name: 'chicken pieces', quantity: '3', unit: 'lbs' },
      { name: 'red onion', quantity: '5', unit: 'large, finely diced' },
      { name: 'berbere spice', quantity: '3', unit: 'tbsp' },
      { name: 'niter kibbeh', quantity: '1/4', unit: 'cup' },
      { name: 'garlic', quantity: '4', unit: 'cloves, minced' },
      { name: 'ginger', quantity: '1', unit: 'tbsp, grated' },
      { name: 'hard-boiled eggs', quantity: '4', unit: 'peeled' },
      { name: 'lime juice', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Cook onions in a dry pot over low heat until deeply caramelized, about 30 minutes.',
      'Add niter kibbeh, berbere, garlic, and ginger. Cook 5 minutes.',
      'Add chicken pieces and enough water to cover. Simmer 45 minutes.',
      'Add hard-boiled eggs and lime juice. Cook 10 more minutes. Serve with injera.',
    ],
    tags: ['doro wat', 'ethiopian', 'chicken', 'berbere', 'stew'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 380,
      protein_g: 32,
      carbs_g: 12,
      fat_g: 22,
      fiber_g: 2,
      sugar_g: 4,
      sodium_mg: 440,
    },
  },
  {
    title: 'Bunny Chow',
    description:
      'South African curry served in a hollowed-out bread loaf — a Durban street food classic.',
    cuisine: 'African',
    prep_minutes: 15,
    cook_minutes: 45,
    servings: 4,
    calories: 480,
    ingredients: [
      { name: 'white bread loaf', quantity: '1', unit: 'whole' },
      { name: 'chicken pieces', quantity: '1.5', unit: 'lbs' },
      { name: 'onion', quantity: '2', unit: 'diced' },
      { name: 'curry powder', quantity: '2', unit: 'tbsp' },
      { name: 'tomato', quantity: '2', unit: 'diced' },
      { name: 'potato', quantity: '2', unit: 'cubed' },
      { name: 'garlic', quantity: '3', unit: 'cloves' },
      { name: 'ginger', quantity: '1', unit: 'tbsp, grated' },
    ],
    steps: [
      'Cook chicken curry: brown chicken, add onion, garlic, ginger, curry powder, tomato, and potato. Simmer 35 minutes.',
      'Hollow out the bread loaf, removing the soft center to create a bowl.',
      'Fill the bread bowl with hot curry.',
      'Use the removed bread center to scoop the curry.',
    ],
    tags: ['bunny chow', 'south african', 'curry', 'bread', 'street food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 480,
      protein_g: 30,
      carbs_g: 48,
      fat_g: 18,
      fiber_g: 4,
      sugar_g: 4,
      sodium_mg: 620,
    },
  },
  {
    title: 'Thieboudienne',
    description: 'Senegalese fish and rice dish with vegetables in a rich tomato sauce.',
    cuisine: 'African',
    prep_minutes: 30,
    cook_minutes: 60,
    servings: 6,
    calories: 420,
    ingredients: [
      { name: 'white fish fillets', quantity: '1.5', unit: 'lbs' },
      { name: 'broken rice', quantity: '3', unit: 'cups' },
      { name: 'tomato paste', quantity: '4', unit: 'tbsp' },
      { name: 'cassava', quantity: '1', unit: 'cup, cubed' },
      { name: 'sweet potato', quantity: '1', unit: 'cubed' },
      { name: 'eggplant', quantity: '1', unit: 'cubed' },
      { name: 'onion', quantity: '2', unit: 'diced' },
      { name: 'tamarind', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Stuff fish with a mix of garlic, parsley, and chili. Fry until golden.',
      'Make sauce: cook onion and tomato paste with tamarind and fish stock.',
      'Add cassava, sweet potato, and eggplant to the sauce. Simmer 30 minutes.',
      'Cook rice separately, then serve fish and vegetables over rice with sauce.',
    ],
    tags: ['thieboudienne', 'senegalese', 'fish', 'rice', 'one-pot'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 30,
      carbs_g: 52,
      fat_g: 8,
      fiber_g: 4,
      sugar_g: 4,
      sodium_mg: 380,
    },
  },
  {
    title: 'Ugali and Sukuma Wiki',
    description: 'Kenyan cornmeal porridge served with braised collard greens and tomatoes.',
    cuisine: 'African',
    prep_minutes: 15,
    cook_minutes: 25,
    servings: 4,
    calories: 300,
    ingredients: [
      { name: 'cornmeal', quantity: '2', unit: 'cups' },
      { name: 'water', quantity: '4', unit: 'cups' },
      { name: 'collard greens', quantity: '4', unit: 'cups, chopped' },
      { name: 'tomato', quantity: '2', unit: 'diced' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'vegetable oil', quantity: '2', unit: 'tbsp' },
      { name: 'salt', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Bring water to boil. Slowly whisk in cornmeal, stirring constantly.',
      'Cook ugali 10-15 minutes, stirring vigorously, until thick and pulling from sides.',
      'Sauté onion in oil, add tomato and collard greens (sukuma wiki). Cook 10 minutes.',
      'Serve ugali in a mound alongside sukuma wiki.',
    ],
    tags: ['ugali', 'sukuma wiki', 'kenyan', 'cornmeal', 'vegan'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 300,
      protein_g: 8,
      carbs_g: 52,
      fat_g: 6,
      fiber_g: 6,
      sugar_g: 3,
      sodium_mg: 320,
    },
  },
  {
    title: 'Biltong',
    description:
      'South African dried cured beef with coriander, pepper, and vinegar — a protein snack.',
    cuisine: 'African',
    prep_minutes: 15,
    cook_minutes: 0,
    servings: 8,
    calories: 150,
    ingredients: [
      { name: 'beef silverside', quantity: '2', unit: 'lbs' },
      { name: 'coriander seeds', quantity: '2', unit: 'tbsp, crushed' },
      { name: 'black pepper', quantity: '1', unit: 'tbsp, coarsely ground' },
      { name: 'salt', quantity: '1/4', unit: 'cup' },
      { name: 'brown sugar', quantity: '2', unit: 'tbsp' },
      { name: 'vinegar', quantity: '1/2', unit: 'cup' },
    ],
    steps: [
      'Slice beef into strips along the grain, about 1 inch thick.',
      'Sprinkle vinegar over meat, then coat with salt, sugar, coriander, and pepper.',
      'Layer in a dish and refrigerate 12-24 hours, turning occasionally.',
      'Hang strips to air-dry in a cool, well-ventilated area for 3-5 days until firm.',
    ],
    tags: ['biltong', 'south african', 'beef', 'dried', 'snack'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 150,
      protein_g: 28,
      carbs_g: 2,
      fat_g: 4,
      fiber_g: 0,
      sugar_g: 1,
      sodium_mg: 820,
    },
  },
  {
    title: 'Piri Piri Chicken',
    description: 'Mozambican-Portuguese grilled chicken marinated in fiery piri piri chili sauce.',
    cuisine: 'African',
    prep_minutes: 15,
    cook_minutes: 35,
    servings: 4,
    calories: 380,
    ingredients: [
      { name: 'whole chicken', quantity: '1', unit: 'about 3 lbs, spatchcocked' },
      { name: 'piri piri peppers', quantity: '6', unit: 'whole' },
      { name: 'garlic', quantity: '4', unit: 'cloves' },
      { name: 'lemon juice', quantity: '3', unit: 'tbsp' },
      { name: 'olive oil', quantity: '1/4', unit: 'cup' },
      { name: 'paprika', quantity: '1', unit: 'tbsp' },
      { name: 'oregano', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Blend piri piri peppers, garlic, lemon juice, olive oil, paprika, and oregano into a sauce.',
      'Marinate chicken in the sauce for at least 2 hours or overnight.',
      'Grill over medium-high heat 15 minutes per side, basting with remaining sauce.',
      'Serve with grilled lemon halves and a side salad.',
    ],
    tags: ['piri piri', 'mozambican', 'grilled', 'chicken', 'spicy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 380,
      protein_g: 38,
      carbs_g: 4,
      fat_g: 24,
      fiber_g: 1,
      sugar_g: 1,
      sodium_mg: 420,
    },
  },
];

export const africanRecipes = generateCuisineRecipes(configs);

// ── Additional African recipes ──────────────────────────────────────────────

const additionalAfricanConfigs: CuisineRecipeConfig[] = [
  {
    title: 'Suya',
    description: 'Spicy West African grilled meat skewers coated in peanut-chili spice blend.',
    cuisine: 'African',
    prep_minutes: 20,
    cook_minutes: 10,
    servings: 6,
    calories: 240,
    ingredients: [
      { name: 'beef', quantity: '1', unit: 'lb, cubed' },
      { name: 'peanut powder', quantity: '1/2', unit: 'cup' },
      { name: 'cayenne', quantity: '1', unit: 'tsp' },
      { name: 'ginger', quantity: '1', unit: 'tsp, ground' },
      { name: 'onion powder', quantity: '1', unit: 'tsp' },
      { name: 'oil', quantity: '1', unit: 'tbsp' },
      { name: 'onion', quantity: '1', unit: 'sliced' },
    ],
    steps: [
      'Mix peanut powder with cayenne, ginger, onion powder, and salt.',
      'Coat beef cubes in the spice blend.',
      'Thread onto skewers.',
      'Grill over hot charcoal until charred and cooked.',
      'Serve with sliced onion and extra suya spice.',
    ],
    tags: ['african', 'grilled', 'beef', 'spicy', 'street-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 240,
      protein_g: 26,
      carbs_g: 4,
      fat_g: 12,
      fiber_g: 1,
      sugar_g: 1,
      sodium_mg: 380,
    },
  },
  {
    title: 'Chapati',
    description: 'East African flatbread cooked on a griddle, perfect for scooping stews.',
    cuisine: 'African',
    prep_minutes: 15,
    cook_minutes: 10,
    servings: 8,
    calories: 140,
    ingredients: [
      { name: 'flour', quantity: '2', unit: 'cups' },
      { name: 'water', quantity: '3/4', unit: 'cup' },
      { name: 'oil', quantity: '2', unit: 'tbsp' },
      { name: 'salt', quantity: '1/2', unit: 'tsp' },
    ],
    steps: [
      'Mix flour, salt, oil, and water into a soft dough.',
      'Rest 15 minutes.',
      'Roll into thin rounds.',
      'Cook on a hot griddle until puffed and spotted.',
      'Brush with oil or ghee.',
      'Serve with any stew or curry.',
    ],
    tags: ['african', 'flatbread', 'east-african', 'vegan', 'staple'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 140,
      protein_g: 3,
      carbs_g: 24,
      fat_g: 3,
      fiber_g: 1,
      sugar_g: 0,
      sodium_mg: 180,
    },
  },
  {
    title: 'Doro Wat',
    description: 'Ethiopian spicy chicken stew with berbere, served with injera.',
    cuisine: 'African',
    prep_minutes: 15,
    cook_minutes: 90,
    servings: 6,
    calories: 320,
    ingredients: [
      { name: 'chicken', quantity: '1', unit: 'whole, cut up' },
      { name: 'berbere spice', quantity: '2', unit: 'tbsp' },
      { name: 'onion', quantity: '5', unit: 'large, finely diced' },
      { name: 'butter (niter kibbeh)', quantity: '3', unit: 'tbsp' },
      { name: 'garlic', quantity: '4', unit: 'cloves' },
      { name: 'ginger', quantity: '1', unit: 'tbsp, grated' },
      { name: 'hard-boiled egg', quantity: '6', unit: 'pieces' },
    ],
    steps: [
      'Cook onions without oil until deeply caramelized, about 30 minutes.',
      'Add niter kibbeh, berbere, garlic, and ginger.',
      'Add chicken pieces and water. Simmer 1 hour.',
      'Add hard-boiled eggs.',
      'Simmer 15 more minutes.',
      'Serve on injera bread.',
    ],
    tags: ['african', 'ethiopian', 'chicken', 'spicy', 'stew'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 320,
      protein_g: 28,
      carbs_g: 10,
      fat_g: 18,
      fiber_g: 2,
      sugar_g: 4,
      sodium_mg: 580,
    },
  },
  {
    title: 'Peanut Soup',
    description: 'West African peanut soup with chicken, sweet potato, and spinach.',
    cuisine: 'African',
    prep_minutes: 15,
    cook_minutes: 30,
    servings: 6,
    calories: 340,
    ingredients: [
      { name: 'peanut butter', quantity: '1/2', unit: 'cup' },
      { name: 'chicken thigh', quantity: '1', unit: 'lb' },
      { name: 'sweet potato', quantity: '2', unit: 'cubed' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'tomato paste', quantity: '2', unit: 'tbsp' },
      { name: 'spinach', quantity: '2', unit: 'cups' },
      { name: 'chicken broth', quantity: '4', unit: 'cups' },
    ],
    steps: [
      'Brown chicken and set aside.',
      'Sauté onion, add tomato paste and peanut butter.',
      'Add broth, sweet potato, and chicken.',
      'Simmer 25 minutes until sweet potato is tender.',
      'Add spinach and stir.',
      'Serve with rice or fufu.',
    ],
    tags: ['african', 'soup', 'peanut', 'chicken', 'west-african'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 340,
      protein_g: 24,
      carbs_g: 22,
      fat_g: 18,
      fiber_g: 4,
      sugar_g: 4,
      sodium_mg: 580,
    },
  },
  {
    title: 'Ugali',
    description:
      'East African maize porridge — a staple food served with sukuma wiki or meat stew.',
    cuisine: 'African',
    prep_minutes: 5,
    cook_minutes: 15,
    servings: 6,
    calories: 180,
    ingredients: [
      { name: 'cornmeal (fine)', quantity: '2', unit: 'cups' },
      { name: 'water', quantity: '4', unit: 'cups' },
      { name: 'salt', quantity: '1/2', unit: 'tsp' },
    ],
    steps: [
      'Bring salted water to a boil.',
      'Slowly add cornmeal, stirring constantly.',
      'Reduce heat and stir vigorously until thick and pulling away from the pot.',
      'Form into a mound.',
      'Serve with sukuma wiki (collard greens) or meat stew.',
      'Pinch off pieces with your right hand to eat.',
    ],
    tags: ['african', 'porridge', 'maize', 'east-african', 'staple'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 180,
      protein_g: 4,
      carbs_g: 38,
      fat_g: 1,
      fiber_g: 2,
      sugar_g: 0,
      sodium_mg: 180,
    },
  },
  {
    title: 'Bunny Chow',
    description:
      'South African curry served in a hollowed-out bread loaf — a Durban street-food icon.',
    cuisine: 'African',
    prep_minutes: 15,
    cook_minutes: 30,
    servings: 4,
    calories: 420,
    ingredients: [
      { name: 'bread loaf', quantity: '1', unit: 'large, hollowed' },
      { name: 'chicken', quantity: '1', unit: 'lb, cubed' },
      { name: 'curry powder', quantity: '2', unit: 'tbsp' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'tomato', quantity: '2', unit: 'diced' },
      { name: 'potato', quantity: '1', unit: 'cubed' },
      { name: 'garlic', quantity: '3', unit: 'cloves' },
    ],
    steps: [
      'Sauté onion and garlic. Add curry powder.',
      'Add chicken and brown.',
      'Add tomato, potato, and water. Simmer 25 minutes.',
      'Hollow out the bread loaf, keeping the crust intact.',
      'Fill the bread cavity with curry.',
      'Use the scooped-out bread to scoop the curry.',
    ],
    tags: ['african', 'south-african', 'curry', 'bread', 'street-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 22,
      carbs_g: 48,
      fat_g: 12,
      fiber_g: 3,
      sugar_g: 4,
      sodium_mg: 680,
    },
  },
  {
    title: 'Sambusa',
    description: 'East African fried pastry triangles filled with spiced meat or lentils.',
    cuisine: 'African',
    prep_minutes: 25,
    cook_minutes: 10,
    servings: 12,
    calories: 160,
    ingredients: [
      { name: 'wrappers', quantity: '24', unit: 'pieces' },
      { name: 'ground beef', quantity: '1/2', unit: 'lb' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'cumin', quantity: '1', unit: 'tsp' },
      { name: 'cardamom', quantity: '1/4', unit: 'tsp' },
      { name: 'green onion', quantity: '3', unit: 'minced' },
      { name: 'oil', quantity: '2', unit: 'cups, for frying' },
    ],
    steps: [
      'Sauté onion and beef with cumin and cardamom.',
      'Add green onion and cool.',
      'Fill wrappers, fold into triangles, seal with flour paste.',
      'Deep fry at 350°F until golden.',
      'Drain on paper towels.',
      'Serve with hot sauce or chutney.',
    ],
    tags: ['african', 'east-african', 'fried', 'pastry', 'appetizer'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 160,
      protein_g: 6,
      carbs_g: 16,
      fat_g: 8,
      fiber_g: 1,
      sugar_g: 1,
      sodium_mg: 280,
    },
  },
  {
    title: 'Thieboudienne',
    description:
      'Senegalese fish and rice dish with vegetables in a tomato sauce — the national dish.',
    cuisine: 'African',
    prep_minutes: 20,
    cook_minutes: 45,
    servings: 6,
    calories: 380,
    ingredients: [
      { name: 'white fish', quantity: '1.5', unit: 'lb, steaks' },
      { name: 'rice', quantity: '2', unit: 'cups' },
      { name: 'tomato paste', quantity: '3', unit: 'tbsp' },
      { name: 'cassava', quantity: '1', unit: 'cup, chunked' },
      { name: 'sweet potato', quantity: '1', unit: 'chunked' },
      { name: 'eggplant', quantity: '1', unit: 'chunked' },
      { name: 'tamarind', quantity: '1', unit: 'tbsp' },
      { name: 'fish sauce', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Stuff fish with a parsley-garlic-chili paste.',
      'Make a tomato sauce with paste, tamarind, and fish sauce.',
      'Add vegetables and cook until tender.',
      'Cook rice in the tomato sauce.',
      'Serve rice with fish and vegetables on top.',
      'The bottom rice (xoon) should be slightly crispy.',
    ],
    tags: ['african', 'senegalese', 'fish', 'rice', 'national-dish'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 28,
      carbs_g: 42,
      fat_g: 8,
      fiber_g: 3,
      sugar_g: 4,
      sodium_mg: 580,
    },
  },
  {
    title: 'Pilau',
    description:
      'East African spiced rice with meat, cooked in a fragrant broth with cardamom and cloves.',
    cuisine: 'African',
    prep_minutes: 15,
    cook_minutes: 40,
    servings: 6,
    calories: 380,
    ingredients: [
      { name: 'basmati rice', quantity: '2', unit: 'cups' },
      { name: 'beef', quantity: '1', unit: 'lb, cubed' },
      { name: 'onion', quantity: '2', unit: 'sliced' },
      { name: 'cardamom', quantity: '4', unit: 'pods' },
      { name: 'cloves', quantity: '4', unit: 'whole' },
      { name: 'cinnamon stick', quantity: '1', unit: 'small' },
      { name: 'cumin', quantity: '1', unit: 'tsp' },
      { name: 'beef broth', quantity: '3', unit: 'cups' },
    ],
    steps: [
      'Brown beef with onion, cardamom, cloves, and cinnamon.',
      'Add broth and simmer until beef is tender.',
      'Add rice and cumin.',
      'Cover and cook on low until rice is done.',
      'Fluff with a fork.',
      'Serve with kachumbari (tomato-onion salad).',
    ],
    tags: ['african', 'east-african', 'rice', 'spiced', 'beef'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 22,
      carbs_g: 44,
      fat_g: 10,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 480,
    },
  },
  {
    title: 'Biltong',
    description: 'South African dried cured meat snack with coriander, pepper, and vinegar.',
    cuisine: 'African',
    prep_minutes: 15,
    cook_minutes: 0,
    servings: 8,
    calories: 160,
    ingredients: [
      { name: 'beef (silverside)', quantity: '2', unit: 'lb' },
      { name: 'coriander seeds', quantity: '2', unit: 'tbsp, crushed' },
      { name: 'black pepper', quantity: '1', unit: 'tbsp, coarse' },
      { name: 'salt', quantity: '1/4', unit: 'cup' },
      { name: 'brown sugar', quantity: '1', unit: 'tbsp' },
      { name: 'vinegar', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Slice beef into thick strips along the grain.',
      'Sprinkle with vinegar, salt, sugar, coriander, and pepper.',
      'Marinate 12-24 hours.',
      'Hang to dry in a well-ventilated area for 3-5 days.',
      'Slice thin against the grain to eat.',
      'Can also be dried in a dehydrator or oven on low.',
    ],
    tags: ['african', 'south-african', 'snack', 'dried-meat', 'cured'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 160,
      protein_g: 28,
      carbs_g: 2,
      fat_g: 4,
      fiber_g: 0,
      sugar_g: 1,
      sodium_mg: 1200,
    },
  },
];

export const africanAdditionalRecipes = generateCuisineRecipes(additionalAfricanConfigs);
