import type { CuisineRecipeConfig } from './types';
import { generateCuisineRecipes } from './types';

const configs: CuisineRecipeConfig[] = [
  {
    title: 'Classic Cheeseburger',
    description:
      'Juicy grilled beef patty with melted cheddar, lettuce, tomato, and special sauce on a brioche bun.',
    cuisine: 'American',
    prep_minutes: 15,
    cook_minutes: 8,
    servings: 4,
    calories: 520,
    ingredients: [
      { name: 'ground beef', quantity: '1', unit: 'lb (80/20)' },
      { name: 'cheddar cheese', quantity: '4', unit: 'slices' },
      { name: 'brioche buns', quantity: '4', unit: 'pieces' },
      { name: 'lettuce', quantity: '4', unit: 'leaves' },
      { name: 'tomato', quantity: '1', unit: 'sliced' },
      { name: 'onion', quantity: '1/2', unit: 'sliced' },
      { name: 'pickles', quantity: '8', unit: 'slices' },
      { name: 'ketchup', quantity: '2', unit: 'tbsp' },
      { name: 'mustard', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Form beef into 4 patties, make a thumbprint in the center. Season with salt and pepper.',
      'Grill over high heat for 3-4 minutes per side for medium.',
      'Add cheddar cheese in the last minute, cover to melt.',
      'Toast brioche buns on the grill.',
      'Assemble: bun, lettuce, patty, tomato, onion, pickles, sauces.',
      'Serve with fries.',
    ],
    tags: ['american', 'burger', 'beef', 'grilled', 'classic'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 520,
      protein_g: 32,
      carbs_g: 32,
      fat_g: 28,
      fiber_g: 2,
      sugar_g: 6,
      sodium_mg: 820,
    },
  },
  {
    title: 'Mac and Cheese',
    description:
      'Creamy baked elbow macaroni in a rich cheddar-béchamel sauce with a crispy breadcrumb top.',
    cuisine: 'American',
    prep_minutes: 15,
    cook_minutes: 25,
    servings: 6,
    calories: 420,
    ingredients: [
      { name: 'elbow macaroni', quantity: '1', unit: 'lb' },
      { name: 'cheddar cheese', quantity: '2', unit: 'cups, shredded' },
      { name: 'butter', quantity: '3', unit: 'tbsp' },
      { name: 'flour', quantity: '3', unit: 'tbsp' },
      { name: 'milk', quantity: '3', unit: 'cups' },
      { name: 'breadcrumbs', quantity: '1/2', unit: 'cup' },
      { name: 'mustard powder', quantity: '1/2', unit: 'tsp' },
      { name: 'paprika', quantity: '1/4', unit: 'tsp' },
    ],
    steps: [
      'Cook macaroni until just al dente. Drain.',
      'Make roux: melt butter, add flour, cook 1 minute. Whisk in milk until thick.',
      'Add mustard powder and most of the cheddar. Stir until melted.',
      'Combine sauce with macaroni. Pour into a baking dish.',
      'Top with remaining cheese, breadcrumbs, and paprika.',
      'Bake at 375°F for 20 minutes until bubbly and golden.',
    ],
    tags: ['american', 'pasta', 'cheese', 'comfort-food', 'baked'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 18,
      carbs_g: 42,
      fat_g: 20,
      fiber_g: 2,
      sugar_g: 4,
      sodium_mg: 680,
    },
  },
  {
    title: 'BBQ Pulled Pork',
    description: 'Slow-smoked pork shoulder shredded and tossed in tangy, sweet barbecue sauce.',
    cuisine: 'American',
    prep_minutes: 15,
    cook_minutes: 480,
    servings: 8,
    calories: 380,
    ingredients: [
      { name: 'pork shoulder', quantity: '4', unit: 'lb' },
      { name: 'BBQ sauce', quantity: '1.5', unit: 'cups' },
      { name: 'apple cider vinegar', quantity: '2', unit: 'tbsp' },
      { name: 'brown sugar', quantity: '2', unit: 'tbsp' },
      { name: 'paprika', quantity: '1', unit: 'tbsp' },
      { name: 'garlic powder', quantity: '1', unit: 'tsp' },
      { name: 'onion powder', quantity: '1', unit: 'tsp' },
      { name: 'buns', quantity: '8', unit: 'pieces' },
    ],
    steps: [
      'Rub pork with paprika, garlic powder, onion powder, brown sugar, salt, and pepper.',
      'Smoke at 225°F for 6-8 hours until internal temp reaches 205°F.',
      'Let rest 30 minutes, then shred with two forks.',
      'Mix with BBQ sauce and apple cider vinegar.',
      'Pile onto buns.',
      'Serve with coleslaw on the side.',
    ],
    tags: ['american', 'bbq', 'pork', 'slow-cook', 'sandwich'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 32,
      carbs_g: 18,
      fat_g: 20,
      fiber_g: 1,
      sugar_g: 10,
      sodium_mg: 720,
    },
  },
  {
    title: 'Buffalo Wings',
    description:
      'Crispy fried chicken wings tossed in fiery cayenne hot sauce, served with blue cheese dip.',
    cuisine: 'American',
    prep_minutes: 15,
    cook_minutes: 12,
    servings: 6,
    calories: 420,
    ingredients: [
      { name: 'chicken wings', quantity: '3', unit: 'lb' },
      { name: 'hot sauce', quantity: '1/2', unit: 'cup' },
      { name: 'butter', quantity: '3', unit: 'tbsp' },
      { name: 'garlic powder', quantity: '1', unit: 'tsp' },
      { name: 'blue cheese', quantity: '1/2', unit: 'cup, crumbled' },
      { name: 'celery sticks', quantity: '6', unit: 'stalks' },
      { name: 'carrot sticks', quantity: '6', unit: 'pieces' },
      { name: 'ranch dressing', quantity: '1/2', unit: 'cup' },
    ],
    steps: [
      'Pat wings dry, season with salt and garlic powder.',
      'Deep fry at 375°F for 10-12 minutes until crispy and cooked through.',
      'Melt butter with hot sauce for the buffalo sauce.',
      'Toss crispy wings in the buffalo sauce until coated.',
      'Mix blue cheese with sour cream and mayo for dipping.',
      'Serve wings with blue cheese dip, celery, and carrot sticks.',
    ],
    tags: ['american', 'wings', 'spicy', 'fried', 'appetizer'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 28,
      carbs_g: 2,
      fat_g: 36,
      fiber_g: 0,
      sugar_g: 1,
      sodium_mg: 980,
    },
  },
  {
    title: 'New York Pizza',
    description: 'Thin-crust pizza with tangy tomato sauce, mozzarella, and foldable slices.',
    cuisine: 'American',
    prep_minutes: 30,
    cook_minutes: 12,
    servings: 8,
    calories: 280,
    ingredients: [
      { name: 'bread flour', quantity: '3', unit: 'cups' },
      { name: 'tomato sauce', quantity: '1', unit: 'cup' },
      { name: 'mozzarella', quantity: '2', unit: 'cups, shredded' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'yeast', quantity: '1', unit: 'tsp' },
      { name: 'sugar', quantity: '1', unit: 'tsp' },
      { name: 'oregano', quantity: '1', unit: 'tsp' },
      { name: 'parmesan', quantity: '2', unit: 'tbsp, grated' },
    ],
    steps: [
      'Mix flour, yeast, salt, sugar, and water. Knead 10 minutes. Let rise 1-2 hours.',
      'Stretch dough into a large thin round on a floured peel.',
      'Spread tomato sauce, leaving a 1-inch border.',
      'Top with mozzarella, drizzle olive oil, sprinkle oregano.',
      'Slide onto a preheated pizza stone at 500°F.',
      'Bake 10-12 minutes until crust is charred and cheese is bubbly. Finish with parmesan.',
    ],
    tags: ['american', 'pizza', 'italian-american', 'cheese', 'thin-crust'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 12,
      carbs_g: 34,
      fat_g: 10,
      fiber_g: 2,
      sugar_g: 4,
      sodium_mg: 560,
    },
  },
  {
    title: 'Clam Chowder',
    description: 'Thick, creamy New England clam chowder with potatoes, onions, and tender clams.',
    cuisine: 'American',
    prep_minutes: 15,
    cook_minutes: 30,
    servings: 6,
    calories: 320,
    ingredients: [
      { name: 'clams', quantity: '2', unit: 'cans (6.5 oz), chopped' },
      { name: 'potato', quantity: '2', unit: 'medium, diced' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'celery', quantity: '2', unit: 'stalks, diced' },
      { name: 'butter', quantity: '3', unit: 'tbsp' },
      { name: 'flour', quantity: '3', unit: 'tbsp' },
      { name: 'milk', quantity: '2', unit: 'cups' },
      { name: 'heavy cream', quantity: '1', unit: 'cup' },
      { name: 'thyme', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Cook onion and celery in butter until softened.',
      'Add flour and cook 1 minute to make a roux.',
      'Add clam juice, milk, and cream. Whisk until smooth.',
      'Add potatoes and thyme. Simmer 15-20 minutes until potatoes are tender.',
      'Add chopped clams and heat through.',
      'Season with salt and pepper. Serve with oyster crackers.',
    ],
    tags: ['american', 'soup', 'clam', 'creamy', 'new-england'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 14,
      carbs_g: 24,
      fat_g: 18,
      fiber_g: 2,
      sugar_g: 4,
      sodium_mg: 780,
    },
  },
  {
    title: 'Fried Chicken',
    description:
      'Buttermilk-brined chicken pieces coated in seasoned flour and fried until golden and juicy.',
    cuisine: 'American',
    prep_minutes: 20,
    cook_minutes: 20,
    servings: 6,
    calories: 480,
    ingredients: [
      { name: 'chicken pieces', quantity: '3', unit: 'lb' },
      { name: 'buttermilk', quantity: '2', unit: 'cups' },
      { name: 'flour', quantity: '2', unit: 'cups' },
      { name: 'paprika', quantity: '1', unit: 'tbsp' },
      { name: 'garlic powder', quantity: '1', unit: 'tsp' },
      { name: 'onion powder', quantity: '1', unit: 'tsp' },
      { name: 'cayenne', quantity: '1/4', unit: 'tsp' },
      { name: 'egg', quantity: '2', unit: 'beaten' },
    ],
    steps: [
      'Soak chicken in buttermilk for at least 4 hours or overnight.',
      'Mix flour, paprika, garlic powder, onion powder, cayenne, salt, and pepper.',
      'Dredge chicken in seasoned flour, dip in egg, then flour again.',
      'Deep fry at 325°F for 15-20 minutes until golden and cooked to 165°F.',
      'Drain on a wire rack.',
      'Serve with mashed potatoes and gravy.',
    ],
    tags: ['american', 'fried', 'chicken', 'southern', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 480,
      protein_g: 36,
      carbs_g: 18,
      fat_g: 30,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 680,
    },
  },
  {
    title: 'Apple Pie',
    description:
      'Classic double-crust pie filled with cinnamon-spiced apples, baked until golden and bubbling.',
    cuisine: 'American',
    prep_minutes: 30,
    cook_minutes: 50,
    servings: 8,
    calories: 340,
    ingredients: [
      { name: 'apple', quantity: '6', unit: 'Granny Smith, sliced' },
      { name: 'pie crust', quantity: '2', unit: '9-inch rounds' },
      { name: 'sugar', quantity: '3/4', unit: 'cup' },
      { name: 'cinnamon', quantity: '1', unit: 'tbsp' },
      { name: 'nutmeg', quantity: '1/4', unit: 'tsp' },
      { name: 'flour', quantity: '2', unit: 'tbsp' },
      { name: 'butter', quantity: '2', unit: 'tbsp, diced' },
      { name: 'egg wash', quantity: '1', unit: 'egg, beaten' },
    ],
    steps: [
      'Toss sliced apples with sugar, cinnamon, nutmeg, and flour.',
      'Line a pie dish with the bottom crust. Fill with apple mixture.',
      'Dot with butter pieces. Cover with top crust, crimp edges.',
      'Cut steam vents in the top. Brush with egg wash and sprinkle sugar.',
      'Bake at 400°F for 50 minutes until golden and juices bubble.',
      'Cool for at least 1 hour before slicing. Serve with vanilla ice cream.',
    ],
    tags: ['american', 'dessert', 'pie', 'apple', 'cinnamon'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 340,
      protein_g: 2,
      carbs_g: 50,
      fat_g: 14,
      fiber_g: 3,
      sugar_g: 28,
      sodium_mg: 220,
    },
  },
  {
    title: 'Pancakes',
    description: 'Fluffy buttermilk pancakes stacked high and drizzled with maple syrup.',
    cuisine: 'American',
    prep_minutes: 10,
    cook_minutes: 10,
    servings: 4,
    calories: 320,
    ingredients: [
      { name: 'flour', quantity: '1.5', unit: 'cups' },
      { name: 'buttermilk', quantity: '1.25', unit: 'cups' },
      { name: 'egg', quantity: '1', unit: 'large' },
      { name: 'butter', quantity: '2', unit: 'tbsp, melted' },
      { name: 'sugar', quantity: '2', unit: 'tbsp' },
      { name: 'baking powder', quantity: '1', unit: 'tsp' },
      { name: 'baking soda', quantity: '1/2', unit: 'tsp' },
      { name: 'maple syrup', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Whisk flour, sugar, baking powder, and baking soda.',
      'Combine buttermilk, egg, and melted butter.',
      'Mix wet into dry until just combined (lumps are OK).',
      'Pour 1/4 cup batter per pancake onto a buttered griddle.',
      'Cook until bubbles form on top and edges set, flip, cook 1-2 more minutes.',
      'Stack and serve with butter and maple syrup.',
    ],
    tags: ['american', 'breakfast', 'pancakes', 'fluffy', 'maple'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 8,
      carbs_g: 48,
      fat_g: 10,
      fiber_g: 1,
      sugar_g: 14,
      sodium_mg: 620,
    },
  },
  {
    title: 'Cobb Salad',
    description:
      'Hearty chopped salad with chicken, bacon, avocado, egg, blue cheese, and ranch dressing.',
    cuisine: 'American',
    prep_minutes: 20,
    cook_minutes: 15,
    servings: 4,
    calories: 480,
    ingredients: [
      { name: 'chicken breast', quantity: '2', unit: 'grilled, sliced' },
      { name: 'bacon', quantity: '6', unit: 'slices, cooked crispy' },
      { name: 'avocado', quantity: '1', unit: 'diced' },
      { name: 'egg', quantity: '2', unit: 'hard-boiled, quartered' },
      { name: 'blue cheese', quantity: '1/4', unit: 'cup, crumbled' },
      { name: 'romaine lettuce', quantity: '1', unit: 'head, chopped' },
      { name: 'tomato', quantity: '1', unit: 'diced' },
      { name: 'ranch dressing', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Grill chicken breast and slice. Cook bacon until crispy.',
      'Hard-boil eggs, peel and quarter.',
      'Chop romaine and arrange on a large platter.',
      'Arrange chicken, bacon, avocado, egg, blue cheese, and tomato in rows over lettuce.',
      'Drizzle with ranch dressing.',
      'Serve immediately.',
    ],
    tags: ['american', 'salad', 'chicken', 'bacon', 'hearty'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 480,
      protein_g: 38,
      carbs_g: 8,
      fat_g: 34,
      fiber_g: 4,
      sugar_g: 2,
      sodium_mg: 860,
    },
  },
  {
    title: 'Cornbread',
    description:
      'Sweet, moist Southern cornbread with a golden crust, perfect alongside chili or BBQ.',
    cuisine: 'American',
    prep_minutes: 10,
    cook_minutes: 20,
    servings: 8,
    calories: 180,
    ingredients: [
      { name: 'cornmeal', quantity: '1', unit: 'cup' },
      { name: 'flour', quantity: '1', unit: 'cup' },
      { name: 'buttermilk', quantity: '1', unit: 'cup' },
      { name: 'egg', quantity: '1', unit: 'large' },
      { name: 'butter', quantity: '1/4', unit: 'cup, melted' },
      { name: 'sugar', quantity: '1/4', unit: 'cup' },
      { name: 'baking powder', quantity: '1', unit: 'tsp' },
      { name: 'baking soda', quantity: '1/2', unit: 'tsp' },
    ],
    steps: [
      'Preheat oven to 400°F. Place a cast-iron skillet with butter in the oven.',
      'Mix cornmeal, flour, sugar, baking powder, baking soda, and salt.',
      'Combine buttermilk, egg, and melted butter.',
      'Mix wet into dry until just combined.',
      'Pour into the hot buttered skillet.',
      'Bake 18-20 minutes until golden and a toothpick comes out clean.',
    ],
    tags: ['american', 'bread', 'southern', 'cornmeal', 'baked'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 180,
      protein_g: 4,
      carbs_g: 24,
      fat_g: 8,
      fiber_g: 1,
      sugar_g: 6,
      sodium_mg: 340,
    },
  },
  {
    title: 'Jambalaya',
    description:
      'One-pot Creole rice dish with andouille sausage, chicken, shrimp, and the holy trinity.',
    cuisine: 'American',
    prep_minutes: 20,
    cook_minutes: 40,
    servings: 8,
    calories: 420,
    ingredients: [
      { name: 'andouille sausage', quantity: '8', unit: 'oz, sliced' },
      { name: 'chicken thigh', quantity: '1', unit: 'lb, cubed' },
      { name: 'shrimp', quantity: '1/2', unit: 'lb' },
      { name: 'rice', quantity: '2', unit: 'cups' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'bell pepper', quantity: '1', unit: 'diced' },
      { name: 'celery', quantity: '2', unit: 'stalks, diced' },
      { name: 'diced tomato', quantity: '1', unit: 'can (14 oz)' },
      { name: 'cajun seasoning', quantity: '2', unit: 'tbsp' },
      { name: 'chicken broth', quantity: '3', unit: 'cups' },
    ],
    steps: [
      'Brown andouille sausage in a large pot. Remove.',
      'Brown chicken in the rendered fat. Remove.',
      'Sauté onion, bell pepper, and celery (holy trinity) until soft.',
      'Add rice, Cajun seasoning, tomato, and broth. Bring to a boil.',
      'Add sausage and chicken back. Cover and simmer 20 minutes.',
      'Add shrimp in the last 5 minutes. Fluff and serve.',
    ],
    tags: ['american', 'creole', 'rice', 'sausage', 'one-pot'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 30,
      carbs_g: 36,
      fat_g: 16,
      fiber_g: 2,
      sugar_g: 4,
      sodium_mg: 980,
    },
  },
  {
    title: 'Philly Cheesesteak',
    description: 'Shaved ribeye with melted provolone and caramelized onions on a hoagie roll.',
    cuisine: 'American',
    prep_minutes: 10,
    cook_minutes: 10,
    servings: 4,
    calories: 480,
    ingredients: [
      { name: 'ribeye steak', quantity: '1', unit: 'lb, thinly sliced' },
      { name: 'provolone cheese', quantity: '4', unit: 'slices' },
      { name: 'hoagie rolls', quantity: '4', unit: 'pieces' },
      { name: 'onion', quantity: '2', unit: 'sliced' },
      { name: 'bell pepper', quantity: '1', unit: 'sliced' },
      { name: 'olive oil', quantity: '1', unit: 'tbsp' },
      { name: 'Worcestershire sauce', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Caramelize onions and peppers in oil until deeply golden.',
      'Cook thinly sliced ribeye on a hot griddle, chop with spatula.',
      'Add Worcestershire sauce and season.',
      'Mix meat with the onions and peppers.',
      'Lay provolone on top, let it melt.',
      'Scoop into hoagie rolls and serve immediately.',
    ],
    tags: ['american', 'sandwich', 'steak', 'cheese', 'philly'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 480,
      protein_g: 34,
      carbs_g: 32,
      fat_g: 24,
      fiber_g: 2,
      sugar_g: 4,
      sodium_mg: 780,
    },
  },
  {
    title: 'Chocolate Chip Cookies',
    description: 'Chewy, gooey chocolate chip cookies with crisp edges and a soft center.',
    cuisine: 'American',
    prep_minutes: 15,
    cook_minutes: 12,
    servings: 24,
    calories: 160,
    ingredients: [
      { name: 'butter', quantity: '1', unit: 'cup (2 sticks), softened' },
      { name: 'brown sugar', quantity: '3/4', unit: 'cup' },
      { name: 'white sugar', quantity: '1/4', unit: 'cup' },
      { name: 'egg', quantity: '2', unit: 'large' },
      { name: 'vanilla extract', quantity: '1', unit: 'tbsp' },
      { name: 'flour', quantity: '2.5', unit: 'cups' },
      { name: 'baking soda', quantity: '1', unit: 'tsp' },
      { name: 'chocolate chips', quantity: '2', unit: 'cups' },
      { name: 'salt', quantity: '1/2', unit: 'tsp' },
    ],
    steps: [
      'Cream butter and both sugars until light and fluffy.',
      'Beat in eggs and vanilla.',
      'Mix flour, baking soda, and salt. Add to butter mixture.',
      'Fold in chocolate chips.',
      'Scoop dough onto baking sheets, 2 inches apart.',
      'Bake at 375°F for 9-11 minutes until edges are golden. Cool on sheets 5 minutes.',
    ],
    tags: ['american', 'dessert', 'cookie', 'chocolate', 'baking'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 160,
      protein_g: 2,
      carbs_g: 20,
      fat_g: 8,
      fiber_g: 0,
      sugar_g: 12,
      sodium_mg: 140,
    },
  },
  {
    title: 'Grits',
    description: 'Creamy Southern stone-ground grits with butter and sharp cheddar cheese.',
    cuisine: 'American',
    prep_minutes: 5,
    cook_minutes: 25,
    servings: 4,
    calories: 220,
    ingredients: [
      { name: 'stone-ground grits', quantity: '1', unit: 'cup' },
      { name: 'water', quantity: '4', unit: 'cups' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
      { name: 'cheddar cheese', quantity: '1/2', unit: 'cup, shredded' },
      { name: 'heavy cream', quantity: '1/4', unit: 'cup' },
      { name: 'salt', quantity: '1/2', unit: 'tsp' },
      { name: 'black pepper', quantity: '1/4', unit: 'tsp' },
    ],
    steps: [
      'Bring salted water to a boil.',
      'Slowly whisk in grits to prevent lumps.',
      'Reduce heat and simmer, stirring frequently, for 20-25 minutes.',
      'Stir in butter, cream, and cheddar until melted and smooth.',
      'Season with salt and pepper.',
      'Serve as a side with shrimp or as a breakfast dish.',
    ],
    tags: ['american', 'southern', 'grits', 'breakfast', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 220,
      protein_g: 6,
      carbs_g: 28,
      fat_g: 10,
      fiber_g: 1,
      sugar_g: 1,
      sodium_mg: 380,
    },
  },
  {
    title: 'Brownies',
    description: 'Fudgy, dense chocolate brownies with a crackly top and rich cocoa flavor.',
    cuisine: 'American',
    prep_minutes: 15,
    cook_minutes: 25,
    servings: 16,
    calories: 200,
    ingredients: [
      { name: 'butter', quantity: '1', unit: 'cup (2 sticks)' },
      { name: 'sugar', quantity: '2', unit: 'cups' },
      { name: 'cocoa powder', quantity: '1', unit: 'cup' },
      { name: 'egg', quantity: '4', unit: 'large' },
      { name: 'vanilla extract', quantity: '1', unit: 'tbsp' },
      { name: 'flour', quantity: '1', unit: 'cup' },
      { name: 'salt', quantity: '1/2', unit: 'tsp' },
      { name: 'chocolate chips', quantity: '1', unit: 'cup' },
    ],
    steps: [
      'Melt butter, stir in sugar and cocoa powder.',
      'Beat in eggs one at a time, then vanilla.',
      'Fold in flour and salt until just combined.',
      'Stir in chocolate chips.',
      'Spread in a greased 9x13 pan.',
      'Bake at 350°F for 20-25 minutes until a toothpick comes out with moist crumbs.',
    ],
    tags: ['american', 'dessert', 'brownie', 'chocolate', 'fudgy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 200,
      protein_g: 3,
      carbs_g: 28,
      fat_g: 10,
      fiber_g: 1,
      sugar_g: 20,
      sodium_mg: 120,
    },
  },
];

export const americanRecipes = generateCuisineRecipes(configs);

// ── Additional American recipes ──────────────────────────────────────────────

const additionalAmericanConfigs: CuisineRecipeConfig[] = [
  {
    title: 'Mac and Cheese',
    description:
      'Creamy baked macaroni with a sharp cheddar cheese sauce and buttery breadcrumb topping.',
    cuisine: 'American',
    prep_minutes: 15,
    cook_minutes: 25,
    servings: 8,
    calories: 420,
    ingredients: [
      { name: 'macaroni', quantity: '1', unit: 'lb' },
      { name: 'sharp cheddar', quantity: '2', unit: 'cups, shredded' },
      { name: 'butter', quantity: '3', unit: 'tbsp' },
      { name: 'flour', quantity: '3', unit: 'tbsp' },
      { name: 'milk', quantity: '3', unit: 'cups' },
      { name: 'breadcrumbs', quantity: '1/2', unit: 'cup' },
      { name: 'mustard powder', quantity: '1/2', unit: 'tsp' },
    ],
    steps: [
      'Cook macaroni until just al dente. Drain.',
      'Make roux with butter and flour. Add milk, whisk until thick.',
      'Add cheese and mustard. Stir until melted.',
      'Combine sauce with macaroni. Pour into a baking dish.',
      'Top with breadcrumbs and extra cheese.',
      'Bake at 375°F for 20 minutes until bubbly and golden.',
    ],
    tags: ['american', 'pasta', 'cheese', 'baked', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 18,
      carbs_g: 38,
      fat_g: 22,
      fiber_g: 1,
      sugar_g: 4,
      sodium_mg: 680,
    },
  },
  {
    title: 'Buffalo Wings',
    description:
      'Crispy fried chicken wings tossed in a cayenne-vinegar hot sauce, served with blue cheese.',
    cuisine: 'American',
    prep_minutes: 10,
    cook_minutes: 12,
    servings: 6,
    calories: 380,
    ingredients: [
      { name: 'chicken wings', quantity: '2', unit: 'lb' },
      { name: 'hot sauce', quantity: '1/2', unit: 'cup' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
      { name: 'vinegar', quantity: '1', unit: 'tbsp' },
      { name: 'celery', quantity: '4', unit: 'sticks' },
      { name: 'blue cheese dressing', quantity: '1/2', unit: 'cup' },
    ],
    steps: [
      'Deep fry wings at 350°F for 10-12 minutes until crispy.',
      'Melt butter with hot sauce and vinegar.',
      'Toss crispy wings in the sauce.',
      'Serve with celery sticks and blue cheese dressing.',
    ],
    tags: ['american', 'wings', 'spicy', 'fried', 'appetizer'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 24,
      carbs_g: 2,
      fat_g: 30,
      fiber_g: 0,
      sugar_g: 0,
      sodium_mg: 860,
    },
  },
  {
    title: 'Clam Chowder',
    description: 'New England-style creamy clam chowder with potatoes, onions, and celery.',
    cuisine: 'American',
    prep_minutes: 15,
    cook_minutes: 25,
    servings: 6,
    calories: 280,
    ingredients: [
      { name: 'clams', quantity: '2', unit: 'cans (6.5 oz), chopped' },
      { name: 'potato', quantity: '2', unit: 'diced' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'celery', quantity: '2', unit: 'stalks, diced' },
      { name: 'cream', quantity: '1', unit: 'cup' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
      { name: 'flour', quantity: '2', unit: 'tbsp' },
      { name: 'clam juice', quantity: '2', unit: 'cups' },
    ],
    steps: [
      'Sauté onion and celery in butter. Add flour.',
      'Add clam juice and potatoes. Simmer until tender.',
      'Add clams and cream.',
      'Simmer 10 minutes. Do not boil.',
      'Season with salt, pepper, and thyme.',
      'Serve in bread bowls.',
    ],
    tags: ['american', 'soup', 'clam', 'cream', 'new-england'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 14,
      carbs_g: 22,
      fat_g: 14,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 680,
    },
  },
  {
    title: 'Apple Pie',
    description: 'Classic American apple pie with cinnamon-spiced apples in a flaky double crust.',
    cuisine: 'American',
    prep_minutes: 25,
    cook_minutes: 50,
    servings: 8,
    calories: 340,
    ingredients: [
      { name: 'pie crust', quantity: '2', unit: '9-inch rounds' },
      { name: 'apple', quantity: '6', unit: 'sliced' },
      { name: 'sugar', quantity: '3/4', unit: 'cup' },
      { name: 'cinnamon', quantity: '1', unit: 'tsp' },
      { name: 'nutmeg', quantity: '1/4', unit: 'tsp' },
      { name: 'flour', quantity: '2', unit: 'tbsp' },
      { name: 'butter', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Toss apples with sugar, cinnamon, nutmeg, and flour.',
      'Line pie dish with bottom crust. Add apple filling.',
      'Dot with butter. Cover with top crust. Crimp edges.',
      'Cut steam vents. Brush with egg wash.',
      'Bake at 400°F for 50 minutes until golden.',
      'Cool before slicing. Serve with vanilla ice cream.',
    ],
    tags: ['american', 'pie', 'apple', 'dessert', 'classic'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 340,
      protein_g: 2,
      carbs_g: 48,
      fat_g: 16,
      fiber_g: 2,
      sugar_g: 28,
      sodium_mg: 220,
    },
  },
  {
    title: 'Gumbo',
    description: 'Louisiana gumbo with dark roux, andouille sausage, chicken, shrimp, and okra.',
    cuisine: 'American',
    prep_minutes: 20,
    cook_minutes: 60,
    servings: 8,
    calories: 380,
    ingredients: [
      { name: 'flour', quantity: '1/2', unit: 'cup' },
      { name: 'oil', quantity: '1/2', unit: 'cup' },
      { name: 'andouille sausage', quantity: '8', unit: 'oz, sliced' },
      { name: 'chicken thigh', quantity: '1', unit: 'lb' },
      { name: 'shrimp', quantity: '1/2', unit: 'lb' },
      { name: 'okra', quantity: '1', unit: 'cup, sliced' },
      { name: 'bell pepper', quantity: '1', unit: 'diced' },
      { name: 'chicken broth', quantity: '4', unit: 'cups' },
    ],
    steps: [
      'Make a dark roux with flour and oil, stirring 20-30 minutes.',
      'Add onion, bell pepper, and celery. Sauté.',
      'Add broth, chicken, and sausage. Simmer 40 minutes.',
      'Add okra and shrimp. Cook 10 minutes.',
      'Season with filé powder, hot sauce, salt, and pepper.',
      'Serve over white rice.',
    ],
    tags: ['american', 'gumbo', 'cajun', 'stew', 'louisiana'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 28,
      carbs_g: 14,
      fat_g: 22,
      fiber_g: 2,
      sugar_g: 2,
      sodium_mg: 860,
    },
  },
  {
    title: 'Jambalaya',
    description:
      'One-pot Cajun rice dish with chicken, sausage, and shrimp in a spicy tomato broth.',
    cuisine: 'American',
    prep_minutes: 15,
    cook_minutes: 35,
    servings: 8,
    calories: 380,
    ingredients: [
      { name: 'rice', quantity: '2', unit: 'cups' },
      { name: 'chicken thigh', quantity: '1', unit: 'lb, cubed' },
      { name: 'andouille sausage', quantity: '8', unit: 'oz, sliced' },
      { name: 'shrimp', quantity: '1/2', unit: 'lb' },
      { name: 'diced tomato', quantity: '1', unit: 'can (14 oz)' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'cajun seasoning', quantity: '2', unit: 'tbsp' },
      { name: 'chicken broth', quantity: '3', unit: 'cups' },
    ],
    steps: [
      'Brown chicken and sausage. Set aside.',
      'Sauté onion, bell pepper, and celery.',
      'Add rice, tomato, broth, and Cajun seasoning.',
      'Return chicken and sausage. Cover and simmer 25 minutes.',
      'Add shrimp, cook 5 more minutes.',
      'Serve hot. The rice should be fluffy and flavorful.',
    ],
    tags: ['american', 'rice', 'cajun', 'one-pot', 'louisiana'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 28,
      carbs_g: 36,
      fat_g: 12,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 860,
    },
  },
  {
    title: 'Cornbread',
    description: 'Southern-style cornbread — slightly sweet, crumbly, and perfect with chili.',
    cuisine: 'American',
    prep_minutes: 10,
    cook_minutes: 20,
    servings: 8,
    calories: 180,
    ingredients: [
      { name: 'cornmeal', quantity: '1', unit: 'cup' },
      { name: 'flour', quantity: '1', unit: 'cup' },
      { name: 'sugar', quantity: '1/4', unit: 'cup' },
      { name: 'baking powder', quantity: '1', unit: 'tbsp' },
      { name: 'egg', quantity: '1', unit: 'large' },
      { name: 'milk', quantity: '1', unit: 'cup' },
      { name: 'butter', quantity: '1/4', unit: 'cup, melted' },
    ],
    steps: [
      'Mix cornmeal, flour, sugar, baking powder, and salt.',
      'Whisk egg, milk, and melted butter.',
      'Combine wet and dry ingredients. Do not overmix.',
      'Pour into a greased cast iron skillet.',
      'Bake at 400°F for 18-20 minutes until golden.',
      'Serve warm with butter and honey.',
    ],
    tags: ['american', 'bread', 'cornbread', 'southern', 'baking'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 180,
      protein_g: 4,
      carbs_g: 26,
      fat_g: 6,
      fiber_g: 1,
      sugar_g: 6,
      sodium_mg: 280,
    },
  },
  {
    title: 'Biscuits and Gravy',
    description: 'Southern breakfast of flaky biscuits smothered in sausage cream gravy.',
    cuisine: 'American',
    prep_minutes: 15,
    cook_minutes: 15,
    servings: 4,
    calories: 480,
    ingredients: [
      { name: 'biscuits', quantity: '8', unit: 'homemade or canned' },
      { name: 'ground sausage', quantity: '1/2', unit: 'lb' },
      { name: 'flour', quantity: '3', unit: 'tbsp' },
      { name: 'milk', quantity: '2', unit: 'cups' },
      { name: 'black pepper', quantity: '1/2', unit: 'tsp' },
      { name: 'butter', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Bake biscuits according to directions.',
      'Brown sausage in a skillet, breaking apart.',
      'Sprinkle flour over sausage, stir 1 minute.',
      'Gradually add milk, stirring until thickened.',
      'Season with plenty of black pepper and salt.',
      'Split biscuits, ladle gravy over. Serve immediately.',
    ],
    tags: ['american', 'breakfast', 'biscuits', 'gravy', 'southern'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 480,
      protein_g: 16,
      carbs_g: 38,
      fat_g: 28,
      fiber_g: 1,
      sugar_g: 4,
      sodium_mg: 860,
    },
  },
  {
    title: 'Pecan Pie',
    description: 'Rich, buttery pecan pie with a gooey brown sugar filling in a flaky crust.',
    cuisine: 'American',
    prep_minutes: 15,
    cook_minutes: 50,
    servings: 8,
    calories: 420,
    ingredients: [
      { name: 'pie crust', quantity: '1', unit: '9-inch' },
      { name: 'pecans', quantity: '2', unit: 'cups' },
      { name: 'corn syrup', quantity: '1', unit: 'cup' },
      { name: 'brown sugar', quantity: '1', unit: 'cup' },
      { name: 'butter', quantity: '1/4', unit: 'cup, melted' },
      { name: 'egg', quantity: '3', unit: 'large' },
      { name: 'vanilla', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Spread pecans in the pie crust.',
      'Whisk corn syrup, brown sugar, butter, eggs, and vanilla.',
      'Pour over pecans.',
      'Bake at 350°F for 50 minutes until set.',
      'Cool completely before slicing.',
      'Serve with whipped cream.',
    ],
    tags: ['american', 'pie', 'pecan', 'dessert', 'southern'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 4,
      carbs_g: 52,
      fat_g: 22,
      fiber_g: 2,
      sugar_g: 36,
      sodium_mg: 180,
    },
  },
  {
    title: 'Pulled Pork',
    description: 'Slow-smoked pork shoulder shredded and tossed in tangy BBQ sauce.',
    cuisine: 'American',
    prep_minutes: 15,
    cook_minutes: 480,
    servings: 10,
    calories: 280,
    ingredients: [
      { name: 'pork shoulder', quantity: '5', unit: 'lb' },
      { name: 'BBQ rub', quantity: '3', unit: 'tbsp' },
      { name: 'apple cider vinegar', quantity: '1/4', unit: 'cup' },
      { name: 'BBQ sauce', quantity: '1', unit: 'cup' },
      { name: 'buns', quantity: '10', unit: 'pieces' },
      { name: 'coleslaw', quantity: '3', unit: 'cups' },
    ],
    steps: [
      'Rub pork shoulder with BBQ spice rub.',
      'Smoke at 225°F for 8 hours or slow-roast in the oven.',
      'Shred with forks when tender.',
      'Toss with BBQ sauce and apple cider vinegar.',
      'Pile on buns with coleslaw.',
      'Serve with pickles and extra sauce.',
    ],
    tags: ['american', 'pork', 'bbq', 'smoked', 'sandwich'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 22,
      carbs_g: 14,
      fat_g: 14,
      fiber_g: 1,
      sugar_g: 6,
      sodium_mg: 680,
    },
  },
];

export const americanAdditionalRecipes = generateCuisineRecipes(additionalAmericanConfigs);
