import type { CuisineRecipeConfig } from './types';
import { generateCuisineRecipes } from './types';

const configs: CuisineRecipeConfig[] = [
  {
    title: 'Pad Thai',
    description:
      'Stir-fried rice noodles with shrimp, tofu, bean sprouts, peanuts, and tamarind sauce.',
    cuisine: 'Asian',
    prep_minutes: 15,
    cook_minutes: 10,
    servings: 4,
    calories: 380,
    ingredients: [
      { name: 'rice noodles', quantity: '8', unit: 'oz' },
      { name: 'shrimp', quantity: '1/2', unit: 'lb' },
      { name: 'firm tofu', quantity: '4', unit: 'oz, cubed' },
      { name: 'bean sprouts', quantity: '1', unit: 'cup' },
      { name: 'peanuts', quantity: '1/4', unit: 'cup, crushed' },
      { name: 'tamarind paste', quantity: '2', unit: 'tbsp' },
      { name: 'fish sauce', quantity: '2', unit: 'tbsp' },
      { name: 'lime', quantity: '2', unit: 'wedges' },
      { name: 'egg', quantity: '2', unit: 'large' },
      { name: 'green onion', quantity: '3', unit: 'stalks' },
    ],
    steps: [
      'Soak rice noodles in warm water for 20 minutes, then drain.',
      'Mix tamarind paste, fish sauce, and sugar for the sauce.',
      'Stir-fry shrimp and tofu in a wok until golden. Push to side and scramble eggs.',
      'Add noodles and sauce, toss until noodles absorb the sauce.',
      'Add bean sprouts and green onions, toss briefly. Serve with lime wedges and crushed peanuts.',
    ],
    tags: ['thai', 'noodles', 'stir-fry', 'shrimp', 'street-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 22,
      carbs_g: 42,
      fat_g: 12,
      fiber_g: 3,
      sugar_g: 8,
      sodium_mg: 820,
    },
  },
  {
    title: 'Kung Pao Chicken',
    description:
      'Spicy Sichuan stir-fry with diced chicken, peanuts, chili peppers, and Sichuan peppercorns.',
    cuisine: 'Asian',
    prep_minutes: 20,
    cook_minutes: 10,
    servings: 4,
    calories: 340,
    ingredients: [
      { name: 'chicken breast', quantity: '1', unit: 'lb, diced' },
      { name: 'peanuts', quantity: '1/3', unit: 'cup' },
      { name: 'dried red chilies', quantity: '8', unit: 'whole' },
      { name: 'Sichuan peppercorns', quantity: '1', unit: 'tsp' },
      { name: 'soy sauce', quantity: '2', unit: 'tbsp' },
      { name: 'rice vinegar', quantity: '1', unit: 'tbsp' },
      { name: 'cornstarch', quantity: '1', unit: 'tbsp' },
      { name: 'green onion', quantity: '4', unit: 'stalks' },
      { name: 'ginger', quantity: '1', unit: 'tbsp, minced' },
      { name: 'garlic', quantity: '3', unit: 'cloves, minced' },
    ],
    steps: [
      'Marinate chicken with soy sauce, cornstarch, and a splash of rice wine for 15 minutes.',
      'Toast peanuts in a dry wok until golden, set aside.',
      'Stir-fry dried chilies and Sichuan peppercorns in oil until fragrant.',
      'Add chicken, stir-fry until cooked through.',
      'Add sauce mixture (soy sauce, vinegar, sugar, cornstarch slurry) and toss.',
      'Add green onions and peanuts, toss and serve immediately with steamed rice.',
    ],
    tags: ['chinese', 'spicy', 'stir-fry', 'chicken', 'sichuan'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 340,
      protein_g: 32,
      carbs_g: 10,
      fat_g: 18,
      fiber_g: 2,
      sugar_g: 4,
      sodium_mg: 720,
    },
  },
  {
    title: 'Sushi Rolls',
    description:
      'Japanese maki rolls with seasoned rice, fresh fish, cucumber, and avocado wrapped in nori.',
    cuisine: 'Asian',
    prep_minutes: 40,
    cook_minutes: 20,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'sushi rice', quantity: '2', unit: 'cups' },
      { name: 'rice vinegar', quantity: '3', unit: 'tbsp' },
      { name: 'nori sheets', quantity: '8', unit: 'sheets' },
      { name: 'sushi-grade tuna', quantity: '8', unit: 'oz' },
      { name: 'cucumber', quantity: '1', unit: 'medium, julienned' },
      { name: 'avocado', quantity: '1', unit: 'sliced' },
      { name: 'soy sauce', quantity: '2', unit: 'tbsp' },
      { name: 'wasabi', quantity: '1', unit: 'tsp' },
      { name: 'pickled ginger', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Cook sushi rice and season with rice vinegar, sugar, and salt while folding gently.',
      'Lay a nori sheet on a bamboo mat, shiny side down.',
      'Spread rice evenly, leaving a 1-inch strip at the top.',
      'Place tuna, cucumber, and avocado in a line across the center.',
      'Roll tightly using the bamboo mat, seal the edge with water.',
      'Slice with a wet knife into 6-8 pieces. Serve with soy sauce, wasabi, and pickled ginger.',
    ],
    tags: ['japanese', 'sushi', 'fish', 'rice', 'raw'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 18,
      carbs_g: 38,
      fat_g: 6,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 540,
    },
  },
  {
    title: 'Pho',
    description: 'Vietnamese aromatic beef noodle soup with star anise, cinnamon, and fresh herbs.',
    cuisine: 'Asian',
    prep_minutes: 30,
    cook_minutes: 180,
    servings: 6,
    calories: 350,
    ingredients: [
      { name: 'beef bones', quantity: '3', unit: 'lb' },
      { name: 'rice noodles', quantity: '8', unit: 'oz' },
      { name: 'star anise', quantity: '3', unit: 'whole' },
      { name: 'cinnamon stick', quantity: '1', unit: 'whole' },
      { name: 'bean sprouts', quantity: '2', unit: 'cups' },
      { name: 'thai basil', quantity: '1', unit: 'cup' },
      { name: 'hoisin sauce', quantity: '2', unit: 'tbsp' },
      { name: 'sriracha', quantity: '1', unit: 'tbsp' },
      { name: 'lime', quantity: '2', unit: 'halved' },
      { name: 'onion', quantity: '1', unit: 'large, halved' },
    ],
    steps: [
      'Char onion and ginger under the broiler until blackened.',
      'Simmer beef bones in water, skimming foam for 30 minutes.',
      'Add charred aromatics, star anise, cinnamon, and fish sauce. Simmer 2-3 hours.',
      'Cook rice noodles according to package, divide among bowls.',
      'Strain broth and ladle over noodles. Top with thinly sliced rare beef.',
      'Serve with bean sprouts, Thai basil, lime, hoisin, and sriracha on the side.',
    ],
    tags: ['vietnamese', 'soup', 'beef', 'noodles', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 350,
      protein_g: 28,
      carbs_g: 35,
      fat_g: 10,
      fiber_g: 2,
      sugar_g: 4,
      sodium_mg: 980,
    },
  },
  {
    title: 'Spring Rolls',
    description:
      'Crispy fried rolls filled with pork, shrimp, and vegetables, served with sweet chili sauce.',
    cuisine: 'Asian',
    prep_minutes: 30,
    cook_minutes: 10,
    servings: 6,
    calories: 220,
    ingredients: [
      { name: 'spring roll wrappers', quantity: '12', unit: 'sheets' },
      { name: 'ground pork', quantity: '1/2', unit: 'lb' },
      { name: 'shrimp', quantity: '1/4', unit: 'lb, minced' },
      { name: 'cabbage', quantity: '2', unit: 'cups, shredded' },
      { name: 'carrot', quantity: '1', unit: 'julienned' },
      { name: 'glass noodles', quantity: '2', unit: 'oz, soaked' },
      { name: 'garlic', quantity: '3', unit: 'cloves, minced' },
      { name: 'sweet chili sauce', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Cook pork and shrimp with garlic until done. Let cool.',
      'Soak glass noodles, cut into short pieces. Mix with cabbage and carrot.',
      'Combine meat mixture with vegetables. Season with fish sauce and pepper.',
      'Place filling on wrapper, fold sides in, roll tightly, seal with water.',
      'Deep fry at 350°F until golden and crispy, about 5 minutes.',
      'Serve with sweet chili sauce for dipping.',
    ],
    tags: ['vietnamese', 'appetizer', 'fried', 'pork', 'shrimp'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 220,
      protein_g: 12,
      carbs_g: 20,
      fat_g: 10,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 480,
    },
  },
  {
    title: 'Tom Yum Soup',
    description:
      'Hot and sour Thai soup with shrimp, lemongrass, galangal, and kaffir lime leaves.',
    cuisine: 'Asian',
    prep_minutes: 15,
    cook_minutes: 15,
    servings: 4,
    calories: 180,
    ingredients: [
      { name: 'shrimp', quantity: '1/2', unit: 'lb' },
      { name: 'lemongrass', quantity: '3', unit: 'stalks, bruised' },
      { name: 'galangal', quantity: '3', unit: 'slices' },
      { name: 'kaffir lime leaves', quantity: '5', unit: 'leaves' },
      { name: 'mushrooms', quantity: '1', unit: 'cup, sliced' },
      { name: 'cherry tomatoes', quantity: '6', unit: 'halved' },
      { name: 'lime juice', quantity: '3', unit: 'tbsp' },
      { name: 'fish sauce', quantity: '2', unit: 'tbsp' },
      { name: 'chili paste', quantity: '1', unit: 'tbsp' },
      { name: 'cilantro', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Bring 4 cups of water or chicken broth to a boil.',
      'Add lemongrass, galangal, and kaffir lime leaves. Simmer 5 minutes.',
      'Add mushrooms and cook 3 minutes.',
      'Add shrimp and cherry tomatoes, cook until shrimp is pink, about 2 minutes.',
      'Season with fish sauce, lime juice, and chili paste.',
      'Garnish with cilantro and serve steaming hot.',
    ],
    tags: ['thai', 'soup', 'spicy', 'shrimp', 'sour'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 180,
      protein_g: 20,
      carbs_g: 8,
      fat_g: 6,
      fiber_g: 1,
      sugar_g: 3,
      sodium_mg: 860,
    },
  },
  {
    title: 'Fried Rice',
    description:
      'Wok-fried rice with egg, vegetables, soy sauce, and day-old rice for the perfect texture.',
    cuisine: 'Asian',
    prep_minutes: 10,
    cook_minutes: 8,
    servings: 4,
    calories: 320,
    ingredients: [
      { name: 'cooked rice', quantity: '4', unit: 'cups, day-old' },
      { name: 'egg', quantity: '3', unit: 'large' },
      { name: 'peas', quantity: '1/2', unit: 'cup' },
      { name: 'carrot', quantity: '1', unit: 'diced' },
      { name: 'green onion', quantity: '4', unit: 'stalks' },
      { name: 'soy sauce', quantity: '3', unit: 'tbsp' },
      { name: 'sesame oil', quantity: '1', unit: 'tsp' },
      { name: 'garlic', quantity: '2', unit: 'cloves, minced' },
      { name: 'vegetable oil', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Heat wok over high heat until smoking. Add oil.',
      'Scramble eggs, break into pieces, and set aside.',
      'Stir-fry carrots and peas for 2 minutes.',
      'Add rice and press flat against the wok to get crispy bits.',
      'Add soy sauce and sesame oil, toss everything together.',
      'Return eggs, add green onions, toss and serve immediately.',
    ],
    tags: ['chinese', 'rice', 'quick', 'egg', 'wok'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 10,
      carbs_g: 48,
      fat_g: 10,
      fiber_g: 3,
      sugar_g: 3,
      sodium_mg: 680,
    },
  },
  {
    title: 'Miso Ramen',
    description: 'Rich miso-based ramen with chashu pork, soft-boiled egg, corn, and nori.',
    cuisine: 'Asian',
    prep_minutes: 20,
    cook_minutes: 30,
    servings: 4,
    calories: 520,
    ingredients: [
      { name: 'ramen noodles', quantity: '12', unit: 'oz' },
      { name: 'miso paste', quantity: '3', unit: 'tbsp' },
      { name: 'chashu pork', quantity: '8', unit: 'oz, sliced' },
      { name: 'soft-boiled egg', quantity: '4', unit: 'halved' },
      { name: 'corn kernels', quantity: '1/2', unit: 'cup' },
      { name: 'nori sheets', quantity: '4', unit: 'sheets' },
      { name: 'green onion', quantity: '4', unit: 'stalks, sliced' },
      { name: 'chicken broth', quantity: '6', unit: 'cups' },
      { name: 'sesame oil', quantity: '1', unit: 'tbsp' },
      { name: 'ginger', quantity: '1', unit: 'tbsp, grated' },
    ],
    steps: [
      'Bring chicken broth to a simmer with ginger. Whisk in miso paste.',
      'Cook ramen noodles according to package directions.',
      'Warm chashu pork slices in the broth.',
      'Divide noodles among bowls, ladle broth over.',
      'Top with chashu, soft-boiled egg, corn, nori, and green onions.',
      'Drizzle with sesame oil and serve immediately.',
    ],
    tags: ['japanese', 'ramen', 'noodles', 'pork', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 520,
      protein_g: 28,
      carbs_g: 52,
      fat_g: 20,
      fiber_g: 3,
      sugar_g: 5,
      sodium_mg: 1200,
    },
  },
  {
    title: 'Dim Sum Dumplings',
    description:
      'Steamed or pan-fried pork dumplings with ginger, scallion, and soy dipping sauce.',
    cuisine: 'Asian',
    prep_minutes: 40,
    cook_minutes: 12,
    servings: 6,
    calories: 240,
    ingredients: [
      { name: 'dumpling wrappers', quantity: '40', unit: 'round' },
      { name: 'ground pork', quantity: '1', unit: 'lb' },
      { name: 'napa cabbage', quantity: '1', unit: 'cup, minced' },
      { name: 'ginger', quantity: '1', unit: 'tbsp, grated' },
      { name: 'green onion', quantity: '4', unit: 'stalks, minced' },
      { name: 'soy sauce', quantity: '2', unit: 'tbsp' },
      { name: 'sesame oil', quantity: '1', unit: 'tsp' },
      { name: 'rice vinegar', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Mix pork, cabbage, ginger, green onion, soy sauce, and sesame oil.',
      'Place a teaspoon of filling in the center of each wrapper.',
      'Moisten edges with water, fold and pleat to seal.',
      'Steam for 8 minutes or pan-fry with water for a crispy bottom.',
      'Mix soy sauce, vinegar, and ginger for the dipping sauce.',
      'Serve dumplings hot with dipping sauce.',
    ],
    tags: ['chinese', 'dumplings', 'dim-sum', 'pork', 'steamed'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 240,
      protein_g: 16,
      carbs_g: 22,
      fat_g: 10,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 520,
    },
  },
  {
    title: 'Bibimbap',
    description:
      'Korean mixed rice bowl with sautéed vegetables, gochujang, beef, and a fried egg.',
    cuisine: 'Asian',
    prep_minutes: 25,
    cook_minutes: 15,
    servings: 4,
    calories: 420,
    ingredients: [
      { name: 'steamed rice', quantity: '4', unit: 'cups' },
      { name: 'beef bulgogi', quantity: '8', unit: 'oz' },
      { name: 'spinach', quantity: '2', unit: 'cups, blanched' },
      { name: 'carrot', quantity: '1', unit: 'julienned' },
      { name: 'zucchini', quantity: '1', unit: 'sliced' },
      { name: 'bean sprouts', quantity: '1', unit: 'cup, blanched' },
      { name: 'egg', quantity: '4', unit: 'fried' },
      { name: 'gochujang', quantity: '2', unit: 'tbsp' },
      { name: 'sesame oil', quantity: '2', unit: 'tsp' },
      { name: 'sesame seeds', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Cook rice and keep warm. Sauté each vegetable separately with sesame oil and salt.',
      'Cook beef bulgogi in a hot pan until caramelized.',
      'Fry eggs sunny-side up.',
      'Arrange rice in a bowl, top with vegetables and beef in sections.',
      'Place fried egg in the center. Add gochujang.',
      'Drizzle with sesame oil, sprinkle sesame seeds. Mix before eating.',
    ],
    tags: ['korean', 'rice-bowl', 'beef', 'egg', 'gochujang'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 24,
      carbs_g: 50,
      fat_g: 14,
      fiber_g: 4,
      sugar_g: 5,
      sodium_mg: 680,
    },
  },
  {
    title: 'Sweet and Sour Pork',
    description:
      'Crispy battered pork pieces tossed in a vibrant sweet and sour sauce with bell peppers and pineapple.',
    cuisine: 'Asian',
    prep_minutes: 20,
    cook_minutes: 15,
    servings: 4,
    calories: 420,
    ingredients: [
      { name: 'pork tenderloin', quantity: '1', unit: 'lb, cubed' },
      { name: 'pineapple chunks', quantity: '1', unit: 'cup' },
      { name: 'bell pepper', quantity: '2', unit: 'diced' },
      { name: 'ketchup', quantity: '3', unit: 'tbsp' },
      { name: 'rice vinegar', quantity: '2', unit: 'tbsp' },
      { name: 'sugar', quantity: '3', unit: 'tbsp' },
      { name: 'cornstarch', quantity: '1/2', unit: 'cup for coating' },
      { name: 'egg', quantity: '1', unit: 'beaten' },
      { name: 'onion', quantity: '1', unit: 'chunked' },
    ],
    steps: [
      'Coat pork cubes in cornstarch and beaten egg.',
      'Deep fry pork at 350°F until golden and crispy.',
      'Sauté bell peppers and onion in a wok for 2 minutes.',
      'Add pineapple chunks and the sweet and sour sauce (ketchup, vinegar, sugar, soy sauce).',
      'Toss crispy pork in the sauce until coated.',
      'Serve immediately over steamed rice.',
    ],
    tags: ['chinese', 'pork', 'sweet-and-sour', 'crispy', 'pineapple'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 28,
      carbs_g: 38,
      fat_g: 16,
      fiber_g: 2,
      sugar_g: 18,
      sodium_mg: 560,
    },
  },
  {
    title: 'Thai Green Curry',
    description:
      'Creamy coconut curry with chicken, Thai basil, bamboo shoots, and green curry paste.',
    cuisine: 'Asian',
    prep_minutes: 15,
    cook_minutes: 20,
    servings: 4,
    calories: 380,
    ingredients: [
      { name: 'chicken thigh', quantity: '1', unit: 'lb, sliced' },
      { name: 'coconut milk', quantity: '2', unit: 'cans (14 oz)' },
      { name: 'green curry paste', quantity: '3', unit: 'tbsp' },
      { name: 'bamboo shoots', quantity: '1', unit: 'cup' },
      { name: 'thai basil', quantity: '1', unit: 'cup' },
      { name: 'fish sauce', quantity: '2', unit: 'tbsp' },
      { name: 'palm sugar', quantity: '1', unit: 'tbsp' },
      { name: 'thai eggplant', quantity: '4', unit: 'quartered' },
      { name: 'kaffir lime leaves', quantity: '4', unit: 'leaves' },
    ],
    steps: [
      'Heat coconut cream in a wok until it separates and sizzles.',
      'Fry green curry paste in the coconut cream for 2 minutes until fragrant.',
      'Add chicken and cook until no longer pink.',
      'Pour in remaining coconut milk, add bamboo shoots and eggplant.',
      'Season with fish sauce and palm sugar. Simmer 10 minutes.',
      'Stir in Thai basil and kaffir lime leaves. Serve with jasmine rice.',
    ],
    tags: ['thai', 'curry', 'coconut', 'chicken', 'spicy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 380,
      protein_g: 26,
      carbs_g: 10,
      fat_g: 26,
      fiber_g: 3,
      sugar_g: 4,
      sodium_mg: 780,
    },
  },
  {
    title: 'Japanese Tempura',
    description: 'Light, crispy battered shrimp and vegetables served with tentsuyu dipping sauce.',
    cuisine: 'Asian',
    prep_minutes: 15,
    cook_minutes: 10,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'large shrimp', quantity: '12', unit: 'peeled' },
      { name: 'sweet potato', quantity: '1', unit: 'sliced thin' },
      { name: 'eggplant', quantity: '1', unit: 'sliced' },
      { name: 'green beans', quantity: '1', unit: 'cup' },
      { name: 'flour', quantity: '1', unit: 'cup' },
      { name: 'egg', quantity: '1', unit: 'yolk' },
      { name: 'ice water', quantity: '1', unit: 'cup' },
      { name: 'dashi', quantity: '1', unit: 'cup' },
      { name: 'soy sauce', quantity: '2', unit: 'tbsp' },
      { name: 'mirin', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Make tempura batter: mix flour, egg yolk, and ice water gently (lumps are OK).',
      'Heat oil to 350°F.',
      'Dip shrimp and vegetables in batter, fry until golden, about 2-3 minutes.',
      'Make tentsuyu: combine dashi, soy sauce, and mirin.',
      'Drain tempura on paper towels.',
      'Serve hot with tentsuyu dipping sauce and grated daikon.',
    ],
    tags: ['japanese', 'tempura', 'fried', 'shrimp', 'vegetables'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 16,
      carbs_g: 24,
      fat_g: 14,
      fiber_g: 3,
      sugar_g: 4,
      sodium_mg: 620,
    },
  },
  {
    title: 'Korean Kimchi Jjigae',
    description:
      'Hearty Korean stew made with fermented kimchi, pork belly, and tofu, simmered to tangy perfection.',
    cuisine: 'Asian',
    prep_minutes: 10,
    cook_minutes: 25,
    servings: 4,
    calories: 320,
    ingredients: [
      { name: 'aged kimchi', quantity: '2', unit: 'cups, chopped' },
      { name: 'pork belly', quantity: '8', unit: 'oz, sliced' },
      { name: 'firm tofu', quantity: '1', unit: 'block, cubed' },
      { name: 'onion', quantity: '1', unit: 'sliced' },
      { name: 'garlic', quantity: '4', unit: 'cloves, minced' },
      { name: 'kimchi brine', quantity: '1/4', unit: 'cup' },
      { name: 'gochugaru', quantity: '1', unit: 'tbsp' },
      { name: 'green onion', quantity: '3', unit: 'stalks' },
    ],
    steps: [
      'Sauté pork belly in a pot until fat renders and edges are crispy.',
      'Add chopped kimchi and onion, stir-fry 3 minutes.',
      'Add kimchi brine, gochugaru, garlic, and 3 cups water.',
      'Bring to a boil, then simmer 15-20 minutes.',
      'Add tofu cubes and cook 5 more minutes.',
      'Garnish with green onions and serve with steamed rice.',
    ],
    tags: ['korean', 'stew', 'kimchi', 'pork', 'spicy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 20,
      carbs_g: 12,
      fat_g: 22,
      fiber_g: 3,
      sugar_g: 4,
      sodium_mg: 1100,
    },
  },
  {
    title: 'Mapo Tofu',
    description: 'Sichuan silken tofu in a fiery, numbing sauce with ground pork and doubanjiang.',
    cuisine: 'Asian',
    prep_minutes: 10,
    cook_minutes: 15,
    servings: 4,
    calories: 260,
    ingredients: [
      { name: 'silken tofu', quantity: '1', unit: 'block, cubed' },
      { name: 'ground pork', quantity: '4', unit: 'oz' },
      { name: 'doubanjiang', quantity: '2', unit: 'tbsp' },
      { name: 'Sichuan peppercorn powder', quantity: '1', unit: 'tsp' },
      { name: 'garlic', quantity: '3', unit: 'cloves, minced' },
      { name: 'ginger', quantity: '1', unit: 'tbsp, minced' },
      { name: 'green onion', quantity: '3', unit: 'stalks' },
      { name: 'soy sauce', quantity: '1', unit: 'tbsp' },
      { name: 'chili oil', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Brown ground pork in a wok, breaking into small pieces.',
      'Add doubanjiang, garlic, and ginger. Stir-fry until fragrant.',
      'Add 1 cup water and soy sauce, bring to a simmer.',
      'Gently slide in tofu cubes. Simmer 5 minutes without stirring too much.',
      'Thicken with cornstarch slurry. Add Sichuan peppercorn powder.',
      'Drizzle with chili oil, garnish with green onions. Serve with rice.',
    ],
    tags: ['chinese', 'sichuan', 'tofu', 'spicy', 'numbing'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 260,
      protein_g: 16,
      carbs_g: 10,
      fat_g: 18,
      fiber_g: 2,
      sugar_g: 2,
      sodium_mg: 860,
    },
  },
  {
    title: 'Vietnamese Banh Mi',
    description: 'Crispy baguette sandwich with pate, pickled vegetables, cilantro, and jalapeño.',
    cuisine: 'Asian',
    prep_minutes: 20,
    cook_minutes: 10,
    servings: 4,
    calories: 380,
    ingredients: [
      { name: 'baguette', quantity: '4', unit: 'small' },
      { name: 'pork pate', quantity: '1/4', unit: 'cup' },
      { name: 'grilled pork', quantity: '8', unit: 'oz, sliced' },
      { name: 'pickled daikon', quantity: '1/2', unit: 'cup' },
      { name: 'pickled carrot', quantity: '1/2', unit: 'cup' },
      { name: 'cucumber', quantity: '1', unit: 'sliced' },
      { name: 'cilantro', quantity: '1', unit: 'cup' },
      { name: 'jalapeño', quantity: '2', unit: 'sliced' },
      { name: 'mayonnaise', quantity: '2', unit: 'tbsp' },
      { name: 'soy sauce', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Slice baguettes lengthwise, leaving one side attached.',
      'Spread mayonnaise and pate on both sides of the bread.',
      'Layer grilled pork slices on the bottom half.',
      'Add pickled daikon, carrot, and cucumber slices.',
      'Top with fresh cilantro and jalapeño slices.',
      'Drizzle with soy sauce, press sandwich, and serve.',
    ],
    tags: ['vietnamese', 'sandwich', 'pork', 'baguette', 'street-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 22,
      carbs_g: 42,
      fat_g: 14,
      fiber_g: 3,
      sugar_g: 6,
      sodium_mg: 720,
    },
  },
  {
    title: 'Laksa',
    description: 'Malaysian spicy noodle soup with coconut curry broth, shrimp, and tofu puffs.',
    cuisine: 'Asian',
    prep_minutes: 15,
    cook_minutes: 20,
    servings: 4,
    calories: 420,
    ingredients: [
      { name: 'laksa noodles', quantity: '8', unit: 'oz' },
      { name: 'shrimp', quantity: '1/2', unit: 'lb' },
      { name: 'tofu puffs', quantity: '1', unit: 'cup' },
      { name: 'coconut milk', quantity: '2', unit: 'cans (14 oz)' },
      { name: 'laksa paste', quantity: '3', unit: 'tbsp' },
      { name: 'bean sprouts', quantity: '1', unit: 'cup' },
      { name: 'fish cake', quantity: '4', unit: 'sliced' },
      { name: 'lime', quantity: '2', unit: 'wedges' },
      { name: 'cilantro', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Fry laksa paste in oil until fragrant, about 2 minutes.',
      'Add coconut milk and 2 cups of water or broth. Bring to a simmer.',
      'Add shrimp, tofu puffs, and fish cakes. Cook 5 minutes.',
      'Cook laksa noodles separately and divide among bowls.',
      'Ladle the curry broth and toppings over noodles.',
      'Garnish with bean sprouts, cilantro, and lime wedges.',
    ],
    tags: ['malaysian', 'noodle-soup', 'curry', 'coconut', 'spicy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 22,
      carbs_g: 38,
      fat_g: 20,
      fiber_g: 3,
      sugar_g: 5,
      sodium_mg: 860,
    },
  },
  {
    title: 'Char Siu',
    description:
      'Chinese BBQ pork with a glossy, sweet-savory glaze roasted until caramelized edges form.',
    cuisine: 'Asian',
    prep_minutes: 15,
    cook_minutes: 40,
    servings: 6,
    calories: 320,
    ingredients: [
      { name: 'pork shoulder', quantity: '2', unit: 'lb' },
      { name: 'hoisin sauce', quantity: '3', unit: 'tbsp' },
      { name: 'soy sauce', quantity: '2', unit: 'tbsp' },
      { name: 'honey', quantity: '2', unit: 'tbsp' },
      { name: 'five-spice powder', quantity: '1', unit: 'tsp' },
      { name: 'red fermented bean curd', quantity: '1', unit: 'tbsp' },
      { name: 'garlic', quantity: '3', unit: 'cloves, minced' },
      { name: 'rice wine', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Mix hoisin sauce, soy sauce, honey, five-spice, red bean curd, garlic, and rice wine.',
      'Marinate pork shoulder in the mixture for at least 4 hours or overnight.',
      'Roast at 400°F for 30 minutes, basting every 10 minutes.',
      'Increase heat to broil for the last 5 minutes for caramelized edges.',
      'Let rest 10 minutes before slicing.',
      'Slice thinly and serve with steamed rice or in bao buns.',
    ],
    tags: ['chinese', 'bbq', 'pork', 'roasted', 'sweet'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 32,
      carbs_g: 12,
      fat_g: 16,
      fiber_g: 0,
      sugar_g: 10,
      sodium_mg: 780,
    },
  },
  {
    title: 'Yakisoba',
    description: 'Japanese stir-fried noodles with pork, cabbage, and yakisoba sauce.',
    cuisine: 'Asian',
    prep_minutes: 10,
    cook_minutes: 10,
    servings: 4,
    calories: 340,
    ingredients: [
      { name: 'yakisoba noodles', quantity: '2', unit: 'packs (8 oz)' },
      { name: 'pork belly', quantity: '6', unit: 'oz, sliced' },
      { name: 'cabbage', quantity: '2', unit: 'cups, shredded' },
      { name: 'carrot', quantity: '1', unit: 'julienned' },
      { name: 'onion', quantity: '1', unit: 'sliced' },
      { name: 'yakisoba sauce', quantity: '3', unit: 'tbsp' },
      { name: 'aonori', quantity: '1', unit: 'tsp' },
      { name: 'pickled ginger', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Heat oil in a large pan or griddle over high heat.',
      'Stir-fry pork belly until slightly crispy.',
      'Add cabbage, carrot, and onion. Stir-fry 3 minutes.',
      'Add noodles and yakisoba sauce, toss until noodles absorb the sauce.',
      'Serve topped with aonori and pickled ginger.',
    ],
    tags: ['japanese', 'noodles', 'stir-fry', 'pork', 'street-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 340,
      protein_g: 16,
      carbs_g: 40,
      fat_g: 14,
      fiber_g: 3,
      sugar_g: 6,
      sodium_mg: 780,
    },
  },
  {
    title: 'Dan Dan Noodles',
    description:
      'Spicy Sichuan noodles with a savory sesame-chili sauce, ground pork, and pickled mustard greens.',
    cuisine: 'Asian',
    prep_minutes: 10,
    cook_minutes: 10,
    servings: 4,
    calories: 380,
    ingredients: [
      { name: 'wheat noodles', quantity: '8', unit: 'oz' },
      { name: 'ground pork', quantity: '6', unit: 'oz' },
      { name: 'sesame paste', quantity: '2', unit: 'tbsp' },
      { name: 'chili oil', quantity: '3', unit: 'tbsp' },
      { name: 'Sichuan peppercorn powder', quantity: '1/2', unit: 'tsp' },
      { name: 'soy sauce', quantity: '2', unit: 'tbsp' },
      { name: 'pickled mustard greens', quantity: '1/4', unit: 'cup, chopped' },
      { name: 'green onion', quantity: '3', unit: 'stalks, sliced' },
      { name: 'garlic', quantity: '2', unit: 'cloves, minced' },
    ],
    steps: [
      'Cook noodles according to package, drain and set aside.',
      'Brown ground pork with soy sauce and garlic.',
      'Mix sesame paste, chili oil, soy sauce, and Sichuan peppercorn powder in a bowl.',
      'Divide sauce among 4 bowls. Add a splash of noodle water.',
      'Place noodles in bowls and top with ground pork and pickled greens.',
      'Garnish with green onions and serve. Mix before eating.',
    ],
    tags: ['chinese', 'sichuan', 'noodles', 'spicy', 'sesame'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 18,
      carbs_g: 40,
      fat_g: 16,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 820,
    },
  },
  {
    title: 'Satay Skewers',
    description: 'Grilled marinated chicken skewers served with creamy peanut dipping sauce.',
    cuisine: 'Asian',
    prep_minutes: 30,
    cook_minutes: 10,
    servings: 6,
    calories: 280,
    ingredients: [
      { name: 'chicken thigh', quantity: '1', unit: 'lb, cubed' },
      { name: 'coconut milk', quantity: '1/2', unit: 'cup' },
      { name: 'turmeric', quantity: '1', unit: 'tsp' },
      { name: 'lemongrass', quantity: '1', unit: 'stalk, minced' },
      { name: 'peanut butter', quantity: '1/4', unit: 'cup' },
      { name: 'soy sauce', quantity: '2', unit: 'tbsp' },
      { name: 'lime juice', quantity: '2', unit: 'tbsp' },
      { name: 'brown sugar', quantity: '1', unit: 'tbsp' },
      { name: 'bamboo skewers', quantity: '12', unit: 'soaked' },
    ],
    steps: [
      'Marinate chicken cubes in coconut milk, turmeric, lemongrass, and soy sauce for 1 hour.',
      'Thread chicken onto soaked bamboo skewers.',
      'Grill over high heat, turning, until charred and cooked through.',
      'Make peanut sauce: mix peanut butter, soy sauce, lime juice, brown sugar, and water.',
      'Serve skewers hot with peanut dipping sauce and cucumber relish.',
    ],
    tags: ['malaysian', 'indonesian', 'grilled', 'chicken', 'peanut'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 26,
      carbs_g: 10,
      fat_g: 16,
      fiber_g: 2,
      sugar_g: 5,
      sodium_mg: 520,
    },
  },
];

export const asianRecipes = generateCuisineRecipes(configs);

// ── Additional Asian recipes ──────────────────────────────────────────────

const additionalAsianConfigs: CuisineRecipeConfig[] = [
  {
    title: 'Mapo Tofu',
    description: 'Sichuan silken tofu in a fiery, numbing chili-bean sauce with ground pork.',
    cuisine: 'Chinese',
    prep_minutes: 10,
    cook_minutes: 10,
    servings: 4,
    calories: 220,
    ingredients: [
      { name: 'silken tofu', quantity: '1', unit: 'block' },
      { name: 'ground pork', quantity: '4', unit: 'oz' },
      { name: 'doubanjiang', quantity: '2', unit: 'tbsp' },
      { name: 'Sichuan peppercorn', quantity: '1', unit: 'tsp, ground' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
      { name: 'ginger', quantity: '1', unit: 'tsp, minced' },
      { name: 'scallion', quantity: '3', unit: 'cut' },
      { name: 'chili oil', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Brown pork in a wok.',
      'Add doubanjiang, garlic, and ginger. Stir-fry.',
      'Add broth and tofu cubes. Simmer 5 minutes.',
      'Thicken with cornstarch slurry.',
      'Add Sichuan peppercorn and chili oil.',
      'Top with scallions and serve with rice.',
    ],
    tags: ['chinese', 'tofu', 'sichuan', 'spicy', 'mapo'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 220,
      protein_g: 14,
      carbs_g: 6,
      fat_g: 14,
      fiber_g: 1,
      sugar_g: 1,
      sodium_mg: 680,
    },
  },
  {
    title: 'Char Siu',
    description: 'Cantonese BBQ pork with a glossy red glaze of honey, soy, and five-spice.',
    cuisine: 'Chinese',
    prep_minutes: 15,
    cook_minutes: 30,
    servings: 6,
    calories: 320,
    ingredients: [
      { name: 'pork shoulder', quantity: '2', unit: 'lb, strips' },
      { name: 'soy sauce', quantity: '3', unit: 'tbsp' },
      { name: 'hoisin sauce', quantity: '2', unit: 'tbsp' },
      { name: 'honey', quantity: '2', unit: 'tbsp' },
      { name: 'five-spice powder', quantity: '1', unit: 'tsp' },
      { name: 'red fermented bean curd', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Marinate pork in soy, hoisin, honey, five-spice, and bean curd overnight.',
      'Roast at 400°F for 25 minutes, basting with marinade.',
      'Broil 3 minutes for a charred, glossy finish.',
      'Let rest 5 minutes, then slice.',
      'Serve with rice or in bao buns.',
    ],
    tags: ['chinese', 'bbq', 'pork', 'sweet', 'roasted'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 28,
      carbs_g: 14,
      fat_g: 16,
      fiber_g: 0,
      sugar_g: 10,
      sodium_mg: 680,
    },
  },
  {
    title: 'Dan Dan Noodles',
    description: 'Spicy Sichuan noodles with chili oil, sesame paste, and minced pork.',
    cuisine: 'Chinese',
    prep_minutes: 10,
    cook_minutes: 10,
    servings: 4,
    calories: 380,
    ingredients: [
      { name: 'egg noodles', quantity: '8', unit: 'oz' },
      { name: 'ground pork', quantity: '1/2', unit: 'lb' },
      { name: 'chili oil', quantity: '3', unit: 'tbsp' },
      { name: 'sesame paste', quantity: '2', unit: 'tbsp' },
      { name: 'soy sauce', quantity: '2', unit: 'tbsp' },
      { name: 'Sichuan peppercorn', quantity: '1/2', unit: 'tsp' },
      { name: 'scallion', quantity: '3', unit: 'cut' },
      { name: 'peanuts', quantity: '2', unit: 'tbsp, crushed' },
    ],
    steps: [
      'Cook noodles. Set aside.',
      'Brown pork with soy sauce.',
      'Mix chili oil, sesame paste, soy sauce, and Sichuan pepper in bowls.',
      'Add a splash of noodle water to each bowl.',
      'Add noodles and top with pork.',
      'Garnish with scallions and peanuts.',
    ],
    tags: ['chinese', 'noodles', 'sichuan', 'spicy', 'pork'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 16,
      carbs_g: 36,
      fat_g: 18,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 860,
    },
  },
  {
    title: 'Wonton Soup',
    description: 'Delicate pork and shrimp wontons in a clear chicken broth with bok choy.',
    cuisine: 'Chinese',
    prep_minutes: 30,
    cook_minutes: 10,
    servings: 6,
    calories: 180,
    ingredients: [
      { name: 'wonton wrappers', quantity: '40', unit: 'pieces' },
      { name: 'ground pork', quantity: '1/2', unit: 'lb' },
      { name: 'shrimp', quantity: '1/4', unit: 'lb, minced' },
      { name: 'ginger', quantity: '1', unit: 'tsp, minced' },
      { name: 'scallion', quantity: '3', unit: 'minced' },
      { name: 'chicken broth', quantity: '6', unit: 'cups' },
      { name: 'bok choy', quantity: '2', unit: 'cups' },
    ],
    steps: [
      'Mix pork, shrimp, ginger, scallion, soy sauce, and sesame oil.',
      'Wrap filling in wonton skins.',
      'Bring broth to a boil. Add wontons.',
      'Cook 5 minutes until wontons float.',
      'Add bok choy.',
      'Serve in bowls with sesame oil drizzle.',
    ],
    tags: ['chinese', 'soup', 'wonton', 'pork', 'shrimp'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 180,
      protein_g: 12,
      carbs_g: 18,
      fat_g: 6,
      fiber_g: 1,
      sugar_g: 1,
      sodium_mg: 680,
    },
  },
  {
    title: 'Kung Pao Chicken',
    description: 'Spicy stir-fried chicken with peanuts, dried chili, and Sichuan peppercorn.',
    cuisine: 'Chinese',
    prep_minutes: 15,
    cook_minutes: 8,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'chicken breast', quantity: '1', unit: 'lb, cubed' },
      { name: 'peanuts', quantity: '1/4', unit: 'cup' },
      { name: 'dried chili', quantity: '8', unit: 'whole' },
      { name: 'Sichuan peppercorn', quantity: '1', unit: 'tsp' },
      { name: 'soy sauce', quantity: '2', unit: 'tbsp' },
      { name: 'vinegar', quantity: '1', unit: 'tbsp' },
      { name: 'sugar', quantity: '1', unit: 'tbsp' },
      { name: 'scallion', quantity: '3', unit: 'cut' },
    ],
    steps: [
      'Marinate chicken in soy sauce and cornstarch.',
      'Fry dried chili and Sichuan peppercorn in oil until fragrant.',
      'Stir-fry chicken until done.',
      'Add soy sauce, vinegar, and sugar.',
      'Add peanuts and scallion.',
      'Serve with steamed rice.',
    ],
    tags: ['chinese', 'chicken', 'spicy', 'peanuts', 'sichuan'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 26,
      carbs_g: 8,
      fat_g: 14,
      fiber_g: 1,
      sugar_g: 4,
      sodium_mg: 680,
    },
  },
  {
    title: 'Egg Fried Rice',
    description: 'Wok-fried rice with egg, scallion, and soy sauce — the ultimate comfort food.',
    cuisine: 'Chinese',
    prep_minutes: 10,
    cook_minutes: 5,
    servings: 4,
    calories: 320,
    ingredients: [
      { name: 'day-old rice', quantity: '4', unit: 'cups' },
      { name: 'egg', quantity: '3', unit: 'large' },
      { name: 'scallion', quantity: '4', unit: 'cut' },
      { name: 'soy sauce', quantity: '2', unit: 'tbsp' },
      { name: 'sesame oil', quantity: '1', unit: 'tsp' },
      { name: 'oil', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Heat wok over high heat. Add oil.',
      'Scramble eggs, break into pieces.',
      'Add rice, stir-fry until each grain is separate.',
      'Add soy sauce and sesame oil.',
      'Toss in scallion.',
      'Serve immediately.',
    ],
    tags: ['chinese', 'rice', 'egg', 'stir-fry', 'quick'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 10,
      carbs_g: 48,
      fat_g: 8,
      fiber_g: 1,
      sugar_g: 1,
      sodium_mg: 580,
    },
  },
  {
    title: 'Hot and Sour Soup',
    description: 'Chinese soup with tofu, wood ear, bamboo, egg, and a vinegary-chili kick.',
    cuisine: 'Chinese',
    prep_minutes: 10,
    cook_minutes: 10,
    servings: 4,
    calories: 120,
    ingredients: [
      { name: 'tofu', quantity: '1/2', unit: 'block, julienned' },
      { name: 'wood ear mushroom', quantity: '1/4', unit: 'cup, soaked' },
      { name: 'bamboo shoots', quantity: '1/4', unit: 'cup' },
      { name: 'egg', quantity: '1', unit: 'beaten' },
      { name: 'vinegar', quantity: '3', unit: 'tbsp' },
      { name: 'white pepper', quantity: '1/2', unit: 'tsp' },
      { name: 'soy sauce', quantity: '1', unit: 'tbsp' },
      { name: 'chicken broth', quantity: '4', unit: 'cups' },
    ],
    steps: [
      'Bring broth to a boil. Add mushrooms, bamboo, and tofu.',
      'Add soy sauce, vinegar, and white pepper.',
      'Thicken with cornstarch slurry.',
      'Swirl in beaten egg.',
      'Add sesame oil.',
      'Serve hot — should be sour, spicy, and savory.',
    ],
    tags: ['chinese', 'soup', 'tofu', 'spicy', 'sour'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 120,
      protein_g: 8,
      carbs_g: 10,
      fat_g: 4,
      fiber_g: 1,
      sugar_g: 1,
      sodium_mg: 680,
    },
  },
  {
    title: 'Xiao Long Bao',
    description: 'Shanghai soup dumplings with pork filling and a rich gelatin-based broth inside.',
    cuisine: 'Chinese',
    prep_minutes: 45,
    cook_minutes: 8,
    servings: 6,
    calories: 200,
    ingredients: [
      { name: 'dumpling wrappers', quantity: '30', unit: 'pieces' },
      { name: 'ground pork', quantity: '1/2', unit: 'lb' },
      { name: 'pork aspic (gelatin broth)', quantity: '1/4', unit: 'cup, chilled & cubed' },
      { name: 'ginger', quantity: '1', unit: 'tsp, minced' },
      { name: 'soy sauce', quantity: '1', unit: 'tbsp' },
      { name: 'sesame oil', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Mix pork with ginger, soy sauce, and sesame oil.',
      'Add chilled aspic cubes to the filling.',
      'Wrap filling in thin wrappers with pleats.',
      'Steam in bamboo baskets for 8 minutes.',
      'Serve with black vinegar and ginger slivers.',
      'Bite carefully — the soup inside is hot!',
    ],
    tags: ['chinese', 'dumplings', 'shanghai', 'pork', 'steamed'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 200,
      protein_g: 10,
      carbs_g: 20,
      fat_g: 8,
      fiber_g: 0,
      sugar_g: 1,
      sodium_mg: 480,
    },
  },
  {
    title: 'Beijing Duck',
    description:
      'Famous Peking duck with crispy lacquered skin, served with pancakes, hoisin, and scallion.',
    cuisine: 'Chinese',
    prep_minutes: 30,
    cook_minutes: 90,
    servings: 6,
    calories: 380,
    ingredients: [
      { name: 'whole duck', quantity: '1', unit: '(5 lb)' },
      { name: 'hoisin sauce', quantity: '1/4', unit: 'cup' },
      { name: 'mandarin pancakes', quantity: '12', unit: 'pieces' },
      { name: 'scallion', quantity: '6', unit: 'julienned' },
      { name: 'cucumber', quantity: '1', unit: 'julienned' },
      { name: 'honey', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Pump air between skin and meat. Blanch. Dry overnight.',
      'Glaze with honey and roast at 375°F for 90 minutes.',
      'Skin should be thin, crispy, and lacquered.',
      'Carve skin and meat separately.',
      'Spread hoisin on a pancake, add skin, meat, scallion, and cucumber.',
      'Roll up and eat.',
    ],
    tags: ['chinese', 'duck', 'roasted', 'peking', 'festive'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 380,
      protein_g: 28,
      carbs_g: 12,
      fat_g: 22,
      fiber_g: 1,
      sugar_g: 4,
      sodium_mg: 580,
    },
  },
  {
    title: 'Dim Sum (Siu Mai)',
    description: 'Open-topped steamed dumplings with pork and shrimp, a dim sum classic.',
    cuisine: 'Chinese',
    prep_minutes: 25,
    cook_minutes: 8,
    servings: 8,
    calories: 140,
    ingredients: [
      { name: 'wonton wrappers', quantity: '24', unit: 'round' },
      { name: 'ground pork', quantity: '1/2', unit: 'lb' },
      { name: 'shrimp', quantity: '1/4', unit: 'lb, minced' },
      { name: 'shiitake mushroom', quantity: '3', unit: 'minced' },
      { name: 'ginger', quantity: '1', unit: 'tsp, minced' },
      { name: 'soy sauce', quantity: '1', unit: 'tbsp' },
      { name: 'sesame oil', quantity: '1/2', unit: 'tsp' },
    ],
    steps: [
      'Mix pork, shrimp, mushroom, ginger, soy sauce, and sesame oil.',
      'Place filling in the center of a wrapper.',
      'Cup the wrapper around the filling, leaving the top open.',
      'Steam in bamboo baskets for 8 minutes.',
      'Serve with soy sauce and chili oil.',
    ],
    tags: ['chinese', 'dim-sum', 'dumplings', 'steamed', 'shrimp'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 140,
      protein_g: 8,
      carbs_g: 12,
      fat_g: 6,
      fiber_g: 0,
      sugar_g: 1,
      sodium_mg: 380,
    },
  },
];

export const asianAdditionalRecipes = generateCuisineRecipes(additionalAsianConfigs);
