import type { CuisineRecipeConfig } from './types';
import { generateCuisineRecipes } from './types';

const configs: CuisineRecipeConfig[] = [
  {
    title: 'Feijoada',
    description:
      "Brazil's national dish — a hearty black bean stew with assorted smoked and cured meats.",
    cuisine: 'Brazilian',
    prep_minutes: 30,
    cook_minutes: 180,
    servings: 10,
    calories: 480,
    ingredients: [
      { name: 'black beans', quantity: '2', unit: 'lb, soaked overnight' },
      { name: 'smoked pork ribs', quantity: '1', unit: 'lb' },
      { name: 'chorizo', quantity: '8', unit: 'oz' },
      { name: 'bacon', quantity: '8', unit: 'oz' },
      { name: 'pork shoulder', quantity: '1', unit: 'lb' },
      { name: 'beef jerky', quantity: '8', unit: 'oz' },
      { name: 'onion', quantity: '2', unit: 'diced' },
      { name: 'garlic', quantity: '6', unit: 'cloves' },
      { name: 'bay leaf', quantity: '3', unit: 'leaves' },
      { name: 'orange', quantity: '1', unit: 'whole' },
    ],
    steps: [
      'Soak beans overnight. Soak salted meats to remove excess salt.',
      'Simmer beans with bay leaves and orange (keeps beans soft).',
      'Add smoked and cured meats in stages — tougher cuts first.',
      'Sauté onion and garlic, add to the pot.',
      'Simmer 3-4 hours until everything is tender.',
      'Serve with white rice, farofa, collard greens, and orange slices.',
    ],
    tags: ['brazilian', 'stew', 'beans', 'pork', 'national-dish'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 480,
      protein_g: 36,
      carbs_g: 34,
      fat_g: 22,
      fiber_g: 12,
      sugar_g: 3,
      sodium_mg: 1200,
    },
  },
  {
    title: 'Coxinha',
    description:
      'Tear-shaped Brazilian chicken croquettes with creamy filling and crispy potato dough.',
    cuisine: 'Brazilian',
    prep_minutes: 30,
    cook_minutes: 10,
    servings: 12,
    calories: 180,
    ingredients: [
      { name: 'chicken breast', quantity: '1', unit: 'lb, cooked & shredded' },
      { name: 'cream cheese', quantity: '4', unit: 'oz' },
      { name: 'chicken broth', quantity: '2', unit: 'cups' },
      { name: 'flour', quantity: '2', unit: 'cups' },
      { name: 'egg', quantity: '2', unit: 'beaten' },
      { name: 'breadcrumbs', quantity: '1', unit: 'cup' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'oil', quantity: '2', unit: 'cups, for frying' },
    ],
    steps: [
      'Shred cooked chicken and mix with cream cheese and sautéed onion.',
      'Make dough: boil broth, add flour all at once, stir vigorously until dough forms.',
      'Let dough cool, knead until smooth.',
      'Form dough into cups, fill with chicken mixture, shape into teardrops.',
      'Dredge in egg and breadcrumbs.',
      'Deep fry at 350°F until golden. Serve hot.',
    ],
    tags: ['brazilian', 'snack', 'chicken', 'fried', 'street-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 180,
      protein_g: 8,
      carbs_g: 18,
      fat_g: 8,
      fiber_g: 1,
      sugar_g: 1,
      sodium_mg: 380,
    },
  },
  {
    title: 'Pão de Queijo',
    description:
      'Chewy Brazilian cheese bread puffs made with tapioca flour — naturally gluten-free!',
    cuisine: 'Brazilian',
    prep_minutes: 10,
    cook_minutes: 20,
    servings: 12,
    calories: 120,
    ingredients: [
      { name: 'tapioca flour', quantity: '2', unit: 'cups' },
      { name: 'milk', quantity: '1/2', unit: 'cup' },
      { name: 'oil', quantity: '1/4', unit: 'cup' },
      { name: 'egg', quantity: '2', unit: 'large' },
      { name: 'parmesan cheese', quantity: '1', unit: 'cup, grated' },
      { name: 'salt', quantity: '1/2', unit: 'tsp' },
    ],
    steps: [
      'Bring milk, oil, and salt to a boil.',
      'Pour over tapioca flour and stir vigorously until smooth.',
      'Cool slightly, then beat in eggs one at a time.',
      'Mix in grated parmesan.',
      'Scoop into greased muffin tins.',
      'Bake at 400°F for 18-20 minutes until puffed and golden.',
    ],
    tags: ['brazilian', 'bread', 'cheese', 'gluten-free', 'snack'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 120,
      protein_g: 4,
      carbs_g: 14,
      fat_g: 5,
      fiber_g: 0,
      sugar_g: 1,
      sodium_mg: 240,
    },
  },
  {
    title: 'Moqueca',
    description:
      'Brazilian fish stew cooked in a clay pot with coconut milk, palm oil, and peppers.',
    cuisine: 'Brazilian',
    prep_minutes: 20,
    cook_minutes: 25,
    servings: 6,
    calories: 320,
    ingredients: [
      { name: 'white fish', quantity: '1.5', unit: 'lb, chunked' },
      { name: 'coconut milk', quantity: '1', unit: 'can (14 oz)' },
      { name: 'dendê oil (palm oil)', quantity: '2', unit: 'tbsp' },
      { name: 'bell pepper', quantity: '2', unit: 'sliced' },
      { name: 'onion', quantity: '1', unit: 'sliced' },
      { name: 'tomato', quantity: '2', unit: 'diced' },
      { name: 'lime juice', quantity: '2', unit: 'tbsp' },
      { name: 'cilantro', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Marinate fish in lime juice, salt, and garlic.',
      'Layer onion, pepper, and tomato in a clay pot.',
      'Place fish on top, drizzle with dendê oil.',
      'Pour coconut milk over. Cover and simmer 20 minutes.',
      'Do not stir — shake the pot gently.',
      'Garnish with cilantro and serve with rice.',
    ],
    tags: ['brazilian', 'fish', 'stew', 'coconut', 'clay-pot'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 320,
      protein_g: 32,
      carbs_g: 8,
      fat_g: 16,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 480,
    },
  },
  {
    title: 'Brigadeiro',
    description: 'Fudgy Brazilian chocolate truffles made with condensed milk and cocoa.',
    cuisine: 'Brazilian',
    prep_minutes: 10,
    cook_minutes: 10,
    servings: 20,
    calories: 80,
    ingredients: [
      { name: 'condensed milk', quantity: '1', unit: 'can (14 oz)' },
      { name: 'cocoa powder', quantity: '3', unit: 'tbsp' },
      { name: 'butter', quantity: '1', unit: 'tbsp' },
      { name: 'chocolate sprinkles', quantity: '1', unit: 'cup' },
    ],
    steps: [
      'Combine condensed milk, cocoa, and butter in a pan.',
      'Cook over medium-low heat, stirring constantly.',
      'Cook until mixture thickens and pulls away from the pan, about 10 minutes.',
      'Cool completely.',
      'Roll into small balls.',
      'Roll in chocolate sprinkles. Place in mini cupcake liners.',
    ],
    tags: ['brazilian', 'dessert', 'chocolate', 'truffle', 'party'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 80,
      protein_g: 1,
      carbs_g: 14,
      fat_g: 2,
      fiber_g: 0,
      sugar_g: 12,
      sodium_mg: 20,
    },
  },
  {
    title: 'Açaí Bowl',
    description: 'Thick frozen açaí smoothie bowl topped with granola, banana, and honey.',
    cuisine: 'Brazilian',
    prep_minutes: 5,
    cook_minutes: 0,
    servings: 2,
    calories: 280,
    ingredients: [
      { name: 'frozen açaí pulp', quantity: '2', unit: 'packs (3.5 oz each)' },
      { name: 'banana', quantity: '1', unit: 'frozen' },
      { name: 'granola', quantity: '1/2', unit: 'cup' },
      { name: 'honey', quantity: '1', unit: 'tbsp' },
      { name: 'fresh fruit', quantity: '1/2', unit: 'cup, for topping' },
      { name: 'coconut flakes', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Blend frozen açaí and banana until very thick and smooth.',
      'Pour into bowls.',
      'Top with granola.',
      'Add fresh fruit and coconut flakes.',
      'Drizzle with honey.',
      'Eat immediately before it melts!',
    ],
    tags: ['brazilian', 'breakfast', 'smoothie-bowl', 'açaí', 'healthy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 4,
      carbs_g: 48,
      fat_g: 8,
      fiber_g: 6,
      sugar_g: 28,
      sodium_mg: 40,
    },
  },
  {
    title: 'Churrasco',
    description:
      'Brazilian BBQ with various grilled meats carved tableside, served with farofa and vinaigrette.',
    cuisine: 'Brazilian',
    prep_minutes: 20,
    cook_minutes: 20,
    servings: 8,
    calories: 420,
    ingredients: [
      { name: 'picanha (rump cap)', quantity: '2', unit: 'lb' },
      { name: 'garlic', quantity: '4', unit: 'cloves, minced' },
      { name: 'coarse salt', quantity: '2', unit: 'tbsp' },
      { name: 'farofa', quantity: '1', unit: 'cup' },
      { name: 'vinaigrette salsa', quantity: '1', unit: 'cup' },
      { name: 'chimichurri', quantity: '1/2', unit: 'cup' },
    ],
    steps: [
      'Score picanha fat cap. Season heavily with coarse salt and garlic.',
      'Skewer the meat curved side up.',
      'Grill over hot charcoal, turning, until medium-rare.',
      'Slice thin pieces off the skewer at the table.',
      'Serve with farofa (toasted cassava flour) and vinaigrette salsa.',
      'Continue grilling and slicing as you eat.',
    ],
    tags: ['brazilian', 'bbq', 'beef', 'grilled', 'churrasco'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 420,
      protein_g: 42,
      carbs_g: 4,
      fat_g: 26,
      fiber_g: 1,
      sugar_g: 1,
      sodium_mg: 680,
    },
  },
  {
    title: 'Vatapá',
    description:
      'Creamy Afro-Brazilian stew with shrimp, coconut milk, peanuts, and dendê oil over rice.',
    cuisine: 'Brazilian',
    prep_minutes: 20,
    cook_minutes: 25,
    servings: 6,
    calories: 340,
    ingredients: [
      { name: 'shrimp', quantity: '1', unit: 'lb' },
      { name: 'coconut milk', quantity: '1', unit: 'can (14 oz)' },
      { name: 'peanuts', quantity: '1/4', unit: 'cup, ground' },
      { name: 'cashews', quantity: '1/4', unit: 'cup, ground' },
      { name: 'dendê oil', quantity: '2', unit: 'tbsp' },
      { name: 'bread', quantity: '2', unit: 'slices, soaked' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'ginger', quantity: '1', unit: 'tsp, grated' },
    ],
    steps: [
      'Soak bread in coconut milk. Blend with peanuts and cashews.',
      'Sauté onion and ginger in dendê oil.',
      'Add shrimp and cook until pink.',
      'Add the coconut-nut paste. Stir well.',
      'Simmer until thick and creamy, about 15 minutes.',
      'Serve over white rice.',
    ],
    tags: ['brazilian', 'stew', 'shrimp', 'coconut', 'afro-brazilian'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 340,
      protein_g: 22,
      carbs_g: 16,
      fat_g: 22,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 580,
    },
  },
  {
    title: 'Caipirinha',
    description: "Brazil's national cocktail — cachaça, lime, and sugar muddled with ice.",
    cuisine: 'Brazilian',
    prep_minutes: 3,
    cook_minutes: 0,
    servings: 1,
    calories: 180,
    ingredients: [
      { name: 'cachaça', quantity: '2', unit: 'oz' },
      { name: 'lime', quantity: '1', unit: 'quartered' },
      { name: 'sugar', quantity: '2', unit: 'tsp' },
      { name: 'ice', quantity: '1', unit: 'cup' },
    ],
    steps: [
      'Cut lime into quarters, place in a glass.',
      'Add sugar.',
      'Muddle lime and sugar together.',
      'Add ice.',
      'Pour cachaça over.',
      'Stir and serve.',
    ],
    tags: ['brazilian', 'cocktail', 'cachaca', 'lime', 'drink'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 180,
      protein_g: 0,
      carbs_g: 14,
      fat_g: 0,
      fiber_g: 0,
      sugar_g: 12,
      sodium_mg: 0,
    },
  },
  {
    title: 'Tapioca Crepe',
    description: 'Brazilian cassava starch crepe filled with cheese, ham, or sweet fillings.',
    cuisine: 'Brazilian',
    prep_minutes: 5,
    cook_minutes: 5,
    servings: 4,
    calories: 200,
    ingredients: [
      { name: 'tapioca starch (goma)', quantity: '1', unit: 'cup' },
      { name: 'water', quantity: '1/4', unit: 'cup' },
      { name: 'mozzarella cheese', quantity: '1/2', unit: 'cup, shredded' },
      { name: 'ham', quantity: '4', unit: 'slices' },
      { name: 'butter', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Moisten tapioca starch with water and sift to create a sandy texture.',
      'Heat a non-stick pan. Sprinkle a thin layer of the moist starch.',
      'It will fuse into a crepe-like disc as it heats.',
      'Add cheese and ham to one half.',
      'Fold over and cook until cheese melts.',
      'Serve immediately.',
    ],
    tags: ['brazilian', 'crepe', 'tapioca', 'gluten-free', 'breakfast'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 200,
      protein_g: 10,
      carbs_g: 22,
      fat_g: 8,
      fiber_g: 0,
      sugar_g: 1,
      sodium_mg: 380,
    },
  },
  {
    title: 'Bolo de Fubá',
    description:
      'Brazilian cornmeal cake with a tender crumb, flavored with fennel seeds and coconut.',
    cuisine: 'Brazilian',
    prep_minutes: 15,
    cook_minutes: 35,
    servings: 12,
    calories: 180,
    ingredients: [
      { name: 'cornmeal (fubá)', quantity: '1', unit: 'cup' },
      { name: 'flour', quantity: '1', unit: 'cup' },
      { name: 'sugar', quantity: '1', unit: 'cup' },
      { name: 'butter', quantity: '1/2', unit: 'cup' },
      { name: 'egg', quantity: '3', unit: 'large' },
      { name: 'milk', quantity: '1', unit: 'cup' },
      { name: 'coconut', quantity: '1/2', unit: 'cup, shredded' },
      { name: 'baking powder', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Cream butter and sugar. Add eggs one at a time.',
      'Mix cornmeal, flour, and baking powder.',
      'Alternate adding dry ingredients and milk.',
      'Fold in shredded coconut.',
      'Pour into a greased tube pan.',
      'Bake at 350°F for 35 minutes until golden.',
    ],
    tags: ['brazilian', 'cake', 'cornmeal', 'coconut', 'dessert'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 180,
      protein_g: 3,
      carbs_g: 26,
      fat_g: 7,
      fiber_g: 1,
      sugar_g: 14,
      sodium_mg: 120,
    },
  },
];

export const brazilianRecipes = generateCuisineRecipes(configs);
