import type { CuisineRecipeConfig } from './types';
import { generateCuisineRecipes } from './types';

const configs: CuisineRecipeConfig[] = [
  {
    title: 'Fish and Chips',
    description: 'Beer-battered cod with thick-cut chips, mushy peas, and tartar sauce.',
    cuisine: 'British',
    prep_minutes: 20,
    cook_minutes: 20,
    servings: 4,
    calories: 580,
    ingredients: [
      { name: 'cod fillets', quantity: '4', unit: 'pieces' },
      { name: 'beer', quantity: '1', unit: 'cup, cold' },
      { name: 'flour', quantity: '1.5', unit: 'cups' },
      { name: 'potatoes', quantity: '4', unit: 'large, cut into chips' },
      { name: 'vegetable oil', quantity: '4', unit: 'cups, for frying' },
      { name: 'baking powder', quantity: '1', unit: 'tsp' },
      { name: 'mushy peas', quantity: '1', unit: 'cup' },
      { name: 'tartar sauce', quantity: '1/2', unit: 'cup' },
    ],
    steps: [
      'Fry chips at 325°F for 5 minutes until soft. Remove and increase oil to 375°F.',
      'Make batter: whisk flour, baking powder, salt, and cold beer until smooth.',
      'Dip cod in batter, fry at 375°F for 4-5 minutes until golden and crispy.',
      'Refry chips at 375°F for 2-3 minutes until crispy. Serve with mushy peas and tartar sauce.',
    ],
    tags: ['fish and chips', 'british', 'fried', 'cod', 'pub food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 580,
      protein_g: 28,
      carbs_g: 56,
      fat_g: 28,
      fiber_g: 4,
      sugar_g: 3,
      sodium_mg: 680,
    },
  },
  {
    title: "Shepherd's Pie",
    description: 'Lamb and vegetable filling topped with creamy mashed potatoes and baked golden.',
    cuisine: 'British',
    prep_minutes: 25,
    cook_minutes: 35,
    servings: 6,
    calories: 420,
    ingredients: [
      { name: 'ground lamb', quantity: '1.5', unit: 'lbs' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'carrot', quantity: '2', unit: 'diced' },
      { name: 'peas', quantity: '1', unit: 'cup' },
      { name: 'tomato paste', quantity: '2', unit: 'tbsp' },
      { name: 'potatoes', quantity: '3', unit: 'lbs, mashed' },
      { name: 'butter', quantity: '3', unit: 'tbsp' },
      { name: 'milk', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Brown lamb with onion, carrot, and garlic. Add tomato paste and broth. Simmer 15 minutes.',
      'Add peas and season with thyme, rosemary, salt, and pepper.',
      'Spread lamb mixture in a baking dish. Top with creamy mashed potatoes.',
      'Bake at 400°F for 25 minutes until top is golden and filling is bubbly.',
    ],
    tags: ["shepherd's pie", 'british', 'lamb', 'pie', 'comfort food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 26,
      carbs_g: 36,
      fat_g: 20,
      fiber_g: 4,
      sugar_g: 5,
      sodium_mg: 520,
    },
  },
  {
    title: 'Scones with Clotted Cream',
    description:
      'Tender British scones served with clotted cream and strawberry jam for afternoon tea.',
    cuisine: 'British',
    prep_minutes: 15,
    cook_minutes: 15,
    servings: 8,
    calories: 320,
    ingredients: [
      { name: 'all-purpose flour', quantity: '3', unit: 'cups' },
      { name: 'butter', quantity: '1/2', unit: 'cup, cold, cubed' },
      { name: 'sugar', quantity: '1/4', unit: 'cup' },
      { name: 'baking powder', quantity: '2', unit: 'tsp' },
      { name: 'milk', quantity: '3/4', unit: 'cup' },
      { name: 'egg', quantity: '1', unit: 'for wash' },
      { name: 'clotted cream', quantity: '1', unit: 'cup' },
      { name: 'strawberry jam', quantity: '1/2', unit: 'cup' },
    ],
    steps: [
      'Rub cold butter into flour, sugar, and baking powder until crumbly.',
      'Add milk and mix gently until dough comes together. Pat into a round, cut into wedges.',
      'Brush with egg wash and bake at 400°F for 12-15 minutes until golden.',
      'Split warm scones and serve with clotted cream and jam.',
    ],
    tags: ['scones', 'tea', 'british', 'baking', 'cream'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 6,
      carbs_g: 38,
      fat_g: 16,
      fiber_g: 1,
      sugar_g: 12,
      sodium_mg: 340,
    },
  },
  {
    title: 'Sunday Roast Beef',
    description: 'Classic British roast beef with Yorkshire pudding, roast potatoes, and gravy.',
    cuisine: 'British',
    prep_minutes: 30,
    cook_minutes: 120,
    servings: 8,
    calories: 520,
    ingredients: [
      { name: 'beef rib roast', quantity: '4', unit: 'lbs' },
      { name: 'flour', quantity: '1', unit: 'cup' },
      { name: 'eggs', quantity: '3', unit: 'large' },
      { name: 'milk', quantity: '1', unit: 'cup' },
      { name: 'potatoes', quantity: '4', unit: 'large, quartered' },
      { name: 'beef drippings', quantity: '2', unit: 'tbsp' },
      { name: 'horseradish sauce', quantity: '1/4', unit: 'cup' },
      { name: 'gravy', quantity: '2', unit: 'cups' },
    ],
    steps: [
      'Season beef and roast at 450°F for 20 minutes, then reduce to 325°F for 90 minutes.',
      'Make Yorkshire pudding batter: whisk flour, eggs, and milk. Rest 30 minutes.',
      'Roast potatoes in beef drippings at 400°F for 45 minutes until crispy.',
      'Pour Yorkshire batter into hot drippings, bake at 425°F for 20 minutes until puffed. Serve with gravy.',
    ],
    tags: ['roast beef', 'sunday roast', 'british', 'yorkshire pudding', 'traditional'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 520,
      protein_g: 42,
      carbs_g: 28,
      fat_g: 28,
      fiber_g: 2,
      sugar_g: 2,
      sodium_mg: 580,
    },
  },
  {
    title: 'Sticky Toffee Pudding',
    description:
      'Moist date sponge drenched in warm toffee sauce, served with custard or ice cream.',
    cuisine: 'British',
    prep_minutes: 20,
    cook_minutes: 30,
    servings: 8,
    calories: 480,
    ingredients: [
      { name: 'dates', quantity: '1.5', unit: 'cups, pitted and chopped' },
      { name: 'boiling water', quantity: '1', unit: 'cup' },
      { name: 'flour', quantity: '1.5', unit: 'cups' },
      { name: 'butter', quantity: '1/2', unit: 'cup' },
      { name: 'brown sugar', quantity: '3/4', unit: 'cup' },
      { name: 'eggs', quantity: '2', unit: 'large' },
      { name: 'heavy cream', quantity: '1', unit: 'cup' },
      { name: 'vanilla extract', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Soak dates in boiling water for 10 minutes, then mash.',
      'Cream butter and sugar, beat in eggs. Fold in flour and date mixture. Bake at 350°F for 25 minutes.',
      'Make toffee sauce: simmer brown sugar, butter, and heavy cream until thick.',
      'Pour warm toffee sauce over pudding. Serve with custard or vanilla ice cream.',
    ],
    tags: ['sticky toffee', 'pudding', 'british', 'dessert', 'date'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 480,
      protein_g: 6,
      carbs_g: 64,
      fat_g: 24,
      fiber_g: 3,
      sugar_g: 48,
      sodium_mg: 280,
    },
  },
  {
    title: 'Bangers and Mash',
    description: 'Pork sausages with creamy mashed potatoes and onion gravy.',
    cuisine: 'British',
    prep_minutes: 15,
    cook_minutes: 25,
    servings: 4,
    calories: 480,
    ingredients: [
      { name: 'pork sausages', quantity: '8', unit: 'links' },
      { name: 'potatoes', quantity: '2', unit: 'lbs, mashed' },
      { name: 'onion', quantity: '2', unit: 'sliced' },
      { name: 'beef broth', quantity: '1', unit: 'cup' },
      { name: 'butter', quantity: '3', unit: 'tbsp' },
      { name: 'milk', quantity: '1/4', unit: 'cup' },
      { name: 'flour', quantity: '1', unit: 'tbsp' },
      { name: 'Worcestershire sauce', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Pan-fry sausages until browned and cooked through, about 15 minutes.',
      'Caramelize onions in butter, add flour, then broth and Worcestershire. Simmer for gravy.',
      'Boil and mash potatoes with butter and milk.',
      'Serve sausages over mash with onion gravy.',
    ],
    tags: ['bangers and mash', 'british', 'sausage', 'mash', 'comfort food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 480,
      protein_g: 22,
      carbs_g: 42,
      fat_g: 26,
      fiber_g: 3,
      sugar_g: 4,
      sodium_mg: 820,
    },
  },
  {
    title: 'Full English Breakfast',
    description: 'Traditional fry-up with eggs, bacon, sausage, baked beans, mushrooms, and toast.',
    cuisine: 'British',
    prep_minutes: 15,
    cook_minutes: 20,
    servings: 2,
    calories: 720,
    ingredients: [
      { name: 'eggs', quantity: '4', unit: 'large, fried' },
      { name: 'back bacon', quantity: '4', unit: 'rashers' },
      { name: 'pork sausages', quantity: '4', unit: 'links' },
      { name: 'baked beans', quantity: '1', unit: 'can' },
      { name: 'mushrooms', quantity: '4', unit: 'large, halved' },
      { name: 'tomato', quantity: '2', unit: 'halved' },
      { name: 'toast', quantity: '4', unit: 'slices' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Grill or fry bacon and sausages until cooked through.',
      'Fry eggs sunny-side up. Sauté mushrooms and grill tomato halves.',
      'Heat baked beans in a saucepan.',
      'Plate everything together with buttered toast.',
    ],
    tags: ['full english', 'breakfast', 'british', 'fry-up', 'traditional'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 720,
      protein_g: 44,
      carbs_g: 48,
      fat_g: 38,
      fiber_g: 6,
      sugar_g: 10,
      sodium_mg: 1420,
    },
  },
  {
    title: 'Beef Wellington',
    description: 'Tender beef fillet wrapped in mushroom duxelles and puff pastry, roasted golden.',
    cuisine: 'British',
    prep_minutes: 45,
    cook_minutes: 30,
    servings: 8,
    calories: 520,
    ingredients: [
      { name: 'beef tenderloin', quantity: '2', unit: 'lbs' },
      { name: 'mushrooms', quantity: '1', unit: 'lb, finely chopped' },
      { name: 'puff pastry', quantity: '1', unit: 'sheet' },
      { name: 'prosciutto', quantity: '6', unit: 'slices' },
      { name: 'Dijon mustard', quantity: '2', unit: 'tbsp' },
      { name: 'egg', quantity: '1', unit: 'beaten for wash' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
      { name: 'shallot', quantity: '2', unit: 'minced' },
    ],
    steps: [
      'Sear beef on all sides. Brush with Dijon mustard. Chill.',
      'Cook mushrooms and shallots in butter until dry (duxelles). Cool.',
      'Layer prosciutto on plastic wrap, spread duxelles, roll beef tightly. Chill 30 minutes.',
      'Wrap in puff pastry, brush with egg wash. Bake at 425°F for 25-30 minutes. Rest 10 minutes.',
    ],
    tags: ['beef wellington', 'british', 'beef', 'puff pastry', 'elegant'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 520,
      protein_g: 38,
      carbs_g: 22,
      fat_g: 32,
      fiber_g: 2,
      sugar_g: 2,
      sodium_mg: 620,
    },
  },
  {
    title: 'Cornish Pasty',
    description: "Handheld pastry filled with beef, potato, rutabaga, and onion — a miner's lunch.",
    cuisine: 'British',
    prep_minutes: 30,
    cook_minutes: 45,
    servings: 6,
    calories: 440,
    ingredients: [
      { name: 'beef skirt', quantity: '1', unit: 'lb, diced' },
      { name: 'potato', quantity: '2', unit: 'medium, diced' },
      { name: 'rutabaga', quantity: '1', unit: 'cup, diced' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'shortcrust pastry', quantity: '1', unit: 'batch' },
      { name: 'egg wash', quantity: '1', unit: 'egg, beaten' },
      { name: 'salt', quantity: '1', unit: 'tsp' },
      { name: 'pepper', quantity: '1/2', unit: 'tsp' },
    ],
    steps: [
      'Roll pastry and cut into circles. Fill with raw beef, potato, rutabaga, and onion.',
      'Season well with salt and pepper. Fold over and crimp edges tightly.',
      'Cut a small slit for steam. Brush with egg wash.',
      'Bake at 375°F for 40-45 minutes until golden brown.',
    ],
    tags: ['pasty', 'cornish', 'british', 'beef', 'handheld'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 440,
      protein_g: 22,
      carbs_g: 36,
      fat_g: 24,
      fiber_g: 3,
      sugar_g: 3,
      sodium_mg: 520,
    },
  },
  {
    title: 'Toad in the Hole',
    description: 'Pork sausages baked in Yorkshire pudding batter until puffed and golden.',
    cuisine: 'British',
    prep_minutes: 10,
    cook_minutes: 30,
    servings: 4,
    calories: 460,
    ingredients: [
      { name: 'pork sausages', quantity: '8', unit: 'links' },
      { name: 'flour', quantity: '1', unit: 'cup' },
      { name: 'eggs', quantity: '3', unit: 'large' },
      { name: 'milk', quantity: '1', unit: 'cup' },
      { name: 'beef drippings', quantity: '2', unit: 'tbsp' },
      { name: 'onion gravy', quantity: '2', unit: 'cups' },
    ],
    steps: [
      'Brown sausages in a skillet. Place in a baking dish with hot beef drippings.',
      'Whisk flour, eggs, milk, and salt into a smooth batter. Pour over sausages.',
      'Bake at 425°F for 25-30 minutes until puffed and golden. Do not open the oven!',
      'Serve with onion gravy.',
    ],
    tags: ['toad in the hole', 'british', 'sausage', 'yorkshire', 'comfort food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 460,
      protein_g: 22,
      carbs_g: 32,
      fat_g: 28,
      fiber_g: 1,
      sugar_g: 3,
      sodium_mg: 780,
    },
  },
  {
    title: "Ploughman's Lunch",
    description: 'Cold British pub platter of cheddar, pickle, bread, ham, and pickled onions.',
    cuisine: 'British',
    prep_minutes: 10,
    cook_minutes: 0,
    servings: 2,
    calories: 520,
    ingredients: [
      { name: 'cheddar cheese', quantity: '8', unit: 'oz, thick slices' },
      { name: 'crusty bread', quantity: '1', unit: 'loaf' },
      { name: 'branston pickle', quantity: '1/4', unit: 'cup' },
      { name: 'ham', quantity: '4', unit: 'oz, sliced' },
      { name: 'pickled onions', quantity: '4', unit: 'small' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
      { name: 'apple', quantity: '1', unit: 'sliced' },
      { name: 'lettuce', quantity: '4', unit: 'leaves' },
    ],
    steps: [
      'Slice bread and spread with butter.',
      'Arrange cheese, ham, and pickle on a platter.',
      'Add pickled onions, apple slices, and lettuce.',
      'Serve as a cold lunch with ale or cider.',
    ],
    tags: ["ploughman's", 'british', 'cheese', 'pub', 'cold'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 520,
      protein_g: 28,
      carbs_g: 44,
      fat_g: 28,
      fiber_g: 4,
      sugar_g: 12,
      sodium_mg: 1080,
    },
  },
  {
    title: 'Eton Mess',
    description: 'Whipped cream folded with crushed meringue and fresh strawberries.',
    cuisine: 'British',
    prep_minutes: 15,
    cook_minutes: 0,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'meringue nests', quantity: '4', unit: 'crushed' },
      { name: 'heavy cream', quantity: '1.5', unit: 'cups, whipped' },
      { name: 'strawberries', quantity: '2', unit: 'cups, sliced' },
      { name: 'vanilla extract', quantity: '1', unit: 'tsp' },
      { name: 'sugar', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Whip cream with vanilla and sugar until soft peaks.',
      'Hull and slice strawberries. Reserve a few for garnish.',
      'Gently fold crushed meringue and most strawberries into the cream.',
      'Spoon into glasses and top with remaining strawberries.',
    ],
    tags: ['eton mess', 'british', 'dessert', 'strawberry', 'meringue'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 3,
      carbs_g: 30,
      fat_g: 16,
      fiber_g: 2,
      sugar_g: 24,
      sodium_mg: 80,
    },
  },
  {
    title: 'Steak and Kidney Pie',
    description: 'Rich beef and kidney stew topped with flaky pastry — a British pub classic.',
    cuisine: 'British',
    prep_minutes: 25,
    cook_minutes: 120,
    servings: 6,
    calories: 480,
    ingredients: [
      { name: 'beef stew meat', quantity: '1.5', unit: 'lbs' },
      { name: 'lamb kidney', quantity: '8', unit: 'oz, trimmed' },
      { name: 'onion', quantity: '2', unit: 'diced' },
      { name: 'beef broth', quantity: '2', unit: 'cups' },
      { name: 'flour', quantity: '2', unit: 'tbsp' },
      { name: 'Worcestershire sauce', quantity: '2', unit: 'tbsp' },
      { name: 'puff pastry', quantity: '1', unit: 'sheet' },
      { name: 'egg wash', quantity: '1', unit: 'egg, beaten' },
    ],
    steps: [
      'Brown beef and kidney in batches. Add onion and flour. Cook 2 minutes.',
      'Add broth and Worcestershire. Simmer 90 minutes until meat is tender.',
      'Transfer to a pie dish. Top with puff pastry and brush with egg wash.',
      'Bake at 400°F for 25-30 minutes until pastry is golden and puffed.',
    ],
    tags: ['steak and kidney', 'pie', 'british', 'pub', 'pastry'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 480,
      protein_g: 30,
      carbs_g: 28,
      fat_g: 26,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 620,
    },
  },
  {
    title: 'Trifle',
    description:
      'Layered British dessert of sherry-soaked sponge, custard, fruit, and whipped cream.',
    cuisine: 'British',
    prep_minutes: 25,
    cook_minutes: 10,
    servings: 8,
    calories: 340,
    ingredients: [
      { name: 'sponge cake', quantity: '1', unit: 'lb, sliced' },
      { name: 'sherry', quantity: '1/4', unit: 'cup' },
      { name: 'raspberries', quantity: '2', unit: 'cups' },
      { name: 'custard', quantity: '2', unit: 'cups' },
      { name: 'heavy cream', quantity: '1', unit: 'cup, whipped' },
      { name: 'sliced almonds', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Layer sponge cake in a trifle dish and drizzle with sherry.',
      'Add a layer of raspberries, then pour custard over.',
      'Top with whipped cream and spread evenly.',
      'Garnish with sliced almonds and a few raspberries. Chill 2 hours before serving.',
    ],
    tags: ['trifle', 'british', 'dessert', 'custard', 'layered'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 340,
      protein_g: 6,
      carbs_g: 40,
      fat_g: 16,
      fiber_g: 3,
      sugar_g: 28,
      sodium_mg: 160,
    },
  },
  {
    title: 'Cottage Pie',
    description:
      "Ground beef and vegetable filling topped with mashed potatoes — the beef cousin of shepherd's pie.",
    cuisine: 'British',
    prep_minutes: 20,
    cook_minutes: 35,
    servings: 6,
    calories: 400,
    ingredients: [
      { name: 'ground beef', quantity: '1.5', unit: 'lbs' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'carrot', quantity: '2', unit: 'diced' },
      { name: 'peas', quantity: '1', unit: 'cup' },
      { name: 'beef broth', quantity: '1', unit: 'cup' },
      { name: 'potatoes', quantity: '3', unit: 'lbs, mashed' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
      { name: 'cheddar cheese', quantity: '1/2', unit: 'cup, grated' },
    ],
    steps: [
      'Brown beef with onion and carrot. Add broth and tomato paste. Simmer 15 minutes.',
      'Add peas and season with Worcestershire, salt, and pepper.',
      'Spread beef mixture in a dish. Top with mashed potatoes and grated cheddar.',
      'Bake at 400°F for 25 minutes until top is golden and bubbly.',
    ],
    tags: ['cottage pie', 'british', 'beef', 'pie', 'comfort food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 400,
      protein_g: 28,
      carbs_g: 34,
      fat_g: 16,
      fiber_g: 4,
      sugar_g: 4,
      sodium_mg: 560,
    },
  },
];

export const britishRecipes = generateCuisineRecipes(configs);
