import type { CuisineRecipeConfig } from './types';
import { generateCuisineRecipes } from './types';

const configs: CuisineRecipeConfig[] = [
  {
    title: 'Jerk Chicken',
    description:
      'Smoky, spicy Jamaican grilled chicken marinated in scotch bonnet, allspice, and thyme.',
    cuisine: 'Caribbean',
    prep_minutes: 20,
    cook_minutes: 45,
    servings: 6,
    calories: 380,
    ingredients: [
      { name: 'chicken pieces', quantity: '3', unit: 'lbs' },
      { name: 'scotch bonnet pepper', quantity: '3', unit: 'whole' },
      { name: 'allspice berries', quantity: '1', unit: 'tbsp, ground' },
      { name: 'thyme', quantity: '2', unit: 'tsp' },
      { name: 'garlic', quantity: '4', unit: 'cloves' },
      { name: 'ginger', quantity: '1', unit: 'tbsp, grated' },
      { name: 'soy sauce', quantity: '2', unit: 'tbsp' },
      { name: 'brown sugar', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Blend scotch bonnet, allspice, thyme, garlic, ginger, soy sauce, and brown sugar into a paste.',
      'Rub jerk paste all over chicken pieces. Marinate at least 4 hours or overnight.',
      'Grill over indirect heat (or bake at 350°F) for 35-45 minutes until cooked through.',
      'Serve with rice and peas, fried plantains, and a squeeze of lime.',
    ],
    tags: ['jerk', 'jamaican', 'chicken', 'grilled', 'spicy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 380,
      protein_g: 36,
      carbs_g: 6,
      fat_g: 24,
      fiber_g: 1,
      sugar_g: 3,
      sodium_mg: 480,
    },
  },
  {
    title: 'Rice and Peas',
    description: 'Jamaican coconut rice cooked with red kidney beans and thyme.',
    cuisine: 'Caribbean',
    prep_minutes: 10,
    cook_minutes: 30,
    servings: 6,
    calories: 280,
    ingredients: [
      { name: 'long grain rice', quantity: '2', unit: 'cups' },
      { name: 'coconut milk', quantity: '1', unit: 'can' },
      { name: 'red kidney beans', quantity: '1', unit: 'can, drained' },
      { name: 'green onion', quantity: '3', unit: 'stalks' },
      { name: 'thyme', quantity: '3', unit: 'sprigs' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
      { name: 'scotch bonnet pepper', quantity: '1', unit: 'whole' },
      { name: 'salt', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Rinse rice until water runs clear.',
      'Combine rice, coconut milk, beans, green onion, thyme, garlic, and whole scotch bonnet in a pot.',
      'Bring to boil, then reduce to low. Cook covered 20-25 minutes until rice is fluffy.',
      'Remove scotch bonnet and thyme sprigs before serving. Fluff with a fork.',
    ],
    tags: ['rice and peas', 'jamaican', 'coconut', 'beans', 'vegan'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 8,
      carbs_g: 46,
      fat_g: 8,
      fiber_g: 5,
      sugar_g: 2,
      sodium_mg: 280,
    },
  },
  {
    title: 'Fried Plantains',
    description: 'Sweet ripe plantains sliced and fried until caramelized and golden.',
    cuisine: 'Caribbean',
    prep_minutes: 5,
    cook_minutes: 10,
    servings: 4,
    calories: 220,
    ingredients: [
      { name: 'ripe plantains', quantity: '3', unit: 'very ripe' },
      { name: 'vegetable oil', quantity: '1/4', unit: 'cup' },
      { name: 'salt', quantity: '1/4', unit: 'tsp' },
    ],
    steps: [
      'Peel plantains and slice diagonally into 1/2 inch pieces.',
      'Heat oil in a skillet over medium heat.',
      'Fry plantain slices 2-3 minutes per side until golden and caramelized.',
      'Drain on paper towels and sprinkle with salt.',
    ],
    tags: ['plantain', 'fried', 'side dish', 'vegan', 'sweet'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 220,
      protein_g: 2,
      carbs_g: 34,
      fat_g: 10,
      fiber_g: 3,
      sugar_g: 16,
      sodium_mg: 140,
    },
  },
  {
    title: 'Callaloo',
    description: 'Trinidadian leafy green stew with coconut milk, okra, and crab.',
    cuisine: 'Caribbean',
    prep_minutes: 15,
    cook_minutes: 30,
    servings: 4,
    calories: 240,
    ingredients: [
      { name: 'callaloo leaves', quantity: '1', unit: 'lb, chopped' },
      { name: 'coconut milk', quantity: '1', unit: 'can' },
      { name: 'okra', quantity: '1', unit: 'cup, sliced' },
      { name: 'crab', quantity: '4', unit: 'oz, picked' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'garlic', quantity: '3', unit: 'cloves' },
      { name: 'thyme', quantity: '1', unit: 'tsp' },
      { name: 'scotch bonnet pepper', quantity: '1', unit: 'whole' },
    ],
    steps: [
      'Sauté onion and garlic in oil. Add callaloo leaves and cook until wilted.',
      'Add coconut milk, okra, thyme, and whole scotch bonnet. Simmer 20 minutes.',
      'Add crab meat and cook 5 more minutes.',
      'Remove scotch bonnet and serve with provisions or rice.',
    ],
    tags: ['callaloo', 'trinidadian', 'greens', 'coconut', 'stew'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 240,
      protein_g: 14,
      carbs_g: 16,
      fat_g: 14,
      fiber_g: 4,
      sugar_g: 3,
      sodium_mg: 380,
    },
  },
  {
    title: 'Curry Goat',
    description:
      'Jamaican-style curried goat with potatoes, slow-cooked until fall-off-the-bone tender.',
    cuisine: 'Caribbean',
    prep_minutes: 20,
    cook_minutes: 120,
    servings: 6,
    calories: 420,
    ingredients: [
      { name: 'goat meat', quantity: '2', unit: 'lbs, bone-in' },
      { name: 'curry powder', quantity: '3', unit: 'tbsp' },
      { name: 'potato', quantity: '2', unit: 'cubed' },
      { name: 'onion', quantity: '2', unit: 'diced' },
      { name: 'garlic', quantity: '4', unit: 'cloves' },
      { name: 'ginger', quantity: '1', unit: 'tbsp, grated' },
      { name: 'thyme', quantity: '2', unit: 'sprigs' },
      { name: 'scotch bonnet pepper', quantity: '1', unit: 'whole' },
    ],
    steps: [
      'Season goat with curry powder, salt, and pepper. Let marinate 30 minutes.',
      'Brown goat in oil. Add onion, garlic, and ginger. Cook 5 minutes.',
      'Add water, thyme, and scotch bonnet. Simmer 90 minutes until tender.',
      'Add potatoes and cook 20 more minutes until potatoes are soft. Serve with rice.',
    ],
    tags: ['curry goat', 'jamaican', 'goat', 'curry', 'slow-cooked'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 420,
      protein_g: 30,
      carbs_g: 12,
      fat_g: 28,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 440,
    },
  },
  {
    title: 'Conch Fritters',
    description:
      'Crispy Bahamian conch fritters with bell pepper, onion, and a lime dipping sauce.',
    cuisine: 'Caribbean',
    prep_minutes: 20,
    cook_minutes: 10,
    servings: 6,
    calories: 240,
    ingredients: [
      { name: 'conch meat', quantity: '1', unit: 'lb, minced' },
      { name: 'flour', quantity: '1', unit: 'cup' },
      { name: 'bell pepper', quantity: '1/2', unit: 'diced' },
      { name: 'onion', quantity: '1/2', unit: 'diced' },
      { name: 'egg', quantity: '1', unit: 'large' },
      { name: 'lime juice', quantity: '2', unit: 'tbsp' },
      { name: 'vegetable oil', quantity: '2', unit: 'cups, for frying' },
      { name: 'hot sauce', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Mix minced conch, flour, bell pepper, onion, egg, and seasonings into a batter.',
      'Heat oil to 375°F.',
      'Drop spoonfuls of batter into hot oil and fry until golden, about 3-4 minutes.',
      'Drain and serve with lime juice and hot sauce dipping sauce.',
    ],
    tags: ['conch', 'fritter', 'bahamian', 'fried', 'seafood'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 240,
      protein_g: 18,
      carbs_g: 20,
      fat_g: 10,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 420,
    },
  },
  {
    title: 'Roti',
    description:
      'Trinidadian flatbread stuffed with curried chickpeas and potato — a street food staple.',
    cuisine: 'Caribbean',
    prep_minutes: 30,
    cook_minutes: 20,
    servings: 4,
    calories: 340,
    ingredients: [
      { name: 'all-purpose flour', quantity: '3', unit: 'cups' },
      { name: 'chickpeas', quantity: '1', unit: 'can, drained' },
      { name: 'potato', quantity: '1', unit: 'large, cubed' },
      { name: 'curry powder', quantity: '2', unit: 'tbsp' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
      { name: 'vegetable oil', quantity: '2', unit: 'tbsp' },
      { name: 'water', quantity: '1', unit: 'cup' },
    ],
    steps: [
      'Make roti dough: mix flour, water, oil, and salt. Knead until smooth, rest 20 minutes.',
      'Cook chickpea and potato curry: sauté onion, garlic, curry, add chickpeas and potato. Cook 15 minutes.',
      'Roll dough thin, cook on a hot griddle 1-2 minutes per side until puffed and spotted.',
      'Fill roti with chickpea curry and fold.',
    ],
    tags: ['roti', 'trinidadian', 'flatbread', 'chickpea', 'vegetarian'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 340,
      protein_g: 12,
      carbs_g: 52,
      fat_g: 10,
      fiber_g: 6,
      sugar_g: 3,
      sodium_mg: 380,
    },
  },
  {
    title: 'Ackee and Saltfish',
    description:
      "Jamaica's national dish: scrambled ackee fruit with salt cod, peppers, and onions.",
    cuisine: 'Caribbean',
    prep_minutes: 20,
    cook_minutes: 20,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'ackee', quantity: '1', unit: 'can, drained' },
      { name: 'salt cod', quantity: '8', unit: 'oz, soaked overnight' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'scotch bonnet pepper', quantity: '1', unit: 'minced' },
      { name: 'bell pepper', quantity: '1', unit: 'diced' },
      { name: 'tomato', quantity: '1', unit: 'diced' },
      { name: 'black pepper', quantity: '1/2', unit: 'tsp' },
      { name: 'coconut oil', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Soak salt cod overnight, then boil for 10 minutes. Flake the fish.',
      'Sauté onion, bell pepper, and scotch bonnet in coconut oil.',
      'Add flaked fish and tomato. Cook 5 minutes.',
      'Gently fold in ackee, season with black pepper. Cook 3 minutes — do not stir too much.',
    ],
    tags: ['ackee', 'saltfish', 'jamaican', 'national dish', 'fish'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 280,
      protein_g: 24,
      carbs_g: 10,
      fat_g: 16,
      fiber_g: 3,
      sugar_g: 2,
      sodium_mg: 680,
    },
  },
  {
    title: 'Cou-Cou and Flying Fish',
    description:
      'Barbadian cornmeal and okra mash served with steamed flying fish in tomato sauce.',
    cuisine: 'Caribbean',
    prep_minutes: 20,
    cook_minutes: 30,
    servings: 4,
    calories: 320,
    ingredients: [
      { name: 'cornmeal', quantity: '1.5', unit: 'cups' },
      { name: 'okra', quantity: '1', unit: 'cup, sliced' },
      { name: 'flying fish fillets', quantity: '8', unit: 'pieces' },
      { name: 'tomato', quantity: '2', unit: 'diced' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
      { name: 'butter', quantity: '1', unit: 'tbsp' },
      { name: 'lime juice', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Steam fish: season fillets, layer with tomato, onion, and garlic. Steam 15 minutes.',
      'Make cou-cou: boil okra in salted water. Slowly whisk in cornmeal.',
      'Stir cou-cou vigorously with a wooden spoon (or cou-cou stick) until smooth.',
      'Add butter and stir. Serve cou-cou with steamed fish on top.',
    ],
    tags: ['cou-cou', 'barbadian', 'flying fish', 'cornmeal', 'national dish'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 24,
      carbs_g: 36,
      fat_g: 8,
      fiber_g: 4,
      sugar_g: 3,
      sodium_mg: 340,
    },
  },
  {
    title: 'Rum Punch',
    description: 'Classic Caribbean rum punch with lime, pineapple, and a dash of bitters.',
    cuisine: 'Caribbean',
    prep_minutes: 5,
    cook_minutes: 0,
    servings: 4,
    calories: 200,
    ingredients: [
      { name: 'dark rum', quantity: '1', unit: 'cup' },
      { name: 'lime juice', quantity: '1/2', unit: 'cup' },
      { name: 'pineapple juice', quantity: '1', unit: 'cup' },
      { name: 'grenadine', quantity: '2', unit: 'tbsp' },
      { name: 'angostura bitters', quantity: '4', unit: 'dashes' },
      { name: 'nutmeg', quantity: '1', unit: 'pinch' },
    ],
    steps: [
      'Combine rum, lime juice, pineapple juice, and grenadine in a pitcher.',
      'Add angostura bitters and stir well.',
      'Pour over ice and grate fresh nutmeg on top.',
      'Garnish with a lime wheel and serve.',
    ],
    tags: ['rum punch', 'cocktail', 'caribbean', 'drink', 'party'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 200,
      protein_g: 0,
      carbs_g: 26,
      fat_g: 0,
      fiber_g: 0,
      sugar_g: 22,
      sodium_mg: 10,
    },
  },
  {
    title: 'Jamaican Beef Patties',
    description: 'Flaky turmeric pastry filled with spiced ground beef and scotch bonnet.',
    cuisine: 'Caribbean',
    prep_minutes: 30,
    cook_minutes: 25,
    servings: 8,
    calories: 320,
    ingredients: [
      { name: 'ground beef', quantity: '1', unit: 'lb' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'scotch bonnet pepper', quantity: '1', unit: 'minced' },
      { name: 'curry powder', quantity: '1', unit: 'tbsp' },
      { name: 'thyme', quantity: '1', unit: 'tsp' },
      { name: 'puff pastry', quantity: '2', unit: 'sheets' },
      { name: 'turmeric', quantity: '1', unit: 'tsp' },
      { name: 'egg wash', quantity: '1', unit: 'egg, beaten' },
    ],
    steps: [
      'Brown beef with onion, scotch bonnet, curry powder, and thyme. Let cool.',
      'Cut pastry into circles. Add beef filling to one half.',
      'Fold over and crimp edges with a fork. Brush with turmeric-tinted egg wash.',
      'Bake at 375°F for 20-25 minutes until golden and flaky.',
    ],
    tags: ['patty', 'jamaican', 'beef', 'pastry', 'handheld'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 14,
      carbs_g: 26,
      fat_g: 18,
      fiber_g: 2,
      sugar_g: 2,
      sodium_mg: 480,
    },
  },
  {
    title: 'Oxtail Stew',
    description: 'Rich Jamaican oxtail stew with butter beans in a savory brown sauce.',
    cuisine: 'Caribbean',
    prep_minutes: 20,
    cook_minutes: 180,
    servings: 6,
    calories: 480,
    ingredients: [
      { name: 'oxtail', quantity: '3', unit: 'lbs' },
      { name: 'butter beans', quantity: '1', unit: 'can' },
      { name: 'onion', quantity: '1', unit: 'large, diced' },
      { name: 'garlic', quantity: '4', unit: 'cloves' },
      { name: 'thyme', quantity: '2', unit: 'sprigs' },
      { name: 'allspice berries', quantity: '4', unit: 'whole' },
      { name: 'browning sauce', quantity: '1', unit: 'tbsp' },
      { name: 'carrot', quantity: '2', unit: 'cubed' },
    ],
    steps: [
      'Season oxtail with salt, pepper, and browning sauce. Brown in oil.',
      'Add onion, garlic, thyme, and allspice. Add water to cover.',
      'Simmer 2.5-3 hours until oxtail is fall-off-the-bone tender.',
      'Add butter beans and carrot. Cook 20 more minutes. Serve with rice.',
    ],
    tags: ['oxtail', 'jamaican', 'stew', 'slow-cooked', 'comfort food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 480,
      protein_g: 32,
      carbs_g: 14,
      fat_g: 34,
      fiber_g: 3,
      sugar_g: 3,
      sodium_mg: 520,
    },
  },
];

export const caribbeanRecipes = generateCuisineRecipes(configs);
