import type { CuisineRecipeConfig } from './types';
import { generateCuisineRecipes } from './types';

const configs: CuisineRecipeConfig[] = [
  {
    title: 'Kung Pao Chicken',
    description:
      'Spicy stir-fried chicken with peanuts, chili peppers, and Sichuan peppercorns in a savory-sweet sauce.',
    cuisine: 'Chinese',
    prep_minutes: 15,
    cook_minutes: 10,
    servings: 4,
    calories: 350,
    ingredients: [
      { name: 'chicken breast', quantity: '1', unit: 'lb, diced' },
      { name: 'peanuts', quantity: '1/3', unit: 'cup, roasted' },
      { name: 'dried red chilies', quantity: '8', unit: 'whole' },
      { name: 'Sichuan peppercorns', quantity: '1', unit: 'tsp' },
      { name: 'soy sauce', quantity: '2', unit: 'tbsp' },
      { name: 'rice vinegar', quantity: '1', unit: 'tbsp' },
      { name: 'sugar', quantity: '1', unit: 'tbsp' },
      { name: 'garlic', quantity: '3', unit: 'cloves, minced' },
      { name: 'ginger', quantity: '1', unit: 'tbsp, minced' },
      { name: 'green onion', quantity: '4', unit: 'cut' },
      { name: 'cornstarch', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Marinate chicken with soy sauce, cornstarch, and a splash of rice wine for 15 minutes.',
      'Toast peanuts in a dry wok until golden. Set aside.',
      'Stir-fry dried chilies and Sichuan peppercorns in oil until fragrant.',
      'Add chicken and sear until golden on all sides.',
      'Add garlic, ginger, and the sauce mixture of soy sauce, vinegar, and sugar.',
      'Toss in peanuts and green onion. Serve immediately with steamed rice.',
    ],
    tags: ['chinese', 'sichuan', 'chicken', 'spicy', 'stir-fry', 'kung-pao'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 350,
      protein_g: 32,
      carbs_g: 14,
      fat_g: 18,
      fiber_g: 2,
      sugar_g: 6,
      sodium_mg: 680,
    },
  },
  {
    title: 'Mapo Tofu',
    description:
      'Silken tofu in a fiery, numbing Sichuan chili-bean sauce with ground pork and scallions.',
    cuisine: 'Chinese',
    prep_minutes: 10,
    cook_minutes: 15,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'silken tofu', quantity: '1', unit: 'block, cubed' },
      { name: 'ground pork', quantity: '4', unit: 'oz' },
      { name: 'doubanjiang', quantity: '2', unit: 'tbsp' },
      { name: 'Sichuan peppercorn powder', quantity: '1', unit: 'tsp' },
      { name: 'garlic', quantity: '3', unit: 'cloves, minced' },
      { name: 'ginger', quantity: '1', unit: 'tbsp, minced' },
      { name: 'soy sauce', quantity: '1', unit: 'tbsp' },
      { name: 'chili oil', quantity: '2', unit: 'tbsp' },
      { name: 'green onion', quantity: '3', unit: 'sliced' },
      { name: 'cornstarch', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Brown ground pork in a wok, breaking into small pieces.',
      'Add doubanjiang and stir-fry until fragrant and oil turns red.',
      'Add garlic, ginger, and Sichuan peppercorn powder.',
      'Pour in water and soy sauce. Bring to a simmer.',
      'Gently slide in tofu cubes. Simmer 5 minutes without stirring too much.',
      'Thicken with cornstarch slurry. Drizzle chili oil and top with green onion.',
    ],
    tags: ['chinese', 'sichuan', 'tofu', 'spicy', 'mapo', 'stew'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 18,
      carbs_g: 10,
      fat_g: 20,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 750,
    },
  },
  {
    title: 'Egg Fried Rice',
    description:
      'Classic wok-fried rice with egg, peas, carrots, and scallions tossed in a light soy sauce seasoning.',
    cuisine: 'Chinese',
    prep_minutes: 10,
    cook_minutes: 8,
    servings: 4,
    calories: 310,
    ingredients: [
      { name: 'cooked jasmine rice', quantity: '4', unit: 'cups, day-old' },
      { name: 'eggs', quantity: '3', unit: 'large, beaten' },
      { name: 'frozen peas', quantity: '1/2', unit: 'cup' },
      { name: 'carrot', quantity: '1', unit: 'medium, diced' },
      { name: 'soy sauce', quantity: '2', unit: 'tbsp' },
      { name: 'sesame oil', quantity: '1', unit: 'tsp' },
      { name: 'green onion', quantity: '4', unit: 'sliced' },
      { name: 'vegetable oil', quantity: '2', unit: 'tbsp' },
      { name: 'white pepper', quantity: '1/4', unit: 'tsp' },
    ],
    steps: [
      'Heat wok over high heat. Scramble eggs in oil, break into small pieces, and set aside.',
      'Add more oil. Stir-fry diced carrot and peas for 1 minute.',
      'Add rice and press flat. Let it sit 30 seconds, then toss. Repeat for even browning.',
      'Season with soy sauce and white pepper.',
      'Return scrambled eggs. Drizzle sesame oil and toss.',
      'Garnish with green onion and serve.',
    ],
    tags: ['chinese', 'rice', 'egg', 'stir-fry', 'quick', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 310,
      protein_g: 10,
      carbs_g: 44,
      fat_g: 10,
      fiber_g: 3,
      sugar_g: 4,
      sodium_mg: 540,
    },
  },
  {
    title: 'Pork Dumplings (Jiaozi)',
    description:
      'Handmade dumplings filled with ground pork, napa cabbage, and ginger, boiled or pan-fried to golden perfection.',
    cuisine: 'Chinese',
    prep_minutes: 45,
    cook_minutes: 10,
    servings: 4,
    calories: 290,
    ingredients: [
      { name: 'ground pork', quantity: '1', unit: 'lb' },
      { name: 'napa cabbage', quantity: '2', unit: 'cups, finely chopped' },
      { name: 'ginger', quantity: '1', unit: 'tbsp, minced' },
      { name: 'soy sauce', quantity: '2', unit: 'tbsp' },
      { name: 'sesame oil', quantity: '1', unit: 'tbsp' },
      { name: 'green onion', quantity: '3', unit: 'minced' },
      { name: 'dumpling wrappers', quantity: '40', unit: 'round' },
      { name: 'rice vinegar', quantity: '2', unit: 'tbsp, for dipping' },
      { name: 'chili oil', quantity: '1', unit: 'tsp, for dipping' },
    ],
    steps: [
      'Salt napa cabbage, let sit 10 minutes, then squeeze out excess water.',
      'Mix pork, cabbage, ginger, soy sauce, sesame oil, and green onion.',
      'Place a tablespoon of filling in each wrapper. Fold and pleat to seal.',
      'Boil dumplings in batches — they float when done, about 4 minutes.',
      'For potstickers, pan-fry in oil until bottoms are golden, then add water and cover to steam.',
      'Serve with a dipping sauce of rice vinegar, soy sauce, and chili oil.',
    ],
    tags: ['chinese', 'dumplings', 'pork', 'jiaozi', 'comfort-food', 'dim-sum'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 290,
      protein_g: 16,
      carbs_g: 28,
      fat_g: 13,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 620,
    },
  },
  {
    title: 'Hot and Sour Soup',
    description:
      'A bold, warming soup with wood ear mushrooms, tofu, bamboo shoots, and egg ribbons in a vinegary, peppery broth.',
    cuisine: 'Chinese',
    prep_minutes: 15,
    cook_minutes: 15,
    servings: 4,
    calories: 120,
    ingredients: [
      { name: 'wood ear mushrooms', quantity: '1/2', unit: 'cup, soaked and sliced' },
      { name: 'firm tofu', quantity: '1/2', unit: 'block, julienned' },
      { name: 'bamboo shoots', quantity: '1/2', unit: 'cup, shredded' },
      { name: 'egg', quantity: '1', unit: 'beaten' },
      { name: 'soy sauce', quantity: '2', unit: 'tbsp' },
      { name: 'rice vinegar', quantity: '3', unit: 'tbsp' },
      { name: 'white pepper', quantity: '1/2', unit: 'tsp' },
      { name: 'sesame oil', quantity: '1', unit: 'tsp' },
      { name: 'cornstarch', quantity: '1', unit: 'tbsp' },
      { name: 'green onion', quantity: '2', unit: 'sliced' },
    ],
    steps: [
      'Bring chicken broth to a boil. Add mushrooms, tofu, and bamboo shoots.',
      'Season with soy sauce, rice vinegar, and white pepper.',
      'Simmer 5 minutes until flavors meld.',
      'Thicken with cornstarch slurry, stirring gently.',
      'Slowly drizzle beaten egg in a thin stream to create egg ribbons.',
      'Finish with sesame oil and green onion. Serve hot.',
    ],
    tags: ['chinese', 'soup', 'spicy', 'sour', 'tofu', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 120,
      protein_g: 8,
      carbs_g: 10,
      fat_g: 5,
      fiber_g: 2,
      sugar_g: 2,
      sodium_mg: 820,
    },
  },
  {
    title: 'Char Siu (Chinese BBQ Pork)',
    description:
      'Sweet and savory roasted pork shoulder glazed with a red-hued char siu sauce, sliced and served with rice.',
    cuisine: 'Chinese',
    prep_minutes: 15,
    cook_minutes: 40,
    servings: 6,
    calories: 380,
    ingredients: [
      { name: 'pork shoulder', quantity: '2', unit: 'lb, cut into strips' },
      { name: 'hoisin sauce', quantity: '3', unit: 'tbsp' },
      { name: 'soy sauce', quantity: '3', unit: 'tbsp' },
      { name: 'honey', quantity: '2', unit: 'tbsp' },
      { name: 'oyster sauce', quantity: '1', unit: 'tbsp' },
      { name: 'five-spice powder', quantity: '1', unit: 'tsp' },
      { name: 'garlic', quantity: '3', unit: 'cloves, minced' },
      { name: 'red food coloring', quantity: '1/4', unit: 'tsp, optional' },
      { name: 'rice wine', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Mix hoisin, soy sauce, honey, oyster sauce, five-spice, garlic, rice wine, and food coloring.',
      'Marinate pork strips in the sauce for at least 4 hours or overnight.',
      'Roast at 400°F on a wire rack over a foil-lined tray for 25 minutes.',
      'Baste with remaining marinade every 10 minutes.',
      'Broil for 3-5 minutes until edges are charred and caramelized.',
      'Rest 5 minutes, slice thinly, and serve with steamed rice.',
    ],
    tags: ['chinese', 'pork', 'bbq', 'roasted', 'char-siu', 'cantonese'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 28,
      carbs_g: 16,
      fat_g: 22,
      fiber_g: 0,
      sugar_g: 12,
      sodium_mg: 780,
    },
  },
  {
    title: 'Dan Dan Noodles',
    description:
      'Spicy Sichuan noodles topped with a savory pork sauce, chili oil, and a numbing hit of Sichuan peppercorns.',
    cuisine: 'Chinese',
    prep_minutes: 10,
    cook_minutes: 10,
    servings: 2,
    calories: 420,
    ingredients: [
      { name: 'Chinese wheat noodles', quantity: '8', unit: 'oz' },
      { name: 'ground pork', quantity: '6', unit: 'oz' },
      { name: 'Sichuan peppercorn powder', quantity: '1', unit: 'tsp' },
      { name: 'chili oil', quantity: '3', unit: 'tbsp' },
      { name: 'soy sauce', quantity: '1', unit: 'tbsp' },
      { name: 'Chinese sesame paste', quantity: '2', unit: 'tbsp' },
      { name: 'garlic', quantity: '2', unit: 'cloves, minced' },
      { name: 'green onion', quantity: '2', unit: 'sliced' },
      { name: 'ya cai', quantity: '1', unit: 'tbsp, optional' },
    ],
    steps: [
      'Cook noodles according to package directions. Drain and set aside.',
      'Brown ground pork in a wok until crispy.',
      'Add ya cai (if using) and garlic. Stir-fry 30 seconds.',
      'Mix chili oil, sesame paste, soy sauce, and Sichuan peppercorn powder in a bowl.',
      'Divide sauce between bowls. Add noodles and toss to coat.',
      'Top with pork, green onion, and extra chili oil.',
    ],
    tags: ['chinese', 'sichuan', 'noodles', 'spicy', 'dan-dan', 'pork'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 22,
      carbs_g: 38,
      fat_g: 20,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 690,
    },
  },
  {
    title: 'Wonton Soup',
    description:
      'Delicate pork and shrimp wontons floating in a clear, savory chicken broth with bok choy and scallions.',
    cuisine: 'Chinese',
    prep_minutes: 30,
    cook_minutes: 10,
    servings: 4,
    calories: 220,
    ingredients: [
      { name: 'ground pork', quantity: '8', unit: 'oz' },
      { name: 'shrimp', quantity: '4', unit: 'oz, minced' },
      { name: 'wonton wrappers', quantity: '30', unit: 'square' },
      { name: 'ginger', quantity: '1', unit: 'tsp, minced' },
      { name: 'soy sauce', quantity: '1', unit: 'tbsp' },
      { name: 'sesame oil', quantity: '1', unit: 'tsp' },
      { name: 'bok choy', quantity: '4', unit: 'stalks, halved' },
      { name: 'green onion', quantity: '3', unit: 'sliced' },
      { name: 'chicken broth', quantity: '6', unit: 'cups' },
    ],
    steps: [
      'Mix pork, shrimp, ginger, soy sauce, and sesame oil for the filling.',
      'Place a teaspoon of filling in each wonton wrapper. Fold into triangles or pouches.',
      'Bring chicken broth to a gentle simmer.',
      'Drop wontons in and cook until they float, about 3-4 minutes.',
      'Add bok choy and cook 1 minute more.',
      'Ladle into bowls and garnish with green onion.',
    ],
    tags: ['chinese', 'soup', 'wonton', 'pork', 'shrimp', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 220,
      protein_g: 14,
      carbs_g: 20,
      fat_g: 9,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 640,
    },
  },
  {
    title: 'Moo Shu Pork',
    description:
      'Stir-fried shredded pork with wood ear mushrooms, egg, and cabbage, served with hoisin sauce in thin pancakes.',
    cuisine: 'Chinese',
    prep_minutes: 20,
    cook_minutes: 10,
    servings: 4,
    calories: 340,
    ingredients: [
      { name: 'pork tenderloin', quantity: '12', unit: 'oz, shredded' },
      { name: 'wood ear mushrooms', quantity: '1/2', unit: 'cup, soaked and shredded' },
      { name: 'egg', quantity: '2', unit: 'beaten' },
      { name: 'napa cabbage', quantity: '2', unit: 'cups, shredded' },
      { name: 'hoisin sauce', quantity: '3', unit: 'tbsp' },
      { name: 'soy sauce', quantity: '1', unit: 'tbsp' },
      { name: 'ginger', quantity: '1', unit: 'tsp, minced' },
      { name: 'green onion', quantity: '3', unit: 'cut' },
      { name: 'mandarin pancakes', quantity: '8', unit: 'store-bought or homemade' },
    ],
    steps: [
      'Scramble eggs in a wok, break into pieces, and set aside.',
      'Stir-fry shredded pork until just cooked. Set aside.',
      'Sauté ginger, then add cabbage and wood ear mushrooms.',
      'Return pork and egg to the wok. Season with soy sauce.',
      'Warm pancakes and spread each with hoisin sauce.',
      'Spoon filling into pancakes, roll up, and serve.',
    ],
    tags: ['chinese', 'pork', 'moo-shu', 'stir-fry', 'pancakes', 'northern'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 340,
      protein_g: 24,
      carbs_g: 22,
      fat_g: 16,
      fiber_g: 2,
      sugar_g: 5,
      sodium_mg: 660,
    },
  },
  {
    title: 'Beef and Broccoli',
    description:
      'Tender sliced beef stir-fried with crisp broccoli florets in a savory garlic-soy sauce.',
    cuisine: 'Chinese',
    prep_minutes: 15,
    cook_minutes: 8,
    servings: 4,
    calories: 330,
    ingredients: [
      { name: 'flank steak', quantity: '1', unit: 'lb, sliced thin against grain' },
      { name: 'broccoli', quantity: '2', unit: 'cups, cut into florets' },
      { name: 'soy sauce', quantity: '3', unit: 'tbsp' },
      { name: 'oyster sauce', quantity: '2', unit: 'tbsp' },
      { name: 'garlic', quantity: '3', unit: 'cloves, minced' },
      { name: 'ginger', quantity: '1', unit: 'tsp, minced' },
      { name: 'cornstarch', quantity: '1', unit: 'tbsp' },
      { name: 'sesame oil', quantity: '1', unit: 'tsp' },
      { name: 'vegetable oil', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Marinate beef with soy sauce, cornstarch, and a splash of water for 15 minutes.',
      'Blanch broccoli in boiling water for 1 minute. Drain.',
      'Sear beef in a hot wok until browned. Set aside.',
      'Sauté garlic and ginger. Add broccoli and toss.',
      'Return beef. Add oyster sauce and a splash of water.',
      'Drizzle sesame oil, toss, and serve with rice.',
    ],
    tags: ['chinese', 'beef', 'broccoli', 'stir-fry', 'quick', 'american-chinese'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 330,
      protein_g: 30,
      carbs_g: 12,
      fat_g: 18,
      fiber_g: 3,
      sugar_g: 4,
      sodium_mg: 720,
    },
  },
  {
    title: 'Egg Drop Soup',
    description:
      'A silky, comforting soup of chicken broth with delicate egg ribbons and a hint of sesame.',
    cuisine: 'Chinese',
    prep_minutes: 5,
    cook_minutes: 10,
    servings: 4,
    calories: 90,
    ingredients: [
      { name: 'chicken broth', quantity: '6', unit: 'cups' },
      { name: 'egg', quantity: '3', unit: 'large, beaten' },
      { name: 'cornstarch', quantity: '1', unit: 'tbsp' },
      { name: 'ginger', quantity: '1', unit: 'tsp, grated' },
      { name: 'soy sauce', quantity: '1', unit: 'tsp' },
      { name: 'sesame oil', quantity: '1/2', unit: 'tsp' },
      { name: 'green onion', quantity: '2', unit: 'sliced' },
      { name: 'white pepper', quantity: '1/4', unit: 'tsp' },
    ],
    steps: [
      'Bring chicken broth to a boil with ginger and white pepper.',
      'Thicken with cornstarch slurry — stir until silky.',
      'Reduce heat. Slowly pour beaten egg in a thin stream while stirring gently in one direction.',
      'Let egg set for 10 seconds without stirring.',
      'Season with soy sauce and sesame oil.',
      'Ladle into bowls and top with green onion.',
    ],
    tags: ['chinese', 'soup', 'egg', 'comfort-food', 'quick', 'light'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 90,
      protein_g: 6,
      carbs_g: 6,
      fat_g: 4,
      fiber_g: 0,
      sugar_g: 1,
      sodium_mg: 680,
    },
  },
  {
    title: 'Vegetable Spring Rolls',
    description:
      'Crispy fried rolls filled with shredded cabbage, carrot, and mushroom, served with sweet chili dipping sauce.',
    cuisine: 'Chinese',
    prep_minutes: 25,
    cook_minutes: 8,
    servings: 4,
    calories: 200,
    ingredients: [
      { name: 'spring roll wrappers', quantity: '12', unit: 'sheets' },
      { name: 'napa cabbage', quantity: '2', unit: 'cups, shredded' },
      { name: 'carrot', quantity: '1', unit: 'large, julienned' },
      { name: 'shiitake mushrooms', quantity: '1/2', unit: 'cup, sliced' },
      { name: 'bean sprouts', quantity: '1/2', unit: 'cup' },
      { name: 'garlic', quantity: '2', unit: 'cloves, minced' },
      { name: 'soy sauce', quantity: '1', unit: 'tbsp' },
      { name: 'sesame oil', quantity: '1', unit: 'tsp' },
      { name: 'vegetable oil', quantity: '2', unit: 'cups, for frying' },
    ],
    steps: [
      'Sauté garlic, mushrooms, and carrot for 2 minutes.',
      'Add cabbage and bean sprouts. Season with soy sauce and sesame oil. Cool.',
      'Place filling on each wrapper. Fold sides in and roll tightly. Seal with flour paste.',
      'Deep-fry at 350°F until golden and crispy, about 3-4 minutes.',
      'Drain on paper towels.',
      'Serve with sweet chili sauce or plum sauce.',
    ],
    tags: ['chinese', 'spring-rolls', 'vegetarian', 'fried', 'appetizer', 'dim-sum'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 200,
      protein_g: 4,
      carbs_g: 22,
      fat_g: 10,
      fiber_g: 3,
      sugar_g: 3,
      sodium_mg: 380,
    },
  },
  {
    title: 'Sweet and Sour Pork',
    description:
      'Crispy battered pork pieces tossed in a vibrant sweet-and-sour sauce with bell peppers and pineapple.',
    cuisine: 'Chinese',
    prep_minutes: 15,
    cook_minutes: 12,
    servings: 4,
    calories: 400,
    ingredients: [
      { name: 'pork loin', quantity: '1', unit: 'lb, cubed' },
      { name: 'pineapple chunks', quantity: '1/2', unit: 'cup' },
      { name: 'bell pepper', quantity: '1', unit: 'large, diced' },
      { name: 'rice vinegar', quantity: '3', unit: 'tbsp' },
      { name: 'ketchup', quantity: '3', unit: 'tbsp' },
      { name: 'sugar', quantity: '2', unit: 'tbsp' },
      { name: 'soy sauce', quantity: '1', unit: 'tbsp' },
      { name: 'cornstarch', quantity: '2', unit: 'tbsp' },
      { name: 'egg', quantity: '1', unit: 'for batter' },
      { name: 'vegetable oil', quantity: '2', unit: 'cups, for frying' },
    ],
    steps: [
      'Coat pork in cornstarch, dip in beaten egg, then coat again in cornstarch.',
      'Deep-fry pork at 375°F until golden and crispy. Drain.',
      'Combine rice vinegar, ketchup, sugar, and soy sauce for the sauce.',
      'Stir-fry bell pepper and pineapple briefly.',
      'Pour in the sauce and bring to a boil. Thicken with cornstarch slurry.',
      'Toss in crispy pork. Serve immediately before it softens.',
    ],
    tags: ['chinese', 'pork', 'sweet-and-sour', 'fried', 'american-chinese', 'crispy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 400,
      protein_g: 24,
      carbs_g: 30,
      fat_g: 20,
      fiber_g: 2,
      sugar_g: 14,
      sodium_mg: 580,
    },
  },
  {
    title: 'Chow Mein',
    description:
      'Stir-fried egg noodles with cabbage, carrots, bean sprouts, and a savory soy-oyster sauce.',
    cuisine: 'Chinese',
    prep_minutes: 15,
    cook_minutes: 8,
    servings: 4,
    calories: 350,
    ingredients: [
      { name: 'egg noodles', quantity: '12', unit: 'oz, fresh or dried' },
      { name: 'napa cabbage', quantity: '2', unit: 'cups, shredded' },
      { name: 'carrot', quantity: '1', unit: 'medium, julienned' },
      { name: 'bean sprouts', quantity: '1', unit: 'cup' },
      { name: 'soy sauce', quantity: '2', unit: 'tbsp' },
      { name: 'oyster sauce', quantity: '1', unit: 'tbsp' },
      { name: 'sesame oil', quantity: '1', unit: 'tsp' },
      { name: 'green onion', quantity: '3', unit: 'cut' },
      { name: 'vegetable oil', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Boil noodles until just al dente. Rinse and drain well.',
      'Heat oil in a wok over high heat.',
      'Stir-fry carrot and cabbage for 2 minutes.',
      'Add noodles and toss with soy sauce and oyster sauce.',
      'Add bean sprouts and toss for 30 seconds.',
      'Drizzle sesame oil, garnish with green onion, and serve.',
    ],
    tags: ['chinese', 'noodles', 'chow-mein', 'stir-fry', 'vegetarian', 'quick'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 350,
      protein_g: 10,
      carbs_g: 48,
      fat_g: 12,
      fiber_g: 4,
      sugar_g: 4,
      sodium_mg: 620,
    },
  },
  {
    title: 'Ma La Chicken',
    description:
      'Numbing-and-spicy Sichuan chicken stir-fried with dried chilies, Sichuan peppercorns, and crunchy peanuts.',
    cuisine: 'Chinese',
    prep_minutes: 15,
    cook_minutes: 10,
    servings: 4,
    calories: 370,
    ingredients: [
      { name: 'chicken thigh', quantity: '1', unit: 'lb, boneless, diced' },
      { name: 'dried red chilies', quantity: '10', unit: 'whole' },
      { name: 'Sichuan peppercorns', quantity: '2', unit: 'tsp' },
      { name: 'peanuts', quantity: '1/4', unit: 'cup, roasted' },
      { name: 'garlic', quantity: '4', unit: 'cloves, sliced' },
      { name: 'ginger', quantity: '1', unit: 'tbsp, sliced' },
      { name: 'soy sauce', quantity: '2', unit: 'tbsp' },
      { name: 'Shaoxing wine', quantity: '1', unit: 'tbsp' },
      { name: 'sugar', quantity: '1', unit: 'tsp' },
      { name: 'green onion', quantity: '3', unit: 'cut' },
    ],
    steps: [
      'Marinate chicken with soy sauce, Shaoxing wine, and cornstarch for 15 minutes.',
      'Toast peanuts in a dry wok. Set aside.',
      'Fry dried chilies and Sichuan peppercorns in oil until fragrant and darkened.',
      'Add chicken and stir-fry until cooked through and slightly charred.',
      'Add garlic, ginger, and sugar. Toss quickly.',
      'Stir in peanuts and green onion. Serve with steamed rice.',
    ],
    tags: ['chinese', 'sichuan', 'chicken', 'spicy', 'ma-la', 'numbing'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 370,
      protein_g: 30,
      carbs_g: 8,
      fat_g: 24,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 700,
    },
  },
  {
    title: 'Vegetable Lo Mein',
    description:
      'Soft egg noodles tossed with a colorful medley of stir-fried vegetables in a light soy-ginger sauce.',
    cuisine: 'Chinese',
    prep_minutes: 15,
    cook_minutes: 8,
    servings: 4,
    calories: 320,
    ingredients: [
      { name: 'egg noodles', quantity: '12', unit: 'oz' },
      { name: 'bok choy', quantity: '2', unit: 'stalks, chopped' },
      { name: 'bell pepper', quantity: '1', unit: 'sliced' },
      { name: 'carrot', quantity: '1', unit: 'julienned' },
      { name: 'mushrooms', quantity: '1', unit: 'cup, sliced' },
      { name: 'soy sauce', quantity: '2', unit: 'tbsp' },
      { name: 'hoisin sauce', quantity: '1', unit: 'tbsp' },
      { name: 'ginger', quantity: '1', unit: 'tsp, minced' },
      { name: 'sesame oil', quantity: '1', unit: 'tsp' },
      { name: 'green onion', quantity: '3', unit: 'sliced' },
    ],
    steps: [
      'Cook noodles according to package directions. Drain.',
      'Heat oil in a wok over high heat.',
      'Stir-fry carrot, bell pepper, and mushrooms for 2 minutes.',
      'Add bok choy and ginger. Toss 1 minute.',
      'Add noodles, soy sauce, and hoisin sauce. Toss to combine.',
      'Finish with sesame oil and green onion. Serve hot.',
    ],
    tags: ['chinese', 'noodles', 'lo-mein', 'vegetarian', 'vegan', 'stir-fry'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 9,
      carbs_g: 46,
      fat_g: 10,
      fiber_g: 4,
      sugar_g: 5,
      sodium_mg: 580,
    },
  },
];

export const chineseRecipes = generateCuisineRecipes(configs);
