import type { CuisineRecipeConfig } from './types';
import { generateCuisineRecipes } from './types';

const configs: CuisineRecipeConfig[] = [
  {
    title: 'Borscht',
    description: 'Vibrant beet soup with beef, cabbage, potatoes, and a dollop of sour cream.',
    cuisine: 'Eastern European',
    prep_minutes: 20,
    cook_minutes: 90,
    servings: 8,
    calories: 240,
    ingredients: [
      { name: 'beets', quantity: '4', unit: 'medium, peeled & grated' },
      { name: 'beef shank', quantity: '1', unit: 'lb' },
      { name: 'cabbage', quantity: '2', unit: 'cups, shredded' },
      { name: 'potato', quantity: '2', unit: 'diced' },
      { name: 'carrot', quantity: '1', unit: 'sliced' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'tomato paste', quantity: '2', unit: 'tbsp' },
      { name: 'vinegar', quantity: '1', unit: 'tbsp' },
      { name: 'sour cream', quantity: '1/2', unit: 'cup' },
      { name: 'dill', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Simmer beef shank in water for 1 hour, skimming foam.',
      'Add beets, potato, carrot, and onion. Cook 20 minutes.',
      'Add cabbage and tomato paste. Cook 10 more minutes.',
      'Add vinegar and season with salt and pepper.',
      'Ladle into bowls and top with sour cream.',
      'Garnish with fresh dill. Serve with rye bread.',
    ],
    tags: ['eastern-european', 'soup', 'beet', 'beef', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 240,
      protein_g: 18,
      carbs_g: 22,
      fat_g: 10,
      fiber_g: 4,
      sugar_g: 8,
      sodium_mg: 480,
    },
  },
  {
    title: 'Pierogi',
    description:
      'Polish dumplings filled with potato and cheese, boiled then pan-fried with onions.',
    cuisine: 'Eastern European',
    prep_minutes: 40,
    cook_minutes: 15,
    servings: 6,
    calories: 280,
    ingredients: [
      { name: 'flour', quantity: '2', unit: 'cups' },
      { name: 'egg', quantity: '1', unit: 'large' },
      { name: 'sour cream', quantity: '1/4', unit: 'cup' },
      { name: 'potato', quantity: '3', unit: 'mashed' },
      { name: 'farmer cheese', quantity: '1/2', unit: 'cup' },
      { name: 'onion', quantity: '2', unit: 'sliced' },
      { name: 'butter', quantity: '3', unit: 'tbsp' },
    ],
    steps: [
      'Make dough: mix flour, egg, sour cream, and salt. Knead until smooth. Rest 30 minutes.',
      'Mix mashed potato with cheese and sautéed onion for filling.',
      'Roll dough thin, cut circles. Fill and crimp edges.',
      'Boil pierogi until they float. Remove.',
      'Pan-fry boiled pierogi in butter with sliced onion until golden.',
      'Serve with sour cream.',
    ],
    tags: ['eastern-european', 'dumplings', 'potato', 'polish', 'vegetarian'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 8,
      carbs_g: 38,
      fat_g: 10,
      fiber_g: 2,
      sugar_g: 2,
      sodium_mg: 320,
    },
  },
  {
    title: 'Beef Stroganoff',
    description: 'Sliced beef in a creamy mushroom sauce with Dijon, served over egg noodles.',
    cuisine: 'Eastern European',
    prep_minutes: 15,
    cook_minutes: 20,
    servings: 4,
    calories: 420,
    ingredients: [
      { name: 'beef sirloin', quantity: '1', unit: 'lb, sliced thin' },
      { name: 'mushrooms', quantity: '8', unit: 'oz, sliced' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'sour cream', quantity: '1', unit: 'cup' },
      { name: 'beef broth', quantity: '1', unit: 'cup' },
      { name: 'Dijon mustard', quantity: '1', unit: 'tbsp' },
      { name: 'egg noodles', quantity: '8', unit: 'oz' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Sear beef strips in butter until browned. Remove.',
      'Sauté mushrooms and onion until golden.',
      'Add beef broth and simmer 5 minutes.',
      'Stir in sour cream and Dijon. Do not boil.',
      'Return beef to the sauce.',
      'Serve over cooked egg noodles.',
    ],
    tags: ['eastern-european', 'beef', 'mushroom', 'creamy', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 32,
      carbs_g: 24,
      fat_g: 22,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 580,
    },
  },
  {
    title: 'Goulash',
    description: 'Hungarian paprika beef stew with potatoes and caraway seeds.',
    cuisine: 'Eastern European',
    prep_minutes: 15,
    cook_minutes: 90,
    servings: 6,
    calories: 380,
    ingredients: [
      { name: 'beef chuck', quantity: '2', unit: 'lb, cubed' },
      { name: 'Hungarian paprika', quantity: '3', unit: 'tbsp' },
      { name: 'onion', quantity: '3', unit: 'large, diced' },
      { name: 'potato', quantity: '2', unit: 'diced' },
      { name: 'caraway seeds', quantity: '1', unit: 'tsp' },
      { name: 'tomato paste', quantity: '2', unit: 'tbsp' },
      { name: 'beef broth', quantity: '3', unit: 'cups' },
      { name: 'bell pepper', quantity: '1', unit: 'diced' },
    ],
    steps: [
      'Brown beef in batches. Set aside.',
      'Sauté onions until very soft and golden.',
      'Add paprika (off heat briefly to avoid burning), stir.',
      'Return beef, add broth, tomato paste, caraway, and bell pepper.',
      'Simmer covered for 1.5 hours until beef is tender.',
      'Add potatoes for the last 20 minutes. Serve with crusty bread.',
    ],
    tags: ['eastern-european', 'hungarian', 'beef', 'paprika', 'stew'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 380,
      protein_g: 34,
      carbs_g: 16,
      fat_g: 20,
      fiber_g: 3,
      sugar_g: 4,
      sodium_mg: 580,
    },
  },
  {
    title: 'Cabbage Rolls',
    description: 'Braised cabbage leaves stuffed with rice and meat in a tangy tomato sauce.',
    cuisine: 'Eastern European',
    prep_minutes: 30,
    cook_minutes: 60,
    servings: 6,
    calories: 280,
    ingredients: [
      { name: 'cabbage', quantity: '1', unit: 'large, leaves separated' },
      { name: 'ground beef', quantity: '1', unit: 'lb' },
      { name: 'rice', quantity: '1/2', unit: 'cup, cooked' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'egg', quantity: '1', unit: 'beaten' },
      { name: 'tomato sauce', quantity: '2', unit: 'cups' },
      { name: 'sour cream', quantity: '1/4', unit: 'cup' },
      { name: 'dill', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Blanch cabbage leaves until pliable. Trim thick veins.',
      'Mix beef, rice, onion, egg, salt, and pepper.',
      'Place filling on each leaf, roll up tightly, tucking ends.',
      'Arrange rolls seam-down in a pot. Pour tomato sauce over.',
      'Simmer covered for 1 hour.',
      'Serve with sour cream and dill.',
    ],
    tags: ['eastern-european', 'cabbage', 'beef', 'comfort-food', 'braised'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 20,
      carbs_g: 18,
      fat_g: 14,
      fiber_g: 3,
      sugar_g: 6,
      sodium_mg: 620,
    },
  },
  {
    title: 'Pelmeni',
    description:
      'Russian meat dumplings filled with a mix of beef and pork, boiled and served with sour cream.',
    cuisine: 'Eastern European',
    prep_minutes: 40,
    cook_minutes: 10,
    servings: 6,
    calories: 320,
    ingredients: [
      { name: 'flour', quantity: '2', unit: 'cups' },
      { name: 'egg', quantity: '1', unit: 'large' },
      { name: 'ground beef', quantity: '1/2', unit: 'lb' },
      { name: 'ground pork', quantity: '1/2', unit: 'lb' },
      { name: 'onion', quantity: '1', unit: 'grated' },
      { name: 'garlic', quantity: '2', unit: 'cloves, minced' },
      { name: 'sour cream', quantity: '1/2', unit: 'cup' },
      { name: 'dill', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Make dough with flour, egg, and water. Knead until smooth. Rest 30 minutes.',
      'Mix beef, pork, onion, garlic, salt, and pepper for filling.',
      'Roll dough thin, cut circles. Fill and crimp into half-moons.',
      'Boil in salted water until they float, about 5-7 minutes.',
      'Serve with sour cream and dill.',
      'Can also be pan-fried after boiling for extra crispiness.',
    ],
    tags: ['eastern-european', 'dumplings', 'russian', 'meat', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 18,
      carbs_g: 28,
      fat_g: 14,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 480,
    },
  },
  {
    title: 'Blini',
    description: 'Thin Russian crepes served with sour cream, caviar, smoked salmon, or jam.',
    cuisine: 'Eastern European',
    prep_minutes: 15,
    cook_minutes: 15,
    servings: 8,
    calories: 160,
    ingredients: [
      { name: 'flour', quantity: '1.5', unit: 'cups' },
      { name: 'milk', quantity: '1.5', unit: 'cups' },
      { name: 'egg', quantity: '2', unit: 'large' },
      { name: 'butter', quantity: '2', unit: 'tbsp, melted' },
      { name: 'sugar', quantity: '1', unit: 'tbsp' },
      { name: 'yeast', quantity: '1/2', unit: 'tsp' },
      { name: 'sour cream', quantity: '1/2', unit: 'cup' },
      { name: 'smoked salmon', quantity: '4', unit: 'oz' },
    ],
    steps: [
      'Mix flour, yeast, sugar, eggs, milk, and melted butter into a thin batter.',
      'Let rest 30 minutes.',
      'Cook thin crepes in a buttered non-stick pan.',
      'Stack on a plate.',
      'Serve with sour cream and smoked salmon, or sweet with jam.',
      'Can also be served with caviar for a festive occasion.',
    ],
    tags: ['eastern-european', 'crepe', 'russian', 'breakfast', 'versatile'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 160,
      protein_g: 6,
      carbs_g: 18,
      fat_g: 7,
      fiber_g: 0,
      sugar_g: 3,
      sodium_mg: 220,
    },
  },
  {
    title: 'Chicken Kiev',
    description:
      'Breaded chicken breast rolled around garlic-herb butter, fried until golden and oozing.',
    cuisine: 'Eastern European',
    prep_minutes: 25,
    cook_minutes: 15,
    servings: 4,
    calories: 420,
    ingredients: [
      { name: 'chicken breast', quantity: '4', unit: 'large, butterflied' },
      { name: 'butter', quantity: '4', unit: 'tbsp, softened' },
      { name: 'garlic', quantity: '3', unit: 'cloves, minced' },
      { name: 'dill', quantity: '1', unit: 'tbsp, chopped' },
      { name: 'flour', quantity: '1/2', unit: 'cup' },
      { name: 'egg', quantity: '2', unit: 'beaten' },
      { name: 'breadcrumbs', quantity: '1', unit: 'cup' },
      { name: 'oil', quantity: '1/2', unit: 'cup, for frying' },
    ],
    steps: [
      'Mix softened butter with garlic and dill. Roll into 4 logs, freeze until firm.',
      'Pound chicken thin. Place a butter log on each, roll tightly.',
      'Dredge in flour, dip in egg, coat in breadcrumbs. Repeat egg and breadcrumbs.',
      'Deep fry at 350°F for 10-12 minutes until golden and cooked through.',
      'Let rest 2 minutes before serving.',
      'Serve with mashed potatoes. Cut open to release the buttery sauce.',
    ],
    tags: ['eastern-european', 'chicken', 'fried', 'butter', 'ukrainian'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 32,
      carbs_g: 18,
      fat_g: 26,
      fiber_g: 1,
      sugar_g: 1,
      sodium_mg: 580,
    },
  },
  {
    title: 'Syrniki',
    description: 'Russian cottage cheese pancakes served with sour cream and jam.',
    cuisine: 'Eastern European',
    prep_minutes: 10,
    cook_minutes: 8,
    servings: 4,
    calories: 240,
    ingredients: [
      { name: 'tvorog (cottage cheese)', quantity: '1', unit: 'lb' },
      { name: 'egg', quantity: '1', unit: 'large' },
      { name: 'flour', quantity: '3', unit: 'tbsp' },
      { name: 'sugar', quantity: '2', unit: 'tbsp' },
      { name: 'vanilla', quantity: '1', unit: 'tsp' },
      { name: 'sour cream', quantity: '1/2', unit: 'cup' },
      { name: 'berry jam', quantity: '1/4', unit: 'cup' },
      { name: 'oil', quantity: '2', unit: 'tbsp, for frying' },
    ],
    steps: [
      'Mash tvorog, mix with egg, sugar, vanilla, and flour.',
      'Form into small thick patties.',
      'Fry in oil until golden on both sides, about 3-4 minutes per side.',
      'Serve with sour cream and berry jam.',
    ],
    tags: ['eastern-european', 'pancake', 'breakfast', 'cheese', 'russian'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 240,
      protein_g: 16,
      carbs_g: 20,
      fat_g: 10,
      fiber_g: 0,
      sugar_g: 8,
      sodium_mg: 280,
    },
  },
  {
    title: 'Kielbasa and Sauerkraut',
    description: 'Smoked Polish sausage braised with sauerkraut, apples, and caraway seeds.',
    cuisine: 'Eastern European',
    prep_minutes: 10,
    cook_minutes: 30,
    servings: 6,
    calories: 380,
    ingredients: [
      { name: 'kielbasa', quantity: '1', unit: 'lb, sliced' },
      { name: 'sauerkraut', quantity: '3', unit: 'cups, drained' },
      { name: 'apple', quantity: '1', unit: 'diced' },
      { name: 'onion', quantity: '1', unit: 'sliced' },
      { name: 'caraway seeds', quantity: '1', unit: 'tsp' },
      { name: 'brown sugar', quantity: '1', unit: 'tbsp' },
      { name: 'beer', quantity: '1/2', unit: 'cup' },
      { name: 'butter', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Brown kielbasa slices in a Dutch oven.',
      'Add onion and apple, sauté 3 minutes.',
      'Add sauerkraut, caraway, brown sugar, and beer.',
      'Cover and simmer 20-25 minutes.',
      'Stir in butter before serving.',
      'Serve with rye bread and mustard.',
    ],
    tags: ['eastern-european', 'polish', 'sausage', 'sauerkraut', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 18,
      carbs_g: 10,
      fat_g: 28,
      fiber_g: 4,
      sugar_g: 5,
      sodium_mg: 1100,
    },
  },
  {
    title: 'Honey Cake',
    description:
      'Multi-layered Russian honey cake with creamy sour cream frosting — a beloved celebration dessert.',
    cuisine: 'Eastern European',
    prep_minutes: 30,
    cook_minutes: 10,
    servings: 12,
    calories: 320,
    ingredients: [
      { name: 'honey', quantity: '1/2', unit: 'cup' },
      { name: 'butter', quantity: '1/2', unit: 'cup' },
      { name: 'sugar', quantity: '1/2', unit: 'cup' },
      { name: 'egg', quantity: '3', unit: 'large' },
      { name: 'flour', quantity: '3', unit: 'cups' },
      { name: 'baking soda', quantity: '1', unit: 'tsp' },
      { name: 'sour cream', quantity: '2', unit: 'cups' },
      { name: 'vanilla', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Melt honey, butter, and sugar together. Add eggs and mix.',
      'Add flour and baking soda to form a soft dough.',
      'Divide into 8 portions. Roll each very thin and bake at 400°F for 5 minutes.',
      'Make frosting: whip sour cream with sugar and vanilla.',
      'Layer cake rounds with sour cream frosting.',
      'Crumble one layer for crumbs, press on sides. Chill overnight.',
    ],
    tags: ['eastern-european', 'dessert', 'honey', 'cake', 'russian'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 6,
      carbs_g: 42,
      fat_g: 14,
      fiber_g: 1,
      sugar_g: 24,
      sodium_mg: 220,
    },
  },
  {
    title: 'Kvass',
    description: 'Traditional fermented bread drink, lightly effervescent and slightly sweet-sour.',
    cuisine: 'Eastern European',
    prep_minutes: 15,
    cook_minutes: 0,
    servings: 8,
    calories: 80,
    ingredients: [
      { name: 'rye bread', quantity: '1', unit: 'lb, dried & toasted' },
      { name: 'water', quantity: '12', unit: 'cups, boiling' },
      { name: 'sugar', quantity: '1', unit: 'cup' },
      { name: 'yeast', quantity: '1/4', unit: 'tsp' },
      { name: 'raisins', quantity: '1/4', unit: 'cup' },
      { name: 'mint', quantity: '4', unit: 'sprigs' },
    ],
    steps: [
      'Toast rye bread until very dark (almost burnt).',
      'Pour boiling water over bread. Let steep 8 hours.',
      'Strain liquid, add sugar and stir to dissolve.',
      'Cool to lukewarm, add yeast. Let ferment 12-24 hours.',
      'Strain, add raisins and mint. Bottle and chill.',
      'Serve cold as a refreshing drink.',
    ],
    tags: ['eastern-european', 'drink', 'fermented', 'bread', 'russian'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 80,
      protein_g: 1,
      carbs_g: 18,
      fat_g: 0,
      fiber_g: 1,
      sugar_g: 14,
      sodium_mg: 40,
    },
  },
  {
    title: 'Shashlik',
    description:
      'Marinated lamb or pork skewers grilled over charcoal, a beloved BBQ across Eastern Europe.',
    cuisine: 'Eastern European',
    prep_minutes: 20,
    cook_minutes: 12,
    servings: 6,
    calories: 320,
    ingredients: [
      { name: 'pork shoulder', quantity: '2', unit: 'lb, cubed' },
      { name: 'onion', quantity: '3', unit: 'large, sliced' },
      { name: 'vinegar', quantity: '2', unit: 'tbsp' },
      { name: 'lemon juice', quantity: '2', unit: 'tbsp' },
      { name: 'garlic', quantity: '4', unit: 'cloves, minced' },
      { name: 'paprika', quantity: '1', unit: 'tbsp' },
      { name: 'coriander', quantity: '1', unit: 'tsp' },
      { name: 'metal skewers', quantity: '6', unit: 'pieces' },
    ],
    steps: [
      'Marinate pork with onion, vinegar, lemon, garlic, paprika, and coriander for 4-8 hours.',
      'Thread pork onto skewers, alternating with onion.',
      'Grill over hot charcoal, turning every 3 minutes.',
      'Cook until charred on outside and juicy inside, about 12 minutes total.',
      'Serve with flatbread, sliced raw onion, and vinegar.',
    ],
    tags: ['eastern-european', 'grilled', 'skewers', 'pork', 'bbq'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 320,
      protein_g: 28,
      carbs_g: 4,
      fat_g: 20,
      fiber_g: 1,
      sugar_g: 1,
      sodium_mg: 380,
    },
  },
];

export const easternEuropeanRecipes = generateCuisineRecipes(configs);

// ── Additional Eastern European recipes ──────────────────────────────────────

const additionalEasternEuropeanConfigs: CuisineRecipeConfig[] = [
  {
    title: 'Borscht',
    description: 'Deep ruby beet soup with beef, cabbage, and a dollop of sour cream.',
    cuisine: 'Eastern European',
    prep_minutes: 20,
    cook_minutes: 60,
    servings: 8,
    calories: 180,
    ingredients: [
      { name: 'beet', quantity: '4', unit: 'medium, grated' },
      { name: 'beef', quantity: '1', unit: 'lb, cubed' },
      { name: 'cabbage', quantity: '2', unit: 'cups, shredded' },
      { name: 'potato', quantity: '2', unit: 'diced' },
      { name: 'carrot', quantity: '1', unit: 'sliced' },
      { name: 'tomato paste', quantity: '2', unit: 'tbsp' },
      { name: 'sour cream', quantity: '1/2', unit: 'cup' },
      { name: 'dill', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Brown beef in a pot. Add water and simmer 30 minutes.',
      'Add beets, potato, carrot, and cabbage.',
      'Add tomato paste. Simmer 30 minutes.',
      'Season with vinegar, salt, and pepper.',
      'Serve with a generous dollop of sour cream.',
      'Garnish with dill.',
    ],
    tags: ['eastern-european', 'soup', 'beet', 'beef', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 180,
      protein_g: 14,
      carbs_g: 16,
      fat_g: 6,
      fiber_g: 3,
      sugar_g: 6,
      sodium_mg: 480,
    },
  },
  {
    title: 'Pierogi',
    description: 'Polish dumplings filled with potato and cheese, pan-fried with onion.',
    cuisine: 'Eastern European',
    prep_minutes: 30,
    cook_minutes: 10,
    servings: 6,
    calories: 280,
    ingredients: [
      { name: 'flour', quantity: '2', unit: 'cups' },
      { name: 'egg', quantity: '1', unit: 'large' },
      { name: 'potato', quantity: '3', unit: 'mashed' },
      { name: 'farmer cheese', quantity: '1/2', unit: 'cup, crumbled' },
      { name: 'onion', quantity: '2', unit: 'caramelized' },
      { name: 'sour cream', quantity: '1/2', unit: 'cup' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Make dough with flour, egg, and water. Rest 30 minutes.',
      'Mix mashed potato with cheese and caramelized onion.',
      'Roll dough, cut circles, fill, and crimp.',
      'Boil until they float.',
      'Pan-fry in butter until golden.',
      'Serve with sour cream and more caramelized onion.',
    ],
    tags: ['eastern-european', 'dumplings', 'potato', 'polish', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 8,
      carbs_g: 38,
      fat_g: 10,
      fiber_g: 2,
      sugar_g: 2,
      sodium_mg: 380,
    },
  },
  {
    title: 'Beef Stroganoff',
    description: 'Russian beef strips in a creamy mushroom sauce with a hint of mustard.',
    cuisine: 'Eastern European',
    prep_minutes: 15,
    cook_minutes: 20,
    servings: 4,
    calories: 380,
    ingredients: [
      { name: 'beef sirloin', quantity: '1', unit: 'lb, sliced thin' },
      { name: 'mushroom', quantity: '8', unit: 'oz, sliced' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'sour cream', quantity: '1', unit: 'cup' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
      { name: 'mustard', quantity: '1', unit: 'tsp' },
      { name: 'egg noodles', quantity: '8', unit: 'oz' },
    ],
    steps: [
      'Sear beef strips in butter. Set aside.',
      'Sauté onion and mushroom.',
      'Add broth and mustard. Simmer 10 minutes.',
      'Stir in sour cream off the heat.',
      'Return beef.',
      'Serve over egg noodles.',
    ],
    tags: ['eastern-european', 'beef', 'mushroom', 'creamy', 'russian'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 28,
      carbs_g: 20,
      fat_g: 20,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 480,
    },
  },
  {
    title: 'Cabbage Rolls (Golubtsi)',
    description: 'Stuffed cabbage leaves with rice and meat in a tomato sauce.',
    cuisine: 'Eastern European',
    prep_minutes: 30,
    cook_minutes: 60,
    servings: 6,
    calories: 280,
    ingredients: [
      { name: 'cabbage', quantity: '1', unit: 'large, leaves separated' },
      { name: 'ground beef', quantity: '1/2', unit: 'lb' },
      { name: 'ground pork', quantity: '1/2', unit: 'lb' },
      { name: 'rice', quantity: '1/2', unit: 'cup, cooked' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'tomato sauce', quantity: '2', unit: 'cups' },
      { name: 'sour cream', quantity: '1/2', unit: 'cup' },
    ],
    steps: [
      'Blanch cabbage leaves until pliable.',
      'Mix beef, pork, rice, and onion. Season.',
      'Roll filling in cabbage leaves.',
      'Place in a pot, seam-side down.',
      'Pour tomato sauce over. Simmer 1 hour.',
      'Serve with sour cream.',
    ],
    tags: ['eastern-european', 'cabbage', 'stuffed', 'comfort-food', 'ukrainian'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 18,
      carbs_g: 18,
      fat_g: 14,
      fiber_g: 2,
      sugar_g: 4,
      sodium_mg: 580,
    },
  },
  {
    title: 'Blini',
    description: 'Russian thin pancakes served with sour cream, caviar, or jam.',
    cuisine: 'Eastern European',
    prep_minutes: 15,
    cook_minutes: 10,
    servings: 8,
    calories: 160,
    ingredients: [
      { name: 'flour', quantity: '1', unit: 'cup' },
      { name: 'milk', quantity: '1', unit: 'cup' },
      { name: 'egg', quantity: '2', unit: 'large' },
      { name: 'butter', quantity: '2', unit: 'tbsp, melted' },
      { name: 'sugar', quantity: '1', unit: 'tbsp' },
      { name: 'yeast', quantity: '1/2', unit: 'tsp' },
    ],
    steps: [
      'Mix flour, yeast, sugar, egg, and milk into a thin batter.',
      'Let rise 30 minutes.',
      'Add melted butter.',
      'Cook small thin pancakes in a hot pan.',
      'Serve with sour cream and caviar, or jam.',
      'Fold into quarters or roll up.',
    ],
    tags: ['eastern-european', 'pancakes', 'russian', 'breakfast', 'festive'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 160,
      protein_g: 5,
      carbs_g: 20,
      fat_g: 6,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 120,
    },
  },
  {
    title: 'Shashlik',
    description: 'Caucasus-style marinated pork skewers grilled over charcoal with onion.',
    cuisine: 'Eastern European',
    prep_minutes: 15,
    cook_minutes: 15,
    servings: 6,
    calories: 320,
    ingredients: [
      { name: 'pork shoulder', quantity: '2', unit: 'lb, cubed' },
      { name: 'onion', quantity: '3', unit: 'sliced' },
      { name: 'vinegar', quantity: '2', unit: 'tbsp' },
      { name: 'black pepper', quantity: '1', unit: 'tsp' },
      { name: 'bay leaf', quantity: '2', unit: 'leaves' },
      { name: 'lemon', quantity: '1', unit: 'juiced' },
    ],
    steps: [
      'Marinate pork with onion, vinegar, pepper, bay leaf, and lemon for 4+ hours.',
      'Thread onto skewers, alternating with onion.',
      'Grill over hot charcoal until charred and cooked.',
      'Serve with raw onion and flatbread.',
      'Accompany with adjika or tkemali sauce.',
    ],
    tags: ['eastern-european', 'grilled', 'pork', 'skewers', 'caucasus'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 320,
      protein_g: 28,
      carbs_g: 4,
      fat_g: 20,
      fiber_g: 0,
      sugar_g: 1,
      sodium_mg: 380,
    },
  },
  {
    title: 'Syrniki',
    description:
      'Russian cottage cheese pancakes, lightly fried and served with sour cream and jam.',
    cuisine: 'Eastern European',
    prep_minutes: 10,
    cook_minutes: 8,
    servings: 4,
    calories: 220,
    ingredients: [
      { name: 'cottage cheese (tvorog)', quantity: '1', unit: 'lb' },
      { name: 'egg', quantity: '1', unit: 'large' },
      { name: 'flour', quantity: '3', unit: 'tbsp' },
      { name: 'sugar', quantity: '2', unit: 'tbsp' },
      { name: 'vanilla', quantity: '1/2', unit: 'tsp' },
      { name: 'oil', quantity: '1', unit: 'tbsp, for frying' },
    ],
    steps: [
      'Mix tvorog, egg, flour, sugar, and vanilla.',
      'Form into thick patties.',
      'Pan-fry in oil until golden on both sides.',
      'Serve with sour cream.',
      'Add berry jam or honey.',
    ],
    tags: ['eastern-european', 'pancakes', 'cheese', 'breakfast', 'russian'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 220,
      protein_g: 14,
      carbs_g: 16,
      fat_g: 10,
      fiber_g: 0,
      sugar_g: 6,
      sodium_mg: 280,
    },
  },
  {
    title: 'Kulich',
    description: 'Tall Russian Easter bread with dried fruit, topped with white icing.',
    cuisine: 'Eastern European',
    prep_minutes: 30,
    cook_minutes: 40,
    servings: 10,
    calories: 280,
    ingredients: [
      { name: 'flour', quantity: '4', unit: 'cups' },
      { name: 'yeast', quantity: '1', unit: 'packet' },
      { name: 'milk', quantity: '1', unit: 'cup, warm' },
      { name: 'butter', quantity: '1/2', unit: 'cup' },
      { name: 'egg', quantity: '3', unit: 'large' },
      { name: 'sugar', quantity: '1/2', unit: 'cup' },
      { name: 'raisins', quantity: '1/2', unit: 'cup' },
      { name: 'vanilla', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Make a sponge with yeast, warm milk, and 1 cup flour. Let rise.',
      'Add butter, eggs, sugar, vanilla, and remaining flour.',
      'Knead in raisins. Let rise until doubled.',
      'Spoon into tall cylindrical molds (coffee cans).',
      'Bake at 350°F for 35-40 minutes.',
      'Top with white icing and sprinkles.',
    ],
    tags: ['eastern-european', 'bread', 'easter', 'russian', 'sweet'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 6,
      carbs_g: 42,
      fat_g: 8,
      fiber_g: 1,
      sugar_g: 14,
      sodium_mg: 180,
    },
  },
];

export const easternEuropeanAdditionalRecipes = generateCuisineRecipes(
  additionalEasternEuropeanConfigs,
);
