import type { CuisineRecipeConfig } from './types';
import { generateCuisineRecipes } from './types';

const configs: CuisineRecipeConfig[] = [
  {
    title: 'Chicken Adobo',
    description:
      'Philippine adobo — chicken braised in soy sauce, vinegar, garlic, and bay leaves.',
    cuisine: 'Filipino',
    prep_minutes: 10,
    cook_minutes: 40,
    servings: 6,
    calories: 320,
    ingredients: [
      { name: 'chicken thigh', quantity: '3', unit: 'lb' },
      { name: 'soy sauce', quantity: '1/2', unit: 'cup' },
      { name: 'vinegar', quantity: '1/4', unit: 'cup' },
      { name: 'garlic', quantity: '1', unit: 'head, crushed' },
      { name: 'bay leaf', quantity: '3', unit: 'leaves' },
      { name: 'peppercorns', quantity: '1', unit: 'tsp' },
      { name: 'sugar', quantity: '1', unit: 'tbsp' },
      { name: 'oil', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Marinate chicken in soy sauce, vinegar, garlic, and bay leaves for 1 hour.',
      'Brown chicken in oil.',
      'Add marinade and enough water to cover.',
      'Simmer 30-40 minutes until chicken is tender.',
      'Reduce sauce until slightly thickened.',
      'Serve with steamed rice.',
    ],
    tags: ['filipino', 'chicken', 'adobo', 'soy-sauce', 'vinegar'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 28,
      carbs_g: 6,
      fat_g: 20,
      fiber_g: 0,
      sugar_g: 2,
      sodium_mg: 860,
    },
  },
  {
    title: 'Sinigang',
    description: 'Tamarind-sour Filipino soup with pork, vegetables, and a tangy broth.',
    cuisine: 'Filipino',
    prep_minutes: 15,
    cook_minutes: 40,
    servings: 6,
    calories: 280,
    ingredients: [
      { name: 'pork belly', quantity: '1', unit: 'lb, cubed' },
      { name: 'tamarind soup base', quantity: '2', unit: 'tbsp' },
      { name: 'tomato', quantity: '2', unit: 'quartered' },
      { name: 'water spinach', quantity: '2', unit: 'cups' },
      { name: 'radish', quantity: '1', unit: 'sliced' },
      { name: 'eggplant', quantity: '1', unit: 'sliced' },
      { name: 'okra', quantity: '8', unit: 'pieces' },
      { name: 'onion', quantity: '1', unit: 'quartered' },
    ],
    steps: [
      'Boil pork with onion and tomato until tender.',
      'Add tamarind base and stir to dissolve.',
      'Add radish and eggplant. Cook 5 minutes.',
      'Add okra and water spinach.',
      'Simmer 3-5 minutes until vegetables are just done.',
      'Serve hot with rice. The broth should be very sour.',
    ],
    tags: ['filipino', 'soup', 'pork', 'tamarind', 'sour'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 280,
      protein_g: 18,
      carbs_g: 10,
      fat_g: 18,
      fiber_g: 3,
      sugar_g: 3,
      sodium_mg: 580,
    },
  },
  {
    title: 'Lumpia',
    description: 'Crispy Filipino spring rolls filled with ground pork and vegetables.',
    cuisine: 'Filipino',
    prep_minutes: 30,
    cook_minutes: 10,
    servings: 12,
    calories: 160,
    ingredients: [
      { name: 'lumpia wrappers', quantity: '30', unit: 'pieces' },
      { name: 'ground pork', quantity: '1', unit: 'lb' },
      { name: 'carrot', quantity: '1', unit: 'minced' },
      { name: 'onion', quantity: '1', unit: 'minced' },
      { name: 'garlic', quantity: '3', unit: 'cloves, minced' },
      { name: 'soy sauce', quantity: '1', unit: 'tbsp' },
      { name: 'egg', quantity: '1', unit: 'beaten' },
      { name: 'oil', quantity: '2', unit: 'cups, for frying' },
    ],
    steps: [
      'Mix pork, carrot, onion, garlic, soy sauce, and egg.',
      'Place a tablespoon of filling on a wrapper, roll tightly into a thin cylinder.',
      'Seal the edge with water.',
      'Deep fry at 350°F until golden and crispy.',
      'Drain on paper towels.',
      'Serve with sweet chili sauce or banana ketchup.',
    ],
    tags: ['filipino', 'spring-rolls', 'pork', 'fried', 'appetizer'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 160,
      protein_g: 8,
      carbs_g: 14,
      fat_g: 8,
      fiber_g: 1,
      sugar_g: 1,
      sodium_mg: 320,
    },
  },
  {
    title: 'Pancit',
    description: 'Filipino stir-fried noodles with vegetables, chicken, and soy sauce.',
    cuisine: 'Filipino',
    prep_minutes: 15,
    cook_minutes: 10,
    servings: 6,
    calories: 320,
    ingredients: [
      { name: 'pancit noodles', quantity: '8', unit: 'oz' },
      { name: 'chicken breast', quantity: '1/2', unit: 'lb, sliced' },
      { name: 'cabbage', quantity: '1', unit: 'cup, shredded' },
      { name: 'carrot', quantity: '1', unit: 'julienned' },
      { name: 'green bean', quantity: '1', unit: 'cup, cut' },
      { name: 'soy sauce', quantity: '3', unit: 'tbsp' },
      { name: 'garlic', quantity: '3', unit: 'cloves' },
      { name: 'onion', quantity: '1', unit: 'sliced' },
    ],
    steps: [
      'Soak noodles in warm water.',
      'Sauté garlic, onion, and chicken.',
      'Add vegetables and stir-fry.',
      'Add soy sauce and chicken broth.',
      'Add noodles and toss until absorbed.',
      'Serve with calamansi or lemon.',
    ],
    tags: ['filipino', 'noodles', 'stir-fry', 'chicken', 'celebration'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 18,
      carbs_g: 42,
      fat_g: 6,
      fiber_g: 3,
      sugar_g: 2,
      sodium_mg: 680,
    },
  },
  {
    title: 'Lechon Kawali',
    description: 'Crispy deep-fried pork belly served with liver sauce (Mang Tomas).',
    cuisine: 'Filipino',
    prep_minutes: 10,
    cook_minutes: 60,
    servings: 6,
    calories: 480,
    ingredients: [
      { name: 'pork belly', quantity: '2', unit: 'lb, skin-on' },
      { name: 'garlic', quantity: '6', unit: 'cloves, crushed' },
      { name: 'bay leaf', quantity: '3', unit: 'leaves' },
      { name: 'peppercorns', quantity: '1', unit: 'tsp' },
      { name: 'salt', quantity: '1', unit: 'tbsp' },
      { name: 'oil', quantity: '3', unit: 'cups, for frying' },
      { name: 'liver sauce', quantity: '1/2', unit: 'cup' },
    ],
    steps: [
      'Boil pork belly with garlic, bay leaf, peppercorns, and salt for 45 minutes.',
      'Cool completely and dry the skin thoroughly.',
      'Deep fry at 350°F until skin is blistered and very crispy.',
      'Drain and chop into pieces.',
      'Serve with liver sauce and vinegar dip.',
    ],
    tags: ['filipino', 'pork', 'fried', 'crispy', 'celebration'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 480,
      protein_g: 24,
      carbs_g: 2,
      fat_g: 40,
      fiber_g: 0,
      sugar_g: 0,
      sodium_mg: 680,
    },
  },
  {
    title: 'Kare-Kare',
    description: 'Filipino oxtail stew in a rich peanut sauce with vegetables and bagoong.',
    cuisine: 'Filipino',
    prep_minutes: 20,
    cook_minutes: 180,
    servings: 8,
    calories: 380,
    ingredients: [
      { name: 'oxtail', quantity: '2', unit: 'lb, cut' },
      { name: 'peanut butter', quantity: '1/2', unit: 'cup' },
      { name: 'annatto seeds', quantity: '1', unit: 'tbsp' },
      { name: 'eggplant', quantity: '1', unit: 'sliced' },
      { name: 'bok choy', quantity: '1', unit: 'bunch' },
      { name: 'green bean', quantity: '1', unit: 'cup' },
      { name: 'bagoong (shrimp paste)', quantity: '2', unit: 'tbsp' },
      { name: 'rice', quantity: '1/4', unit: 'cup, ground' },
    ],
    steps: [
      'Boil oxtail until very tender, about 2.5 hours.',
      'Soak annatto seeds in warm water for color.',
      'Add peanut butter and ground rice to thicken the broth.',
      'Add annatto water for the orange color.',
      'Add eggplant, green beans, and bok choy.',
      'Serve with bagoong on the side and rice.',
    ],
    tags: ['filipino', 'stew', 'oxtail', 'peanut', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 24,
      carbs_g: 14,
      fat_g: 24,
      fiber_g: 3,
      sugar_g: 3,
      sodium_mg: 580,
    },
  },
  {
    title: 'Halo-Halo',
    description:
      'Filipino shaved ice dessert with sweet beans, fruits, leche flan, and ube ice cream.',
    cuisine: 'Filipino',
    prep_minutes: 15,
    cook_minutes: 0,
    servings: 4,
    calories: 320,
    ingredients: [
      { name: 'shaved ice', quantity: '4', unit: 'cups' },
      { name: 'sweet red beans', quantity: '1/4', unit: 'cup' },
      { name: 'ube halaya', quantity: '1/4', unit: 'cup' },
      { name: 'leche flan', quantity: '4', unit: 'slices' },
      { name: 'condensed milk', quantity: '1/4', unit: 'cup' },
      { name: 'evaporated milk', quantity: '1/4', unit: 'cup' },
      { name: 'banana', quantity: '1', unit: 'sliced' },
      { name: 'jackfruit', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Place sweet beans, ube, banana, and jackfruit in a tall glass.',
      'Pack shaved ice on top.',
      'Pour evaporated and condensed milk over the ice.',
      'Top with leche flan.',
      'Serve with a long spoon — mix (halo) before eating!',
    ],
    tags: ['filipino', 'dessert', 'shaved-ice', 'ube', 'sweet'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 6,
      carbs_g: 56,
      fat_g: 8,
      fiber_g: 3,
      sugar_g: 38,
      sodium_mg: 120,
    },
  },
  {
    title: 'Sisig',
    description:
      'Sizzling chopped pork face and belly with calamansi, onion, and chili — a Filipino bar favorite.',
    cuisine: 'Filipino',
    prep_minutes: 15,
    cook_minutes: 30,
    servings: 4,
    calories: 380,
    ingredients: [
      { name: 'pork belly', quantity: '1', unit: 'lb' },
      { name: 'pork face (maskara)', quantity: '1/2', unit: 'lb' },
      { name: 'onion', quantity: '2', unit: 'minced' },
      { name: 'calamansi', quantity: '4', unit: 'pieces' },
      { name: 'chili', quantity: '2', unit: 'sliced' },
      { name: 'soy sauce', quantity: '1', unit: 'tbsp' },
      { name: 'mayonnaise', quantity: '2', unit: 'tbsp' },
      { name: 'egg', quantity: '1', unit: 'raw' },
    ],
    steps: [
      'Boil and grill pork belly and face until charred.',
      'Chop into very small pieces.',
      'Sauté onion, add chopped pork, soy sauce, and calamansi.',
      'Season with chili and pepper.',
      'Serve on a sizzling hot plate.',
      'Top with raw egg and mayo, mix as it sizzles.',
    ],
    tags: ['filipino', 'pork', 'sizzling', 'spicy', 'bar-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 22,
      carbs_g: 6,
      fat_g: 28,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 580,
    },
  },
  {
    title: 'Bistek Tagalog',
    description:
      'Filipino beef steak marinated in calamansi and soy sauce, with caramelized onion rings.',
    cuisine: 'Filipino',
    prep_minutes: 15,
    cook_minutes: 10,
    servings: 4,
    calories: 320,
    ingredients: [
      { name: 'beef sirloin', quantity: '1', unit: 'lb, sliced thin' },
      { name: 'soy sauce', quantity: '1/4', unit: 'cup' },
      { name: 'calamansi juice', quantity: '3', unit: 'tbsp' },
      { name: 'onion', quantity: '2', unit: 'rings' },
      { name: 'garlic', quantity: '3', unit: 'cloves, minced' },
      { name: 'oil', quantity: '2', unit: 'tbsp' },
      { name: 'peppercorns', quantity: '1/2', unit: 'tsp, cracked' },
    ],
    steps: [
      'Marinate beef in soy sauce and calamansi for 1 hour.',
      'Pan-fry beef until browned.',
      'Caramelize onion rings in the same pan.',
      'Return beef, add marinade and a splash of water.',
      'Simmer 5 minutes.',
      'Top with onion rings and serve with rice.',
    ],
    tags: ['filipino', 'beef', 'soy-sauce', 'calamansi', 'quick'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 32,
      carbs_g: 6,
      fat_g: 16,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 860,
    },
  },
  {
    title: 'Ube Halaya',
    description: 'Purple yam jam cooked with coconut milk and butter — a beloved Filipino dessert.',
    cuisine: 'Filipino',
    prep_minutes: 10,
    cook_minutes: 30,
    servings: 8,
    calories: 180,
    ingredients: [
      { name: 'purple yam (ube)', quantity: '1', unit: 'lb, grated' },
      { name: 'coconut milk', quantity: '1', unit: 'can (14 oz)' },
      { name: 'condensed milk', quantity: '1/2', unit: 'cup' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
      { name: 'vanilla', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Grate or mash cooked ube.',
      'Cook ube with coconut milk, stirring constantly.',
      'Add condensed milk and butter.',
      'Cook over medium-low heat for 20-30 minutes until very thick.',
      'Add vanilla.',
      'Spread in a dish, cool, and serve.',
    ],
    tags: ['filipino', 'dessert', 'ube', 'purple-yam', 'coconut'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 180,
      protein_g: 2,
      carbs_g: 28,
      fat_g: 7,
      fiber_g: 2,
      sugar_g: 16,
      sodium_mg: 60,
    },
  },
  {
    title: 'Laing',
    description: 'Bicol-style taro leaves cooked in coconut milk with chili and shrimp paste.',
    cuisine: 'Filipino',
    prep_minutes: 10,
    cook_minutes: 30,
    servings: 4,
    calories: 180,
    ingredients: [
      { name: 'dried taro leaves', quantity: '2', unit: 'cups' },
      { name: 'coconut milk', quantity: '2', unit: 'cans (14 oz)' },
      { name: 'shrimp paste', quantity: '1', unit: 'tbsp' },
      { name: 'chili', quantity: '3', unit: 'sliced' },
      { name: 'garlic', quantity: '3', unit: 'cloves, minced' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'pork belly', quantity: '1/4', unit: 'lb, diced' },
    ],
    steps: [
      'Sauté garlic, onion, and pork belly.',
      'Add coconut milk and bring to a simmer.',
      'Add dried taro leaves — do not stir!',
      'Simmer 20-30 minutes until leaves are soft and liquid is reduced.',
      'Add chili and shrimp paste.',
      'Serve with rice.',
    ],
    tags: ['filipino', 'vegetables', 'coconut', 'spicy', 'bicol'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 180,
      protein_g: 8,
      carbs_g: 6,
      fat_g: 14,
      fiber_g: 2,
      sugar_g: 1,
      sodium_mg: 480,
    },
  },
  {
    title: 'Tocino',
    description: 'Sweet cured pork, pan-fried until caramelized — a Filipino breakfast staple.',
    cuisine: 'Filipino',
    prep_minutes: 10,
    cook_minutes: 10,
    servings: 4,
    calories: 340,
    ingredients: [
      { name: 'pork shoulder', quantity: '1', unit: 'lb, sliced thin' },
      { name: 'sugar', quantity: '1/4', unit: 'cup' },
      { name: 'soy sauce', quantity: '2', unit: 'tbsp' },
      { name: 'garlic', quantity: '3', unit: 'cloves, minced' },
      { name: 'annatto powder', quantity: '1', unit: 'tsp' },
      { name: 'salt', quantity: '1/2', unit: 'tsp' },
    ],
    steps: [
      'Mix sugar, soy sauce, garlic, annatto, and salt.',
      'Marinate pork for at least 24 hours.',
      'Pan-fry with a little water, cover and cook until water evaporates.',
      'Continue frying in rendered fat until caramelized.',
      'Serve with garlic fried rice and a fried egg.',
      'This is the classic "tocilog" breakfast.',
    ],
    tags: ['filipino', 'pork', 'breakfast', 'sweet', 'cured'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 340,
      protein_g: 22,
      carbs_g: 16,
      fat_g: 20,
      fiber_g: 0,
      sugar_g: 10,
      sodium_mg: 680,
    },
  },
];

export const filipinoRecipes = generateCuisineRecipes(configs);
