import type { CuisineRecipeConfig } from './types';
import { generateCuisineRecipes } from './types';

const configs: CuisineRecipeConfig[] = [
  {
    title: 'Coq au Vin',
    description:
      'Classic French braised chicken in red wine with mushrooms, pearl onions, and lardons.',
    cuisine: 'French',
    prep_minutes: 30,
    cook_minutes: 90,
    servings: 6,
    calories: 420,
    ingredients: [
      { name: 'chicken', quantity: '1', unit: '(4 lb), cut up' },
      { name: 'red wine', quantity: '2', unit: 'cups' },
      { name: 'lardons', quantity: '4', unit: 'oz' },
      { name: 'pearl onions', quantity: '1', unit: 'cup' },
      { name: 'mushrooms', quantity: '1', unit: 'cup, quartered' },
      { name: 'carrot', quantity: '1', unit: 'sliced' },
      { name: 'garlic', quantity: '3', unit: 'cloves' },
      { name: 'thyme', quantity: '3', unit: 'sprigs' },
      { name: 'bay leaf', quantity: '2', unit: 'leaves' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Brown lardons in a Dutch oven. Remove and set aside.',
      'Brown chicken pieces in the rendered fat on all sides. Remove.',
      'Sauté pearl onions, mushrooms, and carrot in butter.',
      'Deglaze with red wine, scraping up browned bits.',
      'Return chicken and lardons, add thyme and bay leaf. Cover and braise at 325°F for 1.5 hours.',
      'Remove lid for the last 20 minutes to reduce sauce. Serve with crusty bread or mashed potatoes.',
    ],
    tags: ['french', 'braised', 'chicken', 'wine', 'classic'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 36,
      carbs_g: 10,
      fat_g: 24,
      fiber_g: 2,
      sugar_g: 4,
      sodium_mg: 580,
    },
  },
  {
    title: 'Ratatouille',
    description: 'Provençal vegetable stew of layered zucchini, eggplant, tomato, and bell pepper.',
    cuisine: 'French',
    prep_minutes: 30,
    cook_minutes: 45,
    servings: 6,
    calories: 160,
    ingredients: [
      { name: 'eggplant', quantity: '1', unit: 'medium, sliced' },
      { name: 'zucchini', quantity: '2', unit: 'sliced' },
      { name: 'bell pepper', quantity: '2', unit: 'sliced' },
      { name: 'tomato', quantity: '4', unit: 'sliced' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'garlic', quantity: '4', unit: 'cloves, minced' },
      { name: 'olive oil', quantity: '3', unit: 'tbsp' },
      { name: 'thyme', quantity: '3', unit: 'sprigs' },
      { name: 'basil', quantity: '1/4', unit: 'cup, fresh' },
    ],
    steps: [
      'Sauté onion and garlic in olive oil until softened.',
      'Arrange sliced vegetables in a baking dish in an overlapping pattern.',
      'Drizzle with olive oil, season with salt, pepper, and thyme.',
      'Cover with foil and bake at 375°F for 40 minutes.',
      'Remove foil and bake 15 more minutes until edges are golden.',
      'Garnish with fresh basil and serve as a main or side.',
    ],
    tags: ['french', 'vegetarian', 'vegan', 'vegetables', 'provencal'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 160,
      protein_g: 4,
      carbs_g: 18,
      fat_g: 10,
      fiber_g: 6,
      sugar_g: 8,
      sodium_mg: 220,
    },
  },
  {
    title: 'Beef Bourguignon',
    description: 'Rich French beef stew braised in Burgundy wine with pearl onions and mushrooms.',
    cuisine: 'French',
    prep_minutes: 30,
    cook_minutes: 150,
    servings: 8,
    calories: 480,
    ingredients: [
      { name: 'beef chuck', quantity: '3', unit: 'lb, cubed' },
      { name: 'Burgundy wine', quantity: '3', unit: 'cups' },
      { name: 'pearl onions', quantity: '1', unit: 'cup' },
      { name: 'mushrooms', quantity: '1', unit: 'cup, quartered' },
      { name: 'carrot', quantity: '2', unit: 'chunked' },
      { name: 'garlic', quantity: '4', unit: 'cloves' },
      { name: 'tomato paste', quantity: '2', unit: 'tbsp' },
      { name: 'thyme', quantity: '3', unit: 'sprigs' },
      { name: 'bay leaf', quantity: '2', unit: 'leaves' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Pat beef dry and brown in batches in a Dutch oven. Set aside.',
      'Sauté carrots, onion, and garlic. Add tomato paste and cook 2 minutes.',
      'Deglaze with wine, add beef back with thyme and bay leaf.',
      'Cover and braise at 325°F for 2-2.5 hours until beef is fork-tender.',
      'Sauté mushrooms and pearl onions in butter, add to the stew.',
      'Simmer 15 minutes, adjust seasoning. Serve with crusty bread or egg noodles.',
    ],
    tags: ['french', 'stew', 'beef', 'wine', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 480,
      protein_g: 42,
      carbs_g: 12,
      fat_g: 26,
      fiber_g: 2,
      sugar_g: 4,
      sodium_mg: 620,
    },
  },
  {
    title: 'Crème Brûlée',
    description: 'Silky vanilla custard with a shatteringly crisp caramelized sugar top.',
    cuisine: 'French',
    prep_minutes: 15,
    cook_minutes: 45,
    servings: 6,
    calories: 320,
    ingredients: [
      { name: 'heavy cream', quantity: '2', unit: 'cups' },
      { name: 'egg yolk', quantity: '6', unit: 'large' },
      { name: 'sugar', quantity: '1/2', unit: 'cup' },
      { name: 'vanilla bean', quantity: '1', unit: 'split' },
      { name: 'salt', quantity: '1', unit: 'pinch' },
      { name: 'superfine sugar', quantity: '6', unit: 'tsp, for topping' },
    ],
    steps: [
      'Heat cream with vanilla bean and seeds until just simmering. Steep 15 minutes.',
      'Whisk egg yolks and sugar until pale.',
      'Slowly temper hot cream into yolk mixture, stirring constantly.',
      'Strain into ramekins. Bake in a water bath at 325°F for 40-45 minutes.',
      'Chill custards for at least 4 hours or overnight.',
      'Sprinkle superfine sugar on top and torch until caramelized and crackling.',
    ],
    tags: ['french', 'dessert', 'custard', 'vanilla', 'classic'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 4,
      carbs_g: 22,
      fat_g: 26,
      fiber_g: 0,
      sugar_g: 20,
      sodium_mg: 60,
    },
  },
  {
    title: 'French Onion Soup',
    description:
      'Deeply caramelized onion soup topped with crusty bread and melted Gruyère cheese.',
    cuisine: 'French',
    prep_minutes: 15,
    cook_minutes: 60,
    servings: 4,
    calories: 380,
    ingredients: [
      { name: 'onion', quantity: '6', unit: 'large, thinly sliced' },
      { name: 'beef broth', quantity: '6', unit: 'cups' },
      { name: 'butter', quantity: '3', unit: 'tbsp' },
      { name: 'white wine', quantity: '1/2', unit: 'cup' },
      { name: 'thyme', quantity: '2', unit: 'sprigs' },
      { name: 'bay leaf', quantity: '1', unit: 'leaf' },
      { name: 'baguette', quantity: '4', unit: 'slices, toasted' },
      { name: 'Gruyère cheese', quantity: '1.5', unit: 'cups, grated' },
    ],
    steps: [
      'Melt butter and cook onions on medium-low heat for 40-50 minutes until deep golden.',
      'Deglaze with white wine, scraping up fond.',
      'Add beef broth, thyme, and bay leaf. Simmer 15 minutes.',
      'Ladle soup into oven-safe bowls. Top with toasted baguette slices.',
      'Pile Gruyère cheese on top of the bread.',
      'Broil until cheese is bubbly and golden brown. Serve immediately.',
    ],
    tags: ['french', 'soup', 'onion', 'cheese', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 18,
      carbs_g: 28,
      fat_g: 20,
      fiber_g: 4,
      sugar_g: 10,
      sodium_mg: 980,
    },
  },
  {
    title: 'Quiche Lorraine',
    description:
      'Classic savory tart with a buttery crust, lardons, Gruyère, and creamy egg custard.',
    cuisine: 'French',
    prep_minutes: 20,
    cook_minutes: 40,
    servings: 8,
    calories: 340,
    ingredients: [
      { name: 'pie crust', quantity: '1', unit: '9-inch, unbaked' },
      { name: 'lardons', quantity: '6', unit: 'oz' },
      { name: 'Gruyère cheese', quantity: '1', unit: 'cup, grated' },
      { name: 'egg', quantity: '4', unit: 'large' },
      { name: 'heavy cream', quantity: '1', unit: 'cup' },
      { name: 'milk', quantity: '1/2', unit: 'cup' },
      { name: 'nutmeg', quantity: '1', unit: 'pinch' },
      { name: 'onion', quantity: '1', unit: 'small, diced' },
    ],
    steps: [
      'Blind bake the pie crust at 375°F for 15 minutes.',
      'Cook lardons and onion until golden. Drain excess fat.',
      'Spread lardons and onion in the crust. Top with grated Gruyère.',
      'Whisk eggs, cream, milk, nutmeg, salt, and pepper.',
      'Pour custard over the filling. Bake at 350°F for 35-40 minutes until set.',
      'Let rest 10 minutes before slicing. Serve warm or at room temperature.',
    ],
    tags: ['french', 'quiche', 'egg', 'cheese', 'savory-tart'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 340,
      protein_g: 16,
      carbs_g: 18,
      fat_g: 22,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 520,
    },
  },
  {
    title: 'Croque Monsieur',
    description: 'French hot sandwich with ham, Gruyère, and creamy béchamel, broiled golden.',
    cuisine: 'French',
    prep_minutes: 10,
    cook_minutes: 15,
    servings: 4,
    calories: 420,
    ingredients: [
      { name: 'bread', quantity: '8', unit: 'slices, brioche' },
      { name: 'ham', quantity: '8', unit: 'slices' },
      { name: 'Gruyère cheese', quantity: '1.5', unit: 'cups, grated' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
      { name: 'flour', quantity: '1', unit: 'tbsp' },
      { name: 'milk', quantity: '1', unit: 'cup' },
      { name: 'Dijon mustard', quantity: '2', unit: 'tsp' },
      { name: 'nutmeg', quantity: '1', unit: 'pinch' },
    ],
    steps: [
      'Make béchamel: melt butter, add flour, cook 1 minute. Whisk in milk until thick.',
      'Add half the Gruyère and nutmeg to the béchamel. Stir until melted.',
      'Spread Dijon on bread. Layer ham and cheese between slices.',
      'Top each sandwich with béchamel sauce and remaining Gruyère.',
      'Broil until cheese is golden and bubbling.',
      'Serve immediately with a green salad.',
    ],
    tags: ['french', 'sandwich', 'ham', 'cheese', 'grilled'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 22,
      carbs_g: 32,
      fat_g: 24,
      fiber_g: 2,
      sugar_g: 4,
      sodium_mg: 780,
    },
  },
  {
    title: 'Niçoise Salad',
    description:
      'Mediterranean salad with tuna, hard-boiled egg, olives, green beans, and potatoes.',
    cuisine: 'French',
    prep_minutes: 20,
    cook_minutes: 15,
    servings: 4,
    calories: 320,
    ingredients: [
      { name: 'tuna steak', quantity: '2', unit: '(6 oz each), seared' },
      { name: 'egg', quantity: '4', unit: 'hard-boiled, quartered' },
      { name: 'potato', quantity: '4', unit: 'small, boiled & halved' },
      { name: 'green beans', quantity: '1', unit: 'cup, blanched' },
      { name: 'Niçoise olives', quantity: '1/2', unit: 'cup' },
      { name: 'cherry tomato', quantity: '1', unit: 'cup, halved' },
      { name: 'anchovy', quantity: '4', unit: 'fillets' },
      { name: 'Dijon vinaigrette', quantity: '3', unit: 'tbsp' },
    ],
    steps: [
      'Boil potatoes until tender. Blanch green beans until crisp-tender.',
      'Sear tuna steaks for 1-2 minutes per side (keep rare in center).',
      'Arrange lettuce on a platter. Arrange potatoes, green beans, tomatoes, and eggs.',
      'Flake tuna over the salad. Add olives and anchovy fillets.',
      'Drizzle with Dijon vinaigrette.',
      'Serve immediately as a main course salad.',
    ],
    tags: ['french', 'salad', 'tuna', 'mediterranean', 'nicoise'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 28,
      carbs_g: 16,
      fat_g: 16,
      fiber_g: 4,
      sugar_g: 3,
      sodium_mg: 620,
    },
  },
  {
    title: 'Duck Confit',
    description: 'Slow-cooked duck legs in their own fat until impossibly tender with crispy skin.',
    cuisine: 'French',
    prep_minutes: 15,
    cook_minutes: 240,
    servings: 4,
    calories: 520,
    ingredients: [
      { name: 'duck legs', quantity: '4', unit: 'pieces' },
      { name: 'duck fat', quantity: '3', unit: 'cups' },
      { name: 'garlic', quantity: '4', unit: 'cloves' },
      { name: 'thyme', quantity: '4', unit: 'sprigs' },
      { name: 'bay leaf', quantity: '2', unit: 'leaves' },
      { name: 'salt', quantity: '1', unit: 'tbsp' },
      { name: 'black pepper', quantity: '1', unit: 'tsp' },
      { name: 'star anise', quantity: '2', unit: 'whole' },
    ],
    steps: [
      'Cure duck legs with salt, pepper, garlic, thyme, and star anise overnight in the fridge.',
      'Rinse and pat dry. Submerge in duck fat in a heavy pot.',
      'Cook at 275°F for 2.5-3 hours until meat slides off the bone.',
      'Remove from fat. Store in fat for up to a month, or use immediately.',
      'To serve, crisp skin side in a hot skillet until golden and crackling.',
      'Serve with lentils du Puy or a simple green salad.',
    ],
    tags: ['french', 'duck', 'confit', 'slow-cook', 'classic'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 520,
      protein_g: 36,
      carbs_g: 0,
      fat_g: 42,
      fiber_g: 0,
      sugar_g: 0,
      sodium_mg: 680,
    },
  },
  {
    title: 'Crêpes Suzette',
    description:
      'Thin French crêpes flambéed in a caramelized orange-butter sauce with Grand Marnier.',
    cuisine: 'French',
    prep_minutes: 20,
    cook_minutes: 15,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'flour', quantity: '1', unit: 'cup' },
      { name: 'egg', quantity: '2', unit: 'large' },
      { name: 'milk', quantity: '1', unit: 'cup' },
      { name: 'butter', quantity: '3', unit: 'tbsp' },
      { name: 'orange juice', quantity: '1/2', unit: 'cup' },
      { name: 'orange zest', quantity: '1', unit: 'tbsp' },
      { name: 'sugar', quantity: '1/4', unit: 'cup' },
      { name: 'Grand Marnier', quantity: '3', unit: 'tbsp' },
    ],
    steps: [
      'Make crêpe batter: whisk flour, eggs, milk, and a pinch of salt until smooth. Rest 30 minutes.',
      'Cook thin crêpes in a buttered non-stick pan. Stack and set aside.',
      'Make Suzette sauce: melt butter with sugar until caramelized.',
      'Add orange juice and zest. Simmer until syrupy.',
      'Fold crêpes into quarters and warm in the sauce.',
      'Add Grand Marnier and carefully flambé. Serve immediately.',
    ],
    tags: ['french', 'dessert', 'crepe', 'orange', 'flambe'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 6,
      carbs_g: 34,
      fat_g: 12,
      fiber_g: 1,
      sugar_g: 18,
      sodium_mg: 120,
    },
  },
  {
    title: 'Bouillabaisse',
    description:
      'Provençal fish stew with mixed seafood, saffron, fennel, and rouille-topped croutons.',
    cuisine: 'French',
    prep_minutes: 25,
    cook_minutes: 35,
    servings: 6,
    calories: 320,
    ingredients: [
      { name: 'mixed fish', quantity: '1.5', unit: 'lb (cod, snapper, etc.)' },
      { name: 'shrimp', quantity: '1/2', unit: 'lb' },
      { name: 'mussels', quantity: '1/2', unit: 'lb' },
      { name: 'fennel', quantity: '1', unit: 'bulb, sliced' },
      { name: 'saffron', quantity: '1', unit: 'pinch' },
      { name: 'tomato', quantity: '3', unit: 'diced' },
      { name: 'garlic', quantity: '4', unit: 'cloves' },
      { name: 'Pernod', quantity: '2', unit: 'tbsp' },
      { name: 'orange zest', quantity: '1', unit: 'strip' },
      { name: 'croutons', quantity: '6', unit: 'slices' },
    ],
    steps: [
      'Sauté fennel, onion, and garlic in olive oil until softened.',
      'Add tomatoes, saffron, Pernod, and orange zest. Cook 10 minutes.',
      'Add fish stock and bring to a simmer.',
      'Add firm fish first, then delicate fish and shrimp. Cook 8 minutes.',
      'Add mussels, cover and cook until they open, about 3 minutes.',
      'Serve in deep bowls with rouille-topped croutons on the side.',
    ],
    tags: ['french', 'stew', 'seafood', 'saffron', 'provencal'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 320,
      protein_g: 32,
      carbs_g: 14,
      fat_g: 14,
      fiber_g: 3,
      sugar_g: 4,
      sodium_mg: 720,
    },
  },
  {
    title: 'Tarte Tatin',
    description: 'Upside-down caramelized apple tart with buttery, flaky puff pastry.',
    cuisine: 'French',
    prep_minutes: 20,
    cook_minutes: 35,
    servings: 8,
    calories: 280,
    ingredients: [
      { name: 'apple', quantity: '6', unit: 'Granny Smith, quartered' },
      { name: 'butter', quantity: '4', unit: 'tbsp' },
      { name: 'sugar', quantity: '3/4', unit: 'cup' },
      { name: 'puff pastry', quantity: '1', unit: 'sheet, thawed' },
      { name: 'lemon juice', quantity: '1', unit: 'tbsp' },
      { name: 'cinnamon', quantity: '1/4', unit: 'tsp' },
    ],
    steps: [
      'Melt butter and sugar in an oven-safe skillet until golden caramel forms.',
      'Add lemon juice and cinnamon. Arrange apple quarters tightly in the caramel.',
      'Cook apples in caramel for 10-15 minutes until softened.',
      'Drape puff pastry over the apples, tucking edges inside the pan.',
      'Bake at 400°F for 25-30 minutes until pastry is golden and puffed.',
      'Let rest 5 minutes, then invert onto a serving plate. Serve with crème fraîche.',
    ],
    tags: ['french', 'dessert', 'apple', 'tart', 'caramel'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 2,
      carbs_g: 38,
      fat_g: 14,
      fiber_g: 2,
      sugar_g: 24,
      sodium_mg: 140,
    },
  },
  {
    title: 'Sole Meunière',
    description: 'Pan-fried sole in brown butter with lemon, capers, and fresh parsley.',
    cuisine: 'French',
    prep_minutes: 10,
    cook_minutes: 10,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'sole fillets', quantity: '4', unit: '(6 oz each)' },
      { name: 'butter', quantity: '4', unit: 'tbsp' },
      { name: 'lemon', quantity: '1', unit: 'juiced' },
      { name: 'capers', quantity: '2', unit: 'tbsp' },
      { name: 'flour', quantity: '1/4', unit: 'cup, for dredging' },
      { name: 'parsley', quantity: '2', unit: 'tbsp, chopped' },
      { name: 'salt', quantity: '1/2', unit: 'tsp' },
      { name: 'white pepper', quantity: '1/4', unit: 'tsp' },
    ],
    steps: [
      'Season sole fillets and dredge lightly in flour, shaking off excess.',
      'Melt 2 tablespoons butter in a large skillet over medium-high heat.',
      'Cook fillets 2-3 minutes per side until golden. Transfer to a warm plate.',
      'Add remaining butter to the pan and cook until it turns nutty brown.',
      'Add lemon juice and capers. Pour brown butter sauce over the fish.',
      'Garnish with parsley and serve immediately.',
    ],
    tags: ['french', 'fish', 'sole', 'butter', 'quick'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 28,
      carbs_g: 6,
      fat_g: 16,
      fiber_g: 0,
      sugar_g: 1,
      sodium_mg: 380,
    },
  },
  {
    title: 'French Baguette',
    description: 'Crispy-crusted, airy-crumbed French bread with a shattering exterior.',
    cuisine: 'French',
    prep_minutes: 20,
    cook_minutes: 25,
    servings: 8,
    calories: 150,
    ingredients: [
      { name: 'bread flour', quantity: '4', unit: 'cups' },
      { name: 'water', quantity: '1.5', unit: 'cups, warm' },
      { name: 'yeast', quantity: '1', unit: 'tsp' },
      { name: 'salt', quantity: '2', unit: 'tsp' },
    ],
    steps: [
      'Mix flour, yeast, and salt. Add water and mix until a shaggy dough forms.',
      'Knead for 10 minutes until smooth and elastic.',
      'Let rise for 1 hour until doubled.',
      'Divide into 3 pieces, shape into baguettes. Let rise 30 minutes on a floured towel.',
      'Score the tops with a razor blade.',
      'Bake at 450°F with steam (water in a pan below) for 20-25 minutes until golden.',
    ],
    tags: ['french', 'bread', 'baguette', 'baking', 'vegan'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 150,
      protein_g: 4,
      carbs_g: 30,
      fat_g: 1,
      fiber_g: 1,
      sugar_g: 0,
      sodium_mg: 480,
    },
  },
  {
    title: 'Potage Parmentier',
    description: 'Creamy French potato-leek soup, silky smooth and comforting.',
    cuisine: 'French',
    prep_minutes: 10,
    cook_minutes: 30,
    servings: 6,
    calories: 180,
    ingredients: [
      { name: 'leek', quantity: '3', unit: 'large, sliced' },
      { name: 'potato', quantity: '3', unit: 'medium, cubed' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
      { name: 'chicken broth', quantity: '4', unit: 'cups' },
      { name: 'heavy cream', quantity: '1/2', unit: 'cup' },
      { name: 'chives', quantity: '2', unit: 'tbsp, chopped' },
      { name: 'nutmeg', quantity: '1', unit: 'pinch' },
    ],
    steps: [
      'Sauté leeks in butter until very soft but not browned, about 8 minutes.',
      'Add potatoes and chicken broth. Bring to a boil, then simmer 20 minutes.',
      'Blend until silky smooth.',
      'Stir in cream and nutmeg. Adjust seasoning.',
      'Serve hot, garnished with chives.',
    ],
    tags: ['french', 'soup', 'potato', 'leek', 'creamy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 180,
      protein_g: 4,
      carbs_g: 22,
      fat_g: 10,
      fiber_g: 3,
      sugar_g: 3,
      sodium_mg: 420,
    },
  },
  {
    title: 'Profiteroles',
    description:
      'Light choux pastry puffs filled with vanilla ice cream and drizzled with chocolate sauce.',
    cuisine: 'French',
    prep_minutes: 20,
    cook_minutes: 25,
    servings: 6,
    calories: 300,
    ingredients: [
      { name: 'water', quantity: '1', unit: 'cup' },
      { name: 'butter', quantity: '1/2', unit: 'cup' },
      { name: 'flour', quantity: '1', unit: 'cup' },
      { name: 'egg', quantity: '4', unit: 'large' },
      { name: 'vanilla ice cream', quantity: '1', unit: 'pint' },
      { name: 'dark chocolate', quantity: '4', unit: 'oz, chopped' },
      { name: 'heavy cream', quantity: '1/4', unit: 'cup' },
      { name: 'sugar', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Bring water and butter to a boil. Add flour all at once, stir vigorously.',
      'Cook dough 2 minutes, then cool slightly. Beat in eggs one at a time.',
      'Pipe small mounds onto a baking sheet. Bake at 400°F for 20-25 minutes.',
      'Cool completely, then slice in half.',
      'Fill with vanilla ice cream.',
      'Make chocolate sauce: melt chocolate with cream and sugar. Drizzle over profiteroles.',
    ],
    tags: ['french', 'dessert', 'choux', 'chocolate', 'ice-cream'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 300,
      protein_g: 6,
      carbs_g: 28,
      fat_g: 18,
      fiber_g: 1,
      sugar_g: 14,
      sodium_mg: 180,
    },
  },
];

export const frenchRecipes = generateCuisineRecipes(configs);

// ── Additional French recipes ────────────────────────────────────────────────

const additionalFrenchConfigs: CuisineRecipeConfig[] = [
  {
    title: 'Ratatouille',
    description: 'Provençal vegetable stew with eggplant, zucchini, bell pepper, and tomato.',
    cuisine: 'French',
    prep_minutes: 25,
    cook_minutes: 45,
    servings: 6,
    calories: 160,
    ingredients: [
      { name: 'eggplant', quantity: '1', unit: 'cubed' },
      { name: 'zucchini', quantity: '2', unit: 'sliced' },
      { name: 'bell pepper', quantity: '2', unit: 'diced' },
      { name: 'tomato', quantity: '4', unit: 'diced' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'garlic', quantity: '4', unit: 'cloves' },
      { name: 'olive oil', quantity: '3', unit: 'tbsp' },
      { name: 'herbes de Provence', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Sauté eggplant in olive oil until golden. Set aside.',
      'Sauté onion, bell pepper, and zucchini.',
      'Add tomato, garlic, and herbes de Provence.',
      'Return eggplant. Simmer 30 minutes.',
      'Season with salt and pepper.',
      'Serve as a side or main with crusty bread.',
    ],
    tags: ['french', 'vegetables', 'provencal', 'vegan', 'stew'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 160,
      protein_g: 4,
      carbs_g: 18,
      fat_g: 8,
      fiber_g: 5,
      sugar_g: 8,
      sodium_mg: 280,
    },
  },
  {
    title: 'French Onion Soup',
    description: 'Caramelized onion soup in beef broth, topped with a crouton and melted Gruyère.',
    cuisine: 'French',
    prep_minutes: 10,
    cook_minutes: 60,
    servings: 4,
    calories: 380,
    ingredients: [
      { name: 'onion', quantity: '6', unit: 'large, sliced' },
      { name: 'butter', quantity: '3', unit: 'tbsp' },
      { name: 'beef broth', quantity: '6', unit: 'cups' },
      { name: 'white wine', quantity: '1/2', unit: 'cup' },
      { name: 'baguette', quantity: '4', unit: 'slices, toasted' },
      { name: 'Gruyère cheese', quantity: '2', unit: 'cups, shredded' },
      { name: 'thyme', quantity: '2', unit: 'sprigs' },
    ],
    steps: [
      'Caramelize onions in butter over medium-low heat for 40 minutes.',
      'Add wine and deglaze. Add beef broth and thyme.',
      'Simmer 15 minutes.',
      'Ladle into oven-safe bowls.',
      'Top with toasted baguette and Gruyère.',
      'Broil until cheese is bubbly and golden.',
    ],
    tags: ['french', 'soup', 'onion', 'cheese', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 18,
      carbs_g: 28,
      fat_g: 20,
      fiber_g: 3,
      sugar_g: 8,
      sodium_mg: 860,
    },
  },
  {
    title: 'Coq au Vin',
    description: 'Chicken braised in red wine with mushrooms, lardons, and pearl onions.',
    cuisine: 'French',
    prep_minutes: 20,
    cook_minutes: 90,
    servings: 6,
    calories: 380,
    ingredients: [
      { name: 'chicken', quantity: '1', unit: 'whole, cut up' },
      { name: 'red wine', quantity: '2', unit: 'cups' },
      { name: 'bacon lardons', quantity: '4', unit: 'oz' },
      { name: 'mushroom', quantity: '8', unit: 'oz, quartered' },
      { name: 'pearl onion', quantity: '1', unit: 'cup, peeled' },
      { name: 'carrot', quantity: '2', unit: 'sliced' },
      { name: 'garlic', quantity: '3', unit: 'cloves' },
      { name: 'thyme', quantity: '3', unit: 'sprigs' },
    ],
    steps: [
      'Brown lardons. Brown chicken pieces in the fat.',
      'Sauté carrot, mushroom, and pearl onion.',
      'Add wine, broth, garlic, and thyme.',
      'Return chicken. Simmer covered 1.5 hours.',
      'Remove lid, reduce sauce slightly.',
      'Serve with mashed potatoes or crusty bread.',
    ],
    tags: ['french', 'chicken', 'wine', 'braised', 'classic'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 380,
      protein_g: 32,
      carbs_g: 10,
      fat_g: 18,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 580,
    },
  },
  {
    title: 'Quiche Lorraine',
    description: 'Classic French quiche with bacon, Gruyère, and a silky egg-cream custard.',
    cuisine: 'French',
    prep_minutes: 15,
    cook_minutes: 40,
    servings: 8,
    calories: 340,
    ingredients: [
      { name: 'pie crust', quantity: '1', unit: '9-inch' },
      { name: 'bacon', quantity: '6', unit: 'slices, diced' },
      { name: 'egg', quantity: '4', unit: 'large' },
      { name: 'heavy cream', quantity: '1', unit: 'cup' },
      { name: 'Gruyère', quantity: '1', unit: 'cup, grated' },
      { name: 'nutmeg', quantity: '1', unit: 'pinch' },
    ],
    steps: [
      'Blind-bake the crust for 10 minutes.',
      'Sauté bacon until crispy.',
      'Whisk eggs, cream, nutmeg, salt, and pepper.',
      'Spread bacon and cheese in the crust.',
      'Pour custard over.',
      'Bake at 350°F for 35 minutes until just set.',
    ],
    tags: ['french', 'quiche', 'bacon', 'cheese', 'brunch'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 340,
      protein_g: 14,
      carbs_g: 18,
      fat_g: 22,
      fiber_g: 0,
      sugar_g: 2,
      sodium_mg: 580,
    },
  },
  {
    title: 'Crème Brûlée',
    description: 'Silky vanilla custard with a crisp caramelized sugar top.',
    cuisine: 'French',
    prep_minutes: 10,
    cook_minutes: 40,
    servings: 6,
    calories: 280,
    ingredients: [
      { name: 'heavy cream', quantity: '2', unit: 'cups' },
      { name: 'egg yolk', quantity: '5', unit: 'large' },
      { name: 'sugar', quantity: '1/2', unit: 'cup' },
      { name: 'vanilla bean', quantity: '1', unit: 'split' },
      { name: 'superfine sugar', quantity: '6', unit: 'tsp, for topping' },
    ],
    steps: [
      'Heat cream with vanilla bean until simmering.',
      'Whisk egg yolks and sugar. Temper in hot cream.',
      'Strain into ramekins.',
      'Bake in a water bath at 325°F for 40 minutes.',
      'Chill 4 hours.',
      'Sprinkle sugar on top, torch until caramelized.',
    ],
    tags: ['french', 'dessert', 'custard', 'caramelized', 'classic'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 4,
      carbs_g: 24,
      fat_g: 18,
      fiber_g: 0,
      sugar_g: 20,
      sodium_mg: 40,
    },
  },
  {
    title: 'Bouillabaisse',
    description:
      'Marseille fish stew with mixed seafood, saffron, and a spicy rouille on crusty bread.',
    cuisine: 'French',
    prep_minutes: 20,
    cook_minutes: 30,
    servings: 6,
    calories: 320,
    ingredients: [
      { name: 'mixed fish and seafood', quantity: '2', unit: 'lb' },
      { name: 'fennel', quantity: '1', unit: 'sliced' },
      { name: 'tomato', quantity: '3', unit: 'diced' },
      { name: 'saffron', quantity: '1', unit: 'pinch' },
      { name: 'Pernod', quantity: '2', unit: 'tbsp' },
      { name: 'garlic', quantity: '4', unit: 'cloves' },
      { name: 'fish stock', quantity: '4', unit: 'cups' },
      { name: 'rouille', quantity: '1/2', unit: 'cup' },
    ],
    steps: [
      'Sauté fennel, onion, and garlic.',
      'Add tomato, saffron, Pernod, and fish stock. Simmer 15 minutes.',
      'Add firm fish first, then delicate seafood.',
      'Cook 10 minutes until seafood is just done.',
      'Serve in bowls with rouille on crusty bread.',
      'The broth should be rich and saffron-gold.',
    ],
    tags: ['french', 'stew', 'seafood', 'saffron', 'marseille'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 320,
      protein_g: 32,
      carbs_g: 10,
      fat_g: 14,
      fiber_g: 2,
      sugar_g: 4,
      sodium_mg: 680,
    },
  },
  {
    title: 'Sole Meunière',
    description: 'Pan-fried sole in brown butter with lemon, capers, and parsley.',
    cuisine: 'French',
    prep_minutes: 10,
    cook_minutes: 8,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'sole fillet', quantity: '4', unit: 'pieces' },
      { name: 'butter', quantity: '4', unit: 'tbsp' },
      { name: 'lemon', quantity: '1', unit: 'juiced' },
      { name: 'capers', quantity: '1', unit: 'tbsp' },
      { name: 'parsley', quantity: '2', unit: 'tbsp, chopped' },
      { name: 'flour', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Dredge sole in flour, shake off excess.',
      'Pan-fry in butter until golden, about 3 minutes per side.',
      'Add more butter and cook until nutty brown.',
      'Squeeze lemon, add capers.',
      'Pour brown butter sauce over fish.',
      'Garnish with parsley and serve.',
    ],
    tags: ['french', 'fish', 'butter', 'lemon', 'classic'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 24,
      carbs_g: 8,
      fat_g: 16,
      fiber_g: 0,
      sugar_g: 1,
      sodium_mg: 380,
    },
  },
  {
    title: 'Tarte Tatin',
    description: 'Upside-down caramelized apple tart — buttery, sticky, and delicious.',
    cuisine: 'French',
    prep_minutes: 15,
    cook_minutes: 30,
    servings: 8,
    calories: 280,
    ingredients: [
      { name: 'apple', quantity: '6', unit: 'peeled, quartered' },
      { name: 'sugar', quantity: '1', unit: 'cup' },
      { name: 'butter', quantity: '4', unit: 'tbsp' },
      { name: 'puff pastry', quantity: '1', unit: 'sheet' },
      { name: 'cinnamon', quantity: '1/4', unit: 'tsp' },
    ],
    steps: [
      'Melt sugar in a cast iron pan until deep amber.',
      'Add butter. Arrange apples in a tight circle.',
      'Cook 15 minutes until apples are caramelized.',
      'Cover with puff pastry, tuck edges in.',
      'Bake at 400°F for 25 minutes until pastry is golden.',
      'Invert onto a plate. Serve warm with crème fraîche.',
    ],
    tags: ['french', 'tart', 'apple', 'caramelized', 'dessert'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 2,
      carbs_g: 38,
      fat_g: 14,
      fiber_g: 2,
      sugar_g: 24,
      sodium_mg: 160,
    },
  },
  {
    title: 'Duck Confit',
    description:
      'Slowly cooked duck legs in their own fat until meltingly tender, with crispy skin.',
    cuisine: 'French',
    prep_minutes: 10,
    cook_minutes: 240,
    servings: 4,
    calories: 480,
    ingredients: [
      { name: 'duck legs', quantity: '4', unit: 'pieces' },
      { name: 'duck fat', quantity: '2', unit: 'cups' },
      { name: 'garlic', quantity: '4', unit: 'cloves' },
      { name: 'thyme', quantity: '4', unit: 'sprigs' },
      { name: 'salt', quantity: '1', unit: 'tbsp' },
      { name: 'bay leaf', quantity: '2', unit: 'leaves' },
    ],
    steps: [
      'Cure duck legs with salt, garlic, thyme, and bay leaf for 24 hours.',
      'Rinse and submerge in duck fat.',
      'Cook at 275°F for 3-4 hours until meat falls off the bone.',
      'Cool in the fat.',
      'To serve, crisp the skin in a hot pan.',
      'Serve with lentils or potatoes.',
    ],
    tags: ['french', 'duck', 'confit', 'classic', 'rich'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 480,
      protein_g: 32,
      carbs_g: 0,
      fat_g: 38,
      fiber_g: 0,
      sugar_g: 0,
      sodium_mg: 680,
    },
  },
  {
    title: 'Profiteroles',
    description:
      'Choux pastry puffs filled with vanilla ice cream and drizzled with chocolate sauce.',
    cuisine: 'French',
    prep_minutes: 15,
    cook_minutes: 25,
    servings: 8,
    calories: 260,
    ingredients: [
      { name: 'water', quantity: '1', unit: 'cup' },
      { name: 'butter', quantity: '1/2', unit: 'cup' },
      { name: 'flour', quantity: '1', unit: 'cup' },
      { name: 'egg', quantity: '4', unit: 'large' },
      { name: 'vanilla ice cream', quantity: '1', unit: 'pint' },
      { name: 'dark chocolate', quantity: '4', unit: 'oz, melted' },
    ],
    steps: [
      'Bring water and butter to a boil. Add flour all at once.',
      'Stir vigorously until dough forms a ball. Cool slightly.',
      'Beat in eggs one at a time.',
      'Pipe small mounds onto a baking sheet.',
      'Bake at 400°F for 25 minutes until puffed and golden.',
      'Split, fill with ice cream, drizzle with chocolate.',
    ],
    tags: ['french', 'dessert', 'choux', 'chocolate', 'ice-cream'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 260,
      protein_g: 6,
      carbs_g: 28,
      fat_g: 14,
      fiber_g: 1,
      sugar_g: 12,
      sodium_mg: 160,
    },
  },
];

export const frenchAdditionalRecipes = generateCuisineRecipes(additionalFrenchConfigs);
