import type { CuisineRecipeConfig } from './types';
import { generateCuisineRecipes } from './types';

const configs: CuisineRecipeConfig[] = [
  {
    title: 'Sauerbraten',
    description:
      'German pot roast marinated in vinegar and spices, slow-braised until fork-tender.',
    cuisine: 'German',
    prep_minutes: 15,
    cook_minutes: 180,
    servings: 8,
    calories: 420,
    ingredients: [
      { name: 'beef bottom round', quantity: '3', unit: 'lb' },
      { name: 'red wine vinegar', quantity: '2', unit: 'cups' },
      { name: 'onion', quantity: '2', unit: 'sliced' },
      { name: 'bay leaf', quantity: '3', unit: 'leaves' },
      { name: 'juniper berries', quantity: '6', unit: 'whole' },
      { name: 'gingersnap cookies', quantity: '8', unit: 'crushed' },
      { name: 'raisins', quantity: '1/4', unit: 'cup' },
      { name: 'cloves', quantity: '3', unit: 'whole' },
    ],
    steps: [
      'Marinate beef in vinegar, onion, bay leaf, juniper, and cloves for 3-5 days.',
      'Remove beef, pat dry, and brown on all sides in a Dutch oven.',
      'Strain marinade, add to pot with beef. Cover and braise at 325°F for 2.5-3 hours.',
      'Remove beef. Thicken sauce with crushed gingersnaps and raisins.',
      'Simmer sauce until glossy and thickened.',
      'Slice beef and serve with sauce, red cabbage, and potato dumplings.',
    ],
    tags: ['german', 'beef', 'braised', 'marinated', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 40,
      carbs_g: 12,
      fat_g: 24,
      fiber_g: 1,
      sugar_g: 6,
      sodium_mg: 620,
    },
  },
  {
    title: 'Bratwurst',
    description: 'Juicy German pork sausage grilled and served with sauerkraut and mustard.',
    cuisine: 'German',
    prep_minutes: 5,
    cook_minutes: 15,
    servings: 4,
    calories: 380,
    ingredients: [
      { name: 'bratwurst', quantity: '8', unit: 'links' },
      { name: 'sauerkraut', quantity: '2', unit: 'cups' },
      { name: 'onion', quantity: '1', unit: 'sliced' },
      { name: 'beer', quantity: '1/2', unit: 'cup' },
      { name: 'mustard', quantity: '2', unit: 'tbsp' },
      { name: 'bratwurst buns', quantity: '8', unit: 'pieces' },
      { name: 'butter', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Simmer bratwurst in beer with onion for 10 minutes.',
      'Grill bratwurst over medium-high heat until charred on all sides.',
      'Warm sauerkraut in a pan with butter.',
      'Place bratwurst in buns.',
      'Top with sauerkraut and mustard.',
      'Serve with potato salad.',
    ],
    tags: ['german', 'sausage', 'grilled', 'pork', 'beer'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 18,
      carbs_g: 16,
      fat_g: 26,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 980,
    },
  },
  {
    title: 'Schnitzel',
    description: 'Crispy breaded and pan-fried pork cutlet served with lemon and potato salad.',
    cuisine: 'German',
    prep_minutes: 15,
    cook_minutes: 10,
    servings: 4,
    calories: 420,
    ingredients: [
      { name: 'pork loin', quantity: '4', unit: 'cutlets, pounded thin' },
      { name: 'flour', quantity: '1/2', unit: 'cup' },
      { name: 'egg', quantity: '2', unit: 'beaten' },
      { name: 'breadcrumbs', quantity: '1', unit: 'cup' },
      { name: 'butter', quantity: '4', unit: 'tbsp' },
      { name: 'lemon', quantity: '1', unit: 'quartered' },
      { name: 'capers', quantity: '1', unit: 'tbsp' },
      { name: 'parsley', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Pound pork cutlets between plastic wrap until 1/4 inch thin.',
      'Season with salt and pepper.',
      'Dredge in flour, dip in egg, coat in breadcrumbs.',
      'Pan-fry in butter and oil until golden on both sides, about 3 minutes per side.',
      'Serve with lemon wedges, capers, and parsley.',
      'Traditionally served with potato salad or spaetzle.',
    ],
    tags: ['german', 'pork', 'fried', 'breaded', 'classic'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 32,
      carbs_g: 18,
      fat_g: 24,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 520,
    },
  },
  {
    title: 'Pretzel',
    description: 'Soft, chewy German pretzel with a shiny lye-bathed crust and coarse salt.',
    cuisine: 'German',
    prep_minutes: 20,
    cook_minutes: 15,
    servings: 8,
    calories: 180,
    ingredients: [
      { name: 'flour', quantity: '3.5', unit: 'cups' },
      { name: 'yeast', quantity: '1', unit: 'packet' },
      { name: 'warm water', quantity: '1.25', unit: 'cups' },
      { name: 'baking soda', quantity: '1/2', unit: 'cup (for bath)' },
      { name: 'sugar', quantity: '1', unit: 'tbsp' },
      { name: 'butter', quantity: '2', unit: 'tbsp, melted' },
      { name: 'coarse salt', quantity: '2', unit: 'tsp' },
    ],
    steps: [
      'Mix flour, yeast, sugar, salt, water, and butter. Knead 5 minutes.',
      'Let rise 1 hour until doubled.',
      'Divide into 8 pieces, roll into long ropes, shape into pretzels.',
      'Dip each in a baking soda water bath for 30 seconds.',
      'Place on a baking sheet, sprinkle with coarse salt.',
      'Bake at 450°F for 12-15 minutes until deep brown. Serve with mustard.',
    ],
    tags: ['german', 'bread', 'pretzel', 'baking', 'snack'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 180,
      protein_g: 4,
      carbs_g: 34,
      fat_g: 3,
      fiber_g: 1,
      sugar_g: 1,
      sodium_mg: 880,
    },
  },
  {
    title: 'Spätzle',
    description: 'Soft German egg noodles tossed with butter and served as a side or with cheese.',
    cuisine: 'German',
    prep_minutes: 10,
    cook_minutes: 10,
    servings: 4,
    calories: 220,
    ingredients: [
      { name: 'flour', quantity: '2', unit: 'cups' },
      { name: 'egg', quantity: '3', unit: 'large' },
      { name: 'milk', quantity: '1/4', unit: 'cup' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
      { name: 'nutmeg', quantity: '1', unit: 'pinch' },
      { name: 'parsley', quantity: '1', unit: 'tbsp' },
      { name: 'emmental cheese', quantity: '1/2', unit: 'cup, grated' },
    ],
    steps: [
      'Mix flour, eggs, milk, nutmeg, and salt into a thick batter.',
      'Push batter through a spaetzle maker or colander into boiling salted water.',
      'Cook until noodles float, about 2-3 minutes. Drain.',
      'Toss with melted butter and emmental cheese.',
      'Garnish with parsley.',
      'Serve as a side with schnitzel or stews.',
    ],
    tags: ['german', 'noodles', 'egg', 'butter', 'side-dish'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 220,
      protein_g: 10,
      carbs_g: 28,
      fat_g: 8,
      fiber_g: 1,
      sugar_g: 1,
      sodium_mg: 280,
    },
  },
  {
    title: 'Kartoffelpuffer',
    description: 'Crispy German potato pancakes served with applesauce or sour cream.',
    cuisine: 'German',
    prep_minutes: 15,
    cook_minutes: 10,
    servings: 6,
    calories: 180,
    ingredients: [
      { name: 'potato', quantity: '4', unit: 'medium, grated' },
      { name: 'onion', quantity: '1', unit: 'grated' },
      { name: 'egg', quantity: '2', unit: 'large' },
      { name: 'flour', quantity: '2', unit: 'tbsp' },
      { name: 'oil', quantity: '1/4', unit: 'cup, for frying' },
      { name: 'applesauce', quantity: '1/2', unit: 'cup' },
      { name: 'sour cream', quantity: '1/2', unit: 'cup' },
    ],
    steps: [
      'Grate potatoes and onion. Squeeze out as much liquid as possible.',
      'Mix with egg, flour, salt, and pepper.',
      'Heat oil in a large skillet over medium-high heat.',
      'Drop spoonfuls of mixture and flatten into pancakes.',
      'Fry until golden on both sides, about 3-4 minutes per side.',
      'Drain on paper towels. Serve with applesauce or sour cream.',
    ],
    tags: ['german', 'potato', 'pancake', 'fried', 'vegetarian'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 180,
      protein_g: 4,
      carbs_g: 22,
      fat_g: 8,
      fiber_g: 2,
      sugar_g: 2,
      sodium_mg: 280,
    },
  },
  {
    title: 'Käsespätzle',
    description:
      'German mac and cheese — spaetzle baked with Emmental and topped with crispy onions.',
    cuisine: 'German',
    prep_minutes: 15,
    cook_minutes: 20,
    servings: 4,
    calories: 380,
    ingredients: [
      { name: 'spätzle dough', quantity: '1', unit: 'batch' },
      { name: 'emmental cheese', quantity: '2', unit: 'cups, grated' },
      { name: 'onion', quantity: '2', unit: 'sliced' },
      { name: 'butter', quantity: '3', unit: 'tbsp' },
      { name: 'cream', quantity: '1/4', unit: 'cup' },
      { name: 'parsley', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Make spaetzle and cook until floating. Drain.',
      'Caramelize onions in butter until deep golden and crispy.',
      'Layer spaetzle and grated Emmental in a baking dish.',
      'Pour cream over, top with remaining cheese.',
      'Bake at 375°F for 15 minutes until bubbly.',
      'Top with crispy onions and parsley. Serve immediately.',
    ],
    tags: ['german', 'cheese', 'spaetzle', 'vegetarian', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 16,
      carbs_g: 32,
      fat_g: 20,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 480,
    },
  },
  {
    title: 'Red Cabbage',
    description: 'Sweet and sour braised red cabbage with apples, vinegar, and warm spices.',
    cuisine: 'German',
    prep_minutes: 15,
    cook_minutes: 45,
    servings: 6,
    calories: 120,
    ingredients: [
      { name: 'red cabbage', quantity: '1', unit: 'head, shredded' },
      { name: 'apple', quantity: '2', unit: 'diced' },
      { name: 'red wine vinegar', quantity: '1/4', unit: 'cup' },
      { name: 'sugar', quantity: '2', unit: 'tbsp' },
      { name: 'butter', quantity: '1', unit: 'tbsp' },
      { name: 'cinnamon stick', quantity: '1', unit: 'small' },
      { name: 'clove', quantity: '2', unit: 'whole' },
      { name: 'onion', quantity: '1', unit: 'sliced' },
    ],
    steps: [
      'Sauté onion in butter until soft.',
      'Add shredded cabbage and diced apples.',
      'Add vinegar, sugar, cinnamon, and cloves.',
      'Cover and braise on low heat for 40-45 minutes, stirring occasionally.',
      'Remove cinnamon stick and cloves.',
      'Adjust seasoning and serve as a side dish.',
    ],
    tags: ['german', 'vegetarian', 'cabbage', 'side-dish', 'braised'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 120,
      protein_g: 2,
      carbs_g: 20,
      fat_g: 4,
      fiber_g: 4,
      sugar_g: 12,
      sodium_mg: 180,
    },
  },
  {
    title: 'Black Forest Cake',
    description: 'Chocolate sponge layered with whipped cream, cherries, and kirsch liqueur.',
    cuisine: 'German',
    prep_minutes: 30,
    cook_minutes: 30,
    servings: 12,
    calories: 340,
    ingredients: [
      { name: 'chocolate cake layers', quantity: '3', unit: '8-inch rounds' },
      { name: 'heavy cream', quantity: '2', unit: 'cups, whipped' },
      { name: 'cherry pie filling', quantity: '1', unit: 'can (21 oz)' },
      { name: 'kirsch', quantity: '3', unit: 'tbsp' },
      { name: 'chocolate shavings', quantity: '1/2', unit: 'cup' },
      { name: 'sugar', quantity: '1/4', unit: 'cup' },
      { name: 'vanilla extract', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Brush each cake layer with kirsch.',
      'Whip cream with sugar and vanilla until stiff.',
      'Layer: cake, whipped cream, cherry filling. Repeat.',
      'Frost outside with whipped cream.',
      'Cover sides with chocolate shavings.',
      'Pipe rosettes on top and place cherries. Chill 2 hours before serving.',
    ],
    tags: ['german', 'dessert', 'cake', 'chocolate', 'cherry'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 340,
      protein_g: 4,
      carbs_g: 40,
      fat_g: 18,
      fiber_g: 2,
      sugar_g: 28,
      sodium_mg: 180,
    },
  },
  {
    title: 'Apfelstrudel',
    description: 'Thin, flaky pastry filled with cinnamon apples, raisins, and breadcrumbs.',
    cuisine: 'German',
    prep_minutes: 30,
    cook_minutes: 35,
    servings: 8,
    calories: 260,
    ingredients: [
      { name: 'strudel dough', quantity: '1', unit: 'sheet' },
      { name: 'apple', quantity: '6', unit: 'Granny Smith, sliced' },
      { name: 'sugar', quantity: '1/2', unit: 'cup' },
      { name: 'cinnamon', quantity: '1', unit: 'tbsp' },
      { name: 'raisins', quantity: '1/4', unit: 'cup' },
      { name: 'breadcrumbs', quantity: '1/2', unit: 'cup, toasted in butter' },
      { name: 'butter', quantity: '3', unit: 'tbsp, melted' },
      { name: 'vanilla sauce', quantity: '1', unit: 'cup' },
    ],
    steps: [
      'Toss apples with sugar, cinnamon, and raisins.',
      'Spread butter-toasted breadcrumbs on stretched dough.',
      'Pile apple filling on top. Roll up carefully, tucking ends.',
      'Place seam-side down on a baking sheet. Brush with melted butter.',
      'Bake at 375°F for 35 minutes until golden and crispy.',
      'Dust with powdered sugar and serve with warm vanilla sauce.',
    ],
    tags: ['german', 'dessert', 'apple', 'strudel', 'pastry'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 260,
      protein_g: 3,
      carbs_g: 38,
      fat_g: 12,
      fiber_g: 2,
      sugar_g: 20,
      sodium_mg: 160,
    },
  },
  {
    title: 'Kartoffelsalat',
    description: 'Warm German potato salad with bacon, vinegar, and fresh herbs.',
    cuisine: 'German',
    prep_minutes: 15,
    cook_minutes: 20,
    servings: 6,
    calories: 220,
    ingredients: [
      { name: 'potato', quantity: '3', unit: 'lb, boiled & sliced' },
      { name: 'bacon', quantity: '6', unit: 'slices, diced' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'vinegar', quantity: '1/4', unit: 'cup' },
      { name: 'mustard', quantity: '1', unit: 'tbsp' },
      { name: 'sugar', quantity: '1', unit: 'tsp' },
      { name: 'chives', quantity: '2', unit: 'tbsp' },
      { name: 'bacon drippings', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Boil potatoes until tender. Slice while still warm.',
      'Fry bacon until crispy. Reserve drippings.',
      'Sauté onion in bacon drippings until soft.',
      'Add vinegar, mustard, and sugar to the pan. Bring to a boil.',
      'Pour warm dressing over sliced potatoes. Toss gently.',
      'Top with crispy bacon and chives. Serve warm.',
    ],
    tags: ['german', 'potato-salad', 'bacon', 'side-dish', 'warm'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 220,
      protein_g: 8,
      carbs_g: 28,
      fat_g: 10,
      fiber_g: 3,
      sugar_g: 3,
      sodium_mg: 520,
    },
  },
  {
    title: 'Rouladen',
    description: 'Beef rolls stuffed with bacon, pickles, and mustard, braised in a rich gravy.',
    cuisine: 'German',
    prep_minutes: 25,
    cook_minutes: 90,
    servings: 6,
    calories: 380,
    ingredients: [
      { name: 'beef round', quantity: '6', unit: 'slices, thin' },
      { name: 'bacon', quantity: '6', unit: 'slices' },
      { name: 'dill pickle', quantity: '3', unit: 'whole, halved lengthwise' },
      { name: 'mustard', quantity: '3', unit: 'tbsp' },
      { name: 'onion', quantity: '2', unit: 'sliced' },
      { name: 'beef broth', quantity: '2', unit: 'cups' },
      { name: 'toothpicks', quantity: '12', unit: 'pieces' },
    ],
    steps: [
      'Spread mustard on each beef slice. Lay bacon and pickle halves on top.',
      'Roll up tightly and secure with toothpicks.',
      'Brown rouladen on all sides in a Dutch oven.',
      'Add onion and beef broth. Cover and braise at 325°F for 1.5 hours.',
      'Remove rouladen. Thicken sauce with a cornstarch slurry.',
      'Serve with red cabbage and potato dumplings.',
    ],
    tags: ['german', 'beef', 'rolled', 'braised', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 34,
      carbs_g: 6,
      fat_g: 24,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 780,
    },
  },
  {
    title: 'Currywurst',
    description: 'Sliced fried sausage smothered in curry ketchup, a beloved Berlin street food.',
    cuisine: 'German',
    prep_minutes: 5,
    cook_minutes: 10,
    servings: 4,
    calories: 320,
    ingredients: [
      { name: 'bratwurst', quantity: '4', unit: 'links' },
      { name: 'curry ketchup', quantity: '1/2', unit: 'cup' },
      { name: 'curry powder', quantity: '1', unit: 'tsp' },
      { name: 'fries', quantity: '1', unit: 'lb' },
      { name: 'onion', quantity: '1/2', unit: 'small, diced' },
    ],
    steps: [
      'Pan-fry or grill bratwurst until golden and cooked through.',
      'Slice sausages into bite-size rounds.',
      'Mix ketchup with curry powder and diced onion.',
      'Pour curry sauce over the sliced sausage.',
      'Sprinkle with extra curry powder.',
      'Serve with fries on the side.',
    ],
    tags: ['german', 'sausage', 'street-food', 'curry', 'quick'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 14,
      carbs_g: 24,
      fat_g: 18,
      fiber_g: 2,
      sugar_g: 8,
      sodium_mg: 820,
    },
  },
  {
    title: 'Stollen',
    description: 'German Christmas fruit bread with marzipan, dried fruit, and powdered sugar.',
    cuisine: 'German',
    prep_minutes: 30,
    cook_minutes: 50,
    servings: 12,
    calories: 280,
    ingredients: [
      { name: 'flour', quantity: '4', unit: 'cups' },
      { name: 'marzipan', quantity: '8', unit: 'oz, rolled' },
      { name: 'raisins', quantity: '1', unit: 'cup' },
      { name: 'candied citrus peel', quantity: '1/2', unit: 'cup' },
      { name: 'butter', quantity: '1', unit: 'cup' },
      { name: 'almonds', quantity: '1/2', unit: 'cup, slivered' },
      { name: 'rum', quantity: '2', unit: 'tbsp' },
      { name: 'powdered sugar', quantity: '1/2', unit: 'cup' },
    ],
    steps: [
      'Soak raisins and candied peel in rum overnight.',
      'Make a rich yeast dough with butter, eggs, and flour.',
      'Knead in the soaked fruits and almonds.',
      'Roll marzipan into a log, place in the center of the dough, fold over.',
      'Bake at 350°F for 45-50 minutes until golden.',
      'Brush with melted butter and dust heavily with powdered sugar.',
    ],
    tags: ['german', 'bread', 'christmas', 'fruit', 'marzipan'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 4,
      carbs_g: 34,
      fat_g: 14,
      fiber_g: 2,
      sugar_g: 14,
      sodium_mg: 140,
    },
  },
];

export const germanRecipes = generateCuisineRecipes(configs);
