import type { CuisineRecipeConfig } from './types';
import { generateCuisineRecipes } from './types';

const configs: CuisineRecipeConfig[] = [
  {
    title: 'Moussaka',
    description: 'Layered eggplant and lamb casserole with béchamel sauce, baked golden.',
    cuisine: 'Greek',
    prep_minutes: 40,
    cook_minutes: 60,
    servings: 8,
    calories: 420,
    ingredients: [
      { name: 'eggplant', quantity: '3', unit: 'large, sliced' },
      { name: 'ground lamb', quantity: '1.5', unit: 'lbs' },
      { name: 'onion', quantity: '1', unit: 'large, diced' },
      { name: 'tomato sauce', quantity: '2', unit: 'cups' },
      { name: 'cinnamon', quantity: '1/2', unit: 'tsp' },
      { name: 'butter', quantity: '3', unit: 'tbsp' },
      { name: 'flour', quantity: '3', unit: 'tbsp' },
      { name: 'milk', quantity: '2', unit: 'cups' },
    ],
    steps: [
      'Slice and salt eggplant. Let sweat 20 minutes, then brush with olive oil and roast at 400°F for 20 minutes.',
      'Cook lamb with onion, garlic, cinnamon, and tomato sauce. Simmer 15 minutes.',
      'Make béchamel: melt butter, add flour, whisk in milk until thick. Add nutmeg and egg.',
      'Layer eggplant, meat sauce, repeat. Top with béchamel and bake at 375°F for 45 minutes.',
    ],
    tags: ['moussaka', 'greek', 'eggplant', 'lamb', 'casserole'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 22,
      carbs_g: 24,
      fat_g: 26,
      fiber_g: 5,
      sugar_g: 8,
      sodium_mg: 580,
    },
  },
  {
    title: 'Spanakopita',
    description: 'Crispy phyllo pie filled with spinach, feta, and herbs.',
    cuisine: 'Greek',
    prep_minutes: 30,
    cook_minutes: 40,
    servings: 8,
    calories: 280,
    ingredients: [
      { name: 'spinach', quantity: '2', unit: 'lbs, chopped' },
      { name: 'feta cheese', quantity: '1', unit: 'cup, crumbled' },
      { name: 'phyllo dough', quantity: '1', unit: 'package' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'dill', quantity: '2', unit: 'tbsp, chopped' },
      { name: 'eggs', quantity: '3', unit: 'large' },
      { name: 'olive oil', quantity: '1/4', unit: 'cup' },
      { name: 'nutmeg', quantity: '1/4', unit: 'tsp' },
    ],
    steps: [
      'Sauté onion, add spinach and cook until wilted. Drain well and cool.',
      'Mix spinach with feta, dill, eggs, and nutmeg.',
      'Layer phyllo sheets in a baking dish, brushing each with olive oil. Add filling, top with more phyllo.',
      'Score the top and bake at 375°F for 35-40 minutes until golden and crispy.',
    ],
    tags: ['spanakopita', 'greek', 'spinach', 'feta', 'phyllo'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 12,
      carbs_g: 20,
      fat_g: 18,
      fiber_g: 3,
      sugar_g: 3,
      sodium_mg: 480,
    },
  },
  {
    title: 'Souvlaki',
    description: 'Greek marinated pork skewers grilled and served with pita, tomato, and tzatziki.',
    cuisine: 'Greek',
    prep_minutes: 20,
    cook_minutes: 12,
    servings: 4,
    calories: 380,
    ingredients: [
      { name: 'pork shoulder', quantity: '1.5', unit: 'lbs, cubed' },
      { name: 'olive oil', quantity: '1/4', unit: 'cup' },
      { name: 'lemon juice', quantity: '3', unit: 'tbsp' },
      { name: 'oregano', quantity: '1', unit: 'tbsp' },
      { name: 'garlic', quantity: '3', unit: 'cloves, minced' },
      { name: 'pita bread', quantity: '4', unit: 'pieces' },
      { name: 'tomato', quantity: '1', unit: 'sliced' },
      { name: 'tzatziki', quantity: '1/2', unit: 'cup' },
    ],
    steps: [
      'Marinate pork in olive oil, lemon juice, oregano, and garlic for at least 2 hours.',
      'Thread pork onto skewers and grill over high heat 4-5 minutes per side.',
      'Warm pita bread on the grill.',
      'Serve souvlaki in pita with tomato, onion, and tzatziki.',
    ],
    tags: ['souvlaki', 'greek', 'pork', 'skewer', 'grilled'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 32,
      carbs_g: 22,
      fat_g: 18,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 480,
    },
  },
  {
    title: 'Tzatziki',
    description: 'Cool Greek yogurt dip with cucumber, garlic, dill, and olive oil.',
    cuisine: 'Greek',
    prep_minutes: 15,
    cook_minutes: 0,
    servings: 8,
    calories: 80,
    ingredients: [
      { name: 'Greek yogurt', quantity: '2', unit: 'cups' },
      { name: 'cucumber', quantity: '1', unit: 'medium, grated' },
      { name: 'garlic', quantity: '2', unit: 'cloves, minced' },
      { name: 'dill', quantity: '2', unit: 'tbsp, chopped' },
      { name: 'olive oil', quantity: '1', unit: 'tbsp' },
      { name: 'lemon juice', quantity: '1', unit: 'tbsp' },
      { name: 'salt', quantity: '1/2', unit: 'tsp' },
    ],
    steps: [
      'Grate cucumber and squeeze out excess water.',
      'Combine yogurt, cucumber, garlic, dill, and lemon juice.',
      'Drizzle with olive oil and season with salt.',
      'Refrigerate 1 hour before serving. Serve with pita or vegetables.',
    ],
    tags: ['tzatziki', 'greek', 'yogurt', 'dip', 'cucumber'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 80,
      protein_g: 6,
      carbs_g: 4,
      fat_g: 5,
      fiber_g: 0,
      sugar_g: 3,
      sodium_mg: 180,
    },
  },
  {
    title: 'Baklava',
    description: 'Flaky phyllo layers with walnuts and pistachios drenched in honey syrup.',
    cuisine: 'Greek',
    prep_minutes: 30,
    cook_minutes: 45,
    servings: 24,
    calories: 200,
    ingredients: [
      { name: 'phyllo dough', quantity: '1', unit: 'package' },
      { name: 'walnuts', quantity: '2', unit: 'cups, chopped' },
      { name: 'pistachios', quantity: '1', unit: 'cup, chopped' },
      { name: 'butter', quantity: '1', unit: 'cup, melted' },
      { name: 'sugar', quantity: '1', unit: 'cup' },
      { name: 'honey', quantity: '1', unit: 'cup' },
      { name: 'cinnamon', quantity: '1', unit: 'tsp' },
      { name: 'lemon juice', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Layer phyllo in a baking dish, brushing each sheet with butter. Every 5th layer, spread nut mixture.',
      'Cut into diamond shapes before baking. Bake at 350°F for 45 minutes until golden.',
      'Make syrup: boil sugar, honey, water, and lemon juice for 10 minutes.',
      'Pour hot syrup over hot baklava. Let cool completely before serving.',
    ],
    tags: ['baklava', 'greek', 'dessert', 'phyllo', 'honey'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 200,
      protein_g: 3,
      carbs_g: 24,
      fat_g: 12,
      fiber_g: 1,
      sugar_g: 18,
      sodium_mg: 120,
    },
  },
  {
    title: 'Greek Salad',
    description:
      'Chunky salad of tomatoes, cucumbers, olives, and feta with olive oil and oregano.',
    cuisine: 'Greek',
    prep_minutes: 10,
    cook_minutes: 0,
    servings: 4,
    calories: 220,
    ingredients: [
      { name: 'tomato', quantity: '4', unit: 'large, chunked' },
      { name: 'cucumber', quantity: '1', unit: 'large, chunked' },
      { name: 'red onion', quantity: '1/2', unit: 'sliced' },
      { name: 'kalamata olives', quantity: '1/2', unit: 'cup' },
      { name: 'feta cheese', quantity: '4', unit: 'oz, block' },
      { name: 'olive oil', quantity: '3', unit: 'tbsp' },
      { name: 'oregano', quantity: '1', unit: 'tsp' },
      { name: 'red wine vinegar', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Cut tomatoes, cucumbers, and onion into large chunks.',
      'Arrange on a platter with olives and a slab of feta on top.',
      'Drizzle with olive oil and vinegar. Sprinkle with oregano.',
      'Season with salt and pepper. Serve with crusty bread.',
    ],
    tags: ['greek salad', 'greek', 'salad', 'feta', 'vegetarian'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 220,
      protein_g: 8,
      carbs_g: 10,
      fat_g: 18,
      fiber_g: 3,
      sugar_g: 5,
      sodium_mg: 480,
    },
  },
  {
    title: 'Pastitsio',
    description: 'Greek baked pasta with spiced meat sauce and creamy béchamel topping.',
    cuisine: 'Greek',
    prep_minutes: 30,
    cook_minutes: 45,
    servings: 8,
    calories: 460,
    ingredients: [
      { name: 'bucatini pasta', quantity: '1', unit: 'lb' },
      { name: 'ground beef', quantity: '1', unit: 'lb' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'tomato sauce', quantity: '1.5', unit: 'cups' },
      { name: 'cinnamon', quantity: '1/2', unit: 'tsp' },
      { name: 'butter', quantity: '3', unit: 'tbsp' },
      { name: 'flour', quantity: '3', unit: 'tbsp' },
      { name: 'milk', quantity: '2', unit: 'cups' },
    ],
    steps: [
      'Cook pasta al dente. Make meat sauce: brown beef with onion, add tomato sauce and cinnamon. Simmer 15 minutes.',
      'Make béchamel: melt butter, whisk in flour, slowly add milk until thick. Add nutmeg and egg.',
      'Layer pasta, meat sauce, more pasta. Top with béchamel.',
      'Bake at 375°F for 40 minutes until golden. Rest 15 minutes before cutting.',
    ],
    tags: ['pastitsio', 'greek', 'pasta', 'baked', 'béchamel'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 460,
      protein_g: 22,
      carbs_g: 42,
      fat_g: 22,
      fiber_g: 3,
      sugar_g: 6,
      sodium_mg: 520,
    },
  },
  {
    title: 'Dolmades',
    description: 'Grape leaves stuffed with herbed rice, pine nuts, and lemon.',
    cuisine: 'Greek',
    prep_minutes: 40,
    cook_minutes: 45,
    servings: 8,
    calories: 120,
    ingredients: [
      { name: 'grape leaves', quantity: '1', unit: 'jar, rinsed' },
      { name: 'rice', quantity: '1', unit: 'cup' },
      { name: 'pine nuts', quantity: '1/4', unit: 'cup' },
      { name: 'onion', quantity: '1', unit: 'small, diced' },
      { name: 'dill', quantity: '2', unit: 'tbsp' },
      { name: 'mint', quantity: '2', unit: 'tbsp' },
      { name: 'lemon juice', quantity: '3', unit: 'tbsp' },
      { name: 'olive oil', quantity: '3', unit: 'tbsp' },
    ],
    steps: [
      'Sauté onion, add rice and cook 2 minutes. Add pine nuts, dill, mint, salt, and water. Cook until rice absorbs liquid.',
      'Place a spoonful of filling on each grape leaf. Fold sides in and roll tightly.',
      'Arrange rolls seam-down in a pot. Add olive oil, lemon juice, and water.',
      'Simmer covered for 40 minutes. Serve warm or at room temperature.',
    ],
    tags: ['dolmades', 'greek', 'grape leaves', 'stuffed', 'vegetarian'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 120,
      protein_g: 3,
      carbs_g: 16,
      fat_g: 5,
      fiber_g: 2,
      sugar_g: 1,
      sodium_mg: 280,
    },
  },
  {
    title: 'Gyros',
    description: 'Seasoned meat carved from a vertical rotisserie, served in pita with fixings.',
    cuisine: 'Greek',
    prep_minutes: 20,
    cook_minutes: 30,
    servings: 4,
    calories: 480,
    ingredients: [
      { name: 'pork shoulder', quantity: '1.5', unit: 'lbs, sliced thin' },
      { name: 'pita bread', quantity: '4', unit: 'pieces' },
      { name: 'tzatziki', quantity: '1/2', unit: 'cup' },
      { name: 'tomato', quantity: '1', unit: 'sliced' },
      { name: 'onion', quantity: '1/2', unit: 'sliced' },
      { name: 'oregano', quantity: '1', unit: 'tbsp' },
      { name: 'lemon juice', quantity: '2', unit: 'tbsp' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Marinate pork in olive oil, lemon juice, oregano, garlic, and thyme for 2+ hours.',
      'Grill or pan-sear pork slices until charred and cooked through.',
      'Warm pita bread. Assemble gyros with meat, tzatziki, tomato, and onion.',
      'Sprinkle with oregano and a squeeze of lemon.',
    ],
    tags: ['gyros', 'greek', 'pork', 'pita', 'street food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 480,
      protein_g: 32,
      carbs_g: 30,
      fat_g: 24,
      fiber_g: 2,
      sugar_g: 4,
      sodium_mg: 580,
    },
  },
  {
    title: 'Avgolemono Soup',
    description: 'Silky Greek chicken soup thickened with egg-lemon liaison and orzo.',
    cuisine: 'Greek',
    prep_minutes: 10,
    cook_minutes: 25,
    servings: 6,
    calories: 240,
    ingredients: [
      { name: 'chicken broth', quantity: '6', unit: 'cups' },
      { name: 'orzo pasta', quantity: '1/2', unit: 'cup' },
      { name: 'eggs', quantity: '3', unit: 'large' },
      { name: 'lemon juice', quantity: '1/3', unit: 'cup' },
      { name: 'shredded chicken', quantity: '1.5', unit: 'cups' },
      { name: 'dill', quantity: '2', unit: 'tbsp, chopped' },
      { name: 'salt', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Bring broth to boil, add orzo and cook 8 minutes until tender.',
      'Add shredded chicken and heat through.',
      'Whisk eggs and lemon juice together. Slowly temper in hot broth.',
      'Stir egg-lemon mixture back into soup. Add dill. Do not boil after adding eggs.',
    ],
    tags: ['avgolemono', 'greek', 'soup', 'chicken', 'lemon'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 240,
      protein_g: 18,
      carbs_g: 18,
      fat_g: 10,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 680,
    },
  },
  {
    title: 'Saganaki',
    description: 'Pan-seared Greek cheese flambéed with brandy and finished with lemon.',
    cuisine: 'Greek',
    prep_minutes: 5,
    cook_minutes: 5,
    servings: 4,
    calories: 180,
    ingredients: [
      { name: 'kasseri cheese', quantity: '8', unit: 'oz, sliced thick' },
      { name: 'flour', quantity: '2', unit: 'tbsp, for dusting' },
      { name: 'olive oil', quantity: '1', unit: 'tbsp' },
      { name: 'brandy', quantity: '2', unit: 'tbsp' },
      { name: 'lemon wedges', quantity: '4', unit: 'pieces' },
    ],
    steps: [
      'Dust cheese slices with flour on both sides.',
      'Heat olive oil in a skillet over medium-high heat.',
      'Sear cheese 1-2 minutes per side until golden and softened.',
      'Carefully add brandy and ignite. Squeeze lemon when flames die. Serve immediately.',
    ],
    tags: ['saganaki', 'greek', 'cheese', 'flambé', 'appetizer'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 180,
      protein_g: 10,
      carbs_g: 4,
      fat_g: 14,
      fiber_g: 0,
      sugar_g: 1,
      sodium_mg: 340,
    },
  },
  {
    title: 'Lemon Potatoes',
    description: 'Roasted potatoes with lemon, oregano, and garlic — a Greek table staple.',
    cuisine: 'Greek',
    prep_minutes: 10,
    cook_minutes: 50,
    servings: 6,
    calories: 200,
    ingredients: [
      { name: 'potatoes', quantity: '3', unit: 'lbs, quartered' },
      { name: 'lemon juice', quantity: '1/4', unit: 'cup' },
      { name: 'olive oil', quantity: '1/4', unit: 'cup' },
      { name: 'oregano', quantity: '1', unit: 'tbsp' },
      { name: 'garlic', quantity: '4', unit: 'cloves, smashed' },
      { name: 'chicken broth', quantity: '1/2', unit: 'cup' },
      { name: 'salt', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Toss potatoes with olive oil, lemon juice, oregano, garlic, and salt.',
      'Arrange in a single layer in a baking dish. Pour broth around potatoes.',
      'Roast at 400°F for 45-50 minutes, turning once, until golden and tender.',
      'Serve hot with extra lemon wedges.',
    ],
    tags: ['lemon potatoes', 'greek', 'potato', 'roasted', 'side dish'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 200,
      protein_g: 4,
      carbs_g: 30,
      fat_g: 8,
      fiber_g: 3,
      sugar_g: 2,
      sodium_mg: 280,
    },
  },
  {
    title: 'Lamb Kleftiko',
    description:
      "Slow-baked lamb with herbs, lemon, and vegetables in parchment — the bandit's way.",
    cuisine: 'Greek',
    prep_minutes: 20,
    cook_minutes: 180,
    servings: 6,
    calories: 420,
    ingredients: [
      { name: 'lamb shoulder', quantity: '3', unit: 'lbs' },
      { name: 'lemon juice', quantity: '3', unit: 'tbsp' },
      { name: 'oregano', quantity: '1', unit: 'tbsp' },
      { name: 'garlic', quantity: '6', unit: 'cloves' },
      { name: 'potato', quantity: '4', unit: 'medium, quartered' },
      { name: 'onion', quantity: '2', unit: 'quartered' },
      { name: 'olive oil', quantity: '3', unit: 'tbsp' },
      { name: 'rosemary', quantity: '2', unit: 'sprigs' },
    ],
    steps: [
      'Score lamb and rub with garlic, oregano, lemon, olive oil, salt, and pepper.',
      'Place lamb with potatoes and onion on parchment. Seal tightly.',
      'Bake at 325°F for 3 hours until lamb is falling-apart tender.',
      'Open parchment at the table. Serve with the juices.',
    ],
    tags: ['kleftiko', 'greek', 'lamb', 'slow-cooked', 'parchment'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 32,
      carbs_g: 20,
      fat_g: 24,
      fiber_g: 3,
      sugar_g: 3,
      sodium_mg: 420,
    },
  },
  {
    title: 'Galaktoboureko',
    description: 'Greek custard pie wrapped in crispy phyllo and soaked in lemon syrup.',
    cuisine: 'Greek',
    prep_minutes: 25,
    cook_minutes: 45,
    servings: 12,
    calories: 280,
    ingredients: [
      { name: 'semolina', quantity: '1/2', unit: 'cup' },
      { name: 'milk', quantity: '4', unit: 'cups' },
      { name: 'sugar', quantity: '3/4', unit: 'cup' },
      { name: 'eggs', quantity: '4', unit: 'large' },
      { name: 'butter', quantity: '1/2', unit: 'cup, melted' },
      { name: 'phyllo dough', quantity: '1', unit: 'package' },
      { name: 'lemon zest', quantity: '1', unit: 'tbsp' },
      { name: 'vanilla', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Make custard: heat milk, whisk in semolina and sugar. Cook until thick. Temper in beaten eggs, add zest and vanilla.',
      'Layer buttered phyllo in a baking dish. Pour in custard. Top with more phyllo.',
      'Bake at 350°F for 40 minutes until golden.',
      'Pour warm lemon syrup over hot pastry. Cool before slicing.',
    ],
    tags: ['galaktoboureko', 'greek', 'dessert', 'custard', 'phyllo'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 8,
      carbs_g: 34,
      fat_g: 13,
      fiber_g: 1,
      sugar_g: 22,
      sodium_mg: 160,
    },
  },
  {
    title: 'Fasolada',
    description: 'Hearty Greek white bean soup with tomato, celery, and olive oil.',
    cuisine: 'Greek',
    prep_minutes: 10,
    cook_minutes: 60,
    servings: 6,
    calories: 240,
    ingredients: [
      { name: 'white beans', quantity: '2', unit: 'cups, dried, soaked' },
      { name: 'tomato', quantity: '2', unit: 'diced' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'celery', quantity: '3', unit: 'stalks, diced' },
      { name: 'carrot', quantity: '1', unit: 'diced' },
      { name: 'olive oil', quantity: '1/4', unit: 'cup' },
      { name: 'tomato paste', quantity: '2', unit: 'tbsp' },
      { name: 'bay leaf', quantity: '1', unit: 'piece' },
    ],
    steps: [
      'Soak beans overnight. Drain and rinse.',
      'Sauté onion, celery, and carrot in olive oil. Add tomato paste and cook 2 minutes.',
      'Add beans, tomato, bay leaf, and water. Simmer 50-60 minutes until beans are tender.',
      'Finish with a generous drizzle of raw olive oil. Serve with crusty bread.',
    ],
    tags: ['fasolada', 'greek', 'beans', 'soup', 'vegan'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 240,
      protein_g: 12,
      carbs_g: 34,
      fat_g: 8,
      fiber_g: 10,
      sugar_g: 4,
      sodium_mg: 280,
    },
  },
];

export const greekRecipes = generateCuisineRecipes(configs);
