import type { CuisineRecipeConfig } from './types';
import { generateCuisineRecipes } from './types';

const configs: CuisineRecipeConfig[] = [
  {
    title: 'Butter Chicken',
    description:
      'Creamy tomato-based curry with tender marinated chicken, butter, and warm spices.',
    cuisine: 'Indian',
    prep_minutes: 30,
    cook_minutes: 30,
    servings: 6,
    calories: 380,
    ingredients: [
      { name: 'chicken thigh', quantity: '1.5', unit: 'lb, cubed' },
      { name: 'yogurt', quantity: '1/2', unit: 'cup' },
      { name: 'garam masala', quantity: '1', unit: 'tbsp' },
      { name: 'butter', quantity: '3', unit: 'tbsp' },
      { name: 'tomato puree', quantity: '2', unit: 'cups' },
      { name: 'heavy cream', quantity: '1/2', unit: 'cup' },
      { name: 'ginger-garlic paste', quantity: '1', unit: 'tbsp' },
      { name: 'kasuri methi', quantity: '1', unit: 'tbsp' },
      { name: 'cumin', quantity: '1', unit: 'tsp' },
      { name: 'sugar', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Marinate chicken in yogurt, garam masala, and salt for at least 1 hour.',
      'Grill or pan-sear marinated chicken until charred. Set aside.',
      'Melt butter, add cumin and ginger-garlic paste. Cook until fragrant.',
      'Add tomato puree and simmer 15 minutes until thickened.',
      'Add cream, kasuri methi, and sugar. Stir well.',
      'Add charred chicken pieces, simmer 10 minutes. Serve with naan or rice.',
    ],
    tags: ['indian', 'curry', 'chicken', 'creamy', 'tomato'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 32,
      carbs_g: 10,
      fat_g: 24,
      fiber_g: 2,
      sugar_g: 6,
      sodium_mg: 580,
    },
  },
  {
    title: 'Chicken Tikka Masala',
    description: 'Smoky tandoori-spiced chicken pieces in a rich, spiced tomato-cream sauce.',
    cuisine: 'Indian',
    prep_minutes: 30,
    cook_minutes: 25,
    servings: 6,
    calories: 400,
    ingredients: [
      { name: 'chicken breast', quantity: '1.5', unit: 'lb, cubed' },
      { name: 'yogurt', quantity: '1/2', unit: 'cup' },
      { name: 'tandoori spice', quantity: '2', unit: 'tbsp' },
      { name: 'tomato sauce', quantity: '2', unit: 'cups' },
      { name: 'heavy cream', quantity: '1/2', unit: 'cup' },
      { name: 'onion', quantity: '1', unit: 'large, diced' },
      { name: 'ginger-garlic paste', quantity: '1', unit: 'tbsp' },
      { name: 'garam masala', quantity: '1', unit: 'tbsp' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
      { name: 'cilantro', quantity: '1/4', unit: 'cup, chopped' },
    ],
    steps: [
      'Marinate chicken in yogurt and tandoori spice for 2 hours.',
      'Grill or broil chicken until charred on edges.',
      'Sauté onion in butter, add ginger-garlic paste and garam masala.',
      'Add tomato sauce and simmer 15 minutes.',
      'Stir in cream and add the grilled chicken pieces.',
      'Simmer 10 minutes, garnish with cilantro. Serve with basmati rice.',
    ],
    tags: ['indian', 'curry', 'chicken', 'tandoori', 'creamy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 400,
      protein_g: 36,
      carbs_g: 12,
      fat_g: 22,
      fiber_g: 2,
      sugar_g: 8,
      sodium_mg: 620,
    },
  },
  {
    title: 'Palak Paneer',
    description: 'Creamy pureed spinach curry with cubes of paneer cheese and aromatic spices.',
    cuisine: 'Indian',
    prep_minutes: 15,
    cook_minutes: 25,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'paneer', quantity: '8', unit: 'oz, cubed' },
      { name: 'fresh spinach', quantity: '1', unit: 'lb' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'ginger-garlic paste', quantity: '1', unit: 'tbsp' },
      { name: 'cumin', quantity: '1', unit: 'tsp' },
      { name: 'garam masala', quantity: '1', unit: 'tsp' },
      { name: 'cream', quantity: '1/4', unit: 'cup' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
      { name: 'green chili', quantity: '2', unit: 'whole' },
    ],
    steps: [
      'Blanch spinach and blend into a smooth puree.',
      'Pan-fry paneer cubes until golden on all sides. Set aside.',
      'Sauté onion, add ginger-garlic paste, cumin, and garam masala.',
      'Add spinach puree and simmer 10 minutes.',
      'Stir in cream and butter. Add paneer cubes.',
      'Simmer 5 minutes and serve with naan or rice.',
    ],
    tags: ['indian', 'vegetarian', 'spinach', 'paneer', 'curry'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 16,
      carbs_g: 10,
      fat_g: 20,
      fiber_g: 4,
      sugar_g: 3,
      sodium_mg: 480,
    },
  },
  {
    title: 'Chana Masala',
    description: 'Hearty chickpea curry simmered in a tangy tomato sauce with warming spices.',
    cuisine: 'Indian',
    prep_minutes: 10,
    cook_minutes: 25,
    servings: 4,
    calories: 240,
    ingredients: [
      { name: 'chickpeas', quantity: '2', unit: 'cans (15 oz), drained' },
      { name: 'tomato', quantity: '3', unit: 'medium, diced' },
      { name: 'onion', quantity: '1', unit: 'large, diced' },
      { name: 'ginger-garlic paste', quantity: '1', unit: 'tbsp' },
      { name: 'cumin', quantity: '1', unit: 'tsp' },
      { name: 'coriander', quantity: '1', unit: 'tsp' },
      { name: 'garam masala', quantity: '1', unit: 'tsp' },
      { name: 'amchur powder', quantity: '1/2', unit: 'tsp' },
      { name: 'cilantro', quantity: '1/4', unit: 'cup' },
      { name: 'green chili', quantity: '1', unit: 'sliced' },
    ],
    steps: [
      'Sauté onion until golden, add cumin seeds until they splutter.',
      'Add ginger-garlic paste and cook 1 minute.',
      'Add tomatoes and cook until soft and oil separates.',
      'Add coriander, garam masala, and amchur powder.',
      'Add chickpeas and 1 cup water. Simmer 20 minutes, mashing some chickpeas.',
      'Garnish with cilantro and green chili. Serve with rice or bhatura.',
    ],
    tags: ['indian', 'vegetarian', 'vegan', 'chickpea', 'curry'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 240,
      protein_g: 12,
      carbs_g: 36,
      fat_g: 6,
      fiber_g: 10,
      sugar_g: 6,
      sodium_mg: 420,
    },
  },
  {
    title: 'Dal Tadka',
    description: 'Yellow lentils tempered with ghee, cumin, mustard seeds, and dried red chilies.',
    cuisine: 'Indian',
    prep_minutes: 10,
    cook_minutes: 30,
    servings: 4,
    calories: 200,
    ingredients: [
      { name: 'toor dal', quantity: '1', unit: 'cup' },
      { name: 'turmeric', quantity: '1/2', unit: 'tsp' },
      { name: 'ghee', quantity: '2', unit: 'tbsp' },
      { name: 'cumin seeds', quantity: '1', unit: 'tsp' },
      { name: 'mustard seeds', quantity: '1/2', unit: 'tsp' },
      { name: 'dried red chili', quantity: '2', unit: 'whole' },
      { name: 'garlic', quantity: '3', unit: 'cloves, sliced' },
      { name: 'asafoetida', quantity: '1', unit: 'pinch' },
      { name: 'tomato', quantity: '1', unit: 'diced' },
      { name: 'cilantro', quantity: '2', unit: 'tbsp, chopped' },
    ],
    steps: [
      'Wash and cook dal with turmeric and 3 cups water until soft, about 25 minutes.',
      'Mash dal partially for a creamy consistency.',
      'Heat ghee in a small pan. Add cumin and mustard seeds until they splutter.',
      'Add dried chilies, garlic, and asafoetida. Fry until garlic is golden.',
      'Add tomato and cook 2 minutes.',
      'Pour the tempering (tadka) over the dal. Garnish with cilantro and serve with rice.',
    ],
    tags: ['indian', 'vegetarian', 'lentils', 'comfort-food', 'dal'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 200,
      protein_g: 12,
      carbs_g: 28,
      fat_g: 6,
      fiber_g: 8,
      sugar_g: 3,
      sodium_mg: 320,
    },
  },
  {
    title: 'Biryani',
    description: 'Fragrant layered rice dish with spiced chicken, saffron, and crispy onions.',
    cuisine: 'Indian',
    prep_minutes: 40,
    cook_minutes: 40,
    servings: 8,
    calories: 450,
    ingredients: [
      { name: 'basmati rice', quantity: '2', unit: 'cups' },
      { name: 'chicken', quantity: '2', unit: 'lb, pieces' },
      { name: 'yogurt', quantity: '1', unit: 'cup' },
      { name: 'saffron', quantity: '1', unit: 'pinch, soaked in milk' },
      { name: 'ghee', quantity: '3', unit: 'tbsp' },
      { name: 'onion', quantity: '3', unit: 'large, sliced' },
      { name: 'ginger-garlic paste', quantity: '2', unit: 'tbsp' },
      { name: 'biryani masala', quantity: '2', unit: 'tbsp' },
      { name: 'mint', quantity: '1/4', unit: 'cup' },
      { name: 'cilantro', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Marinate chicken in yogurt, biryani masala, and ginger-garlic paste for 2 hours.',
      'Parboil basmati rice with whole spices until 70% done. Drain.',
      'Fry sliced onions in ghee until deep golden and crispy.',
      'Layer marinated chicken in a pot, top with parboiled rice.',
      'Drizzle saffron milk, add mint, cilantro, and crispy onions.',
      'Seal pot with dough or foil. Cook on low heat (dum) for 30 minutes.',
    ],
    tags: ['indian', 'rice', 'chicken', 'saffron', 'festive'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 450,
      protein_g: 30,
      carbs_g: 42,
      fat_g: 18,
      fiber_g: 2,
      sugar_g: 4,
      sodium_mg: 560,
    },
  },
  {
    title: 'Samosa',
    description: 'Crispy golden pastry triangles filled with spiced potatoes, peas, and cumin.',
    cuisine: 'Indian',
    prep_minutes: 30,
    cook_minutes: 15,
    servings: 8,
    calories: 180,
    ingredients: [
      { name: 'samosa wrappers', quantity: '16', unit: 'sheets' },
      { name: 'potato', quantity: '3', unit: 'medium, boiled & mashed' },
      { name: 'green peas', quantity: '1/2', unit: 'cup' },
      { name: 'cumin seeds', quantity: '1', unit: 'tsp' },
      { name: 'garam masala', quantity: '1', unit: 'tsp' },
      { name: 'amchur powder', quantity: '1/2', unit: 'tsp' },
      { name: 'green chili', quantity: '2', unit: 'minced' },
      { name: 'ginger', quantity: '1', unit: 'tsp, minced' },
      { name: 'cilantro', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Heat oil, add cumin seeds until they splutter. Add ginger and green chili.',
      'Add peas and cook 2 minutes. Add mashed potatoes, garam masala, and amchur.',
      'Mix well, add cilantro, and let filling cool completely.',
      'Cut wrappers into strips, form cones, fill with potato mixture, and seal.',
      'Deep fry at 325°F until golden and crispy.',
      'Serve with mint chutney and tamarind sauce.',
    ],
    tags: ['indian', 'vegetarian', 'appetizer', 'fried', 'street-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 180,
      protein_g: 4,
      carbs_g: 24,
      fat_g: 8,
      fiber_g: 3,
      sugar_g: 2,
      sodium_mg: 340,
    },
  },
  {
    title: 'Aloo Gobi',
    description: 'Dry curry of potatoes and cauliflower with turmeric, cumin, and green peas.',
    cuisine: 'Indian',
    prep_minutes: 15,
    cook_minutes: 20,
    servings: 4,
    calories: 220,
    ingredients: [
      { name: 'potato', quantity: '2', unit: 'medium, cubed' },
      { name: 'cauliflower', quantity: '1', unit: 'small, florets' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'tomato', quantity: '2', unit: 'diced' },
      { name: 'turmeric', quantity: '1/2', unit: 'tsp' },
      { name: 'cumin seeds', quantity: '1', unit: 'tsp' },
      { name: 'coriander powder', quantity: '1', unit: 'tsp' },
      { name: 'green peas', quantity: '1/4', unit: 'cup' },
      { name: 'ginger', quantity: '1', unit: 'tsp, grated' },
      { name: 'cilantro', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Heat oil, add cumin seeds until they splutter. Add onion and ginger.',
      'Add turmeric, coriander, and cook 1 minute.',
      'Add potato cubes and cauliflower florets. Toss to coat with spices.',
      'Add tomatoes, salt, and a splash of water. Cover and cook 15 minutes.',
      'Add green peas and cook 5 more minutes.',
      'Garnish with cilantro and serve with chapati or rice.',
    ],
    tags: ['indian', 'vegetarian', 'vegan', 'potato', 'cauliflower'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 220,
      protein_g: 6,
      carbs_g: 34,
      fat_g: 8,
      fiber_g: 6,
      sugar_g: 4,
      sodium_mg: 380,
    },
  },
  {
    title: 'Naan Bread',
    description:
      'Soft, pillowy Indian flatbread brushed with butter, cooked in a hot skillet or tandoor.',
    cuisine: 'Indian',
    prep_minutes: 15,
    cook_minutes: 10,
    servings: 8,
    calories: 160,
    ingredients: [
      { name: 'all-purpose flour', quantity: '3', unit: 'cups' },
      { name: 'yogurt', quantity: '1/4', unit: 'cup' },
      { name: 'warm water', quantity: '1/2', unit: 'cup' },
      { name: 'yeast', quantity: '1', unit: 'tsp' },
      { name: 'sugar', quantity: '1', unit: 'tsp' },
      { name: 'baking powder', quantity: '1/2', unit: 'tsp' },
      { name: 'butter', quantity: '2', unit: 'tbsp, melted' },
      { name: 'garlic', quantity: '2', unit: 'cloves, minced' },
      { name: 'cilantro', quantity: '1', unit: 'tbsp, chopped' },
    ],
    steps: [
      'Mix yeast, sugar, and warm water. Let proof for 10 minutes.',
      'Combine flour, yogurt, baking powder, salt, and yeast mixture. Knead 5 minutes.',
      'Let dough rise for 1 hour until doubled.',
      'Divide into 8 balls, roll into ovals.',
      'Cook on a hot cast-iron skillet until puffed and charred on both sides.',
      'Brush with garlic butter and sprinkle with cilantro. Serve immediately.',
    ],
    tags: ['indian', 'bread', 'naan', 'vegetarian', 'flatbread'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 160,
      protein_g: 4,
      carbs_g: 28,
      fat_g: 4,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 280,
    },
  },
  {
    title: 'Tandoori Chicken',
    description:
      'Yogurt-marinated chicken roasted with smoky tandoori spices until charred and juicy.',
    cuisine: 'Indian',
    prep_minutes: 15,
    cook_minutes: 30,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'whole chicken', quantity: '1', unit: '(3-4 lb), quartered' },
      { name: 'yogurt', quantity: '1', unit: 'cup' },
      { name: 'tandoori paste', quantity: '3', unit: 'tbsp' },
      { name: 'ginger-garlic paste', quantity: '1', unit: 'tbsp' },
      { name: 'lemon juice', quantity: '2', unit: 'tbsp' },
      { name: 'garam masala', quantity: '1', unit: 'tsp' },
      { name: 'red food coloring', quantity: '1', unit: 'drop' },
      { name: 'cilantro', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Make deep slashes in chicken pieces.',
      'Mix yogurt, tandoori paste, ginger-garlic, lemon juice, and garam masala.',
      'Coat chicken thoroughly in marinade. Refrigerate 4-8 hours.',
      'Roast at 475°F for 25-30 minutes until charred and cooked through.',
      'Baste with butter halfway through cooking.',
      'Garnish with cilantro and serve with mint chutney and naan.',
    ],
    tags: ['indian', 'chicken', 'tandoori', 'grilled', 'spicy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 38,
      carbs_g: 4,
      fat_g: 12,
      fiber_g: 0,
      sugar_g: 3,
      sodium_mg: 460,
    },
  },
  {
    title: 'Rogan Josh',
    description: 'Kashmiri slow-braised lamb curry with deep red chili, fennel, and yogurt.',
    cuisine: 'Indian',
    prep_minutes: 20,
    cook_minutes: 90,
    servings: 6,
    calories: 380,
    ingredients: [
      { name: 'lamb shoulder', quantity: '2', unit: 'lb, cubed' },
      { name: 'yogurt', quantity: '1/2', unit: 'cup' },
      { name: 'Kashmiri chili powder', quantity: '2', unit: 'tbsp' },
      { name: 'fennel seeds', quantity: '1', unit: 'tsp, ground' },
      { name: 'ginger', quantity: '1', unit: 'tbsp, grated' },
      { name: 'garam masala', quantity: '1', unit: 'tsp' },
      { name: 'onion', quantity: '2', unit: 'sliced' },
      { name: 'ghee', quantity: '2', unit: 'tbsp' },
      { name: 'cardamom', quantity: '3', unit: 'pods' },
      { name: 'cinnamon stick', quantity: '1', unit: 'inch piece' },
    ],
    steps: [
      'Brown lamb in ghee on all sides. Set aside.',
      'Sauté onions until golden. Add ginger and whole spices.',
      'Add Kashmiri chili and fennel, cook 1 minute.',
      'Return lamb, add yogurt and 2 cups water.',
      'Bring to boil, then simmer covered for 1.5 hours until lamb is tender.',
      'Add garam masala, adjust salt. Serve with steamed rice or naan.',
    ],
    tags: ['indian', 'curry', 'lamb', 'kashmiri', 'slow-cook'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 32,
      carbs_g: 6,
      fat_g: 24,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 520,
    },
  },
  {
    title: 'Masala Dosa',
    description:
      'Crispy fermented rice-lentil crepe filled with spiced potato masala and served with chutneys.',
    cuisine: 'Indian',
    prep_minutes: 20,
    cook_minutes: 10,
    servings: 6,
    calories: 220,
    ingredients: [
      { name: 'dosa batter', quantity: '3', unit: 'cups' },
      { name: 'potato', quantity: '4', unit: 'boiled, mashed' },
      { name: 'mustard seeds', quantity: '1', unit: 'tsp' },
      { name: 'urad dal', quantity: '1', unit: 'tsp' },
      { name: 'curry leaves', quantity: '8', unit: 'leaves' },
      { name: 'green chili', quantity: '2', unit: 'sliced' },
      { name: 'onion', quantity: '1', unit: 'sliced' },
      { name: 'turmeric', quantity: '1/4', unit: 'tsp' },
      { name: 'ghee', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Heat ghee, add mustard seeds and urad dal until they splutter.',
      'Add curry leaves, green chili, and onion. Sauté until onion is soft.',
      'Add turmeric and mashed potatoes. Mix well and season.',
      'Spread dosa batter thin on a hot griddle. Drizzle oil around edges.',
      'Cook until bottom is crispy and golden. Place potato filling in center.',
      'Fold dosa over filling and serve with coconut chutney and sambar.',
    ],
    tags: ['indian', 'south-indian', 'dosa', 'vegetarian', 'breakfast'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 220,
      protein_g: 6,
      carbs_g: 34,
      fat_g: 8,
      fiber_g: 3,
      sugar_g: 2,
      sodium_mg: 320,
    },
  },
  {
    title: 'Vindaloo',
    description: 'Fiery Goan pork curry with vinegar, garlic, and a blend of hot spices.',
    cuisine: 'Indian',
    prep_minutes: 20,
    cook_minutes: 60,
    servings: 6,
    calories: 360,
    ingredients: [
      { name: 'pork shoulder', quantity: '2', unit: 'lb, cubed' },
      { name: 'vinegar', quantity: '3', unit: 'tbsp' },
      { name: 'garlic', quantity: '6', unit: 'cloves, minced' },
      { name: 'ginger', quantity: '1', unit: 'tbsp, grated' },
      { name: 'Kashmiri chili', quantity: '6', unit: 'dried' },
      { name: 'cumin', quantity: '1', unit: 'tsp' },
      { name: 'mustard seeds', quantity: '1/2', unit: 'tsp' },
      { name: 'turmeric', quantity: '1/2', unit: 'tsp' },
      { name: 'onion', quantity: '2', unit: 'large, diced' },
      { name: 'cinnamon stick', quantity: '1', unit: 'small' },
    ],
    steps: [
      'Grind dried chilies, cumin, mustard seeds, and turmeric into a paste with vinegar.',
      'Marinate pork in the spice paste with garlic and ginger for 4 hours.',
      'Brown pork pieces in oil, set aside.',
      'Sauté onions until deep golden. Add cinnamon stick.',
      'Return pork with marinade and 1 cup water. Simmer covered 45-60 minutes.',
      'Adjust vinegar and salt. Serve with steamed rice.',
    ],
    tags: ['indian', 'goan', 'pork', 'spicy', 'curry'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 360,
      protein_g: 30,
      carbs_g: 8,
      fat_g: 22,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 480,
    },
  },
  {
    title: 'Malai Kofta',
    description: 'Deep-fried paneer and potato dumplings in a rich, creamy tomato-cashew sauce.',
    cuisine: 'Indian',
    prep_minutes: 30,
    cook_minutes: 25,
    servings: 6,
    calories: 340,
    ingredients: [
      { name: 'paneer', quantity: '8', unit: 'oz, grated' },
      { name: 'potato', quantity: '2', unit: 'medium, boiled & mashed' },
      { name: 'cashews', quantity: '1/4', unit: 'cup, soaked' },
      { name: 'tomato', quantity: '4', unit: 'large, pureed' },
      { name: 'cream', quantity: '1/2', unit: 'cup' },
      { name: 'garam masala', quantity: '1', unit: 'tsp' },
      { name: 'cornstarch', quantity: '2', unit: 'tbsp' },
      { name: 'raisins', quantity: '2', unit: 'tbsp' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
      { name: 'ginger-garlic paste', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Mix grated paneer, mashed potato, cornstarch, and salt. Form into balls with raisin centers.',
      'Deep fry kofta balls until golden. Set aside.',
      'Blend soaked cashews with a little water into a smooth paste.',
      'Sauté ginger-garlic in butter, add tomato puree and cook 15 minutes.',
      'Add cashew paste, cream, and garam masala. Simmer 10 minutes.',
      'Place kofta in serving dish, pour sauce over. Serve with naan.',
    ],
    tags: ['indian', 'vegetarian', 'paneer', 'creamy', 'festive'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 340,
      protein_g: 14,
      carbs_g: 18,
      fat_g: 24,
      fiber_g: 3,
      sugar_g: 6,
      sodium_mg: 460,
    },
  },
  {
    title: 'Raita',
    description:
      'Cool yogurt condiment with cucumber, cumin, and fresh herbs to balance spicy dishes.',
    cuisine: 'Indian',
    prep_minutes: 10,
    cook_minutes: 0,
    servings: 6,
    calories: 60,
    ingredients: [
      { name: 'yogurt', quantity: '2', unit: 'cups' },
      { name: 'cucumber', quantity: '1', unit: 'grated' },
      { name: 'cumin', quantity: '1/2', unit: 'tsp, roasted & ground' },
      { name: 'mint', quantity: '1', unit: 'tbsp, chopped' },
      { name: 'green chili', quantity: '1', unit: 'minced' },
      { name: 'salt', quantity: '1/2', unit: 'tsp' },
      { name: 'black pepper', quantity: '1/4', unit: 'tsp' },
    ],
    steps: [
      'Whisk yogurt until smooth.',
      'Squeeze excess water from grated cucumber.',
      'Mix cucumber into yogurt with cumin, mint, and green chili.',
      'Season with salt and black pepper.',
      'Chill for 30 minutes before serving.',
      'Serve as a cooling side with any spicy Indian dish.',
    ],
    tags: ['indian', 'vegetarian', 'yogurt', 'condiment', 'cooling'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 60,
      protein_g: 4,
      carbs_g: 6,
      fat_g: 2,
      fiber_g: 0,
      sugar_g: 4,
      sodium_mg: 180,
    },
  },
  {
    title: 'Gulab Jamun',
    description: 'Soft, spongy milk-solid dumplings soaked in fragrant rose-cardamom sugar syrup.',
    cuisine: 'Indian',
    prep_minutes: 20,
    cook_minutes: 15,
    servings: 8,
    calories: 200,
    ingredients: [
      { name: 'milk powder', quantity: '1', unit: 'cup' },
      { name: 'flour', quantity: '1/4', unit: 'cup' },
      { name: 'butter', quantity: '1', unit: 'tbsp, melted' },
      { name: 'milk', quantity: '1/4', unit: 'cup' },
      { name: 'sugar', quantity: '1.5', unit: 'cups' },
      { name: 'water', quantity: '1', unit: 'cup' },
      { name: 'rose water', quantity: '1', unit: 'tsp' },
      { name: 'cardamom', quantity: '1/4', unit: 'tsp, ground' },
      { name: 'saffron', quantity: '1', unit: 'pinch' },
      { name: 'ghee', quantity: '2', unit: 'cups for frying' },
    ],
    steps: [
      'Make sugar syrup: boil sugar and water, add rose water and cardamom. Set aside.',
      'Mix milk powder, flour, and butter. Add milk gradually to form a soft dough.',
      'Shape into smooth, crack-free balls.',
      'Fry in ghee at low heat (300°F) until deep golden all over.',
      'Immediately transfer hot jamuns into warm sugar syrup.',
      'Soak for at least 2 hours. Serve warm or at room temperature.',
    ],
    tags: ['indian', 'dessert', 'sweet', 'milk', 'festive'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 200,
      protein_g: 4,
      carbs_g: 36,
      fat_g: 6,
      fiber_g: 0,
      sugar_g: 28,
      sodium_mg: 120,
    },
  },
  {
    title: 'Pakora',
    description:
      'Crispy chickpea-flour fritters with onion, spinach, and aromatic spices, deep-fried golden.',
    cuisine: 'Indian',
    prep_minutes: 15,
    cook_minutes: 10,
    servings: 6,
    calories: 180,
    ingredients: [
      { name: 'besan (chickpea flour)', quantity: '1', unit: 'cup' },
      { name: 'onion', quantity: '2', unit: 'sliced thin' },
      { name: 'spinach', quantity: '1', unit: 'cup, chopped' },
      { name: 'green chili', quantity: '2', unit: 'minced' },
      { name: 'cumin seeds', quantity: '1', unit: 'tsp' },
      { name: 'turmeric', quantity: '1/4', unit: 'tsp' },
      { name: 'baking soda', quantity: '1/4', unit: 'tsp' },
      { name: 'cilantro', quantity: '2', unit: 'tbsp' },
      { name: 'water', quantity: '1/2', unit: 'cup' },
    ],
    steps: [
      'Mix besan, cumin, turmeric, baking soda, and salt.',
      'Add onion, spinach, green chili, and cilantro.',
      'Add water gradually to make a thick batter that coats the vegetables.',
      'Heat oil to 350°F. Drop spoonfuls of batter into the oil.',
      'Fry until golden and crispy on all sides, about 3-4 minutes.',
      'Drain on paper towels. Serve hot with mint chutney and tamarind sauce.',
    ],
    tags: ['indian', 'vegetarian', 'vegan', 'fritter', 'appetizer'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 180,
      protein_g: 6,
      carbs_g: 22,
      fat_g: 8,
      fiber_g: 4,
      sugar_g: 3,
      sodium_mg: 380,
    },
  },
  {
    title: 'Saag Aloo',
    description: 'Tender potato cubes simmered in a rich, spiced pureed spinach gravy.',
    cuisine: 'Indian',
    prep_minutes: 15,
    cook_minutes: 25,
    servings: 4,
    calories: 200,
    ingredients: [
      { name: 'potato', quantity: '3', unit: 'medium, cubed' },
      { name: 'fresh spinach', quantity: '1', unit: 'lb' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'ginger-garlic paste', quantity: '1', unit: 'tbsp' },
      { name: 'cumin seeds', quantity: '1', unit: 'tsp' },
      { name: 'garam masala', quantity: '1/2', unit: 'tsp' },
      { name: 'green chili', quantity: '2', unit: 'whole' },
      { name: 'oil', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Blanch spinach and blend into a puree.',
      'Fry cumin seeds in oil until they splutter. Add onion and ginger-garlic paste.',
      'Add potato cubes and cook 5 minutes, stirring.',
      'Add spinach puree, green chilies, and salt. Cover and simmer 20 minutes.',
      'Add garam masala and stir through.',
      'Serve hot with roti or steamed rice.',
    ],
    tags: ['indian', 'vegetarian', 'vegan', 'spinach', 'potato'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 200,
      protein_g: 8,
      carbs_g: 28,
      fat_g: 8,
      fiber_g: 6,
      sugar_g: 3,
      sodium_mg: 340,
    },
  },
  {
    title: 'Pani Puri',
    description:
      'Crispy hollow puri shells filled with spiced potato and dunked in tangy mint water.',
    cuisine: 'Indian',
    prep_minutes: 30,
    cook_minutes: 15,
    servings: 6,
    calories: 150,
    ingredients: [
      { name: 'puri shells', quantity: '30', unit: 'pieces' },
      { name: 'potato', quantity: '2', unit: 'boiled, mashed' },
      { name: 'chickpeas', quantity: '1/2', unit: 'cup, boiled' },
      { name: 'mint leaves', quantity: '1', unit: 'cup' },
      { name: 'cilantro', quantity: '1/2', unit: 'cup' },
      { name: 'green chili', quantity: '2', unit: 'whole' },
      { name: 'tamarind paste', quantity: '2', unit: 'tbsp' },
      { name: 'cumin powder', quantity: '1', unit: 'tsp' },
      { name: 'black salt', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Blend mint, cilantro, green chili, cumin, and black salt with water for pani.',
      'Add tamarind paste to the pani and chill.',
      'Mix mashed potato with chickpeas, cumin, and salt for the filling.',
      'Crack a small hole in each puri shell.',
      'Fill with potato mixture.',
      'Dunk into mint pani and eat in one bite!',
    ],
    tags: ['indian', 'street-food', 'snack', 'vegetarian', 'vegan'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 150,
      protein_g: 4,
      carbs_g: 24,
      fat_g: 4,
      fiber_g: 3,
      sugar_g: 4,
      sodium_mg: 420,
    },
  },
  {
    title: 'Korma',
    description: 'Mild, creamy curry with yogurt, nuts, and aromatic spices — rich and luxurious.',
    cuisine: 'Indian',
    prep_minutes: 20,
    cook_minutes: 30,
    servings: 6,
    calories: 360,
    ingredients: [
      { name: 'chicken', quantity: '1.5', unit: 'lb, cubed' },
      { name: 'yogurt', quantity: '1', unit: 'cup' },
      { name: 'cashews', quantity: '1/4', unit: 'cup, ground' },
      { name: 'almonds', quantity: '1/4', unit: 'cup, ground' },
      { name: 'cream', quantity: '1/4', unit: 'cup' },
      { name: 'onion', quantity: '2', unit: 'sliced' },
      { name: 'ginger-garlic paste', quantity: '1', unit: 'tbsp' },
      { name: 'garam masala', quantity: '1', unit: 'tsp' },
      { name: 'cardamom', quantity: '3', unit: 'pods' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Marinate chicken in yogurt, salt, and garam masala for 1 hour.',
      'Sauté onions in butter until golden. Add ginger-garlic paste and cardamom.',
      'Add ground cashews and almonds, cook 2 minutes.',
      'Add marinated chicken and cook until no longer pink.',
      'Add cream and simmer 15 minutes until thick and rich.',
      'Adjust seasoning and serve with naan or rice.',
    ],
    tags: ['indian', 'curry', 'chicken', 'creamy', 'mild'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 360,
      protein_g: 30,
      carbs_g: 10,
      fat_g: 24,
      fiber_g: 2,
      sugar_g: 4,
      sodium_mg: 480,
    },
  },
];

export const indianRecipes = generateCuisineRecipes(configs);
