import type { CuisineRecipeConfig } from './types';
import { generateCuisineRecipes } from './types';

const configs: CuisineRecipeConfig[] = [
  {
    title: 'Butter Chicken',
    description:
      'Creamy tomato-based curry with tender marinated chicken, butter, and warm spices.',
    cuisine: 'Indian',
    prep_minutes: 30,
    cook_minutes: 30,
    servings: 6,
    calories: 380,
    ingredients: [
      { name: 'chicken thigh', quantity: '1.5', unit: 'lb, cubed' },
      { name: 'yogurt', quantity: '1/2', unit: 'cup' },
      { name: 'garam masala', quantity: '1', unit: 'tbsp' },
      { name: 'butter', quantity: '3', unit: 'tbsp' },
      { name: 'tomato puree', quantity: '2', unit: 'cups' },
      { name: 'heavy cream', quantity: '1/2', unit: 'cup' },
      { name: 'ginger-garlic paste', quantity: '1', unit: 'tbsp' },
      { name: 'kasuri methi', quantity: '1', unit: 'tbsp' },
      { name: 'cumin', quantity: '1', unit: 'tsp' },
      { name: 'sugar', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Marinate chicken in yogurt, garam masala, and salt for at least 1 hour.',
      'Grill or pan-sear marinated chicken until charred. Set aside.',
      'Melt butter, add cumin and ginger-garlic paste. Cook until fragrant.',
      'Add tomato puree and simmer 15 minutes until thickened.',
      'Add cream, kasuri methi, and sugar. Stir well.',
      'Add charred chicken pieces, simmer 10 minutes. Serve with naan or rice.',
    ],
    tags: ['indian', 'curry', 'chicken', 'creamy', 'tomato'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 32,
      carbs_g: 10,
      fat_g: 24,
      fiber_g: 2,
      sugar_g: 6,
      sodium_mg: 580,
    },
  },
  {
    title: 'Chicken Tikka Masala',
    description: 'Smoky tandoori-spiced chicken pieces in a rich, spiced tomato-cream sauce.',
    cuisine: 'Indian',
    prep_minutes: 30,
    cook_minutes: 25,
    servings: 6,
    calories: 400,
    ingredients: [
      { name: 'chicken breast', quantity: '1.5', unit: 'lb, cubed' },
      { name: 'yogurt', quantity: '1/2', unit: 'cup' },
      { name: 'tandoori spice', quantity: '2', unit: 'tbsp' },
      { name: 'tomato sauce', quantity: '2', unit: 'cups' },
      { name: 'heavy cream', quantity: '1/2', unit: 'cup' },
      { name: 'onion', quantity: '1', unit: 'large, diced' },
      { name: 'ginger-garlic paste', quantity: '1', unit: 'tbsp' },
      { name: 'garam masala', quantity: '1', unit: 'tbsp' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
      { name: 'cilantro', quantity: '1/4', unit: 'cup, chopped' },
    ],
    steps: [
      'Marinate chicken in yogurt and tandoori spice for 2 hours.',
      'Grill or broil chicken until charred on edges.',
      'Sauté onion in butter, add ginger-garlic paste and garam masala.',
      'Add tomato sauce and simmer 15 minutes.',
      'Stir in cream and add the grilled chicken pieces.',
      'Simmer 10 minutes, garnish with cilantro. Serve with basmati rice.',
    ],
    tags: ['indian', 'curry', 'chicken', 'tandoori', 'creamy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 400,
      protein_g: 36,
      carbs_g: 12,
      fat_g: 22,
      fiber_g: 2,
      sugar_g: 8,
      sodium_mg: 620,
    },
  },
  {
    title: 'Palak Paneer',
    description: 'Creamy pureed spinach curry with cubes of paneer cheese and aromatic spices.',
    cuisine: 'Indian',
    prep_minutes: 15,
    cook_minutes: 25,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'paneer', quantity: '8', unit: 'oz, cubed' },
      { name: 'fresh spinach', quantity: '1', unit: 'lb' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'ginger-garlic paste', quantity: '1', unit: 'tbsp' },
      { name: 'cumin', quantity: '1', unit: 'tsp' },
      { name: 'garam masala', quantity: '1', unit: 'tsp' },
      { name: 'cream', quantity: '1/4', unit: 'cup' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
      { name: 'green chili', quantity: '2', unit: 'whole' },
    ],
    steps: [
      'Blanch spinach and blend into a smooth puree.',
      'Pan-fry paneer cubes until golden on all sides. Set aside.',
      'Sauté onion, add ginger-garlic paste, cumin, and garam masala.',
      'Add spinach puree and simmer 10 minutes.',
      'Stir in cream and butter. Add paneer cubes.',
      'Simmer 5 minutes and serve with naan or rice.',
    ],
    tags: ['indian', 'vegetarian', 'spinach', 'paneer', 'curry'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 16,
      carbs_g: 10,
      fat_g: 20,
      fiber_g: 4,
      sugar_g: 3,
      sodium_mg: 480,
    },
  },
  {
    title: 'Chana Masala',
    description: 'Hearty chickpea curry simmered in a tangy tomato sauce with warming spices.',
    cuisine: 'Indian',
    prep_minutes: 10,
    cook_minutes: 25,
    servings: 4,
    calories: 240,
    ingredients: [
      { name: 'chickpeas', quantity: '2', unit: 'cans (15 oz), drained' },
      { name: 'tomato', quantity: '3', unit: 'medium, diced' },
      { name: 'onion', quantity: '1', unit: 'large, diced' },
      { name: 'ginger-garlic paste', quantity: '1', unit: 'tbsp' },
      { name: 'cumin', quantity: '1', unit: 'tsp' },
      { name: 'coriander', quantity: '1', unit: 'tsp' },
      { name: 'garam masala', quantity: '1', unit: 'tsp' },
      { name: 'amchur powder', quantity: '1/2', unit: 'tsp' },
      { name: 'cilantro', quantity: '1/4', unit: 'cup' },
      { name: 'green chili', quantity: '1', unit: 'sliced' },
    ],
    steps: [
      'Sauté onion until golden, add cumin seeds until they splutter.',
      'Add ginger-garlic paste and cook 1 minute.',
      'Add tomatoes and cook until soft and oil separates.',
      'Add coriander, garam masala, and amchur powder.',
      'Add chickpeas and 1 cup water. Simmer 20 minutes, mashing some chickpeas.',
      'Garnish with cilantro and green chili. Serve with rice or bhatura.',
    ],
    tags: ['indian', 'vegetarian', 'vegan', 'chickpea', 'curry'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 240,
      protein_g: 12,
      carbs_g: 36,
      fat_g: 6,
      fiber_g: 10,
      sugar_g: 6,
      sodium_mg: 420,
    },
  },
  {
    title: 'Dal Tadka',
    description: 'Yellow lentils tempered with ghee, cumin, mustard seeds, and dried red chilies.',
    cuisine: 'Indian',
    prep_minutes: 10,
    cook_minutes: 30,
    servings: 4,
    calories: 200,
    ingredients: [
      { name: 'toor dal', quantity: '1', unit: 'cup' },
      { name: 'turmeric', quantity: '1/2', unit: 'tsp' },
      { name: 'ghee', quantity: '2', unit: 'tbsp' },
      { name: 'cumin seeds', quantity: '1', unit: 'tsp' },
      { name: 'mustard seeds', quantity: '1/2', unit: 'tsp' },
      { name: 'dried red chili', quantity: '2', unit: 'whole' },
      { name: 'garlic', quantity: '3', unit: 'cloves, sliced' },
      { name: 'asafoetida', quantity: '1', unit: 'pinch' },
      { name: 'tomato', quantity: '1', unit: 'diced' },
      { name: 'cilantro', quantity: '2', unit: 'tbsp, chopped' },
    ],
    steps: [
      'Wash and cook dal with turmeric and 3 cups water until soft, about 25 minutes.',
      'Mash dal partially for a creamy consistency.',
      'Heat ghee in a small pan. Add cumin and mustard seeds until they splutter.',
      'Add dried chilies, garlic, and asafoetida. Fry until garlic is golden.',
      'Add tomato and cook 2 minutes.',
      'Pour the tempering (tadka) over the dal. Garnish with cilantro and serve with rice.',
    ],
    tags: ['indian', 'vegetarian', 'lentils', 'comfort-food', 'dal'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 200,
      protein_g: 12,
      carbs_g: 28,
      fat_g: 6,
      fiber_g: 8,
      sugar_g: 3,
      sodium_mg: 320,
    },
  },
  {
    title: 'Biryani',
    description: 'Fragrant layered rice dish with spiced chicken, saffron, and crispy onions.',
    cuisine: 'Indian',
    prep_minutes: 40,
    cook_minutes: 40,
    servings: 8,
    calories: 450,
    ingredients: [
      { name: 'basmati rice', quantity: '2', unit: 'cups' },
      { name: 'chicken', quantity: '2', unit: 'lb, pieces' },
      { name: 'yogurt', quantity: '1', unit: 'cup' },
      { name: 'saffron', quantity: '1', unit: 'pinch, soaked in milk' },
      { name: 'ghee', quantity: '3', unit: 'tbsp' },
      { name: 'onion', quantity: '3', unit: 'large, sliced' },
      { name: 'ginger-garlic paste', quantity: '2', unit: 'tbsp' },
      { name: 'biryani masala', quantity: '2', unit: 'tbsp' },
      { name: 'mint', quantity: '1/4', unit: 'cup' },
      { name: 'cilantro', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Marinate chicken in yogurt, biryani masala, and ginger-garlic paste for 2 hours.',
      'Parboil basmati rice with whole spices until 70% done. Drain.',
      'Fry sliced onions in ghee until deep golden and crispy.',
      'Layer marinated chicken in a pot, top with parboiled rice.',
      'Drizzle saffron milk, add mint, cilantro, and crispy onions.',
      'Seal pot with dough or foil. Cook on low heat (dum) for 30 minutes.',
    ],
    tags: ['indian', 'rice', 'chicken', 'saffron', 'festive'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 450,
      protein_g: 30,
      carbs_g: 42,
      fat_g: 18,
      fiber_g: 2,
      sugar_g: 4,
      sodium_mg: 560,
    },
  },
  {
    title: 'Samosa',
    description: 'Crispy golden pastry triangles filled with spiced potatoes, peas, and cumin.',
    cuisine: 'Indian',
    prep_minutes: 30,
    cook_minutes: 15,
    servings: 8,
    calories: 180,
    ingredients: [
      { name: 'samosa wrappers', quantity: '16', unit: 'sheets' },
      { name: 'potato', quantity: '3', unit: 'medium, boiled & mashed' },
      { name: 'green peas', quantity: '1/2', unit: 'cup' },
      { name: 'cumin seeds', quantity: '1', unit: 'tsp' },
      { name: 'garam masala', quantity: '1', unit: 'tsp' },
      { name: 'amchur powder', quantity: '1/2', unit: 'tsp' },
      { name: 'green chili', quantity: '2', unit: 'minced' },
      { name: 'ginger', quantity: '1', unit: 'tsp, minced' },
      { name: 'cilantro', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Heat oil, add cumin seeds until they splutter. Add ginger and green chili.',
      'Add peas and cook 2 minutes. Add mashed potatoes, garam masala, and amchur.',
      'Mix well, add cilantro, and let filling cool completely.',
      'Cut wrappers into strips, form cones, fill with potato mixture, and seal.',
      'Deep fry at 325°F until golden and crispy.',
      'Serve with mint chutney and tamarind sauce.',
    ],
    tags: ['indian', 'vegetarian', 'appetizer', 'fried', 'street-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 180,
      protein_g: 4,
      carbs_g: 24,
      fat_g: 8,
      fiber_g: 3,
      sugar_g: 2,
      sodium_mg: 340,
    },
  },
  {
    title: 'Aloo Gobi',
    description: 'Dry curry of potatoes and cauliflower with turmeric, cumin, and green peas.',
    cuisine: 'Indian',
    prep_minutes: 15,
    cook_minutes: 20,
    servings: 4,
    calories: 220,
    ingredients: [
      { name: 'potato', quantity: '2', unit: 'medium, cubed' },
      { name: 'cauliflower', quantity: '1', unit: 'small, florets' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'tomato', quantity: '2', unit: 'diced' },
      { name: 'turmeric', quantity: '1/2', unit: 'tsp' },
      { name: 'cumin seeds', quantity: '1', unit: 'tsp' },
      { name: 'coriander powder', quantity: '1', unit: 'tsp' },
      { name: 'green peas', quantity: '1/4', unit: 'cup' },
      { name: 'ginger', quantity: '1', unit: 'tsp, grated' },
      { name: 'cilantro', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Heat oil, add cumin seeds until they splutter. Add onion and ginger.',
      'Add turmeric, coriander, and cook 1 minute.',
      'Add potato cubes and cauliflower florets. Toss to coat with spices.',
      'Add tomatoes, salt, and a splash of water. Cover and cook 15 minutes.',
      'Add green peas and cook 5 more minutes.',
      'Garnish with cilantro and serve with chapati or rice.',
    ],
    tags: ['indian', 'vegetarian', 'vegan', 'potato', 'cauliflower'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 220,
      protein_g: 6,
      carbs_g: 34,
      fat_g: 8,
      fiber_g: 6,
      sugar_g: 4,
      sodium_mg: 380,
    },
  },
  {
    title: 'Naan Bread',
    description:
      'Soft, pillowy Indian flatbread brushed with butter, cooked in a hot skillet or tandoor.',
    cuisine: 'Indian',
    prep_minutes: 15,
    cook_minutes: 10,
    servings: 8,
    calories: 160,
    ingredients: [
      { name: 'all-purpose flour', quantity: '3', unit: 'cups' },
      { name: 'yogurt', quantity: '1/4', unit: 'cup' },
      { name: 'warm water', quantity: '1/2', unit: 'cup' },
      { name: 'yeast', quantity: '1', unit: 'tsp' },
      { name: 'sugar', quantity: '1', unit: 'tsp' },
      { name: 'baking powder', quantity: '1/2', unit: 'tsp' },
      { name: 'butter', quantity: '2', unit: 'tbsp, melted' },
      { name: 'garlic', quantity: '2', unit: 'cloves, minced' },
      { name: 'cilantro', quantity: '1', unit: 'tbsp, chopped' },
    ],
    steps: [
      'Mix yeast, sugar, and warm water. Let proof for 10 minutes.',
      'Combine flour, yogurt, baking powder, salt, and yeast mixture. Knead 5 minutes.',
      'Let dough rise for 1 hour until doubled.',
      'Divide into 8 balls, roll into ovals.',
      'Cook on a hot cast-iron skillet until puffed and charred on both sides.',
      'Brush with garlic butter and sprinkle with cilantro. Serve immediately.',
    ],
    tags: ['indian', 'bread', 'naan', 'vegetarian', 'flatbread'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 160,
      protein_g: 4,
      carbs_g: 28,
      fat_g: 4,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 280,
    },
  },
  {
    title: 'Tandoori Chicken',
    description:
      'Yogurt-marinated chicken roasted with smoky tandoori spices until charred and juicy.',
    cuisine: 'Indian',
    prep_minutes: 15,
    cook_minutes: 30,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'whole chicken', quantity: '1', unit: '(3-4 lb), quartered' },
      { name: 'yogurt', quantity: '1', unit: 'cup' },
      { name: 'tandoori paste', quantity: '3', unit: 'tbsp' },
      { name: 'ginger-garlic paste', quantity: '1', unit: 'tbsp' },
      { name: 'lemon juice', quantity: '2', unit: 'tbsp' },
      { name: 'garam masala', quantity: '1', unit: 'tsp' },
      { name: 'red food coloring', quantity: '1', unit: 'drop' },
      { name: 'cilantro', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Make deep slashes in chicken pieces.',
      'Mix yogurt, tandoori paste, ginger-garlic, lemon juice, and garam masala.',
      'Coat chicken thoroughly in marinade. Refrigerate 4-8 hours.',
      'Roast at 475°F for 25-30 minutes until charred and cooked through.',
      'Baste with butter halfway through cooking.',
      'Garnish with cilantro and serve with mint chutney and naan.',
    ],
    tags: ['indian', 'chicken', 'tandoori', 'grilled', 'spicy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 38,
      carbs_g: 4,
      fat_g: 12,
      fiber_g: 0,
      sugar_g: 3,
      sodium_mg: 460,
    },
  },
  {
    title: 'Rogan Josh',
    description: 'Kashmiri slow-braised lamb curry with deep red chili, fennel, and yogurt.',
    cuisine: 'Indian',
    prep_minutes: 20,
    cook_minutes: 90,
    servings: 6,
    calories: 380,
    ingredients: [
      { name: 'lamb shoulder', quantity: '2', unit: 'lb, cubed' },
      { name: 'yogurt', quantity: '1/2', unit: 'cup' },
      { name: 'Kashmiri chili powder', quantity: '2', unit: 'tbsp' },
      { name: 'fennel seeds', quantity: '1', unit: 'tsp, ground' },
      { name: 'ginger', quantity: '1', unit: 'tbsp, grated' },
      { name: 'garam masala', quantity: '1', unit: 'tsp' },
      { name: 'onion', quantity: '2', unit: 'sliced' },
      { name: 'ghee', quantity: '2', unit: 'tbsp' },
      { name: 'cardamom', quantity: '3', unit: 'pods' },
      { name: 'cinnamon stick', quantity: '1', unit: 'inch piece' },
    ],
    steps: [
      'Brown lamb in ghee on all sides. Set aside.',
      'Sauté onions until golden. Add ginger and whole spices.',
      'Add Kashmiri chili and fennel, cook 1 minute.',
      'Return lamb, add yogurt and 2 cups water.',
      'Bring to boil, then simmer covered for 1.5 hours until lamb is tender.',
      'Add garam masala, adjust salt. Serve with steamed rice or naan.',
    ],
    tags: ['indian', 'curry', 'lamb', 'kashmiri', 'slow-cook'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 32,
      carbs_g: 6,
      fat_g: 24,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 520,
    },
  },
  {
    title: 'Masala Dosa',
    description:
      'Crispy fermented rice-lentil crepe filled with spiced potato masala and served with chutneys.',
    cuisine: 'Indian',
    prep_minutes: 20,
    cook_minutes: 10,
    servings: 6,
    calories: 220,
    ingredients: [
      { name: 'dosa batter', quantity: '3', unit: 'cups' },
      { name: 'potato', quantity: '4', unit: 'boiled, mashed' },
      { name: 'mustard seeds', quantity: '1', unit: 'tsp' },
      { name: 'urad dal', quantity: '1', unit: 'tsp' },
      { name: 'curry leaves', quantity: '8', unit: 'leaves' },
      { name: 'green chili', quantity: '2', unit: 'sliced' },
      { name: 'onion', quantity: '1', unit: 'sliced' },
      { name: 'turmeric', quantity: '1/4', unit: 'tsp' },
      { name: 'ghee', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Heat ghee, add mustard seeds and urad dal until they splutter.',
      'Add curry leaves, green chili, and onion. Sauté until onion is soft.',
      'Add turmeric and mashed potatoes. Mix well and season.',
      'Spread dosa batter thin on a hot griddle. Drizzle oil around edges.',
      'Cook until bottom is crispy and golden. Place potato filling in center.',
      'Fold dosa over filling and serve with coconut chutney and sambar.',
    ],
    tags: ['indian', 'south-indian', 'dosa', 'vegetarian', 'breakfast'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 220,
      protein_g: 6,
      carbs_g: 34,
      fat_g: 8,
      fiber_g: 3,
      sugar_g: 2,
      sodium_mg: 320,
    },
  },
  {
    title: 'Vindaloo',
    description: 'Fiery Goan pork curry with vinegar, garlic, and a blend of hot spices.',
    cuisine: 'Indian',
    prep_minutes: 20,
    cook_minutes: 60,
    servings: 6,
    calories: 360,
    ingredients: [
      { name: 'pork shoulder', quantity: '2', unit: 'lb, cubed' },
      { name: 'vinegar', quantity: '3', unit: 'tbsp' },
      { name: 'garlic', quantity: '6', unit: 'cloves, minced' },
      { name: 'ginger', quantity: '1', unit: 'tbsp, grated' },
      { name: 'Kashmiri chili', quantity: '6', unit: 'dried' },
      { name: 'cumin', quantity: '1', unit: 'tsp' },
      { name: 'mustard seeds', quantity: '1/2', unit: 'tsp' },
      { name: 'turmeric', quantity: '1/2', unit: 'tsp' },
      { name: 'onion', quantity: '2', unit: 'large, diced' },
      { name: 'cinnamon stick', quantity: '1', unit: 'small' },
    ],
    steps: [
      'Grind dried chilies, cumin, mustard seeds, and turmeric into a paste with vinegar.',
      'Marinate pork in the spice paste with garlic and ginger for 4 hours.',
      'Brown pork pieces in oil, set aside.',
      'Sauté onions until deep golden. Add cinnamon stick.',
      'Return pork with marinade and 1 cup water. Simmer covered 45-60 minutes.',
      'Adjust vinegar and salt. Serve with steamed rice.',
    ],
    tags: ['indian', 'goan', 'pork', 'spicy', 'curry'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 360,
      protein_g: 30,
      carbs_g: 8,
      fat_g: 22,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 480,
    },
  },
  {
    title: 'Malai Kofta',
    description: 'Deep-fried paneer and potato dumplings in a rich, creamy tomato-cashew sauce.',
    cuisine: 'Indian',
    prep_minutes: 30,
    cook_minutes: 25,
    servings: 6,
    calories: 340,
    ingredients: [
      { name: 'paneer', quantity: '8', unit: 'oz, grated' },
      { name: 'potato', quantity: '2', unit: 'medium, boiled & mashed' },
      { name: 'cashews', quantity: '1/4', unit: 'cup, soaked' },
      { name: 'tomato', quantity: '4', unit: 'large, pureed' },
      { name: 'cream', quantity: '1/2', unit: 'cup' },
      { name: 'garam masala', quantity: '1', unit: 'tsp' },
      { name: 'cornstarch', quantity: '2', unit: 'tbsp' },
      { name: 'raisins', quantity: '2', unit: 'tbsp' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
      { name: 'ginger-garlic paste', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Mix grated paneer, mashed potato, cornstarch, and salt. Form into balls with raisin centers.',
      'Deep fry kofta balls until golden. Set aside.',
      'Blend soaked cashews with a little water into a smooth paste.',
      'Sauté ginger-garlic in butter, add tomato puree and cook 15 minutes.',
      'Add cashew paste, cream, and garam masala. Simmer 10 minutes.',
      'Place kofta in serving dish, pour sauce over. Serve with naan.',
    ],
    tags: ['indian', 'vegetarian', 'paneer', 'creamy', 'festive'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 340,
      protein_g: 14,
      carbs_g: 18,
      fat_g: 24,
      fiber_g: 3,
      sugar_g: 6,
      sodium_mg: 460,
    },
  },
  {
    title: 'Raita',
    description:
      'Cool yogurt condiment with cucumber, cumin, and fresh herbs to balance spicy dishes.',
    cuisine: 'Indian',
    prep_minutes: 10,
    cook_minutes: 0,
    servings: 6,
    calories: 60,
    ingredients: [
      { name: 'yogurt', quantity: '2', unit: 'cups' },
      { name: 'cucumber', quantity: '1', unit: 'grated' },
      { name: 'cumin', quantity: '1/2', unit: 'tsp, roasted & ground' },
      { name: 'mint', quantity: '1', unit: 'tbsp, chopped' },
      { name: 'green chili', quantity: '1', unit: 'minced' },
      { name: 'salt', quantity: '1/2', unit: 'tsp' },
      { name: 'black pepper', quantity: '1/4', unit: 'tsp' },
    ],
    steps: [
      'Whisk yogurt until smooth.',
      'Squeeze excess water from grated cucumber.',
      'Mix cucumber into yogurt with cumin, mint, and green chili.',
      'Season with salt and black pepper.',
      'Chill for 30 minutes before serving.',
      'Serve as a cooling side with any spicy Indian dish.',
    ],
    tags: ['indian', 'vegetarian', 'yogurt', 'condiment', 'cooling'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 60,
      protein_g: 4,
      carbs_g: 6,
      fat_g: 2,
      fiber_g: 0,
      sugar_g: 4,
      sodium_mg: 180,
    },
  },
  {
    title: 'Gulab Jamun',
    description: 'Soft, spongy milk-solid dumplings soaked in fragrant rose-cardamom sugar syrup.',
    cuisine: 'Indian',
    prep_minutes: 20,
    cook_minutes: 15,
    servings: 8,
    calories: 200,
    ingredients: [
      { name: 'milk powder', quantity: '1', unit: 'cup' },
      { name: 'flour', quantity: '1/4', unit: 'cup' },
      { name: 'butter', quantity: '1', unit: 'tbsp, melted' },
      { name: 'milk', quantity: '1/4', unit: 'cup' },
      { name: 'sugar', quantity: '1.5', unit: 'cups' },
      { name: 'water', quantity: '1', unit: 'cup' },
      { name: 'rose water', quantity: '1', unit: 'tsp' },
      { name: 'cardamom', quantity: '1/4', unit: 'tsp, ground' },
      { name: 'saffron', quantity: '1', unit: 'pinch' },
      { name: 'ghee', quantity: '2', unit: 'cups for frying' },
    ],
    steps: [
      'Make sugar syrup: boil sugar and water, add rose water and cardamom. Set aside.',
      'Mix milk powder, flour, and butter. Add milk gradually to form a soft dough.',
      'Shape into smooth, crack-free balls.',
      'Fry in ghee at low heat (300°F) until deep golden all over.',
      'Immediately transfer hot jamuns into warm sugar syrup.',
      'Soak for at least 2 hours. Serve warm or at room temperature.',
    ],
    tags: ['indian', 'dessert', 'sweet', 'milk', 'festive'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 200,
      protein_g: 4,
      carbs_g: 36,
      fat_g: 6,
      fiber_g: 0,
      sugar_g: 28,
      sodium_mg: 120,
    },
  },
  {
    title: 'Pakora',
    description:
      'Crispy chickpea-flour fritters with onion, spinach, and aromatic spices, deep-fried golden.',
    cuisine: 'Indian',
    prep_minutes: 15,
    cook_minutes: 10,
    servings: 6,
    calories: 180,
    ingredients: [
      { name: 'besan (chickpea flour)', quantity: '1', unit: 'cup' },
      { name: 'onion', quantity: '2', unit: 'sliced thin' },
      { name: 'spinach', quantity: '1', unit: 'cup, chopped' },
      { name: 'green chili', quantity: '2', unit: 'minced' },
      { name: 'cumin seeds', quantity: '1', unit: 'tsp' },
      { name: 'turmeric', quantity: '1/4', unit: 'tsp' },
      { name: 'baking soda', quantity: '1/4', unit: 'tsp' },
      { name: 'cilantro', quantity: '2', unit: 'tbsp' },
      { name: 'water', quantity: '1/2', unit: 'cup' },
    ],
    steps: [
      'Mix besan, cumin, turmeric, baking soda, and salt.',
      'Add onion, spinach, green chili, and cilantro.',
      'Add water gradually to make a thick batter that coats the vegetables.',
      'Heat oil to 350°F. Drop spoonfuls of batter into the oil.',
      'Fry until golden and crispy on all sides, about 3-4 minutes.',
      'Drain on paper towels. Serve hot with mint chutney and tamarind sauce.',
    ],
    tags: ['indian', 'vegetarian', 'vegan', 'fritter', 'appetizer'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 180,
      protein_g: 6,
      carbs_g: 22,
      fat_g: 8,
      fiber_g: 4,
      sugar_g: 3,
      sodium_mg: 380,
    },
  },
  {
    title: 'Saag Aloo',
    description: 'Tender potato cubes simmered in a rich, spiced pureed spinach gravy.',
    cuisine: 'Indian',
    prep_minutes: 15,
    cook_minutes: 25,
    servings: 4,
    calories: 200,
    ingredients: [
      { name: 'potato', quantity: '3', unit: 'medium, cubed' },
      { name: 'fresh spinach', quantity: '1', unit: 'lb' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'ginger-garlic paste', quantity: '1', unit: 'tbsp' },
      { name: 'cumin seeds', quantity: '1', unit: 'tsp' },
      { name: 'garam masala', quantity: '1/2', unit: 'tsp' },
      { name: 'green chili', quantity: '2', unit: 'whole' },
      { name: 'oil', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Blanch spinach and blend into a puree.',
      'Fry cumin seeds in oil until they splutter. Add onion and ginger-garlic paste.',
      'Add potato cubes and cook 5 minutes, stirring.',
      'Add spinach puree, green chilies, and salt. Cover and simmer 20 minutes.',
      'Add garam masala and stir through.',
      'Serve hot with roti or steamed rice.',
    ],
    tags: ['indian', 'vegetarian', 'vegan', 'spinach', 'potato'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 200,
      protein_g: 8,
      carbs_g: 28,
      fat_g: 8,
      fiber_g: 6,
      sugar_g: 3,
      sodium_mg: 340,
    },
  },
  {
    title: 'Pani Puri',
    description:
      'Crispy hollow puri shells filled with spiced potato and dunked in tangy mint water.',
    cuisine: 'Indian',
    prep_minutes: 30,
    cook_minutes: 15,
    servings: 6,
    calories: 150,
    ingredients: [
      { name: 'puri shells', quantity: '30', unit: 'pieces' },
      { name: 'potato', quantity: '2', unit: 'boiled, mashed' },
      { name: 'chickpeas', quantity: '1/2', unit: 'cup, boiled' },
      { name: 'mint leaves', quantity: '1', unit: 'cup' },
      { name: 'cilantro', quantity: '1/2', unit: 'cup' },
      { name: 'green chili', quantity: '2', unit: 'whole' },
      { name: 'tamarind paste', quantity: '2', unit: 'tbsp' },
      { name: 'cumin powder', quantity: '1', unit: 'tsp' },
      { name: 'black salt', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Blend mint, cilantro, green chili, cumin, and black salt with water for pani.',
      'Add tamarind paste to the pani and chill.',
      'Mix mashed potato with chickpeas, cumin, and salt for the filling.',
      'Crack a small hole in each puri shell.',
      'Fill with potato mixture.',
      'Dunk into mint pani and eat in one bite!',
    ],
    tags: ['indian', 'street-food', 'snack', 'vegetarian', 'vegan'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 150,
      protein_g: 4,
      carbs_g: 24,
      fat_g: 4,
      fiber_g: 3,
      sugar_g: 4,
      sodium_mg: 420,
    },
  },
  {
    title: 'Korma',
    description: 'Mild, creamy curry with yogurt, nuts, and aromatic spices — rich and luxurious.',
    cuisine: 'Indian',
    prep_minutes: 20,
    cook_minutes: 30,
    servings: 6,
    calories: 360,
    ingredients: [
      { name: 'chicken', quantity: '1.5', unit: 'lb, cubed' },
      { name: 'yogurt', quantity: '1', unit: 'cup' },
      { name: 'cashews', quantity: '1/4', unit: 'cup, ground' },
      { name: 'almonds', quantity: '1/4', unit: 'cup, ground' },
      { name: 'cream', quantity: '1/4', unit: 'cup' },
      { name: 'onion', quantity: '2', unit: 'sliced' },
      { name: 'ginger-garlic paste', quantity: '1', unit: 'tbsp' },
      { name: 'garam masala', quantity: '1', unit: 'tsp' },
      { name: 'cardamom', quantity: '3', unit: 'pods' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Marinate chicken in yogurt, salt, and garam masala for 1 hour.',
      'Sauté onions in butter until golden. Add ginger-garlic paste and cardamom.',
      'Add ground cashews and almonds, cook 2 minutes.',
      'Add marinated chicken and cook until no longer pink.',
      'Add cream and simmer 15 minutes until thick and rich.',
      'Adjust seasoning and serve with naan or rice.',
    ],
    tags: ['indian', 'curry', 'chicken', 'creamy', 'mild'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 360,
      protein_g: 30,
      carbs_g: 10,
      fat_g: 24,
      fiber_g: 2,
      sugar_g: 4,
      sodium_mg: 480,
    },
  },
];

export const indianRecipes = generateCuisineRecipes(configs);

// ── Additional Indian recipes ──────────────────────────────────────────────

const additionalIndianConfigs: CuisineRecipeConfig[] = [
  {
    title: 'Aloo Gobi',
    description: 'Dry curry of potatoes and cauliflower with turmeric, cumin, and cilantro.',
    cuisine: 'Indian',
    prep_minutes: 15,
    cook_minutes: 20,
    servings: 4,
    calories: 180,
    ingredients: [
      { name: 'potato', quantity: '2', unit: 'cubed' },
      { name: 'cauliflower', quantity: '1', unit: 'small, florets' },
      { name: 'turmeric', quantity: '1', unit: 'tsp' },
      { name: 'cumin seeds', quantity: '1', unit: 'tsp' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'tomato', quantity: '1', unit: 'diced' },
      { name: 'cilantro', quantity: '1/4', unit: 'cup' },
      { name: 'ginger-garlic paste', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Temper cumin seeds in oil.',
      'Add onion and ginger-garlic paste. Sauté.',
      'Add turmeric, potato, and cauliflower.',
      'Add tomato, cover and cook until vegetables are tender.',
      'Season with garam masala, salt, and cilantro.',
      'Serve with roti or rice.',
    ],
    tags: ['indian', 'vegetarian', 'potato', 'cauliflower', 'dry-curry'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 180,
      protein_g: 6,
      carbs_g: 28,
      fat_g: 6,
      fiber_g: 4,
      sugar_g: 3,
      sodium_mg: 380,
    },
  },
  {
    title: 'Saag Paneer',
    description: 'Creamy spinach curry with cubes of paneer cheese and aromatic spices.',
    cuisine: 'Indian',
    prep_minutes: 10,
    cook_minutes: 20,
    servings: 4,
    calories: 260,
    ingredients: [
      { name: 'paneer', quantity: '8', unit: 'oz, cubed' },
      { name: 'spinach', quantity: '1', unit: 'lb, blanched & puréed' },
      { name: 'cream', quantity: '1/4', unit: 'cup' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'ginger-garlic paste', quantity: '1', unit: 'tbsp' },
      { name: 'garam masala', quantity: '1', unit: 'tsp' },
      { name: 'cumin', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Pan-fry paneer until golden.',
      'Sauté onion and ginger-garlic paste.',
      'Add cumin, garam masala, and puréed spinach.',
      'Add cream and simmer 10 minutes.',
      'Add paneer cubes.',
      'Serve with naan or rice.',
    ],
    tags: ['indian', 'vegetarian', 'spinach', 'paneer', 'creamy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 260,
      protein_g: 14,
      carbs_g: 8,
      fat_g: 18,
      fiber_g: 3,
      sugar_g: 2,
      sodium_mg: 480,
    },
  },
  {
    title: 'Chana Masala',
    description: 'Spiced chickpea curry with tomatoes, amchur, and garam masala.',
    cuisine: 'Indian',
    prep_minutes: 10,
    cook_minutes: 25,
    servings: 4,
    calories: 220,
    ingredients: [
      { name: 'chickpeas', quantity: '2', unit: 'cans, drained' },
      { name: 'tomato', quantity: '3', unit: 'diced' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'ginger-garlic paste', quantity: '1', unit: 'tbsp' },
      { name: 'garam masala', quantity: '1', unit: 'tsp' },
      { name: 'cumin', quantity: '1', unit: 'tsp' },
      { name: 'amchur (mango powder)', quantity: '1/2', unit: 'tsp' },
      { name: 'cilantro', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Sauté onion and ginger-garlic paste.',
      'Add cumin, garam masala, and tomato.',
      'Cook until tomatoes break down.',
      'Add chickpeas and water. Simmer 20 minutes.',
      'Add amchur for tanginess.',
      'Garnish with cilantro and serve with rice.',
    ],
    tags: ['indian', 'vegetarian', 'vegan', 'chickpea', 'curry'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 220,
      protein_g: 10,
      carbs_g: 32,
      fat_g: 6,
      fiber_g: 8,
      sugar_g: 4,
      sodium_mg: 480,
    },
  },
  {
    title: 'Biryani (Vegetable)',
    description: 'Fragrant layered rice with spiced vegetables, saffron, and fried onions.',
    cuisine: 'Indian',
    prep_minutes: 25,
    cook_minutes: 40,
    servings: 6,
    calories: 380,
    ingredients: [
      { name: 'basmati rice', quantity: '2', unit: 'cups' },
      { name: 'mixed vegetables', quantity: '2', unit: 'cups' },
      { name: 'yogurt', quantity: '1/2', unit: 'cup' },
      { name: 'saffron', quantity: '1', unit: 'pinch, in warm milk' },
      { name: 'fried onion', quantity: '1', unit: 'cup' },
      { name: 'garam masala', quantity: '1', unit: 'tsp' },
      { name: 'mint', quantity: '2', unit: 'tbsp' },
      { name: 'cilantro', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Parboil rice with whole spices.',
      'Cook vegetables with yogurt and spices.',
      'Layer rice and vegetables in a pot.',
      'Add saffron milk, fried onions, mint, and cilantro.',
      'Seal and steam (dum) for 20 minutes.',
      'Mix gently before serving.',
    ],
    tags: ['indian', 'vegetarian', 'rice', 'saffron', 'biryani'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 10,
      carbs_g: 56,
      fat_g: 12,
      fiber_g: 4,
      sugar_g: 4,
      sodium_mg: 480,
    },
  },
  {
    title: 'Pav Bhaji',
    description:
      'Spiced mashed vegetable curry served with buttered bread rolls — Mumbai street food.',
    cuisine: 'Indian',
    prep_minutes: 15,
    cook_minutes: 25,
    servings: 4,
    calories: 340,
    ingredients: [
      {
        name: 'mixed vegetables (potato, cauliflower, peas)',
        quantity: '3',
        unit: 'cups, boiled & mashed',
      },
      { name: 'pav bhaji masala', quantity: '2', unit: 'tbsp' },
      { name: 'tomato', quantity: '3', unit: 'diced' },
      { name: 'butter', quantity: '3', unit: 'tbsp' },
      { name: 'pav bread rolls', quantity: '8', unit: 'pieces' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'cilantro', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Sauté onion in butter. Add tomato and pav bhaji masala.',
      'Add mashed vegetables and water. Simmer 15 minutes.',
      'Mash everything together until smooth.',
      'Toast pav rolls in butter.',
      'Serve bhaji with a pat of butter and cilantro.',
      'Dip the bread in the curry!',
    ],
    tags: ['indian', 'street-food', 'vegetarian', 'mumbai', 'bread'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 340,
      protein_g: 8,
      carbs_g: 44,
      fat_g: 14,
      fiber_g: 4,
      sugar_g: 6,
      sodium_mg: 680,
    },
  },
  {
    title: 'Raita',
    description: 'Cooling yogurt side dish with cucumber, cumin, and mint.',
    cuisine: 'Indian',
    prep_minutes: 10,
    cook_minutes: 0,
    servings: 6,
    calories: 60,
    ingredients: [
      { name: 'yogurt', quantity: '2', unit: 'cups' },
      { name: 'cucumber', quantity: '1', unit: 'grated' },
      { name: 'cumin', quantity: '1/2', unit: 'tsp, roasted & ground' },
      { name: 'mint', quantity: '1', unit: 'tbsp, chopped' },
      { name: 'black salt', quantity: '1/4', unit: 'tsp' },
    ],
    steps: [
      'Whisk yogurt until smooth.',
      'Grate cucumber, squeeze out excess water.',
      'Add cucumber, cumin, mint, and salt to yogurt.',
      'Chill for 30 minutes.',
      'Serve alongside spicy dishes.',
    ],
    tags: ['indian', 'yogurt', 'side', 'cooling', 'vegetarian'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 60,
      protein_g: 4,
      carbs_g: 4,
      fat_g: 3,
      fiber_g: 0,
      sugar_g: 3,
      sodium_mg: 180,
    },
  },
  {
    title: 'Masala Dosa',
    description:
      'Crispy rice-lentil crepe filled with spiced potato, served with sambar and chutney.',
    cuisine: 'Indian',
    prep_minutes: 20,
    cook_minutes: 10,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'dosa batter', quantity: '2', unit: 'cups (rice-lentil fermented)' },
      { name: 'potato', quantity: '3', unit: 'mashed & spiced' },
      { name: 'mustard seeds', quantity: '1/2', unit: 'tsp' },
      { name: 'curry leaves', quantity: '6', unit: 'leaves' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'turmeric', quantity: '1/4', unit: 'tsp' },
      { name: 'ghee', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Make potato filling: temper mustard seeds and curry leaves, add onion, turmeric, and mashed potato.',
      'Heat a flat griddle. Pour dosa batter, spread thin.',
      'Drizzle ghee around edges. Cook until crispy.',
      'Place potato filling in the center. Fold.',
      'Serve with coconut chutney and sambar.',
    ],
    tags: ['indian', 'dosa', 'breakfast', 'south-indian', 'vegetarian'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 8,
      carbs_g: 42,
      fat_g: 8,
      fiber_g: 3,
      sugar_g: 2,
      sodium_mg: 380,
    },
  },
  {
    title: 'Vada Pav',
    description: "Mumbai's favorite street food — spiced potato fritter in a bun with chutneys.",
    cuisine: 'Indian',
    prep_minutes: 20,
    cook_minutes: 8,
    servings: 6,
    calories: 240,
    ingredients: [
      { name: 'potato', quantity: '4', unit: 'mashed' },
      { name: 'green chili', quantity: '2', unit: 'minced' },
      { name: 'garlic', quantity: '3', unit: 'cloves' },
      { name: 'besan (chickpea flour)', quantity: '1/2', unit: 'cup' },
      { name: 'pav buns', quantity: '6', unit: 'pieces' },
      { name: 'tamarind chutney', quantity: '1/4', unit: 'cup' },
      { name: 'green chutney', quantity: '1/4', unit: 'cup' },
      { name: 'oil', quantity: '2', unit: 'cups, for frying' },
    ],
    steps: [
      'Mix mashed potato with green chili, garlic, turmeric, and salt.',
      'Form into balls and flatten slightly.',
      'Dip in besan batter.',
      'Deep fry until golden and crispy.',
      'Place vada in a pav bun with tamarind and green chutney.',
      'Serve immediately.',
    ],
    tags: ['indian', 'street-food', 'potato', 'mumbai', 'vegetarian'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 240,
      protein_g: 6,
      carbs_g: 36,
      fat_g: 8,
      fiber_g: 3,
      sugar_g: 4,
      sodium_mg: 580,
    },
  },
  {
    title: 'Rasgulla',
    description: 'Soft spongy cheese balls soaked in cardamom-scented sugar syrup.',
    cuisine: 'Indian',
    prep_minutes: 20,
    cook_minutes: 25,
    servings: 8,
    calories: 140,
    ingredients: [
      { name: 'milk', quantity: '1', unit: 'gallon (for chhena)' },
      { name: 'sugar', quantity: '1.5', unit: 'cups' },
      { name: 'cardamom', quantity: '4', unit: 'pods, crushed' },
      { name: 'lemon juice', quantity: '3', unit: 'tbsp (for curdling)' },
    ],
    steps: [
      'Curdle milk with lemon juice to make chhena (paneer).',
      'Knead chhena until very smooth.',
      'Roll into small balls.',
      'Make sugar syrup with cardamom.',
      'Boil rasgulla in syrup for 15-20 minutes until puffy.',
      'Chill and serve in the syrup.',
    ],
    tags: ['indian', 'dessert', 'bengali', 'cheese', 'sweet'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 140,
      protein_g: 4,
      carbs_g: 28,
      fat_g: 2,
      fiber_g: 0,
      sugar_g: 24,
      sodium_mg: 40,
    },
  },
  {
    title: 'Kadhi',
    description:
      'Tangy yogurt-based curry with besan dumplings, tempered with cumin and curry leaves.',
    cuisine: 'Indian',
    prep_minutes: 15,
    cook_minutes: 25,
    servings: 4,
    calories: 180,
    ingredients: [
      { name: 'yogurt', quantity: '2', unit: 'cups, whisked' },
      { name: 'besan (chickpea flour)', quantity: '1/2', unit: 'cup' },
      { name: 'turmeric', quantity: '1/2', unit: 'tsp' },
      { name: 'mustard seeds', quantity: '1/2', unit: 'tsp' },
      { name: 'curry leaves', quantity: '6', unit: 'leaves' },
      { name: 'dried red chili', quantity: '2', unit: 'whole' },
      { name: 'pakora dumplings', quantity: '8', unit: 'pieces' },
    ],
    steps: [
      'Whisk yogurt with besan, turmeric, and water.',
      'Bring to a simmer, stirring constantly to prevent curdling.',
      'Add pakora dumplings.',
      'Make temper: fry mustard seeds, curry leaves, and dried chili in ghee.',
      'Pour temper over kadhi.',
      'Serve with steamed rice.',
    ],
    tags: ['indian', 'curry', 'yogurt', 'vegetarian', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 180,
      protein_g: 8,
      carbs_g: 16,
      fat_g: 8,
      fiber_g: 2,
      sugar_g: 4,
      sodium_mg: 380,
    },
  },
];

// ── Batch 3: Additional Indian recipes ──────────────────────────────────────

const indianBatch3Configs: CuisineRecipeConfig[] = [
  {
    title: 'Idli',
    description:
      'Steamed fermented rice and lentil cakes, a staple South Indian breakfast served with chutney and sambar.',
    cuisine: 'Indian',
    prep_minutes: 480,
    cook_minutes: 15,
    servings: 8,
    calories: 130,
    ingredients: [
      { name: 'rice', quantity: '2', unit: 'cups' },
      { name: 'urad dal', quantity: '1', unit: 'cup' },
      { name: 'fenugreek seeds', quantity: '1/2', unit: 'tsp' },
      { name: 'salt', quantity: '1', unit: 'tsp' },
      { name: 'water', quantity: '1', unit: 'cup' },
    ],
    steps: [
      'Soak rice and urad dal separately for 6-8 hours.',
      'Grind urad dal to a smooth batter, then grind rice coarsely.',
      'Mix both batters, add fenugreek seeds and salt. Ferment overnight.',
      'Grease idli molds and pour batter into each cavity.',
      'Steam for 12-15 minutes until a toothpick comes out clean.',
      'Serve hot with coconut chutney and sambar.',
    ],
    tags: ['indian', 'south-indian', 'breakfast', 'steamed', 'fermented'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 130,
      protein_g: 4,
      carbs_g: 26,
      fat_g: 1,
      fiber_g: 2,
      sugar_g: 0,
      sodium_mg: 180,
    },
  },
  {
    title: 'Dal Makhani',
    description:
      'Rich, creamy black lentil curry slow-cooked with butter, cream, and aromatic spices.',
    cuisine: 'Indian',
    prep_minutes: 30,
    cook_minutes: 120,
    servings: 6,
    calories: 320,
    ingredients: [
      { name: 'whole black lentils', quantity: '1', unit: 'cup' },
      { name: 'kidney beans', quantity: '1/4', unit: 'cup' },
      { name: 'butter', quantity: '3', unit: 'tbsp' },
      { name: 'tomato puree', quantity: '1', unit: 'cup' },
      { name: 'heavy cream', quantity: '1/4', unit: 'cup' },
      { name: 'ginger-garlic paste', quantity: '1', unit: 'tbsp' },
      { name: 'garam masala', quantity: '1', unit: 'tsp' },
      { name: 'cumin seeds', quantity: '1', unit: 'tsp' },
      { name: 'kasuri methi', quantity: '1', unit: 'tsp' },
      { name: 'salt', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Soak black lentils and kidney beans overnight. Boil until very soft.',
      'Melt butter, add cumin seeds and ginger-garlic paste. Cook until fragrant.',
      'Add tomato puree and cook until oil separates.',
      'Add boiled lentils, mash some for creaminess. Simmer 1 hour.',
      'Add garam masala, kasuri methi, and cream. Stir well.',
      'Simmer 15 more minutes. Serve with naan or rice.',
    ],
    tags: ['indian', 'dal', 'lentil', 'creamy', 'slow-cooked'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 14,
      carbs_g: 32,
      fat_g: 16,
      fiber_g: 10,
      sugar_g: 4,
      sodium_mg: 420,
    },
  },
  {
    title: 'Chicken Korma',
    description:
      'Mild, creamy chicken curry with yogurt, ground nuts, and fragrant Mughlai spices.',
    cuisine: 'Indian',
    prep_minutes: 20,
    cook_minutes: 35,
    servings: 6,
    calories: 420,
    ingredients: [
      { name: 'chicken thigh', quantity: '1.5', unit: 'lb, cubed' },
      { name: 'yogurt', quantity: '1/2', unit: 'cup' },
      { name: 'cashew paste', quantity: '3', unit: 'tbsp' },
      { name: 'onion', quantity: '2', unit: 'sliced' },
      { name: 'ginger-garlic paste', quantity: '1', unit: 'tbsp' },
      { name: 'garam masala', quantity: '1', unit: 'tsp' },
      { name: 'coriander powder', quantity: '1', unit: 'tsp' },
      { name: 'heavy cream', quantity: '1/4', unit: 'cup' },
      { name: 'oil', quantity: '2', unit: 'tbsp' },
      { name: 'saffron', quantity: 'pinch', unit: '' },
    ],
    steps: [
      'Marinate chicken in yogurt, salt, and garam masala for 30 minutes.',
      'Fry sliced onions until deep golden. Blend into a paste.',
      'Heat oil, add ginger-garlic paste and onion paste. Cook 5 minutes.',
      'Add coriander powder and cashew paste. Stir well.',
      'Add marinated chicken and cook until sealed on all sides.',
      'Add cream and saffron. Simmer 20 minutes until chicken is cooked through.',
    ],
    tags: ['indian', 'curry', 'chicken', 'mughlai', 'creamy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 30,
      carbs_g: 14,
      fat_g: 28,
      fiber_g: 2,
      sugar_g: 6,
      sodium_mg: 520,
    },
  },
  {
    title: 'Pongal',
    description:
      'Comforting South Indian rice and lentil porridge seasoned with black pepper, cumin, and ghee.',
    cuisine: 'Indian',
    prep_minutes: 10,
    cook_minutes: 25,
    servings: 4,
    calories: 250,
    ingredients: [
      { name: 'rice', quantity: '1', unit: 'cup' },
      { name: 'moong dal', quantity: '1/2', unit: 'cup' },
      { name: 'ghee', quantity: '3', unit: 'tbsp' },
      { name: 'black pepper', quantity: '1', unit: 'tsp, crushed' },
      { name: 'cumin seeds', quantity: '1', unit: 'tsp' },
      { name: 'ginger', quantity: '1', unit: 'inch, minced' },
      { name: 'cashews', quantity: '2', unit: 'tbsp' },
      { name: 'curry leaves', quantity: '8', unit: 'leaves' },
      { name: 'salt', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Dry-roast moong dal until fragrant. Wash rice and dal together.',
      'Cook rice and dal with 4 cups water until soft and mushy.',
      'Heat ghee, add cumin, pepper, ginger, and curry leaves. Temper.',
      'Add cashews and fry until golden.',
      'Pour tempering over the cooked rice-dal mixture. Mix well.',
      'Add salt and serve hot with coconut chutney.',
    ],
    tags: ['indian', 'south-indian', 'breakfast', 'comfort-food', 'rice'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 250,
      protein_g: 8,
      carbs_g: 36,
      fat_g: 9,
      fiber_g: 3,
      sugar_g: 1,
      sodium_mg: 290,
    },
  },
  {
    title: 'Fish Curry',
    description:
      'Tangy and spicy coastal fish curry simmered in coconut milk with tamarind and curry leaves.',
    cuisine: 'Indian',
    prep_minutes: 15,
    cook_minutes: 20,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'white fish fillets', quantity: '1', unit: 'lb' },
      { name: 'coconut milk', quantity: '1', unit: 'can' },
      { name: 'tamarind paste', quantity: '1', unit: 'tbsp' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'tomato', quantity: '2', unit: 'diced' },
      { name: 'ginger-garlic paste', quantity: '1', unit: 'tbsp' },
      { name: 'curry leaves', quantity: '10', unit: 'leaves' },
      { name: 'mustard seeds', quantity: '1', unit: 'tsp' },
      { name: 'turmeric', quantity: '1/2', unit: 'tsp' },
      { name: 'red chili powder', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Marinate fish with turmeric and salt for 10 minutes.',
      'Heat oil, add mustard seeds and curry leaves. Let them splutter.',
      'Add onion and ginger-garlic paste. Sauté until golden.',
      'Add tomatoes, chili powder, and tamarind. Cook 5 minutes.',
      'Add coconut milk and bring to a gentle simmer.',
      'Add fish fillets, cook 8-10 minutes until fish is flaky. Serve with rice.',
    ],
    tags: ['indian', 'fish', 'coastal', 'coconut', 'curry'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 280,
      protein_g: 28,
      carbs_g: 10,
      fat_g: 16,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 450,
    },
  },
  {
    title: 'Aloo Paratha',
    description:
      'Stuffed whole wheat flatbread filled with spiced mashed potatoes, served with yogurt and pickle.',
    cuisine: 'Indian',
    prep_minutes: 25,
    cook_minutes: 20,
    servings: 6,
    calories: 220,
    ingredients: [
      { name: 'whole wheat flour', quantity: '2', unit: 'cups' },
      { name: 'potato', quantity: '3', unit: 'medium, boiled' },
      { name: 'green chili', quantity: '2', unit: 'minced' },
      { name: 'cumin seeds', quantity: '1', unit: 'tsp' },
      { name: 'coriander', quantity: '2', unit: 'tbsp, chopped' },
      { name: 'ghee', quantity: '2', unit: 'tbsp' },
      { name: 'amchur', quantity: '1/2', unit: 'tsp' },
      { name: 'salt', quantity: '1', unit: 'tsp' },
      { name: 'water', quantity: '1/2', unit: 'cup' },
    ],
    steps: [
      'Mash boiled potatoes with green chili, cumin, coriander, amchur, and salt.',
      'Make dough with flour, water, and a tablespoon of ghee. Rest 15 minutes.',
      'Divide dough into balls. Flatten each, place potato filling in center.',
      'Seal edges and roll out into a round paratha.',
      'Cook on a hot griddle with ghee until golden on both sides.',
      'Serve hot with yogurt, pickle, or butter.',
    ],
    tags: ['indian', 'bread', 'breakfast', 'stuffed', 'potato'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 220,
      protein_g: 6,
      carbs_g: 34,
      fat_g: 7,
      fiber_g: 4,
      sugar_g: 1,
      sodium_mg: 340,
    },
  },
  {
    title: 'Matar Paneer',
    description:
      'Classic North Indian curry of green peas and paneer in a rich tomato-onion gravy.',
    cuisine: 'Indian',
    prep_minutes: 15,
    cook_minutes: 25,
    servings: 4,
    calories: 310,
    ingredients: [
      { name: 'paneer', quantity: '8', unit: 'oz, cubed' },
      { name: 'green peas', quantity: '1', unit: 'cup' },
      { name: 'tomato', quantity: '3', unit: 'pureed' },
      { name: 'onion', quantity: '2', unit: 'diced' },
      { name: 'ginger-garlic paste', quantity: '1', unit: 'tbsp' },
      { name: 'garam masala', quantity: '1', unit: 'tsp' },
      { name: 'coriander powder', quantity: '1', unit: 'tsp' },
      { name: 'heavy cream', quantity: '2', unit: 'tbsp' },
      { name: 'oil', quantity: '2', unit: 'tbsp' },
      { name: 'cumin seeds', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Pan-fry paneer cubes until golden. Set aside.',
      'Heat oil, add cumin seeds. Add onion and cook until golden.',
      'Add ginger-garlic paste, cook 1 minute.',
      'Add tomato puree, coriander powder, and garam masala. Cook until oil separates.',
      'Add peas and 1/2 cup water. Simmer 10 minutes.',
      'Add paneer and cream. Simmer 5 minutes. Serve with naan.',
    ],
    tags: ['indian', 'curry', 'paneer', 'peas', 'vegetarian'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 310,
      protein_g: 14,
      carbs_g: 18,
      fat_g: 20,
      fiber_g: 4,
      sugar_g: 6,
      sodium_mg: 460,
    },
  },
  {
    title: 'Egg Curry',
    description:
      'Hard-boiled eggs simmered in a spiced onion-tomato gravy with aromatic Indian spices.',
    cuisine: 'Indian',
    prep_minutes: 10,
    cook_minutes: 25,
    servings: 4,
    calories: 260,
    ingredients: [
      { name: 'egg', quantity: '6', unit: 'hard-boiled' },
      { name: 'onion', quantity: '2', unit: 'diced' },
      { name: 'tomato', quantity: '2', unit: 'pureed' },
      { name: 'ginger-garlic paste', quantity: '1', unit: 'tbsp' },
      { name: 'garam masala', quantity: '1', unit: 'tsp' },
      { name: 'turmeric', quantity: '1/2', unit: 'tsp' },
      { name: 'red chili powder', quantity: '1', unit: 'tsp' },
      { name: 'coriander powder', quantity: '1', unit: 'tsp' },
      { name: 'oil', quantity: '2', unit: 'tbsp' },
      { name: 'cilantro', quantity: '2', unit: 'tbsp, chopped' },
    ],
    steps: [
      'Peel hard-boiled eggs and lightly fry in oil until golden. Set aside.',
      'In the same pan, sauté onions until deep golden.',
      'Add ginger-garlic paste and cook 1 minute.',
      'Add tomato puree, turmeric, chili powder, coriander, and garam masala.',
      'Cook until oil separates from the masala. Add 1/2 cup water.',
      'Add eggs, simmer 10 minutes. Garnish with cilantro. Serve with rice.',
    ],
    tags: ['indian', 'egg', 'curry', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 260,
      protein_g: 16,
      carbs_g: 10,
      fat_g: 18,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 410,
    },
  },
  {
    title: 'Upma',
    description:
      'Savory semolina porridge tempered with mustard seeds, curry leaves, and vegetables.',
    cuisine: 'Indian',
    prep_minutes: 10,
    cook_minutes: 15,
    servings: 4,
    calories: 190,
    ingredients: [
      { name: 'semolina', quantity: '1', unit: 'cup' },
      { name: 'mustard seeds', quantity: '1', unit: 'tsp' },
      { name: 'urad dal', quantity: '1', unit: 'tbsp' },
      { name: 'curry leaves', quantity: '8', unit: 'leaves' },
      { name: 'green chili', quantity: '2', unit: 'slit' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'carrot', quantity: '1/2', unit: 'cup, diced' },
      { name: 'peas', quantity: '1/4', unit: 'cup' },
      { name: 'ghee', quantity: '1', unit: 'tbsp' },
      { name: 'water', quantity: '2.5', unit: 'cups' },
    ],
    steps: [
      'Dry-roast semolina in a pan until lightly golden. Set aside.',
      'Heat ghee, add mustard seeds and urad dal. Let them splutter.',
      'Add curry leaves, green chili, and onion. Sauté until soft.',
      'Add carrot, peas, and water. Bring to a boil.',
      'Slowly add roasted semolina, stirring continuously to avoid lumps.',
      'Cover and cook 3-4 minutes. Fluff and serve with coconut chutney.',
    ],
    tags: ['indian', 'south-indian', 'breakfast', 'semolina', 'quick'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 190,
      protein_g: 5,
      carbs_g: 30,
      fat_g: 6,
      fiber_g: 3,
      sugar_g: 2,
      sodium_mg: 250,
    },
  },
  {
    title: 'Paneer Tikka',
    description:
      'Chargrilled marinated paneer cubes with bell peppers and onions, cooked in a tandoor or oven.',
    cuisine: 'Indian',
    prep_minutes: 30,
    cook_minutes: 15,
    servings: 4,
    calories: 290,
    ingredients: [
      { name: 'paneer', quantity: '10', unit: 'oz, cubed' },
      { name: 'yogurt', quantity: '1/2', unit: 'cup' },
      { name: 'bell pepper', quantity: '1', unit: 'cubed' },
      { name: 'onion', quantity: '1', unit: 'cubed' },
      { name: 'tandoori spice', quantity: '1', unit: 'tbsp' },
      { name: 'ginger-garlic paste', quantity: '1', unit: 'tbsp' },
      { name: 'lemon juice', quantity: '1', unit: 'tbsp' },
      { name: 'chickpea flour', quantity: '1', unit: 'tbsp' },
      { name: 'oil', quantity: '1', unit: 'tbsp' },
      { name: 'chaat masala', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Whisk yogurt with tandoori spice, ginger-garlic paste, lemon juice, and chickpea flour.',
      'Marinate paneer and vegetables in the mixture for 30 minutes.',
      'Thread paneer and vegetables onto skewers.',
      'Grill or broil on high heat, turning occasionally, until charred.',
      'Baste with oil while cooking.',
      'Sprinkle with chaat masala and serve with mint chutney.',
    ],
    tags: ['indian', 'paneer', 'tandoor', 'appetizer', 'grilled'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 290,
      protein_g: 14,
      carbs_g: 12,
      fat_g: 20,
      fiber_g: 2,
      sugar_g: 4,
      sodium_mg: 480,
    },
  },
  {
    title: 'Bhindi Masala',
    description:
      'Crispy okra stir-fried with onions, tomatoes, and aromatic dry spices — a classic dry curry.',
    cuisine: 'Indian',
    prep_minutes: 15,
    cook_minutes: 20,
    servings: 4,
    calories: 160,
    ingredients: [
      { name: 'okra', quantity: '1', unit: 'lb, sliced' },
      { name: 'onion', quantity: '1', unit: 'sliced' },
      { name: 'tomato', quantity: '1', unit: 'diced' },
      { name: 'cumin seeds', quantity: '1', unit: 'tsp' },
      { name: 'coriander powder', quantity: '1', unit: 'tsp' },
      { name: 'turmeric', quantity: '1/2', unit: 'tsp' },
      { name: 'amchur', quantity: '1/2', unit: 'tsp' },
      { name: 'green chili', quantity: '1', unit: 'slit' },
      { name: 'oil', quantity: '2', unit: 'tbsp' },
      { name: 'salt', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Dry-roast okra slices in a pan until slime disappears. Set aside.',
      'Heat oil, add cumin seeds and green chili.',
      'Add onion and cook until golden.',
      'Add tomato, turmeric, and coriander powder. Cook 3 minutes.',
      'Add roasted okra, amchur, and salt. Toss gently.',
      'Cook 5 minutes on medium heat. Serve with roti.',
    ],
    tags: ['indian', 'okra', 'dry-curry', 'vegetarian', 'side-dish'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 160,
      protein_g: 4,
      carbs_g: 14,
      fat_g: 10,
      fiber_g: 5,
      sugar_g: 3,
      sodium_mg: 280,
    },
  },
];

// ── Batch 4: More Indian recipes ────────────────────────────────────────────

const indianBatch4Configs: CuisineRecipeConfig[] = [
  {
    title: 'Lamb Keema',
    description:
      'Spiced ground lamb curry with peas, cooked in aromatic masala — a hearty, flavorful dish.',
    cuisine: 'Indian',
    prep_minutes: 10,
    cook_minutes: 30,
    servings: 4,
    calories: 340,
    ingredients: [
      { name: 'ground lamb', quantity: '1', unit: 'lb' },
      { name: 'green peas', quantity: '1/2', unit: 'cup' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'tomato', quantity: '2', unit: 'diced' },
      { name: 'ginger-garlic paste', quantity: '1', unit: 'tbsp' },
      { name: 'garam masala', quantity: '1', unit: 'tsp' },
      { name: 'cumin powder', quantity: '1', unit: 'tsp' },
      { name: 'coriander powder', quantity: '1', unit: 'tsp' },
      { name: 'oil', quantity: '2', unit: 'tbsp' },
      { name: 'cilantro', quantity: '2', unit: 'tbsp, chopped' },
    ],
    steps: [
      'Heat oil, add onion and cook until golden.',
      'Add ginger-garlic paste, cook 1 minute.',
      'Add ground lamb and brown, breaking up lumps.',
      'Add tomato, cumin, coriander, and garam masala. Cook 10 minutes.',
      'Add peas and 1/4 cup water. Simmer until peas are tender.',
      'Garnish with cilantro. Serve with naan or rice.',
    ],
    tags: ['indian', 'lamb', 'keema', 'curry', 'ground-meat'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 340,
      protein_g: 24,
      carbs_g: 10,
      fat_g: 22,
      fiber_g: 3,
      sugar_g: 3,
      sodium_mg: 490,
    },
  },
  {
    title: 'Uttapam',
    description:
      'Thick, savory rice-lentil pancake topped with onions, tomatoes, and chilies — a South Indian specialty.',
    cuisine: 'Indian',
    prep_minutes: 480,
    cook_minutes: 10,
    servings: 4,
    calories: 180,
    ingredients: [
      { name: 'dosa batter', quantity: '2', unit: 'cups' },
      { name: 'onion', quantity: '1', unit: 'finely diced' },
      { name: 'tomato', quantity: '1', unit: 'finely diced' },
      { name: 'green chili', quantity: '2', unit: 'minced' },
      { name: 'cilantro', quantity: '2', unit: 'tbsp, chopped' },
      { name: 'oil', quantity: '2', unit: 'tbsp' },
      { name: 'salt', quantity: '1/2', unit: 'tsp' },
    ],
    steps: [
      'Prepare dosa batter by soaking and fermenting rice and urad dal overnight.',
      'Mix onion, tomato, green chili, cilantro, and salt in a bowl.',
      'Heat a griddle, pour a ladle of batter and spread into a thick circle.',
      'Sprinkle the vegetable topping evenly over the batter.',
      'Drizzle oil around edges. Cook until bottom is golden.',
      'Flip and cook 1 minute. Serve with sambar and chutney.',
    ],
    tags: ['indian', 'south-indian', 'breakfast', 'pancake', 'fermented'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 180,
      protein_g: 5,
      carbs_g: 28,
      fat_g: 6,
      fiber_g: 2,
      sugar_g: 2,
      sodium_mg: 210,
    },
  },
  {
    title: 'Chicken Chettinad',
    description:
      'Fiery South Indian chicken curry from Chettinad, packed with freshly ground spices and curry leaves.',
    cuisine: 'Indian',
    prep_minutes: 20,
    cook_minutes: 35,
    servings: 4,
    calories: 350,
    ingredients: [
      { name: 'chicken', quantity: '1.5', unit: 'lb, pieces' },
      { name: 'onion', quantity: '2', unit: 'sliced' },
      { name: 'tomato', quantity: '2', unit: 'diced' },
      { name: 'ginger-garlic paste', quantity: '1', unit: 'tbsp' },
      { name: 'curry leaves', quantity: '10', unit: 'leaves' },
      { name: 'black pepper', quantity: '1', unit: 'tbsp' },
      { name: 'coriander seeds', quantity: '1', unit: 'tbsp' },
      { name: 'cumin seeds', quantity: '1', unit: 'tsp' },
      { name: 'fennel seeds', quantity: '1', unit: 'tsp' },
      { name: 'coconut', quantity: '1/4', unit: 'cup, grated' },
    ],
    steps: [
      'Dry-roast pepper, coriander, cumin, and fennel seeds. Grind into a paste with coconut.',
      'Heat oil, add curry leaves and onion. Cook until golden.',
      'Add ginger-garlic paste and tomato. Cook 5 minutes.',
      'Add the ground spice paste and cook until fragrant.',
      'Add chicken pieces, salt, and 1/2 cup water. Simmer 25 minutes.',
      'Serve hot with rice or parotta.',
    ],
    tags: ['indian', 'south-indian', 'chicken', 'spicy', 'chettinad'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 350,
      protein_g: 32,
      carbs_g: 10,
      fat_g: 20,
      fiber_g: 3,
      sugar_g: 3,
      sodium_mg: 510,
    },
  },
  {
    title: 'Medu Vada',
    description:
      'Crispy, golden lentil donuts flavored with black pepper and curry leaves — a beloved South Indian snack.',
    cuisine: 'Indian',
    prep_minutes: 240,
    cook_minutes: 15,
    servings: 6,
    calories: 170,
    ingredients: [
      { name: 'urad dal', quantity: '1', unit: 'cup' },
      { name: 'black pepper', quantity: '1', unit: 'tsp, crushed' },
      { name: 'curry leaves', quantity: '8', unit: 'chopped' },
      { name: 'green chili', quantity: '2', unit: 'minced' },
      { name: 'ginger', quantity: '1', unit: 'tsp, minced' },
      { name: 'rice flour', quantity: '1', unit: 'tbsp' },
      { name: 'salt', quantity: '1', unit: 'tsp' },
      { name: 'oil', quantity: '2', unit: 'cups, for frying' },
    ],
    steps: [
      'Soak urad dal for 4 hours. Drain and grind to a fluffy batter with minimal water.',
      'Add black pepper, curry leaves, green chili, ginger, rice flour, and salt. Mix well.',
      'Wet your hands, take a portion of batter, make a hole in the center to form a donut shape.',
      'Slide into hot oil and deep-fry until golden and crispy on both sides.',
      'Drain on paper towels.',
      'Serve hot with sambar and coconut chutney.',
    ],
    tags: ['indian', 'south-indian', 'snack', 'fried', 'lentil'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 170,
      protein_g: 7,
      carbs_g: 18,
      fat_g: 8,
      fiber_g: 3,
      sugar_g: 1,
      sodium_mg: 320,
    },
  },
];

export const indianAdditionalRecipes = generateCuisineRecipes(additionalIndianConfigs);
export const indianBatch3Recipes = generateCuisineRecipes(indianBatch3Configs);
export const indianBatch4Recipes = generateCuisineRecipes(indianBatch4Configs);
