import type { CuisineRecipeConfig } from './types';
import { generateCuisineRecipes } from './types';

const configs: CuisineRecipeConfig[] = [
  {
    title: 'Spaghetti Carbonara',
    description: 'Classic Roman pasta with guanciale, egg yolk, pecorino, and black pepper.',
    cuisine: 'Italian',
    prep_minutes: 10,
    cook_minutes: 15,
    servings: 4,
    calories: 480,
    ingredients: [
      { name: 'spaghetti', quantity: '1', unit: 'lb' },
      { name: 'guanciale', quantity: '6', unit: 'oz, diced' },
      { name: 'egg yolks', quantity: '4', unit: 'large' },
      { name: 'pecorino romano', quantity: '1', unit: 'cup, grated' },
      { name: 'black pepper', quantity: '2', unit: 'tsp, freshly cracked' },
      { name: 'salt', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Cook spaghetti in salted water until al dente. Reserve 1 cup pasta water.',
      'Crisp guanciale in a skillet until golden. Remove from heat.',
      'Whisk egg yolks, pecorino, and pepper together.',
      'Toss hot pasta with guanciale, then quickly stir in egg mixture. Add pasta water to reach creamy consistency.',
    ],
    tags: ['carbonara', 'italian', 'pasta', 'roman', 'egg'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 480,
      protein_g: 20,
      carbs_g: 52,
      fat_g: 22,
      fiber_g: 2,
      sugar_g: 2,
      sodium_mg: 580,
    },
  },
  {
    title: 'Margherita Pizza',
    description: 'Neapolitan pizza with San Marzano tomatoes, fresh mozzarella, and basil.',
    cuisine: 'Italian',
    prep_minutes: 15,
    cook_minutes: 10,
    servings: 4,
    calories: 320,
    ingredients: [
      { name: 'pizza dough', quantity: '1', unit: 'ball (12 oz)' },
      { name: 'San Marzano tomatoes', quantity: '1/2', unit: 'cup, crushed' },
      { name: 'fresh mozzarella', quantity: '6', unit: 'oz, sliced' },
      { name: 'fresh basil', quantity: '8', unit: 'leaves' },
      { name: 'olive oil', quantity: '1', unit: 'tbsp' },
      { name: 'salt', quantity: '1/4', unit: 'tsp' },
    ],
    steps: [
      'Stretch dough into a 12-inch round on a floured surface.',
      'Spread crushed tomatoes, leaving a 1-inch border. Add mozzarella.',
      'Bake at 500°F (or as hot as your oven goes) for 8-10 minutes until bubbly and charred.',
      'Top with fresh basil, drizzle olive oil, and serve immediately.',
    ],
    tags: ['pizza', 'margherita', 'italian', 'neapolitan', 'vegetarian'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 14,
      carbs_g: 36,
      fat_g: 12,
      fiber_g: 2,
      sugar_g: 4,
      sodium_mg: 520,
    },
  },
  {
    title: 'Osso Buco',
    description: 'Braised veal shanks in white wine and vegetables with gremolata.',
    cuisine: 'Italian',
    prep_minutes: 20,
    cook_minutes: 120,
    servings: 4,
    calories: 480,
    ingredients: [
      { name: 'veal shanks', quantity: '4', unit: 'pieces (2 inches thick)' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'carrot', quantity: '1', unit: 'diced' },
      { name: 'celery', quantity: '1', unit: 'diced' },
      { name: 'white wine', quantity: '1', unit: 'cup' },
      { name: 'diced tomato', quantity: '1', unit: 'can (14 oz)' },
      { name: 'lemon zest', quantity: '1', unit: 'tbsp' },
      { name: 'parsley', quantity: '2', unit: 'tbsp, chopped' },
    ],
    steps: [
      'Dredge veal shanks in flour and brown in oil on both sides.',
      'Sauté onion, carrot, and celery. Add wine and reduce by half.',
      'Add tomatoes and broth. Return shanks. Cover and braise at 325°F for 2 hours.',
      'Make gremolata: mix lemon zest, garlic, and parsley. Serve shanks with gremolata and risotto.',
    ],
    tags: ['osso buco', 'italian', 'veal', 'braised', 'milanese'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 480,
      protein_g: 38,
      carbs_g: 12,
      fat_g: 28,
      fiber_g: 2,
      sugar_g: 4,
      sodium_mg: 520,
    },
  },
  {
    title: 'Risotto alla Milanese',
    description: 'Creamy saffron risotto from Milan — golden, rich, and comforting.',
    cuisine: 'Italian',
    prep_minutes: 5,
    cook_minutes: 25,
    servings: 4,
    calories: 380,
    ingredients: [
      { name: 'arborio rice', quantity: '1.5', unit: 'cups' },
      { name: 'saffron threads', quantity: '1/4', unit: 'tsp' },
      { name: 'chicken broth', quantity: '5', unit: 'cups, warm' },
      { name: 'white wine', quantity: '1/2', unit: 'cup' },
      { name: 'onion', quantity: '1/2', unit: 'finely diced' },
      { name: 'butter', quantity: '3', unit: 'tbsp' },
      { name: 'parmigiano reggiano', quantity: '1/2', unit: 'cup, grated' },
    ],
    steps: [
      'Bloom saffron in warm broth.',
      'Sauté onion in butter. Add rice and toast 2 minutes. Add wine and stir until absorbed.',
      'Add saffron broth one ladle at a time, stirring constantly, for 18-20 minutes.',
      'Finish with butter and parmigiano. Serve immediately — risotto waits for no one.',
    ],
    tags: ['risotto', 'milanese', 'saffron', 'italian', 'creamy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 10,
      carbs_g: 52,
      fat_g: 14,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 680,
    },
  },
  {
    title: 'Bruschetta al Pomodoro',
    description:
      'Grilled bread rubbed with garlic and topped with fresh tomato, basil, and olive oil.',
    cuisine: 'Italian',
    prep_minutes: 10,
    cook_minutes: 3,
    servings: 6,
    calories: 140,
    ingredients: [
      { name: 'ciabatta bread', quantity: '1', unit: 'loaf, sliced' },
      { name: 'ripe tomato', quantity: '4', unit: 'diced' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
      { name: 'fresh basil', quantity: '1/4', unit: 'cup, chopped' },
      { name: 'olive oil', quantity: '3', unit: 'tbsp' },
      { name: 'salt', quantity: '1/4', unit: 'tsp' },
    ],
    steps: [
      'Grill or toast bread slices until golden on both sides.',
      'Rub warm bread with a halved garlic clove.',
      'Top with diced tomato, basil, olive oil, and salt.',
      'Serve immediately while bread is still warm.',
    ],
    tags: ['bruschetta', 'italian', 'tomato', 'bread', 'appetizer'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 140,
      protein_g: 4,
      carbs_g: 20,
      fat_g: 6,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 220,
    },
  },
  {
    title: 'Tiramisu',
    description: 'Italian coffee-soaked ladyfingers layered with mascarpone cream and cocoa.',
    cuisine: 'Italian',
    prep_minutes: 25,
    cook_minutes: 0,
    servings: 8,
    calories: 320,
    ingredients: [
      { name: 'ladyfingers', quantity: '24', unit: 'pieces' },
      { name: 'espresso', quantity: '1.5', unit: 'cups, cooled' },
      { name: 'mascarpone', quantity: '1', unit: 'cup' },
      { name: 'egg yolks', quantity: '4', unit: 'large' },
      { name: 'sugar', quantity: '1/2', unit: 'cup' },
      { name: 'cocoa powder', quantity: '2', unit: 'tbsp' },
      { name: 'heavy cream', quantity: '1', unit: 'cup' },
    ],
    steps: [
      'Whisk egg yolks and sugar until pale and thick. Fold in mascarpone.',
      'Whip heavy cream to stiff peaks and fold into mascarpone mixture.',
      'Dip ladyfingers briefly in espresso. Layer in a dish.',
      'Spread cream over ladyfingers, repeat layers. Dust with cocoa. Refrigerate 4+ hours.',
    ],
    tags: ['tiramisu', 'italian', 'dessert', 'coffee', 'mascarpone'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 8,
      carbs_g: 32,
      fat_g: 18,
      fiber_g: 1,
      sugar_g: 22,
      sodium_mg: 120,
    },
  },
  {
    title: 'Cacio e Pepe',
    description: 'Minimalist Roman pasta with pecorino, black pepper, and starchy pasta water.',
    cuisine: 'Italian',
    prep_minutes: 5,
    cook_minutes: 12,
    servings: 4,
    calories: 420,
    ingredients: [
      { name: 'tonnarelli or spaghetti', quantity: '1', unit: 'lb' },
      { name: 'pecorino romano', quantity: '1.5', unit: 'cups, finely grated' },
      { name: 'black pepper', quantity: '2', unit: 'tbsp, freshly cracked' },
      { name: 'salt', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Toast black pepper in a dry skillet for 2 minutes.',
      'Cook pasta in salted water until al dente. Reserve 2 cups pasta water.',
      'Add pepper and 1 cup pasta water to the hot pan. Add pasta and toss.',
      'Remove from heat, add pecorino in stages, tossing vigorously. Add more water if needed for a creamy sauce.',
    ],
    tags: ['cacio e pepe', 'italian', 'pasta', 'roman', 'pecorino'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 16,
      carbs_g: 52,
      fat_g: 16,
      fiber_g: 2,
      sugar_g: 2,
      sodium_mg: 520,
    },
  },
  {
    title: 'Pasta e Fagioli',
    description: 'Hearty Italian pasta and bean soup with tomato, vegetables, and herbs.',
    cuisine: 'Italian',
    prep_minutes: 15,
    cook_minutes: 30,
    servings: 6,
    calories: 320,
    ingredients: [
      { name: 'ditalini pasta', quantity: '1', unit: 'cup' },
      { name: 'cannellini beans', quantity: '2', unit: 'cans, drained' },
      { name: 'crushed tomatoes', quantity: '1', unit: 'can (28 oz)' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'carrot', quantity: '1', unit: 'diced' },
      { name: 'celery', quantity: '1', unit: 'diced' },
      { name: 'garlic', quantity: '3', unit: 'cloves' },
      { name: 'parmesan rind', quantity: '1', unit: 'piece' },
    ],
    steps: [
      'Sauté onion, carrot, and celery. Add garlic and cook 1 minute.',
      'Add tomatoes, beans, broth, and parmesan rind. Simmer 20 minutes.',
      'Mash some beans to thicken. Add pasta and cook until al dente.',
      'Season with salt, pepper, and rosemary. Drizzle with olive oil.',
    ],
    tags: ['pasta e fagioli', 'italian', 'soup', 'beans', 'pasta'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 14,
      carbs_g: 48,
      fat_g: 6,
      fiber_g: 10,
      sugar_g: 6,
      sodium_mg: 620,
    },
  },
  {
    title: 'Chicken Parmesan',
    description:
      'Breaded chicken cutlet topped with marinara and melted mozzarella over spaghetti.',
    cuisine: 'Italian',
    prep_minutes: 20,
    cook_minutes: 25,
    servings: 4,
    calories: 520,
    ingredients: [
      { name: 'chicken breasts', quantity: '4', unit: 'pounded thin' },
      { name: 'breadcrumbs', quantity: '1', unit: 'cup' },
      { name: 'marinara sauce', quantity: '2', unit: 'cups' },
      { name: 'mozzarella cheese', quantity: '8', unit: 'oz, shredded' },
      { name: 'parmesan', quantity: '1/4', unit: 'cup, grated' },
      { name: 'egg', quantity: '2', unit: 'beaten' },
      { name: 'flour', quantity: '1/2', unit: 'cup' },
      { name: 'spaghetti', quantity: '1/2', unit: 'lb' },
    ],
    steps: [
      'Dredge chicken in flour, dip in egg, coat in breadcrumbs mixed with parmesan.',
      'Pan-fry chicken in oil until golden on both sides, about 4 minutes per side.',
      'Top with marinara and mozzarella. Bake at 400°F for 10-12 minutes until cheese melts.',
      'Serve over spaghetti with extra marinara.',
    ],
    tags: ['chicken parmesan', 'italian', 'chicken', 'breaded', 'cheese'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 520,
      protein_g: 38,
      carbs_g: 40,
      fat_g: 22,
      fiber_g: 3,
      sugar_g: 6,
      sodium_mg: 820,
    },
  },
  {
    title: 'Caprese Salad',
    description: 'Fresh mozzarella, ripe tomatoes, and basil drizzled with olive oil and balsamic.',
    cuisine: 'Italian',
    prep_minutes: 10,
    cook_minutes: 0,
    servings: 4,
    calories: 200,
    ingredients: [
      { name: 'fresh mozzarella', quantity: '8', unit: 'oz, sliced' },
      { name: 'ripe tomato', quantity: '2', unit: 'large, sliced' },
      { name: 'fresh basil', quantity: '12', unit: 'leaves' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'balsamic glaze', quantity: '1', unit: 'tbsp' },
      { name: 'salt', quantity: '1/4', unit: 'tsp' },
    ],
    steps: [
      'Slice mozzarella and tomatoes into thick rounds.',
      'Alternate tomato and mozzarella on a plate, tucking basil leaves between.',
      'Drizzle with olive oil and balsamic glaze.',
      'Season with salt and freshly cracked pepper.',
    ],
    tags: ['caprese', 'italian', 'salad', 'mozzarella', 'vegetarian'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 200,
      protein_g: 12,
      carbs_g: 6,
      fat_g: 14,
      fiber_g: 1,
      sugar_g: 4,
      sodium_mg: 280,
    },
  },
  {
    title: 'Lasagna Bolognese',
    description: 'Layered pasta with rich meat ragù, béchamel, and parmesan.',
    cuisine: 'Italian',
    prep_minutes: 30,
    cook_minutes: 60,
    servings: 8,
    calories: 480,
    ingredients: [
      { name: 'lasagna sheets', quantity: '12', unit: 'pieces' },
      { name: 'ground beef', quantity: '1', unit: 'lb' },
      { name: 'ground pork', quantity: '1/2', unit: 'lb' },
      { name: 'tomato sauce', quantity: '3', unit: 'cups' },
      { name: 'butter', quantity: '3', unit: 'tbsp' },
      { name: 'flour', quantity: '3', unit: 'tbsp' },
      { name: 'milk', quantity: '2', unit: 'cups' },
      { name: 'parmesan', quantity: '1', unit: 'cup, grated' },
    ],
    steps: [
      'Make ragù: brown beef and pork, add tomato sauce, simmer 30 minutes.',
      'Make béchamel: melt butter, whisk in flour, add milk until thick.',
      'Layer: ragù, pasta, béchamel, parmesan. Repeat 3 times.',
      'Bake at 375°F for 40 minutes covered, then 15 uncovered until golden. Rest 15 minutes.',
    ],
    tags: ['lasagna', 'italian', 'bolognese', 'baked', 'pasta'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 480,
      protein_g: 28,
      carbs_g: 40,
      fat_g: 22,
      fiber_g: 3,
      sugar_g: 6,
      sodium_mg: 720,
    },
  },
  {
    title: 'Pesto Pasta',
    description: 'Fresh basil pesto with pine nuts, garlic, and parmesan tossed with pasta.',
    cuisine: 'Italian',
    prep_minutes: 10,
    cook_minutes: 12,
    servings: 4,
    calories: 420,
    ingredients: [
      { name: 'pasta', quantity: '1', unit: 'lb' },
      { name: 'fresh basil', quantity: '2', unit: 'cups, packed' },
      { name: 'pine nuts', quantity: '1/4', unit: 'cup' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
      { name: 'parmesan', quantity: '1/2', unit: 'cup, grated' },
      { name: 'olive oil', quantity: '1/2', unit: 'cup' },
      { name: 'salt', quantity: '1/2', unit: 'tsp' },
    ],
    steps: [
      'Blend basil, pine nuts, garlic, parmesan, and olive oil into a smooth pesto.',
      'Cook pasta until al dente. Reserve 1/2 cup pasta water.',
      'Toss hot pasta with pesto, adding pasta water to thin as needed.',
      'Serve with extra parmesan and a drizzle of olive oil.',
    ],
    tags: ['pesto', 'italian', 'pasta', 'basil', 'vegetarian'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 14,
      carbs_g: 50,
      fat_g: 20,
      fiber_g: 3,
      sugar_g: 3,
      sodium_mg: 380,
    },
  },
  {
    title: 'Minestrone',
    description: 'Hearty Italian vegetable soup with pasta, beans, and seasonal vegetables.',
    cuisine: 'Italian',
    prep_minutes: 15,
    cook_minutes: 35,
    servings: 6,
    calories: 240,
    ingredients: [
      { name: 'mixed vegetables', quantity: '4', unit: 'cups, diced' },
      { name: 'cannellini beans', quantity: '1', unit: 'can, drained' },
      { name: 'ditalini pasta', quantity: '1/2', unit: 'cup' },
      { name: 'crushed tomatoes', quantity: '1', unit: 'can' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'garlic', quantity: '3', unit: 'cloves' },
      { name: 'vegetable broth', quantity: '4', unit: 'cups' },
      { name: 'parmesan rind', quantity: '1', unit: 'piece' },
    ],
    steps: [
      'Sauté onion and garlic. Add diced vegetables and cook 5 minutes.',
      'Add tomatoes, broth, and parmesan rind. Simmer 20 minutes.',
      'Add beans and pasta. Cook 10 more minutes until pasta is tender.',
      'Season with salt, pepper, and fresh basil. Drizzle with olive oil.',
    ],
    tags: ['minestrone', 'italian', 'soup', 'vegetables', 'vegetarian'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 240,
      protein_g: 10,
      carbs_g: 38,
      fat_g: 5,
      fiber_g: 8,
      sugar_g: 6,
      sodium_mg: 580,
    },
  },
  {
    title: 'Arancini',
    description:
      'Crispy fried risotto balls stuffed with mozzarella — a Sicilian street food classic.',
    cuisine: 'Italian',
    prep_minutes: 30,
    cook_minutes: 10,
    servings: 6,
    calories: 320,
    ingredients: [
      { name: 'cooked risotto', quantity: '3', unit: 'cups, cooled' },
      { name: 'mozzarella', quantity: '4', unit: 'oz, cubed' },
      { name: 'flour', quantity: '1/2', unit: 'cup' },
      { name: 'eggs', quantity: '2', unit: 'beaten' },
      { name: 'breadcrumbs', quantity: '1', unit: 'cup' },
      { name: 'vegetable oil', quantity: '2', unit: 'cups, for frying' },
      { name: 'marinara sauce', quantity: '1/2', unit: 'cup, for dipping' },
    ],
    steps: [
      'Take a handful of cold risotto, press a mozzarella cube into the center, and shape into a ball.',
      'Roll in flour, dip in egg, and coat in breadcrumbs.',
      'Fry in 350°F oil for 3-4 minutes until golden and cheese is melted inside.',
      'Drain and serve with warm marinara for dipping.',
    ],
    tags: ['arancini', 'italian', 'sicilian', 'fried', 'risotto'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 12,
      carbs_g: 34,
      fat_g: 16,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 480,
    },
  },
  {
    title: 'Focaccia',
    description:
      'Olive oil-rich Italian flatbread dimpled and topped with rosemary and flaky salt.',
    cuisine: 'Italian',
    prep_minutes: 15,
    cook_minutes: 25,
    servings: 8,
    calories: 180,
    ingredients: [
      { name: 'flour', quantity: '3', unit: 'cups' },
      { name: 'olive oil', quantity: '1/4', unit: 'cup' },
      { name: 'water', quantity: '1.5', unit: 'cups, warm' },
      { name: 'yeast', quantity: '1', unit: 'packet' },
      { name: 'rosemary', quantity: '2', unit: 'tbsp, fresh' },
      { name: 'flaky sea salt', quantity: '1', unit: 'tsp' },
      { name: 'sugar', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Mix flour, yeast, sugar, water, and 2 tbsp olive oil. Knead and rise 1 hour.',
      'Stretch dough into an oiled sheet pan. Dimple with fingers.',
      'Drizzle generously with olive oil, add rosemary and flaky salt. Rise 30 minutes.',
      'Bake at 425°F for 20-25 minutes until golden. Brush with more olive oil.',
    ],
    tags: ['focaccia', 'italian', 'bread', 'rosemary', 'olive oil'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 180,
      protein_g: 4,
      carbs_g: 24,
      fat_g: 8,
      fiber_g: 1,
      sugar_g: 1,
      sodium_mg: 280,
    },
  },
];

export const italianRecipes = generateCuisineRecipes(configs);
