import type { CuisineRecipeConfig } from './types';
import { generateCuisineRecipes } from './types';

const configs: CuisineRecipeConfig[] = [
  {
    title: 'Tonkotsu Ramen',
    description: 'Rich, milky pork-bone broth ramen with chashu, soft egg, nori, and green onions.',
    cuisine: 'Japanese',
    prep_minutes: 30,
    cook_minutes: 720,
    servings: 4,
    calories: 580,
    ingredients: [
      { name: 'pork bones', quantity: '3', unit: 'lb' },
      { name: 'ramen noodles', quantity: '12', unit: 'oz' },
      { name: 'chashu pork', quantity: '8', unit: 'oz, sliced' },
      { name: 'soft-boiled egg', quantity: '4', unit: 'halved' },
      { name: 'nori', quantity: '4', unit: 'sheets' },
      { name: 'green onion', quantity: '4', unit: 'sliced' },
      { name: 'garlic', quantity: '6', unit: 'cloves' },
      { name: 'ginger', quantity: '3', unit: 'inches, sliced' },
      { name: 'soy sauce', quantity: '2', unit: 'tbsp' },
      { name: 'sesame oil', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Blanch pork bones, then scrub clean. Cover with fresh water and boil.',
      'Boil bones vigorously for 8-12 hours, adding water as needed, until broth is milky.',
      'Strain broth and season with soy sauce, sesame oil, and salt.',
      'Cook ramen noodles according to package.',
      'Divide noodles among bowls, ladle hot broth over.',
      'Top with chashu, egg, nori, and green onions.',
    ],
    tags: ['japanese', 'ramen', 'pork', 'noodles', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 580,
      protein_g: 32,
      carbs_g: 48,
      fat_g: 28,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 1400,
    },
  },
  {
    title: 'Okonomiyaki',
    description:
      'Savory Japanese cabbage pancake topped with okonomiyaki sauce, mayo, and bonito flakes.',
    cuisine: 'Japanese',
    prep_minutes: 15,
    cook_minutes: 10,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'cabbage', quantity: '3', unit: 'cups, shredded' },
      { name: 'flour', quantity: '1', unit: 'cup' },
      { name: 'egg', quantity: '2', unit: 'large' },
      { name: 'dashi', quantity: '1/2', unit: 'cup' },
      { name: 'pork belly', quantity: '4', unit: 'slices, thin' },
      { name: 'okonomiyaki sauce', quantity: '3', unit: 'tbsp' },
      { name: 'Japanese mayo', quantity: '2', unit: 'tbsp' },
      { name: 'bonito flakes', quantity: '1', unit: 'tbsp' },
      { name: 'aonori', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Mix flour, dashi, and eggs. Add shredded cabbage and mix.',
      'Heat a griddle, oil it. Pour batter into a round.',
      'Lay pork belly slices on top.',
      'Flip when bottom is golden, cook until pork is crispy.',
      'Slide onto a plate, top with okonomiyaki sauce and mayo in a zigzag.',
      'Garnish with bonito flakes and aonori.',
    ],
    tags: ['japanese', 'pancake', 'cabbage', 'pork', 'street-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 14,
      carbs_g: 26,
      fat_g: 14,
      fiber_g: 3,
      sugar_g: 4,
      sodium_mg: 780,
    },
  },
  {
    title: 'Gyoza',
    description:
      'Crispy-bottomed Japanese dumplings filled with pork and cabbage, pan-fried to perfection.',
    cuisine: 'Japanese',
    prep_minutes: 30,
    cook_minutes: 8,
    servings: 6,
    calories: 200,
    ingredients: [
      { name: 'gyoza wrappers', quantity: '30', unit: 'round' },
      { name: 'ground pork', quantity: '1/2', unit: 'lb' },
      { name: 'cabbage', quantity: '1', unit: 'cup, minced' },
      { name: 'green onion', quantity: '4', unit: 'minced' },
      { name: 'ginger', quantity: '1', unit: 'tbsp, grated' },
      { name: 'garlic', quantity: '2', unit: 'cloves, minced' },
      { name: 'soy sauce', quantity: '1', unit: 'tbsp' },
      { name: 'sesame oil', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Mix pork, cabbage, green onion, ginger, garlic, soy sauce, and sesame oil.',
      'Place a teaspoon of filling in each wrapper, fold and pleat to seal.',
      'Heat oil in a skillet. Place gyoza flat side down.',
      'Add 1/4 cup water, cover, and steam 3 minutes.',
      'Uncover and cook until water evaporates and bottoms are crispy.',
      'Serve with soy-vinegar dipping sauce.',
    ],
    tags: ['japanese', 'dumplings', 'pork', 'pan-fried', 'appetizer'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 200,
      protein_g: 10,
      carbs_g: 20,
      fat_g: 8,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 480,
    },
  },
  {
    title: 'Yakitori',
    description: 'Grilled chicken skewers basted with sweet-savory tare sauce over charcoal.',
    cuisine: 'Japanese',
    prep_minutes: 15,
    cook_minutes: 10,
    servings: 4,
    calories: 240,
    ingredients: [
      { name: 'chicken thigh', quantity: '1', unit: 'lb, cubed' },
      { name: 'green onion', quantity: '4', unit: 'stalks, cut' },
      { name: 'soy sauce', quantity: '3', unit: 'tbsp' },
      { name: 'mirin', quantity: '2', unit: 'tbsp' },
      { name: 'sake', quantity: '2', unit: 'tbsp' },
      { name: 'sugar', quantity: '1', unit: 'tbsp' },
      { name: 'bamboo skewers', quantity: '8', unit: 'soaked' },
    ],
    steps: [
      'Thread chicken and green onion alternately onto skewers.',
      'Make tare sauce: simmer soy sauce, mirin, sake, and sugar until slightly thickened.',
      'Grill skewers over medium-high heat, turning every 2 minutes.',
      'Baste with tare sauce each time you turn.',
      'Grill until chicken is cooked through and slightly charred.',
      'Serve with extra tare sauce on the side.',
    ],
    tags: ['japanese', 'grilled', 'chicken', 'skewers', 'street-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 240,
      protein_g: 24,
      carbs_g: 8,
      fat_g: 12,
      fiber_g: 0,
      sugar_g: 5,
      sodium_mg: 680,
    },
  },
  {
    title: 'Katsu Curry',
    description: 'Crispy panko-breaded pork cutlet served over rice with Japanese curry sauce.',
    cuisine: 'Japanese',
    prep_minutes: 20,
    cook_minutes: 20,
    servings: 4,
    calories: 520,
    ingredients: [
      { name: 'pork loin', quantity: '4', unit: 'cutlets' },
      { name: 'panko breadcrumbs', quantity: '1', unit: 'cup' },
      { name: 'egg', quantity: '1', unit: 'beaten' },
      { name: 'flour', quantity: '1/2', unit: 'cup' },
      { name: 'curry roux blocks', quantity: '3', unit: 'oz' },
      { name: 'onion', quantity: '1', unit: 'sliced' },
      { name: 'carrot', quantity: '1', unit: 'diced' },
      { name: 'potato', quantity: '1', unit: 'diced' },
      { name: 'steamed rice', quantity: '4', unit: 'cups' },
    ],
    steps: [
      'Make curry: sauté onion, carrot, and potato. Add water and simmer until tender.',
      'Add curry roux blocks and stir until dissolved and thickened.',
      'Pound pork cutlets thin. Dredge in flour, egg, then panko.',
      'Deep fry at 350°F until golden and cooked through.',
      'Slice katsu into strips.',
      'Serve rice topped with curry sauce and katsu on top.',
    ],
    tags: ['japanese', 'curry', 'pork', 'fried', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 520,
      protein_g: 28,
      carbs_g: 56,
      fat_g: 18,
      fiber_g: 3,
      sugar_g: 5,
      sodium_mg: 860,
    },
  },
  {
    title: 'Oyakodon',
    description:
      'Chicken and egg rice bowl simmered in a sweet dashi-soy broth, served over steamed rice.',
    cuisine: 'Japanese',
    prep_minutes: 10,
    cook_minutes: 10,
    servings: 2,
    calories: 420,
    ingredients: [
      { name: 'chicken thigh', quantity: '8', unit: 'oz, sliced' },
      { name: 'egg', quantity: '3', unit: 'large' },
      { name: 'onion', quantity: '1', unit: 'sliced' },
      { name: 'dashi', quantity: '1/2', unit: 'cup' },
      { name: 'soy sauce', quantity: '2', unit: 'tbsp' },
      { name: 'mirin', quantity: '1', unit: 'tbsp' },
      { name: 'sugar', quantity: '1', unit: 'tsp' },
      { name: 'steamed rice', quantity: '2', unit: 'cups' },
    ],
    steps: [
      'Bring dashi, soy sauce, mirin, and sugar to a simmer in a pan.',
      'Add sliced onion and chicken. Cook until chicken is done.',
      'Beat eggs lightly and pour over the chicken and onion.',
      'Cover and cook until eggs are just barely set, about 1-2 minutes.',
      'Slide the whole thing onto a bowl of steamed rice.',
      'Garnish with mitsuba or green onion.',
    ],
    tags: ['japanese', 'rice-bowl', 'chicken', 'egg', 'quick'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 26,
      carbs_g: 42,
      fat_g: 14,
      fiber_g: 1,
      sugar_g: 4,
      sodium_mg: 820,
    },
  },
  {
    title: 'Matcha Mochi',
    description:
      'Soft, chewy Japanese rice cakes flavored with matcha green tea and dusted with kinako.',
    cuisine: 'Japanese',
    prep_minutes: 15,
    cook_minutes: 5,
    servings: 8,
    calories: 120,
    ingredients: [
      { name: 'mochiko (sweet rice flour)', quantity: '1', unit: 'cup' },
      { name: 'sugar', quantity: '1/3', unit: 'cup' },
      { name: 'matcha powder', quantity: '1', unit: 'tbsp' },
      { name: 'water', quantity: '1', unit: 'cup' },
      { name: 'cornstarch', quantity: '1/4', unit: 'cup, for dusting' },
      { name: 'red bean paste', quantity: '1/2', unit: 'cup' },
    ],
    steps: [
      'Mix mochiko, sugar, and matcha powder.',
      'Add water and stir until smooth.',
      'Microwave for 2 minutes, stir, then 1 more minute until translucent.',
      'Dust a surface with cornstarch. Turn out the mochi.',
      'Pinch off pieces, flatten, and wrap around red bean paste.',
      'Dust with extra cornstarch and serve.',
    ],
    tags: ['japanese', 'dessert', 'mochi', 'matcha', 'sweet'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 120,
      protein_g: 1,
      carbs_g: 26,
      fat_g: 0,
      fiber_g: 0,
      sugar_g: 12,
      sodium_mg: 20,
    },
  },
  {
    title: 'Japanese Curry',
    description:
      'Mild, slightly sweet Japanese curry with vegetables and your choice of protein over rice.',
    cuisine: 'Japanese',
    prep_minutes: 15,
    cook_minutes: 30,
    servings: 6,
    calories: 420,
    ingredients: [
      { name: 'curry roux', quantity: '4', unit: 'oz' },
      { name: 'chicken thigh', quantity: '1', unit: 'lb, cubed' },
      { name: 'potato', quantity: '2', unit: 'diced' },
      { name: 'carrot', quantity: '2', unit: 'diced' },
      { name: 'onion', quantity: '2', unit: 'sliced' },
      { name: 'garlic', quantity: '2', unit: 'cloves, minced' },
      { name: 'ginger', quantity: '1', unit: 'tsp, grated' },
      { name: 'steamed rice', quantity: '6', unit: 'cups' },
    ],
    steps: [
      'Sauté onion, garlic, and ginger until fragrant.',
      'Add chicken and cook until no longer pink.',
      'Add potato and carrot, stir to coat.',
      'Add 4 cups water and bring to a boil. Simmer 15 minutes.',
      'Add curry roux blocks, stir until dissolved and thickened.',
      'Simmer 10 more minutes. Serve over steamed rice.',
    ],
    tags: ['japanese', 'curry', 'chicken', 'rice', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 24,
      carbs_g: 52,
      fat_g: 12,
      fiber_g: 3,
      sugar_g: 5,
      sodium_mg: 860,
    },
  },
  {
    title: 'Tamagoyaki',
    description: 'Japanese rolled omelette layered with dashi, slightly sweet and custardy.',
    cuisine: 'Japanese',
    prep_minutes: 5,
    cook_minutes: 8,
    servings: 4,
    calories: 120,
    ingredients: [
      { name: 'egg', quantity: '4', unit: 'large' },
      { name: 'dashi', quantity: '2', unit: 'tbsp' },
      { name: 'sugar', quantity: '1', unit: 'tbsp' },
      { name: 'soy sauce', quantity: '1', unit: 'tsp' },
      { name: 'mirin', quantity: '1', unit: 'tsp' },
      { name: 'oil', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Beat eggs with dashi, sugar, soy sauce, and mirin.',
      'Heat a rectangular tamagoyaki pan with a thin layer of oil.',
      'Pour a thin layer of egg, roll it to one end when set.',
      'Push roll back, add more egg, roll again. Repeat 4-5 times.',
      'Shape the roll while still warm using a bamboo mat.',
      'Slice into pieces and serve as a side or in bento.',
    ],
    tags: ['japanese', 'egg', 'omelette', 'breakfast', 'bento'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 120,
      protein_g: 8,
      carbs_g: 4,
      fat_g: 8,
      fiber_g: 0,
      sugar_g: 3,
      sodium_mg: 280,
    },
  },
  {
    title: 'Onigiri',
    description: 'Japanese rice balls shaped into triangles with a filling, wrapped in nori.',
    cuisine: 'Japanese',
    prep_minutes: 15,
    cook_minutes: 0,
    servings: 4,
    calories: 160,
    ingredients: [
      { name: 'sushi rice', quantity: '2', unit: 'cups, cooked' },
      { name: 'nori', quantity: '4', unit: 'sheets, halved' },
      { name: 'salmon flake', quantity: '1/2', unit: 'cup' },
      { name: 'umeboshi', quantity: '4', unit: 'pickled plums' },
      { name: 'salt', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Cook and season sushi rice. Wet hands with salted water.',
      'Place a handful of rice in your palm.',
      'Make an indentation, add salmon or umeboshi filling.',
      'Fold rice over filling and shape into a triangle.',
      'Wrap a strip of nori around the base.',
      'Serve immediately or wrap for bento.',
    ],
    tags: ['japanese', 'rice', 'snack', 'bento', 'portable'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 160,
      protein_g: 6,
      carbs_g: 28,
      fat_g: 2,
      fiber_g: 0,
      sugar_g: 1,
      sodium_mg: 420,
    },
  },
  {
    title: 'Karaage',
    description: 'Japanese-style fried chicken marinated in soy-ginger, coated in potato starch.',
    cuisine: 'Japanese',
    prep_minutes: 20,
    cook_minutes: 8,
    servings: 4,
    calories: 320,
    ingredients: [
      { name: 'chicken thigh', quantity: '1', unit: 'lb, boneless, cubed' },
      { name: 'soy sauce', quantity: '2', unit: 'tbsp' },
      { name: 'ginger', quantity: '1', unit: 'tbsp, grated' },
      { name: 'garlic', quantity: '2', unit: 'cloves, minced' },
      { name: 'sake', quantity: '1', unit: 'tbsp' },
      { name: 'potato starch', quantity: '1', unit: 'cup' },
      { name: 'lemon', quantity: '1', unit: 'wedges' },
      { name: 'Japanese mayo', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Marinate chicken in soy sauce, ginger, garlic, and sake for 30 minutes.',
      'Coat chicken pieces in potato starch.',
      'Deep fry at 340°F for 4 minutes. Remove.',
      'Increase oil to 375°F and fry again for 2 minutes until extra crispy.',
      'Drain on paper towels.',
      'Serve with lemon wedges and Japanese mayo.',
    ],
    tags: ['japanese', 'fried-chicken', 'appetizer', 'crispy', 'ginger'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 24,
      carbs_g: 16,
      fat_g: 18,
      fiber_g: 0,
      sugar_g: 2,
      sodium_mg: 680,
    },
  },
  {
    title: 'Dorayaki',
    description: 'Two fluffy pancake-like discs sandwiched with sweet red bean paste.',
    cuisine: 'Japanese',
    prep_minutes: 10,
    cook_minutes: 10,
    servings: 6,
    calories: 180,
    ingredients: [
      { name: 'flour', quantity: '1', unit: 'cup' },
      { name: 'egg', quantity: '2', unit: 'large' },
      { name: 'sugar', quantity: '1/3', unit: 'cup' },
      { name: 'honey', quantity: '2', unit: 'tbsp' },
      { name: 'baking soda', quantity: '1/2', unit: 'tsp' },
      { name: 'water', quantity: '2', unit: 'tbsp' },
      { name: 'red bean paste', quantity: '1', unit: 'cup' },
    ],
    steps: [
      'Beat eggs and sugar. Add honey and water.',
      'Sift in flour and baking soda. Mix until smooth. Rest 30 minutes.',
      'Cook small pancakes on a non-stick pan until bubbly, then flip.',
      'Cool the pancakes.',
      'Spread red bean paste on one pancake, top with another.',
      'Serve as a snack or dessert.',
    ],
    tags: ['japanese', 'dessert', 'pancake', 'red-bean', 'sweet'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 180,
      protein_g: 4,
      carbs_g: 34,
      fat_g: 3,
      fiber_g: 1,
      sugar_g: 18,
      sodium_mg: 160,
    },
  },
  {
    title: 'Miso Soup',
    description: 'Classic Japanese soup with dashi, miso paste, tofu, and wakame seaweed.',
    cuisine: 'Japanese',
    prep_minutes: 5,
    cook_minutes: 5,
    servings: 4,
    calories: 60,
    ingredients: [
      { name: 'dashi', quantity: '4', unit: 'cups' },
      { name: 'miso paste', quantity: '3', unit: 'tbsp' },
      { name: 'silken tofu', quantity: '1/2', unit: 'block, cubed' },
      { name: 'wakame', quantity: '1', unit: 'tbsp, dried' },
      { name: 'green onion', quantity: '2', unit: 'sliced' },
    ],
    steps: [
      'Bring dashi to a simmer.',
      'Add wakame and tofu. Simmer 2 minutes.',
      'Remove from heat. Dissolve miso paste in a ladle of broth, then stir in.',
      'Never boil miso — it kills the beneficial cultures.',
      'Ladle into bowls.',
      'Garnish with green onion.',
    ],
    tags: ['japanese', 'soup', 'miso', 'tofu', 'quick'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 60,
      protein_g: 4,
      carbs_g: 4,
      fat_g: 2,
      fiber_g: 0,
      sugar_g: 1,
      sodium_mg: 620,
    },
  },
  {
    title: 'Teriyaki Salmon',
    description: 'Glazed salmon fillet with sweet soy teriyaki sauce, served with steamed rice.',
    cuisine: 'Japanese',
    prep_minutes: 10,
    cook_minutes: 10,
    servings: 4,
    calories: 340,
    ingredients: [
      { name: 'salmon fillet', quantity: '4', unit: '(6 oz each)' },
      { name: 'soy sauce', quantity: '3', unit: 'tbsp' },
      { name: 'mirin', quantity: '2', unit: 'tbsp' },
      { name: 'sake', quantity: '1', unit: 'tbsp' },
      { name: 'sugar', quantity: '1', unit: 'tbsp' },
      { name: 'ginger', quantity: '1', unit: 'tsp, grated' },
      { name: 'steamed rice', quantity: '4', unit: 'cups' },
      { name: 'sesame seeds', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Mix soy sauce, mirin, sake, sugar, and ginger for teriyaki sauce.',
      'Pan-sear salmon skin-side down until crispy.',
      'Flip and pour teriyaki sauce into the pan.',
      'Baste salmon with the sauce as it reduces and thickens.',
      'Cook until salmon is glazed and cooked through.',
      'Serve over rice, sprinkled with sesame seeds.',
    ],
    tags: ['japanese', 'salmon', 'teriyaki', 'fish', 'quick'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 340,
      protein_g: 32,
      carbs_g: 20,
      fat_g: 14,
      fiber_g: 0,
      sugar_g: 8,
      sodium_mg: 720,
    },
  },
  {
    title: 'Chawanmushi',
    description: 'Silky steamed egg custard with dashi, chicken, shrimp, and gingko nuts.',
    cuisine: 'Japanese',
    prep_minutes: 10,
    cook_minutes: 15,
    servings: 4,
    calories: 100,
    ingredients: [
      { name: 'egg', quantity: '3', unit: 'large' },
      { name: 'dashi', quantity: '1.5', unit: 'cups' },
      { name: 'soy sauce', quantity: '1', unit: 'tsp' },
      { name: 'mirin', quantity: '1', unit: 'tsp' },
      { name: 'chicken', quantity: '2', unit: 'oz, diced' },
      { name: 'shrimp', quantity: '4', unit: 'small' },
      { name: 'shiitake mushroom', quantity: '4', unit: 'sliced' },
      { name: 'mitsuba', quantity: '4', unit: 'sprigs' },
    ],
    steps: [
      'Beat eggs gently. Add cooled dashi, soy sauce, and mirin. Strain.',
      'Place chicken, shrimp, and mushroom in ramekins.',
      'Pour egg mixture over the fillings.',
      'Cover with foil and steam at low heat for 12-15 minutes.',
      'Test with a skewer — it should come out clean.',
      'Garnish with mitsuba and serve warm.',
    ],
    tags: ['japanese', 'custard', 'egg', 'appetizer', 'steamed'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 100,
      protein_g: 10,
      carbs_g: 2,
      fat_g: 6,
      fiber_g: 0,
      sugar_g: 1,
      sodium_mg: 320,
    },
  },
];

export const japaneseRecipes = generateCuisineRecipes(configs);
