import type { CuisineRecipeConfig } from './types';
import { generateCuisineRecipes } from './types';

const configs: CuisineRecipeConfig[] = [
  {
    title: 'Korean BBQ (Bulgogi)',
    description: 'Thinly sliced marinated beef grilled with pear-soy sauce, garlic, and sesame.',
    cuisine: 'Korean',
    prep_minutes: 20,
    cook_minutes: 10,
    servings: 4,
    calories: 320,
    ingredients: [
      { name: 'beef sirloin', quantity: '1.5', unit: 'lb, thinly sliced' },
      { name: 'soy sauce', quantity: '3', unit: 'tbsp' },
      { name: 'Asian pear', quantity: '1/2', unit: 'grated' },
      { name: 'garlic', quantity: '4', unit: 'cloves, minced' },
      { name: 'ginger', quantity: '1', unit: 'tsp, grated' },
      { name: 'sesame oil', quantity: '1', unit: 'tbsp' },
      { name: 'sugar', quantity: '1', unit: 'tbsp' },
      { name: 'green onion', quantity: '4', unit: 'sliced' },
      { name: 'sesame seeds', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Mix soy sauce, grated pear, garlic, ginger, sesame oil, and sugar.',
      'Marinate beef for at least 2 hours.',
      'Grill on a hot griddle or BBQ until charred, 2-3 minutes per side.',
      'Garnish with green onion and sesame seeds.',
      'Serve with rice, lettuce wraps, and banchan.',
      'Wrap in lettuce with ssamjang sauce.',
    ],
    tags: ['korean', 'bbq', 'beef', 'grilled', 'bulgogi'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 36,
      carbs_g: 12,
      fat_g: 14,
      fiber_g: 1,
      sugar_g: 6,
      sodium_mg: 720,
    },
  },
  {
    title: 'Kimchi Jjigae',
    description: 'Spicy, tangy kimchi stew with pork belly, tofu, and a rich fermented broth.',
    cuisine: 'Korean',
    prep_minutes: 10,
    cook_minutes: 25,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'aged kimchi', quantity: '2', unit: 'cups, chopped' },
      { name: 'pork belly', quantity: '8', unit: 'oz, sliced' },
      { name: 'tofu', quantity: '1', unit: 'block, cubed' },
      { name: 'kimchi brine', quantity: '1/4', unit: 'cup' },
      { name: 'gochugaru', quantity: '1', unit: 'tbsp' },
      { name: 'garlic', quantity: '3', unit: 'cloves, minced' },
      { name: 'onion', quantity: '1/2', unit: 'sliced' },
      { name: 'green onion', quantity: '3', unit: 'cut' },
    ],
    steps: [
      'Sauté pork belly until some fat renders.',
      'Add kimchi and onion. Sauté 5 minutes.',
      'Add kimchi brine, gochugaru, garlic, and water.',
      'Bring to a boil, add tofu.',
      'Simmer 15 minutes.',
      'Serve bubbling hot with rice.',
    ],
    tags: ['korean', 'stew', 'kimchi', 'pork', 'spicy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 280,
      protein_g: 18,
      carbs_g: 8,
      fat_g: 18,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 860,
    },
  },
  {
    title: 'Bibimbap',
    description: 'Mixed rice bowl with sautéed vegetables, gochujang, egg, and optional beef.',
    cuisine: 'Korean',
    prep_minutes: 25,
    cook_minutes: 15,
    servings: 4,
    calories: 420,
    ingredients: [
      { name: 'steamed rice', quantity: '4', unit: 'cups' },
      { name: 'spinach', quantity: '2', unit: 'cups, blanched & seasoned' },
      { name: 'carrot', quantity: '1', unit: 'julienned & sautéed' },
      { name: 'zucchini', quantity: '1', unit: 'sautéed' },
      { name: 'bean sprouts', quantity: '1', unit: 'cup, blanched' },
      { name: 'egg', quantity: '4', unit: 'fried' },
      { name: 'gochujang', quantity: '2', unit: 'tbsp' },
      { name: 'sesame oil', quantity: '1', unit: 'tbsp' },
      { name: 'beef (optional)', quantity: '1/2', unit: 'lb, sautéed' },
    ],
    steps: [
      'Prepare each vegetable separately: blanch, sauté, and season with sesame oil and salt.',
      'Cook beef if using, with soy sauce and sesame oil.',
      'Place hot rice in bowls. Arrange vegetables and beef in sections.',
      'Top with a fried egg.',
      'Add gochujang and sesame oil.',
      'Mix everything together before eating.',
    ],
    tags: ['korean', 'rice-bowl', 'vegetables', 'egg', 'gochujang'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 18,
      carbs_g: 56,
      fat_g: 12,
      fiber_g: 4,
      sugar_g: 4,
      sodium_mg: 680,
    },
  },
  {
    title: 'Japchae',
    description: 'Korean glass noodle stir-fry with vegetables, beef, and sesame-soy sauce.',
    cuisine: 'Korean',
    prep_minutes: 20,
    cook_minutes: 15,
    servings: 6,
    calories: 280,
    ingredients: [
      { name: 'sweet potato noodles', quantity: '8', unit: 'oz' },
      { name: 'beef', quantity: '1/2', unit: 'lb, sliced thin' },
      { name: 'spinach', quantity: '1', unit: 'cup, blanched' },
      { name: 'carrot', quantity: '1', unit: 'julienned' },
      { name: 'mushroom', quantity: '1', unit: 'cup, sliced' },
      { name: 'soy sauce', quantity: '3', unit: 'tbsp' },
      { name: 'sesame oil', quantity: '2', unit: 'tbsp' },
      { name: 'sugar', quantity: '1', unit: 'tbsp' },
      { name: 'sesame seeds', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Soak and boil noodles until tender. Rinse and cut.',
      'Sauté each vegetable and beef separately. Season each with sesame oil and salt.',
      'Combine all ingredients in a large bowl.',
      'Add soy sauce, sesame oil, and sugar. Toss well.',
      'Garnish with sesame seeds.',
      'Serve warm or at room temperature.',
    ],
    tags: ['korean', 'noodles', 'stir-fry', 'beef', 'sesame'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 16,
      carbs_g: 36,
      fat_g: 8,
      fiber_g: 2,
      sugar_g: 4,
      sodium_mg: 680,
    },
  },
  {
    title: 'Tteokbokki',
    description: 'Chewy rice cakes in a fiery gochujang sauce with fish cake and boiled egg.',
    cuisine: 'Korean',
    prep_minutes: 10,
    cook_minutes: 15,
    servings: 4,
    calories: 320,
    ingredients: [
      { name: 'rice cakes', quantity: '1', unit: 'lb, cylindrical' },
      { name: 'fish cake', quantity: '4', unit: 'oz, sliced' },
      { name: 'gochujang', quantity: '3', unit: 'tbsp' },
      { name: 'gochugaru', quantity: '1', unit: 'tbsp' },
      { name: 'soy sauce', quantity: '1', unit: 'tbsp' },
      { name: 'sugar', quantity: '1', unit: 'tbsp' },
      { name: 'hard-boiled egg', quantity: '2', unit: 'halved' },
      { name: 'green onion', quantity: '3', unit: 'cut' },
    ],
    steps: [
      'Soak rice cakes in warm water for 10 minutes.',
      'Bring 2 cups water to a boil with gochujang, gochugaru, soy sauce, and sugar.',
      'Add rice cakes and fish cake. Stir.',
      'Simmer 10-15 minutes until sauce thickens and coats the rice cakes.',
      'Add boiled eggs and green onion.',
      'Serve hot as a street-food snack.',
    ],
    tags: ['korean', 'rice-cake', 'spicy', 'street-food', 'snack'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 10,
      carbs_g: 56,
      fat_g: 4,
      fiber_g: 2,
      sugar_g: 8,
      sodium_mg: 860,
    },
  },
  {
    title: 'Korean Fried Chicken',
    description: 'Double-fried crispy chicken glazed in a sweet-spicy gochujang sauce.',
    cuisine: 'Korean',
    prep_minutes: 15,
    cook_minutes: 15,
    servings: 4,
    calories: 420,
    ingredients: [
      { name: 'chicken wings', quantity: '2', unit: 'lb' },
      { name: 'cornstarch', quantity: '1/2', unit: 'cup' },
      { name: 'flour', quantity: '1/2', unit: 'cup' },
      { name: 'gochujang', quantity: '2', unit: 'tbsp' },
      { name: 'soy sauce', quantity: '2', unit: 'tbsp' },
      { name: 'honey', quantity: '2', unit: 'tbsp' },
      { name: 'garlic', quantity: '3', unit: 'cloves, minced' },
      { name: 'sesame seeds', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Season wings. Dredge in flour-cornstarch mix.',
      'First fry at 325°F for 8 minutes. Rest 10 minutes.',
      'Second fry at 375°F for 3 minutes until extra crispy.',
      'Make glaze: simmer gochujang, soy sauce, honey, and garlic.',
      'Toss crispy wings in the glaze.',
      'Garnish with sesame seeds and serve.',
    ],
    tags: ['korean', 'fried-chicken', 'spicy', 'sweet', 'crispy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 28,
      carbs_g: 24,
      fat_g: 22,
      fiber_g: 0,
      sugar_g: 10,
      sodium_mg: 780,
    },
  },
  {
    title: 'Sundubu Jjigae',
    description:
      'Silken tofu stew with seafood or meat in a spicy gochugaru broth, served bubbling hot.',
    cuisine: 'Korean',
    prep_minutes: 10,
    cook_minutes: 15,
    servings: 4,
    calories: 220,
    ingredients: [
      { name: 'silken tofu', quantity: '1', unit: 'block' },
      { name: 'gochugaru', quantity: '2', unit: 'tbsp' },
      { name: 'garlic', quantity: '3', unit: 'cloves, minced' },
      { name: 'shrimp', quantity: '1/2', unit: 'cup' },
      { name: 'clam', quantity: '6', unit: 'whole' },
      { name: 'zucchini', quantity: '1/2', unit: 'sliced' },
      { name: 'egg', quantity: '1', unit: 'raw' },
      { name: 'green onion', quantity: '2', unit: 'cut' },
    ],
    steps: [
      'Sauté garlic and gochugaru in sesame oil.',
      'Add zucchini and cook 2 minutes.',
      'Add water, bring to a boil.',
      'Add tofu (scoop directly from package), shrimp, and clams.',
      'Simmer 5 minutes until clams open.',
      'Crack a raw egg on top, serve bubbling in a stone pot.',
    ],
    tags: ['korean', 'stew', 'tofu', 'spicy', 'seafood'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 220,
      protein_g: 18,
      carbs_g: 8,
      fat_g: 10,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 680,
    },
  },
  {
    title: 'Kimbap',
    description: 'Korean seaweed rice rolls filled with vegetables, egg, and pickled radish.',
    cuisine: 'Korean',
    prep_minutes: 25,
    cook_minutes: 10,
    servings: 6,
    calories: 200,
    ingredients: [
      { name: 'sushi rice', quantity: '3', unit: 'cups, cooked & seasoned' },
      { name: 'nori', quantity: '6', unit: 'sheets' },
      { name: 'spinach', quantity: '1', unit: 'cup, blanched & seasoned' },
      { name: 'carrot', quantity: '1', unit: 'julienned & sautéed' },
      { name: 'egg', quantity: '2', unit: 'cooked as jidan, sliced' },
      { name: 'pickled radish', quantity: '6', unit: 'sticks' },
      { name: 'cucumber', quantity: '1', unit: 'sticks' },
      { name: 'sesame oil', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Season rice with sesame oil and salt.',
      'Prepare all fillings: sauté spinach, carrot, make egg jidan.',
      'Place nori on a bamboo mat, spread rice evenly, leaving 1 inch at top.',
      'Lay fillings in a line across the center.',
      'Roll tightly using the mat, seal edge with water.',
      'Slice with a wet knife into rounds.',
    ],
    tags: ['korean', 'rice-roll', 'seaweed', 'portable', 'vegetarian'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 200,
      protein_g: 6,
      carbs_g: 34,
      fat_g: 4,
      fiber_g: 2,
      sugar_g: 2,
      sodium_mg: 420,
    },
  },
  {
    title: 'Samgyeopsal',
    description: 'Thick pork belly slices grilled at the table, wrapped in lettuce with ssamjang.',
    cuisine: 'Korean',
    prep_minutes: 10,
    cook_minutes: 10,
    servings: 4,
    calories: 380,
    ingredients: [
      { name: 'pork belly', quantity: '1.5', unit: 'lb, thickly sliced' },
      { name: 'lettuce', quantity: '1', unit: 'head, leaves separated' },
      { name: 'ssamjang', quantity: '3', unit: 'tbsp' },
      { name: 'garlic', quantity: '1', unit: 'head, sliced' },
      { name: 'green chili', quantity: '4', unit: 'sliced' },
      { name: 'kimchi', quantity: '1', unit: 'cup' },
      { name: 'steamed rice', quantity: '4', unit: 'cups' },
    ],
    steps: [
      'Grill pork belly slices on a tabletop grill until crispy on both sides.',
      'Grill garlic and kimchi alongside.',
      'Place a lettuce leaf in your palm.',
      'Add rice, pork belly, ssamjang, garlic, and kimchi.',
      'Wrap into a bundle.',
      'Eat in one bite!',
    ],
    tags: ['korean', 'bbq', 'pork', 'grilled', 'wrap'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 380,
      protein_g: 18,
      carbs_g: 24,
      fat_g: 22,
      fiber_g: 2,
      sugar_g: 2,
      sodium_mg: 860,
    },
  },
  {
    title: 'Haemul Pajeon',
    description: 'Crispy Korean seafood pancake with green onion, shrimp, and a soy-vinegar dip.',
    cuisine: 'Korean',
    prep_minutes: 15,
    cook_minutes: 10,
    servings: 4,
    calories: 240,
    ingredients: [
      { name: 'flour', quantity: '1', unit: 'cup' },
      { name: 'egg', quantity: '2', unit: 'large' },
      { name: 'green onion', quantity: '8', unit: 'stalks' },
      { name: 'shrimp', quantity: '1/2', unit: 'cup, small' },
      { name: 'squid', quantity: '1/4', unit: 'cup, sliced' },
      { name: 'rice flour', quantity: '1/4', unit: 'cup' },
      { name: 'ice water', quantity: '1', unit: 'cup' },
      { name: 'soy sauce', quantity: '2', unit: 'tbsp (for dip)' },
    ],
    steps: [
      'Mix flour, rice flour, egg, and ice water into a thin batter.',
      'Lay green onions in a hot oiled pan.',
      'Pour batter over, add seafood on top.',
      'Cook until bottom is crispy, flip carefully.',
      'Cook other side until golden.',
      'Cut into pieces and serve with soy-vinegar dipping sauce.',
    ],
    tags: ['korean', 'pancake', 'seafood', 'green-onion', 'appetizer'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 240,
      protein_g: 14,
      carbs_g: 24,
      fat_g: 8,
      fiber_g: 2,
      sugar_g: 2,
      sodium_mg: 680,
    },
  },
  {
    title: 'Doenjang Jjigae',
    description: 'Hearty Korean soybean paste stew with tofu, zucchini, and mushrooms.',
    cuisine: 'Korean',
    prep_minutes: 10,
    cook_minutes: 15,
    servings: 4,
    calories: 180,
    ingredients: [
      { name: 'doenjang (soybean paste)', quantity: '3', unit: 'tbsp' },
      { name: 'tofu', quantity: '1', unit: 'block, cubed' },
      { name: 'zucchini', quantity: '1/2', unit: 'sliced' },
      { name: 'mushroom', quantity: '1', unit: 'cup, sliced' },
      { name: 'onion', quantity: '1/2', unit: 'sliced' },
      { name: 'garlic', quantity: '2', unit: 'cloves, minced' },
      { name: 'gochugaru', quantity: '1', unit: 'tsp' },
      { name: 'green onion', quantity: '2', unit: 'cut' },
    ],
    steps: [
      'Dissolve doenjang in water or anchovy broth.',
      'Add onion, zucchini, and mushroom. Bring to a boil.',
      'Add tofu and gochugaru.',
      'Simmer 10 minutes.',
      'Add garlic and green onion.',
      'Serve hot with rice.',
    ],
    tags: ['korean', 'stew', 'tofu', 'soybean-paste', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 180,
      protein_g: 12,
      carbs_g: 12,
      fat_g: 8,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 780,
    },
  },
  {
    title: 'Korean Corn Dog',
    description: 'Sausage on a stick coated in batter and panko, fried and rolled in sugar.',
    cuisine: 'Korean',
    prep_minutes: 15,
    cook_minutes: 8,
    servings: 6,
    calories: 340,
    ingredients: [
      { name: 'hot dog', quantity: '6', unit: 'pieces' },
      { name: 'mozzarella cheese', quantity: '6', unit: 'sticks' },
      { name: 'flour', quantity: '1', unit: 'cup' },
      { name: 'sugar', quantity: '2', unit: 'tbsp' },
      { name: 'yeast', quantity: '1', unit: 'tsp' },
      { name: 'panko', quantity: '1', unit: 'cup' },
      { name: 'ketchup', quantity: '1/4', unit: 'cup' },
      { name: 'mustard', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Make a yeast batter with flour, sugar, and warm water. Let rise.',
      'Skewer hot dogs, optionally with mozzarella sticks.',
      'Dip in batter, then roll in panko.',
      'Deep fry at 350°F until golden.',
      'Roll in sugar while hot.',
      'Drizzle with ketchup and mustard.',
    ],
    tags: ['korean', 'street-food', 'corn-dog', 'fried', 'snack'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 340,
      protein_g: 12,
      carbs_g: 32,
      fat_g: 18,
      fiber_g: 1,
      sugar_g: 6,
      sodium_mg: 720,
    },
  },
  {
    title: 'Yukgaejang',
    description: 'Spicy shredded beef soup with fernbrake, bean sprouts, and a rich red broth.',
    cuisine: 'Korean',
    prep_minutes: 15,
    cook_minutes: 60,
    servings: 4,
    calories: 240,
    ingredients: [
      { name: 'beef brisket', quantity: '1', unit: 'lb' },
      { name: 'gosari (fernbrake)', quantity: '1', unit: 'cup, soaked' },
      { name: 'bean sprouts', quantity: '1', unit: 'cup' },
      { name: 'gochugaru', quantity: '2', unit: 'tbsp' },
      { name: 'garlic', quantity: '4', unit: 'cloves, minced' },
      { name: 'soy sauce', quantity: '2', unit: 'tbsp' },
      { name: 'sesame oil', quantity: '1', unit: 'tbsp' },
      { name: 'green onion', quantity: '3', unit: 'cut' },
    ],
    steps: [
      'Boil beef until tender, about 45 minutes. Reserve broth.',
      'Shred beef when cool enough to handle.',
      'Season shredded beef with gochugaru, garlic, soy sauce, and sesame oil.',
      'Add seasoned beef and gosari to the broth.',
      'Add bean sprouts and simmer 15 minutes.',
      'Serve hot with rice and green onion.',
    ],
    tags: ['korean', 'soup', 'beef', 'spicy', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 240,
      protein_g: 26,
      carbs_g: 8,
      fat_g: 10,
      fiber_g: 2,
      sugar_g: 2,
      sodium_mg: 780,
    },
  },
  {
    title: 'Hotteok',
    description: 'Korean sweet pancake filled with brown sugar, cinnamon, and chopped nuts.',
    cuisine: 'Korean',
    prep_minutes: 20,
    cook_minutes: 8,
    servings: 6,
    calories: 220,
    ingredients: [
      { name: 'flour', quantity: '2', unit: 'cups' },
      { name: 'yeast', quantity: '1', unit: 'tsp' },
      { name: 'brown sugar', quantity: '1/2', unit: 'cup' },
      { name: 'cinnamon', quantity: '1', unit: 'tsp' },
      { name: 'chopped peanuts', quantity: '1/4', unit: 'cup' },
      { name: 'oil', quantity: '2', unit: 'tbsp, for frying' },
      { name: 'warm water', quantity: '3/4', unit: 'cup' },
    ],
    steps: [
      'Make a soft yeast dough. Let rise 1 hour.',
      'Mix brown sugar, cinnamon, and peanuts for filling.',
      'Divide dough into balls. Flatten, add filling, seal.',
      'Pan-fry in oil, pressing flat with a spatula.',
      'Cook until golden on both sides.',
      'Serve hot — be careful of the molten filling!',
    ],
    tags: ['korean', 'pancake', 'sweet', 'street-food', 'dessert'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 220,
      protein_g: 4,
      carbs_g: 36,
      fat_g: 7,
      fiber_g: 1,
      sugar_g: 16,
      sodium_mg: 120,
    },
  },
];

export const koreanRecipes = generateCuisineRecipes(configs);
