import type { CuisineRecipeConfig } from './types';
import { generateCuisineRecipes } from './types';

const configs: CuisineRecipeConfig[] = [
  {
    title: 'Beef Empanadas',
    description:
      'Flaky pastry turnovers filled with seasoned ground beef, onions, olives, and hard-boiled eggs.',
    cuisine: 'Latin American',
    prep_minutes: 30,
    cook_minutes: 25,
    servings: 6,
    calories: 420,
    ingredients: [
      { name: 'ground beef', quantity: '1', unit: 'lb' },
      { name: 'onion', quantity: '1', unit: 'medium, diced' },
      { name: 'green olives', quantity: '1/4', unit: 'cup, chopped' },
      { name: 'hard-boiled egg', quantity: '2', unit: 'chopped' },
      { name: 'cumin', quantity: '1', unit: 'tsp' },
      { name: 'paprika', quantity: '1', unit: 'tsp' },
      { name: 'empanada discs', quantity: '12', unit: 'pieces' },
      { name: 'egg wash', quantity: '1', unit: 'egg, beaten' },
    ],
    steps: [
      'Cook ground beef with onion until browned. Season with cumin, paprika, salt, and pepper.',
      'Add chopped olives and hard-boiled eggs. Let cool slightly.',
      'Place filling on empanada discs, fold, and crimp edges with a fork.',
      'Brush with egg wash and bake at 375°F for 20-25 minutes until golden.',
    ],
    tags: ['empanada', 'beef', 'pastry', 'handheld', 'baked'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 22,
      carbs_g: 30,
      fat_g: 24,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 580,
    },
  },
  {
    title: 'Ceviche',
    description: 'Fresh white fish cured in citrus juice with red onion, cilantro, and aji pepper.',
    cuisine: 'Latin American',
    prep_minutes: 25,
    cook_minutes: 0,
    servings: 4,
    calories: 150,
    ingredients: [
      { name: 'white fish fillet', quantity: '1', unit: 'lb, cubed' },
      { name: 'lime juice', quantity: '1', unit: 'cup' },
      { name: 'red onion', quantity: '1', unit: 'small, sliced thin' },
      { name: 'cilantro', quantity: '1/2', unit: 'cup, chopped' },
      { name: 'aji amarillo paste', quantity: '1', unit: 'tbsp' },
      { name: 'salt', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Cube fish into small pieces and place in a glass bowl.',
      'Pour lime juice over fish, making sure all pieces are submerged. Refrigerate for 20 minutes.',
      'Drain excess juice, add sliced red onion, cilantro, and aji paste.',
      'Season with salt and serve immediately with sweet potato or corn.',
    ],
    tags: ['ceviche', 'seafood', 'no-cook', 'fresh', 'light'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 150,
      protein_g: 28,
      carbs_g: 6,
      fat_g: 2,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 340,
    },
  },
  {
    title: 'Arepas',
    description: 'Crispy corn cakes split and stuffed with black beans, cheese, and avocado.',
    cuisine: 'Latin American',
    prep_minutes: 15,
    cook_minutes: 15,
    servings: 4,
    calories: 320,
    ingredients: [
      { name: 'pre-cooked cornmeal', quantity: '2', unit: 'cups' },
      { name: 'warm water', quantity: '2.5', unit: 'cups' },
      { name: 'salt', quantity: '1', unit: 'tsp' },
      { name: 'black beans', quantity: '1', unit: 'can, drained' },
      { name: 'queso fresco', quantity: '1/2', unit: 'cup, crumbled' },
      { name: 'avocado', quantity: '1', unit: 'sliced' },
    ],
    steps: [
      'Mix cornmeal, salt, and warm water. Let rest 5 minutes.',
      'Form dough into 4-inch patties about 3/4 inch thick.',
      'Cook on a greased griddle over medium heat for 5 minutes per side until golden.',
      'Split open and fill with black beans, queso fresco, and avocado slices.',
    ],
    tags: ['arepa', 'venezuelan', 'corn', 'stuffed', 'vegetarian'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 12,
      carbs_g: 42,
      fat_g: 12,
      fiber_g: 8,
      sugar_g: 2,
      sodium_mg: 420,
    },
  },
  {
    title: 'Tres Leches Cake',
    description: 'Light sponge cake soaked in three kinds of milk, topped with whipped cream.',
    cuisine: 'Latin American',
    prep_minutes: 25,
    cook_minutes: 30,
    servings: 10,
    calories: 380,
    ingredients: [
      { name: 'all-purpose flour', quantity: '1.5', unit: 'cups' },
      { name: 'sugar', quantity: '1', unit: 'cup' },
      { name: 'eggs', quantity: '5', unit: 'large' },
      { name: 'whole milk', quantity: '1', unit: 'cup' },
      { name: 'evaporated milk', quantity: '1', unit: 'can' },
      { name: 'sweetened condensed milk', quantity: '1', unit: 'can' },
      { name: 'heavy cream', quantity: '1.5', unit: 'cups' },
      { name: 'vanilla extract', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Bake sponge cake: beat eggs and sugar until fluffy, fold in flour and milk. Bake at 350°F for 25-30 minutes.',
      'Let cake cool, then poke holes all over with a fork.',
      'Mix whole milk, evaporated milk, and condensed milk. Pour over cake slowly. Refrigerate 2 hours.',
      'Whip heavy cream with vanilla and spread over cake before serving.',
    ],
    tags: ['tres leches', 'cake', 'dessert', 'milk', 'sweet'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 8,
      carbs_g: 52,
      fat_g: 16,
      fiber_g: 0,
      sugar_g: 40,
      sodium_mg: 180,
    },
  },
  {
    title: 'Ropa Vieja',
    description:
      'Cuban shredded beef stew with bell peppers, onions, and tomatoes served over rice.',
    cuisine: 'Latin American',
    prep_minutes: 20,
    cook_minutes: 180,
    servings: 6,
    calories: 450,
    ingredients: [
      { name: 'flank steak', quantity: '2', unit: 'lbs' },
      { name: 'onion', quantity: '1', unit: 'large, sliced' },
      { name: 'green bell pepper', quantity: '1', unit: 'sliced' },
      { name: 'garlic', quantity: '4', unit: 'cloves, minced' },
      { name: 'crushed tomatoes', quantity: '1', unit: 'can (28 oz)' },
      { name: 'cumin', quantity: '1', unit: 'tbsp' },
      { name: 'oregano', quantity: '1', unit: 'tsp' },
      { name: 'white rice', quantity: '2', unit: 'cups, cooked' },
    ],
    steps: [
      'Brown flank steak in a large pot, then add water to cover. Simmer 2 hours until tender.',
      'Shred the beef with two forks and return to pot.',
      'Add onion, bell pepper, garlic, tomatoes, cumin, and oregano.',
      'Simmer for another 30 minutes until flavors meld. Serve over white rice.',
    ],
    tags: ['ropa vieja', 'cuban', 'beef', 'stew', 'shredded'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 450,
      protein_g: 38,
      carbs_g: 28,
      fat_g: 20,
      fiber_g: 4,
      sugar_g: 6,
      sodium_mg: 620,
    },
  },
  {
    title: 'Chimichurri Grilled Steak',
    description:
      'Grilled flank steak topped with vibrant Argentine chimichurri sauce of parsley, garlic, and oregano.',
    cuisine: 'Latin American',
    prep_minutes: 15,
    cook_minutes: 12,
    servings: 4,
    calories: 380,
    ingredients: [
      { name: 'flank steak', quantity: '1.5', unit: 'lbs' },
      { name: 'fresh parsley', quantity: '1', unit: 'cup, chopped' },
      { name: 'garlic', quantity: '4', unit: 'cloves, minced' },
      { name: 'oregano', quantity: '1', unit: 'tbsp' },
      { name: 'red wine vinegar', quantity: '3', unit: 'tbsp' },
      { name: 'olive oil', quantity: '1/2', unit: 'cup' },
      { name: 'red pepper flakes', quantity: '1/2', unit: 'tsp' },
    ],
    steps: [
      'Make chimichurri: combine parsley, garlic, oregano, vinegar, olive oil, and red pepper flakes. Let sit 15 minutes.',
      'Season steak with salt and pepper. Grill over high heat 4-5 minutes per side for medium-rare.',
      'Let rest 5 minutes, then slice against the grain.',
      'Spoon chimichurri generously over sliced steak and serve.',
    ],
    tags: ['chimichurri', 'argentine', 'grilled', 'steak', 'sauce'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 380,
      protein_g: 42,
      carbs_g: 3,
      fat_g: 22,
      fiber_g: 1,
      sugar_g: 0,
      sodium_mg: 280,
    },
  },
  {
    title: 'Pupusas with Curtido',
    description:
      'Thick Salvadoran corn tortillas stuffed with cheese and beans, served with tangy cabbage slaw.',
    cuisine: 'Latin American',
    prep_minutes: 30,
    cook_minutes: 15,
    servings: 6,
    calories: 290,
    ingredients: [
      { name: 'masa harina', quantity: '2', unit: 'cups' },
      { name: 'warm water', quantity: '1.5', unit: 'cups' },
      { name: 'refried beans', quantity: '1', unit: 'cup' },
      { name: 'queso fresco', quantity: '1', unit: 'cup, crumbled' },
      { name: 'cabbage', quantity: '2', unit: 'cups, shredded' },
      { name: 'carrot', quantity: '1', unit: 'shredded' },
      { name: 'vinegar', quantity: '1/2', unit: 'cup' },
      { name: 'oregano', quantity: '1/2', unit: 'tsp' },
    ],
    steps: [
      'Make curtido: toss cabbage, carrot, vinegar, oregano, and salt. Refrigerate 30 minutes.',
      'Mix masa harina with water to form a dough. Divide into 8 balls.',
      'Flatten each ball, add beans and cheese filling, and seal edges. Flatten into thick discs.',
      'Cook on a dry griddle 3-4 minutes per side until golden. Serve with curtido.',
    ],
    tags: ['pupusa', 'salvadoran', 'corn', 'stuffed', 'vegetarian'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 290,
      protein_g: 12,
      carbs_g: 38,
      fat_g: 10,
      fiber_g: 6,
      sugar_g: 3,
      sodium_mg: 460,
    },
  },
  {
    title: 'Feijoada',
    description:
      'Brazilian black bean stew with smoked meats, served with rice, farofa, and orange slices.',
    cuisine: 'Latin American',
    prep_minutes: 30,
    cook_minutes: 180,
    servings: 8,
    calories: 520,
    ingredients: [
      { name: 'black beans', quantity: '2', unit: 'cups, dried' },
      { name: 'smoked pork ribs', quantity: '1', unit: 'lb' },
      { name: 'smoked sausage', quantity: '1/2', unit: 'lb' },
      { name: 'bacon', quantity: '4', unit: 'oz, diced' },
      { name: 'onion', quantity: '1', unit: 'large, diced' },
      { name: 'garlic', quantity: '4', unit: 'cloves, minced' },
      { name: 'bay leaves', quantity: '2', unit: 'pieces' },
      { name: 'orange', quantity: '1', unit: 'sliced' },
    ],
    steps: [
      'Soak black beans overnight. Drain and rinse.',
      'Brown the smoked meats and bacon in a large pot. Add onion and garlic.',
      'Add beans, bay leaves, and water to cover. Simmer 2-3 hours until beans are tender.',
      'Mash some beans to thicken. Serve with white rice, farofa, and orange slices.',
    ],
    tags: ['feijoada', 'brazilian', 'beans', 'stew', 'pork'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 520,
      protein_g: 34,
      carbs_g: 40,
      fat_g: 24,
      fiber_g: 12,
      sugar_g: 4,
      sodium_mg: 820,
    },
  },
  {
    title: 'Lomo Saltado',
    description:
      'Peruvian stir-fry of marinated beef, onions, tomatoes, and fries served with rice.',
    cuisine: 'Latin American',
    prep_minutes: 20,
    cook_minutes: 15,
    servings: 4,
    calories: 480,
    ingredients: [
      { name: 'sirloin steak', quantity: '1', unit: 'lb, sliced thin' },
      { name: 'red onion', quantity: '1', unit: 'large, sliced' },
      { name: 'tomato', quantity: '2', unit: 'large, wedged' },
      { name: 'soy sauce', quantity: '3', unit: 'tbsp' },
      { name: 'vinegar', quantity: '2', unit: 'tbsp' },
      { name: 'french fries', quantity: '2', unit: 'cups' },
      { name: 'white rice', quantity: '2', unit: 'cups, cooked' },
      { name: 'aji amarillo paste', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Marinate sliced beef in soy sauce, vinegar, and aji paste for 15 minutes.',
      'Stir-fry beef over high heat until browned. Remove and set aside.',
      'Stir-fry onion and tomato until slightly softened. Return beef to pan.',
      'Serve over white rice topped with crispy french fries.',
    ],
    tags: ['lomo saltado', 'peruvian', 'stir-fry', 'beef', 'fusion'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 480,
      protein_g: 32,
      carbs_g: 44,
      fat_g: 20,
      fiber_g: 4,
      sugar_g: 5,
      sodium_mg: 720,
    },
  },
  {
    title: 'Chilaquiles Verdes',
    description:
      'Crispy tortilla chips simmered in green salsa, topped with crema, cheese, and eggs.',
    cuisine: 'Latin American',
    prep_minutes: 15,
    cook_minutes: 15,
    servings: 4,
    calories: 350,
    ingredients: [
      { name: 'tortilla chips', quantity: '4', unit: 'cups' },
      { name: 'green salsa', quantity: '2', unit: 'cups' },
      { name: 'eggs', quantity: '4', unit: 'large, fried' },
      { name: 'Mexican crema', quantity: '1/4', unit: 'cup' },
      { name: 'queso fresco', quantity: '1/2', unit: 'cup, crumbled' },
      { name: 'white onion', quantity: '1/4', unit: 'cup, sliced' },
      { name: 'cilantro', quantity: '2', unit: 'tbsp, chopped' },
    ],
    steps: [
      'Heat salsa in a large skillet until simmering.',
      'Add tortilla chips and toss gently to coat. Cook 2-3 minutes until slightly softened.',
      'Transfer to plates and top with fried eggs, crema, queso fresco, onion, and cilantro.',
      'Serve immediately while chips still have some crunch.',
    ],
    tags: ['chilaquiles', 'breakfast', 'salsa', 'eggs', 'tortilla'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 350,
      protein_g: 16,
      carbs_g: 34,
      fat_g: 18,
      fiber_g: 4,
      sugar_g: 3,
      sodium_mg: 640,
    },
  },
  {
    title: 'Enchiladas Suizas',
    description:
      'Corn tortillas filled with chicken, rolled in creamy tomatillo sauce, and baked with cheese.',
    cuisine: 'Latin American',
    prep_minutes: 25,
    cook_minutes: 25,
    servings: 6,
    calories: 410,
    ingredients: [
      { name: 'shredded chicken', quantity: '3', unit: 'cups' },
      { name: 'corn tortillas', quantity: '12', unit: 'pieces' },
      { name: 'tomatillos', quantity: '1', unit: 'lb, husked' },
      { name: 'sour cream', quantity: '1/2', unit: 'cup' },
      { name: 'monterey jack cheese', quantity: '1.5', unit: 'cups, shredded' },
      { name: 'onion', quantity: '1', unit: 'small, diced' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
      { name: 'cilantro', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Boil tomatillos until soft. Blend with onion, garlic, cilantro, and sour cream for sauce.',
      'Fill each tortilla with shredded chicken, roll tightly, and place seam-down in a baking dish.',
      'Pour tomatillo sauce over enchiladas and top with shredded cheese.',
      'Bake at 375°F for 20 minutes until bubbly and golden.',
    ],
    tags: ['enchiladas', 'chicken', 'tomatillo', 'baked', 'cheese'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 410,
      protein_g: 28,
      carbs_g: 30,
      fat_g: 20,
      fiber_g: 4,
      sugar_g: 4,
      sodium_mg: 540,
    },
  },
  {
    title: 'Tamales de Puerco',
    description: 'Masa-wrapped pork tamales steamed in corn husks with red chile sauce.',
    cuisine: 'Latin American',
    prep_minutes: 60,
    cook_minutes: 90,
    servings: 12,
    calories: 280,
    ingredients: [
      { name: 'masa harina', quantity: '4', unit: 'cups' },
      { name: 'lard', quantity: '1', unit: 'cup' },
      { name: 'shredded pork', quantity: '2', unit: 'cups' },
      { name: 'red chile sauce', quantity: '1.5', unit: 'cups' },
      { name: 'corn husks', quantity: '24', unit: 'pieces, soaked' },
      { name: 'baking powder', quantity: '1', unit: 'tsp' },
      { name: 'salt', quantity: '1', unit: 'tsp' },
      { name: 'chicken broth', quantity: '1', unit: 'cup' },
    ],
    steps: [
      'Beat lard until fluffy. Mix in masa, baking powder, salt, and broth to form soft dough.',
      'Spread masa dough on soaked corn husks, add pork and chile sauce filling.',
      'Fold husks over and tie ends. Stand upright in a steamer.',
      'Steam for 90 minutes until masa pulls away from husks cleanly.',
    ],
    tags: ['tamales', 'pork', 'steamed', 'corn', 'traditional'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 14,
      carbs_g: 24,
      fat_g: 16,
      fiber_g: 3,
      sugar_g: 1,
      sodium_mg: 480,
    },
  },
  {
    title: 'Ajiaco',
    description: 'Colombian chicken and potato soup with corn, capers, avocado, and cream.',
    cuisine: 'Latin American',
    prep_minutes: 20,
    cook_minutes: 60,
    servings: 6,
    calories: 340,
    ingredients: [
      { name: 'chicken thighs', quantity: '2', unit: 'lbs' },
      { name: 'yellow potatoes', quantity: '2', unit: 'lbs, cubed' },
      { name: 'corn on the cob', quantity: '3', unit: 'ears, cut in thirds' },
      { name: 'guascas', quantity: '2', unit: 'tbsp' },
      { name: 'avocado', quantity: '1', unit: 'sliced' },
      { name: 'capers', quantity: '2', unit: 'tbsp' },
      { name: 'heavy cream', quantity: '1/4', unit: 'cup' },
      { name: 'cilantro', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Boil chicken in water with onion and garlic for 30 minutes. Shred and return to pot.',
      'Add potatoes and corn. Cook until potatoes are tender, about 20 minutes.',
      'Add guascas and simmer 10 more minutes. Some potatoes should dissolve to thicken.',
      'Serve with avocado, capers, cream, and cilantro on top.',
    ],
    tags: ['ajiaco', 'colombian', 'soup', 'chicken', 'potato'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 340,
      protein_g: 28,
      carbs_g: 36,
      fat_g: 10,
      fiber_g: 5,
      sugar_g: 4,
      sodium_mg: 380,
    },
  },
  {
    title: 'Patacones',
    description:
      'Twice-fried green plantain discs smashed flat and salted, served with hogao sauce.',
    cuisine: 'Latin American',
    prep_minutes: 10,
    cook_minutes: 15,
    servings: 4,
    calories: 220,
    ingredients: [
      { name: 'green plantains', quantity: '3', unit: 'large' },
      { name: 'vegetable oil', quantity: '2', unit: 'cups, for frying' },
      { name: 'salt', quantity: '1', unit: 'tsp' },
      { name: 'tomato', quantity: '1', unit: 'diced' },
      { name: 'onion', quantity: '1/2', unit: 'diced' },
      { name: 'cumin', quantity: '1/4', unit: 'tsp' },
    ],
    steps: [
      'Peel plantains and cut into 1-inch rounds. Fry in oil for 3 minutes until lightly golden.',
      'Remove and smash each round flat with a press or heavy pan.',
      'Return flattened plantains to oil and fry 2-3 minutes until crispy and golden.',
      'Sprinkle with salt. Serve with hogao sauce (sautéed tomato, onion, cumin).',
    ],
    tags: ['patacones', 'plantain', 'fried', 'snack', 'vegan'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 220,
      protein_g: 2,
      carbs_g: 30,
      fat_g: 11,
      fiber_g: 3,
      sugar_g: 2,
      sodium_mg: 320,
    },
  },
  {
    title: 'Arroz con Leche',
    description: 'Creamy Latin rice pudding with cinnamon, condensed milk, and raisins.',
    cuisine: 'Latin American',
    prep_minutes: 5,
    cook_minutes: 40,
    servings: 6,
    calories: 280,
    ingredients: [
      { name: 'white rice', quantity: '1', unit: 'cup' },
      { name: 'whole milk', quantity: '4', unit: 'cups' },
      { name: 'sweetened condensed milk', quantity: '1', unit: 'can' },
      { name: 'cinnamon stick', quantity: '1', unit: 'piece' },
      { name: 'raisins', quantity: '1/4', unit: 'cup' },
      { name: 'vanilla extract', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Simmer rice with milk and cinnamon stick over medium-low heat, stirring often, for 30 minutes.',
      'Add condensed milk and raisins. Cook 10 more minutes until thick and creamy.',
      'Remove cinnamon stick and stir in vanilla.',
      'Serve warm or chilled, dusted with ground cinnamon.',
    ],
    tags: ['arroz con leche', 'dessert', 'rice pudding', 'cinnamon', 'sweet'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 8,
      carbs_g: 46,
      fat_g: 7,
      fiber_g: 0,
      sugar_g: 32,
      sodium_mg: 120,
    },
  },
  {
    title: 'Cachapas',
    description: 'Venezuelan sweet corn pancakes folded with queso de mano cheese.',
    cuisine: 'Latin American',
    prep_minutes: 15,
    cook_minutes: 10,
    servings: 4,
    calories: 310,
    ingredients: [
      { name: 'fresh corn kernels', quantity: '4', unit: 'cups' },
      { name: 'sugar', quantity: '2', unit: 'tbsp' },
      { name: 'salt', quantity: '1/2', unit: 'tsp' },
      { name: 'milk', quantity: '2', unit: 'tbsp' },
      { name: 'queso fresco', quantity: '1', unit: 'cup, sliced' },
      { name: 'butter', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Blend corn kernels with sugar, salt, and milk until slightly chunky.',
      'Heat butter on a griddle over medium heat.',
      'Pour 1/4 cup batter per cachapa and cook 3-4 minutes per side until golden.',
      'Fold each cachapa over sliced queso fresco and serve warm.',
    ],
    tags: ['cachapa', 'venezuelan', 'corn', 'pancake', 'cheese'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 310,
      protein_g: 14,
      carbs_g: 40,
      fat_g: 12,
      fiber_g: 4,
      sugar_g: 8,
      sodium_mg: 380,
    },
  },
  {
    title: 'Churrasco with Pebre',
    description: 'Grilled skirt steak with Chilean pebre herb salsa and roasted vegetables.',
    cuisine: 'Latin American',
    prep_minutes: 20,
    cook_minutes: 15,
    servings: 4,
    calories: 400,
    ingredients: [
      { name: 'skirt steak', quantity: '1.5', unit: 'lbs' },
      { name: 'fresh cilantro', quantity: '1', unit: 'cup, chopped' },
      { name: 'tomato', quantity: '1', unit: 'diced' },
      { name: 'onion', quantity: '1/2', unit: 'finely diced' },
      { name: 'garlic', quantity: '2', unit: 'cloves, minced' },
      { name: 'olive oil', quantity: '3', unit: 'tbsp' },
      { name: 'red wine vinegar', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Make pebre: combine cilantro, tomato, onion, garlic, olive oil, and vinegar. Season with salt.',
      'Season steak with salt and grill over high heat 3-4 minutes per side.',
      'Let steak rest 5 minutes, then slice against the grain.',
      'Serve with pebre spooned over the top.',
    ],
    tags: ['churrasco', 'grilled', 'steak', 'chilean', 'salsa'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 400,
      protein_g: 44,
      carbs_g: 4,
      fat_g: 24,
      fiber_g: 1,
      sugar_g: 1,
      sodium_mg: 300,
    },
  },
  {
    title: 'Sancocho',
    description: 'Hearty Dominican soup with beef, plantains, yuca, and root vegetables.',
    cuisine: 'Latin American',
    prep_minutes: 20,
    cook_minutes: 90,
    servings: 8,
    calories: 380,
    ingredients: [
      { name: 'beef stew meat', quantity: '1', unit: 'lb' },
      { name: 'green plantain', quantity: '2', unit: 'sliced' },
      { name: 'yuca', quantity: '1', unit: 'lb, peeled and cubed' },
      { name: 'yautía', quantity: '1', unit: 'cup, cubed' },
      { name: 'corn on the cob', quantity: '2', unit: 'ears, cut in pieces' },
      { name: 'cilantro', quantity: '1/4', unit: 'cup' },
      { name: 'garlic', quantity: '4', unit: 'cloves' },
      { name: 'sour orange juice', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Brown beef in a large pot. Add garlic, cilantro, and sour orange juice.',
      'Add water and bring to a boil. Simmer 30 minutes.',
      'Add yuca, yautía, plantains, and corn. Cook 40 minutes until tender.',
      'Season with salt and serve hot with avocado and white rice.',
    ],
    tags: ['sancocho', 'dominican', 'soup', 'beef', 'root vegetables'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 24,
      carbs_g: 42,
      fat_g: 12,
      fiber_g: 5,
      sugar_g: 3,
      sodium_mg: 460,
    },
  },
  {
    title: 'Picadillo',
    description: 'Cuban-style ground beef hash with olives, raisins, and capers served over rice.',
    cuisine: 'Latin American',
    prep_minutes: 10,
    cook_minutes: 25,
    servings: 6,
    calories: 340,
    ingredients: [
      { name: 'ground beef', quantity: '1.5', unit: 'lbs' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'garlic', quantity: '3', unit: 'cloves, minced' },
      { name: 'green olives', quantity: '1/4', unit: 'cup, chopped' },
      { name: 'raisins', quantity: '1/4', unit: 'cup' },
      { name: 'capers', quantity: '2', unit: 'tbsp' },
      { name: 'tomato sauce', quantity: '1', unit: 'cup' },
      { name: 'white rice', quantity: '3', unit: 'cups, cooked' },
    ],
    steps: [
      'Brown ground beef with onion and garlic. Drain excess fat.',
      'Add tomato sauce, olives, raisins, and capers. Season with cumin and oregano.',
      'Simmer 15 minutes until flavors meld.',
      'Serve over white rice with fried plantains on the side.',
    ],
    tags: ['picadillo', 'cuban', 'ground beef', 'hash', 'rice'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 340,
      protein_g: 24,
      carbs_g: 30,
      fat_g: 14,
      fiber_g: 3,
      sugar_g: 8,
      sodium_mg: 580,
    },
  },
  {
    title: 'Mazamorra Morada',
    description: 'Peruvian purple corn pudding with fruit, cinnamon, and cloves.',
    cuisine: 'Latin American',
    prep_minutes: 10,
    cook_minutes: 45,
    servings: 8,
    calories: 180,
    ingredients: [
      { name: 'purple corn', quantity: '1', unit: 'lb' },
      { name: 'water', quantity: '8', unit: 'cups' },
      { name: 'pineapple peel', quantity: '1', unit: 'piece' },
      { name: 'cinnamon stick', quantity: '2', unit: 'pieces' },
      { name: 'cloves', quantity: '4', unit: 'whole' },
      { name: 'sugar', quantity: '1', unit: 'cup' },
      { name: 'cornstarch', quantity: '1/4', unit: 'cup' },
      { name: 'dried apricots', quantity: '1/4', unit: 'cup, diced' },
    ],
    steps: [
      'Boil purple corn, pineapple peel, cinnamon, and cloves in water for 45 minutes.',
      'Strain the liquid and discard solids. Return to pot.',
      'Add sugar, apricots, and dissolved cornstarch. Stir until thickened.',
      'Serve warm or chilled in bowls.',
    ],
    tags: ['mazamorra', 'peruvian', 'dessert', 'purple corn', 'pudding'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 180,
      protein_g: 2,
      carbs_g: 40,
      fat_g: 0,
      fiber_g: 2,
      sugar_g: 30,
      sodium_mg: 40,
    },
  },
  {
    title: 'Yuca Frita',
    description: 'Crispy fried yuca sticks served with garlic mojo sauce.',
    cuisine: 'Latin American',
    prep_minutes: 10,
    cook_minutes: 20,
    servings: 4,
    calories: 250,
    ingredients: [
      { name: 'yuca', quantity: '2', unit: 'lbs, peeled and cut into sticks' },
      { name: 'garlic', quantity: '4', unit: 'cloves, minced' },
      { name: 'olive oil', quantity: '1/4', unit: 'cup' },
      { name: 'sour orange juice', quantity: '2', unit: 'tbsp' },
      { name: 'salt', quantity: '1', unit: 'tsp' },
      { name: 'vegetable oil', quantity: '2', unit: 'cups, for frying' },
    ],
    steps: [
      'Boil yuca sticks in salted water for 10 minutes until just tender. Drain well.',
      'Heat vegetable oil to 375°F. Fry yuca sticks in batches until golden and crispy.',
      'Make mojo: sauté garlic in olive oil, add sour orange juice and salt.',
      'Serve yuca frita hot with garlic mojo for dipping.',
    ],
    tags: ['yuca', 'fried', 'side dish', 'vegan', 'mojo'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 250,
      protein_g: 3,
      carbs_g: 36,
      fat_g: 12,
      fiber_g: 2,
      sugar_g: 1,
      sodium_mg: 380,
    },
  },
  {
    title: 'Choripán',
    description: 'Argentine grilled chorizo sandwich with chimichurri on crusty bread.',
    cuisine: 'Latin American',
    prep_minutes: 10,
    cook_minutes: 12,
    servings: 4,
    calories: 420,
    ingredients: [
      { name: 'fresh chorizo', quantity: '4', unit: 'links' },
      { name: 'crusty bread rolls', quantity: '4', unit: 'pieces' },
      { name: 'chimichurri sauce', quantity: '1/2', unit: 'cup' },
      { name: 'onion', quantity: '1/2', unit: 'sliced' },
    ],
    steps: [
      'Grill chorizo links over medium heat for 10-12 minutes, turning occasionally.',
      'Split bread rolls and toast on the grill.',
      'Slice chorizo lengthwise and place in rolls.',
      'Top with chimichurri and sliced onion.',
    ],
    tags: ['choripán', 'argentine', 'sandwich', 'chorizo', 'grilled'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 20,
      carbs_g: 32,
      fat_g: 24,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 820,
    },
  },
  {
    title: 'Pernil',
    description:
      'Puerto Rican slow-roasted pork shoulder with garlic, oregano, and adobo seasoning.',
    cuisine: 'Latin American',
    prep_minutes: 20,
    cook_minutes: 300,
    servings: 10,
    calories: 380,
    ingredients: [
      { name: 'pork shoulder', quantity: '8', unit: 'lbs' },
      { name: 'garlic', quantity: '1', unit: 'head, minced' },
      { name: 'adobo seasoning', quantity: '3', unit: 'tbsp' },
      { name: 'oregano', quantity: '2', unit: 'tbsp' },
      { name: 'sazón seasoning', quantity: '2', unit: 'packets' },
      { name: 'olive oil', quantity: '1/4', unit: 'cup' },
      { name: 'vinegar', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Make small cuts all over pork and stuff with garlic. Rub with adobo, oregano, sazón, oil, and vinegar.',
      'Refrigerate overnight or at least 4 hours.',
      'Roast at 325°F for 5 hours, covered with foil. Uncover for last 30 minutes to crisp skin.',
      'Shred and serve with rice and beans.',
    ],
    tags: ['pernil', 'puerto rican', 'pork', 'roasted', 'slow-cooked'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 380,
      protein_g: 32,
      carbs_g: 2,
      fat_g: 28,
      fiber_g: 0,
      sugar_g: 0,
      sodium_mg: 640,
    },
  },
  {
    title: 'Buñuelos',
    description:
      'Crispy fried Colombian cheese fritters served during holidays with honey or aguardiente.',
    cuisine: 'Latin American',
    prep_minutes: 20,
    cook_minutes: 10,
    servings: 8,
    calories: 200,
    ingredients: [
      { name: 'precooked cornmeal', quantity: '1', unit: 'cup' },
      { name: 'queso fresco', quantity: '1', unit: 'cup, crumbled' },
      { name: 'eggs', quantity: '2', unit: 'large' },
      { name: 'milk', quantity: '1/2', unit: 'cup' },
      { name: 'sugar', quantity: '2', unit: 'tbsp' },
      { name: 'baking powder', quantity: '1', unit: 'tsp' },
      { name: 'vegetable oil', quantity: '2', unit: 'cups, for frying' },
    ],
    steps: [
      'Mix cornmeal, cheese, eggs, milk, sugar, and baking powder into a soft dough.',
      'Form dough into small balls about 1 inch in diameter.',
      'Fry in hot oil (350°F) until golden and puffed, about 3-4 minutes.',
      'Drain on paper towels and serve warm with honey.',
    ],
    tags: ['buñuelos', 'colombian', 'fritter', 'cheese', 'fried'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 200,
      protein_g: 7,
      carbs_g: 20,
      fat_g: 11,
      fiber_g: 1,
      sugar_g: 5,
      sodium_mg: 340,
    },
  },
  {
    title: 'Quinoa Ensalada',
    description:
      'Bright Andean quinoa salad with roasted peppers, black beans, avocado, and lime vinaigrette.',
    cuisine: 'Latin American',
    prep_minutes: 20,
    cook_minutes: 15,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'quinoa', quantity: '1', unit: 'cup' },
      { name: 'black beans', quantity: '1', unit: 'can, drained' },
      { name: 'roasted red pepper', quantity: '1', unit: 'diced' },
      { name: 'avocado', quantity: '1', unit: 'cubed' },
      { name: 'lime juice', quantity: '3', unit: 'tbsp' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'cilantro', quantity: '1/4', unit: 'cup, chopped' },
      { name: 'cumin', quantity: '1/2', unit: 'tsp' },
    ],
    steps: [
      'Cook quinoa according to package directions. Let cool.',
      'Whisk lime juice, olive oil, and cumin for vinaigrette.',
      'Toss quinoa with black beans, roasted pepper, avocado, and cilantro.',
      'Drizzle with vinaigrette and serve at room temperature.',
    ],
    tags: ['quinoa', 'salad', 'vegan', 'healthy', 'andean'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 10,
      carbs_g: 36,
      fat_g: 11,
      fiber_g: 8,
      sugar_g: 2,
      sodium_mg: 200,
    },
  },
  {
    title: 'Chorizo and Potato Tacos',
    description:
      'Mexican-style chorizo with crispy potatoes in warm corn tortillas with salsa verde.',
    cuisine: 'Latin American',
    prep_minutes: 10,
    cook_minutes: 15,
    servings: 4,
    calories: 380,
    ingredients: [
      { name: 'chorizo', quantity: '8', unit: 'oz' },
      { name: 'potato', quantity: '2', unit: 'medium, diced small' },
      { name: 'corn tortillas', quantity: '8', unit: 'pieces' },
      { name: 'salsa verde', quantity: '1/2', unit: 'cup' },
      { name: 'onion', quantity: '1/4', unit: 'cup, diced' },
      { name: 'cilantro', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Cook diced potatoes in a skillet until crispy and golden. Set aside.',
      'Cook chorizo in the same skillet, breaking it up, until browned.',
      'Combine chorizo and potatoes. Warm tortillas.',
      'Fill tortillas with chorizo-potato mixture. Top with salsa verde, onion, and cilantro.',
    ],
    tags: ['taco', 'chorizo', 'potato', 'mexican', 'street food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 18,
      carbs_g: 34,
      fat_g: 20,
      fiber_g: 4,
      sugar_g: 2,
      sodium_mg: 720,
    },
  },
  {
    title: 'Choclo con Queso',
    description:
      'Peruvian large-kernel corn on the cob slathered with fresh cheese and aji amarillo.',
    cuisine: 'Latin American',
    prep_minutes: 5,
    cook_minutes: 15,
    servings: 4,
    calories: 220,
    ingredients: [
      { name: 'large kernel corn', quantity: '4', unit: 'ears' },
      { name: 'queso fresco', quantity: '1/2', unit: 'cup, crumbled' },
      { name: 'aji amarillo paste', quantity: '1', unit: 'tbsp' },
      { name: 'lime', quantity: '1', unit: 'cut into wedges' },
      { name: 'salt', quantity: '1/2', unit: 'tsp' },
    ],
    steps: [
      'Boil corn in salted water for 10-15 minutes until tender.',
      'Mix crumbled queso fresco with aji amarillo paste.',
      'Spread cheese mixture generously over each ear of corn.',
      'Squeeze lime over top and serve immediately.',
    ],
    tags: ['choclo', 'peruvian', 'corn', 'cheese', 'vegetarian'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 220,
      protein_g: 8,
      carbs_g: 34,
      fat_g: 7,
      fiber_g: 4,
      sugar_g: 5,
      sodium_mg: 320,
    },
  },
];

export const latinAmericanRecipes = generateCuisineRecipes(configs);
