import type { CuisineRecipeConfig } from './types';
import { generateCuisineRecipes } from './types';

const configs: CuisineRecipeConfig[] = [
  {
    title: 'Shakshuka Mediterranean',
    description: 'Eggs poached in a vibrant tomato-pepper sauce with feta and fresh herbs.',
    cuisine: 'Mediterranean',
    prep_minutes: 10,
    cook_minutes: 20,
    servings: 4,
    calories: 220,
    ingredients: [
      { name: 'egg', quantity: '6', unit: 'large' },
      { name: 'tomato', quantity: '4', unit: 'diced' },
      { name: 'bell pepper', quantity: '1', unit: 'diced' },
      { name: 'feta cheese', quantity: '2', unit: 'oz, crumbled' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'cumin', quantity: '1', unit: 'tsp' },
      { name: 'garlic', quantity: '3', unit: 'cloves, minced' },
      { name: 'cilantro', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Sauté pepper and garlic in olive oil until soft.',
      'Add tomatoes and cumin, simmer 10 minutes.',
      'Make wells and crack eggs into the sauce.',
      'Cover and cook until whites set, 5-7 minutes.',
      'Top with feta and cilantro.',
      'Serve with crusty bread.',
    ],
    tags: ['mediterranean', 'eggs', 'tomato', 'breakfast', 'vegetarian'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 220,
      protein_g: 14,
      carbs_g: 10,
      fat_g: 14,
      fiber_g: 2,
      sugar_g: 5,
      sodium_mg: 440,
    },
  },
  {
    title: 'Grilled Halloumi Salad',
    description:
      'Charred halloumi cheese over mixed greens with pomegranate, mint, and lemon dressing.',
    cuisine: 'Mediterranean',
    prep_minutes: 15,
    cook_minutes: 5,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'halloumi cheese', quantity: '8', unit: 'oz, sliced' },
      { name: 'mixed greens', quantity: '4', unit: 'cups' },
      { name: 'pomegranate seeds', quantity: '1/3', unit: 'cup' },
      { name: 'cucumber', quantity: '1', unit: 'diced' },
      { name: 'mint', quantity: '2', unit: 'tbsp' },
      { name: 'lemon juice', quantity: '2', unit: 'tbsp' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'honey', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Grill halloumi slices 2 minutes per side until charred.',
      'Toss greens, cucumber, pomegranate, and mint.',
      'Whisk lemon juice, olive oil, and honey for dressing.',
      'Arrange salad on plates, top with grilled halloumi.',
      'Drizzle with dressing.',
      'Serve immediately.',
    ],
    tags: ['mediterranean', 'salad', 'halloumi', 'vegetarian', 'grilled'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 14,
      carbs_g: 12,
      fat_g: 20,
      fiber_g: 2,
      sugar_g: 8,
      sodium_mg: 520,
    },
  },
  {
    title: 'Lemon Herb Grilled Fish',
    description:
      'Whole grilled sea bass with lemon, herbs, and olive oil over a bed of roasted vegetables.',
    cuisine: 'Mediterranean',
    prep_minutes: 15,
    cook_minutes: 20,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'sea bass', quantity: '1', unit: 'whole (2 lb)' },
      { name: 'lemon', quantity: '2', unit: 'sliced' },
      { name: 'olive oil', quantity: '3', unit: 'tbsp' },
      { name: 'garlic', quantity: '4', unit: 'cloves, sliced' },
      { name: 'thyme', quantity: '4', unit: 'sprigs' },
      { name: 'rosemary', quantity: '2', unit: 'sprigs' },
      { name: 'cherry tomato', quantity: '1', unit: 'cup' },
      { name: 'capers', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Score fish on both sides. Season with salt, pepper, and olive oil.',
      'Stuff cavity with lemon slices, garlic, thyme, and rosemary.',
      'Place on a bed of cherry tomatoes and capers.',
      'Drizzle with olive oil and roast at 400°F for 20 minutes.',
      'Fish is done when flesh flakes easily.',
      'Serve with the roasted tomatoes and a drizzle of good olive oil.',
    ],
    tags: ['mediterranean', 'fish', 'grilled', 'lemon', 'healthy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 280,
      protein_g: 36,
      carbs_g: 6,
      fat_g: 12,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 380,
    },
  },
  {
    title: 'Stuffed Bell Peppers',
    description: 'Bell peppers filled with herbed quinoa, chickpeas, feta, and sun-dried tomatoes.',
    cuisine: 'Mediterranean',
    prep_minutes: 20,
    cook_minutes: 30,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'bell pepper', quantity: '4', unit: 'large, halved' },
      { name: 'quinoa', quantity: '1', unit: 'cup, cooked' },
      { name: 'chickpeas', quantity: '1', unit: 'can, drained' },
      { name: 'feta cheese', quantity: '1/4', unit: 'cup, crumbled' },
      { name: 'sun-dried tomato', quantity: '1/4', unit: 'cup, chopped' },
      { name: 'spinach', quantity: '2', unit: 'cups' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'oregano', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Halve peppers and remove seeds. Parboil 5 minutes.',
      'Mix quinoa, chickpeas, sun-dried tomatoes, spinach, oregano, and half the feta.',
      'Fill pepper halves with the mixture.',
      'Top with remaining feta and drizzle with olive oil.',
      'Bake at 375°F for 25-30 minutes until peppers are tender.',
      'Serve with a side of tzatziki or hummus.',
    ],
    tags: ['mediterranean', 'vegetarian', 'stuffed-pepper', 'quinoa', 'healthy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 12,
      carbs_g: 34,
      fat_g: 10,
      fiber_g: 8,
      sugar_g: 6,
      sodium_mg: 420,
    },
  },
  {
    title: 'Lamb Kofta',
    description:
      'Spiced ground lamb skewers grilled with Mediterranean herbs and served with tzatziki.',
    cuisine: 'Mediterranean',
    prep_minutes: 20,
    cook_minutes: 10,
    servings: 6,
    calories: 280,
    ingredients: [
      { name: 'ground lamb', quantity: '1.5', unit: 'lb' },
      { name: 'onion', quantity: '1', unit: 'grated' },
      { name: 'mint', quantity: '2', unit: 'tbsp, chopped' },
      { name: 'parsley', quantity: '2', unit: 'tbsp, chopped' },
      { name: 'cumin', quantity: '1', unit: 'tsp' },
      { name: 'coriander', quantity: '1', unit: 'tsp' },
      { name: 'garlic', quantity: '2', unit: 'cloves, minced' },
      { name: 'tzatziki', quantity: '1/2', unit: 'cup' },
    ],
    steps: [
      'Mix lamb, onion, mint, parsley, cumin, coriander, garlic, salt, and pepper.',
      'Shape around skewers into ovals.',
      'Grill over medium-high heat, turning, until charred and cooked through.',
      'Serve with tzatziki, warm pita, and salad.',
    ],
    tags: ['mediterranean', 'lamb', 'grilled', 'kebab', 'spiced'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 280,
      protein_g: 22,
      carbs_g: 2,
      fat_g: 20,
      fiber_g: 0,
      sugar_g: 1,
      sodium_mg: 320,
    },
  },
  {
    title: 'Mediterranean Pasta',
    description:
      'Penne with sun-dried tomatoes, olives, artichoke hearts, and feta in a lemon-herb sauce.',
    cuisine: 'Mediterranean',
    prep_minutes: 10,
    cook_minutes: 15,
    servings: 6,
    calories: 380,
    ingredients: [
      { name: 'penne pasta', quantity: '1', unit: 'lb' },
      { name: 'sun-dried tomato', quantity: '1/3', unit: 'cup, chopped' },
      { name: 'kalamata olives', quantity: '1/2', unit: 'cup, halved' },
      { name: 'artichoke hearts', quantity: '1', unit: 'can, quartered' },
      { name: 'feta cheese', quantity: '1/2', unit: 'cup, crumbled' },
      { name: 'garlic', quantity: '3', unit: 'cloves, minced' },
      { name: 'lemon juice', quantity: '2', unit: 'tbsp' },
      { name: 'basil', quantity: '1/4', unit: 'cup, fresh' },
    ],
    steps: [
      'Cook penne until al dente. Reserve 1 cup pasta water.',
      'Sauté garlic in olive oil, add sun-dried tomatoes.',
      'Add olives and artichoke hearts, toss to warm.',
      'Add pasta with a splash of pasta water and lemon juice.',
      'Toss with feta and fresh basil.',
      'Serve with a drizzle of olive oil.',
    ],
    tags: ['mediterranean', 'pasta', 'vegetarian', 'olives', 'feta'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 14,
      carbs_g: 52,
      fat_g: 12,
      fiber_g: 4,
      sugar_g: 4,
      sodium_mg: 680,
    },
  },
  {
    title: 'White Bean Soup',
    description: 'Hearty Tuscan-style white bean soup with kale, rosemary, and Parmesan.',
    cuisine: 'Mediterranean',
    prep_minutes: 10,
    cook_minutes: 30,
    servings: 6,
    calories: 220,
    ingredients: [
      { name: 'cannellini beans', quantity: '2', unit: 'cans, drained' },
      { name: 'kale', quantity: '2', unit: 'cups, chopped' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'garlic', quantity: '3', unit: 'cloves' },
      { name: 'rosemary', quantity: '2', unit: 'sprigs' },
      { name: 'vegetable broth', quantity: '4', unit: 'cups' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'parmesan rind', quantity: '1', unit: 'piece' },
    ],
    steps: [
      'Sauté onion and garlic in olive oil.',
      'Add beans, broth, rosemary, and Parmesan rind.',
      'Simmer 20 minutes. Mash half the beans for thickness.',
      'Add kale and cook 5 more minutes.',
      'Remove rosemary sprigs and Parmesan rind.',
      'Serve with crusty bread and a drizzle of olive oil.',
    ],
    tags: ['mediterranean', 'soup', 'vegetarian', 'beans', 'kale'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 220,
      protein_g: 10,
      carbs_g: 30,
      fat_g: 6,
      fiber_g: 8,
      sugar_g: 2,
      sodium_mg: 580,
    },
  },
  {
    title: 'Grilled Vegetable Platter',
    description:
      'Assorted grilled vegetables with balsamic glaze, fresh herbs, and whipped ricotta.',
    cuisine: 'Mediterranean',
    prep_minutes: 15,
    cook_minutes: 15,
    servings: 6,
    calories: 180,
    ingredients: [
      { name: 'zucchini', quantity: '2', unit: 'sliced lengthwise' },
      { name: 'eggplant', quantity: '1', unit: 'sliced' },
      { name: 'bell pepper', quantity: '2', unit: 'halved' },
      { name: 'asparagus', quantity: '1', unit: 'bunch' },
      { name: 'balsamic vinegar', quantity: '2', unit: 'tbsp' },
      { name: 'ricotta', quantity: '1/2', unit: 'cup, whipped' },
      { name: 'olive oil', quantity: '3', unit: 'tbsp' },
      { name: 'basil', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Brush all vegetables with olive oil and season.',
      'Grill vegetables on high heat until charred and tender.',
      'Arrange on a platter.',
      'Drizzle with balsamic vinegar.',
      'Add dollops of whipped ricotta.',
      'Garnish with fresh basil and serve.',
    ],
    tags: ['mediterranean', 'vegetarian', 'grilled', 'vegetables', 'healthy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 180,
      protein_g: 6,
      carbs_g: 14,
      fat_g: 12,
      fiber_g: 4,
      sugar_g: 6,
      sodium_mg: 280,
    },
  },
  {
    title: 'Lemon Orzo Salad',
    description:
      'Bright orzo pasta salad with cherry tomatoes, cucumber, feta, and a lemon-herb vinaigrette.',
    cuisine: 'Mediterranean',
    prep_minutes: 15,
    cook_minutes: 10,
    servings: 6,
    calories: 240,
    ingredients: [
      { name: 'orzo pasta', quantity: '1', unit: 'cup' },
      { name: 'cherry tomato', quantity: '1', unit: 'cup, halved' },
      { name: 'cucumber', quantity: '1', unit: 'diced' },
      { name: 'feta cheese', quantity: '1/4', unit: 'cup, crumbled' },
      { name: 'kalamata olives', quantity: '1/4', unit: 'cup' },
      { name: 'lemon juice', quantity: '3', unit: 'tbsp' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'dill', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Cook orzo until al dente. Rinse and cool.',
      'Combine orzo, tomatoes, cucumber, olives, and feta.',
      'Whisk lemon juice, olive oil, dill, salt, and pepper.',
      'Toss salad with dressing.',
      'Chill for 30 minutes.',
      'Serve as a side or light lunch.',
    ],
    tags: ['mediterranean', 'pasta-salad', 'vegetarian', 'lemon', 'cold'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 240,
      protein_g: 8,
      carbs_g: 32,
      fat_g: 10,
      fiber_g: 2,
      sugar_g: 4,
      sodium_mg: 480,
    },
  },
  {
    title: 'Baba Ganoush Mediterranean',
    description: 'Smoky eggplant dip with tahini, lemon, and olive oil served with warm flatbread.',
    cuisine: 'Mediterranean',
    prep_minutes: 10,
    cook_minutes: 40,
    servings: 6,
    calories: 110,
    ingredients: [
      { name: 'eggplant', quantity: '2', unit: 'large' },
      { name: 'tahini', quantity: '3', unit: 'tbsp' },
      { name: 'lemon juice', quantity: '2', unit: 'tbsp' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'smoked paprika', quantity: '1/4', unit: 'tsp' },
      { name: 'parsley', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Roast eggplants until charred and collapsed.',
      'Scoop out flesh, drain liquid.',
      'Blend with tahini, lemon, and garlic until smooth.',
      'Season with salt and paprika.',
      'Drizzle with olive oil.',
      'Serve with warm flatbread.',
    ],
    tags: ['mediterranean', 'dip', 'eggplant', 'vegan', 'smoky'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 110,
      protein_g: 3,
      carbs_g: 10,
      fat_g: 7,
      fiber_g: 4,
      sugar_g: 3,
      sodium_mg: 140,
    },
  },
  {
    title: 'Caprese Salad',
    description: 'Fresh mozzarella, ripe tomatoes, and basil drizzled with balsamic and olive oil.',
    cuisine: 'Mediterranean',
    prep_minutes: 10,
    cook_minutes: 0,
    servings: 4,
    calories: 200,
    ingredients: [
      { name: 'fresh mozzarella', quantity: '8', unit: 'oz, sliced' },
      { name: 'tomato', quantity: '3', unit: 'large, sliced' },
      { name: 'basil', quantity: '1', unit: 'cup, fresh leaves' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'balsamic glaze', quantity: '1', unit: 'tbsp' },
      { name: 'salt', quantity: '1/4', unit: 'tsp' },
      { name: 'black pepper', quantity: '1/4', unit: 'tsp' },
    ],
    steps: [
      'Slice mozzarella and tomatoes into 1/4-inch rounds.',
      'Alternate tomato and mozzarella slices on a plate.',
      'Tuck fresh basil leaves between slices.',
      'Drizzle with extra virgin olive oil.',
      'Add balsamic glaze in a thin stream.',
      'Season with salt and pepper. Serve immediately.',
    ],
    tags: ['mediterranean', 'salad', 'vegetarian', 'caprese', 'fresh'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 200,
      protein_g: 12,
      carbs_g: 6,
      fat_g: 14,
      fiber_g: 1,
      sugar_g: 3,
      sodium_mg: 320,
    },
  },
];

export const mediterraneanRecipes = generateCuisineRecipes(configs);

// ── Additional Mediterranean recipes ──────────────────────────────────────────

const additionalConfigs: CuisineRecipeConfig[] = [
  {
    title: 'Fattoush',
    description:
      'Levantine salad with toasted pita, crisp vegetables, sumac, and pomegranate molasses.',
    cuisine: 'Mediterranean',
    prep_minutes: 15,
    cook_minutes: 3,
    servings: 4,
    calories: 160,
    ingredients: [
      { name: 'pita bread', quantity: '2', unit: 'pieces, toasted & broken' },
      { name: 'cucumber', quantity: '1', unit: 'diced' },
      { name: 'tomato', quantity: '2', unit: 'diced' },
      { name: 'radish', quantity: '4', unit: 'sliced' },
      { name: 'sumac', quantity: '1', unit: 'tsp' },
      { name: 'pomegranate molasses', quantity: '1', unit: 'tbsp' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'lettuce', quantity: '2', unit: 'cups, torn' },
    ],
    steps: [
      'Toast pita until crispy and break into pieces.',
      'Combine cucumber, tomato, radish, and lettuce.',
      'Whisk olive oil, pomegranate molasses, sumac, and lemon.',
      'Toss salad with dressing.',
      'Add pita chips on top just before serving.',
      'Serve immediately.',
    ],
    tags: ['mediterranean', 'salad', 'pita', 'sumac', 'vegan'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 160,
      protein_g: 4,
      carbs_g: 20,
      fat_g: 8,
      fiber_g: 3,
      sugar_g: 4,
      sodium_mg: 220,
    },
  },
  {
    title: 'Mujadara',
    description:
      'Lentils and rice topped with crispy caramelized onions — a beloved Middle Eastern staple.',
    cuisine: 'Mediterranean',
    prep_minutes: 15,
    cook_minutes: 35,
    servings: 6,
    calories: 280,
    ingredients: [
      { name: 'brown lentils', quantity: '1', unit: 'cup' },
      { name: 'rice', quantity: '1', unit: 'cup' },
      { name: 'onion', quantity: '3', unit: 'large, sliced' },
      { name: 'olive oil', quantity: '3', unit: 'tbsp' },
      { name: 'cumin', quantity: '1', unit: 'tsp' },
      { name: 'cinnamon', quantity: '1/4', unit: 'tsp' },
      { name: 'yogurt', quantity: '1/2', unit: 'cup' },
    ],
    steps: [
      'Caramelize onions in olive oil until deep brown and crispy. Reserve half for topping.',
      'Cook lentils in water until almost tender.',
      'Add rice, cumin, cinnamon, and caramelized onion. Cook until rice is done.',
      'Season with salt and pepper.',
      'Serve topped with reserved crispy onions.',
      'Serve with yogurt on the side.',
    ],
    tags: ['mediterranean', 'lentils', 'rice', 'vegetarian', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 12,
      carbs_g: 44,
      fat_g: 8,
      fiber_g: 8,
      sugar_g: 4,
      sodium_mg: 280,
    },
  },
  {
    title: 'Hummus',
    description:
      'Silky smooth chickpea dip with tahini, lemon, and garlic, drizzled with olive oil.',
    cuisine: 'Mediterranean',
    prep_minutes: 10,
    cook_minutes: 0,
    servings: 8,
    calories: 100,
    ingredients: [
      { name: 'chickpeas', quantity: '2', unit: 'cans, drained' },
      { name: 'tahini', quantity: '1/4', unit: 'cup' },
      { name: 'lemon juice', quantity: '3', unit: 'tbsp' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'cumin', quantity: '1/2', unit: 'tsp' },
      { name: 'paprika', quantity: '1/4', unit: 'tsp' },
      { name: 'parsley', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Blend chickpeas, tahini, lemon juice, and garlic until very smooth.',
      'Add ice water while blending for extra creaminess.',
      'Season with cumin, salt, and pepper.',
      'Spread on a plate, make a well.',
      'Drizzle with olive oil and sprinkle paprika.',
      'Serve with warm pita bread.',
    ],
    tags: ['mediterranean', 'dip', 'chickpea', 'vegan', 'tahini'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 100,
      protein_g: 4,
      carbs_g: 12,
      fat_g: 4,
      fiber_g: 3,
      sugar_g: 1,
      sodium_mg: 180,
    },
  },
  {
    title: 'Tabbouleh',
    description: 'Fresh parsley and bulgur salad with tomato, mint, and lemon dressing.',
    cuisine: 'Mediterranean',
    prep_minutes: 20,
    cook_minutes: 0,
    servings: 6,
    calories: 120,
    ingredients: [
      { name: 'bulgur wheat', quantity: '1/2', unit: 'cup, soaked' },
      { name: 'parsley', quantity: '2', unit: 'cups, finely chopped' },
      { name: 'mint', quantity: '1/2', unit: 'cup, chopped' },
      { name: 'tomato', quantity: '3', unit: 'diced' },
      { name: 'onion', quantity: '1/4', unit: 'minced' },
      { name: 'lemon juice', quantity: '3', unit: 'tbsp' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Soak bulgur in boiling water for 20 minutes. Drain and squeeze dry.',
      'Finely chop parsley and mint.',
      'Dice tomato and mince onion.',
      'Toss everything together with lemon juice and olive oil.',
      'Season with salt and pepper.',
      'Chill before serving.',
    ],
    tags: ['mediterranean', 'salad', 'bulgur', 'parsley', 'vegan'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 120,
      protein_g: 3,
      carbs_g: 18,
      fat_g: 4,
      fiber_g: 4,
      sugar_g: 2,
      sodium_mg: 120,
    },
  },
  {
    title: 'Dolmades',
    description: 'Grape leaves stuffed with herbed rice, pine nuts, and lemon.',
    cuisine: 'Mediterranean',
    prep_minutes: 30,
    cook_minutes: 45,
    servings: 8,
    calories: 80,
    ingredients: [
      { name: 'grape leaves', quantity: '1', unit: 'jar, rinsed' },
      { name: 'rice', quantity: '1', unit: 'cup' },
      { name: 'pine nuts', quantity: '1/4', unit: 'cup' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'dill', quantity: '2', unit: 'tbsp' },
      { name: 'mint', quantity: '1', unit: 'tbsp' },
      { name: 'lemon juice', quantity: '3', unit: 'tbsp' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Sauté onion, add rice, pine nuts, herbs, and lemon juice.',
      'Place a spoonful of filling on each grape leaf, roll tightly.',
      'Arrange in a pot, seam-side down.',
      'Add lemon juice, olive oil, and water.',
      'Weight down with a plate and simmer 45 minutes.',
      'Serve warm or cold with yogurt.',
    ],
    tags: ['mediterranean', 'grape-leaves', 'vegetarian', 'rice', 'stuffed'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 80,
      protein_g: 2,
      carbs_g: 12,
      fat_g: 3,
      fiber_g: 1,
      sugar_g: 1,
      sodium_mg: 320,
    },
  },
  {
    title: 'Fasolada',
    description: 'Greek white bean soup with tomato, celery, and olive oil — hearty and warming.',
    cuisine: 'Mediterranean',
    prep_minutes: 10,
    cook_minutes: 60,
    servings: 6,
    calories: 220,
    ingredients: [
      { name: 'white beans', quantity: '1', unit: 'lb, soaked' },
      { name: 'tomato', quantity: '2', unit: 'diced' },
      { name: 'celery', quantity: '3', unit: 'stalks, diced' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'olive oil', quantity: '1/4', unit: 'cup' },
      { name: 'carrot', quantity: '1', unit: 'diced' },
      { name: 'tomato paste', quantity: '1', unit: 'tbsp' },
      { name: 'parsley', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Sauté onion, celery, and carrot in olive oil.',
      'Add beans, tomato, tomato paste, and water.',
      'Simmer until beans are very tender, about 1 hour.',
      'Add a generous pour of olive oil at the end.',
      'Season with salt and pepper.',
      'Serve with crusty bread.',
    ],
    tags: ['mediterranean', 'soup', 'beans', 'vegan', 'greek'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 220,
      protein_g: 10,
      carbs_g: 30,
      fat_g: 8,
      fiber_g: 10,
      sugar_g: 4,
      sodium_mg: 380,
    },
  },
  {
    title: 'Muhammara',
    description: 'Spicy roasted red pepper and walnut dip with pomegranate molasses.',
    cuisine: 'Mediterranean',
    prep_minutes: 10,
    cook_minutes: 20,
    servings: 6,
    calories: 120,
    ingredients: [
      { name: 'roasted red pepper', quantity: '3', unit: 'large' },
      { name: 'walnuts', quantity: '1/2', unit: 'cup' },
      { name: 'breadcrumbs', quantity: '2', unit: 'tbsp' },
      { name: 'pomegranate molasses', quantity: '1', unit: 'tbsp' },
      { name: 'cumin', quantity: '1/2', unit: 'tsp' },
      { name: 'chili flakes', quantity: '1/2', unit: 'tsp' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Roast peppers until charred. Peel and seed.',
      'Blend peppers, walnuts, breadcrumbs, and pomegranate molasses.',
      'Add cumin, chili flakes, salt, and olive oil.',
      'Blend until slightly chunky.',
      'Transfer to a bowl, drizzle with olive oil.',
      'Serve with pita or crackers.',
    ],
    tags: ['mediterranean', 'dip', 'pepper', 'walnut', 'spicy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 120,
      protein_g: 3,
      carbs_g: 8,
      fat_g: 8,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 180,
    },
  },
  {
    title: 'Avgolemono',
    description: 'Greek egg-lemon soup with rice — silky, tangy, and deeply comforting.',
    cuisine: 'Mediterranean',
    prep_minutes: 10,
    cook_minutes: 20,
    servings: 4,
    calories: 180,
    ingredients: [
      { name: 'chicken broth', quantity: '6', unit: 'cups' },
      { name: 'rice', quantity: '1/3', unit: 'cup' },
      { name: 'egg', quantity: '3', unit: 'large' },
      { name: 'lemon juice', quantity: '3', unit: 'tbsp' },
      { name: 'chicken', quantity: '1', unit: 'cup, shredded (optional)' },
      { name: 'dill', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Simmer rice in chicken broth until tender.',
      'Add shredded chicken if using.',
      'Beat eggs with lemon juice.',
      'Slowly whisk hot broth into the egg-lemon mixture to temper.',
      'Pour back into the pot, stir gently. Do not boil.',
      'Serve with dill.',
    ],
    tags: ['mediterranean', 'soup', 'egg', 'lemon', 'greek'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 180,
      protein_g: 10,
      carbs_g: 16,
      fat_g: 8,
      fiber_g: 0,
      sugar_g: 1,
      sodium_mg: 480,
    },
  },
  {
    title: 'Lamb Meatballs',
    description: 'Spiced Mediterranean lamb meatballs with mint yogurt and couscous.',
    cuisine: 'Mediterranean',
    prep_minutes: 20,
    cook_minutes: 15,
    servings: 4,
    calories: 320,
    ingredients: [
      { name: 'ground lamb', quantity: '1', unit: 'lb' },
      { name: 'onion', quantity: '1/2', unit: 'grated' },
      { name: 'mint', quantity: '2', unit: 'tbsp, chopped' },
      { name: 'cumin', quantity: '1', unit: 'tsp' },
      { name: 'cinnamon', quantity: '1/4', unit: 'tsp' },
      { name: 'yogurt', quantity: '1/2', unit: 'cup' },
      { name: 'couscous', quantity: '1', unit: 'cup' },
      { name: 'garlic', quantity: '2', unit: 'cloves, minced' },
    ],
    steps: [
      'Mix lamb, onion, mint, cumin, cinnamon, garlic, salt, and pepper.',
      'Form into meatballs.',
      'Pan-fry until golden and cooked through.',
      'Cook couscous according to package.',
      'Mix yogurt with minced garlic and a pinch of salt.',
      'Serve meatballs over couscous with mint yogurt.',
    ],
    tags: ['mediterranean', 'lamb', 'meatballs', 'mint', 'couscous'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 22,
      carbs_g: 20,
      fat_g: 16,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 420,
    },
  },
  {
    title: 'Stuffed Eggplant',
    description: 'Roasted eggplant halves filled with spiced lamb, tomatoes, and pine nuts.',
    cuisine: 'Mediterranean',
    prep_minutes: 20,
    cook_minutes: 40,
    servings: 4,
    calories: 320,
    ingredients: [
      { name: 'eggplant', quantity: '2', unit: 'large, halved' },
      { name: 'ground lamb', quantity: '1/2', unit: 'lb' },
      { name: 'tomato', quantity: '2', unit: 'diced' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'pine nuts', quantity: '2', unit: 'tbsp' },
      { name: 'cinnamon', quantity: '1/4', unit: 'tsp' },
      { name: 'allspice', quantity: '1/4', unit: 'tsp' },
      { name: 'parsley', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Scoop out eggplant flesh, leaving shells. Chop flesh.',
      'Sauté onion and lamb with cinnamon and allspice.',
      'Add chopped eggplant and tomato. Cook until thick.',
      'Fill eggplant shells with the mixture.',
      'Top with pine nuts.',
      'Bake at 375°F for 30 minutes. Garnish with parsley.',
    ],
    tags: ['mediterranean', 'eggplant', 'lamb', 'stuffed', 'baked'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 320,
      protein_g: 18,
      carbs_g: 14,
      fat_g: 20,
      fiber_g: 6,
      sugar_g: 6,
      sodium_mg: 380,
    },
  },
];

// ── Batch 2 additional Mediterranean recipes ──────────────────────────────────

const batch2Configs: CuisineRecipeConfig[] = [
  {
    title: 'Grilled Swordfish with Lemon Caper Sauce',
    description: 'Succulent swordfish steaks grilled and topped with a bright lemon caper sauce.',
    cuisine: 'Mediterranean',
    prep_minutes: 10,
    cook_minutes: 12,
    servings: 4,
    calories: 340,
    ingredients: [
      { name: 'swordfish steaks', quantity: '4', unit: '6 oz each' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'lemon juice', quantity: '3', unit: 'tbsp' },
      { name: 'capers', quantity: '2', unit: 'tbsp, drained' },
      { name: 'garlic', quantity: '2', unit: 'cloves, minced' },
      { name: 'fresh parsley', quantity: '2', unit: 'tbsp, chopped' },
      { name: 'salt', quantity: '1', unit: 'tsp' },
      { name: 'black pepper', quantity: '1/2', unit: 'tsp' },
    ],
    steps: [
      'Brush swordfish with olive oil and season with salt and pepper.',
      'Grill over high heat for 4-5 minutes per side.',
      'Meanwhile, sauté garlic in olive oil for 30 seconds.',
      'Add lemon juice and capers, simmer 2 minutes.',
      'Spoon sauce over grilled swordfish.',
      'Garnish with fresh parsley and serve.',
    ],
    tags: ['mediterranean', 'fish', 'grilled', 'keto', 'gluten-free'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 340,
      protein_g: 42,
      carbs_g: 2,
      fat_g: 18,
      fiber_g: 0,
      sugar_g: 0,
      sodium_mg: 390,
    },
  },
  {
    title: 'Spanakopita',
    description: 'Crispy phyllo pastry filled with spinach, feta, and herbs.',
    cuisine: 'Mediterranean',
    prep_minutes: 25,
    cook_minutes: 35,
    servings: 8,
    calories: 280,
    ingredients: [
      { name: 'phyllo dough', quantity: '12', unit: 'sheets' },
      { name: 'spinach', quantity: '16', unit: 'oz, thawed and drained' },
      { name: 'feta cheese', quantity: '8', unit: 'oz, crumbled' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'dill', quantity: '2', unit: 'tbsp, fresh' },
      { name: 'eggs', quantity: '3', unit: 'large' },
      { name: 'olive oil', quantity: '1/4', unit: 'cup' },
      { name: 'nutmeg', quantity: '1/4', unit: 'tsp' },
    ],
    steps: [
      'Sauté onion in olive oil until translucent.',
      'Mix spinach, feta, dill, eggs, and nutmeg in a large bowl.',
      'Add sautéed onion and stir to combine.',
      'Layer phyllo sheets in a baking dish, brushing each with olive oil.',
      'Spread spinach filling over the phyllo.',
      'Top with remaining phyllo sheets, brushing with oil.',
      'Score the top and bake at 375°F for 35 minutes until golden.',
    ],
    tags: ['mediterranean', 'greek', 'pastry', 'vegetarian', 'spinach'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 12,
      carbs_g: 22,
      fat_g: 18,
      fiber_g: 3,
      sugar_g: 3,
      sodium_mg: 520,
    },
  },
  {
    title: 'Lamb Shawarma Bowl',
    description: 'Spiced roasted lamb served over rice with pickled vegetables and tahini sauce.',
    cuisine: 'Mediterranean',
    prep_minutes: 20,
    cook_minutes: 45,
    servings: 4,
    calories: 580,
    ingredients: [
      { name: 'lamb shoulder', quantity: '1.5', unit: 'lbs' },
      { name: 'cumin', quantity: '2', unit: 'tsp' },
      { name: 'coriander', quantity: '1', unit: 'tsp' },
      { name: 'paprika', quantity: '1', unit: 'tsp' },
      { name: 'turmeric', quantity: '1/2', unit: 'tsp' },
      { name: 'garlic', quantity: '4', unit: 'cloves, minced' },
      { name: 'tahini', quantity: '3', unit: 'tbsp' },
      { name: 'rice', quantity: '2', unit: 'cups' },
      { name: 'cucumber', quantity: '1', unit: 'sliced' },
      { name: 'red onion', quantity: '1', unit: 'pickled' },
    ],
    steps: [
      'Mix cumin, coriander, paprika, turmeric, and garlic into a paste.',
      'Rub spice paste over lamb shoulder and marinate for at least 1 hour.',
      'Roast lamb at 375°F for 45 minutes until tender.',
      'Cook rice according to package directions.',
      'Whisk tahini with lemon juice and water for sauce.',
      'Slice lamb and serve over rice with cucumber, pickled onion, and tahini.',
    ],
    tags: ['mediterranean', 'lamb', 'shawarma', 'rice', 'halal'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 580,
      protein_g: 38,
      carbs_g: 42,
      fat_g: 28,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 460,
    },
  },
  {
    title: 'Mediterranean Stuffed Zucchini',
    description: 'Zucchini boats filled with herbed quinoa, sun-dried tomatoes, and pine nuts.',
    cuisine: 'Mediterranean',
    prep_minutes: 15,
    cook_minutes: 25,
    servings: 4,
    calories: 240,
    ingredients: [
      { name: 'zucchini', quantity: '4', unit: 'medium' },
      { name: 'quinoa', quantity: '1', unit: 'cup, cooked' },
      { name: 'sun-dried tomatoes', quantity: '1/4', unit: 'cup, chopped' },
      { name: 'pine nuts', quantity: '2', unit: 'tbsp, toasted' },
      { name: 'feta cheese', quantity: '2', unit: 'oz, crumbled' },
      { name: 'fresh mint', quantity: '2', unit: 'tbsp' },
      { name: 'lemon juice', quantity: '1', unit: 'tbsp' },
      { name: 'olive oil', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Halve zucchini lengthwise and scoop out centers.',
      'Sauté scooped zucchini flesh with olive oil for 3 minutes.',
      'Mix with cooked quinoa, sun-dried tomatoes, pine nuts, mint, and feta.',
      'Fill zucchini halves with the mixture.',
      'Bake at 400°F for 20-25 minutes until zucchini is tender.',
      'Drizzle with lemon juice and serve.',
    ],
    tags: ['mediterranean', 'vegetarian', 'quinoa', 'zucchini', 'healthy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 240,
      protein_g: 10,
      carbs_g: 26,
      fat_g: 12,
      fiber_g: 4,
      sugar_g: 4,
      sodium_mg: 310,
    },
  },
  {
    title: 'Tzatziki Sauce',
    description: 'Cool cucumber yogurt dip with garlic, dill, and lemon.',
    cuisine: 'Mediterranean',
    prep_minutes: 10,
    cook_minutes: 0,
    servings: 6,
    calories: 60,
    ingredients: [
      { name: 'Greek yogurt', quantity: '2', unit: 'cups' },
      { name: 'cucumber', quantity: '1', unit: 'grated and drained' },
      { name: 'garlic', quantity: '2', unit: 'cloves, minced' },
      { name: 'fresh dill', quantity: '2', unit: 'tbsp' },
      { name: 'lemon juice', quantity: '1', unit: 'tbsp' },
      { name: 'olive oil', quantity: '1', unit: 'tbsp' },
      { name: 'salt', quantity: '1/2', unit: 'tsp' },
    ],
    steps: [
      'Grate cucumber and squeeze out excess moisture.',
      'Combine yogurt, cucumber, garlic, and dill.',
      'Stir in lemon juice, olive oil, and salt.',
      'Refrigerate for at least 30 minutes before serving.',
      'Serve with pita bread or fresh vegetables.',
    ],
    tags: ['mediterranean', 'greek', 'sauce', 'vegetarian', 'dip'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 60,
      protein_g: 4,
      carbs_g: 4,
      fat_g: 4,
      fiber_g: 0,
      sugar_g: 3,
      sodium_mg: 180,
    },
  },
  {
    title: 'Mediterranean Lentil Soup',
    description: 'Hearty red lentil soup with cumin, lemon, and fresh herbs.',
    cuisine: 'Mediterranean',
    prep_minutes: 10,
    cook_minutes: 30,
    servings: 6,
    calories: 220,
    ingredients: [
      { name: 'red lentils', quantity: '1.5', unit: 'cups' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'carrot', quantity: '2', unit: 'diced' },
      { name: 'cumin', quantity: '1', unit: 'tsp' },
      { name: 'garlic', quantity: '3', unit: 'cloves' },
      { name: 'lemon juice', quantity: '2', unit: 'tbsp' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'vegetable broth', quantity: '6', unit: 'cups' },
      { name: 'fresh parsley', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Sauté onion and carrot in olive oil for 5 minutes.',
      'Add garlic and cumin, cook 1 minute.',
      'Add lentils and broth, bring to a boil.',
      'Reduce heat and simmer 25 minutes until lentils are soft.',
      'Stir in lemon juice and season with salt.',
      'Serve topped with parsley and a drizzle of olive oil.',
    ],
    tags: ['mediterranean', 'soup', 'lentils', 'vegan', 'healthy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 220,
      protein_g: 14,
      carbs_g: 32,
      fat_g: 5,
      fiber_g: 12,
      sugar_g: 4,
      sodium_mg: 340,
    },
  },
  {
    title: 'Grilled Halloumi and Vegetable Skewers',
    description:
      'Chunks of halloumi cheese threaded with colorful vegetables and grilled to perfection.',
    cuisine: 'Mediterranean',
    prep_minutes: 15,
    cook_minutes: 10,
    servings: 4,
    calories: 260,
    ingredients: [
      { name: 'halloumi cheese', quantity: '8', unit: 'oz, cubed' },
      { name: 'bell peppers', quantity: '2', unit: 'chunked' },
      { name: 'zucchini', quantity: '1', unit: 'sliced thick' },
      { name: 'red onion', quantity: '1', unit: 'chunked' },
      { name: 'cherry tomatoes', quantity: '8', unit: 'whole' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'dried oregano', quantity: '1', unit: 'tsp' },
      { name: 'lemon', quantity: '1', unit: 'quartered' },
    ],
    steps: [
      'Cut halloumi and vegetables into skewer-sized pieces.',
      'Thread onto soaked wooden skewers alternately.',
      'Brush with olive oil and sprinkle with oregano.',
      'Grill over medium-high heat for 3-4 minutes per side.',
      'Squeeze lemon juice over skewers before serving.',
    ],
    tags: ['mediterranean', 'grilled', 'halloumi', 'vegetarian', 'skewers'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 260,
      protein_g: 14,
      carbs_g: 10,
      fat_g: 20,
      fiber_g: 2,
      sugar_g: 4,
      sodium_mg: 580,
    },
  },
  {
    title: 'Mediterranean Chickpea Bowl',
    description:
      'Warm spiced chickpeas over greens with roasted red pepper, olives, and tahini dressing.',
    cuisine: 'Mediterranean',
    prep_minutes: 10,
    cook_minutes: 15,
    servings: 2,
    calories: 380,
    ingredients: [
      { name: 'chickpeas', quantity: '1', unit: 'can, drained' },
      { name: 'mixed greens', quantity: '4', unit: 'cups' },
      { name: 'roasted red pepper', quantity: '1', unit: 'sliced' },
      { name: 'kalamata olives', quantity: '1/4', unit: 'cup' },
      { name: 'tahini', quantity: '2', unit: 'tbsp' },
      { name: 'lemon juice', quantity: '2', unit: 'tbsp' },
      { name: 'cumin', quantity: '1', unit: 'tsp' },
      { name: 'olive oil', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Sauté chickpeas with cumin and olive oil for 8 minutes until lightly crispy.',
      'Whisk tahini with lemon juice and a splash of water for dressing.',
      'Arrange greens in bowls and top with warm chickpeas.',
      'Add roasted red pepper and olives.',
      'Drizzle with tahini dressing and serve.',
    ],
    tags: ['mediterranean', 'chickpeas', 'bowl', 'vegan', 'healthy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 14,
      carbs_g: 38,
      fat_g: 20,
      fiber_g: 10,
      sugar_g: 5,
      sodium_mg: 520,
    },
  },
  {
    title: 'Mediterranean Baked Sea Bass',
    description: 'Whole sea bass baked with tomatoes, olives, and capers in white wine.',
    cuisine: 'Mediterranean',
    prep_minutes: 15,
    cook_minutes: 25,
    servings: 4,
    calories: 320,
    ingredients: [
      { name: 'sea bass', quantity: '1', unit: 'whole, about 2 lbs' },
      { name: 'cherry tomatoes', quantity: '1', unit: 'cup, halved' },
      { name: 'kalamata olives', quantity: '1/4', unit: 'cup' },
      { name: 'capers', quantity: '1', unit: 'tbsp' },
      { name: 'white wine', quantity: '1/4', unit: 'cup' },
      { name: 'garlic', quantity: '3', unit: 'cloves, sliced' },
      { name: 'fresh thyme', quantity: '4', unit: 'sprigs' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Preheat oven to 400°F.',
      'Score the fish on both sides and season with salt and pepper.',
      'Place fish in a baking dish with tomatoes, olives, capers, and garlic.',
      'Pour white wine and olive oil over the fish.',
      'Top with thyme sprigs and bake for 25 minutes.',
      'Serve with the pan juices spooned over.',
    ],
    tags: ['mediterranean', 'fish', 'sea bass', 'baked', 'gluten-free'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 320,
      protein_g: 36,
      carbs_g: 6,
      fat_g: 16,
      fiber_g: 1,
      sugar_g: 3,
      sodium_mg: 420,
    },
  },
  {
    title: 'Muhammara Dip',
    description: 'Smoky roasted red pepper and walnut dip with pomegranate molasses.',
    cuisine: 'Mediterranean',
    prep_minutes: 10,
    cook_minutes: 20,
    servings: 8,
    calories: 120,
    ingredients: [
      { name: 'roasted red peppers', quantity: '3', unit: 'large' },
      { name: 'walnuts', quantity: '1/2', unit: 'cup' },
      { name: 'breadcrumbs', quantity: '2', unit: 'tbsp' },
      { name: 'pomegranate molasses', quantity: '1', unit: 'tbsp' },
      { name: 'cumin', quantity: '1/2', unit: 'tsp' },
      { name: 'garlic', quantity: '1', unit: 'clove' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'lemon juice', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Roast peppers under the broiler until charred, then peel.',
      'Combine peppers, walnuts, breadcrumbs, and garlic in a food processor.',
      'Add pomegranate molasses, cumin, and lemon juice.',
      'Pulse until slightly chunky.',
      'Transfer to a bowl and drizzle with olive oil.',
      'Serve with pita chips or crackers.',
    ],
    tags: ['mediterranean', 'dip', 'red pepper', 'vegan', 'appetizer'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 120,
      protein_g: 3,
      carbs_g: 8,
      fat_g: 9,
      fiber_g: 2,
      sugar_g: 4,
      sodium_mg: 160,
    },
  },
  {
    title: 'Mediterranean Orzo Salad',
    description: 'Chilled orzo pasta tossed with sun-dried tomatoes, artichoke hearts, and feta.',
    cuisine: 'Mediterranean',
    prep_minutes: 15,
    cook_minutes: 10,
    servings: 8,
    calories: 210,
    ingredients: [
      { name: 'orzo pasta', quantity: '12', unit: 'oz' },
      { name: 'sun-dried tomatoes', quantity: '1/3', unit: 'cup, chopped' },
      { name: 'artichoke hearts', quantity: '1', unit: 'can, chopped' },
      { name: 'feta cheese', quantity: '4', unit: 'oz, crumbled' },
      { name: 'kalamata olives', quantity: '1/4', unit: 'cup, sliced' },
      { name: 'fresh basil', quantity: '2', unit: 'tbsp' },
      { name: 'lemon vinaigrette', quantity: '3', unit: 'tbsp' },
      { name: 'pine nuts', quantity: '2', unit: 'tbsp, toasted' },
    ],
    steps: [
      'Cook orzo according to package directions and drain.',
      'Rinse with cold water and drain well.',
      'Toss orzo with sun-dried tomatoes, artichoke hearts, olives, and feta.',
      'Add lemon vinaigrette and toss to coat.',
      'Fold in fresh basil and pine nuts.',
      'Chill for 30 minutes before serving.',
    ],
    tags: ['mediterranean', 'pasta', 'salad', 'vegetarian', 'cold'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 210,
      protein_g: 8,
      carbs_g: 28,
      fat_g: 8,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 380,
    },
  },
];

export const mediterraneanBatch2Recipes = generateCuisineRecipes(batch2Configs);

export const mediterraneanAdditionalRecipes = generateCuisineRecipes(additionalConfigs);
