import type { CuisineRecipeConfig } from './types';
import { generateCuisineRecipes } from './types';

const configs: CuisineRecipeConfig[] = [
  {
    title: 'Shakshuka Mediterranean',
    description: 'Eggs poached in a vibrant tomato-pepper sauce with feta and fresh herbs.',
    cuisine: 'Mediterranean',
    prep_minutes: 10,
    cook_minutes: 20,
    servings: 4,
    calories: 220,
    ingredients: [
      { name: 'egg', quantity: '6', unit: 'large' },
      { name: 'tomato', quantity: '4', unit: 'diced' },
      { name: 'bell pepper', quantity: '1', unit: 'diced' },
      { name: 'feta cheese', quantity: '2', unit: 'oz, crumbled' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'cumin', quantity: '1', unit: 'tsp' },
      { name: 'garlic', quantity: '3', unit: 'cloves, minced' },
      { name: 'cilantro', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Sauté pepper and garlic in olive oil until soft.',
      'Add tomatoes and cumin, simmer 10 minutes.',
      'Make wells and crack eggs into the sauce.',
      'Cover and cook until whites set, 5-7 minutes.',
      'Top with feta and cilantro.',
      'Serve with crusty bread.',
    ],
    tags: ['mediterranean', 'eggs', 'tomato', 'breakfast', 'vegetarian'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 220,
      protein_g: 14,
      carbs_g: 10,
      fat_g: 14,
      fiber_g: 2,
      sugar_g: 5,
      sodium_mg: 440,
    },
  },
  {
    title: 'Grilled Halloumi Salad',
    description:
      'Charred halloumi cheese over mixed greens with pomegranate, mint, and lemon dressing.',
    cuisine: 'Mediterranean',
    prep_minutes: 15,
    cook_minutes: 5,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'halloumi cheese', quantity: '8', unit: 'oz, sliced' },
      { name: 'mixed greens', quantity: '4', unit: 'cups' },
      { name: 'pomegranate seeds', quantity: '1/3', unit: 'cup' },
      { name: 'cucumber', quantity: '1', unit: 'diced' },
      { name: 'mint', quantity: '2', unit: 'tbsp' },
      { name: 'lemon juice', quantity: '2', unit: 'tbsp' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'honey', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Grill halloumi slices 2 minutes per side until charred.',
      'Toss greens, cucumber, pomegranate, and mint.',
      'Whisk lemon juice, olive oil, and honey for dressing.',
      'Arrange salad on plates, top with grilled halloumi.',
      'Drizzle with dressing.',
      'Serve immediately.',
    ],
    tags: ['mediterranean', 'salad', 'halloumi', 'vegetarian', 'grilled'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 14,
      carbs_g: 12,
      fat_g: 20,
      fiber_g: 2,
      sugar_g: 8,
      sodium_mg: 520,
    },
  },
  {
    title: 'Lemon Herb Grilled Fish',
    description:
      'Whole grilled sea bass with lemon, herbs, and olive oil over a bed of roasted vegetables.',
    cuisine: 'Mediterranean',
    prep_minutes: 15,
    cook_minutes: 20,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'sea bass', quantity: '1', unit: 'whole (2 lb)' },
      { name: 'lemon', quantity: '2', unit: 'sliced' },
      { name: 'olive oil', quantity: '3', unit: 'tbsp' },
      { name: 'garlic', quantity: '4', unit: 'cloves, sliced' },
      { name: 'thyme', quantity: '4', unit: 'sprigs' },
      { name: 'rosemary', quantity: '2', unit: 'sprigs' },
      { name: 'cherry tomato', quantity: '1', unit: 'cup' },
      { name: 'capers', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Score fish on both sides. Season with salt, pepper, and olive oil.',
      'Stuff cavity with lemon slices, garlic, thyme, and rosemary.',
      'Place on a bed of cherry tomatoes and capers.',
      'Drizzle with olive oil and roast at 400°F for 20 minutes.',
      'Fish is done when flesh flakes easily.',
      'Serve with the roasted tomatoes and a drizzle of good olive oil.',
    ],
    tags: ['mediterranean', 'fish', 'grilled', 'lemon', 'healthy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 280,
      protein_g: 36,
      carbs_g: 6,
      fat_g: 12,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 380,
    },
  },
  {
    title: 'Stuffed Bell Peppers',
    description: 'Bell peppers filled with herbed quinoa, chickpeas, feta, and sun-dried tomatoes.',
    cuisine: 'Mediterranean',
    prep_minutes: 20,
    cook_minutes: 30,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'bell pepper', quantity: '4', unit: 'large, halved' },
      { name: 'quinoa', quantity: '1', unit: 'cup, cooked' },
      { name: 'chickpeas', quantity: '1', unit: 'can, drained' },
      { name: 'feta cheese', quantity: '1/4', unit: 'cup, crumbled' },
      { name: 'sun-dried tomato', quantity: '1/4', unit: 'cup, chopped' },
      { name: 'spinach', quantity: '2', unit: 'cups' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'oregano', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Halve peppers and remove seeds. Parboil 5 minutes.',
      'Mix quinoa, chickpeas, sun-dried tomatoes, spinach, oregano, and half the feta.',
      'Fill pepper halves with the mixture.',
      'Top with remaining feta and drizzle with olive oil.',
      'Bake at 375°F for 25-30 minutes until peppers are tender.',
      'Serve with a side of tzatziki or hummus.',
    ],
    tags: ['mediterranean', 'vegetarian', 'stuffed-pepper', 'quinoa', 'healthy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 12,
      carbs_g: 34,
      fat_g: 10,
      fiber_g: 8,
      sugar_g: 6,
      sodium_mg: 420,
    },
  },
  {
    title: 'Lamb Kofta',
    description:
      'Spiced ground lamb skewers grilled with Mediterranean herbs and served with tzatziki.',
    cuisine: 'Mediterranean',
    prep_minutes: 20,
    cook_minutes: 10,
    servings: 6,
    calories: 280,
    ingredients: [
      { name: 'ground lamb', quantity: '1.5', unit: 'lb' },
      { name: 'onion', quantity: '1', unit: 'grated' },
      { name: 'mint', quantity: '2', unit: 'tbsp, chopped' },
      { name: 'parsley', quantity: '2', unit: 'tbsp, chopped' },
      { name: 'cumin', quantity: '1', unit: 'tsp' },
      { name: 'coriander', quantity: '1', unit: 'tsp' },
      { name: 'garlic', quantity: '2', unit: 'cloves, minced' },
      { name: 'tzatziki', quantity: '1/2', unit: 'cup' },
    ],
    steps: [
      'Mix lamb, onion, mint, parsley, cumin, coriander, garlic, salt, and pepper.',
      'Shape around skewers into ovals.',
      'Grill over medium-high heat, turning, until charred and cooked through.',
      'Serve with tzatziki, warm pita, and salad.',
    ],
    tags: ['mediterranean', 'lamb', 'grilled', 'kebab', 'spiced'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 280,
      protein_g: 22,
      carbs_g: 2,
      fat_g: 20,
      fiber_g: 0,
      sugar_g: 1,
      sodium_mg: 320,
    },
  },
  {
    title: 'Mediterranean Pasta',
    description:
      'Penne with sun-dried tomatoes, olives, artichoke hearts, and feta in a lemon-herb sauce.',
    cuisine: 'Mediterranean',
    prep_minutes: 10,
    cook_minutes: 15,
    servings: 6,
    calories: 380,
    ingredients: [
      { name: 'penne pasta', quantity: '1', unit: 'lb' },
      { name: 'sun-dried tomato', quantity: '1/3', unit: 'cup, chopped' },
      { name: 'kalamata olives', quantity: '1/2', unit: 'cup, halved' },
      { name: 'artichoke hearts', quantity: '1', unit: 'can, quartered' },
      { name: 'feta cheese', quantity: '1/2', unit: 'cup, crumbled' },
      { name: 'garlic', quantity: '3', unit: 'cloves, minced' },
      { name: 'lemon juice', quantity: '2', unit: 'tbsp' },
      { name: 'basil', quantity: '1/4', unit: 'cup, fresh' },
    ],
    steps: [
      'Cook penne until al dente. Reserve 1 cup pasta water.',
      'Sauté garlic in olive oil, add sun-dried tomatoes.',
      'Add olives and artichoke hearts, toss to warm.',
      'Add pasta with a splash of pasta water and lemon juice.',
      'Toss with feta and fresh basil.',
      'Serve with a drizzle of olive oil.',
    ],
    tags: ['mediterranean', 'pasta', 'vegetarian', 'olives', 'feta'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 14,
      carbs_g: 52,
      fat_g: 12,
      fiber_g: 4,
      sugar_g: 4,
      sodium_mg: 680,
    },
  },
  {
    title: 'White Bean Soup',
    description: 'Hearty Tuscan-style white bean soup with kale, rosemary, and Parmesan.',
    cuisine: 'Mediterranean',
    prep_minutes: 10,
    cook_minutes: 30,
    servings: 6,
    calories: 220,
    ingredients: [
      { name: 'cannellini beans', quantity: '2', unit: 'cans, drained' },
      { name: 'kale', quantity: '2', unit: 'cups, chopped' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'garlic', quantity: '3', unit: 'cloves' },
      { name: 'rosemary', quantity: '2', unit: 'sprigs' },
      { name: 'vegetable broth', quantity: '4', unit: 'cups' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'parmesan rind', quantity: '1', unit: 'piece' },
    ],
    steps: [
      'Sauté onion and garlic in olive oil.',
      'Add beans, broth, rosemary, and Parmesan rind.',
      'Simmer 20 minutes. Mash half the beans for thickness.',
      'Add kale and cook 5 more minutes.',
      'Remove rosemary sprigs and Parmesan rind.',
      'Serve with crusty bread and a drizzle of olive oil.',
    ],
    tags: ['mediterranean', 'soup', 'vegetarian', 'beans', 'kale'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 220,
      protein_g: 10,
      carbs_g: 30,
      fat_g: 6,
      fiber_g: 8,
      sugar_g: 2,
      sodium_mg: 580,
    },
  },
  {
    title: 'Grilled Vegetable Platter',
    description:
      'Assorted grilled vegetables with balsamic glaze, fresh herbs, and whipped ricotta.',
    cuisine: 'Mediterranean',
    prep_minutes: 15,
    cook_minutes: 15,
    servings: 6,
    calories: 180,
    ingredients: [
      { name: 'zucchini', quantity: '2', unit: 'sliced lengthwise' },
      { name: 'eggplant', quantity: '1', unit: 'sliced' },
      { name: 'bell pepper', quantity: '2', unit: 'halved' },
      { name: 'asparagus', quantity: '1', unit: 'bunch' },
      { name: 'balsamic vinegar', quantity: '2', unit: 'tbsp' },
      { name: 'ricotta', quantity: '1/2', unit: 'cup, whipped' },
      { name: 'olive oil', quantity: '3', unit: 'tbsp' },
      { name: 'basil', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Brush all vegetables with olive oil and season.',
      'Grill vegetables on high heat until charred and tender.',
      'Arrange on a platter.',
      'Drizzle with balsamic vinegar.',
      'Add dollops of whipped ricotta.',
      'Garnish with fresh basil and serve.',
    ],
    tags: ['mediterranean', 'vegetarian', 'grilled', 'vegetables', 'healthy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 180,
      protein_g: 6,
      carbs_g: 14,
      fat_g: 12,
      fiber_g: 4,
      sugar_g: 6,
      sodium_mg: 280,
    },
  },
  {
    title: 'Lemon Orzo Salad',
    description:
      'Bright orzo pasta salad with cherry tomatoes, cucumber, feta, and a lemon-herb vinaigrette.',
    cuisine: 'Mediterranean',
    prep_minutes: 15,
    cook_minutes: 10,
    servings: 6,
    calories: 240,
    ingredients: [
      { name: 'orzo pasta', quantity: '1', unit: 'cup' },
      { name: 'cherry tomato', quantity: '1', unit: 'cup, halved' },
      { name: 'cucumber', quantity: '1', unit: 'diced' },
      { name: 'feta cheese', quantity: '1/4', unit: 'cup, crumbled' },
      { name: 'kalamata olives', quantity: '1/4', unit: 'cup' },
      { name: 'lemon juice', quantity: '3', unit: 'tbsp' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'dill', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Cook orzo until al dente. Rinse and cool.',
      'Combine orzo, tomatoes, cucumber, olives, and feta.',
      'Whisk lemon juice, olive oil, dill, salt, and pepper.',
      'Toss salad with dressing.',
      'Chill for 30 minutes.',
      'Serve as a side or light lunch.',
    ],
    tags: ['mediterranean', 'pasta-salad', 'vegetarian', 'lemon', 'cold'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 240,
      protein_g: 8,
      carbs_g: 32,
      fat_g: 10,
      fiber_g: 2,
      sugar_g: 4,
      sodium_mg: 480,
    },
  },
  {
    title: 'Baba Ganoush Mediterranean',
    description: 'Smoky eggplant dip with tahini, lemon, and olive oil served with warm flatbread.',
    cuisine: 'Mediterranean',
    prep_minutes: 10,
    cook_minutes: 40,
    servings: 6,
    calories: 110,
    ingredients: [
      { name: 'eggplant', quantity: '2', unit: 'large' },
      { name: 'tahini', quantity: '3', unit: 'tbsp' },
      { name: 'lemon juice', quantity: '2', unit: 'tbsp' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'smoked paprika', quantity: '1/4', unit: 'tsp' },
      { name: 'parsley', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Roast eggplants until charred and collapsed.',
      'Scoop out flesh, drain liquid.',
      'Blend with tahini, lemon, and garlic until smooth.',
      'Season with salt and paprika.',
      'Drizzle with olive oil.',
      'Serve with warm flatbread.',
    ],
    tags: ['mediterranean', 'dip', 'eggplant', 'vegan', 'smoky'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 110,
      protein_g: 3,
      carbs_g: 10,
      fat_g: 7,
      fiber_g: 4,
      sugar_g: 3,
      sodium_mg: 140,
    },
  },
  {
    title: 'Caprese Salad',
    description: 'Fresh mozzarella, ripe tomatoes, and basil drizzled with balsamic and olive oil.',
    cuisine: 'Mediterranean',
    prep_minutes: 10,
    cook_minutes: 0,
    servings: 4,
    calories: 200,
    ingredients: [
      { name: 'fresh mozzarella', quantity: '8', unit: 'oz, sliced' },
      { name: 'tomato', quantity: '3', unit: 'large, sliced' },
      { name: 'basil', quantity: '1', unit: 'cup, fresh leaves' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'balsamic glaze', quantity: '1', unit: 'tbsp' },
      { name: 'salt', quantity: '1/4', unit: 'tsp' },
      { name: 'black pepper', quantity: '1/4', unit: 'tsp' },
    ],
    steps: [
      'Slice mozzarella and tomatoes into 1/4-inch rounds.',
      'Alternate tomato and mozzarella slices on a plate.',
      'Tuck fresh basil leaves between slices.',
      'Drizzle with extra virgin olive oil.',
      'Add balsamic glaze in a thin stream.',
      'Season with salt and pepper. Serve immediately.',
    ],
    tags: ['mediterranean', 'salad', 'vegetarian', 'caprese', 'fresh'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 200,
      protein_g: 12,
      carbs_g: 6,
      fat_g: 14,
      fiber_g: 1,
      sugar_g: 3,
      sodium_mg: 320,
    },
  },
];

export const mediterraneanRecipes = generateCuisineRecipes(configs);

// ── Additional Mediterranean recipes ──────────────────────────────────────────

const additionalConfigs: CuisineRecipeConfig[] = [
  {
    title: 'Fattoush',
    description:
      'Levantine salad with toasted pita, crisp vegetables, sumac, and pomegranate molasses.',
    cuisine: 'Mediterranean',
    prep_minutes: 15,
    cook_minutes: 3,
    servings: 4,
    calories: 160,
    ingredients: [
      { name: 'pita bread', quantity: '2', unit: 'pieces, toasted & broken' },
      { name: 'cucumber', quantity: '1', unit: 'diced' },
      { name: 'tomato', quantity: '2', unit: 'diced' },
      { name: 'radish', quantity: '4', unit: 'sliced' },
      { name: 'sumac', quantity: '1', unit: 'tsp' },
      { name: 'pomegranate molasses', quantity: '1', unit: 'tbsp' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'lettuce', quantity: '2', unit: 'cups, torn' },
    ],
    steps: [
      'Toast pita until crispy and break into pieces.',
      'Combine cucumber, tomato, radish, and lettuce.',
      'Whisk olive oil, pomegranate molasses, sumac, and lemon.',
      'Toss salad with dressing.',
      'Add pita chips on top just before serving.',
      'Serve immediately.',
    ],
    tags: ['mediterranean', 'salad', 'pita', 'sumac', 'vegan'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 160,
      protein_g: 4,
      carbs_g: 20,
      fat_g: 8,
      fiber_g: 3,
      sugar_g: 4,
      sodium_mg: 220,
    },
  },
  {
    title: 'Mujadara',
    description:
      'Lentils and rice topped with crispy caramelized onions — a beloved Middle Eastern staple.',
    cuisine: 'Mediterranean',
    prep_minutes: 15,
    cook_minutes: 35,
    servings: 6,
    calories: 280,
    ingredients: [
      { name: 'brown lentils', quantity: '1', unit: 'cup' },
      { name: 'rice', quantity: '1', unit: 'cup' },
      { name: 'onion', quantity: '3', unit: 'large, sliced' },
      { name: 'olive oil', quantity: '3', unit: 'tbsp' },
      { name: 'cumin', quantity: '1', unit: 'tsp' },
      { name: 'cinnamon', quantity: '1/4', unit: 'tsp' },
      { name: 'yogurt', quantity: '1/2', unit: 'cup' },
    ],
    steps: [
      'Caramelize onions in olive oil until deep brown and crispy. Reserve half for topping.',
      'Cook lentils in water until almost tender.',
      'Add rice, cumin, cinnamon, and caramelized onion. Cook until rice is done.',
      'Season with salt and pepper.',
      'Serve topped with reserved crispy onions.',
      'Serve with yogurt on the side.',
    ],
    tags: ['mediterranean', 'lentils', 'rice', 'vegetarian', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 12,
      carbs_g: 44,
      fat_g: 8,
      fiber_g: 8,
      sugar_g: 4,
      sodium_mg: 280,
    },
  },
  {
    title: 'Hummus',
    description:
      'Silky smooth chickpea dip with tahini, lemon, and garlic, drizzled with olive oil.',
    cuisine: 'Mediterranean',
    prep_minutes: 10,
    cook_minutes: 0,
    servings: 8,
    calories: 100,
    ingredients: [
      { name: 'chickpeas', quantity: '2', unit: 'cans, drained' },
      { name: 'tahini', quantity: '1/4', unit: 'cup' },
      { name: 'lemon juice', quantity: '3', unit: 'tbsp' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'cumin', quantity: '1/2', unit: 'tsp' },
      { name: 'paprika', quantity: '1/4', unit: 'tsp' },
      { name: 'parsley', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Blend chickpeas, tahini, lemon juice, and garlic until very smooth.',
      'Add ice water while blending for extra creaminess.',
      'Season with cumin, salt, and pepper.',
      'Spread on a plate, make a well.',
      'Drizzle with olive oil and sprinkle paprika.',
      'Serve with warm pita bread.',
    ],
    tags: ['mediterranean', 'dip', 'chickpea', 'vegan', 'tahini'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 100,
      protein_g: 4,
      carbs_g: 12,
      fat_g: 4,
      fiber_g: 3,
      sugar_g: 1,
      sodium_mg: 180,
    },
  },
  {
    title: 'Tabbouleh',
    description: 'Fresh parsley and bulgur salad with tomato, mint, and lemon dressing.',
    cuisine: 'Mediterranean',
    prep_minutes: 20,
    cook_minutes: 0,
    servings: 6,
    calories: 120,
    ingredients: [
      { name: 'bulgur wheat', quantity: '1/2', unit: 'cup, soaked' },
      { name: 'parsley', quantity: '2', unit: 'cups, finely chopped' },
      { name: 'mint', quantity: '1/2', unit: 'cup, chopped' },
      { name: 'tomato', quantity: '3', unit: 'diced' },
      { name: 'onion', quantity: '1/4', unit: 'minced' },
      { name: 'lemon juice', quantity: '3', unit: 'tbsp' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Soak bulgur in boiling water for 20 minutes. Drain and squeeze dry.',
      'Finely chop parsley and mint.',
      'Dice tomato and mince onion.',
      'Toss everything together with lemon juice and olive oil.',
      'Season with salt and pepper.',
      'Chill before serving.',
    ],
    tags: ['mediterranean', 'salad', 'bulgur', 'parsley', 'vegan'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 120,
      protein_g: 3,
      carbs_g: 18,
      fat_g: 4,
      fiber_g: 4,
      sugar_g: 2,
      sodium_mg: 120,
    },
  },
  {
    title: 'Dolmades',
    description: 'Grape leaves stuffed with herbed rice, pine nuts, and lemon.',
    cuisine: 'Mediterranean',
    prep_minutes: 30,
    cook_minutes: 45,
    servings: 8,
    calories: 80,
    ingredients: [
      { name: 'grape leaves', quantity: '1', unit: 'jar, rinsed' },
      { name: 'rice', quantity: '1', unit: 'cup' },
      { name: 'pine nuts', quantity: '1/4', unit: 'cup' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'dill', quantity: '2', unit: 'tbsp' },
      { name: 'mint', quantity: '1', unit: 'tbsp' },
      { name: 'lemon juice', quantity: '3', unit: 'tbsp' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Sauté onion, add rice, pine nuts, herbs, and lemon juice.',
      'Place a spoonful of filling on each grape leaf, roll tightly.',
      'Arrange in a pot, seam-side down.',
      'Add lemon juice, olive oil, and water.',
      'Weight down with a plate and simmer 45 minutes.',
      'Serve warm or cold with yogurt.',
    ],
    tags: ['mediterranean', 'grape-leaves', 'vegetarian', 'rice', 'stuffed'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 80,
      protein_g: 2,
      carbs_g: 12,
      fat_g: 3,
      fiber_g: 1,
      sugar_g: 1,
      sodium_mg: 320,
    },
  },
  {
    title: 'Fasolada',
    description: 'Greek white bean soup with tomato, celery, and olive oil — hearty and warming.',
    cuisine: 'Mediterranean',
    prep_minutes: 10,
    cook_minutes: 60,
    servings: 6,
    calories: 220,
    ingredients: [
      { name: 'white beans', quantity: '1', unit: 'lb, soaked' },
      { name: 'tomato', quantity: '2', unit: 'diced' },
      { name: 'celery', quantity: '3', unit: 'stalks, diced' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'olive oil', quantity: '1/4', unit: 'cup' },
      { name: 'carrot', quantity: '1', unit: 'diced' },
      { name: 'tomato paste', quantity: '1', unit: 'tbsp' },
      { name: 'parsley', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Sauté onion, celery, and carrot in olive oil.',
      'Add beans, tomato, tomato paste, and water.',
      'Simmer until beans are very tender, about 1 hour.',
      'Add a generous pour of olive oil at the end.',
      'Season with salt and pepper.',
      'Serve with crusty bread.',
    ],
    tags: ['mediterranean', 'soup', 'beans', 'vegan', 'greek'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 220,
      protein_g: 10,
      carbs_g: 30,
      fat_g: 8,
      fiber_g: 10,
      sugar_g: 4,
      sodium_mg: 380,
    },
  },
  {
    title: 'Muhammara',
    description: 'Spicy roasted red pepper and walnut dip with pomegranate molasses.',
    cuisine: 'Mediterranean',
    prep_minutes: 10,
    cook_minutes: 20,
    servings: 6,
    calories: 120,
    ingredients: [
      { name: 'roasted red pepper', quantity: '3', unit: 'large' },
      { name: 'walnuts', quantity: '1/2', unit: 'cup' },
      { name: 'breadcrumbs', quantity: '2', unit: 'tbsp' },
      { name: 'pomegranate molasses', quantity: '1', unit: 'tbsp' },
      { name: 'cumin', quantity: '1/2', unit: 'tsp' },
      { name: 'chili flakes', quantity: '1/2', unit: 'tsp' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Roast peppers until charred. Peel and seed.',
      'Blend peppers, walnuts, breadcrumbs, and pomegranate molasses.',
      'Add cumin, chili flakes, salt, and olive oil.',
      'Blend until slightly chunky.',
      'Transfer to a bowl, drizzle with olive oil.',
      'Serve with pita or crackers.',
    ],
    tags: ['mediterranean', 'dip', 'pepper', 'walnut', 'spicy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 120,
      protein_g: 3,
      carbs_g: 8,
      fat_g: 8,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 180,
    },
  },
  {
    title: 'Avgolemono',
    description: 'Greek egg-lemon soup with rice — silky, tangy, and deeply comforting.',
    cuisine: 'Mediterranean',
    prep_minutes: 10,
    cook_minutes: 20,
    servings: 4,
    calories: 180,
    ingredients: [
      { name: 'chicken broth', quantity: '6', unit: 'cups' },
      { name: 'rice', quantity: '1/3', unit: 'cup' },
      { name: 'egg', quantity: '3', unit: 'large' },
      { name: 'lemon juice', quantity: '3', unit: 'tbsp' },
      { name: 'chicken', quantity: '1', unit: 'cup, shredded (optional)' },
      { name: 'dill', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Simmer rice in chicken broth until tender.',
      'Add shredded chicken if using.',
      'Beat eggs with lemon juice.',
      'Slowly whisk hot broth into the egg-lemon mixture to temper.',
      'Pour back into the pot, stir gently. Do not boil.',
      'Serve with dill.',
    ],
    tags: ['mediterranean', 'soup', 'egg', 'lemon', 'greek'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 180,
      protein_g: 10,
      carbs_g: 16,
      fat_g: 8,
      fiber_g: 0,
      sugar_g: 1,
      sodium_mg: 480,
    },
  },
  {
    title: 'Lamb Meatballs',
    description: 'Spiced Mediterranean lamb meatballs with mint yogurt and couscous.',
    cuisine: 'Mediterranean',
    prep_minutes: 20,
    cook_minutes: 15,
    servings: 4,
    calories: 320,
    ingredients: [
      { name: 'ground lamb', quantity: '1', unit: 'lb' },
      { name: 'onion', quantity: '1/2', unit: 'grated' },
      { name: 'mint', quantity: '2', unit: 'tbsp, chopped' },
      { name: 'cumin', quantity: '1', unit: 'tsp' },
      { name: 'cinnamon', quantity: '1/4', unit: 'tsp' },
      { name: 'yogurt', quantity: '1/2', unit: 'cup' },
      { name: 'couscous', quantity: '1', unit: 'cup' },
      { name: 'garlic', quantity: '2', unit: 'cloves, minced' },
    ],
    steps: [
      'Mix lamb, onion, mint, cumin, cinnamon, garlic, salt, and pepper.',
      'Form into meatballs.',
      'Pan-fry until golden and cooked through.',
      'Cook couscous according to package.',
      'Mix yogurt with minced garlic and a pinch of salt.',
      'Serve meatballs over couscous with mint yogurt.',
    ],
    tags: ['mediterranean', 'lamb', 'meatballs', 'mint', 'couscous'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 22,
      carbs_g: 20,
      fat_g: 16,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 420,
    },
  },
  {
    title: 'Stuffed Eggplant',
    description: 'Roasted eggplant halves filled with spiced lamb, tomatoes, and pine nuts.',
    cuisine: 'Mediterranean',
    prep_minutes: 20,
    cook_minutes: 40,
    servings: 4,
    calories: 320,
    ingredients: [
      { name: 'eggplant', quantity: '2', unit: 'large, halved' },
      { name: 'ground lamb', quantity: '1/2', unit: 'lb' },
      { name: 'tomato', quantity: '2', unit: 'diced' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'pine nuts', quantity: '2', unit: 'tbsp' },
      { name: 'cinnamon', quantity: '1/4', unit: 'tsp' },
      { name: 'allspice', quantity: '1/4', unit: 'tsp' },
      { name: 'parsley', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Scoop out eggplant flesh, leaving shells. Chop flesh.',
      'Sauté onion and lamb with cinnamon and allspice.',
      'Add chopped eggplant and tomato. Cook until thick.',
      'Fill eggplant shells with the mixture.',
      'Top with pine nuts.',
      'Bake at 375°F for 30 minutes. Garnish with parsley.',
    ],
    tags: ['mediterranean', 'eggplant', 'lamb', 'stuffed', 'baked'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 320,
      protein_g: 18,
      carbs_g: 14,
      fat_g: 20,
      fiber_g: 6,
      sugar_g: 6,
      sodium_mg: 380,
    },
  },
];

export const mediterraneanAdditionalRecipes = generateCuisineRecipes(additionalConfigs);
