import type { CuisineRecipeConfig } from './types';
import { generateCuisineRecipes } from './types';

const configs: CuisineRecipeConfig[] = [
  {
    title: 'Shakshuka Mediterranean',
    description: 'Eggs poached in a vibrant tomato-pepper sauce with feta and fresh herbs.',
    cuisine: 'Mediterranean',
    prep_minutes: 10,
    cook_minutes: 20,
    servings: 4,
    calories: 220,
    ingredients: [
      { name: 'egg', quantity: '6', unit: 'large' },
      { name: 'tomato', quantity: '4', unit: 'diced' },
      { name: 'bell pepper', quantity: '1', unit: 'diced' },
      { name: 'feta cheese', quantity: '2', unit: 'oz, crumbled' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'cumin', quantity: '1', unit: 'tsp' },
      { name: 'garlic', quantity: '3', unit: 'cloves, minced' },
      { name: 'cilantro', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Sauté pepper and garlic in olive oil until soft.',
      'Add tomatoes and cumin, simmer 10 minutes.',
      'Make wells and crack eggs into the sauce.',
      'Cover and cook until whites set, 5-7 minutes.',
      'Top with feta and cilantro.',
      'Serve with crusty bread.',
    ],
    tags: ['mediterranean', 'eggs', 'tomato', 'breakfast', 'vegetarian'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 220,
      protein_g: 14,
      carbs_g: 10,
      fat_g: 14,
      fiber_g: 2,
      sugar_g: 5,
      sodium_mg: 440,
    },
  },
  {
    title: 'Grilled Halloumi Salad',
    description:
      'Charred halloumi cheese over mixed greens with pomegranate, mint, and lemon dressing.',
    cuisine: 'Mediterranean',
    prep_minutes: 15,
    cook_minutes: 5,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'halloumi cheese', quantity: '8', unit: 'oz, sliced' },
      { name: 'mixed greens', quantity: '4', unit: 'cups' },
      { name: 'pomegranate seeds', quantity: '1/3', unit: 'cup' },
      { name: 'cucumber', quantity: '1', unit: 'diced' },
      { name: 'mint', quantity: '2', unit: 'tbsp' },
      { name: 'lemon juice', quantity: '2', unit: 'tbsp' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'honey', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Grill halloumi slices 2 minutes per side until charred.',
      'Toss greens, cucumber, pomegranate, and mint.',
      'Whisk lemon juice, olive oil, and honey for dressing.',
      'Arrange salad on plates, top with grilled halloumi.',
      'Drizzle with dressing.',
      'Serve immediately.',
    ],
    tags: ['mediterranean', 'salad', 'halloumi', 'vegetarian', 'grilled'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 14,
      carbs_g: 12,
      fat_g: 20,
      fiber_g: 2,
      sugar_g: 8,
      sodium_mg: 520,
    },
  },
  {
    title: 'Lemon Herb Grilled Fish',
    description:
      'Whole grilled sea bass with lemon, herbs, and olive oil over a bed of roasted vegetables.',
    cuisine: 'Mediterranean',
    prep_minutes: 15,
    cook_minutes: 20,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'sea bass', quantity: '1', unit: 'whole (2 lb)' },
      { name: 'lemon', quantity: '2', unit: 'sliced' },
      { name: 'olive oil', quantity: '3', unit: 'tbsp' },
      { name: 'garlic', quantity: '4', unit: 'cloves, sliced' },
      { name: 'thyme', quantity: '4', unit: 'sprigs' },
      { name: 'rosemary', quantity: '2', unit: 'sprigs' },
      { name: 'cherry tomato', quantity: '1', unit: 'cup' },
      { name: 'capers', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Score fish on both sides. Season with salt, pepper, and olive oil.',
      'Stuff cavity with lemon slices, garlic, thyme, and rosemary.',
      'Place on a bed of cherry tomatoes and capers.',
      'Drizzle with olive oil and roast at 400°F for 20 minutes.',
      'Fish is done when flesh flakes easily.',
      'Serve with the roasted tomatoes and a drizzle of good olive oil.',
    ],
    tags: ['mediterranean', 'fish', 'grilled', 'lemon', 'healthy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 280,
      protein_g: 36,
      carbs_g: 6,
      fat_g: 12,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 380,
    },
  },
  {
    title: 'Stuffed Bell Peppers',
    description: 'Bell peppers filled with herbed quinoa, chickpeas, feta, and sun-dried tomatoes.',
    cuisine: 'Mediterranean',
    prep_minutes: 20,
    cook_minutes: 30,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'bell pepper', quantity: '4', unit: 'large, halved' },
      { name: 'quinoa', quantity: '1', unit: 'cup, cooked' },
      { name: 'chickpeas', quantity: '1', unit: 'can, drained' },
      { name: 'feta cheese', quantity: '1/4', unit: 'cup, crumbled' },
      { name: 'sun-dried tomato', quantity: '1/4', unit: 'cup, chopped' },
      { name: 'spinach', quantity: '2', unit: 'cups' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'oregano', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Halve peppers and remove seeds. Parboil 5 minutes.',
      'Mix quinoa, chickpeas, sun-dried tomatoes, spinach, oregano, and half the feta.',
      'Fill pepper halves with the mixture.',
      'Top with remaining feta and drizzle with olive oil.',
      'Bake at 375°F for 25-30 minutes until peppers are tender.',
      'Serve with a side of tzatziki or hummus.',
    ],
    tags: ['mediterranean', 'vegetarian', 'stuffed-pepper', 'quinoa', 'healthy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 12,
      carbs_g: 34,
      fat_g: 10,
      fiber_g: 8,
      sugar_g: 6,
      sodium_mg: 420,
    },
  },
  {
    title: 'Lamb Kofta',
    description:
      'Spiced ground lamb skewers grilled with Mediterranean herbs and served with tzatziki.',
    cuisine: 'Mediterranean',
    prep_minutes: 20,
    cook_minutes: 10,
    servings: 6,
    calories: 280,
    ingredients: [
      { name: 'ground lamb', quantity: '1.5', unit: 'lb' },
      { name: 'onion', quantity: '1', unit: 'grated' },
      { name: 'mint', quantity: '2', unit: 'tbsp, chopped' },
      { name: 'parsley', quantity: '2', unit: 'tbsp, chopped' },
      { name: 'cumin', quantity: '1', unit: 'tsp' },
      { name: 'coriander', quantity: '1', unit: 'tsp' },
      { name: 'garlic', quantity: '2', unit: 'cloves, minced' },
      { name: 'tzatziki', quantity: '1/2', unit: 'cup' },
    ],
    steps: [
      'Mix lamb, onion, mint, parsley, cumin, coriander, garlic, salt, and pepper.',
      'Shape around skewers into ovals.',
      'Grill over medium-high heat, turning, until charred and cooked through.',
      'Serve with tzatziki, warm pita, and salad.',
    ],
    tags: ['mediterranean', 'lamb', 'grilled', 'kebab', 'spiced'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 280,
      protein_g: 22,
      carbs_g: 2,
      fat_g: 20,
      fiber_g: 0,
      sugar_g: 1,
      sodium_mg: 320,
    },
  },
  {
    title: 'Mediterranean Pasta',
    description:
      'Penne with sun-dried tomatoes, olives, artichoke hearts, and feta in a lemon-herb sauce.',
    cuisine: 'Mediterranean',
    prep_minutes: 10,
    cook_minutes: 15,
    servings: 6,
    calories: 380,
    ingredients: [
      { name: 'penne pasta', quantity: '1', unit: 'lb' },
      { name: 'sun-dried tomato', quantity: '1/3', unit: 'cup, chopped' },
      { name: 'kalamata olives', quantity: '1/2', unit: 'cup, halved' },
      { name: 'artichoke hearts', quantity: '1', unit: 'can, quartered' },
      { name: 'feta cheese', quantity: '1/2', unit: 'cup, crumbled' },
      { name: 'garlic', quantity: '3', unit: 'cloves, minced' },
      { name: 'lemon juice', quantity: '2', unit: 'tbsp' },
      { name: 'basil', quantity: '1/4', unit: 'cup, fresh' },
    ],
    steps: [
      'Cook penne until al dente. Reserve 1 cup pasta water.',
      'Sauté garlic in olive oil, add sun-dried tomatoes.',
      'Add olives and artichoke hearts, toss to warm.',
      'Add pasta with a splash of pasta water and lemon juice.',
      'Toss with feta and fresh basil.',
      'Serve with a drizzle of olive oil.',
    ],
    tags: ['mediterranean', 'pasta', 'vegetarian', 'olives', 'feta'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 14,
      carbs_g: 52,
      fat_g: 12,
      fiber_g: 4,
      sugar_g: 4,
      sodium_mg: 680,
    },
  },
  {
    title: 'White Bean Soup',
    description: 'Hearty Tuscan-style white bean soup with kale, rosemary, and Parmesan.',
    cuisine: 'Mediterranean',
    prep_minutes: 10,
    cook_minutes: 30,
    servings: 6,
    calories: 220,
    ingredients: [
      { name: 'cannellini beans', quantity: '2', unit: 'cans, drained' },
      { name: 'kale', quantity: '2', unit: 'cups, chopped' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'garlic', quantity: '3', unit: 'cloves' },
      { name: 'rosemary', quantity: '2', unit: 'sprigs' },
      { name: 'vegetable broth', quantity: '4', unit: 'cups' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'parmesan rind', quantity: '1', unit: 'piece' },
    ],
    steps: [
      'Sauté onion and garlic in olive oil.',
      'Add beans, broth, rosemary, and Parmesan rind.',
      'Simmer 20 minutes. Mash half the beans for thickness.',
      'Add kale and cook 5 more minutes.',
      'Remove rosemary sprigs and Parmesan rind.',
      'Serve with crusty bread and a drizzle of olive oil.',
    ],
    tags: ['mediterranean', 'soup', 'vegetarian', 'beans', 'kale'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 220,
      protein_g: 10,
      carbs_g: 30,
      fat_g: 6,
      fiber_g: 8,
      sugar_g: 2,
      sodium_mg: 580,
    },
  },
  {
    title: 'Grilled Vegetable Platter',
    description:
      'Assorted grilled vegetables with balsamic glaze, fresh herbs, and whipped ricotta.',
    cuisine: 'Mediterranean',
    prep_minutes: 15,
    cook_minutes: 15,
    servings: 6,
    calories: 180,
    ingredients: [
      { name: 'zucchini', quantity: '2', unit: 'sliced lengthwise' },
      { name: 'eggplant', quantity: '1', unit: 'sliced' },
      { name: 'bell pepper', quantity: '2', unit: 'halved' },
      { name: 'asparagus', quantity: '1', unit: 'bunch' },
      { name: 'balsamic vinegar', quantity: '2', unit: 'tbsp' },
      { name: 'ricotta', quantity: '1/2', unit: 'cup, whipped' },
      { name: 'olive oil', quantity: '3', unit: 'tbsp' },
      { name: 'basil', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Brush all vegetables with olive oil and season.',
      'Grill vegetables on high heat until charred and tender.',
      'Arrange on a platter.',
      'Drizzle with balsamic vinegar.',
      'Add dollops of whipped ricotta.',
      'Garnish with fresh basil and serve.',
    ],
    tags: ['mediterranean', 'vegetarian', 'grilled', 'vegetables', 'healthy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 180,
      protein_g: 6,
      carbs_g: 14,
      fat_g: 12,
      fiber_g: 4,
      sugar_g: 6,
      sodium_mg: 280,
    },
  },
  {
    title: 'Lemon Orzo Salad',
    description:
      'Bright orzo pasta salad with cherry tomatoes, cucumber, feta, and a lemon-herb vinaigrette.',
    cuisine: 'Mediterranean',
    prep_minutes: 15,
    cook_minutes: 10,
    servings: 6,
    calories: 240,
    ingredients: [
      { name: 'orzo pasta', quantity: '1', unit: 'cup' },
      { name: 'cherry tomato', quantity: '1', unit: 'cup, halved' },
      { name: 'cucumber', quantity: '1', unit: 'diced' },
      { name: 'feta cheese', quantity: '1/4', unit: 'cup, crumbled' },
      { name: 'kalamata olives', quantity: '1/4', unit: 'cup' },
      { name: 'lemon juice', quantity: '3', unit: 'tbsp' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'dill', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Cook orzo until al dente. Rinse and cool.',
      'Combine orzo, tomatoes, cucumber, olives, and feta.',
      'Whisk lemon juice, olive oil, dill, salt, and pepper.',
      'Toss salad with dressing.',
      'Chill for 30 minutes.',
      'Serve as a side or light lunch.',
    ],
    tags: ['mediterranean', 'pasta-salad', 'vegetarian', 'lemon', 'cold'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 240,
      protein_g: 8,
      carbs_g: 32,
      fat_g: 10,
      fiber_g: 2,
      sugar_g: 4,
      sodium_mg: 480,
    },
  },
  {
    title: 'Baba Ganoush Mediterranean',
    description: 'Smoky eggplant dip with tahini, lemon, and olive oil served with warm flatbread.',
    cuisine: 'Mediterranean',
    prep_minutes: 10,
    cook_minutes: 40,
    servings: 6,
    calories: 110,
    ingredients: [
      { name: 'eggplant', quantity: '2', unit: 'large' },
      { name: 'tahini', quantity: '3', unit: 'tbsp' },
      { name: 'lemon juice', quantity: '2', unit: 'tbsp' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'smoked paprika', quantity: '1/4', unit: 'tsp' },
      { name: 'parsley', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Roast eggplants until charred and collapsed.',
      'Scoop out flesh, drain liquid.',
      'Blend with tahini, lemon, and garlic until smooth.',
      'Season with salt and paprika.',
      'Drizzle with olive oil.',
      'Serve with warm flatbread.',
    ],
    tags: ['mediterranean', 'dip', 'eggplant', 'vegan', 'smoky'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 110,
      protein_g: 3,
      carbs_g: 10,
      fat_g: 7,
      fiber_g: 4,
      sugar_g: 3,
      sodium_mg: 140,
    },
  },
  {
    title: 'Caprese Salad',
    description: 'Fresh mozzarella, ripe tomatoes, and basil drizzled with balsamic and olive oil.',
    cuisine: 'Mediterranean',
    prep_minutes: 10,
    cook_minutes: 0,
    servings: 4,
    calories: 200,
    ingredients: [
      { name: 'fresh mozzarella', quantity: '8', unit: 'oz, sliced' },
      { name: 'tomato', quantity: '3', unit: 'large, sliced' },
      { name: 'basil', quantity: '1', unit: 'cup, fresh leaves' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'balsamic glaze', quantity: '1', unit: 'tbsp' },
      { name: 'salt', quantity: '1/4', unit: 'tsp' },
      { name: 'black pepper', quantity: '1/4', unit: 'tsp' },
    ],
    steps: [
      'Slice mozzarella and tomatoes into 1/4-inch rounds.',
      'Alternate tomato and mozzarella slices on a plate.',
      'Tuck fresh basil leaves between slices.',
      'Drizzle with extra virgin olive oil.',
      'Add balsamic glaze in a thin stream.',
      'Season with salt and pepper. Serve immediately.',
    ],
    tags: ['mediterranean', 'salad', 'vegetarian', 'caprese', 'fresh'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 200,
      protein_g: 12,
      carbs_g: 6,
      fat_g: 14,
      fiber_g: 1,
      sugar_g: 3,
      sodium_mg: 320,
    },
  },
];

export const mediterraneanRecipes = generateCuisineRecipes(configs);
