import type { CuisineRecipeConfig } from './types';
import { generateCuisineRecipes } from './types';

const configs: CuisineRecipeConfig[] = [
  {
    title: 'Tacos al Pastor',
    description:
      'Marinated pork grilled on a vertical spit, served with pineapple and cilantro on corn tortillas.',
    cuisine: 'Mexican',
    prep_minutes: 30,
    cook_minutes: 20,
    servings: 6,
    calories: 340,
    ingredients: [
      { name: 'pork shoulder', quantity: '2', unit: 'lbs, sliced thin' },
      { name: 'dried guajillo chiles', quantity: '4', unit: 'whole' },
      { name: 'achiote paste', quantity: '2', unit: 'tbsp' },
      { name: 'pineapple', quantity: '1/2', unit: 'cup, diced' },
      { name: 'corn tortillas', quantity: '18', unit: 'small' },
      { name: 'white onion', quantity: '1', unit: 'diced' },
      { name: 'cilantro', quantity: '1/2', unit: 'cup, chopped' },
      { name: 'lime', quantity: '4', unit: 'wedges' },
    ],
    steps: [
      'Toast and blend guajillo chiles with achiote, vinegar, and spices into a marinade.',
      'Coat pork slices in marinade. Refrigerate at least 2 hours or overnight.',
      'Grill or pan-sear pork until charred. Dice into small pieces.',
      'Serve on warm corn tortillas with pineapple, onion, cilantro, and lime.',
    ],
    tags: ['tacos al pastor', 'mexican', 'pork', 'taco', 'street food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 340,
      protein_g: 24,
      carbs_g: 28,
      fat_g: 14,
      fiber_g: 4,
      sugar_g: 4,
      sodium_mg: 520,
    },
  },
  {
    title: 'Mole Poblano',
    description: 'Complex Mexican sauce of dried chiles, chocolate, and spices over chicken.',
    cuisine: 'Mexican',
    prep_minutes: 40,
    cook_minutes: 60,
    servings: 8,
    calories: 420,
    ingredients: [
      { name: 'chicken pieces', quantity: '3', unit: 'lbs' },
      { name: 'dried ancho chiles', quantity: '4', unit: 'whole' },
      { name: 'dried pasilla chiles', quantity: '3', unit: 'whole' },
      { name: 'Mexican chocolate', quantity: '1', unit: 'oz' },
      { name: 'sesame seeds', quantity: '2', unit: 'tbsp' },
      { name: 'onion', quantity: '1', unit: 'medium' },
      { name: 'garlic', quantity: '4', unit: 'cloves' },
      { name: 'peanut butter', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Toast and soak dried chiles. Blend with onion, garlic, sesame, chocolate, and spices.',
      'Sear chicken pieces. Set aside.',
      'Fry the mole paste in lard for 5 minutes. Add broth and simmer.',
      'Return chicken to mole. Simmer 40 minutes until tender. Serve with rice and sesame garnish.',
    ],
    tags: ['mole', 'mexican', 'chicken', 'chocolate', 'traditional'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 30,
      carbs_g: 22,
      fat_g: 22,
      fiber_g: 5,
      sugar_g: 4,
      sodium_mg: 480,
    },
  },
  {
    title: 'Guacamole',
    description: 'Fresh avocado dip with lime, cilantro, jalapeño, and tomato.',
    cuisine: 'Mexican',
    prep_minutes: 10,
    cook_minutes: 0,
    servings: 6,
    calories: 120,
    ingredients: [
      { name: 'avocado', quantity: '3', unit: 'ripe' },
      { name: 'lime juice', quantity: '2', unit: 'tbsp' },
      { name: 'cilantro', quantity: '1/4', unit: 'cup, chopped' },
      { name: 'jalapeño', quantity: '1', unit: 'minced' },
      { name: 'tomato', quantity: '1', unit: 'diced' },
      { name: 'onion', quantity: '2', unit: 'tbsp, minced' },
      { name: 'salt', quantity: '1/2', unit: 'tsp' },
    ],
    steps: [
      'Halve and pit avocados. Scoop into a bowl.',
      'Add lime juice and mash to desired consistency.',
      'Fold in cilantro, jalapeño, tomato, and onion.',
      'Season with salt. Serve immediately with tortilla chips.',
    ],
    tags: ['guacamole', 'mexican', 'avocado', 'dip', 'vegan'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 120,
      protein_g: 2,
      carbs_g: 6,
      fat_g: 11,
      fiber_g: 5,
      sugar_g: 1,
      sodium_mg: 140,
    },
  },
  {
    title: 'Pozole Rojo',
    description: 'Hearty Mexican hominy stew with pork and red chile broth.',
    cuisine: 'Mexican',
    prep_minutes: 20,
    cook_minutes: 120,
    servings: 8,
    calories: 380,
    ingredients: [
      { name: 'pork shoulder', quantity: '2', unit: 'lbs, cubed' },
      { name: 'hominy', quantity: '2', unit: 'cans, drained' },
      { name: 'dried guajillo chiles', quantity: '6', unit: 'whole' },
      { name: 'onion', quantity: '1', unit: 'large, quartered' },
      { name: 'garlic', quantity: '4', unit: 'cloves' },
      { name: 'oregano', quantity: '1', unit: 'tsp' },
      { name: 'cabbage', quantity: '2', unit: 'cups, shredded' },
      { name: 'radish', quantity: '4', unit: 'sliced' },
    ],
    steps: [
      'Boil pork with onion and garlic until tender, about 90 minutes.',
      'Toast and blend guajillo chiles into a smooth sauce. Strain.',
      'Add chile sauce and hominy to the pork broth. Simmer 20 minutes.',
      'Serve with shredded cabbage, radish, oregano, and lime.',
    ],
    tags: ['pozole', 'mexican', 'pork', 'hominy', 'stew'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 28,
      carbs_g: 32,
      fat_g: 14,
      fiber_g: 6,
      sugar_g: 3,
      sodium_mg: 580,
    },
  },
  {
    title: 'Enchiladas Verdes',
    description:
      'Corn tortillas filled with shredded chicken, rolled in tomatillo salsa, and baked.',
    cuisine: 'Mexican',
    prep_minutes: 25,
    cook_minutes: 20,
    servings: 6,
    calories: 380,
    ingredients: [
      { name: 'shredded chicken', quantity: '3', unit: 'cups' },
      { name: 'corn tortillas', quantity: '12', unit: 'pieces' },
      { name: 'tomatillos', quantity: '1', unit: 'lb' },
      { name: 'serrano pepper', quantity: '2', unit: 'whole' },
      { name: 'cilantro', quantity: '1/2', unit: 'cup' },
      { name: 'sour cream', quantity: '1/4', unit: 'cup' },
      { name: 'queso fresco', quantity: '1/2', unit: 'cup' },
      { name: 'onion', quantity: '1/2', unit: 'diced' },
    ],
    steps: [
      'Boil tomatillos and serranos. Blend with cilantro and onion for salsa verde.',
      'Fill tortillas with shredded chicken, roll tightly, and place seam-down in a dish.',
      'Pour salsa verde over enchiladas. Top with sour cream and queso fresco.',
      'Bake at 375°F for 15 minutes until bubbly.',
    ],
    tags: ['enchiladas', 'mexican', 'chicken', 'tomatillo', 'verde'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 26,
      carbs_g: 32,
      fat_g: 16,
      fiber_g: 4,
      sugar_g: 4,
      sodium_mg: 520,
    },
  },
  {
    title: 'Carnitas',
    description: 'Slow-braised then crisped pork shoulder, perfect for tacos and burritos.',
    cuisine: 'Mexican',
    prep_minutes: 15,
    cook_minutes: 180,
    servings: 8,
    calories: 340,
    ingredients: [
      { name: 'pork shoulder', quantity: '4', unit: 'lbs' },
      { name: 'orange juice', quantity: '1/2', unit: 'cup' },
      { name: 'lime juice', quantity: '2', unit: 'tbsp' },
      { name: 'garlic', quantity: '4', unit: 'cloves' },
      { name: 'cumin', quantity: '1', unit: 'tbsp' },
      { name: 'oregano', quantity: '1', unit: 'tsp' },
      { name: 'bay leaf', quantity: '2', unit: 'pieces' },
      { name: 'lard', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Cut pork into large chunks. Season with cumin, oregano, salt, and pepper.',
      'Place in a Dutch oven with garlic, bay leaf, orange and lime juice, and lard.',
      'Simmer covered for 2.5-3 hours until tender and falling apart.',
      'Shred and crisp under the broiler or in a hot skillet. Serve in tacos.',
    ],
    tags: ['carnitas', 'mexican', 'pork', 'slow-cooked', 'taco filling'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 340,
      protein_g: 28,
      carbs_g: 4,
      fat_g: 24,
      fiber_g: 0,
      sugar_g: 2,
      sodium_mg: 440,
    },
  },
  {
    title: 'Elote (Mexican Street Corn)',
    description: 'Grilled corn on the cob slathered with mayo, cotija cheese, chili, and lime.',
    cuisine: 'Mexican',
    prep_minutes: 5,
    cook_minutes: 15,
    servings: 4,
    calories: 220,
    ingredients: [
      { name: 'corn on the cob', quantity: '4', unit: 'ears' },
      { name: 'mayonnaise', quantity: '1/4', unit: 'cup' },
      { name: 'cotija cheese', quantity: '1/2', unit: 'cup, crumbled' },
      { name: 'chili powder', quantity: '1', unit: 'tsp' },
      { name: 'lime', quantity: '2', unit: 'wedges' },
      { name: 'cilantro', quantity: '2', unit: 'tbsp, chopped' },
    ],
    steps: [
      'Grill corn until charred on all sides, about 10 minutes.',
      'Brush with mayonnaise while hot.',
      'Roll in crumbled cotija cheese and sprinkle with chili powder.',
      'Squeeze lime over top and garnish with cilantro.',
    ],
    tags: ['elote', 'mexican', 'corn', 'street food', 'grilled'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 220,
      protein_g: 8,
      carbs_g: 30,
      fat_g: 10,
      fiber_g: 4,
      sugar_g: 5,
      sodium_mg: 380,
    },
  },
  {
    title: 'Sopa de Lima',
    description: 'Yucatecan lime soup with shredded turkey, crispy tortilla strips, and avocado.',
    cuisine: 'Mexican',
    prep_minutes: 15,
    cook_minutes: 25,
    servings: 6,
    calories: 240,
    ingredients: [
      { name: 'shredded turkey', quantity: '2', unit: 'cups' },
      { name: 'chicken broth', quantity: '6', unit: 'cups' },
      { name: 'lime juice', quantity: '1/4', unit: 'cup' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'tomato', quantity: '2', unit: 'diced' },
      { name: 'tortilla strips', quantity: '2', unit: 'cups, fried' },
      { name: 'avocado', quantity: '1', unit: 'sliced' },
      { name: 'cilantro', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Sauté onion and tomato. Add broth and bring to a boil.',
      'Add shredded turkey and simmer 10 minutes.',
      'Add lime juice and season with salt and oregano.',
      'Serve in bowls topped with crispy tortilla strips, avocado, and cilantro.',
    ],
    tags: ['sopa de lima', 'mexican', 'soup', 'lime', 'yucatecan'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 240,
      protein_g: 20,
      carbs_g: 20,
      fat_g: 8,
      fiber_g: 4,
      sugar_g: 3,
      sodium_mg: 480,
    },
  },
  {
    title: 'Chiles Rellenos',
    description:
      'Roasted poblano peppers stuffed with cheese, dipped in egg batter, and fried golden.',
    cuisine: 'Mexican',
    prep_minutes: 25,
    cook_minutes: 15,
    servings: 4,
    calories: 320,
    ingredients: [
      { name: 'poblano peppers', quantity: '4', unit: 'large' },
      { name: 'Oaxaca cheese', quantity: '8', unit: 'oz, shredded' },
      { name: 'eggs', quantity: '4', unit: 'separated' },
      { name: 'flour', quantity: '1/4', unit: 'cup' },
      { name: 'vegetable oil', quantity: '2', unit: 'cups, for frying' },
      { name: 'tomato sauce', quantity: '1', unit: 'cup' },
      { name: 'onion', quantity: '1/2', unit: 'diced' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
    ],
    steps: [
      'Char poblanos over flame or under broiler. Peel and make a slit to remove seeds.',
      'Stuff each pepper with shredded cheese.',
      'Whip egg whites to stiff peaks, fold in yolks and flour. Dip peppers in batter.',
      'Fry in hot oil until golden. Serve with warm tomato sauce.',
    ],
    tags: ['chiles rellenos', 'mexican', 'poblano', 'cheese', 'fried'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 16,
      carbs_g: 18,
      fat_g: 20,
      fiber_g: 3,
      sugar_g: 4,
      sodium_mg: 520,
    },
  },
  {
    title: 'Tamales de Rajas',
    description: 'Mexican corn-husk tamales filled with roasted poblano strips and cheese.',
    cuisine: 'Mexican',
    prep_minutes: 45,
    cook_minutes: 90,
    servings: 12,
    calories: 260,
    ingredients: [
      { name: 'masa harina', quantity: '4', unit: 'cups' },
      { name: 'lard', quantity: '1', unit: 'cup' },
      { name: 'poblano pepper', quantity: '3', unit: 'roasted, cut into strips' },
      { name: 'Oaxaca cheese', quantity: '1', unit: 'cup, shredded' },
      { name: 'corn husks', quantity: '24', unit: 'soaked' },
      { name: 'baking powder', quantity: '1', unit: 'tsp' },
      { name: 'chicken broth', quantity: '1', unit: 'cup' },
      { name: 'salt', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Beat lard until fluffy. Mix in masa, baking powder, salt, and broth.',
      'Spread masa on corn husks. Add poblano strips and cheese filling.',
      'Fold and tie husks. Stand upright in a steamer.',
      'Steam for 90 minutes until masa pulls away from husks cleanly.',
    ],
    tags: ['tamales', 'mexican', 'poblano', 'cheese', 'steamed'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 260,
      protein_g: 8,
      carbs_g: 24,
      fat_g: 16,
      fiber_g: 2,
      sugar_g: 1,
      sodium_mg: 420,
    },
  },
  {
    title: 'Pico de Gallo',
    description: 'Fresh Mexican salsa of diced tomato, onion, jalapeño, and cilantro.',
    cuisine: 'Mexican',
    prep_minutes: 10,
    cook_minutes: 0,
    servings: 8,
    calories: 20,
    ingredients: [
      { name: 'tomato', quantity: '4', unit: 'diced' },
      { name: 'white onion', quantity: '1/2', unit: 'diced' },
      { name: 'jalapeño', quantity: '1', unit: 'minced' },
      { name: 'cilantro', quantity: '1/4', unit: 'cup, chopped' },
      { name: 'lime juice', quantity: '1', unit: 'tbsp' },
      { name: 'salt', quantity: '1/4', unit: 'tsp' },
    ],
    steps: [
      'Dice tomatoes and onion to similar size.',
      'Mince jalapeño finely. Chop cilantro.',
      'Combine all ingredients with lime juice and salt.',
      'Let sit 15 minutes for flavors to meld. Serve with chips or tacos.',
    ],
    tags: ['pico de gallo', 'mexican', 'salsa', 'fresh', 'vegan'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 20,
      protein_g: 1,
      carbs_g: 4,
      fat_g: 0,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 80,
    },
  },
  {
    title: 'Birria Tacos',
    description: 'Crispy consommé-dipped tacos filled with braised beef and melted cheese.',
    cuisine: 'Mexican',
    prep_minutes: 20,
    cook_minutes: 180,
    servings: 6,
    calories: 420,
    ingredients: [
      { name: 'beef chuck', quantity: '3', unit: 'lbs' },
      { name: 'dried guajillo chiles', quantity: '6', unit: 'whole' },
      { name: 'dried ancho chiles', quantity: '3', unit: 'whole' },
      { name: 'corn tortillas', quantity: '12', unit: 'pieces' },
      { name: 'Oaxaca cheese', quantity: '1', unit: 'cup, shredded' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'cilantro', quantity: '1/4', unit: 'cup' },
      { name: 'lime', quantity: '4', unit: 'wedges' },
    ],
    steps: [
      'Toast and blend dried chiles with spices. Marinate beef in the paste overnight.',
      'Braise beef in the chile sauce for 3 hours until fork-tender. Shred.',
      'Dip tortillas in consommé (braising liquid). Fill with beef and cheese. Pan-fry until crispy.',
      'Serve with a cup of consommé for dipping, topped with onion, cilantro, and lime.',
    ],
    tags: ['birria', 'mexican', 'beef', 'taco', 'consommé'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 32,
      carbs_g: 28,
      fat_g: 20,
      fiber_g: 4,
      sugar_g: 3,
      sodium_mg: 620,
    },
  },
  {
    title: 'Huevos Rancheros',
    description: 'Fried eggs on crispy tortillas with ranchero sauce, beans, and avocado.',
    cuisine: 'Mexican',
    prep_minutes: 10,
    cook_minutes: 15,
    servings: 4,
    calories: 360,
    ingredients: [
      { name: 'eggs', quantity: '4', unit: 'large, fried' },
      { name: 'corn tortillas', quantity: '4', unit: 'pieces' },
      { name: 'ranchero sauce', quantity: '1', unit: 'cup' },
      { name: 'refried beans', quantity: '1', unit: 'cup' },
      { name: 'avocado', quantity: '1', unit: 'sliced' },
      { name: 'queso fresco', quantity: '1/4', unit: 'cup, crumbled' },
      { name: 'cilantro', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Warm tortillas and spread with refried beans.',
      'Top each with a fried egg and ranchero sauce.',
      'Add avocado slices, queso fresco, and cilantro.',
      'Serve immediately with a side of salsa.',
    ],
    tags: ['huevos rancheros', 'mexican', 'breakfast', 'eggs', 'vegetarian'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 360,
      protein_g: 16,
      carbs_g: 32,
      fat_g: 18,
      fiber_g: 6,
      sugar_g: 3,
      sodium_mg: 580,
    },
  },
  {
    title: 'Flan Napolitano',
    description: 'Creamy Mexican caramel custard flan with a golden sugar top.',
    cuisine: 'Mexican',
    prep_minutes: 15,
    cook_minutes: 60,
    servings: 8,
    calories: 280,
    ingredients: [
      { name: 'sugar', quantity: '1', unit: 'cup, for caramel' },
      { name: 'cream cheese', quantity: '4', unit: 'oz' },
      { name: 'sweetened condensed milk', quantity: '1', unit: 'can' },
      { name: 'evaporated milk', quantity: '1', unit: 'can' },
      { name: 'eggs', quantity: '5', unit: 'large' },
      { name: 'vanilla extract', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Melt sugar in a pan until golden. Pour into a flan mold, coating the bottom.',
      'Blend cream cheese, condensed milk, evaporated milk, eggs, and vanilla until smooth.',
      'Pour custard over caramel. Cover with foil.',
      'Bake in a water bath at 350°F for 50-60 minutes. Cool and invert to serve.',
    ],
    tags: ['flan', 'mexican', 'dessert', 'caramel', 'custard'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 8,
      carbs_g: 38,
      fat_g: 12,
      fiber_g: 0,
      sugar_g: 34,
      sodium_mg: 160,
    },
  },
  {
    title: 'Sopes',
    description: 'Thick fried corn discs topped with beans, meat, lettuce, and crema.',
    cuisine: 'Mexican',
    prep_minutes: 20,
    cook_minutes: 15,
    servings: 6,
    calories: 300,
    ingredients: [
      { name: 'masa harina', quantity: '2', unit: 'cups' },
      { name: 'water', quantity: '1.5', unit: 'cups' },
      { name: 'refried beans', quantity: '1', unit: 'cup' },
      { name: 'ground beef', quantity: '1/2', unit: 'lb, cooked' },
      { name: 'lettuce', quantity: '1', unit: 'cup, shredded' },
      { name: 'Mexican crema', quantity: '1/4', unit: 'cup' },
      { name: 'queso fresco', quantity: '1/2', unit: 'cup' },
      { name: 'salsa', quantity: '1/2', unit: 'cup' },
    ],
    steps: [
      'Mix masa and water into dough. Form into thick discs and pinch edges to create a rim.',
      'Cook on a griddle 3 minutes per side until set. Deep-fry briefly until crispy.',
      'Spread beans, add beef, lettuce, crema, and queso fresco.',
      'Top with salsa and serve immediately.',
    ],
    tags: ['sopes', 'mexican', 'corn', 'handheld', 'street food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 300,
      protein_g: 14,
      carbs_g: 32,
      fat_g: 14,
      fiber_g: 4,
      sugar_g: 2,
      sodium_mg: 480,
    },
  },
];

export const mexicanRecipes = generateCuisineRecipes(configs);
