import type { CuisineRecipeConfig } from './types';
import { generateCuisineRecipes } from './types';

const configs: CuisineRecipeConfig[] = [
  {
    title: 'Tacos al Pastor',
    description:
      'Marinated pork grilled on a vertical spit, served with pineapple and cilantro on corn tortillas.',
    cuisine: 'Mexican',
    prep_minutes: 30,
    cook_minutes: 20,
    servings: 6,
    calories: 340,
    ingredients: [
      { name: 'pork shoulder', quantity: '2', unit: 'lbs, sliced thin' },
      { name: 'dried guajillo chiles', quantity: '4', unit: 'whole' },
      { name: 'achiote paste', quantity: '2', unit: 'tbsp' },
      { name: 'pineapple', quantity: '1/2', unit: 'cup, diced' },
      { name: 'corn tortillas', quantity: '18', unit: 'small' },
      { name: 'white onion', quantity: '1', unit: 'diced' },
      { name: 'cilantro', quantity: '1/2', unit: 'cup, chopped' },
      { name: 'lime', quantity: '4', unit: 'wedges' },
    ],
    steps: [
      'Toast and blend guajillo chiles with achiote, vinegar, and spices into a marinade.',
      'Coat pork slices in marinade. Refrigerate at least 2 hours or overnight.',
      'Grill or pan-sear pork until charred. Dice into small pieces.',
      'Serve on warm corn tortillas with pineapple, onion, cilantro, and lime.',
    ],
    tags: ['tacos al pastor', 'mexican', 'pork', 'taco', 'street food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 340,
      protein_g: 24,
      carbs_g: 28,
      fat_g: 14,
      fiber_g: 4,
      sugar_g: 4,
      sodium_mg: 520,
    },
  },
  {
    title: 'Mole Poblano',
    description: 'Complex Mexican sauce of dried chiles, chocolate, and spices over chicken.',
    cuisine: 'Mexican',
    prep_minutes: 40,
    cook_minutes: 60,
    servings: 8,
    calories: 420,
    ingredients: [
      { name: 'chicken pieces', quantity: '3', unit: 'lbs' },
      { name: 'dried ancho chiles', quantity: '4', unit: 'whole' },
      { name: 'dried pasilla chiles', quantity: '3', unit: 'whole' },
      { name: 'Mexican chocolate', quantity: '1', unit: 'oz' },
      { name: 'sesame seeds', quantity: '2', unit: 'tbsp' },
      { name: 'onion', quantity: '1', unit: 'medium' },
      { name: 'garlic', quantity: '4', unit: 'cloves' },
      { name: 'peanut butter', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Toast and soak dried chiles. Blend with onion, garlic, sesame, chocolate, and spices.',
      'Sear chicken pieces. Set aside.',
      'Fry the mole paste in lard for 5 minutes. Add broth and simmer.',
      'Return chicken to mole. Simmer 40 minutes until tender. Serve with rice and sesame garnish.',
    ],
    tags: ['mole', 'mexican', 'chicken', 'chocolate', 'traditional'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 30,
      carbs_g: 22,
      fat_g: 22,
      fiber_g: 5,
      sugar_g: 4,
      sodium_mg: 480,
    },
  },
  {
    title: 'Guacamole',
    description: 'Fresh avocado dip with lime, cilantro, jalapeño, and tomato.',
    cuisine: 'Mexican',
    prep_minutes: 10,
    cook_minutes: 0,
    servings: 6,
    calories: 120,
    ingredients: [
      { name: 'avocado', quantity: '3', unit: 'ripe' },
      { name: 'lime juice', quantity: '2', unit: 'tbsp' },
      { name: 'cilantro', quantity: '1/4', unit: 'cup, chopped' },
      { name: 'jalapeño', quantity: '1', unit: 'minced' },
      { name: 'tomato', quantity: '1', unit: 'diced' },
      { name: 'onion', quantity: '2', unit: 'tbsp, minced' },
      { name: 'salt', quantity: '1/2', unit: 'tsp' },
    ],
    steps: [
      'Halve and pit avocados. Scoop into a bowl.',
      'Add lime juice and mash to desired consistency.',
      'Fold in cilantro, jalapeño, tomato, and onion.',
      'Season with salt. Serve immediately with tortilla chips.',
    ],
    tags: ['guacamole', 'mexican', 'avocado', 'dip', 'vegan'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 120,
      protein_g: 2,
      carbs_g: 6,
      fat_g: 11,
      fiber_g: 5,
      sugar_g: 1,
      sodium_mg: 140,
    },
  },
  {
    title: 'Pozole Rojo',
    description: 'Hearty Mexican hominy stew with pork and red chile broth.',
    cuisine: 'Mexican',
    prep_minutes: 20,
    cook_minutes: 120,
    servings: 8,
    calories: 380,
    ingredients: [
      { name: 'pork shoulder', quantity: '2', unit: 'lbs, cubed' },
      { name: 'hominy', quantity: '2', unit: 'cans, drained' },
      { name: 'dried guajillo chiles', quantity: '6', unit: 'whole' },
      { name: 'onion', quantity: '1', unit: 'large, quartered' },
      { name: 'garlic', quantity: '4', unit: 'cloves' },
      { name: 'oregano', quantity: '1', unit: 'tsp' },
      { name: 'cabbage', quantity: '2', unit: 'cups, shredded' },
      { name: 'radish', quantity: '4', unit: 'sliced' },
    ],
    steps: [
      'Boil pork with onion and garlic until tender, about 90 minutes.',
      'Toast and blend guajillo chiles into a smooth sauce. Strain.',
      'Add chile sauce and hominy to the pork broth. Simmer 20 minutes.',
      'Serve with shredded cabbage, radish, oregano, and lime.',
    ],
    tags: ['pozole', 'mexican', 'pork', 'hominy', 'stew'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 28,
      carbs_g: 32,
      fat_g: 14,
      fiber_g: 6,
      sugar_g: 3,
      sodium_mg: 580,
    },
  },
  {
    title: 'Enchiladas Verdes',
    description:
      'Corn tortillas filled with shredded chicken, rolled in tomatillo salsa, and baked.',
    cuisine: 'Mexican',
    prep_minutes: 25,
    cook_minutes: 20,
    servings: 6,
    calories: 380,
    ingredients: [
      { name: 'shredded chicken', quantity: '3', unit: 'cups' },
      { name: 'corn tortillas', quantity: '12', unit: 'pieces' },
      { name: 'tomatillos', quantity: '1', unit: 'lb' },
      { name: 'serrano pepper', quantity: '2', unit: 'whole' },
      { name: 'cilantro', quantity: '1/2', unit: 'cup' },
      { name: 'sour cream', quantity: '1/4', unit: 'cup' },
      { name: 'queso fresco', quantity: '1/2', unit: 'cup' },
      { name: 'onion', quantity: '1/2', unit: 'diced' },
    ],
    steps: [
      'Boil tomatillos and serranos. Blend with cilantro and onion for salsa verde.',
      'Fill tortillas with shredded chicken, roll tightly, and place seam-down in a dish.',
      'Pour salsa verde over enchiladas. Top with sour cream and queso fresco.',
      'Bake at 375°F for 15 minutes until bubbly.',
    ],
    tags: ['enchiladas', 'mexican', 'chicken', 'tomatillo', 'verde'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 26,
      carbs_g: 32,
      fat_g: 16,
      fiber_g: 4,
      sugar_g: 4,
      sodium_mg: 520,
    },
  },
  {
    title: 'Carnitas',
    description: 'Slow-braised then crisped pork shoulder, perfect for tacos and burritos.',
    cuisine: 'Mexican',
    prep_minutes: 15,
    cook_minutes: 180,
    servings: 8,
    calories: 340,
    ingredients: [
      { name: 'pork shoulder', quantity: '4', unit: 'lbs' },
      { name: 'orange juice', quantity: '1/2', unit: 'cup' },
      { name: 'lime juice', quantity: '2', unit: 'tbsp' },
      { name: 'garlic', quantity: '4', unit: 'cloves' },
      { name: 'cumin', quantity: '1', unit: 'tbsp' },
      { name: 'oregano', quantity: '1', unit: 'tsp' },
      { name: 'bay leaf', quantity: '2', unit: 'pieces' },
      { name: 'lard', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Cut pork into large chunks. Season with cumin, oregano, salt, and pepper.',
      'Place in a Dutch oven with garlic, bay leaf, orange and lime juice, and lard.',
      'Simmer covered for 2.5-3 hours until tender and falling apart.',
      'Shred and crisp under the broiler or in a hot skillet. Serve in tacos.',
    ],
    tags: ['carnitas', 'mexican', 'pork', 'slow-cooked', 'taco filling'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 340,
      protein_g: 28,
      carbs_g: 4,
      fat_g: 24,
      fiber_g: 0,
      sugar_g: 2,
      sodium_mg: 440,
    },
  },
  {
    title: 'Elote (Mexican Street Corn)',
    description: 'Grilled corn on the cob slathered with mayo, cotija cheese, chili, and lime.',
    cuisine: 'Mexican',
    prep_minutes: 5,
    cook_minutes: 15,
    servings: 4,
    calories: 220,
    ingredients: [
      { name: 'corn on the cob', quantity: '4', unit: 'ears' },
      { name: 'mayonnaise', quantity: '1/4', unit: 'cup' },
      { name: 'cotija cheese', quantity: '1/2', unit: 'cup, crumbled' },
      { name: 'chili powder', quantity: '1', unit: 'tsp' },
      { name: 'lime', quantity: '2', unit: 'wedges' },
      { name: 'cilantro', quantity: '2', unit: 'tbsp, chopped' },
    ],
    steps: [
      'Grill corn until charred on all sides, about 10 minutes.',
      'Brush with mayonnaise while hot.',
      'Roll in crumbled cotija cheese and sprinkle with chili powder.',
      'Squeeze lime over top and garnish with cilantro.',
    ],
    tags: ['elote', 'mexican', 'corn', 'street food', 'grilled'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 220,
      protein_g: 8,
      carbs_g: 30,
      fat_g: 10,
      fiber_g: 4,
      sugar_g: 5,
      sodium_mg: 380,
    },
  },
  {
    title: 'Sopa de Lima',
    description: 'Yucatecan lime soup with shredded turkey, crispy tortilla strips, and avocado.',
    cuisine: 'Mexican',
    prep_minutes: 15,
    cook_minutes: 25,
    servings: 6,
    calories: 240,
    ingredients: [
      { name: 'shredded turkey', quantity: '2', unit: 'cups' },
      { name: 'chicken broth', quantity: '6', unit: 'cups' },
      { name: 'lime juice', quantity: '1/4', unit: 'cup' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'tomato', quantity: '2', unit: 'diced' },
      { name: 'tortilla strips', quantity: '2', unit: 'cups, fried' },
      { name: 'avocado', quantity: '1', unit: 'sliced' },
      { name: 'cilantro', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Sauté onion and tomato. Add broth and bring to a boil.',
      'Add shredded turkey and simmer 10 minutes.',
      'Add lime juice and season with salt and oregano.',
      'Serve in bowls topped with crispy tortilla strips, avocado, and cilantro.',
    ],
    tags: ['sopa de lima', 'mexican', 'soup', 'lime', 'yucatecan'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 240,
      protein_g: 20,
      carbs_g: 20,
      fat_g: 8,
      fiber_g: 4,
      sugar_g: 3,
      sodium_mg: 480,
    },
  },
  {
    title: 'Chiles Rellenos',
    description:
      'Roasted poblano peppers stuffed with cheese, dipped in egg batter, and fried golden.',
    cuisine: 'Mexican',
    prep_minutes: 25,
    cook_minutes: 15,
    servings: 4,
    calories: 320,
    ingredients: [
      { name: 'poblano peppers', quantity: '4', unit: 'large' },
      { name: 'Oaxaca cheese', quantity: '8', unit: 'oz, shredded' },
      { name: 'eggs', quantity: '4', unit: 'separated' },
      { name: 'flour', quantity: '1/4', unit: 'cup' },
      { name: 'vegetable oil', quantity: '2', unit: 'cups, for frying' },
      { name: 'tomato sauce', quantity: '1', unit: 'cup' },
      { name: 'onion', quantity: '1/2', unit: 'diced' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
    ],
    steps: [
      'Char poblanos over flame or under broiler. Peel and make a slit to remove seeds.',
      'Stuff each pepper with shredded cheese.',
      'Whip egg whites to stiff peaks, fold in yolks and flour. Dip peppers in batter.',
      'Fry in hot oil until golden. Serve with warm tomato sauce.',
    ],
    tags: ['chiles rellenos', 'mexican', 'poblano', 'cheese', 'fried'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 16,
      carbs_g: 18,
      fat_g: 20,
      fiber_g: 3,
      sugar_g: 4,
      sodium_mg: 520,
    },
  },
  {
    title: 'Tamales de Rajas',
    description: 'Mexican corn-husk tamales filled with roasted poblano strips and cheese.',
    cuisine: 'Mexican',
    prep_minutes: 45,
    cook_minutes: 90,
    servings: 12,
    calories: 260,
    ingredients: [
      { name: 'masa harina', quantity: '4', unit: 'cups' },
      { name: 'lard', quantity: '1', unit: 'cup' },
      { name: 'poblano pepper', quantity: '3', unit: 'roasted, cut into strips' },
      { name: 'Oaxaca cheese', quantity: '1', unit: 'cup, shredded' },
      { name: 'corn husks', quantity: '24', unit: 'soaked' },
      { name: 'baking powder', quantity: '1', unit: 'tsp' },
      { name: 'chicken broth', quantity: '1', unit: 'cup' },
      { name: 'salt', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Beat lard until fluffy. Mix in masa, baking powder, salt, and broth.',
      'Spread masa on corn husks. Add poblano strips and cheese filling.',
      'Fold and tie husks. Stand upright in a steamer.',
      'Steam for 90 minutes until masa pulls away from husks cleanly.',
    ],
    tags: ['tamales', 'mexican', 'poblano', 'cheese', 'steamed'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 260,
      protein_g: 8,
      carbs_g: 24,
      fat_g: 16,
      fiber_g: 2,
      sugar_g: 1,
      sodium_mg: 420,
    },
  },
  {
    title: 'Pico de Gallo',
    description: 'Fresh Mexican salsa of diced tomato, onion, jalapeño, and cilantro.',
    cuisine: 'Mexican',
    prep_minutes: 10,
    cook_minutes: 0,
    servings: 8,
    calories: 20,
    ingredients: [
      { name: 'tomato', quantity: '4', unit: 'diced' },
      { name: 'white onion', quantity: '1/2', unit: 'diced' },
      { name: 'jalapeño', quantity: '1', unit: 'minced' },
      { name: 'cilantro', quantity: '1/4', unit: 'cup, chopped' },
      { name: 'lime juice', quantity: '1', unit: 'tbsp' },
      { name: 'salt', quantity: '1/4', unit: 'tsp' },
    ],
    steps: [
      'Dice tomatoes and onion to similar size.',
      'Mince jalapeño finely. Chop cilantro.',
      'Combine all ingredients with lime juice and salt.',
      'Let sit 15 minutes for flavors to meld. Serve with chips or tacos.',
    ],
    tags: ['pico de gallo', 'mexican', 'salsa', 'fresh', 'vegan'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 20,
      protein_g: 1,
      carbs_g: 4,
      fat_g: 0,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 80,
    },
  },
  {
    title: 'Birria Tacos',
    description: 'Crispy consommé-dipped tacos filled with braised beef and melted cheese.',
    cuisine: 'Mexican',
    prep_minutes: 20,
    cook_minutes: 180,
    servings: 6,
    calories: 420,
    ingredients: [
      { name: 'beef chuck', quantity: '3', unit: 'lbs' },
      { name: 'dried guajillo chiles', quantity: '6', unit: 'whole' },
      { name: 'dried ancho chiles', quantity: '3', unit: 'whole' },
      { name: 'corn tortillas', quantity: '12', unit: 'pieces' },
      { name: 'Oaxaca cheese', quantity: '1', unit: 'cup, shredded' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'cilantro', quantity: '1/4', unit: 'cup' },
      { name: 'lime', quantity: '4', unit: 'wedges' },
    ],
    steps: [
      'Toast and blend dried chiles with spices. Marinate beef in the paste overnight.',
      'Braise beef in the chile sauce for 3 hours until fork-tender. Shred.',
      'Dip tortillas in consommé (braising liquid). Fill with beef and cheese. Pan-fry until crispy.',
      'Serve with a cup of consommé for dipping, topped with onion, cilantro, and lime.',
    ],
    tags: ['birria', 'mexican', 'beef', 'taco', 'consommé'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 32,
      carbs_g: 28,
      fat_g: 20,
      fiber_g: 4,
      sugar_g: 3,
      sodium_mg: 620,
    },
  },
  {
    title: 'Huevos Rancheros',
    description: 'Fried eggs on crispy tortillas with ranchero sauce, beans, and avocado.',
    cuisine: 'Mexican',
    prep_minutes: 10,
    cook_minutes: 15,
    servings: 4,
    calories: 360,
    ingredients: [
      { name: 'eggs', quantity: '4', unit: 'large, fried' },
      { name: 'corn tortillas', quantity: '4', unit: 'pieces' },
      { name: 'ranchero sauce', quantity: '1', unit: 'cup' },
      { name: 'refried beans', quantity: '1', unit: 'cup' },
      { name: 'avocado', quantity: '1', unit: 'sliced' },
      { name: 'queso fresco', quantity: '1/4', unit: 'cup, crumbled' },
      { name: 'cilantro', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Warm tortillas and spread with refried beans.',
      'Top each with a fried egg and ranchero sauce.',
      'Add avocado slices, queso fresco, and cilantro.',
      'Serve immediately with a side of salsa.',
    ],
    tags: ['huevos rancheros', 'mexican', 'breakfast', 'eggs', 'vegetarian'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 360,
      protein_g: 16,
      carbs_g: 32,
      fat_g: 18,
      fiber_g: 6,
      sugar_g: 3,
      sodium_mg: 580,
    },
  },
  {
    title: 'Flan Napolitano',
    description: 'Creamy Mexican caramel custard flan with a golden sugar top.',
    cuisine: 'Mexican',
    prep_minutes: 15,
    cook_minutes: 60,
    servings: 8,
    calories: 280,
    ingredients: [
      { name: 'sugar', quantity: '1', unit: 'cup, for caramel' },
      { name: 'cream cheese', quantity: '4', unit: 'oz' },
      { name: 'sweetened condensed milk', quantity: '1', unit: 'can' },
      { name: 'evaporated milk', quantity: '1', unit: 'can' },
      { name: 'eggs', quantity: '5', unit: 'large' },
      { name: 'vanilla extract', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Melt sugar in a pan until golden. Pour into a flan mold, coating the bottom.',
      'Blend cream cheese, condensed milk, evaporated milk, eggs, and vanilla until smooth.',
      'Pour custard over caramel. Cover with foil.',
      'Bake in a water bath at 350°F for 50-60 minutes. Cool and invert to serve.',
    ],
    tags: ['flan', 'mexican', 'dessert', 'caramel', 'custard'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 8,
      carbs_g: 38,
      fat_g: 12,
      fiber_g: 0,
      sugar_g: 34,
      sodium_mg: 160,
    },
  },
  {
    title: 'Sopes',
    description: 'Thick fried corn discs topped with beans, meat, lettuce, and crema.',
    cuisine: 'Mexican',
    prep_minutes: 20,
    cook_minutes: 15,
    servings: 6,
    calories: 300,
    ingredients: [
      { name: 'masa harina', quantity: '2', unit: 'cups' },
      { name: 'water', quantity: '1.5', unit: 'cups' },
      { name: 'refried beans', quantity: '1', unit: 'cup' },
      { name: 'ground beef', quantity: '1/2', unit: 'lb, cooked' },
      { name: 'lettuce', quantity: '1', unit: 'cup, shredded' },
      { name: 'Mexican crema', quantity: '1/4', unit: 'cup' },
      { name: 'queso fresco', quantity: '1/2', unit: 'cup' },
      { name: 'salsa', quantity: '1/2', unit: 'cup' },
    ],
    steps: [
      'Mix masa and water into dough. Form into thick discs and pinch edges to create a rim.',
      'Cook on a griddle 3 minutes per side until set. Deep-fry briefly until crispy.',
      'Spread beans, add beef, lettuce, crema, and queso fresco.',
      'Top with salsa and serve immediately.',
    ],
    tags: ['sopes', 'mexican', 'corn', 'handheld', 'street food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 300,
      protein_g: 14,
      carbs_g: 32,
      fat_g: 14,
      fiber_g: 4,
      sugar_g: 2,
      sodium_mg: 480,
    },
  },
  {
    title: 'Churros with Chocolate Sauce',
    description:
      'Crispy fried dough dusted in cinnamon sugar, served with rich Mexican chocolate dipping sauce.',
    cuisine: 'Mexican',
    prep_minutes: 15,
    cook_minutes: 20,
    servings: 6,
    calories: 290,
    ingredients: [
      { name: 'water', quantity: '1', unit: 'cup' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
      { name: 'all-purpose flour', quantity: '1', unit: 'cup' },
      { name: 'eggs', quantity: '2', unit: 'large' },
      { name: 'sugar', quantity: '1/2', unit: 'cup' },
      { name: 'cinnamon', quantity: '1', unit: 'tsp' },
      { name: 'Mexican chocolate', quantity: '3', unit: 'oz, chopped' },
      { name: 'heavy cream', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Bring water and butter to a boil. Stir in flour until a ball forms.',
      'Beat in eggs one at a time until smooth.',
      'Pipe dough into hot oil (375°F) in 4-inch strips. Fry until golden.',
      'Roll churros in cinnamon sugar mixture.',
      'Melt chocolate with cream for dipping sauce. Serve warm.',
    ],
    tags: ['churros', 'mexican', 'dessert', 'fried', 'chocolate'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 290,
      protein_g: 4,
      carbs_g: 34,
      fat_g: 15,
      fiber_g: 1,
      sugar_g: 18,
      sodium_mg: 120,
    },
  },
  {
    title: 'Quesadillas de Flor de Calabaza',
    description:
      'Crunchy corn tortilla quesadillas filled with squash blossoms, Oaxacan cheese, and epazote.',
    cuisine: 'Mexican',
    prep_minutes: 15,
    cook_minutes: 10,
    servings: 4,
    calories: 260,
    ingredients: [
      { name: 'corn tortillas', quantity: '8', unit: 'small' },
      { name: 'squash blossoms', quantity: '12', unit: 'whole' },
      { name: 'Oaxacan cheese', quantity: '8', unit: 'oz, shredded' },
      { name: 'epazote', quantity: '4', unit: 'leaves, chopped' },
      { name: 'onion', quantity: '1/4', unit: 'cup, diced' },
      { name: 'serrano chile', quantity: '1', unit: 'minced' },
      { name: 'vegetable oil', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Sauté onion and serrano chile in oil until soft. Add squash blossoms and epazote, cook 2 minutes.',
      'Place cheese and filling on half of each tortilla. Fold over.',
      'Cook quesadillas on a dry comal until cheese melts and tortilla is crispy, about 2 minutes per side.',
      'Serve with salsa verde.',
    ],
    tags: ['quesadilla', 'mexican', 'squash blossom', 'vegetarian', 'cheese'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 260,
      protein_g: 14,
      carbs_g: 24,
      fat_g: 13,
      fiber_g: 3,
      sugar_g: 2,
      sodium_mg: 380,
    },
  },
  {
    title: 'Burrito de Carne Asada',
    description:
      'Large flour tortilla stuffed with grilled steak, rice, beans, guacamole, and pico de gallo.',
    cuisine: 'Mexican',
    prep_minutes: 20,
    cook_minutes: 15,
    servings: 4,
    calories: 680,
    ingredients: [
      { name: 'flank steak', quantity: '1', unit: 'lb' },
      { name: 'flour tortillas', quantity: '4', unit: 'large (burrito-size)' },
      { name: 'Mexican rice', quantity: '2', unit: 'cups, cooked' },
      { name: 'pinto beans', quantity: '1', unit: 'cup, cooked' },
      { name: 'guacamole', quantity: '1', unit: 'cup' },
      { name: 'pico de gallo', quantity: '1', unit: 'cup' },
      { name: 'sour cream', quantity: '1/2', unit: 'cup' },
      { name: 'cheddar cheese', quantity: '1', unit: 'cup, shredded' },
    ],
    steps: [
      'Season flank steak with salt, pepper, and lime juice. Grill to medium, then slice thin.',
      'Warm flour tortillas on a comal.',
      'Layer rice, beans, steak, guacamole, pico, sour cream, and cheese on each tortilla.',
      'Fold sides in, then roll tightly into a burrito.',
      'Toast seam-side down on a hot skillet until golden.',
    ],
    tags: ['burrito', 'mexican', 'carne asada', 'steak', 'rice and beans'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 680,
      protein_g: 38,
      carbs_g: 62,
      fat_g: 30,
      fiber_g: 8,
      sugar_g: 4,
      sodium_mg: 920,
    },
  },
  {
    title: 'Sopa de Fideo',
    description:
      'Comforting Mexican noodle soup with tomato-broth, thin vermicelli, and mild chile flavor.',
    cuisine: 'Mexican',
    prep_minutes: 10,
    cook_minutes: 20,
    servings: 6,
    calories: 220,
    ingredients: [
      { name: 'vermicelli pasta', quantity: '8', unit: 'oz' },
      { name: 'tomato', quantity: '4', unit: 'large, blended' },
      { name: 'onion', quantity: '1/2', unit: 'medium, diced' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
      { name: 'chicken broth', quantity: '6', unit: 'cups' },
      { name: 'vegetable oil', quantity: '2', unit: 'tbsp' },
      { name: 'cumin', quantity: '1/2', unit: 'tsp' },
      { name: 'cilantro', quantity: '1/4', unit: 'cup, for garnish' },
      { name: 'lime', quantity: '2', unit: 'wedges' },
    ],
    steps: [
      'Toast vermicelli in oil until golden brown.',
      'Add onion and garlic, sauté 2 minutes.',
      'Pour in blended tomato and broth. Add cumin. Bring to a boil.',
      'Reduce heat and simmer until pasta is tender, about 10 minutes.',
      'Serve topped with cilantro and lime wedges.',
    ],
    tags: ['sopa de fideo', 'mexican', 'soup', 'noodle', 'comfort food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 220,
      protein_g: 8,
      carbs_g: 32,
      fat_g: 7,
      fiber_g: 3,
      sugar_g: 4,
      sodium_mg: 540,
    },
  },
  {
    title: 'Tacos de Carnitas',
    description:
      'Slow-braised pork shoulder, crisped up and served on corn tortillas with onion and cilantro.',
    cuisine: 'Mexican',
    prep_minutes: 15,
    cook_minutes: 180,
    servings: 8,
    calories: 360,
    ingredients: [
      { name: 'pork shoulder', quantity: '3', unit: 'lbs' },
      { name: 'orange juice', quantity: '1/2', unit: 'cup' },
      { name: 'lard', quantity: '2', unit: 'tbsp' },
      { name: 'garlic', quantity: '4', unit: 'cloves' },
      { name: 'bay leaves', quantity: '2', unit: 'whole' },
      { name: 'corn tortillas', quantity: '24', unit: 'small' },
      { name: 'white onion', quantity: '1', unit: 'diced' },
      { name: 'cilantro', quantity: '1', unit: 'cup, chopped' },
      { name: 'salsa verde', quantity: '1', unit: 'cup' },
    ],
    steps: [
      'Season pork with salt. Place in Dutch oven with lard, garlic, bay leaves, and orange juice.',
      'Cover and braise at 325°F for 3 hours until fork-tender.',
      'Shred pork. Crisp in a hot skillet with some of the braising fat.',
      'Serve on warm corn tortillas with onion, cilantro, and salsa verde.',
    ],
    tags: ['carnitas', 'mexican', 'pork', 'taco', 'slow-cooked'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 360,
      protein_g: 28,
      carbs_g: 22,
      fat_g: 18,
      fiber_g: 4,
      sugar_g: 3,
      sodium_mg: 480,
    },
  },
  {
    title: 'Enchiladas Suizas',
    description:
      'Corn tortillas filled with chicken, bathed in creamy tomatillo-serrano sauce and melted cheese.',
    cuisine: 'Mexican',
    prep_minutes: 25,
    cook_minutes: 20,
    servings: 6,
    calories: 420,
    ingredients: [
      { name: 'corn tortillas', quantity: '12', unit: 'small' },
      { name: 'shredded chicken', quantity: '3', unit: 'cups' },
      { name: 'tomatillos', quantity: '1', unit: 'lb, husked' },
      { name: 'serrano chiles', quantity: '2', unit: 'whole' },
      { name: 'Mexican crema', quantity: '1/2', unit: 'cup' },
      { name: 'queso fresco', quantity: '1', unit: 'cup, crumbled' },
      { name: 'onion', quantity: '1/2', unit: 'medium' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
      { name: 'cilantro', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Boil tomatillos and serranos until soft. Blend with onion, garlic, crema, and cilantro.',
      'Warm tortillas in oil briefly. Fill each with chicken and roll.',
      'Place rolled enchiladas seam-down in a baking dish.',
      'Pour tomatillo sauce over enchiladas. Top with queso fresco.',
      'Bake at 375°F for 15 minutes until bubbly.',
    ],
    tags: ['enchiladas', 'mexican', 'chicken', 'tomatillo', 'suizas'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 26,
      carbs_g: 32,
      fat_g: 20,
      fiber_g: 4,
      sugar_g: 4,
      sodium_mg: 520,
    },
  },
  {
    title: 'Tacos de Barbacoa',
    description:
      'Slow-roasted beef barbacoa seasoned with dried chiles and spices, served in warm corn tortillas.',
    cuisine: 'Mexican',
    prep_minutes: 20,
    cook_minutes: 240,
    servings: 8,
    calories: 380,
    ingredients: [
      { name: 'beef chuck roast', quantity: '3', unit: 'lbs' },
      { name: 'dried guajillo chiles', quantity: '3', unit: 'whole' },
      { name: 'dried ancho chiles', quantity: '2', unit: 'whole' },
      { name: 'cumin', quantity: '1', unit: 'tbsp' },
      { name: 'oregano', quantity: '1', unit: 'tsp' },
      { name: 'garlic', quantity: '4', unit: 'cloves' },
      { name: 'apple cider vinegar', quantity: '2', unit: 'tbsp' },
      { name: 'corn tortillas', quantity: '24', unit: 'small' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'cilantro', quantity: '1', unit: 'cup' },
    ],
    steps: [
      'Toast and blend dried chiles with cumin, oregano, garlic, and vinegar into a paste.',
      'Rub paste over beef. Place in Dutch oven with a little water.',
      'Cover tightly and cook at 300°F for 4 hours until fall-apart tender.',
      'Shred beef. Serve on warm tortillas with onion and cilantro.',
    ],
    tags: ['barbacoa', 'mexican', 'beef', 'taco', 'slow-cooked'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 380,
      protein_g: 32,
      carbs_g: 18,
      fat_g: 20,
      fiber_g: 4,
      sugar_g: 3,
      sodium_mg: 520,
    },
  },
  {
    title: 'Pico de Gallo (Fruit)',
    description:
      'Fresh fruit cup with jicama, mango, watermelon, and cucumber dusted with chile-lime seasoning.',
    cuisine: 'Mexican',
    prep_minutes: 15,
    cook_minutes: 0,
    servings: 6,
    calories: 120,
    ingredients: [
      { name: 'jicama', quantity: '1', unit: 'cup, julienned' },
      { name: 'mango', quantity: '1', unit: 'cup, diced' },
      { name: 'watermelon', quantity: '1', unit: 'cup, cubed' },
      { name: 'cucumber', quantity: '1', unit: 'cup, diced' },
      { name: 'lime juice', quantity: '2', unit: 'tbsp' },
      { name: 'Tajín seasoning', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Cut jicama, mango, watermelon, and cucumber into bite-sized pieces.',
      'Toss together in a large bowl with lime juice.',
      'Sprinkle generously with Tajín or chile-lime seasoning.',
      'Serve immediately as a refreshing snack.',
    ],
    tags: ['pico de gallo', 'mexican', 'fruit', 'snack', 'vegan', 'fresh'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 120,
      protein_g: 2,
      carbs_g: 28,
      fat_g: 1,
      fiber_g: 4,
      sugar_g: 20,
      sodium_mg: 180,
    },
  },
  {
    title: 'Chilaquiles Verdes',
    description:
      'Crispy tortilla chips simmered in tangy tomatillo salsa, topped with crema, cheese, and eggs.',
    cuisine: 'Mexican',
    prep_minutes: 15,
    cook_minutes: 15,
    servings: 4,
    calories: 380,
    ingredients: [
      { name: 'corn tortilla chips', quantity: '6', unit: 'oz' },
      { name: 'tomatillos', quantity: '12', unit: 'oz, husked' },
      { name: 'serrano chile', quantity: '1', unit: 'whole' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
      { name: 'onion', quantity: '1/4', unit: 'cup' },
      { name: 'eggs', quantity: '4', unit: 'large, fried' },
      { name: 'Mexican crema', quantity: '1/4', unit: 'cup' },
      { name: 'queso fresco', quantity: '1/2', unit: 'cup, crumbled' },
      { name: 'cilantro', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Boil tomatillos and serrano until soft. Blend with garlic and onion into salsa verde.',
      'Warm salsa in a large skillet.',
      'Add tortilla chips and toss gently to coat. Cook 3 minutes until slightly softened.',
      'Top with fried eggs, drizzle crema, and sprinkle queso fresco and cilantro.',
    ],
    tags: ['chilaquiles', 'mexican', 'breakfast', 'eggs', 'verdes'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 16,
      carbs_g: 36,
      fat_g: 20,
      fiber_g: 4,
      sugar_g: 3,
      sodium_mg: 480,
    },
  },
  {
    title: 'Tamales de Puerco',
    description: 'Traditional pork-filled tamales with red chile sauce wrapped in corn husks.',
    cuisine: 'Mexican',
    prep_minutes: 60,
    cook_minutes: 90,
    servings: 12,
    calories: 320,
    ingredients: [
      { name: 'masa harina', quantity: '4', unit: 'cups' },
      { name: 'lard', quantity: '1', unit: 'cup, softened' },
      { name: 'chicken broth', quantity: '2', unit: 'cups' },
      { name: 'shredded pork', quantity: '2', unit: 'cups' },
      { name: 'dried ancho chiles', quantity: '4', unit: 'whole' },
      { name: 'garlic', quantity: '3', unit: 'cloves' },
      { name: 'cumin', quantity: '1', unit: 'tsp' },
      { name: 'corn husks', quantity: '24', unit: 'dried, soaked' },
      { name: 'baking powder', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Toast and blend ancho chiles with garlic and cumin into red chile sauce. Mix with shredded pork.',
      'Beat lard until fluffy. Mix in masa harina, broth, and baking powder until smooth.',
      'Spread masa on soaked corn husks. Add pork filling. Fold and tie.',
      'Steam tamales upright for 90 minutes until masa pulls away from husk.',
    ],
    tags: ['tamales', 'mexican', 'pork', 'traditional', 'holiday'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 16,
      carbs_g: 28,
      fat_g: 16,
      fiber_g: 4,
      sugar_g: 2,
      sodium_mg: 440,
    },
  },
  {
    title: 'Agua de Horchata',
    description:
      'Creamy Mexican rice drink flavored with cinnamon, vanilla, and a touch of sweetened condensed milk.',
    cuisine: 'Mexican',
    prep_minutes: 10,
    cook_minutes: 0,
    servings: 8,
    calories: 160,
    ingredients: [
      { name: 'long-grain white rice', quantity: '1', unit: 'cup, uncooked' },
      { name: 'water', quantity: '6', unit: 'cups' },
      { name: 'cinnamon sticks', quantity: '2', unit: 'whole' },
      { name: 'sweetened condensed milk', quantity: '1', unit: 'can (14 oz)' },
      { name: 'vanilla extract', quantity: '1', unit: 'tsp' },
      { name: 'sugar', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Soak rice in water with cinnamon sticks for at least 4 hours or overnight.',
      'Blend rice mixture until smooth. Strain through a fine sieve.',
      'Stir in condensed milk, vanilla, and sugar. Add more water to taste.',
      'Serve over ice.',
    ],
    tags: ['horchata', 'mexican', 'drink', 'beverage', 'rice', 'cinnamon'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 160,
      protein_g: 3,
      carbs_g: 30,
      fat_g: 3,
      fiber_g: 0,
      sugar_g: 22,
      sodium_mg: 60,
    },
  },
  {
    title: 'Tostadas de Tinga',
    description:
      'Crispy fried corn tostadas topped with shredded chicken in smoky chipotle-tomato sauce.',
    cuisine: 'Mexican',
    prep_minutes: 15,
    cook_minutes: 25,
    servings: 6,
    calories: 340,
    ingredients: [
      { name: 'corn tostadas', quantity: '12', unit: 'whole' },
      { name: 'shredded chicken', quantity: '3', unit: 'cups' },
      { name: 'chipotle in adobo', quantity: '2', unit: 'canned peppers' },
      { name: 'tomato', quantity: '3', unit: 'medium, diced' },
      { name: 'onion', quantity: '1/2', unit: 'medium, sliced' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
      { name: 'Mexican crema', quantity: '1/4', unit: 'cup' },
      { name: 'avocado', quantity: '2', unit: 'sliced' },
      { name: 'lettuce', quantity: '1', unit: 'cup, shredded' },
    ],
    steps: [
      'Sauté onion and garlic until soft. Add tomatoes and chipotle. Cook 10 minutes.',
      'Add shredded chicken and simmer 10 minutes until flavors meld.',
      'Spread crema on each tostada. Top with tinga, avocado, and lettuce.',
      'Serve with lime wedges.',
    ],
    tags: ['tostada', 'mexican', 'chicken', 'chipotle', 'tinga'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 340,
      protein_g: 22,
      carbs_g: 26,
      fat_g: 16,
      fiber_g: 5,
      sugar_g: 3,
      sodium_mg: 460,
    },
  },
  {
    title: 'Mole Negro Oaxaqueño',
    description:
      'Deep, complex Oaxacan black mole with over 30 ingredients including chilhuacle chiles and chocolate.',
    cuisine: 'Mexican',
    prep_minutes: 60,
    cook_minutes: 120,
    servings: 10,
    calories: 460,
    ingredients: [
      { name: 'chicken pieces', quantity: '4', unit: 'lbs' },
      { name: 'chilhuacle negro chiles', quantity: '6', unit: 'whole' },
      { name: 'mulato chiles', quantity: '4', unit: 'whole' },
      { name: 'Mexican chocolate', quantity: '2', unit: 'oz' },
      { name: 'sesame seeds', quantity: '3', unit: 'tbsp' },
      { name: 'peanuts', quantity: '2', unit: 'tbsp' },
      { name: 'plantain', quantity: '1', unit: 'ripe, sliced' },
      { name: 'tomato', quantity: '2', unit: 'medium' },
      { name: 'onion', quantity: '1', unit: 'medium' },
      { name: 'garlic', quantity: '5', unit: 'cloves' },
      { name: 'lard', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Toast all dried chiles. Soak in hot water 30 minutes.',
      'Toast sesame seeds and peanuts separately. Fry plantain slices.',
      'Blend chiles, seeds, nuts, plantain, tomato, onion, garlic, chocolate, and spices with broth.',
      'Fry mole paste in lard for 10 minutes. Add broth and simmer.',
      'Add seared chicken. Simmer 1 hour until tender and flavors meld.',
      'Serve with rice and garnish with sesame seeds.',
    ],
    tags: ['mole negro', 'mexican', 'oaxacan', 'chicken', 'chocolate', 'traditional'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 460,
      protein_g: 30,
      carbs_g: 28,
      fat_g: 24,
      fiber_g: 6,
      sugar_g: 8,
      sodium_mg: 580,
    },
  },
  {
    title: 'Enfrijoladas',
    description:
      'Corn tortillas dipped in creamy black bean sauce, filled with cheese, and topped with crema.',
    cuisine: 'Mexican',
    prep_minutes: 15,
    cook_minutes: 15,
    servings: 4,
    calories: 320,
    ingredients: [
      { name: 'corn tortillas', quantity: '12', unit: 'small' },
      { name: 'black beans', quantity: '2', unit: 'cups, cooked' },
      { name: 'onion', quantity: '1/4', unit: 'cup' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
      { name: 'epazote', quantity: '2', unit: 'sprigs' },
      { name: 'queso fresco', quantity: '1', unit: 'cup, crumbled' },
      { name: 'Mexican crema', quantity: '1/4', unit: 'cup' },
      { name: 'salsa verde', quantity: '1/2', unit: 'cup' },
    ],
    steps: [
      'Blend black beans with onion, garlic, and epazote into a smooth sauce.',
      'Warm the bean sauce in a skillet.',
      'Dip each tortilla in the warm bean sauce, fill with queso fresco, and roll.',
      'Place in a dish, top with more bean sauce, crema, and salsa verde.',
    ],
    tags: ['enfrijoladas', 'mexican', 'beans', 'vegetarian', 'cheese'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 14,
      carbs_g: 38,
      fat_g: 12,
      fiber_g: 8,
      sugar_g: 2,
      sodium_mg: 420,
    },
  },
  {
    title: 'Ceviche Mexicano',
    description:
      'Fresh white fish marinated in lime juice with tomato, avocado, jalapeño, and cilantro.',
    cuisine: 'Mexican',
    prep_minutes: 25,
    cook_minutes: 0,
    servings: 6,
    calories: 180,
    ingredients: [
      { name: 'white fish fillet', quantity: '1', unit: 'lb, diced' },
      { name: 'lime juice', quantity: '1', unit: 'cup, fresh' },
      { name: 'tomato', quantity: '2', unit: 'medium, diced' },
      { name: 'avocado', quantity: '1', unit: 'diced' },
      { name: 'jalapeño', quantity: '1', unit: 'minced' },
      { name: 'onion', quantity: '1/2', unit: 'small, diced' },
      { name: 'cilantro', quantity: '1/2', unit: 'cup, chopped' },
      { name: 'tostadas', quantity: '12', unit: 'for serving' },
    ],
    steps: [
      'Dice fish and cover with lime juice. Refrigerate 3-4 hours until opaque.',
      'Drain excess lime juice.',
      'Mix fish with tomato, onion, jalapeño, and cilantro.',
      'Gently fold in avocado. Season with salt.',
      'Serve on tostadas with hot sauce.',
    ],
    tags: ['ceviche', 'mexican', 'fish', 'seafood', 'fresh', 'no-cook'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 180,
      protein_g: 22,
      carbs_g: 10,
      fat_g: 7,
      fiber_g: 3,
      sugar_g: 2,
      sodium_mg: 280,
    },
  },
  {
    title: 'Caldo de Res',
    description:
      'Hearty Mexican beef soup with vegetables, corn, and chickpeas in a rich beef broth.',
    cuisine: 'Mexican',
    prep_minutes: 20,
    cook_minutes: 90,
    servings: 8,
    calories: 380,
    ingredients: [
      { name: 'beef shank', quantity: '2', unit: 'lbs, bone-in' },
      { name: 'corn on the cob', quantity: '4', unit: 'pieces, cut into 3-inch rounds' },
      { name: 'carrots', quantity: '3', unit: 'large, chunked' },
      { name: 'potatoes', quantity: '3', unit: 'medium, quartered' },
      { name: 'chayote', quantity: '2', unit: 'quartered' },
      { name: 'zucchini', quantity: '2', unit: 'chunked' },
      { name: 'chickpeas', quantity: '1', unit: 'cup, cooked' },
      { name: 'onion', quantity: '1', unit: 'whole' },
      { name: 'garlic', quantity: '4', unit: 'cloves' },
      { name: 'cilantro', quantity: '1/2', unit: 'cup' },
    ],
    steps: [
      'Cover beef shank with water. Add onion and garlic. Bring to boil, skim foam.',
      'Simmer 1 hour until beef is tender.',
      'Add carrots, potatoes, and chayote. Cook 15 minutes.',
      'Add corn, zucchini, and chickpeas. Cook 10 more minutes.',
      'Season with salt. Serve in deep bowls with cilantro and lime.',
    ],
    tags: ['caldo de res', 'mexican', 'beef', 'soup', 'hearty', 'vegetables'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 28,
      carbs_g: 34,
      fat_g: 14,
      fiber_g: 6,
      sugar_g: 4,
      sodium_mg: 460,
    },
  },
  {
    title: 'Tacos de Pescado (Baja Style)',
    description:
      'Beer-battered white fish in corn tortillas with cabbage slaw, chipotle crema, and lime.',
    cuisine: 'Mexican',
    prep_minutes: 20,
    cook_minutes: 15,
    servings: 4,
    calories: 420,
    ingredients: [
      { name: 'white fish fillets', quantity: '1', unit: 'lb, cut into strips' },
      { name: 'beer', quantity: '1/2', unit: 'cup' },
      { name: 'all-purpose flour', quantity: '1', unit: 'cup' },
      { name: 'corn tortillas', quantity: '12', unit: 'small' },
      { name: 'cabbage', quantity: '2', unit: 'cups, shredded' },
      { name: 'chipotle in adobo', quantity: '1', unit: 'pepper, minced' },
      { name: 'Mexican crema', quantity: '1/4', unit: 'cup' },
      { name: 'lime', quantity: '4', unit: 'wedges' },
      { name: 'vegetable oil', quantity: '2', unit: 'cups, for frying' },
    ],
    steps: [
      'Mix flour, beer, and salt into a batter. Dip fish strips.',
      'Deep fry at 375°F until golden and crispy, about 4 minutes.',
      'Mix crema with minced chipotle for the sauce.',
      'Toss cabbage with lime juice and salt.',
      'Serve fish on warm tortillas with slaw, chipotle crema, and lime.',
    ],
    tags: ['fish taco', 'mexican', 'baja', 'seafood', 'fried'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 22,
      carbs_g: 36,
      fat_g: 22,
      fiber_g: 3,
      sugar_g: 3,
      sodium_mg: 540,
    },
  },
  {
    title: 'Pozole Blanco',
    description:
      'White pozole with hominy and pork in a clear broth, garnished with radishes, lettuce, and oregano.',
    cuisine: 'Mexican',
    prep_minutes: 20,
    cook_minutes: 120,
    servings: 8,
    calories: 380,
    ingredients: [
      { name: 'pork shoulder', quantity: '2', unit: 'lbs, cubed' },
      { name: 'hominy', quantity: '2', unit: 'cans (30 oz each), drained' },
      { name: 'onion', quantity: '1', unit: 'whole' },
      { name: 'garlic', quantity: '6', unit: 'cloves' },
      { name: 'bay leaves', quantity: '3', unit: 'whole' },
      { name: 'radishes', quantity: '6', unit: 'sliced' },
      { name: 'lettuce', quantity: '2', unit: 'cups, shredded' },
      { name: 'dried oregano', quantity: '1', unit: 'tsp' },
      { name: 'lime', quantity: '4', unit: 'wedges' },
    ],
    steps: [
      'Cover pork with water. Add onion, garlic, and bay leaves. Simmer 2 hours.',
      'Remove pork, shred. Strain broth.',
      'Return broth to pot. Add hominy and shredded pork. Simmer 30 minutes.',
      'Serve in bowls with radishes, lettuce, oregano, and lime.',
    ],
    tags: ['pozole', 'mexican', 'pork', 'hominy', 'soup', 'traditional'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 26,
      carbs_g: 36,
      fat_g: 14,
      fiber_g: 6,
      sugar_g: 3,
      sodium_mg: 520,
    },
  },
  {
    title: 'Chiles en Nogada',
    description:
      'Poblano chiles stuffed with picadillo, bathed in walnut-cream sauce, and garnished with pomegranate seeds.',
    cuisine: 'Mexican',
    prep_minutes: 45,
    cook_minutes: 30,
    servings: 6,
    calories: 480,
    ingredients: [
      { name: 'poblano chiles', quantity: '6', unit: 'large, roasted and peeled' },
      { name: 'ground beef', quantity: '1/2', unit: 'lb' },
      { name: 'onion', quantity: '1', unit: 'medium, diced' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
      { name: 'apple', quantity: '1', unit: 'diced' },
      { name: 'plantain', quantity: '1', unit: 'ripe, diced' },
      { name: 'walnuts', quantity: '1', unit: 'cup, soaked and peeled' },
      { name: 'cream cheese', quantity: '4', unit: 'oz, softened' },
      { name: 'milk', quantity: '1/4', unit: 'cup' },
      { name: 'pomegranate seeds', quantity: '1/2', unit: 'cup' },
      { name: 'parsley', quantity: '2', unit: 'tbsp, chopped' },
    ],
    steps: [
      'Make picadillo: sauté beef with onion, garlic, apple, plantain, and spices.',
      'Stuff each roasted poblano with picadillo.',
      'Blend walnuts with cream cheese and milk into a smooth nogada sauce.',
      'Place stuffed chiles on a plate. Cover with walnut sauce.',
      'Garnish with pomegranate seeds and parsley.',
    ],
    tags: ['chiles en nogada', 'mexican', 'poblano', 'walnut', 'puebla', 'traditional'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 480,
      protein_g: 22,
      carbs_g: 30,
      fat_g: 30,
      fiber_g: 5,
      sugar_g: 12,
      sodium_mg: 420,
    },
  },
  {
    title: 'Sopa de Tortilla',
    description:
      'Classic Mexican tortilla soup with tomato-chile broth, crispy tortilla strips, and avocado.',
    cuisine: 'Mexican',
    prep_minutes: 15,
    cook_minutes: 25,
    servings: 6,
    calories: 260,
    ingredients: [
      { name: 'corn tortillas', quantity: '6', unit: 'cut into strips' },
      { name: 'vegetable oil', quantity: '1/4', unit: 'cup, for frying' },
      { name: 'tomato', quantity: '4', unit: 'large, blended' },
      { name: 'onion', quantity: '1/2', unit: 'medium, diced' },
      { name: 'garlic', quantity: '3', unit: 'cloves' },
      { name: 'epazote', quantity: '2', unit: 'sprigs' },
      { name: 'chicken broth', quantity: '6', unit: 'cups' },
      { name: 'pasilla chile', quantity: '1', unit: 'whole, for garnish' },
      { name: 'avocado', quantity: '1', unit: 'diced' },
      { name: 'queso fresco', quantity: '1/2', unit: 'cup, crumbled' },
    ],
    steps: [
      'Fry tortilla strips until crispy. Set aside.',
      'Sauté onion and garlic. Add blended tomato and cook 5 minutes.',
      'Add broth and epazote. Simmer 15 minutes.',
      'Ladlele into bowls. Top with crispy tortilla strips, avocado, queso fresco, and fried pasilla strips.',
    ],
    tags: ['tortilla soup', 'mexican', 'soup', 'tomato', 'tortilla', 'classic'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 260,
      protein_g: 10,
      carbs_g: 28,
      fat_g: 12,
      fiber_g: 5,
      sugar_g: 4,
      sodium_mg: 580,
    },
  },
  {
    title: 'Tamales Dulces',
    description:
      'Sweet tamales with masa flavored with cinnamon, raisins, and piloncillo, wrapped in corn husks.',
    cuisine: 'Mexican',
    prep_minutes: 45,
    cook_minutes: 90,
    servings: 12,
    calories: 240,
    ingredients: [
      { name: 'masa harina', quantity: '4', unit: 'cups' },
      { name: 'lard', quantity: '1', unit: 'cup, softened' },
      { name: 'piloncillo', quantity: '1', unit: 'cone (6 oz), grated' },
      { name: 'cinnamon', quantity: '1', unit: 'tsp, ground' },
      { name: 'raisins', quantity: '1/2', unit: 'cup' },
      { name: 'water', quantity: '2', unit: 'cups' },
      { name: 'baking powder', quantity: '1', unit: 'tsp' },
      { name: 'corn husks', quantity: '24', unit: 'dried, soaked' },
      { name: 'vanilla extract', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Beat lard until fluffy. Mix in masa, water, baking powder, cinnamon, and vanilla.',
      'Dissolve piloncillo in warm water and mix into masa.',
      'Spread sweet masa on corn husks. Add raisins. Fold and tie.',
      'Steam for 90 minutes until masa is firm and pulls away from husk.',
    ],
    tags: ['tamales', 'mexican', 'sweet', 'dessert', 'cinnamon', 'piloncillo'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 240,
      protein_g: 3,
      carbs_g: 32,
      fat_g: 11,
      fiber_g: 3,
      sugar_g: 14,
      sodium_mg: 140,
    },
  },
  {
    title: 'Fajitas de Pollo',
    description:
      'Sizzling chicken fajitas with bell peppers and onions, served with warm tortillas and toppings.',
    cuisine: 'Mexican',
    prep_minutes: 15,
    cook_minutes: 15,
    servings: 4,
    calories: 420,
    ingredients: [
      { name: 'chicken breast', quantity: '1.5', unit: 'lbs, sliced' },
      { name: 'bell peppers', quantity: '3', unit: 'assorted colors, sliced' },
      { name: 'onion', quantity: '1', unit: 'large, sliced' },
      { name: 'flour tortillas', quantity: '8', unit: 'medium' },
      { name: 'lime juice', quantity: '2', unit: 'tbsp' },
      { name: 'cumin', quantity: '1', unit: 'tsp' },
      { name: 'chili powder', quantity: '1', unit: 'tsp' },
      { name: 'garlic', quantity: '2', unit: 'cloves, minced' },
      { name: 'vegetable oil', quantity: '2', unit: 'tbsp' },
      { name: 'sour cream', quantity: '1/2', unit: 'cup' },
      { name: 'guacamole', quantity: '1', unit: 'cup' },
    ],
    steps: [
      'Season chicken with cumin, chili powder, garlic, lime juice, and oil. Marinate 15 minutes.',
      'Grill or sauté chicken until cooked through, about 6 minutes per side.',
      'Sauté peppers and onions in the same pan until charred and tender.',
      'Slice chicken. Serve on warm tortillas with peppers, onions, sour cream, and guacamole.',
    ],
    tags: ['fajitas', 'mexican', 'chicken', 'bell peppers', 'tex-mex'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 32,
      carbs_g: 34,
      fat_g: 16,
      fiber_g: 4,
      sugar_g: 5,
      sodium_mg: 520,
    },
  },
  {
    title: 'Machaca con Huevo',
    description:
      'Dried shredded beef scrambled with eggs, onions, and jalapeños. A classic northern Mexican breakfast.',
    cuisine: 'Mexican',
    prep_minutes: 10,
    cook_minutes: 15,
    servings: 4,
    calories: 340,
    ingredients: [
      { name: 'dried beef (machaca)', quantity: '8', unit: 'oz' },
      { name: 'eggs', quantity: '6', unit: 'large, beaten' },
      { name: 'onion', quantity: '1/2', unit: 'medium, diced' },
      { name: 'jalapeño', quantity: '1', unit: 'minced' },
      { name: 'tomato', quantity: '1', unit: 'medium, diced' },
      { name: 'vegetable oil', quantity: '1', unit: 'tbsp' },
      { name: 'flour tortillas', quantity: '4', unit: 'for serving' },
    ],
    steps: [
      'Soak machaca in warm water 10 minutes. Drain.',
      'Sauté onion and jalapeño in oil. Add machaca and cook 3 minutes.',
      'Add tomato and cook 2 minutes.',
      'Pour beaten eggs over mixture. Scramble until set.',
      'Serve with warm flour tortillas and salsa.',
    ],
    tags: ['machaca', 'mexican', 'breakfast', 'eggs', 'beef', 'northern'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 340,
      protein_g: 28,
      carbs_g: 10,
      fat_g: 20,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 780,
    },
  },
  {
    title: 'Sopes with Refried Beans',
    description:
      'Thick corn masa cups fried and topped with refried beans, lettuce, crema, and queso fresco.',
    cuisine: 'Mexican',
    prep_minutes: 20,
    cook_minutes: 15,
    servings: 6,
    calories: 280,
    ingredients: [
      { name: 'masa harina', quantity: '2', unit: 'cups' },
      { name: 'water', quantity: '1', unit: 'cup' },
      { name: 'refried beans', quantity: '1', unit: 'can (16 oz)' },
      { name: 'lettuce', quantity: '1', unit: 'cup, shredded' },
      { name: 'Mexican crema', quantity: '1/4', unit: 'cup' },
      { name: 'queso fresco', quantity: '1/2', unit: 'cup, crumbled' },
      { name: 'salsa verde', quantity: '1/2', unit: 'cup' },
      { name: 'vegetable oil', quantity: '1/4', unit: 'cup, for frying' },
    ],
    steps: [
      'Mix masa harina with water. Form into thick discs and pinch edges to form a rim.',
      'Grill on a comal until lightly browned on both sides.',
      'Fry in hot oil until crispy. Drain.',
      'Spread refried beans in the center. Top with lettuce, crema, queso fresco, and salsa.',
    ],
    tags: ['sopes', 'mexican', 'masa', 'beans', 'vegetarian', 'street food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 10,
      carbs_g: 34,
      fat_g: 12,
      fiber_g: 6,
      sugar_g: 2,
      sodium_mg: 440,
    },
  },
  {
    title: 'Tacos de Cochinita Pibil',
    description:
      'Achiote-marinated pork wrapped in banana leaves, slow-cooked until tender, served with pickled red onion.',
    cuisine: 'Mexican',
    prep_minutes: 30,
    cook_minutes: 300,
    servings: 10,
    calories: 340,
    ingredients: [
      { name: 'pork shoulder', quantity: '4', unit: 'lbs' },
      { name: 'achiote paste', quantity: '4', unit: 'oz' },
      { name: 'bitter orange juice', quantity: '1/2', unit: 'cup' },
      { name: 'garlic', quantity: '6', unit: 'cloves' },
      { name: 'banana leaves', quantity: '4', unit: 'large, for wrapping' },
      { name: 'corn tortillas', quantity: '30', unit: 'small' },
      { name: 'red onion', quantity: '1', unit: 'large, sliced' },
      { name: 'habanero chile', quantity: '1', unit: 'for garnish' },
    ],
    steps: [
      'Blend achiote with bitter orange juice and garlic. Marinate pork overnight.',
      'Wrap marinated pork in banana leaves. Place in Dutch oven.',
      'Cook at 300°F for 5 hours until fall-apart tender.',
      'Pickle red onion in lime juice with salt and habanero.',
      'Shred pork. Serve on warm tortillas with pickled onion.',
    ],
    tags: ['cochinita pibil', 'mexican', 'pork', 'yucatan', 'taco', 'achiote'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 340,
      protein_g: 28,
      carbs_g: 16,
      fat_g: 18,
      fiber_g: 3,
      sugar_g: 3,
      sodium_mg: 460,
    },
  },
  {
    title: 'Enchiladas Rojas',
    description:
      'Corn tortillas filled with cheese and onion, drenched in red chile sauce, topped with crema.',
    cuisine: 'Mexican',
    prep_minutes: 20,
    cook_minutes: 20,
    servings: 6,
    calories: 380,
    ingredients: [
      { name: 'corn tortillas', quantity: '12', unit: 'small' },
      { name: 'dried guajillo chiles', quantity: '6', unit: 'whole' },
      { name: 'dried ancho chiles', quantity: '2', unit: 'whole' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
      { name: 'onion', quantity: '1/2', unit: 'for sauce + 1 for filling' },
      { name: 'Oaxacan cheese', quantity: '8', unit: 'oz, shredded' },
      { name: 'Mexican crema', quantity: '1/4', unit: 'cup' },
      { name: 'queso fresco', quantity: '1/2', unit: 'cup, crumbled' },
    ],
    steps: [
      'Toast and soak dried chiles. Blend with garlic and onion into a smooth red sauce.',
      'Warm tortillas briefly in oil. Fill with cheese and diced onion. Roll tightly.',
      'Place seam-down in a dish. Pour red sauce over.',
      'Top with crema and queso fresco. Serve immediately.',
    ],
    tags: ['enchiladas', 'mexican', 'red chile', 'cheese', 'vegetarian'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 16,
      carbs_g: 34,
      fat_g: 20,
      fiber_g: 5,
      sugar_g: 3,
      sodium_mg: 520,
    },
  },
  {
    title: 'Queso Fundido with Chorizo',
    description:
      'Bubbling melted cheese with Mexican chorizo, served with warm flour tortillas for dipping.',
    cuisine: 'Mexican',
    prep_minutes: 10,
    cook_minutes: 10,
    servings: 4,
    calories: 380,
    ingredients: [
      { name: 'Mexican chorizo', quantity: '8', unit: 'oz, casing removed' },
      { name: 'Oaxacan cheese', quantity: '8', unit: 'oz, shredded' },
      { name: 'poblano chile', quantity: '1', unit: 'roasted, diced' },
      { name: 'onion', quantity: '1/4', unit: 'cup, diced' },
      { name: 'flour tortillas', quantity: '8', unit: 'warm' },
      { name: 'cilantro', quantity: '2', unit: 'tbsp, chopped' },
    ],
    steps: [
      'Cook chorizo in a skillet until browned. Drain excess fat.',
      'Add onion and poblano. Cook 2 minutes.',
      'Top with shredded cheese. Cover and cook until melted.',
      'Serve in the skillet with warm tortillas and cilantro.',
    ],
    tags: ['queso fundido', 'mexican', 'cheese', 'chorizo', 'appetizer'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 20,
      carbs_g: 14,
      fat_g: 28,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 680,
    },
  },
  {
    title: 'Aguachile',
    description:
      'Raw shrimp cured in spicy lime-chile sauce with cucumber, red onion, and avocado.',
    cuisine: 'Mexican',
    prep_minutes: 20,
    cook_minutes: 0,
    servings: 4,
    calories: 180,
    ingredients: [
      { name: 'raw shrimp', quantity: '1', unit: 'lb, peeled and butterflied' },
      { name: 'lime juice', quantity: '1', unit: 'cup' },
      { name: 'serrano chiles', quantity: '4', unit: 'whole' },
      { name: 'cucumber', quantity: '1', unit: 'large, sliced' },
      { name: 'red onion', quantity: '1/2', unit: 'thinly sliced' },
      { name: 'avocado', quantity: '1', unit: 'sliced' },
      { name: 'cilantro', quantity: '1/4', unit: 'cup' },
      { name: 'tostadas', quantity: '8', unit: 'for serving' },
    ],
    steps: [
      'Blend serrano chiles with lime juice and a little water.',
      'Pour over raw shrimp. Refrigerate 15 minutes until shrimp turn pink.',
      'Arrange cucumber and red onion on a platter.',
      'Top with cured shrimp and sauce. Garnish with avocado and cilantro.',
      'Serve with tostadas.',
    ],
    tags: ['aguachile', 'mexican', 'shrimp', 'seafood', 'raw', 'spicy', 'sinaloa'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 180,
      protein_g: 20,
      carbs_g: 10,
      fat_g: 7,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 320,
    },
  },
  {
    title: 'Tacos de Lengua',
    description:
      'Braised beef tongue, diced and served on corn tortillas with onion, cilantro, and salsa verde.',
    cuisine: 'Mexican',
    prep_minutes: 15,
    cook_minutes: 180,
    servings: 8,
    calories: 320,
    ingredients: [
      { name: 'beef tongue', quantity: '3', unit: 'lbs' },
      { name: 'onion', quantity: '1', unit: 'whole' },
      { name: 'garlic', quantity: '4', unit: 'cloves' },
      { name: 'bay leaves', quantity: '3', unit: 'whole' },
      { name: 'corn tortillas', quantity: '24', unit: 'small' },
      { name: 'white onion', quantity: '1', unit: 'diced, for garnish' },
      { name: 'cilantro', quantity: '1', unit: 'cup, chopped' },
      { name: 'salsa verde', quantity: '1', unit: 'cup' },
    ],
    steps: [
      'Cover tongue with water. Add onion, garlic, and bay leaves. Simmer 3 hours.',
      'Peel outer skin while hot. Dice the tender meat.',
      'Crisp diced tongue in a hot skillet.',
      'Serve on warm tortillas with onion, cilantro, and salsa verde.',
    ],
    tags: ['lengua', 'mexican', 'beef tongue', 'taco', 'traditional'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 320,
      protein_g: 26,
      carbs_g: 18,
      fat_g: 16,
      fiber_g: 4,
      sugar_g: 2,
      sodium_mg: 440,
    },
  },
  {
    title: 'Huaraches de Nopales',
    description:
      'Oval-shaped masa boats topped with cactus paddles, beans, queso fresco, and salsa.',
    cuisine: 'Mexican',
    prep_minutes: 20,
    cook_minutes: 15,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'masa harina', quantity: '2', unit: 'cups' },
      { name: 'water', quantity: '1', unit: 'cup' },
      { name: 'nopales (cactus paddles)', quantity: '4', unit: 'small, diced and boiled' },
      { name: 'refried beans', quantity: '1/2', unit: 'cup' },
      { name: 'queso fresco', quantity: '1/2', unit: 'cup, crumbled' },
      { name: 'salsa verde', quantity: '1/2', unit: 'cup' },
      { name: 'onion', quantity: '1/4', unit: 'cup, diced' },
      { name: 'cilantro', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Mix masa with water. Shape into oval discs. Cook on a comal until set.',
      'Boil nopales until tender. Drain and rinse.',
      'Top huaraches with beans, nopales, onion, and queso fresco.',
      'Drizzle salsa verde and garnish with cilantro.',
    ],
    tags: ['huarache', 'mexican', 'nopales', 'cactus', 'vegetarian', 'masa'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 12,
      carbs_g: 38,
      fat_g: 9,
      fiber_g: 7,
      sugar_g: 2,
      sodium_mg: 380,
    },
  },
  {
    title: 'Pan de Muerto',
    description:
      'Traditional Mexican sweet bread for Day of the Dead, flavored with orange zest and anise.',
    cuisine: 'Mexican',
    prep_minutes: 30,
    cook_minutes: 25,
    servings: 8,
    calories: 260,
    ingredients: [
      { name: 'all-purpose flour', quantity: '4', unit: 'cups' },
      { name: 'sugar', quantity: '1/2', unit: 'cup' },
      { name: 'butter', quantity: '1/2', unit: 'cup, softened' },
      { name: 'eggs', quantity: '3', unit: 'large' },
      { name: 'orange zest', quantity: '1', unit: 'tbsp' },
      { name: 'anise seeds', quantity: '1', unit: 'tsp' },
      { name: 'yeast', quantity: '1', unit: 'packet (2 1/4 tsp)' },
      { name: 'milk', quantity: '1/2', unit: 'cup, warm' },
    ],
    steps: [
      'Dissolve yeast in warm milk. Let bloom 5 minutes.',
      'Mix flour, sugar, butter, eggs, orange zest, and anise. Add yeast mixture. Knead until smooth.',
      'Let rise 1 hour until doubled. Shape into a round with bone-shaped dough strips on top.',
      'Bake at 350°F for 25 minutes until golden. Brush with butter and sprinkle with sugar.',
    ],
    tags: ['pan de muerto', 'mexican', 'bread', 'day of the dead', 'dessert', 'anise'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 260,
      protein_g: 6,
      carbs_g: 40,
      fat_g: 8,
      fiber_g: 2,
      sugar_g: 14,
      sodium_mg: 180,
    },
  },
  {
    title: 'Tlacoyos',
    description:
      'Oval masa pockets stuffed with beans, grilled on a comal, topped with salsa, nopales, and cheese.',
    cuisine: 'Mexican',
    prep_minutes: 25,
    cook_minutes: 10,
    servings: 6,
    calories: 260,
    ingredients: [
      { name: 'masa harina', quantity: '2', unit: 'cups' },
      { name: 'water', quantity: '1', unit: 'cup' },
      { name: 'refried beans', quantity: '1/2', unit: 'cup' },
      { name: 'nopales', quantity: '4', unit: 'paddles, diced and boiled' },
      { name: 'queso fresco', quantity: '1/2', unit: 'cup, crumbled' },
      { name: 'salsa verde', quantity: '1/2', unit: 'cup' },
      { name: 'cilantro', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Mix masa with water. Form into ovals. Fill center with beans. Seal and flatten.',
      'Grill on a hot comal until charred spots appear on both sides.',
      'Top with nopales, queso fresco, salsa verde, and cilantro.',
      'Serve immediately.',
    ],
    tags: ['tlacoyo', 'mexican', 'masa', 'beans', 'street food', 'vegetarian'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 260,
      protein_g: 10,
      carbs_g: 38,
      fat_g: 8,
      fiber_g: 6,
      sugar_g: 2,
      sodium_mg: 360,
    },
  },
  {
    title: 'Camarones a la Diabla',
    description: 'Spicy deviled shrimp sautéed in a fiery chile de árbol and guajillo sauce.',
    cuisine: 'Mexican',
    prep_minutes: 15,
    cook_minutes: 10,
    servings: 4,
    calories: 240,
    ingredients: [
      { name: 'large shrimp', quantity: '1', unit: 'lb, peeled and deveined' },
      { name: 'dried chile de árbol', quantity: '6', unit: 'whole' },
      { name: 'dried guajillo chiles', quantity: '2', unit: 'whole' },
      { name: 'garlic', quantity: '3', unit: 'cloves' },
      { name: 'tomato', quantity: '1', unit: 'medium' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
      { name: 'lime', quantity: '2', unit: 'wedges' },
      { name: 'white rice', quantity: '2', unit: 'cups, cooked, for serving' },
    ],
    steps: [
      'Toast and soak chiles. Blend with garlic and tomato into a smooth sauce.',
      'Melt butter in a skillet. Sauté shrimp 2 minutes per side.',
      'Pour chile sauce over shrimp. Simmer 5 minutes.',
      'Serve over white rice with lime wedges.',
    ],
    tags: ['camarones a la diabla', 'mexican', 'shrimp', 'spicy', 'seafood'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 240,
      protein_g: 24,
      carbs_g: 12,
      fat_g: 10,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 480,
    },
  },
  {
    title: 'Nopales Salad (Ensalada de Nopales)',
    description:
      'Refreshing salad of boiled cactus paddles with tomato, onion, cilantro, and a lime vinaigrette.',
    cuisine: 'Mexican',
    prep_minutes: 15,
    cook_minutes: 10,
    servings: 4,
    calories: 100,
    ingredients: [
      { name: 'nopales (cactus paddles)', quantity: '6', unit: 'small, diced' },
      { name: 'tomato', quantity: '2', unit: 'medium, diced' },
      { name: 'white onion', quantity: '1/2', unit: 'diced' },
      { name: 'cilantro', quantity: '1/4', unit: 'cup, chopped' },
      { name: 'lime juice', quantity: '3', unit: 'tbsp' },
      { name: 'olive oil', quantity: '1', unit: 'tbsp' },
      { name: 'serrano chile', quantity: '1', unit: 'minced' },
      { name: 'oregano', quantity: '1/2', unit: 'tsp' },
    ],
    steps: [
      'Boil nopales in salted water with a pinch of baking soda until tender, about 10 minutes. Drain and rinse.',
      'Combine nopales with tomato, onion, cilantro, and serrano.',
      'Whisk lime juice, olive oil, and oregano for the dressing.',
      'Toss salad with dressing. Season with salt. Serve chilled.',
    ],
    tags: ['nopales', 'mexican', 'salad', 'cactus', 'vegan', 'light'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 100,
      protein_g: 3,
      carbs_g: 12,
      fat_g: 4,
      fiber_g: 5,
      sugar_g: 3,
      sodium_mg: 140,
    },
  },
  {
    title: 'Mole Coloradito',
    description:
      'Oaxacan red-brown mole with ancho and guajillo chiles, plantain, and a touch of chocolate.',
    cuisine: 'Mexican',
    prep_minutes: 40,
    cook_minutes: 60,
    servings: 8,
    calories: 440,
    ingredients: [
      { name: 'chicken pieces', quantity: '3', unit: 'lbs' },
      { name: 'dried ancho chiles', quantity: '5', unit: 'whole' },
      { name: 'dried guajillo chiles', quantity: '3', unit: 'whole' },
      { name: 'plantain', quantity: '1', unit: 'ripe, sliced' },
      { name: 'sesame seeds', quantity: '2', unit: 'tbsp' },
      { name: 'peanuts', quantity: '2', unit: 'tbsp' },
      { name: 'Mexican chocolate', quantity: '1', unit: 'oz' },
      { name: 'onion', quantity: '1', unit: 'medium' },
      { name: 'garlic', quantity: '3', unit: 'cloves' },
      { name: 'lard', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Toast and soak dried chiles. Fry plantain, sesame, and peanuts separately.',
      'Blend chiles with plantain, seeds, nuts, onion, garlic, chocolate, and broth.',
      'Fry mole paste in lard. Add broth and simmer 20 minutes.',
      'Add seared chicken and simmer 30 minutes until tender.',
      'Serve with rice and warm tortillas.',
    ],
    tags: ['mole coloradito', 'mexican', 'oaxacan', 'chicken', 'chocolate'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 440,
      protein_g: 28,
      carbs_g: 26,
      fat_g: 22,
      fiber_g: 5,
      sugar_g: 8,
      sodium_mg: 520,
    },
  },
  {
    title: 'Gorditas de Chicharrón',
    description:
      'Thick masa pockets stuffed with chicharrón prensado, grilled and topped with salsa and cabbage.',
    cuisine: 'Mexican',
    prep_minutes: 20,
    cook_minutes: 10,
    servings: 6,
    calories: 340,
    ingredients: [
      { name: 'masa harina', quantity: '2', unit: 'cups' },
      { name: 'water', quantity: '1', unit: 'cup' },
      { name: 'chicharrón prensado', quantity: '8', unit: 'oz, chopped' },
      { name: 'salsa verde', quantity: '1/2', unit: 'cup' },
      { name: 'cabbage', quantity: '1', unit: 'cup, shredded' },
      { name: 'crema', quantity: '1/4', unit: 'cup' },
      { name: 'queso fresco', quantity: '1/2', unit: 'cup, crumbled' },
    ],
    steps: [
      'Mix masa with water. Form into thick discs.',
      'Grill on a comal until cooked through. Slice open one side.',
      'Stuff with chicharrón prensado.',
      'Top with cabbage, salsa verde, crema, and queso fresco.',
    ],
    tags: ['gorditas', 'mexican', 'chicharron', 'masa', 'pork'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 340,
      protein_g: 18,
      carbs_g: 30,
      fat_g: 16,
      fiber_g: 4,
      sugar_g: 2,
      sodium_mg: 560,
    },
  },
  {
    title: 'Agua de Jamaica',
    description: 'Refreshing Mexican hibiscus tea, tart and sweet, served over ice.',
    cuisine: 'Mexican',
    prep_minutes: 5,
    cook_minutes: 15,
    servings: 8,
    calories: 90,
    ingredients: [
      { name: 'dried hibiscus flowers (jamaica)', quantity: '1', unit: 'cup' },
      { name: 'water', quantity: '8', unit: 'cups' },
      { name: 'sugar', quantity: '3/4', unit: 'cup' },
    ],
    steps: [
      'Boil 4 cups water. Add hibiscus flowers. Simmer 10 minutes.',
      'Strain and discard flowers. Add sugar and stir until dissolved.',
      'Add remaining 4 cups cold water. Chill.',
      'Serve over ice.',
    ],
    tags: ['agua de jamaica', 'mexican', 'hibiscus', 'drink', 'beverage', 'vegan'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 90,
      protein_g: 0,
      carbs_g: 24,
      fat_g: 0,
      fiber_g: 0,
      sugar_g: 22,
      sodium_mg: 5,
    },
  },
];

export const mexicanRecipes = generateCuisineRecipes(configs);
