import type { CuisineRecipeConfig } from './types';
import { generateCuisineRecipes } from './types';

const configs: CuisineRecipeConfig[] = [
  {
    title: 'Hummus',
    description: 'Creamy chickpea dip with tahini, lemon, and garlic, drizzled with olive oil.',
    cuisine: 'Middle Eastern',
    prep_minutes: 15,
    cook_minutes: 0,
    servings: 8,
    calories: 120,
    ingredients: [
      { name: 'chickpeas', quantity: '2', unit: 'cans (15 oz), drained' },
      { name: 'tahini', quantity: '1/3', unit: 'cup' },
      { name: 'lemon juice', quantity: '3', unit: 'tbsp' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'cumin', quantity: '1/2', unit: 'tsp' },
      { name: 'paprika', quantity: '1/4', unit: 'tsp, for garnish' },
      { name: 'parsley', quantity: '1', unit: 'tbsp, chopped' },
    ],
    steps: [
      'Blend chickpeas, tahini, lemon juice, and garlic in a food processor.',
      'Add ice water gradually until smooth and creamy.',
      'Season with cumin, salt, and pepper.',
      'Spread on a plate, make a swirl with the back of a spoon.',
      'Drizzle with olive oil, sprinkle paprika and parsley.',
      'Serve with warm pita bread.',
    ],
    tags: ['middle-eastern', 'dip', 'chickpea', 'tahini', 'vegetarian'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 120,
      protein_g: 4,
      carbs_g: 14,
      fat_g: 6,
      fiber_g: 3,
      sugar_g: 1,
      sodium_mg: 180,
    },
  },
  {
    title: 'Falafel',
    description:
      'Crispy fried chickpea-herb patties seasoned with cumin, coriander, and fresh herbs.',
    cuisine: 'Middle Eastern',
    prep_minutes: 20,
    cook_minutes: 10,
    servings: 6,
    calories: 180,
    ingredients: [
      { name: 'dried chickpeas', quantity: '1', unit: 'cup, soaked overnight' },
      { name: 'parsley', quantity: '1', unit: 'cup, packed' },
      { name: 'cilantro', quantity: '1', unit: 'cup, packed' },
      { name: 'onion', quantity: '1', unit: 'small, quartered' },
      { name: 'garlic', quantity: '4', unit: 'cloves' },
      { name: 'cumin', quantity: '1', unit: 'tsp' },
      { name: 'coriander', quantity: '1', unit: 'tsp' },
      { name: 'baking soda', quantity: '1/4', unit: 'tsp' },
      { name: 'flour', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Pulse soaked chickpeas, herbs, onion, garlic, and spices in a food processor until coarse.',
      'Add baking soda and flour. Pulse to combine. Refrigerate 30 minutes.',
      'Form into small patties or balls.',
      'Deep fry at 350°F until deep golden and crispy, about 3-4 minutes.',
      'Drain on paper towels.',
      'Serve in pita with tahini sauce, pickles, and salad.',
    ],
    tags: ['middle-eastern', 'vegetarian', 'vegan', 'chickpea', 'fried'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 180,
      protein_g: 8,
      carbs_g: 22,
      fat_g: 8,
      fiber_g: 6,
      sugar_g: 2,
      sodium_mg: 280,
    },
  },
  {
    title: 'Shawarma',
    description:
      'Spit-roasted marinated chicken or lamb with warm Middle Eastern spices, served in a wrap.',
    cuisine: 'Middle Eastern',
    prep_minutes: 30,
    cook_minutes: 20,
    servings: 6,
    calories: 380,
    ingredients: [
      { name: 'chicken thigh', quantity: '2', unit: 'lb, boneless' },
      { name: 'yogurt', quantity: '1/2', unit: 'cup' },
      { name: 'cumin', quantity: '1', unit: 'tbsp' },
      { name: 'paprika', quantity: '1', unit: 'tbsp' },
      { name: 'turmeric', quantity: '1', unit: 'tsp' },
      { name: 'cinnamon', quantity: '1/2', unit: 'tsp' },
      { name: 'garlic', quantity: '4', unit: 'cloves, minced' },
      { name: 'pita bread', quantity: '6', unit: 'rounds' },
      { name: 'tahini sauce', quantity: '1/2', unit: 'cup' },
      { name: 'pickled turnip', quantity: '1/2', unit: 'cup' },
    ],
    steps: [
      'Mix yogurt, cumin, paprika, turmeric, cinnamon, garlic, and salt for marinade.',
      'Coat chicken in marinade. Refrigerate at least 4 hours.',
      'Grill or roast chicken at 425°F until charred and cooked through.',
      'Slice chicken into thin strips.',
      'Warm pita bread and spread with tahini sauce.',
      'Fill with sliced chicken, pickled turnips, and fresh vegetables.',
    ],
    tags: ['middle-eastern', 'chicken', 'wrap', 'spiced', 'street-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 36,
      carbs_g: 24,
      fat_g: 16,
      fiber_g: 2,
      sugar_g: 4,
      sodium_mg: 680,
    },
  },
  {
    title: 'Baba Ganoush',
    description: 'Smoky roasted eggplant dip with tahini, lemon, and garlic.',
    cuisine: 'Middle Eastern',
    prep_minutes: 10,
    cook_minutes: 40,
    servings: 6,
    calories: 100,
    ingredients: [
      { name: 'eggplant', quantity: '2', unit: 'large' },
      { name: 'tahini', quantity: '3', unit: 'tbsp' },
      { name: 'lemon juice', quantity: '3', unit: 'tbsp' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'cumin', quantity: '1/4', unit: 'tsp' },
      { name: 'parsley', quantity: '1', unit: 'tbsp, chopped' },
    ],
    steps: [
      'Roast eggplants over an open flame or under a broiler until charred and collapsed.',
      'Scoop out the flesh, drain excess liquid.',
      'Blend eggplant with tahini, lemon juice, garlic, and cumin until smooth.',
      'Season with salt and pepper.',
      'Spread on a plate, drizzle with olive oil.',
      'Garnish with parsley and serve with warm pita.',
    ],
    tags: ['middle-eastern', 'dip', 'eggplant', 'smoky', 'vegan'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 100,
      protein_g: 2,
      carbs_g: 10,
      fat_g: 6,
      fiber_g: 4,
      sugar_g: 3,
      sodium_mg: 140,
    },
  },
  {
    title: 'Tabbouleh',
    description: 'Fresh herb-forward salad with bulgur, tomatoes, mint, and lemon dressing.',
    cuisine: 'Middle Eastern',
    prep_minutes: 20,
    cook_minutes: 0,
    servings: 6,
    calories: 120,
    ingredients: [
      { name: 'bulgur wheat', quantity: '1/2', unit: 'cup, soaked' },
      { name: 'parsley', quantity: '2', unit: 'cups, finely chopped' },
      { name: 'mint', quantity: '1/2', unit: 'cup, chopped' },
      { name: 'tomato', quantity: '3', unit: 'diced' },
      { name: 'cucumber', quantity: '1', unit: 'diced' },
      { name: 'green onion', quantity: '4', unit: 'sliced' },
      { name: 'lemon juice', quantity: '3', unit: 'tbsp' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Soak bulgur in boiling water for 15 minutes. Drain and squeeze dry.',
      'Finely chop parsley, mint, and green onions.',
      'Dice tomatoes and cucumber.',
      'Toss bulgur with herbs and vegetables.',
      'Dress with lemon juice, olive oil, salt, and pepper.',
      'Chill for 30 minutes. Serve as a side or light meal.',
    ],
    tags: ['middle-eastern', 'salad', 'parsley', 'bulgur', 'vegetarian'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 120,
      protein_g: 3,
      carbs_g: 18,
      fat_g: 4,
      fiber_g: 4,
      sugar_g: 2,
      sodium_mg: 120,
    },
  },
  {
    title: 'Kibbeh',
    description: 'Spiced bulgur and lamb croquettes with pine nuts, fried until crispy golden.',
    cuisine: 'Middle Eastern',
    prep_minutes: 40,
    cook_minutes: 10,
    servings: 8,
    calories: 220,
    ingredients: [
      { name: 'bulgur wheat', quantity: '1', unit: 'cup, fine' },
      { name: 'ground lamb', quantity: '1', unit: 'lb' },
      { name: 'onion', quantity: '1', unit: 'grated' },
      { name: 'pine nuts', quantity: '1/4', unit: 'cup, toasted' },
      { name: 'cinnamon', quantity: '1/2', unit: 'tsp' },
      { name: 'allspice', quantity: '1/2', unit: 'tsp' },
      { name: 'mint', quantity: '1', unit: 'tsp, dried' },
      { name: 'flour', quantity: '1/2', unit: 'cup' },
    ],
    steps: [
      'Soak bulgur in warm water 20 minutes. Drain and squeeze very dry.',
      'Mix half the bulgur with ground lamb, onion, and spices for the outer shell.',
      'Cook remaining lamb with pine nuts, cinnamon, and allspice for the filling.',
      'Form bulgur-lamb mixture into oval shells, fill with meat-pine nut mixture, seal.',
      'Deep fry at 350°F until golden and crispy, about 4-5 minutes.',
      'Serve with yogurt dip or tahini sauce.',
    ],
    tags: ['middle-eastern', 'lamb', 'bulgur', 'fried', 'appetizer'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 220,
      protein_g: 16,
      carbs_g: 14,
      fat_g: 12,
      fiber_g: 2,
      sugar_g: 1,
      sodium_mg: 280,
    },
  },
  {
    title: 'Fattoush',
    description:
      'Levantine bread salad with crispy pita, fresh vegetables, sumac, and tangy dressing.',
    cuisine: 'Middle Eastern',
    prep_minutes: 15,
    cook_minutes: 5,
    servings: 4,
    calories: 160,
    ingredients: [
      { name: 'pita bread', quantity: '2', unit: 'rounds, torn' },
      { name: 'romaine lettuce', quantity: '1', unit: 'head, chopped' },
      { name: 'cucumber', quantity: '1', unit: 'diced' },
      { name: 'tomato', quantity: '2', unit: 'diced' },
      { name: 'radish', quantity: '4', unit: 'sliced' },
      { name: 'sumac', quantity: '1', unit: 'tsp' },
      { name: 'lemon juice', quantity: '3', unit: 'tbsp' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'mint', quantity: '2', unit: 'tbsp' },
      { name: 'pomegranate molasses', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Tear pita into pieces and fry or toast until crispy.',
      'Chop all vegetables and combine in a large bowl.',
      'Whisk lemon juice, olive oil, pomegranate molasses, sumac, salt, and pepper.',
      'Dress the salad and toss well.',
      'Add crispy pita just before serving to keep it crunchy.',
      'Garnish with extra sumac and fresh mint.',
    ],
    tags: ['middle-eastern', 'salad', 'pita', 'sumac', 'vegetarian'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 160,
      protein_g: 4,
      carbs_g: 20,
      fat_g: 8,
      fiber_g: 4,
      sugar_g: 4,
      sodium_mg: 220,
    },
  },
  {
    title: 'Shakshuka',
    description: 'Eggs poached in a spiced tomato-pepper sauce with cumin and paprika.',
    cuisine: 'Middle Eastern',
    prep_minutes: 10,
    cook_minutes: 20,
    servings: 4,
    calories: 220,
    ingredients: [
      { name: 'egg', quantity: '6', unit: 'large' },
      { name: 'tomato', quantity: '4', unit: 'diced, or 1 can crushed' },
      { name: 'bell pepper', quantity: '1', unit: 'diced' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'garlic', quantity: '3', unit: 'cloves, minced' },
      { name: 'cumin', quantity: '1', unit: 'tsp' },
      { name: 'paprika', quantity: '1', unit: 'tsp' },
      { name: 'chili flakes', quantity: '1/4', unit: 'tsp' },
      { name: 'feta cheese', quantity: '2', unit: 'oz, crumbled' },
      { name: 'cilantro', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Sauté onion and bell pepper in olive oil until soft.',
      'Add garlic, cumin, paprika, and chili flakes. Cook 1 minute.',
      'Add tomatoes and simmer 10 minutes until thickened.',
      'Make wells in the sauce and crack eggs into them.',
      'Cover and cook until egg whites are set but yolks are still runny, about 5-7 minutes.',
      'Top with crumbled feta and cilantro. Serve with crusty bread.',
    ],
    tags: ['middle-eastern', 'eggs', 'tomato', 'breakfast', 'vegetarian'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 220,
      protein_g: 14,
      carbs_g: 12,
      fat_g: 14,
      fiber_g: 3,
      sugar_g: 6,
      sodium_mg: 480,
    },
  },
  {
    title: 'Baklava',
    description:
      'Layers of flaky phyllo with pistachios and walnuts soaked in fragrant honey-rose syrup.',
    cuisine: 'Middle Eastern',
    prep_minutes: 30,
    cook_minutes: 45,
    servings: 24,
    calories: 180,
    ingredients: [
      { name: 'phyllo dough', quantity: '1', unit: 'lb package' },
      { name: 'pistachios', quantity: '1', unit: 'cup, finely chopped' },
      { name: 'walnuts', quantity: '1', unit: 'cup, finely chopped' },
      { name: 'butter', quantity: '1', unit: 'cup, melted' },
      { name: 'sugar', quantity: '1', unit: 'cup' },
      { name: 'honey', quantity: '1/2', unit: 'cup' },
      { name: 'water', quantity: '1/2', unit: 'cup' },
      { name: 'rose water', quantity: '1', unit: 'tbsp' },
      { name: 'cinnamon', quantity: '1', unit: 'tsp' },
      { name: 'lemon juice', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Mix pistachios, walnuts, cinnamon, and sugar for the filling.',
      'Layer 8 sheets of phyllo in a buttered pan, brushing each with butter.',
      'Spread a thin layer of nut filling. Repeat layers 3-4 times.',
      'Top with 8 more buttered phyllo sheets. Cut diamond shapes before baking.',
      'Bake at 350°F for 45 minutes until golden and crisp.',
      'Pour warm honey-rose syrup over the hot baklava. Let soak overnight.',
    ],
    tags: ['middle-eastern', 'dessert', 'phyllo', 'honey', 'pistachio'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 180,
      protein_g: 3,
      carbs_g: 22,
      fat_g: 10,
      fiber_g: 1,
      sugar_g: 16,
      sodium_mg: 100,
    },
  },
  {
    title: 'Lamb Kofta Kebabs',
    description:
      'Spiced ground lamb skewers grilled over charcoal with herbs and Middle Eastern spices.',
    cuisine: 'Middle Eastern',
    prep_minutes: 20,
    cook_minutes: 10,
    servings: 6,
    calories: 280,
    ingredients: [
      { name: 'ground lamb', quantity: '1.5', unit: 'lb' },
      { name: 'onion', quantity: '1', unit: 'small, grated' },
      { name: 'parsley', quantity: '1/4', unit: 'cup, chopped' },
      { name: 'cumin', quantity: '1', unit: 'tsp' },
      { name: 'coriander', quantity: '1', unit: 'tsp' },
      { name: 'cinnamon', quantity: '1/4', unit: 'tsp' },
      { name: 'garlic', quantity: '3', unit: 'cloves, minced' },
      { name: 'metal skewers', quantity: '6', unit: 'pieces' },
    ],
    steps: [
      'Combine lamb, grated onion, parsley, garlic, cumin, coriander, and cinnamon.',
      'Mix thoroughly and refrigerate 30 minutes.',
      'Shape mixture around metal skewers into elongated ovals.',
      'Grill over medium-high heat, turning, until charred and cooked through.',
      'Serve with pita, hummus, and pickled vegetables.',
    ],
    tags: ['middle-eastern', 'lamb', 'grilled', 'kebab', 'spiced'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 280,
      protein_g: 24,
      carbs_g: 2,
      fat_g: 20,
      fiber_g: 0,
      sugar_g: 1,
      sodium_mg: 320,
    },
  },
  {
    title: 'Mujadara',
    description: 'Comforting lentil and rice dish topped with crispy caramelized onions.',
    cuisine: 'Middle Eastern',
    prep_minutes: 10,
    cook_minutes: 35,
    servings: 6,
    calories: 280,
    ingredients: [
      { name: 'green lentils', quantity: '1', unit: 'cup' },
      { name: 'rice', quantity: '1', unit: 'cup' },
      { name: 'onion', quantity: '3', unit: 'large, sliced' },
      { name: 'olive oil', quantity: '3', unit: 'tbsp' },
      { name: 'cumin', quantity: '1', unit: 'tsp' },
      { name: 'cinnamon', quantity: '1/4', unit: 'tsp' },
      { name: 'yogurt', quantity: '1/2', unit: 'cup, for serving' },
    ],
    steps: [
      'Cook lentils in water until just tender, about 20 minutes. Drain.',
      'Fry sliced onions in olive oil until deeply caramelized and crispy. Reserve half for topping.',
      'Add cumin and cinnamon to the onions, cook 30 seconds.',
      'Add rice and lentils with 2 cups water. Season with salt.',
      'Bring to boil, cover, and simmer 20 minutes until rice is fluffy.',
      'Serve topped with crispy onions and a dollop of yogurt.',
    ],
    tags: ['middle-eastern', 'vegetarian', 'vegan', 'lentils', 'rice'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 12,
      carbs_g: 42,
      fat_g: 8,
      fiber_g: 10,
      sugar_g: 4,
      sodium_mg: 240,
    },
  },
  {
    title: 'Manakish',
    description:
      "Levantine flatbread topped with za'atar and olive oil, baked until puffy and golden.",
    cuisine: 'Middle Eastern',
    prep_minutes: 20,
    cook_minutes: 12,
    servings: 6,
    calories: 180,
    ingredients: [
      { name: 'flour', quantity: '3', unit: 'cups' },
      { name: 'yeast', quantity: '1', unit: 'tsp' },
      { name: 'warm water', quantity: '1', unit: 'cup' },
      { name: "za'atar", quantity: '3', unit: 'tbsp' },
      { name: 'olive oil', quantity: '1/4', unit: 'cup' },
      { name: 'salt', quantity: '1', unit: 'tsp' },
      { name: 'sugar', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Mix flour, yeast, sugar, salt, and water. Knead into a smooth dough.',
      'Let rise for 1 hour until doubled.',
      'Divide into 6 balls, roll into ovals or rounds.',
      "Mix za'atar with olive oil to make a paste.",
      "Spread za'atar paste on each dough round.",
      'Bake at 450°F for 8-12 minutes until puffed and golden. Serve warm.',
    ],
    tags: ['middle-eastern', 'bread', 'zaatar', 'vegetarian', 'vegan'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 180,
      protein_g: 4,
      carbs_g: 26,
      fat_g: 7,
      fiber_g: 2,
      sugar_g: 1,
      sodium_mg: 320,
    },
  },
  {
    title: 'Fattet Hummus',
    description: 'Warm chickpea and yogurt dish layered with toasted pita and pine nuts.',
    cuisine: 'Middle Eastern',
    prep_minutes: 15,
    cook_minutes: 15,
    servings: 4,
    calories: 240,
    ingredients: [
      { name: 'chickpeas', quantity: '2', unit: 'cans, drained' },
      { name: 'yogurt', quantity: '1.5', unit: 'cups' },
      { name: 'tahini', quantity: '2', unit: 'tbsp' },
      { name: 'pita bread', quantity: '2', unit: 'rounds, toasted & broken' },
      { name: 'pine nuts', quantity: '2', unit: 'tbsp, toasted' },
      { name: 'garlic', quantity: '2', unit: 'cloves, minced' },
      { name: 'lemon juice', quantity: '2', unit: 'tbsp' },
      { name: 'butter', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Warm chickpeas in a pot with a little water.',
      'Mix yogurt with tahini, garlic, lemon juice, and salt.',
      'Toast pita pieces until crispy. Arrange on a serving plate.',
      'Layer warm chickpeas over the pita.',
      'Pour yogurt-tahini sauce over the chickpeas.',
      'Melt butter, add pine nuts until golden. Drizzle over the top. Serve warm.',
    ],
    tags: ['middle-eastern', 'vegetarian', 'chickpea', 'yogurt', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 240,
      protein_g: 10,
      carbs_g: 30,
      fat_g: 10,
      fiber_g: 6,
      sugar_g: 4,
      sodium_mg: 380,
    },
  },
  {
    title: 'Kunafa',
    description:
      'Crispy shredded pastry with sweet cheese filling, soaked in orange blossom sugar syrup.',
    cuisine: 'Middle Eastern',
    prep_minutes: 25,
    cook_minutes: 30,
    servings: 8,
    calories: 320,
    ingredients: [
      { name: 'kataifi (shredded pastry)', quantity: '8', unit: 'oz' },
      { name: 'mozzarella cheese', quantity: '8', unit: 'oz, shredded' },
      { name: 'ricotta cheese', quantity: '1', unit: 'cup' },
      { name: 'butter', quantity: '4', unit: 'tbsp, melted' },
      { name: 'sugar', quantity: '1.5', unit: 'cups' },
      { name: 'water', quantity: '1', unit: 'cup' },
      { name: 'orange blossom water', quantity: '1', unit: 'tsp' },
      { name: 'lemon juice', quantity: '1', unit: 'tsp' },
      { name: 'pistachios', quantity: '2', unit: 'tbsp, crushed' },
    ],
    steps: [
      'Make syrup: boil sugar and water, add lemon juice and orange blossom water. Cool.',
      'Shred kataifi and toss with melted butter.',
      'Press half the kataifi into a buttered pan.',
      'Mix mozzarella and ricotta, spread over the kataifi layer.',
      'Top with remaining kataifi, pressing firmly.',
      'Bake at 375°F for 30 minutes until golden. Pour syrup over, garnish with pistachios.',
    ],
    tags: ['middle-eastern', 'dessert', 'cheese', 'pastry', 'sweet'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 12,
      carbs_g: 38,
      fat_g: 14,
      fiber_g: 1,
      sugar_g: 24,
      sodium_mg: 320,
    },
  },
  {
    title: 'Moutabal',
    description:
      'Smoky eggplant dip similar to baba ganoush but with more tahini and a creamier texture.',
    cuisine: 'Middle Eastern',
    prep_minutes: 10,
    cook_minutes: 40,
    servings: 6,
    calories: 110,
    ingredients: [
      { name: 'eggplant', quantity: '2', unit: 'large' },
      { name: 'tahini', quantity: '4', unit: 'tbsp' },
      { name: 'lemon juice', quantity: '2', unit: 'tbsp' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'pomegranate seeds', quantity: '1', unit: 'tbsp' },
      { name: 'parsley', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Roast eggplants over open flame until charred and collapsed, about 20 minutes.',
      'Scoop out flesh, drain liquid.',
      'Blend with tahini, lemon juice, and garlic until very smooth.',
      'Season with salt and pepper.',
      'Spread on a plate, drizzle with olive oil.',
      'Garnish with pomegranate seeds and parsley.',
    ],
    tags: ['middle-eastern', 'dip', 'eggplant', 'smoky', 'vegan'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 110,
      protein_g: 3,
      carbs_g: 10,
      fat_g: 8,
      fiber_g: 4,
      sugar_g: 3,
      sodium_mg: 120,
    },
  },
  {
    title: 'Mansaf',
    description: 'Jordanian lamb and rice dish with tangy jameed sauce and crispy flatbread.',
    cuisine: 'Middle Eastern',
    prep_minutes: 30,
    cook_minutes: 120,
    servings: 8,
    calories: 520,
    ingredients: [
      { name: 'lamb shoulder', quantity: '3', unit: 'lb, cubed' },
      { name: 'jameed (dried yogurt)', quantity: '1', unit: 'cup, rehydrated' },
      { name: 'rice', quantity: '2', unit: 'cups' },
      { name: 'shrak bread', quantity: '4', unit: 'pieces' },
      { name: 'onion', quantity: '2', unit: 'quartered' },
      { name: 'cardamom', quantity: '3', unit: 'pods' },
      { name: 'bay leaf', quantity: '2', unit: 'leaves' },
      { name: 'pine nuts', quantity: '1/4', unit: 'cup, toasted' },
      { name: 'parsley', quantity: '1/4', unit: 'cup, chopped' },
    ],
    steps: [
      'Boil lamb with onion, cardamom, and bay leaf until tender, about 1.5 hours.',
      'Blend rehydrated jameed until smooth, add to the lamb broth.',
      'Simmer lamb in jameed sauce for 30 minutes.',
      'Cook rice until fluffy.',
      'Lay shrak bread on a platter, top with rice.',
      'Arrange lamb on top, pour jameed sauce over, garnish with pine nuts and parsley.',
    ],
    tags: ['middle-eastern', 'jordanian', 'lamb', 'rice', 'festive'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 520,
      protein_g: 38,
      carbs_g: 40,
      fat_g: 22,
      fiber_g: 2,
      sugar_g: 2,
      sodium_mg: 480,
    },
  },
  {
    title: 'Shish Tawook',
    description:
      'Tender marinated chicken skewers grilled with garlic, lemon, and yogurt, served with garlic sauce.',
    cuisine: 'Middle Eastern',
    prep_minutes: 20,
    cook_minutes: 15,
    servings: 6,
    calories: 260,
    ingredients: [
      { name: 'chicken breast', quantity: '1.5', unit: 'lb, cubed' },
      { name: 'yogurt', quantity: '1/2', unit: 'cup' },
      { name: 'lemon juice', quantity: '3', unit: 'tbsp' },
      { name: 'garlic', quantity: '4', unit: 'cloves, minced' },
      { name: 'tomato paste', quantity: '1', unit: 'tbsp' },
      { name: 'cumin', quantity: '1', unit: 'tsp' },
      { name: 'paprika', quantity: '1', unit: 'tsp' },
      { name: 'olive oil', quantity: '1', unit: 'tbsp' },
      { name: 'wooden skewers', quantity: '6', unit: 'pieces, soaked' },
    ],
    steps: [
      'Mix yogurt, lemon juice, garlic, tomato paste, cumin, paprika, olive oil, salt, and pepper.',
      'Marinate chicken cubes in the mixture for at least 2 hours, preferably overnight.',
      'Thread chicken onto soaked skewers.',
      'Grill over medium-high heat, turning occasionally, until charred and cooked through, about 10-12 minutes.',
      'Serve with garlic sauce (toum), pita, and pickled turnips.',
    ],
    tags: ['middle-eastern', 'chicken', 'grilled', 'kebab', 'yogurt'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 260,
      protein_g: 34,
      carbs_g: 6,
      fat_g: 11,
      fiber_g: 0,
      sugar_g: 3,
      sodium_mg: 360,
    },
  },
  {
    title: 'Stuffed Grape Leaves',
    description:
      'Tender grape leaves filled with herbed rice and rolled into bite-sized parcels, simmered in lemon broth.',
    cuisine: 'Middle Eastern',
    prep_minutes: 45,
    cook_minutes: 40,
    servings: 8,
    calories: 140,
    ingredients: [
      { name: 'grape leaves', quantity: '1', unit: 'jar (16 oz), rinsed' },
      { name: 'rice', quantity: '1', unit: 'cup, short-grain' },
      { name: 'parsley', quantity: '1/2', unit: 'cup, chopped' },
      { name: 'dill', quantity: '1/4', unit: 'cup, chopped' },
      { name: 'mint', quantity: '2', unit: 'tbsp, chopped' },
      { name: 'onion', quantity: '1', unit: 'small, finely diced' },
      { name: 'lemon juice', quantity: '1/4', unit: 'cup' },
      { name: 'olive oil', quantity: '3', unit: 'tbsp' },
      { name: 'tomato', quantity: '1', unit: 'small, diced' },
      { name: 'pine nuts', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Mix rice with parsley, dill, mint, onion, tomato, pine nuts, 2 tbsp olive oil, salt, and pepper.',
      'Lay a grape leaf flat, vein side up. Place 1 tbsp filling near the stem.',
      'Fold sides in, then roll tightly into a small cylinder.',
      'Arrange rolls seam-side down in a pot, packing them snugly.',
      'Add lemon juice, remaining olive oil, and enough water to cover.',
      'Place a plate on top to keep rolls submerged. Simmer 40 minutes until rice is tender.',
      'Serve warm or at room temperature with extra lemon.',
    ],
    tags: ['middle-eastern', 'vegetarian', 'vegan', 'grape-leaves', 'rice'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 140,
      protein_g: 3,
      carbs_g: 20,
      fat_g: 6,
      fiber_g: 2,
      sugar_g: 2,
      sodium_mg: 280,
    },
  },
  {
    title: 'Muhammara',
    description:
      'Smoky roasted red pepper and walnut dip with pomegranate molasses and Aleppo pepper.',
    cuisine: 'Middle Eastern',
    prep_minutes: 15,
    cook_minutes: 25,
    servings: 8,
    calories: 130,
    ingredients: [
      { name: 'red bell pepper', quantity: '3', unit: 'large, roasted' },
      { name: 'walnuts', quantity: '1', unit: 'cup' },
      { name: 'breadcrumbs', quantity: '2', unit: 'tbsp' },
      { name: 'pomegranate molasses', quantity: '2', unit: 'tbsp' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'Aleppo pepper', quantity: '1', unit: 'tsp' },
      { name: 'cumin', quantity: '1/2', unit: 'tsp' },
      { name: 'garlic', quantity: '1', unit: 'clove' },
      { name: 'lemon juice', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Roast peppers under a broiler until charred. Peel, seed, and chop.',
      'Toast walnuts in a dry pan until fragrant.',
      'Blend roasted peppers, walnuts, breadcrumbs, garlic, and cumin until slightly chunky.',
      'Add pomegranate molasses, Aleppo pepper, lemon juice, salt, and pepper.',
      'Transfer to a bowl, drizzle with olive oil.',
      'Serve with warm pita or crusty bread.',
    ],
    tags: ['middle-eastern', 'dip', 'red-pepper', 'walnut', 'vegan'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 130,
      protein_g: 3,
      carbs_g: 10,
      fat_g: 10,
      fiber_g: 2,
      sugar_g: 4,
      sodium_mg: 160,
    },
  },
  {
    title: 'Maqluba',
    description:
      'Dramatic upside-down rice casserole with spiced chicken, eggplant, and cauliflower, flipped at the table.',
    cuisine: 'Middle Eastern',
    prep_minutes: 30,
    cook_minutes: 50,
    servings: 6,
    calories: 420,
    ingredients: [
      { name: 'chicken thighs', quantity: '1.5', unit: 'lb, bone-in' },
      { name: 'rice', quantity: '2', unit: 'cups, basmati' },
      { name: 'eggplant', quantity: '1', unit: 'large, sliced' },
      { name: 'cauliflower', quantity: '1', unit: 'small, cut into florets' },
      { name: 'onion', quantity: '1', unit: 'large, sliced' },
      { name: 'garlic', quantity: '4', unit: 'cloves' },
      { name: 'cumin', quantity: '1', unit: 'tsp' },
      { name: 'turmeric', quantity: '1/2', unit: 'tsp' },
      { name: 'cinnamon', quantity: '1/4', unit: 'tsp' },
      { name: 'pine nuts', quantity: '2', unit: 'tbsp, toasted' },
      { name: 'vegetable oil', quantity: '2', unit: 'tbsp, for frying' },
    ],
    steps: [
      'Fry eggplant and cauliflower slices in oil until golden. Drain on paper towels.',
      'Boil chicken with onion, garlic, cumin, turmeric, cinnamon, salt, and water until cooked, about 25 minutes.',
      'Remove chicken, strain and reserve the broth. Debone chicken.',
      'Soak rice in water for 15 minutes, then drain.',
      'Layer chicken at the bottom of a pot, then eggplant, then cauliflower.',
      'Add rice on top, pour chicken broth over (2 cups). Bring to boil, cover, simmer 25 minutes.',
      'Let rest 10 minutes. Invert onto a platter. Garnish with toasted pine nuts and serve with yogurt.',
    ],
    tags: ['middle-eastern', 'chicken', 'rice', 'eggplant', 'one-pot'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 28,
      carbs_g: 38,
      fat_g: 16,
      fiber_g: 4,
      sugar_g: 3,
      sodium_mg: 420,
    },
  },
  {
    title: 'Sambousek',
    description:
      'Crispy golden pastries filled with spiced ground lamb, onions, and pine nuts, popular during Ramadan.',
    cuisine: 'Middle Eastern',
    prep_minutes: 40,
    cook_minutes: 20,
    servings: 12,
    calories: 190,
    ingredients: [
      { name: 'flour', quantity: '2', unit: 'cups' },
      { name: 'vegetable oil', quantity: '3', unit: 'tbsp, plus more for frying' },
      { name: 'ground lamb', quantity: '1', unit: 'lb' },
      { name: 'onion', quantity: '1', unit: 'small, finely diced' },
      { name: 'pine nuts', quantity: '2', unit: 'tbsp, toasted' },
      { name: 'cumin', quantity: '1', unit: 'tsp' },
      { name: 'allspice', quantity: '1/2', unit: 'tsp' },
      { name: 'cinnamon', quantity: '1/4', unit: 'tsp' },
      { name: 'salt', quantity: '1', unit: 'tsp' },
      { name: 'water', quantity: '1/2', unit: 'cup, for dough' },
    ],
    steps: [
      'Make dough: mix flour, oil, salt, and water until smooth. Rest 30 minutes.',
      'Cook lamb with onion until browned. Drain excess fat.',
      'Add cumin, allspice, cinnamon, pine nuts, salt, and pepper. Cool.',
      'Roll dough thin, cut into circles.',
      'Place filling on half of each circle, fold into half-moons, crimp edges with a fork.',
      'Deep fry at 350°F until golden and crispy, about 3-4 minutes.',
      'Drain on paper towels. Serve hot with lemon wedges.',
    ],
    tags: ['middle-eastern', 'lamb', 'pastry', 'fried', 'ramadan'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 190,
      protein_g: 10,
      carbs_g: 14,
      fat_g: 11,
      fiber_g: 1,
      sugar_g: 1,
      sodium_mg: 260,
    },
  },
];

export const middleEasternRecipes = generateCuisineRecipes(configs);
