import type { CuisineRecipeConfig } from './types';
import { generateCuisineRecipes } from './types';

const configs: CuisineRecipeConfig[] = [
  {
    title: 'Chelo Kebab',
    description: 'Saffron rice with grilled ground beef kebabs, grilled tomato, and sumac.',
    cuisine: 'Persian',
    prep_minutes: 20,
    cook_minutes: 15,
    servings: 4,
    calories: 420,
    ingredients: [
      { name: 'ground beef', quantity: '1', unit: 'lb' },
      { name: 'basmati rice', quantity: '2', unit: 'cups' },
      { name: 'saffron', quantity: '1', unit: 'pinch, bloomed' },
      { name: 'onion', quantity: '1', unit: 'grated' },
      { name: 'sumac', quantity: '1', unit: 'tsp' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
      { name: 'grilled tomato', quantity: '4', unit: 'halves' },
    ],
    steps: [
      'Mix beef with grated onion, salt, and pepper. Form onto skewers.',
      'Make saffron rice: cook basmati, steam with saffron water and butter.',
      'Grill kebabs over high heat until charred and cooked.',
      'Grill tomato halves alongside.',
      'Plate saffron rice, top with kebab and tomato.',
      'Sprinkle with sumac. Serve with fresh herbs.',
    ],
    tags: ['persian', 'kebab', 'beef', 'saffron', 'rice'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 28,
      carbs_g: 42,
      fat_g: 14,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 380,
    },
  },
  {
    title: 'Ghormeh Sabzi',
    description: 'Herb-rich Persian stew with kidney beans, dried lime, and tender beef.',
    cuisine: 'Persian',
    prep_minutes: 20,
    cook_minutes: 120,
    servings: 6,
    calories: 340,
    ingredients: [
      { name: 'beef chuck', quantity: '1', unit: 'lb, cubed' },
      { name: 'fresh herbs (parsley, cilantro, fenugreek)', quantity: '4', unit: 'cups, chopped' },
      { name: 'kidney beans', quantity: '1', unit: 'can' },
      { name: 'dried lime (limoo omani)', quantity: '3', unit: 'whole, pierced' },
      { name: 'onion', quantity: '2', unit: 'diced' },
      { name: 'turmeric', quantity: '1', unit: 'tsp' },
      { name: 'oil', quantity: '3', unit: 'tbsp' },
    ],
    steps: [
      'Fry herbs in oil until very dark and fragrant, about 20 minutes.',
      'Brown beef with onion and turmeric.',
      'Add fried herbs, beans, dried limes, and water.',
      'Simmer 2 hours until beef is very tender.',
      'Season with salt and the broth from dried limes.',
      'Serve with saffron rice.',
    ],
    tags: ['persian', 'stew', 'herbs', 'beef', 'dried-lime'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 340,
      protein_g: 28,
      carbs_g: 12,
      fat_g: 20,
      fiber_g: 4,
      sugar_g: 2,
      sodium_mg: 420,
    },
  },
  {
    title: 'Fesenjan',
    description: 'Walnut-pomegranate stew with duck or chicken — a festive Persian classic.',
    cuisine: 'Persian',
    prep_minutes: 20,
    cook_minutes: 90,
    servings: 6,
    calories: 420,
    ingredients: [
      { name: 'chicken thigh', quantity: '2', unit: 'lb' },
      { name: 'walnuts', quantity: '2', unit: 'cups, ground & toasted' },
      { name: 'pomegranate molasses', quantity: '1/2', unit: 'cup' },
      { name: 'onion', quantity: '2', unit: 'diced' },
      { name: 'turmeric', quantity: '1', unit: 'tsp' },
      { name: 'sugar', quantity: '2', unit: 'tbsp' },
      { name: 'saffron', quantity: '1', unit: 'pinch' },
    ],
    steps: [
      'Toast and grind walnuts.',
      'Brown chicken and set aside.',
      'Sauté onion with turmeric. Add ground walnuts and water.',
      'Add pomegranate molasses and sugar. Simmer 30 minutes.',
      'Return chicken. Simmer 1 hour until tender and sauce is thick.',
      'Serve with saffron rice.',
    ],
    tags: ['persian', 'stew', 'walnut', 'pomegranate', 'chicken'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 420,
      protein_g: 28,
      carbs_g: 14,
      fat_g: 28,
      fiber_g: 3,
      sugar_g: 6,
      sodium_mg: 380,
    },
  },
  {
    title: 'Tahdig',
    description:
      'Crispy golden saffron rice crust from the bottom of the pot — the prized part of Persian rice.',
    cuisine: 'Persian',
    prep_minutes: 10,
    cook_minutes: 45,
    servings: 6,
    calories: 220,
    ingredients: [
      { name: 'basmati rice', quantity: '3', unit: 'cups' },
      { name: 'saffron', quantity: '1', unit: 'pinch, bloomed' },
      { name: 'butter', quantity: '3', unit: 'tbsp' },
      { name: 'yogurt', quantity: '2', unit: 'tbsp' },
      { name: 'oil', quantity: '2', unit: 'tbsp' },
      { name: 'salt', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Soak rice for 30 minutes. Parboil until just al dente. Drain.',
      'Mix a scoop of rice with yogurt, saffron, and oil for the tahdig layer.',
      'Spread this mixture on the bottom of a pot.',
      'Pile remaining rice on top in a cone shape.',
      'Cover and steam on low heat for 30-40 minutes.',
      'Flip the pot onto a plate — the crispy crust should come out golden.',
    ],
    tags: ['persian', 'rice', 'saffron', 'crispy', 'tahdig'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 220,
      protein_g: 4,
      carbs_g: 42,
      fat_g: 4,
      fiber_g: 1,
      sugar_g: 0,
      sodium_mg: 280,
    },
  },
  {
    title: 'Zereshk Polo',
    description: 'Saffron rice with barberries and pistachios — a festive Persian rice dish.',
    cuisine: 'Persian',
    prep_minutes: 15,
    cook_minutes: 30,
    servings: 6,
    calories: 280,
    ingredients: [
      { name: 'basmati rice', quantity: '2', unit: 'cups' },
      { name: 'barberries (zereshk)', quantity: '1/2', unit: 'cup' },
      { name: 'saffron', quantity: '1', unit: 'pinch, bloomed' },
      { name: 'pistachios', quantity: '1/4', unit: 'cup, slivered' },
      { name: 'sugar', quantity: '1', unit: 'tbsp' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Cook basmati rice. Steam with saffron.',
      'Rinse barberries, sauté in butter with sugar.',
      'Toast pistachios.',
      'Mound saffron rice on a platter.',
      'Top with barberries and pistachios.',
      'Serve with chicken.',
    ],
    tags: ['persian', 'rice', 'barberry', 'saffron', 'festive'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 6,
      carbs_g: 44,
      fat_g: 8,
      fiber_g: 2,
      sugar_g: 4,
      sodium_mg: 180,
    },
  },
  {
    title: 'Kashk-e Bademjan',
    description: 'Smoky eggplant dip with whey, mint, and walnuts — a rich Persian appetizer.',
    cuisine: 'Persian',
    prep_minutes: 15,
    cook_minutes: 30,
    servings: 6,
    calories: 180,
    ingredients: [
      { name: 'eggplant', quantity: '3', unit: 'large' },
      { name: 'kashk (whey)', quantity: '1/2', unit: 'cup' },
      { name: 'walnuts', quantity: '1/4', unit: 'cup, chopped' },
      { name: 'mint', quantity: '2', unit: 'tbsp, dried & fried' },
      { name: 'garlic', quantity: '3', unit: 'cloves' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'turmeric', quantity: '1/2', unit: 'tsp' },
    ],
    steps: [
      'Fry eggplant slices until golden and soft.',
      'Mash eggplant with sautéed onion, garlic, and turmeric.',
      'Add kashk and stir well.',
      'Top with fried mint, walnuts, and a drizzle of kashk.',
      'Serve with warm flatbread.',
    ],
    tags: ['persian', 'eggplant', 'dip', 'whey', 'appetizer'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 180,
      protein_g: 6,
      carbs_g: 14,
      fat_g: 12,
      fiber_g: 4,
      sugar_g: 4,
      sodium_mg: 320,
    },
  },
  {
    title: 'Sabzi Polo ba Mahi',
    description: 'Herbed rice with fried fish — a traditional Persian New Year dish.',
    cuisine: 'Persian',
    prep_minutes: 20,
    cook_minutes: 30,
    servings: 4,
    calories: 380,
    ingredients: [
      { name: 'white fish fillet', quantity: '4', unit: 'pieces' },
      { name: 'basmati rice', quantity: '2', unit: 'cups' },
      { name: 'dill', quantity: '1', unit: 'cup, chopped' },
      { name: 'parsley', quantity: '1/2', unit: 'cup, chopped' },
      { name: 'chives', quantity: '1/2', unit: 'cup, chopped' },
      { name: 'saffron', quantity: '1', unit: 'pinch' },
      { name: 'flour', quantity: '1/4', unit: 'cup, for dredging' },
      { name: 'turmeric', quantity: '1/2', unit: 'tsp' },
    ],
    steps: [
      'Parboil rice. Mix with chopped herbs.',
      'Steam the herbed rice with saffron for 30 minutes.',
      'Season fish with turmeric, salt, and pepper.',
      'Dredge in flour and pan-fry until golden.',
      'Serve herbed rice with fried fish on top.',
      'Garnish with saffron rice and fresh herbs.',
    ],
    tags: ['persian', 'rice', 'fish', 'herbs', 'new-year'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 28,
      carbs_g: 42,
      fat_g: 8,
      fiber_g: 3,
      sugar_g: 1,
      sodium_mg: 320,
    },
  },
  {
    title: 'Baghali Polo',
    description: 'Persian rice with dill and fava beans, often served with lamb shank.',
    cuisine: 'Persian',
    prep_minutes: 15,
    cook_minutes: 30,
    servings: 6,
    calories: 320,
    ingredients: [
      { name: 'basmati rice', quantity: '2', unit: 'cups' },
      { name: 'fava beans', quantity: '1', unit: 'cup, shelled' },
      { name: 'dill', quantity: '1', unit: 'cup, chopped' },
      { name: 'saffron', quantity: '1', unit: 'pinch' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
      { name: 'lamb shank', quantity: '2', unit: '(optional)' },
    ],
    steps: [
      'Parboil rice until al dente. Drain.',
      'Layer rice with dill and fava beans in a pot.',
      'Add saffron water and butter.',
      'Steam covered on low heat for 30 minutes.',
      'If serving with lamb shank, braise separately until tender.',
      'Serve rice with lamb shank on top.',
    ],
    tags: ['persian', 'rice', 'dill', 'fava-beans', 'lamb'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 8,
      carbs_g: 48,
      fat_g: 8,
      fiber_g: 4,
      sugar_g: 1,
      sodium_mg: 180,
    },
  },
  {
    title: 'Abgoosht',
    description:
      'Hearty Persian lamb and chickpea stew, served as broth and mashed meat separately.',
    cuisine: 'Persian',
    prep_minutes: 15,
    cook_minutes: 120,
    servings: 6,
    calories: 380,
    ingredients: [
      { name: 'lamb shank', quantity: '2', unit: 'lb' },
      { name: 'chickpeas', quantity: '1', unit: 'cup, soaked' },
      { name: 'potato', quantity: '2', unit: 'diced' },
      { name: 'onion', quantity: '2', unit: 'quartered' },
      { name: 'tomato paste', quantity: '2', unit: 'tbsp' },
      { name: 'dried lime', quantity: '2', unit: 'whole' },
      { name: 'turmeric', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Brown lamb with onion and turmeric.',
      'Add water, chickpeas, and dried limes. Simmer 1.5 hours.',
      'Add potato and tomato paste. Cook 30 more minutes.',
      'Remove solids, mash them together (the goosht).',
      'Serve the broth separately in a bowl.',
      'Eat the mashed solids with flatbread, dipping in the broth.',
    ],
    tags: ['persian', 'stew', 'lamb', 'chickpea', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 32,
      carbs_g: 24,
      fat_g: 16,
      fiber_g: 6,
      sugar_g: 3,
      sodium_mg: 480,
    },
  },
  {
    title: 'Sholeh Zard',
    description:
      'Saffron rice pudding with rose water, pistachios, and cinnamon — a Persian dessert.',
    cuisine: 'Persian',
    prep_minutes: 10,
    cook_minutes: 40,
    servings: 6,
    calories: 220,
    ingredients: [
      { name: 'rice', quantity: '1/2', unit: 'cup, short grain' },
      { name: 'sugar', quantity: '1', unit: 'cup' },
      { name: 'saffron', quantity: '1', unit: 'pinch, bloomed' },
      { name: 'rose water', quantity: '1', unit: 'tbsp' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
      { name: 'pistachios', quantity: '2', unit: 'tbsp, slivered' },
      { name: 'cinnamon', quantity: '1/4', unit: 'tsp' },
    ],
    steps: [
      'Boil rice in plenty of water until very soft, about 30 minutes.',
      'Add sugar, saffron, and butter. Stir until thick.',
      'Add rose water.',
      'Pour into a serving dish.',
      'Decorate with cinnamon and pistachios in a pattern.',
      'Serve warm or chilled.',
    ],
    tags: ['persian', 'dessert', 'saffron', 'rice-pudding', 'rose-water'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 220,
      protein_g: 3,
      carbs_g: 44,
      fat_g: 4,
      fiber_g: 0,
      sugar_g: 28,
      sodium_mg: 40,
    },
  },
  {
    title: 'Joojeh Kabab',
    description: 'Saffron-marinated grilled chicken skewers with charred tomatoes and onions.',
    cuisine: 'Persian',
    prep_minutes: 15,
    cook_minutes: 15,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'chicken breast', quantity: '1.5', unit: 'lb, cubed' },
      { name: 'saffron', quantity: '1', unit: 'pinch, bloomed' },
      { name: 'yogurt', quantity: '1/2', unit: 'cup' },
      { name: 'onion', quantity: '1', unit: 'grated' },
      { name: 'lemon juice', quantity: '2', unit: 'tbsp' },
      { name: 'butter', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Marinate chicken in saffron, yogurt, onion, and lemon for 4+ hours.',
      'Thread onto skewers.',
      'Grill over medium-high heat until charred and cooked.',
      'Baste with saffron butter.',
      'Serve with grilled tomato and onion.',
      'Serve with saffron rice.',
    ],
    tags: ['persian', 'chicken', 'grilled', 'saffron', 'kebab'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 34,
      carbs_g: 4,
      fat_g: 12,
      fiber_g: 0,
      sugar_g: 2,
      sodium_mg: 280,
    },
  },
  {
    title: 'Khoresh Bademjan',
    description: 'Persian eggplant and beef stew with tomatoes and golden-fried eggplant.',
    cuisine: 'Persian',
    prep_minutes: 20,
    cook_minutes: 60,
    servings: 6,
    calories: 340,
    ingredients: [
      { name: 'beef chuck', quantity: '1', unit: 'lb, cubed' },
      { name: 'eggplant', quantity: '2', unit: 'large, fried' },
      { name: 'tomato', quantity: '3', unit: 'diced' },
      { name: 'onion', quantity: '2', unit: 'sliced' },
      { name: 'turmeric', quantity: '1', unit: 'tsp' },
      { name: 'saffron', quantity: '1', unit: 'pinch' },
      { name: 'oil', quantity: '1/2', unit: 'cup, for frying' },
    ],
    steps: [
      'Salt eggplant slices, let drain 30 minutes. Pat dry and fry until golden.',
      'Brown beef with onion and turmeric.',
      'Add tomato and water. Simmer 1 hour.',
      'Add fried eggplant on top. Simmer 15 more minutes.',
      'Season with saffron water.',
      'Serve with saffron rice.',
    ],
    tags: ['persian', 'stew', 'eggplant', 'beef', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 340,
      protein_g: 24,
      carbs_g: 10,
      fat_g: 22,
      fiber_g: 4,
      sugar_g: 4,
      sodium_mg: 420,
    },
  },
];

export const persianRecipes = generateCuisineRecipes(configs);
