import type { CuisineRecipeConfig } from './types';
import { generateCuisineRecipes } from './types';

const configs: CuisineRecipeConfig[] = [
  {
    title: 'Swedish Meatballs',
    description:
      'Tender meatballs in creamy gravy served with lingonberry sauce and pickled cucumber.',
    cuisine: 'Scandinavian',
    prep_minutes: 25,
    cook_minutes: 20,
    servings: 6,
    calories: 380,
    ingredients: [
      { name: 'ground beef', quantity: '1', unit: 'lb' },
      { name: 'ground pork', quantity: '1/2', unit: 'lb' },
      { name: 'breadcrumbs', quantity: '1/2', unit: 'cup' },
      { name: 'egg', quantity: '1', unit: 'large' },
      { name: 'onion', quantity: '1/2', unit: 'finely grated' },
      { name: 'beef broth', quantity: '2', unit: 'cups' },
      { name: 'heavy cream', quantity: '1/2', unit: 'cup' },
      { name: 'lingonberry jam', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Mix beef, pork, breadcrumbs, egg, onion, and spices. Form into 1-inch meatballs.',
      'Brown meatballs in butter on all sides. Remove and set aside.',
      'Make gravy: add broth to the pan, scrape up fond. Stir in cream and simmer until thick.',
      'Return meatballs to gravy. Serve with mashed potatoes, lingonberry, and pickled cucumber.',
    ],
    tags: ['meatballs', 'swedish', 'gravy', 'lingonberry', 'comfort food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 24,
      carbs_g: 18,
      fat_g: 24,
      fiber_g: 1,
      sugar_g: 4,
      sodium_mg: 520,
    },
  },
  {
    title: 'Gravlax',
    description:
      'Nordic cured salmon with dill, sugar, and salt, sliced thin and served with mustard-dill sauce.',
    cuisine: 'Scandinavian',
    prep_minutes: 15,
    cook_minutes: 0,
    servings: 8,
    calories: 180,
    ingredients: [
      { name: 'salmon fillet', quantity: '2', unit: 'lbs, skin-on' },
      { name: 'salt', quantity: '1/4', unit: 'cup' },
      { name: 'sugar', quantity: '1/4', unit: 'cup' },
      { name: 'fresh dill', quantity: '2', unit: 'bunches, chopped' },
      { name: 'black pepper', quantity: '1', unit: 'tbsp, cracked' },
      { name: 'Dijon mustard', quantity: '2', unit: 'tbsp' },
      { name: 'honey', quantity: '1', unit: 'tbsp' },
      { name: 'caper brine', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Mix salt, sugar, pepper, and dill. Rub over salmon on both sides.',
      'Wrap tightly in plastic and weight down in the fridge. Cure 48-72 hours, turning once.',
      'Make mustard-dill sauce: whisk Dijon, honey, caper brine, dill, and oil.',
      'Slice gravlax paper-thin on the bias. Serve with sauce and dark bread.',
    ],
    tags: ['gravlax', 'scandinavian', 'salmon', 'cured', 'dill'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 180,
      protein_g: 24,
      carbs_g: 4,
      fat_g: 8,
      fiber_g: 0,
      sugar_g: 2,
      sodium_mg: 680,
    },
  },
  {
    title: 'Smörgåsbord',
    description: 'Swedish buffet spread with herring, gravlax, meatballs, cheese, and crispbread.',
    cuisine: 'Scandinavian',
    prep_minutes: 30,
    cook_minutes: 0,
    servings: 10,
    calories: 420,
    ingredients: [
      { name: 'pickled herring', quantity: '1', unit: 'cup' },
      { name: 'gravlax', quantity: '8', unit: 'oz, sliced' },
      { name: 'meatballs', quantity: '20', unit: 'pieces' },
      { name: 'cheese assortment', quantity: '8', unit: 'oz' },
      { name: 'knäckebröd', quantity: '1', unit: 'package' },
      { name: 'butter', quantity: '4', unit: 'tbsp' },
      { name: 'cucumber salad', quantity: '2', unit: 'cups' },
      { name: 'mustard', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Arrange pickled herring, gravlax, and cold cuts on a platter.',
      'Warm meatballs and serve with lingonberry in a separate dish.',
      'Set out cheese, butter, crispbread, and cucumber salad.',
      'Guests build open-faced sandwiches. Serve with snaps and beer.',
    ],
    tags: ['smörgåsbord', 'swedish', 'buffet', 'herring', 'spread'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 28,
      carbs_g: 24,
      fat_g: 24,
      fiber_g: 2,
      sugar_g: 6,
      sodium_mg: 820,
    },
  },
  {
    title: 'Kanelbullar (Swedish Cinnamon Buns)',
    description: 'Cardamom-scented Swedish cinnamon buns with pearl sugar topping.',
    cuisine: 'Scandinavian',
    prep_minutes: 30,
    cook_minutes: 15,
    servings: 12,
    calories: 260,
    ingredients: [
      { name: 'flour', quantity: '4', unit: 'cups' },
      { name: 'butter', quantity: '1/2', unit: 'cup' },
      { name: 'milk', quantity: '1', unit: 'cup' },
      { name: 'sugar', quantity: '1/2', unit: 'cup' },
      { name: 'cardamom', quantity: '1', unit: 'tsp, ground' },
      { name: 'cinnamon', quantity: '2', unit: 'tbsp' },
      { name: 'yeast', quantity: '1', unit: 'packet' },
      { name: 'pearl sugar', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Make dough: warm milk, dissolve yeast. Mix in flour, cardamom, butter, and sugar. Knead and rise 1 hour.',
      'Roll dough into a rectangle. Spread with butter, cinnamon, and sugar. Roll up and cut into pieces.',
      'Place in paper liners. Rise 30 minutes.',
      'Brush with egg, sprinkle with pearl sugar. Bake at 400°F for 12-15 minutes.',
    ],
    tags: ['kanelbullar', 'cinnamon bun', 'swedish', 'pastry', 'fika'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 260,
      protein_g: 5,
      carbs_g: 36,
      fat_g: 12,
      fiber_g: 1,
      sugar_g: 16,
      sodium_mg: 180,
    },
  },
  {
    title: 'Pickled Herring',
    description: 'Scandinavian herring cured in vinegar, onion, and spice brine.',
    cuisine: 'Scandinavian',
    prep_minutes: 20,
    cook_minutes: 0,
    servings: 8,
    calories: 120,
    ingredients: [
      { name: 'herring fillets', quantity: '1', unit: 'lb, cut into pieces' },
      { name: 'vinegar', quantity: '1', unit: 'cup' },
      { name: 'sugar', quantity: '1/2', unit: 'cup' },
      { name: 'onion', quantity: '1', unit: 'sliced' },
      { name: 'allspice berries', quantity: '6', unit: 'whole' },
      { name: 'bay leaf', quantity: '2', unit: 'pieces' },
      { name: 'mustard seeds', quantity: '1', unit: 'tsp' },
      { name: 'carrot', quantity: '1', unit: 'sliced' },
    ],
    steps: [
      'Salt herring for 12 hours, then rinse.',
      'Bring vinegar, sugar, and spices to a boil. Cool completely.',
      'Layer herring, onion, and carrot in a jar. Pour brine over.',
      'Refrigerate 2-3 days before serving. Keeps for weeks.',
    ],
    tags: ['herring', 'pickled', 'scandinavian', 'preserved', 'appetizer'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 120,
      protein_g: 12,
      carbs_g: 10,
      fat_g: 4,
      fiber_g: 0,
      sugar_g: 8,
      sodium_mg: 580,
    },
  },
  {
    title: 'Norwegian Salmon Soup',
    description: 'Creamy fish chowder with salmon, root vegetables, and dill.',
    cuisine: 'Scandinavian',
    prep_minutes: 15,
    cook_minutes: 25,
    servings: 6,
    calories: 280,
    ingredients: [
      { name: 'salmon fillet', quantity: '1', unit: 'lb, cubed' },
      { name: 'potato', quantity: '2', unit: 'medium, cubed' },
      { name: 'carrot', quantity: '2', unit: 'sliced' },
      { name: 'leek', quantity: '1', unit: 'sliced' },
      { name: 'heavy cream', quantity: '1', unit: 'cup' },
      { name: 'fish stock', quantity: '4', unit: 'cups' },
      { name: 'dill', quantity: '3', unit: 'tbsp, chopped' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Sauté leek and carrot in butter. Add fish stock and potato. Simmer 15 minutes.',
      'Add salmon cubes and cook 5 minutes until just done.',
      'Stir in cream and dill. Season with salt, pepper, and lemon juice.',
      'Serve hot with crusty bread.',
    ],
    tags: ['salmon soup', 'norwegian', 'chowder', 'fish', 'creamy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 22,
      carbs_g: 16,
      fat_g: 14,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 480,
    },
  },
  {
    title: 'Rugbrød (Danish Rye Bread)',
    description: 'Dense, sour Danish whole-grain rye bread with seeds — the base of smørrebrød.',
    cuisine: 'Scandinavian',
    prep_minutes: 20,
    cook_minutes: 90,
    servings: 12,
    calories: 140,
    ingredients: [
      { name: 'rye flour', quantity: '4', unit: 'cups' },
      { name: 'water', quantity: '2.5', unit: 'cups' },
      { name: 'sourdough starter', quantity: '1', unit: 'cup' },
      { name: 'sunflower seeds', quantity: '1/2', unit: 'cup' },
      { name: 'flax seeds', quantity: '1/4', unit: 'cup' },
      { name: 'salt', quantity: '1.5', unit: 'tsp' },
    ],
    steps: [
      'Mix rye flour, water, sourdough starter, seeds, and salt into a thick batter.',
      'Pour into a greased loaf pan. Let rise 12-24 hours until doubled.',
      'Bake at 350°F for 90 minutes until hollow-sounding when tapped.',
      'Cool completely (ideally 24 hours) before slicing thin.',
    ],
    tags: ['rugbrød', 'danish', 'rye bread', 'sourdough', 'seeds'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 140,
      protein_g: 5,
      carbs_g: 24,
      fat_g: 3,
      fiber_g: 5,
      sugar_g: 1,
      sodium_mg: 240,
    },
  },
  {
    title: 'Smørrebrød with Herring',
    description: 'Danish open-faced sandwich on rye bread with pickled herring, onion, and capers.',
    cuisine: 'Scandinavian',
    prep_minutes: 15,
    cook_minutes: 0,
    servings: 4,
    calories: 220,
    ingredients: [
      { name: 'rugbrød', quantity: '4', unit: 'slices' },
      { name: 'pickled herring', quantity: '8', unit: 'oz' },
      { name: 'red onion', quantity: '1/2', unit: 'thinly sliced' },
      { name: 'capers', quantity: '1', unit: 'tbsp' },
      { name: 'dill', quantity: '4', unit: 'sprigs' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Spread butter on each slice of rugbrød.',
      'Arrange pickled herring on the bread.',
      'Top with red onion slices and capers.',
      'Garnish with fresh dill and serve immediately.',
    ],
    tags: ['smørrebrød', 'danish', 'open-faced', 'herring', 'sandwich'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 220,
      protein_g: 12,
      carbs_g: 22,
      fat_g: 10,
      fiber_g: 3,
      sugar_g: 4,
      sodium_mg: 620,
    },
  },
  {
    title: 'Köttbullar with Lingonberry',
    description:
      'Classic Swedish meatballs with lingonberry sauce, creamy gravy, and boiled potatoes.',
    cuisine: 'Scandinavian',
    prep_minutes: 20,
    cook_minutes: 25,
    servings: 4,
    calories: 420,
    ingredients: [
      { name: 'ground beef', quantity: '1', unit: 'lb' },
      { name: 'ground pork', quantity: '1/2', unit: 'lb' },
      { name: 'cream', quantity: '1/2', unit: 'cup' },
      { name: 'breadcrumbs', quantity: '1/3', unit: 'cup' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
      { name: 'beef broth', quantity: '1.5', unit: 'cups' },
      { name: 'lingonberry jam', quantity: '1/4', unit: 'cup' },
      { name: 'potatoes', quantity: '4', unit: 'medium, boiled' },
    ],
    steps: [
      'Mix meats, breadcrumbs, cream, egg, and onion. Form into balls.',
      'Fry meatballs in butter until browned. Remove.',
      'Add flour to butter, whisk in broth and cream for gravy.',
      'Return meatballs to gravy. Serve with boiled potatoes and lingonberry.',
    ],
    tags: ['köttbullar', 'swedish', 'meatballs', 'lingonberry', 'traditional'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 26,
      carbs_g: 28,
      fat_g: 22,
      fiber_g: 2,
      sugar_g: 6,
      sodium_mg: 560,
    },
  },
  {
    title: 'Finnish Salmon Pie (Lohipiirakka)',
    description: 'Savory pie filled with salmon, rice, and hard-boiled eggs in a rye crust.',
    cuisine: 'Scandinavian',
    prep_minutes: 30,
    cook_minutes: 45,
    servings: 8,
    calories: 380,
    ingredients: [
      { name: 'rye flour', quantity: '2', unit: 'cups' },
      { name: 'butter', quantity: '3', unit: 'tbsp' },
      { name: 'salmon fillet', quantity: '1', unit: 'lb, cubed' },
      { name: 'cooked rice', quantity: '1', unit: 'cup' },
      { name: 'hard-boiled eggs', quantity: '3', unit: 'sliced' },
      { name: 'dill', quantity: '2', unit: 'tbsp' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'cream', quantity: '1/2', unit: 'cup' },
    ],
    steps: [
      'Make rye dough: mix flour, butter, and water. Rest 30 minutes.',
      'Roll out dough and line a pie dish. Layer rice, salmon, eggs, onion, and dill.',
      'Pour cream over filling. Top with remaining dough and crimp edges.',
      'Bake at 375°F for 40 minutes until golden. Serve warm or cold.',
    ],
    tags: ['lohipiirakka', 'finnish', 'salmon', 'pie', 'rye'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 22,
      carbs_g: 28,
      fat_g: 18,
      fiber_g: 3,
      sugar_g: 2,
      sodium_mg: 380,
    },
  },
  {
    title: 'Prinsesstårta',
    description:
      'Swedish princess cake — dome of sponge, custard, and whipped cream under green marzipan.',
    cuisine: 'Scandinavian',
    prep_minutes: 40,
    cook_minutes: 25,
    servings: 10,
    calories: 340,
    ingredients: [
      { name: 'sponge cake', quantity: '1', unit: '9-inch round' },
      { name: 'pastry cream', quantity: '2', unit: 'cups' },
      { name: 'heavy cream', quantity: '2', unit: 'cups, whipped' },
      { name: 'green marzipan', quantity: '1', unit: 'lb, rolled' },
      { name: 'raspberry jam', quantity: '1/3', unit: 'cup' },
      { name: 'powdered sugar', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Split sponge cake into 3 layers.',
      'Layer: sponge, raspberry jam, custard, sponge, whipped cream dome.',
      'Drape green marzipan over the cream dome, smoothing it down.',
      'Dust with powdered sugar. Decorate with a marzipan rose.',
    ],
    tags: ['prinsesstårta', 'swedish', 'cake', 'marzipan', 'elegant'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 340,
      protein_g: 6,
      carbs_g: 42,
      fat_g: 17,
      fiber_g: 1,
      sugar_g: 32,
      sodium_mg: 140,
    },
  },
];

export const scandinavianRecipes = generateCuisineRecipes(configs);

// ── Additional Scandinavian recipes ──────────────────────────────────────────

const additionalScandinavianConfigs: CuisineRecipeConfig[] = [
  {
    title: 'Rødgrød med Fløde',
    description: 'Classic Danish red fruit porridge with cream — a beloved summer dessert.',
    cuisine: 'Scandinavian',
    prep_minutes: 10,
    cook_minutes: 15,
    servings: 6,
    calories: 180,
    ingredients: [
      { name: 'mixed red berries (strawberry, raspberry, rhubarb)', quantity: '4', unit: 'cups' },
      { name: 'sugar', quantity: '1/2', unit: 'cup' },
      { name: 'cornstarch', quantity: '2', unit: 'tbsp' },
      { name: 'vanilla', quantity: '1', unit: 'tsp' },
      { name: 'cream', quantity: '1', unit: 'cup' },
    ],
    steps: [
      'Simmer berries with sugar and vanilla until soft.',
      'Dissolve cornstarch in cold water, add to berries.',
      'Cook until thickened and glossy.',
      'Pour into bowls and chill.',
      'Whip cream lightly.',
      'Serve cold with cream poured on top.',
    ],
    tags: ['scandinavian', 'dessert', 'berries', 'danish', 'summer'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 180,
      protein_g: 2,
      carbs_g: 34,
      fat_g: 6,
      fiber_g: 3,
      sugar_g: 24,
      sodium_mg: 20,
    },
  },
  {
    title: 'Frikadeller',
    description:
      'Danish meatballs made with pork and veal, pan-fried and served with potatoes and gravy.',
    cuisine: 'Scandinavian',
    prep_minutes: 15,
    cook_minutes: 10,
    servings: 4,
    calories: 320,
    ingredients: [
      { name: 'ground pork', quantity: '1/2', unit: 'lb' },
      { name: 'ground veal', quantity: '1/2', unit: 'lb' },
      { name: 'onion', quantity: '1', unit: 'grated' },
      { name: 'egg', quantity: '1', unit: 'large' },
      { name: 'milk', quantity: '1/4', unit: 'cup' },
      { name: 'flour', quantity: '2', unit: 'tbsp' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Mix pork, veal, onion, egg, milk, flour, salt, and pepper.',
      'Shape into oval patties.',
      'Pan-fry in butter until golden on both sides.',
      'Make gravy from the pan drippings.',
      'Serve with boiled potatoes and pickled red cabbage.',
    ],
    tags: ['scandinavian', 'meatballs', 'danish', 'pork', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 22,
      carbs_g: 10,
      fat_g: 20,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 420,
    },
  },
  {
    title: 'Pyttipanna',
    description: 'Swedish hash of diced potatoes, meat, and onion, topped with a fried egg.',
    cuisine: 'Scandinavian',
    prep_minutes: 10,
    cook_minutes: 15,
    servings: 4,
    calories: 340,
    ingredients: [
      { name: 'potato', quantity: '4', unit: 'diced' },
      { name: 'leftover meat', quantity: '1', unit: 'cup, diced' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
      { name: 'egg', quantity: '4', unit: 'fried' },
      { name: 'pickled beetroot', quantity: '1/2', unit: 'cup' },
    ],
    steps: [
      'Fry diced potatoes in butter until golden and crispy.',
      'Add onion and cook until soft.',
      'Add diced meat and heat through.',
      'Season with salt and pepper.',
      'Serve topped with a fried egg.',
      'Accompany with pickled beetroot.',
    ],
    tags: ['scandinavian', 'hash', 'potato', 'swedish', 'breakfast'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 340,
      protein_g: 18,
      carbs_g: 32,
      fat_g: 16,
      fiber_g: 3,
      sugar_g: 3,
      sodium_mg: 380,
    },
  },
  {
    title: 'Rugbrød',
    description: 'Dense Danish sourdough rye bread — the foundation of every Danish lunch.',
    cuisine: 'Scandinavian',
    prep_minutes: 20,
    cook_minutes: 60,
    servings: 12,
    calories: 120,
    ingredients: [
      { name: 'rye flour', quantity: '3', unit: 'cups' },
      { name: 'rye sourdough starter', quantity: '1', unit: 'cup' },
      { name: 'water', quantity: '2', unit: 'cups' },
      { name: 'sunflower seeds', quantity: '1/4', unit: 'cup' },
      { name: 'flax seeds', quantity: '2', unit: 'tbsp' },
      { name: 'salt', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Mix rye flour, sourdough starter, water, seeds, and salt.',
      'Let ferment 12-24 hours.',
      'Pour into a loaf pan.',
      'Bake at 350°F for 60 minutes.',
      'Cool completely before slicing.',
      'Serve with butter, cheese, or liver pâté.',
    ],
    tags: ['scandinavian', 'bread', 'rye', 'danish', 'sourdough'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 120,
      protein_g: 4,
      carbs_g: 22,
      fat_g: 2,
      fiber_g: 4,
      sugar_g: 1,
      sodium_mg: 180,
    },
  },
  {
    title: 'Smörgåstårta',
    description:
      'Swedish sandwich cake — layers of bread with creamy fillings, decorated like a cake.',
    cuisine: 'Scandinavian',
    prep_minutes: 30,
    cook_minutes: 0,
    servings: 10,
    calories: 280,
    ingredients: [
      { name: 'white bread slices', quantity: '20', unit: 'pieces' },
      { name: 'cream cheese', quantity: '1', unit: 'cup' },
      { name: 'smoked salmon', quantity: '8', unit: 'oz' },
      { name: 'shrimp', quantity: '1/2', unit: 'lb' },
      { name: 'cucumber', quantity: '1', unit: 'sliced' },
      { name: 'dill', quantity: '1/4', unit: 'cup' },
      { name: 'lemon', quantity: '1', unit: 'wedges' },
    ],
    steps: [
      'Layer bread with cream cheese and fillings (salmon, shrimp, cucumber).',
      'Build 3-4 layers like a cake.',
      'Frost the outside with cream cheese.',
      'Decorate with shrimp, salmon, cucumber, dill, and lemon.',
      'Chill for 2 hours.',
      'Slice and serve as a centerpiece for a party.',
    ],
    tags: ['scandinavian', 'sandwich', 'cake', 'swedish', 'party'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 14,
      carbs_g: 28,
      fat_g: 12,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 580,
    },
  },
  {
    title: 'Klappgröt',
    description:
      'Swedish whipped berry porridge — lingonberries whipped into fluffy rice porridge.',
    cuisine: 'Scandinavian',
    prep_minutes: 5,
    cook_minutes: 30,
    servings: 4,
    calories: 220,
    ingredients: [
      { name: 'rice porridge', quantity: '2', unit: 'cups, cooked' },
      { name: 'lingonberries', quantity: '1', unit: 'cup' },
      { name: 'sugar', quantity: '1/4', unit: 'cup' },
      { name: 'milk', quantity: '1/2', unit: 'cup' },
    ],
    steps: [
      'Cook rice in milk until very soft.',
      'Whip lingonberries with sugar until fluffy.',
      'Fold berry mixture into the rice porridge.',
      'Chill until set.',
      'Serve with cold milk poured over.',
    ],
    tags: ['scandinavian', 'dessert', 'berries', 'swedish', 'porridge'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 220,
      protein_g: 4,
      carbs_g: 40,
      fat_g: 4,
      fiber_g: 2,
      sugar_g: 22,
      sodium_mg: 60,
    },
  },
  {
    title: 'Lohikeitto',
    description: 'Finnish salmon soup with potatoes, leeks, and dill in a creamy broth.',
    cuisine: 'Scandinavian',
    prep_minutes: 10,
    cook_minutes: 20,
    servings: 6,
    calories: 260,
    ingredients: [
      { name: 'salmon fillet', quantity: '1', unit: 'lb, cubed' },
      { name: 'potato', quantity: '3', unit: 'diced' },
      { name: 'leek', quantity: '2', unit: 'sliced' },
      { name: 'cream', quantity: '1', unit: 'cup' },
      { name: 'dill', quantity: '1/4', unit: 'cup' },
      { name: 'fish stock', quantity: '4', unit: 'cups' },
      { name: 'butter', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Sauté leek in butter.',
      'Add fish stock and potato. Simmer until potato is tender.',
      'Add salmon cubes and cook 5 minutes.',
      'Stir in cream and dill.',
      'Season with salt, pepper, and a squeeze of lemon.',
      'Serve with rye bread.',
    ],
    tags: ['scandinavian', 'soup', 'salmon', 'finnish', 'creamy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 260,
      protein_g: 22,
      carbs_g: 18,
      fat_g: 12,
      fiber_g: 2,
      sugar_g: 2,
      sodium_mg: 480,
    },
  },
  {
    title: 'Kjøttkaker',
    description: 'Norwegian meat cakes in brown gravy with potatoes and lingonberry sauce.',
    cuisine: 'Scandinavian',
    prep_minutes: 15,
    cook_minutes: 20,
    servings: 4,
    calories: 380,
    ingredients: [
      { name: 'ground beef', quantity: '1', unit: 'lb' },
      { name: 'ground pork', quantity: '1/2', unit: 'lb' },
      { name: 'onion', quantity: '1', unit: 'grated' },
      { name: 'egg', quantity: '1', unit: 'large' },
      { name: 'breadcrumbs', quantity: '2', unit: 'tbsp' },
      { name: 'brown gravy', quantity: '2', unit: 'cups' },
      { name: 'lingonberry sauce', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Mix beef, pork, onion, egg, breadcrumbs, milk, salt, and pepper.',
      'Form into oval patties.',
      'Pan-fry in butter until golden on both sides.',
      'Make brown gravy from pan drippings.',
      'Simmer meat cakes in gravy for 10 minutes.',
      'Serve with boiled potatoes and lingonberry sauce.',
    ],
    tags: ['scandinavian', 'meatballs', 'norwegian', 'gravy', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 26,
      carbs_g: 14,
      fat_g: 24,
      fiber_g: 1,
      sugar_g: 3,
      sodium_mg: 580,
    },
  },
  {
    title: 'Prinsesstårta',
    description: 'Swedish princess cake — sponge, custard, raspberry, and green marzipan dome.',
    cuisine: 'Scandinavian',
    prep_minutes: 30,
    cook_minutes: 25,
    servings: 10,
    calories: 320,
    ingredients: [
      { name: 'sponge cake', quantity: '1', unit: '9-inch round' },
      { name: 'pastry cream', quantity: '2', unit: 'cups' },
      { name: 'whipped cream', quantity: '2', unit: 'cups' },
      { name: 'raspberry jam', quantity: '1/2', unit: 'cup' },
      { name: 'green marzipan', quantity: '1', unit: 'lb' },
      { name: 'powdered sugar', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Split sponge into 3 layers.',
      'Layer: sponge, raspberry jam, custard, sponge, whipped cream dome.',
      'Cover the dome with more whipped cream.',
      'Roll out green marzipan and drape over the dome.',
      'Smooth and trim. Dust with powdered sugar.',
      'Garnish with a marzipan rose.',
    ],
    tags: ['scandinavian', 'dessert', 'cake', 'marzipan', 'swedish'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 6,
      carbs_g: 42,
      fat_g: 14,
      fiber_g: 1,
      sugar_g: 28,
      sodium_mg: 120,
    },
  },
  {
    title: 'Lefse',
    description: 'Soft Norwegian flatbread made with potato, served with butter and sugar.',
    cuisine: 'Scandinavian',
    prep_minutes: 20,
    cook_minutes: 5,
    servings: 12,
    calories: 100,
    ingredients: [
      { name: 'mashed potato', quantity: '2', unit: 'cups' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
      { name: 'flour', quantity: '1', unit: 'cup' },
      { name: 'cream', quantity: '1/4', unit: 'cup' },
      { name: 'sugar', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Mix cooled mashed potato with butter, cream, and salt.',
      'Add flour to make a soft dough.',
      'Roll very thin on a floured board.',
      'Cook on a dry griddle until lightly spotted on both sides.',
      'Spread with butter and sugar, roll up.',
      'Serve warm.',
    ],
    tags: ['scandinavian', 'flatbread', 'potato', 'norwegian', 'traditional'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 100,
      protein_g: 2,
      carbs_g: 16,
      fat_g: 3,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 80,
    },
  },
];

export const scandinavianAdditionalRecipes = generateCuisineRecipes(additionalScandinavianConfigs);
