import type { CuisineRecipeConfig } from './types';
import { generateCuisineRecipes } from './types';

const configs: CuisineRecipeConfig[] = [
  {
    title: 'Southern Fried Chicken',
    description:
      'Crispy, golden buttermilk-brined fried chicken — the crown jewel of Southern cooking.',
    cuisine: 'Southern US',
    prep_minutes: 30,
    cook_minutes: 25,
    servings: 6,
    calories: 520,
    ingredients: [
      { name: 'chicken pieces', quantity: '3', unit: 'lb, cut up' },
      { name: 'buttermilk', quantity: '2', unit: 'cups' },
      { name: 'all-purpose flour', quantity: '2', unit: 'cups' },
      { name: 'cornstarch', quantity: '1/4', unit: 'cup' },
      { name: 'paprika', quantity: '1', unit: 'tbsp' },
      { name: 'garlic powder', quantity: '1', unit: 'tsp' },
      { name: 'onion powder', quantity: '1', unit: 'tsp' },
      { name: 'cayenne pepper', quantity: '1/2', unit: 'tsp' },
      { name: 'salt', quantity: '1', unit: 'tbsp' },
      { name: 'peanut oil', quantity: '3', unit: 'cups, for frying' },
    ],
    steps: [
      'Soak chicken in buttermilk with salt for at least 4 hours or overnight in the fridge.',
      'Mix flour, cornstarch, paprika, garlic powder, onion powder, cayenne, and salt in a large bowl.',
      'Remove chicken from buttermilk, letting excess drip off.',
      'Dredge each piece in the seasoned flour, pressing firmly to coat.',
      'Let coated chicken rest 10 minutes while oil heats to 350°F.',
      'Fry in batches, skin side down first, 12–15 minutes turning once until golden and cooked to 165°F.',
      'Drain on a wire rack set over a sheet pan; rest 5 minutes before serving.',
    ],
    tags: ['southern', 'fried-chicken', 'comfort-food', 'classic'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 520,
      protein_g: 38,
      carbs_g: 28,
      fat_g: 26,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 780,
    },
  },
  {
    title: 'Chicken and Sausage Gumbo',
    description:
      'A rich, dark roux-based stew with chicken, andouille sausage, and the "holy trinity" of celery, bell pepper, and onion.',
    cuisine: 'Southern US',
    prep_minutes: 30,
    cook_minutes: 60,
    servings: 8,
    calories: 420,
    ingredients: [
      { name: 'vegetable oil', quantity: '1/2', unit: 'cup' },
      { name: 'all-purpose flour', quantity: '1/2', unit: 'cup' },
      { name: 'chicken thighs', quantity: '2', unit: 'lb, bone-in' },
      { name: 'andouille sausage', quantity: '1', unit: 'lb, sliced' },
      { name: 'onion', quantity: '2', unit: 'large, diced' },
      { name: 'celery', quantity: '3', unit: 'stalks, diced' },
      { name: 'green bell pepper', quantity: '1', unit: 'large, diced' },
      { name: 'garlic', quantity: '4', unit: 'cloves, minced' },
      { name: 'chicken broth', quantity: '6', unit: 'cups' },
      { name: 'diced tomatoes', quantity: '1', unit: '14.5-oz can' },
      { name: 'okra', quantity: '1', unit: 'cup, sliced' },
      { name: 'filé powder', quantity: '1', unit: 'tbsp' },
      { name: 'thyme', quantity: '1', unit: 'tsp' },
      { name: 'bay leaves', quantity: '2', unit: 'leaves' },
      { name: 'Cajun seasoning', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Make a dark roux: heat oil in a Dutch oven, whisk in flour, and stir constantly over medium-low heat until deep brown (20–25 min).',
      'Add onion, celery, bell pepper, and garlic; cook 5 minutes.',
      'Add sliced andouille and brown 3 minutes.',
      'Add chicken thighs, broth, tomatoes, thyme, bay leaves, and Cajun seasoning.',
      'Bring to a boil, then reduce heat and simmer 40 minutes.',
      'Remove chicken, shred the meat, discard bones, and return to pot.',
      'Add okra and cook 10 more minutes.',
      'Remove from heat, stir in filé powder, and serve over white rice.',
    ],
    tags: ['southern', 'gumbo', 'creole', 'stew', 'cajun'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 32,
      carbs_g: 18,
      fat_g: 26,
      fiber_g: 3,
      sugar_g: 4,
      sodium_mg: 1050,
    },
  },
  {
    title: 'Jambalaya',
    description:
      'A one-pot Creole rice dish loaded with chicken, sausage, and shrimp — the soul of Louisiana.',
    cuisine: 'Southern US',
    prep_minutes: 20,
    cook_minutes: 45,
    servings: 8,
    calories: 480,
    ingredients: [
      { name: 'chicken thighs', quantity: '1', unit: 'lb, diced' },
      { name: 'andouille sausage', quantity: '3/4', unit: 'lb, sliced' },
      { name: 'shrimp', quantity: '1/2', unit: 'lb, peeled' },
      { name: 'long-grain rice', quantity: '2', unit: 'cups' },
      { name: 'onion', quantity: '1', unit: 'large, diced' },
      { name: 'celery', quantity: '2', unit: 'stalks, diced' },
      { name: 'green bell pepper', quantity: '1', unit: 'diced' },
      { name: 'garlic', quantity: '3', unit: 'cloves, minced' },
      { name: 'diced tomatoes', quantity: '1', unit: '14.5-oz can' },
      { name: 'chicken broth', quantity: '3', unit: 'cups' },
      { name: 'Cajun seasoning', quantity: '2', unit: 'tbsp' },
      { name: 'thyme', quantity: '1', unit: 'tsp' },
      { name: 'hot sauce', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Brown chicken and sausage in a Dutch oven; remove and set aside.',
      'Sauté onion, celery, bell pepper, and garlic 5 minutes.',
      'Add rice and Cajun seasoning; stir to toast rice 2 minutes.',
      'Add broth, tomatoes, thyme, and hot sauce; bring to a boil.',
      'Return chicken and sausage to the pot.',
      'Cover, reduce heat, and simmer 20 minutes until rice is tender.',
      'Add shrimp on top, cover, and cook 5 more minutes until pink.',
      'Fluff with a fork and serve hot.',
    ],
    tags: ['southern', 'jambalaya', 'creole', 'rice', 'one-pot'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 480,
      protein_g: 34,
      carbs_g: 42,
      fat_g: 18,
      fiber_g: 2,
      sugar_g: 4,
      sodium_mg: 920,
    },
  },
  {
    title: 'Biscuits and Sausage Gravy',
    description:
      'Flaky buttermilk biscuits smothered in creamy, peppery sausage gravy — a Southern breakfast icon.',
    cuisine: 'Southern US',
    prep_minutes: 15,
    cook_minutes: 20,
    servings: 6,
    calories: 450,
    ingredients: [
      { name: 'all-purpose flour', quantity: '2', unit: 'cups' },
      { name: 'baking powder', quantity: '1', unit: 'tbsp' },
      { name: 'baking soda', quantity: '1/4', unit: 'tsp' },
      { name: 'cold butter', quantity: '1/4', unit: 'lb, cubed' },
      { name: 'buttermilk', quantity: '3/4', unit: 'cup' },
      { name: 'pork sausage', quantity: '1', unit: 'lb, ground' },
      { name: 'all-purpose flour (gravy)', quantity: '3', unit: 'tbsp' },
      { name: 'whole milk', quantity: '2', unit: 'cups' },
      { name: 'black pepper', quantity: '1', unit: 'tbsp, coarsely ground' },
      { name: 'salt', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Preheat oven to 450°F. Whisk flour, baking powder, baking soda, and salt.',
      'Cut in cold butter until mixture resembles coarse crumbs.',
      'Stir in buttermilk until just combined; do not overwork.',
      'Turn onto floured surface, fold dough 4–5 times, pat to 1-inch thick.',
      'Cut biscuits with a 2.5-inch cutter; place on a baking sheet.',
      'Bake 12–14 minutes until golden.',
      'Meanwhile, brown sausage in a skillet, breaking into crumbles.',
      'Sprinkle flour over sausage, cook 1 minute, then gradually whisk in milk.',
      'Simmer until thickened, stir in pepper and salt, and serve over split biscuits.',
    ],
    tags: ['southern', 'biscuits', 'gravy', 'breakfast', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 450,
      protein_g: 18,
      carbs_g: 34,
      fat_g: 28,
      fiber_g: 1,
      sugar_g: 4,
      sodium_mg: 890,
    },
  },
  {
    title: 'Shrimp and Grits',
    description:
      'Creamy stone-ground grits topped with bacon, shrimp, and a scampi-style sauce — Low Country perfection.',
    cuisine: 'Southern US',
    prep_minutes: 15,
    cook_minutes: 25,
    servings: 4,
    calories: 490,
    ingredients: [
      { name: 'stone-ground grits', quantity: '1', unit: 'cup' },
      { name: 'water', quantity: '4', unit: 'cups' },
      { name: 'heavy cream', quantity: '1/4', unit: 'cup' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
      { name: 'sharp cheddar', quantity: '1/2', unit: 'cup, shredded' },
      { name: 'large shrimp', quantity: '1', unit: 'lb, peeled & deveined' },
      { name: 'bacon', quantity: '4', unit: 'slices, chopped' },
      { name: 'garlic', quantity: '3', unit: 'cloves, minced' },
      { name: 'lemon juice', quantity: '2', unit: 'tbsp' },
      { name: 'hot sauce', quantity: '1', unit: 'tsp' },
      { name: 'green onion', quantity: '2', unit: 'stalks, sliced' },
    ],
    steps: [
      'Bring water to a boil, whisk in grits, reduce heat, and cook 20–25 minutes, stirring often.',
      'Stir in cream, butter, and cheddar; season with salt and pepper.',
      'Meanwhile, cook bacon in a skillet until crisp; remove and set aside.',
      'Sauté shrimp in bacon drippings 2 minutes per side until pink.',
      'Add garlic, lemon juice, and hot sauce; toss 30 seconds.',
      'Spoon grits into bowls, top with shrimp and sauce, and garnish with bacon and green onion.',
    ],
    tags: ['southern', 'shrimp', 'grits', 'low-country', 'seafood'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 490,
      protein_g: 30,
      carbs_g: 36,
      fat_g: 24,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 820,
    },
  },
  {
    title: 'Red Beans and Rice',
    description:
      'Slow-simmered kidney beans with smoked sausage and Creole seasoning served over fluffy white rice.',
    cuisine: 'Southern US',
    prep_minutes: 15,
    cook_minutes: 120,
    servings: 6,
    calories: 410,
    ingredients: [
      { name: 'dried red kidney beans', quantity: '1', unit: 'lb, soaked' },
      { name: 'smoked sausage', quantity: '3/4', unit: 'lb, sliced' },
      { name: 'onion', quantity: '1', unit: 'large, diced' },
      { name: 'celery', quantity: '2', unit: 'stalks, diced' },
      { name: 'green bell pepper', quantity: '1', unit: 'diced' },
      { name: 'garlic', quantity: '4', unit: 'cloves, minced' },
      { name: 'bay leaves', quantity: '2', unit: 'leaves' },
      { name: 'thyme', quantity: '1', unit: 'tsp' },
      { name: 'Cajun seasoning', quantity: '1', unit: 'tbsp' },
      { name: 'chicken broth', quantity: '4', unit: 'cups' },
      { name: 'white rice', quantity: '3', unit: 'cups, cooked' },
    ],
    steps: [
      'Sauté sausage slices until browned; remove and set aside.',
      'Cook onion, celery, bell pepper, and garlic in the same pot 5 minutes.',
      'Add soaked beans, broth, bay leaves, thyme, and Cajun seasoning.',
      'Bring to a boil, then reduce heat and simmer 1.5–2 hours until beans are tender.',
      'Mash some beans against the side of the pot to thicken the broth.',
      'Return sausage to the pot, season to taste, and serve over white rice.',
    ],
    tags: ['southern', 'beans', 'rice', 'cajun', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 410,
      protein_g: 24,
      carbs_g: 48,
      fat_g: 12,
      fiber_g: 12,
      sugar_g: 3,
      sodium_mg: 780,
    },
  },
  {
    title: "Shrimp Po' Boy",
    description:
      'Crispy cornmeal-fried shrimp piled into a French baguette with lettuce, tomato, pickles, and remoulade.',
    cuisine: 'Southern US',
    prep_minutes: 20,
    cook_minutes: 10,
    servings: 4,
    calories: 540,
    ingredients: [
      { name: 'large shrimp', quantity: '1', unit: 'lb, peeled' },
      { name: 'buttermilk', quantity: '1', unit: 'cup' },
      { name: 'cornmeal', quantity: '1', unit: 'cup' },
      { name: 'all-purpose flour', quantity: '1/2', unit: 'cup' },
      { name: 'Cajun seasoning', quantity: '1', unit: 'tbsp' },
      { name: 'peanut oil', quantity: '2', unit: 'cups, for frying' },
      { name: 'French baguette', quantity: '1', unit: 'loaf, split' },
      { name: 'shredded lettuce', quantity: '1', unit: 'cup' },
      { name: 'tomato', quantity: '1', unit: 'large, sliced' },
      { name: 'dill pickles', quantity: '6', unit: 'slices' },
      { name: 'mayonnaise', quantity: '1/4', unit: 'cup' },
      { name: 'hot sauce', quantity: '1', unit: 'tbsp' },
      { name: 'Dijon mustard', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Soak shrimp in buttermilk 15 minutes.',
      'Mix cornmeal, flour, and Cajun seasoning in a shallow bowl.',
      'Drain shrimp, dredge in cornmeal mixture, and fry at 375°F until golden (2–3 min).',
      'Mix mayonnaise, hot sauce, and Dijon to make remoulade.',
      'Toast baguette halves lightly.',
      'Spread remoulade on both halves, layer lettuce, tomato, pickles, and fried shrimp.',
      'Close sandwich, cut in half, and serve.',
    ],
    tags: ['southern', 'po-boy', 'sandwich', 'shrimp', 'new-orleans'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 540,
      protein_g: 28,
      carbs_g: 52,
      fat_g: 24,
      fiber_g: 3,
      sugar_g: 5,
      sodium_mg: 1100,
    },
  },
  {
    title: 'Crawfish Boil',
    description:
      'A festive Louisiana boil of crawfish, corn, potatoes, and sausage seasoned with Cajun spices.',
    cuisine: 'Southern US',
    prep_minutes: 20,
    cook_minutes: 20,
    servings: 8,
    calories: 380,
    ingredients: [
      { name: 'live crawfish', quantity: '5', unit: 'lb, purged' },
      { name: 'small red potatoes', quantity: '2', unit: 'lb' },
      { name: 'corn on the cob', quantity: '4', unit: 'ears, halved' },
      { name: 'smoked sausage', quantity: '1', unit: 'lb, sliced' },
      { name: 'onion', quantity: '2', unit: 'halved' },
      { name: 'garlic', quantity: '2', unit: 'heads, whole' },
      { name: 'lemon', quantity: '3', unit: 'halved' },
      { name: 'Cajun boil seasoning', quantity: '1/2', unit: 'cup' },
      { name: 'bay leaves', quantity: '4', unit: 'leaves' },
    ],
    steps: [
      'Bring a large pot of water with boil seasoning, bay leaves, and halved lemons to a rolling boil.',
      'Add potatoes and onions; cook 10 minutes.',
      'Add sausage and corn; cook 5 minutes.',
      'Add crawfish, stir well, and cook 5 minutes until tails curl.',
      'Turn off heat, cover, and let soak 15 minutes to absorb seasoning.',
      'Drain and spread on a newspaper-lined table; serve family-style.',
    ],
    tags: ['southern', 'crawfish', 'boil', 'cajun', 'louisiana'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 30,
      carbs_g: 32,
      fat_g: 14,
      fiber_g: 3,
      sugar_g: 4,
      sodium_mg: 1350,
    },
  },
  {
    title: 'Chicken Fried Steak',
    description:
      'Tenderized beef steak coated in seasoned flour, fried crispy, and smothered in creamy pepper gravy.',
    cuisine: 'Southern US',
    prep_minutes: 15,
    cook_minutes: 20,
    servings: 4,
    calories: 560,
    ingredients: [
      { name: 'cube steak', quantity: '4', unit: 'pieces (4 oz each)' },
      { name: 'all-purpose flour', quantity: '1', unit: 'cup' },
      { name: 'cornmeal', quantity: '1/4', unit: 'cup' },
      { name: 'paprika', quantity: '1', unit: 'tsp' },
      { name: 'garlic powder', quantity: '1', unit: 'tsp' },
      { name: 'onion powder', quantity: '1', unit: 'tsp' },
      { name: 'buttermilk', quantity: '1', unit: 'cup' },
      { name: 'egg', quantity: '1', unit: 'beaten' },
      { name: 'vegetable oil', quantity: '1/2', unit: 'cup, for frying' },
      { name: 'whole milk', quantity: '2', unit: 'cups' },
      { name: 'black pepper', quantity: '2', unit: 'tsp' },
    ],
    steps: [
      'Mix flour, cornmeal, paprika, garlic powder, onion powder, salt, and pepper in a dish.',
      'Combine buttermilk and egg in another dish.',
      'Dip each steak in buttermilk mixture, then dredge in seasoned flour.',
      'Fry steaks in oil over medium heat, 3–4 minutes per side until golden.',
      'Remove steaks; keep 2 tbsp drippings in the skillet.',
      'Whisk flour into drippings, cook 1 minute, then slowly whisk in milk.',
      'Simmer gravy until thickened, season with pepper, and pour over steaks.',
    ],
    tags: ['southern', 'chicken-fried-steak', 'gravy', 'comfort-food', 'texas'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 560,
      protein_g: 32,
      carbs_g: 30,
      fat_g: 34,
      fiber_g: 1,
      sugar_g: 4,
      sodium_mg: 720,
    },
  },
  {
    title: 'Collard Greens',
    description:
      'Long-simmered collard greens with smoked turkey — a soul-food staple full of flavor and pot likker.',
    cuisine: 'Southern US',
    prep_minutes: 15,
    cook_minutes: 90,
    servings: 6,
    calories: 180,
    ingredients: [
      { name: 'collard greens', quantity: '2', unit: 'lb, stemmed & chopped' },
      { name: 'smoked turkey leg', quantity: '1', unit: 'large' },
      { name: 'onion', quantity: '1', unit: 'large, diced' },
      { name: 'garlic', quantity: '4', unit: 'cloves, minced' },
      { name: 'chicken broth', quantity: '4', unit: 'cups' },
      { name: 'apple cider vinegar', quantity: '2', unit: 'tbsp' },
      { name: 'red pepper flakes', quantity: '1/2', unit: 'tsp' },
      { name: 'sugar', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Wash collards thoroughly in multiple changes of water; strip stems and chop leaves.',
      'Brown smoked turkey leg in a large pot; add onion and garlic.',
      'Add broth, vinegar, red pepper flakes, and sugar; bring to a boil.',
      'Add collards, pushing them down into the liquid.',
      'Reduce heat, cover, and simmer 60–90 minutes until very tender.',
      'Remove turkey, shred meat, return to pot, and season to taste.',
      'Serve with pot likker (the cooking broth) spooned over cornbread.',
    ],
    tags: ['southern', 'collard-greens', 'soul-food', 'vegetables', 'side-dish'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 180,
      protein_g: 18,
      carbs_g: 12,
      fat_g: 8,
      fiber_g: 6,
      sugar_g: 2,
      sodium_mg: 650,
    },
  },
  {
    title: "Hoppin' John",
    description:
      "Black-eyed peas and rice with bacon — the traditional Southern New Year's dish for good luck.",
    cuisine: 'Southern US',
    prep_minutes: 10,
    cook_minutes: 45,
    servings: 6,
    calories: 320,
    ingredients: [
      { name: 'black-eyed peas', quantity: '1', unit: 'lb, dried or 2 cans' },
      { name: 'bacon', quantity: '6', unit: 'slices, chopped' },
      { name: 'onion', quantity: '1', unit: 'medium, diced' },
      { name: 'celery', quantity: '2', unit: 'stalks, diced' },
      { name: 'garlic', quantity: '2', unit: 'cloves, minced' },
      { name: 'long-grain rice', quantity: '1.5', unit: 'cups' },
      { name: 'chicken broth', quantity: '3', unit: 'cups' },
      { name: 'thyme', quantity: '1/2', unit: 'tsp' },
      { name: 'hot sauce', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Cook bacon in a pot until crisp; remove and set aside.',
      'Sauté onion and celery in bacon drippings 5 minutes; add garlic.',
      'Add black-eyed peas, broth, and thyme; bring to a boil.',
      'Reduce heat and simmer 30–40 minutes until peas are tender.',
      'Meanwhile, cook rice separately according to package directions.',
      'Stir cooked rice into the peas, add hot sauce, and top with crumbled bacon.',
    ],
    tags: ['southern', 'black-eyed-peas', 'rice', 'new-years', 'soul-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 18,
      carbs_g: 42,
      fat_g: 8,
      fiber_g: 8,
      sugar_g: 3,
      sodium_mg: 580,
    },
  },
  {
    title: 'Banana Pudding',
    description:
      'Layers of vanilla custard, sliced bananas, and Nilla wafers — the ultimate Southern dessert.',
    cuisine: 'Southern US',
    prep_minutes: 20,
    cook_minutes: 10,
    servings: 8,
    calories: 340,
    ingredients: [
      { name: 'sugar', quantity: '3/4', unit: 'cup' },
      { name: 'cornstarch', quantity: '3', unit: 'tbsp' },
      { name: 'salt', quantity: '1/4', unit: 'tsp' },
      { name: 'whole milk', quantity: '3', unit: 'cups' },
      { name: 'egg yolks', quantity: '4', unit: 'large' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
      { name: 'vanilla extract', quantity: '2', unit: 'tsp' },
      { name: 'bananas', quantity: '4', unit: 'sliced' },
      { name: 'vanilla wafers', quantity: '1', unit: '12-oz box' },
    ],
    steps: [
      'Whisk sugar, cornstarch, and salt in a saucepan; gradually whisk in milk.',
      'Cook over medium heat, stirring constantly, until thickened (5–7 min).',
      'Temper egg yolks with a ladle of hot custard, then stir yolks back into the pot.',
      'Cook 2 more minutes, stirring; remove from heat and stir in butter and vanilla.',
      'Layer wafers, banana slices, and custard in a trifle dish; repeat layers.',
      'Top with remaining wafers, cover, and refrigerate at least 4 hours.',
    ],
    tags: ['southern', 'banana-pudding', 'dessert', 'comfort-food', 'classic'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 340,
      protein_g: 6,
      carbs_g: 52,
      fat_g: 12,
      fiber_g: 2,
      sugar_g: 36,
      sodium_mg: 280,
    },
  },
  {
    title: 'Peach Cobbler',
    description:
      'Juicy Southern peaches baked under a golden, biscuit-like cobbler crust with a caramelized sugar topping.',
    cuisine: 'Southern US',
    prep_minutes: 15,
    cook_minutes: 45,
    servings: 8,
    calories: 380,
    ingredients: [
      { name: 'fresh peaches', quantity: '4', unit: 'lb, sliced' },
      { name: 'sugar', quantity: '1', unit: 'cup, divided' },
      { name: 'lemon juice', quantity: '1', unit: 'tbsp' },
      { name: 'cinnamon', quantity: '1/2', unit: 'tsp' },
      { name: 'all-purpose flour', quantity: '1', unit: 'cup' },
      { name: 'baking powder', quantity: '1', unit: 'tsp' },
      { name: 'salt', quantity: '1/4', unit: 'tsp' },
      { name: 'milk', quantity: '3/4', unit: 'cup' },
      { name: 'butter', quantity: '1/4', unit: 'cup, melted' },
    ],
    steps: [
      'Preheat oven to 375°F. Toss peaches with 1/2 cup sugar, lemon juice, and cinnamon.',
      'Melt butter in a 9×13 baking dish in the oven.',
      'Whisk flour, remaining 1/2 cup sugar, baking powder, and salt.',
      'Stir in milk until just combined; pour batter over melted butter (do not stir).',
      'Spoon peaches evenly over the batter.',
      'Bake 40–45 minutes until golden and bubbly.',
      'Cool 15 minutes and serve warm with vanilla ice cream.',
    ],
    tags: ['southern', 'peach-cobbler', 'dessert', 'fruit', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 4,
      carbs_g: 62,
      fat_g: 14,
      fiber_g: 3,
      sugar_g: 42,
      sodium_mg: 220,
    },
  },
  {
    title: 'Sweet Tea',
    description:
      'The house wine of the South — strong black tea sweetened with a simple syrup and served ice cold.',
    cuisine: 'Southern US',
    prep_minutes: 5,
    cook_minutes: 5,
    servings: 8,
    calories: 90,
    ingredients: [
      { name: 'black tea bags', quantity: '6', unit: 'bags' },
      { name: 'water', quantity: '8', unit: 'cups' },
      { name: 'sugar', quantity: '1', unit: 'cup' },
      { name: 'baking soda', quantity: '1/8', unit: 'tsp' },
      { name: 'lemon', quantity: '1', unit: 'sliced' },
      { name: 'ice', quantity: '4', unit: 'cups' },
    ],
    steps: [
      'Bring 4 cups water to a boil; remove from heat and add tea bags.',
      'Steep 5 minutes, then remove bags (do not squeeze).',
      'Add baking soda to prevent clouding; stir.',
      'Dissolve sugar in 1 cup hot water to make simple syrup.',
      'Combine tea, simple syrup, and remaining 3 cups cold water in a pitcher.',
      'Refrigerate until cold; serve over ice with lemon slices.',
    ],
    tags: ['southern', 'sweet-tea', 'beverage', 'drink', 'classic'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 90,
      protein_g: 0,
      carbs_g: 23,
      fat_g: 0,
      fiber_g: 0,
      sugar_g: 22,
      sodium_mg: 5,
    },
  },
  {
    title: 'Cornbread Dressing',
    description:
      'Crumbled cornbread baked with celery, onion, herbs, and broth — the essential Southern holiday side.',
    cuisine: 'Southern US',
    prep_minutes: 20,
    cook_minutes: 45,
    servings: 8,
    calories: 280,
    ingredients: [
      { name: 'crumbled cornbread', quantity: '6', unit: 'cups' },
      { name: 'celery', quantity: '3', unit: 'stalks, diced' },
      { name: 'onion', quantity: '1', unit: 'large, diced' },
      { name: 'butter', quantity: '4', unit: 'tbsp' },
      { name: 'chicken broth', quantity: '2', unit: 'cups' },
      { name: 'sage', quantity: '1', unit: 'tbsp, dried' },
      { name: 'thyme', quantity: '1', unit: 'tsp' },
      { name: 'eggs', quantity: '2', unit: 'beaten' },
      { name: 'salt', quantity: '1', unit: 'tsp' },
      { name: 'black pepper', quantity: '1/2', unit: 'tsp' },
    ],
    steps: [
      'Sauté celery and onion in butter until soft (5–7 min).',
      'Crumble cornbread into a large bowl; add sautéed vegetables.',
      'Add sage, thyme, salt, and pepper; toss to combine.',
      'Pour in broth gradually until mixture is moist but not soggy.',
      'Stir in beaten eggs.',
      'Transfer to a buttered baking dish and bake at 350°F for 40–45 minutes until golden.',
    ],
    tags: ['southern', 'cornbread', 'dressing', 'stuffing', 'thanksgiving'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 8,
      carbs_g: 36,
      fat_g: 12,
      fiber_g: 3,
      sugar_g: 4,
      sodium_mg: 680,
    },
  },
  {
    title: 'Crawfish Étouffée',
    description:
      'Tender crawfish tails smothered in a rich, buttery Creole sauce served over rice.',
    cuisine: 'Southern US',
    prep_minutes: 15,
    cook_minutes: 30,
    servings: 4,
    calories: 380,
    ingredients: [
      { name: 'butter', quantity: '1/2', unit: 'cup' },
      { name: 'all-purpose flour', quantity: '1/4', unit: 'cup' },
      { name: 'onion', quantity: '1', unit: 'large, diced' },
      { name: 'celery', quantity: '2', unit: 'stalks, diced' },
      { name: 'green bell pepper', quantity: '1', unit: 'diced' },
      { name: 'garlic', quantity: '3', unit: 'cloves, minced' },
      { name: 'crawfish tails', quantity: '1', unit: 'lb, peeled' },
      { name: 'chicken broth', quantity: '1.5', unit: 'cups' },
      { name: 'Worcestershire sauce', quantity: '1', unit: 'tbsp' },
      { name: 'hot sauce', quantity: '1', unit: 'tsp' },
      { name: 'green onion', quantity: '3', unit: 'stalks, sliced' },
      { name: 'white rice', quantity: '3', unit: 'cups, cooked' },
    ],
    steps: [
      'Melt butter in a Dutch oven, whisk in flour, and cook a blond roux 3–4 minutes.',
      'Add onion, celery, bell pepper, and garlic; cook 5 minutes.',
      'Pour in broth, Worcestershire, and hot sauce; simmer 15 minutes.',
      'Add crawfish tails and cook 5 minutes until heated through.',
      'Stir in green onion, season to taste, and serve over rice.',
    ],
    tags: ['southern', 'etouffee', 'crawfish', 'creole', 'louisiana'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 26,
      carbs_g: 24,
      fat_g: 20,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 720,
    },
  },
  {
    title: 'Beignets',
    description:
      'Pillowy fried dough squares buried under a mountain of powdered sugar — the taste of the French Quarter.',
    cuisine: 'Southern US',
    prep_minutes: 20,
    cook_minutes: 10,
    servings: 6,
    calories: 260,
    ingredients: [
      { name: 'all-purpose flour', quantity: '2', unit: 'cups' },
      { name: 'sugar', quantity: '1/4', unit: 'cup' },
      { name: 'salt', quantity: '1/2', unit: 'tsp' },
      { name: 'instant yeast', quantity: '1', unit: 'packet' },
      { name: 'evaporated milk', quantity: '1/2', unit: 'cup, warm' },
      { name: 'water', quantity: '1/4', unit: 'cup, warm' },
      { name: 'egg', quantity: '1', unit: 'large' },
      { name: 'butter', quantity: '2', unit: 'tbsp, melted' },
      { name: 'vegetable oil', quantity: '3', unit: 'cups, for frying' },
      { name: 'powdered sugar', quantity: '1', unit: 'cup, for dusting' },
    ],
    steps: [
      'Dissolve yeast in warm water and evaporated milk; let stand 5 minutes.',
      'Mix flour, sugar, and salt; add yeast mixture, egg, and melted butter.',
      'Knead until smooth, cover, and let rise 1 hour.',
      'Roll dough to 1/4-inch thickness and cut into 2.5-inch squares.',
      'Fry in 360°F oil, turning once, until puffed and golden (2–3 min).',
      'Drain on paper towels and immediately dust generously with powdered sugar.',
    ],
    tags: ['southern', 'beignets', 'dessert', 'new-orleans', 'french-quarter'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 260,
      protein_g: 5,
      carbs_g: 40,
      fat_g: 9,
      fiber_g: 1,
      sugar_g: 20,
      sodium_mg: 180,
    },
  },
  {
    title: 'Pralines',
    description:
      'Sweet, crumbly candy made with pecans, brown sugar, and cream — a New Orleans confection classic.',
    cuisine: 'Southern US',
    prep_minutes: 5,
    cook_minutes: 15,
    servings: 12,
    calories: 210,
    ingredients: [
      { name: 'pecan halves', quantity: '2', unit: 'cups' },
      { name: 'brown sugar', quantity: '1.5', unit: 'cups' },
      { name: 'heavy cream', quantity: '1/2', unit: 'cup' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
      { name: 'vanilla extract', quantity: '1', unit: 'tsp' },
      { name: 'salt', quantity: '1/4', unit: 'tsp' },
    ],
    steps: [
      'Toast pecans lightly in a dry skillet; set aside.',
      'Combine brown sugar, cream, and butter in a saucepan over medium heat.',
      'Stir until sugar dissolves, then clip on a candy thermometer.',
      'Cook to 238°F (soft-ball stage) without stirring.',
      'Remove from heat, stir in vanilla and pecans, and beat until mixture thickens and loses its gloss.',
      'Spoon onto parchment paper in rounds; let cool until set.',
    ],
    tags: ['southern', 'pralines', 'candy', 'pecans', 'new-orleans', 'dessert'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 210,
      protein_g: 2,
      carbs_g: 26,
      fat_g: 12,
      fiber_g: 1,
      sugar_g: 22,
      sodium_mg: 60,
    },
  },
  {
    title: 'Fried Green Tomatoes',
    description:
      'Sliced firm green tomatoes coated in cornmeal and fried until crispy — a Southern appetizer icon.',
    cuisine: 'Southern US',
    prep_minutes: 15,
    cook_minutes: 10,
    servings: 4,
    calories: 220,
    ingredients: [
      { name: 'green tomatoes', quantity: '3', unit: 'large, sliced 1/4-inch' },
      { name: 'buttermilk', quantity: '1', unit: 'cup' },
      { name: 'all-purpose flour', quantity: '1/2', unit: 'cup' },
      { name: 'cornmeal', quantity: '1/2', unit: 'cup' },
      { name: 'paprika', quantity: '1/2', unit: 'tsp' },
      { name: 'cayenne pepper', quantity: '1/4', unit: 'tsp' },
      { name: 'salt', quantity: '1', unit: 'tsp' },
      { name: 'vegetable oil', quantity: '1/2', unit: 'cup, for frying' },
    ],
    steps: [
      'Season tomato slices with salt and let sit 10 minutes; pat dry.',
      'Mix flour, cornmeal, paprika, cayenne, and salt in a shallow dish.',
      'Dip each slice in buttermilk, then dredge in cornmeal mixture.',
      'Fry in oil at 375°F, 2–3 minutes per side until golden.',
      'Drain on a wire rack; serve with remoulade or ranch dressing.',
    ],
    tags: ['southern', 'fried-green-tomatoes', 'appetizer', 'vegetarian', 'side-dish'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 220,
      protein_g: 4,
      carbs_g: 24,
      fat_g: 12,
      fiber_g: 2,
      sugar_g: 4,
      sodium_mg: 480,
    },
  },
  {
    title: 'Macaroni and Cheese',
    description:
      'Baked Southern-style mac and cheese with a creamy custard base and crispy breadcrumb topping.',
    cuisine: 'Southern US',
    prep_minutes: 15,
    cook_minutes: 30,
    servings: 8,
    calories: 420,
    ingredients: [
      { name: 'elbow macaroni', quantity: '1', unit: 'lb' },
      { name: 'sharp cheddar cheese', quantity: '2', unit: 'cups, shredded' },
      { name: 'colby cheese', quantity: '1', unit: 'cup, shredded' },
      { name: 'whole milk', quantity: '2', unit: 'cups' },
      { name: 'eggs', quantity: '2', unit: 'beaten' },
      { name: 'butter', quantity: '4', unit: 'tbsp, melted' },
      { name: 'sour cream', quantity: '1/4', unit: 'cup' },
      { name: 'mustard powder', quantity: '1/2', unit: 'tsp' },
      { name: 'salt', quantity: '1', unit: 'tsp' },
      { name: 'black pepper', quantity: '1/2', unit: 'tsp' },
    ],
    steps: [
      'Cook macaroni 1 minute less than package directions; drain.',
      'Whisk together milk, eggs, melted butter, sour cream, mustard, salt, and pepper.',
      'Layer half the macaroni in a buttered baking dish, top with half the cheese; repeat.',
      'Pour custard mixture evenly over the top.',
      'Bake at 350°F for 25–30 minutes until set and golden on top.',
      'Let rest 10 minutes before serving.',
    ],
    tags: ['southern', 'mac-and-cheese', 'comfort-food', 'side-dish', 'baked'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 20,
      carbs_g: 38,
      fat_g: 22,
      fiber_g: 1,
      sugar_g: 5,
      sodium_mg: 620,
    },
  },
  {
    title: 'Cornbread',
    description:
      'Skillet-baked Southern cornbread with a crispy crust — slightly sweet, perfectly crumbly.',
    cuisine: 'Southern US',
    prep_minutes: 10,
    cook_minutes: 25,
    servings: 8,
    calories: 210,
    ingredients: [
      { name: 'yellow cornmeal', quantity: '1.5', unit: 'cups' },
      { name: 'all-purpose flour', quantity: '1/2', unit: 'cup' },
      { name: 'sugar', quantity: '2', unit: 'tbsp' },
      { name: 'baking powder', quantity: '1', unit: 'tbsp' },
      { name: 'salt', quantity: '1/2', unit: 'tsp' },
      { name: 'buttermilk', quantity: '1', unit: 'cup' },
      { name: 'egg', quantity: '1', unit: 'large' },
      { name: 'butter', quantity: '1/4', unit: 'cup, melted' },
      { name: 'vegetable oil', quantity: '2', unit: 'tbsp, for skillet' },
    ],
    steps: [
      'Preheat oven to 400°F. Place a cast-iron skillet with oil in the oven to heat.',
      'Whisk cornmeal, flour, sugar, baking powder, and salt.',
      'Combine buttermilk, egg, and melted butter; stir into dry ingredients until just mixed.',
      'Carefully pour batter into the hot, oiled skillet.',
      'Bake 20–25 minutes until golden and a toothpick comes out clean.',
      'Let cool 5 minutes, then turn out onto a plate or serve from the skillet.',
    ],
    tags: ['southern', 'cornbread', 'bread', 'side-dish', 'skillet'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 210,
      protein_g: 5,
      carbs_g: 30,
      fat_g: 8,
      fiber_g: 2,
      sugar_g: 5,
      sodium_mg: 380,
    },
  },
  {
    title: 'Blackened Catfish',
    description:
      'Catfish fillets coated in spicy Cajun seasoning and seared in a blazing-hot cast-iron skillet.',
    cuisine: 'Southern US',
    prep_minutes: 10,
    cook_minutes: 8,
    servings: 4,
    calories: 290,
    ingredients: [
      { name: 'catfish fillets', quantity: '4', unit: 'pieces (6 oz each)' },
      { name: 'paprika', quantity: '2', unit: 'tbsp' },
      { name: 'cayenne pepper', quantity: '1', unit: 'tsp' },
      { name: 'garlic powder', quantity: '1', unit: 'tsp' },
      { name: 'onion powder', quantity: '1', unit: 'tsp' },
      { name: 'dried thyme', quantity: '1', unit: 'tsp' },
      { name: 'dried oregano', quantity: '1', unit: 'tsp' },
      { name: 'salt', quantity: '1', unit: 'tsp' },
      { name: 'black pepper', quantity: '1/2', unit: 'tsp' },
      { name: 'butter', quantity: '4', unit: 'tbsp, melted' },
    ],
    steps: [
      'Mix paprika, cayenne, garlic powder, onion powder, thyme, oregano, salt, and pepper.',
      'Brush catfish fillets with melted butter on both sides.',
      'Press the seasoning blend onto both sides of each fillet.',
      'Heat a cast-iron skillet until smoking hot.',
      'Sear fillets 2–3 minutes per side until the seasoning blackens and fish flakes easily.',
      'Serve immediately with lemon wedges and tartar sauce.',
    ],
    tags: ['southern', 'catfish', 'blackened', 'cajun', 'seafood'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 290,
      protein_g: 28,
      carbs_g: 4,
      fat_g: 18,
      fiber_g: 1,
      sugar_g: 1,
      sodium_mg: 520,
    },
  },
  {
    title: 'Pimento Cheese',
    description:
      'The "caviar of the South" — a creamy, tangy spread of cheddar, pimentos, and mayo.',
    cuisine: 'Southern US',
    prep_minutes: 10,
    cook_minutes: 0,
    servings: 8,
    calories: 160,
    ingredients: [
      { name: 'sharp cheddar cheese', quantity: '2', unit: 'cups, freshly grated' },
      { name: 'pimentos', quantity: '1', unit: '4-oz jar, diced' },
      { name: 'mayonnaise', quantity: '1/2', unit: 'cup' },
      { name: 'cream cheese', quantity: '2', unit: 'oz, softened' },
      { name: 'garlic powder', quantity: '1/4', unit: 'tsp' },
      { name: 'onion powder', quantity: '1/4', unit: 'tsp' },
      { name: 'hot sauce', quantity: '1/2', unit: 'tsp' },
      { name: 'black pepper', quantity: '1/4', unit: 'tsp' },
    ],
    steps: [
      'Grate cheddar cheese by hand (pre-shredded has anti-caking agents).',
      'Beat cream cheese and mayo until smooth.',
      'Fold in grated cheddar, diced pimentos, garlic powder, onion powder, hot sauce, and pepper.',
      'Refrigerate at least 1 hour for flavors to meld.',
      'Serve with crackers, celery, or as a sandwich spread.',
    ],
    tags: ['southern', 'pimento-cheese', 'spread', 'appetizer', 'vegetarian'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 160,
      protein_g: 8,
      carbs_g: 2,
      fat_g: 14,
      fiber_g: 0,
      sugar_g: 1,
      sodium_mg: 320,
    },
  },
  {
    title: 'Sweet Potato Pie',
    description:
      "A silky spiced sweet potato filling in a flaky crust — the South's answer to pumpkin pie.",
    cuisine: 'Southern US',
    prep_minutes: 20,
    cook_minutes: 55,
    servings: 8,
    calories: 340,
    ingredients: [
      { name: 'sweet potatoes', quantity: '2', unit: 'lb, baked & mashed' },
      { name: 'unbaked pie crust', quantity: '1', unit: '9-inch' },
      { name: 'sugar', quantity: '3/4', unit: 'cup' },
      { name: 'butter', quantity: '4', unit: 'tbsp, melted' },
      { name: 'eggs', quantity: '3', unit: 'large' },
      { name: 'evaporated milk', quantity: '1/2', unit: 'cup' },
      { name: 'vanilla extract', quantity: '1', unit: 'tsp' },
      { name: 'cinnamon', quantity: '1', unit: 'tsp' },
      { name: 'nutmeg', quantity: '1/4', unit: 'tsp' },
      { name: 'salt', quantity: '1/4', unit: 'tsp' },
    ],
    steps: [
      'Bake sweet potatoes at 400°F until very soft (45–60 min); let cool, peel, and mash.',
      'Whisk mashed sweet potatoes, sugar, butter, eggs, milk, vanilla, cinnamon, nutmeg, and salt until smooth.',
      'Pour filling into the unbaked pie crust.',
      'Bake at 350°F for 50–55 minutes until set (center should jiggle slightly).',
      'Cool completely on a wire rack before slicing.',
      'Serve with whipped cream.',
    ],
    tags: ['southern', 'sweet-potato-pie', 'dessert', 'pie', 'thanksgiving'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 340,
      protein_g: 6,
      carbs_g: 46,
      fat_g: 15,
      fiber_g: 3,
      sugar_g: 28,
      sodium_mg: 280,
    },
  },
  {
    title: "Shepherd's Pie (Southern Style)",
    description:
      'A Southern twist with ground beef, vegetables, and a creamy mashed potato topping — hearty comfort food.',
    cuisine: 'Southern US',
    prep_minutes: 20,
    cook_minutes: 30,
    servings: 6,
    calories: 440,
    ingredients: [
      { name: 'ground beef', quantity: '1.5', unit: 'lb' },
      { name: 'onion', quantity: '1', unit: 'medium, diced' },
      { name: 'carrots', quantity: '2', unit: 'diced' },
      { name: 'peas', quantity: '1', unit: 'cup' },
      { name: 'garlic', quantity: '2', unit: 'cloves, minced' },
      { name: 'tomato paste', quantity: '2', unit: 'tbsp' },
      { name: 'beef broth', quantity: '1', unit: 'cup' },
      { name: 'Worcestershire sauce', quantity: '1', unit: 'tbsp' },
      { name: 'potatoes', quantity: '2', unit: 'lb, peeled & cubed' },
      { name: 'butter', quantity: '4', unit: 'tbsp' },
      { name: 'milk', quantity: '1/4', unit: 'cup' },
      { name: 'cheddar cheese', quantity: '1/2', unit: 'cup, shredded' },
    ],
    steps: [
      'Boil potatoes until tender; mash with butter, milk, salt, and pepper.',
      'Brown ground beef with onion, carrots, and garlic; drain excess fat.',
      'Stir in tomato paste, broth, Worcestershire, and peas; simmer 10 minutes.',
      'Transfer beef mixture to a baking dish; top with mashed potatoes.',
      'Sprinkle cheddar on top and use a fork to create ridges.',
      'Bake at 400°F for 20–25 minutes until golden and bubbly.',
    ],
    tags: ['southern', 'shepherds-pie', 'comfort-food', 'casserole', 'ground-beef'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 440,
      protein_g: 28,
      carbs_g: 32,
      fat_g: 22,
      fiber_g: 4,
      sugar_g: 5,
      sodium_mg: 680,
    },
  },
  {
    title: 'Deviled Eggs',
    description:
      'Classic Southern deviled eggs with a creamy, tangy yolk filling and a sprinkle of paprika.',
    cuisine: 'Southern US',
    prep_minutes: 15,
    cook_minutes: 12,
    servings: 6,
    calories: 130,
    ingredients: [
      { name: 'eggs', quantity: '6', unit: 'large' },
      { name: 'mayonnaise', quantity: '3', unit: 'tbsp' },
      { name: 'Dijon mustard', quantity: '1', unit: 'tsp' },
      { name: 'apple cider vinegar', quantity: '1', unit: 'tsp' },
      { name: 'salt', quantity: '1/4', unit: 'tsp' },
      { name: 'black pepper', quantity: '1/8', unit: 'tsp' },
      { name: 'paprika', quantity: '1/4', unit: 'tsp, for garnish' },
    ],
    steps: [
      'Place eggs in a pot of cold water; bring to a boil, then cover and remove from heat.',
      'Let sit 12 minutes, then transfer to an ice bath.',
      'Peel eggs, halve lengthwise, and remove yolks to a bowl.',
      'Mash yolks with mayo, mustard, vinegar, salt, and pepper until smooth.',
      'Pipe or spoon filling back into the egg white halves.',
      'Dust with paprika and refrigerate until serving.',
    ],
    tags: ['southern', 'deviled-eggs', 'appetizer', 'vegetarian', 'classic'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 130,
      protein_g: 6,
      carbs_g: 1,
      fat_g: 11,
      fiber_g: 0,
      sugar_g: 0,
      sodium_mg: 180,
    },
  },
  {
    title: 'Fried Okra',
    description:
      'Sliced okra coated in cornmeal and fried until crunchy — a beloved Southern snack and side.',
    cuisine: 'Southern US',
    prep_minutes: 10,
    cook_minutes: 8,
    servings: 4,
    calories: 180,
    ingredients: [
      { name: 'fresh okra', quantity: '1', unit: 'lb, sliced 1/2-inch' },
      { name: 'buttermilk', quantity: '1/2', unit: 'cup' },
      { name: 'cornmeal', quantity: '3/4', unit: 'cup' },
      { name: 'all-purpose flour', quantity: '1/4', unit: 'cup' },
      { name: 'salt', quantity: '1', unit: 'tsp' },
      { name: 'cayenne pepper', quantity: '1/4', unit: 'tsp' },
      { name: 'vegetable oil', quantity: '1', unit: 'cup, for frying' },
    ],
    steps: [
      'Toss sliced okra in buttermilk to coat.',
      'Mix cornmeal, flour, salt, and cayenne in a bowl.',
      'Drain okra and dredge in cornmeal mixture, pressing to adhere.',
      'Fry in oil at 375°F in batches, 3–4 minutes until golden and crispy.',
      'Drain on paper towels; serve hot with hot sauce or ranch.',
    ],
    tags: ['southern', 'okra', 'fried', 'side-dish', 'vegetarian', 'snack'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 180,
      protein_g: 4,
      carbs_g: 22,
      fat_g: 9,
      fiber_g: 3,
      sugar_g: 2,
      sodium_mg: 420,
    },
  },
  {
    title: 'Country Ham and Red Eye Gravy',
    description:
      'Thick-cut salt-cured country ham with a pan sauce of coffee and drippings — a Southern breakfast tradition.',
    cuisine: 'Southern US',
    prep_minutes: 5,
    cook_minutes: 10,
    servings: 4,
    calories: 240,
    ingredients: [
      { name: 'country ham slices', quantity: '4', unit: 'pieces (3 oz each)' },
      { name: 'butter', quantity: '1', unit: 'tbsp' },
      { name: 'strong coffee', quantity: '1/2', unit: 'cup' },
      { name: 'brown sugar', quantity: '1', unit: 'tbsp' },
      { name: 'black pepper', quantity: '1/2', unit: 'tsp' },
    ],
    steps: [
      'Score ham slices around the edges to prevent curling.',
      'Fry ham in a hot skillet 3–4 minutes per side until browned; remove to a plate.',
      'Add butter to the skillet, then pour in coffee, scraping up browned bits.',
      'Add brown sugar and pepper; simmer 2–3 minutes until reduced slightly.',
      'Pour red eye gravy over the ham and serve with biscuits.',
    ],
    tags: ['southern', 'ham', 'red-eye-gravy', 'breakfast', 'country'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 240,
      protein_g: 22,
      carbs_g: 2,
      fat_g: 16,
      fiber_g: 0,
      sugar_g: 1,
      sodium_mg: 1400,
    },
  },
];

export const southernUsRecipes = generateCuisineRecipes(configs);
