import type { CuisineRecipeConfig } from './types';
import { generateCuisineRecipes } from './types';

const configs: CuisineRecipeConfig[] = [
  {
    title: 'Paella',
    description:
      'Saffron-infused rice with chicken, seafood, and vegetables in a wide pan with a crispy socarrat.',
    cuisine: 'Spanish',
    prep_minutes: 25,
    cook_minutes: 35,
    servings: 8,
    calories: 420,
    ingredients: [
      { name: 'bomba rice', quantity: '2', unit: 'cups' },
      { name: 'saffron', quantity: '1', unit: 'pinch' },
      { name: 'chicken', quantity: '1', unit: 'lb, pieces' },
      { name: 'shrimp', quantity: '1/2', unit: 'lb' },
      { name: 'mussels', quantity: '1/2', unit: 'lb' },
      { name: 'chorizo', quantity: '4', unit: 'oz, sliced' },
      { name: 'bell pepper', quantity: '1', unit: 'diced' },
      { name: 'chicken broth', quantity: '4', unit: 'cups' },
      { name: 'green beans', quantity: '1', unit: 'cup' },
      { name: 'lemon', quantity: '2', unit: 'wedges' },
    ],
    steps: [
      'Brown chicken and chorizo in a wide paella pan. Set aside.',
      'Sauté bell pepper and green beans.',
      'Add rice, saffron-infused broth, and seasonings. Stir once.',
      'Nestle chicken and chorizo back in. Simmer without stirring 20 minutes.',
      'Add shrimp and mussels on top. Cook 5-8 minutes until mussels open.',
      'Crank heat for 2 minutes for socarrat (crispy bottom). Rest 5 minutes, serve with lemon.',
    ],
    tags: ['spanish', 'rice', 'seafood', 'saffron', 'one-pan'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 28,
      carbs_g: 40,
      fat_g: 14,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 860,
    },
  },
  {
    title: 'Tapas Tortilla Española',
    description:
      'Classic Spanish potato omelette with onions, slowly cooked until golden and custardy.',
    cuisine: 'Spanish',
    prep_minutes: 10,
    cook_minutes: 25,
    servings: 6,
    calories: 220,
    ingredients: [
      { name: 'potato', quantity: '4', unit: 'medium, sliced thin' },
      { name: 'onion', quantity: '1', unit: 'large, sliced' },
      { name: 'egg', quantity: '6', unit: 'large' },
      { name: 'olive oil', quantity: '1', unit: 'cup' },
      { name: 'salt', quantity: '1/2', unit: 'tsp' },
    ],
    steps: [
      'Slowly cook potatoes and onion in olive oil on low heat until very soft, about 20 minutes.',
      'Drain excess oil. Beat eggs with salt.',
      'Combine potato-onion mixture with beaten eggs.',
      'Pour into a non-stick pan and cook on medium-low until set on bottom.',
      'Flip using a plate and cook the other side.',
      'Serve warm or at room temperature, cut into wedges.',
    ],
    tags: ['spanish', 'tapas', 'egg', 'potato', 'vegetarian'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 220,
      protein_g: 10,
      carbs_g: 18,
      fat_g: 12,
      fiber_g: 2,
      sugar_g: 2,
      sodium_mg: 280,
    },
  },
  {
    title: 'Gazpacho',
    description: 'Chilled tomato soup blended with cucumber, pepper, garlic, and sherry vinegar.',
    cuisine: 'Spanish',
    prep_minutes: 20,
    cook_minutes: 0,
    servings: 6,
    calories: 100,
    ingredients: [
      { name: 'tomato', quantity: '6', unit: 'ripe, quartered' },
      { name: 'cucumber', quantity: '1', unit: 'peeled, chunked' },
      { name: 'bell pepper', quantity: '1', unit: 'chunked' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
      { name: 'sherry vinegar', quantity: '2', unit: 'tbsp' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'stale bread', quantity: '1', unit: 'slice, soaked' },
      { name: 'onion', quantity: '1/4', unit: 'small' },
    ],
    steps: [
      'Soak bread in water until soft.',
      'Blend tomatoes, cucumber, pepper, garlic, onion, and soaked bread.',
      'Add sherry vinegar and olive oil while blending.',
      'Season with salt and pepper.',
      'Strain for a smoother texture (optional).',
      'Chill for at least 2 hours. Serve with diced vegetable garnish.',
    ],
    tags: ['spanish', 'soup', 'cold', 'tomato', 'vegan'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 100,
      protein_g: 2,
      carbs_g: 14,
      fat_g: 5,
      fiber_g: 3,
      sugar_g: 6,
      sodium_mg: 180,
    },
  },
  {
    title: 'Patatas Bravas',
    description: 'Crispy fried potato cubes served with spicy bravas sauce and aioli.',
    cuisine: 'Spanish',
    prep_minutes: 10,
    cook_minutes: 15,
    servings: 4,
    calories: 240,
    ingredients: [
      { name: 'potato', quantity: '4', unit: 'medium, cubed' },
      { name: 'olive oil', quantity: '1', unit: 'cup, for frying' },
      { name: 'paprika', quantity: '1', unit: 'tsp' },
      { name: 'cayenne', quantity: '1/4', unit: 'tsp' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
      { name: 'flour', quantity: '1', unit: 'tsp' },
      { name: 'vinegar', quantity: '1', unit: 'tbsp' },
      { name: 'mayonnaise', quantity: '3', unit: 'tbsp' },
    ],
    steps: [
      'Fry potato cubes in olive oil at 350°F until golden and crispy.',
      'Make bravas sauce: sauté garlic, add paprika, cayenne, flour, vinegar, and broth.',
      'Make aioli: mix mayo with minced garlic and lemon.',
      'Drain potatoes on paper towels.',
      'Plate potatoes and drizzle with both sauces.',
      'Serve immediately as a tapa.',
    ],
    tags: ['spanish', 'tapas', 'potato', 'spicy', 'fried'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 240,
      protein_g: 4,
      carbs_g: 28,
      fat_g: 14,
      fiber_g: 3,
      sugar_g: 2,
      sodium_mg: 380,
    },
  },
  {
    title: 'Churros',
    description:
      'Crispy fried dough sticks rolled in cinnamon sugar, served with thick chocolate dipping sauce.',
    cuisine: 'Spanish',
    prep_minutes: 10,
    cook_minutes: 10,
    servings: 6,
    calories: 260,
    ingredients: [
      { name: 'flour', quantity: '1', unit: 'cup' },
      { name: 'water', quantity: '1', unit: 'cup' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
      { name: 'sugar', quantity: '1/2', unit: 'cup' },
      { name: 'cinnamon', quantity: '1', unit: 'tsp' },
      { name: 'dark chocolate', quantity: '4', unit: 'oz, chopped' },
      { name: 'heavy cream', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Bring water, butter, and salt to a boil. Add flour all at once, stir vigorously.',
      'Pipe dough through a star tip into 350°F oil.',
      'Fry until golden and crispy, about 3-4 minutes.',
      'Drain and roll in cinnamon sugar while warm.',
      'Melt chocolate with cream for dipping sauce.',
      'Serve churros warm with chocolate sauce.',
    ],
    tags: ['spanish', 'dessert', 'fried', 'chocolate', 'cinnamon'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 260,
      protein_g: 3,
      carbs_g: 34,
      fat_g: 14,
      fiber_g: 1,
      sugar_g: 18,
      sodium_mg: 160,
    },
  },
  {
    title: 'Croquetas',
    description: 'Creamy béchamel croquettes with jamón, breaded and fried until golden.',
    cuisine: 'Spanish',
    prep_minutes: 20,
    cook_minutes: 10,
    servings: 6,
    calories: 220,
    ingredients: [
      { name: 'jamón serrano', quantity: '4', unit: 'oz, diced' },
      { name: 'butter', quantity: '3', unit: 'tbsp' },
      { name: 'flour', quantity: '3', unit: 'tbsp' },
      { name: 'milk', quantity: '1.5', unit: 'cups' },
      { name: 'egg', quantity: '2', unit: 'beaten' },
      { name: 'breadcrumbs', quantity: '1', unit: 'cup' },
      { name: 'nutmeg', quantity: '1', unit: 'pinch' },
    ],
    steps: [
      'Make thick béchamel: melt butter, add flour, whisk in milk until very thick.',
      'Add diced jamón and nutmeg. Season well.',
      'Spread on a tray, chill until firm.',
      'Shape into small cylinders. Dredge in flour, egg, and breadcrumbs.',
      'Deep fry at 350°F until golden.',
      'Drain and serve hot as a tapa.',
    ],
    tags: ['spanish', 'tapas', 'croquettes', 'fried', 'ham'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 220,
      protein_g: 8,
      carbs_g: 16,
      fat_g: 14,
      fiber_g: 0,
      sugar_g: 2,
      sodium_mg: 480,
    },
  },
  {
    title: 'Crema Catalana',
    description:
      'Spanish custard with a caramelized sugar top, flavored with lemon zest and cinnamon.',
    cuisine: 'Spanish',
    prep_minutes: 10,
    cook_minutes: 20,
    servings: 6,
    calories: 280,
    ingredients: [
      { name: 'milk', quantity: '2', unit: 'cups' },
      { name: 'egg yolk', quantity: '6', unit: 'large' },
      { name: 'sugar', quantity: '1/2', unit: 'cup' },
      { name: 'cornstarch', quantity: '2', unit: 'tbsp' },
      { name: 'lemon zest', quantity: '1', unit: 'strip' },
      { name: 'cinnamon stick', quantity: '1', unit: 'small' },
      { name: 'superfine sugar', quantity: '6', unit: 'tsp, for topping' },
    ],
    steps: [
      'Heat milk with lemon zest and cinnamon stick until simmering. Steep 10 minutes.',
      'Whisk egg yolks, sugar, and cornstarch.',
      'Temper hot milk into yolk mixture. Return to pan and cook until thickened.',
      'Strain into ramekins. Chill 4 hours.',
      'Sprinkle superfine sugar on top.',
      'Torch until caramelized. Serve.',
    ],
    tags: ['spanish', 'dessert', 'custard', 'caramelized', 'classic'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 4,
      carbs_g: 32,
      fat_g: 14,
      fiber_g: 0,
      sugar_g: 26,
      sodium_mg: 60,
    },
  },
  {
    title: 'Pimientos de Padrón',
    description: 'Blistered Spanish peppers fried in olive oil and sprinkled with coarse sea salt.',
    cuisine: 'Spanish',
    prep_minutes: 5,
    cook_minutes: 5,
    servings: 4,
    calories: 80,
    ingredients: [
      { name: 'Padrón peppers', quantity: '1', unit: 'lb' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'flaky sea salt', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Heat olive oil in a skillet over high heat.',
      'Add peppers in a single layer.',
      'Cook, turning, until blistered and charred on all sides.',
      'Transfer to a plate.',
      'Sprinkle generously with flaky sea salt.',
      'Serve immediately as a tapa.',
    ],
    tags: ['spanish', 'tapas', 'peppers', 'quick', 'vegan'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 80,
      protein_g: 2,
      carbs_g: 6,
      fat_g: 6,
      fiber_g: 2,
      sugar_g: 2,
      sodium_mg: 280,
    },
  },
  {
    title: 'Fabada Asturiana',
    description: 'Hearty Asturian bean stew with chorizo, morcilla, and pork shoulder.',
    cuisine: 'Spanish',
    prep_minutes: 15,
    cook_minutes: 120,
    servings: 8,
    calories: 480,
    ingredients: [
      { name: 'fabes beans', quantity: '1', unit: 'lb, soaked overnight' },
      { name: 'chorizo', quantity: '8', unit: 'oz' },
      { name: 'morcilla', quantity: '8', unit: 'oz' },
      { name: 'pork shoulder', quantity: '1', unit: 'lb, cubed' },
      { name: 'onion', quantity: '1', unit: 'quartered' },
      { name: 'garlic', quantity: '4', unit: 'cloves' },
      { name: 'saffron', quantity: '1', unit: 'pinch' },
      { name: 'parsley', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Soak beans overnight. Drain.',
      'Cover beans with cold water. Add all meats, onion, garlic, and saffron.',
      'Bring to a boil, then simmer very gently for 2 hours.',
      'Do not stir — shake the pot occasionally to avoid breaking beans.',
      'Add salt at the end. Remove onion and garlic.',
      'Serve in deep bowls with crusty bread.',
    ],
    tags: ['spanish', 'stew', 'beans', 'chorizo', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 480,
      protein_g: 32,
      carbs_g: 34,
      fat_g: 24,
      fiber_g: 10,
      sugar_g: 3,
      sodium_mg: 980,
    },
  },
  {
    title: 'Pan con Tomate',
    description: 'Toasted bread rubbed with garlic and ripe tomato, drizzled with olive oil.',
    cuisine: 'Spanish',
    prep_minutes: 5,
    cook_minutes: 3,
    servings: 4,
    calories: 150,
    ingredients: [
      { name: 'crusty bread', quantity: '4', unit: 'slices' },
      { name: 'ripe tomato', quantity: '2', unit: 'halved' },
      { name: 'garlic', quantity: '1', unit: 'clove, halved' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'salt', quantity: '1/4', unit: 'tsp' },
    ],
    steps: [
      'Toast bread slices until golden on both sides.',
      'Rub each slice with the cut side of garlic.',
      'Rub cut tomato halves vigorously over the bread.',
      'Drizzle generously with extra virgin olive oil.',
      'Sprinkle with salt.',
      'Serve immediately.',
    ],
    tags: ['spanish', 'tapas', 'bread', 'tomato', 'vegan'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 150,
      protein_g: 3,
      carbs_g: 22,
      fat_g: 6,
      fiber_g: 2,
      sugar_g: 2,
      sodium_mg: 240,
    },
  },
  {
    title: 'Albondigas',
    description: 'Spanish meatballs in a saffron-scented tomato sauce, served as a tapa.',
    cuisine: 'Spanish',
    prep_minutes: 20,
    cook_minutes: 25,
    servings: 6,
    calories: 280,
    ingredients: [
      { name: 'ground beef', quantity: '1/2', unit: 'lb' },
      { name: 'ground pork', quantity: '1/2', unit: 'lb' },
      { name: 'breadcrumbs', quantity: '1/4', unit: 'cup' },
      { name: 'egg', quantity: '1', unit: 'beaten' },
      { name: 'garlic', quantity: '2', unit: 'cloves, minced' },
      { name: 'parsley', quantity: '2', unit: 'tbsp' },
      { name: 'tomato sauce', quantity: '2', unit: 'cups' },
      { name: 'saffron', quantity: '1', unit: 'pinch' },
      { name: 'white wine', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Mix beef, pork, breadcrumbs, egg, garlic, parsley, salt, and pepper. Form into balls.',
      'Brown meatballs in olive oil. Set aside.',
      'Sauté onion and garlic. Add wine, tomato sauce, and saffron.',
      'Return meatballs to the sauce.',
      'Simmer 20 minutes until meatballs are cooked through.',
      'Serve as a tapa with crusty bread.',
    ],
    tags: ['spanish', 'tapas', 'meatballs', 'tomato-sauce', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 20,
      carbs_g: 12,
      fat_g: 16,
      fiber_g: 1,
      sugar_g: 4,
      sodium_mg: 580,
    },
  },
  {
    title: 'Empanada Gallega',
    description:
      'Large Spanish savory pie filled with tuna, peppers, and a hard-boiled egg in a golden crust.',
    cuisine: 'Spanish',
    prep_minutes: 25,
    cook_minutes: 35,
    servings: 8,
    calories: 320,
    ingredients: [
      { name: 'pie dough', quantity: '2', unit: '9-inch rounds' },
      { name: 'tuna', quantity: '2', unit: 'cans (6 oz), drained' },
      { name: 'bell pepper', quantity: '2', unit: 'diced' },
      { name: 'onion', quantity: '1', unit: 'diced' },
      { name: 'tomato sauce', quantity: '1/2', unit: 'cup' },
      { name: 'hard-boiled egg', quantity: '2', unit: 'sliced' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'egg wash', quantity: '1', unit: 'egg, beaten' },
    ],
    steps: [
      'Sauté onion and pepper in olive oil until soft.',
      'Add tomato sauce and tuna. Season with paprika and salt.',
      'Line a baking sheet with bottom crust. Add filling and sliced egg.',
      'Cover with top crust, crimp edges, and cut steam vents.',
      'Brush with egg wash.',
      'Bake at 375°F for 30-35 minutes until golden.',
    ],
    tags: ['spanish', 'pie', 'tuna', 'savory', 'galician'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 16,
      carbs_g: 28,
      fat_g: 14,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 520,
    },
  },
];

export const spanishRecipes = generateCuisineRecipes(configs);

// ── Additional Spanish recipes ──────────────────────────────────────────────

const additionalSpanishConfigs: CuisineRecipeConfig[] = [
  {
    title: 'Paella Mixta',
    description: 'Mixed paella with chicken, seafood, and vegetables on saffron rice.',
    cuisine: 'Spanish',
    prep_minutes: 20,
    cook_minutes: 35,
    servings: 6,
    calories: 420,
    ingredients: [
      { name: 'bomba rice', quantity: '2', unit: 'cups' },
      { name: 'chicken thigh', quantity: '1', unit: 'lb' },
      { name: 'shrimp', quantity: '1/2', unit: 'lb' },
      { name: 'mussel', quantity: '1/2', unit: 'lb' },
      { name: 'saffron', quantity: '1', unit: 'pinch' },
      { name: 'bell pepper', quantity: '1', unit: 'sliced' },
      { name: 'green bean', quantity: '1', unit: 'cup' },
      { name: 'chicken broth', quantity: '4', unit: 'cups' },
    ],
    steps: [
      'Brown chicken in a paella pan.',
      'Add bell pepper and green beans.',
      'Add rice, saffron, and broth. Do not stir after this point.',
      'Add mussels and shrimp on top.',
      'Cook until rice is done and socarrat (crispy bottom) forms.',
      'Let rest 5 minutes before serving.',
    ],
    tags: ['spanish', 'paella', 'rice', 'seafood', 'saffron'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 28,
      carbs_g: 42,
      fat_g: 12,
      fiber_g: 2,
      sugar_g: 2,
      sodium_mg: 680,
    },
  },
  {
    title: 'Tortilla Española',
    description: 'Spanish potato omelette — thick, tender, and served at every tapas bar.',
    cuisine: 'Spanish',
    prep_minutes: 10,
    cook_minutes: 25,
    servings: 6,
    calories: 220,
    ingredients: [
      { name: 'potato', quantity: '4', unit: 'sliced thin' },
      { name: 'onion', quantity: '1', unit: 'sliced' },
      { name: 'egg', quantity: '6', unit: 'large' },
      { name: 'olive oil', quantity: '1/2', unit: 'cup' },
      { name: 'salt', quantity: '1/2', unit: 'tsp' },
    ],
    steps: [
      'Fry potato and onion in olive oil until very soft, not brown.',
      'Drain, mix with beaten eggs and salt.',
      'Pour into a non-stick pan. Cook on medium-low until set.',
      'Flip using a plate. Cook the other side.',
      'Should be soft in the center, not dry.',
      'Serve warm or at room temperature.',
    ],
    tags: ['spanish', 'omelette', 'potato', 'vegetarian', 'tapas'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 220,
      protein_g: 10,
      carbs_g: 18,
      fat_g: 12,
      fiber_g: 2,
      sugar_g: 1,
      sodium_mg: 280,
    },
  },
  {
    title: 'Gazpacho',
    description: 'Cold tomato soup blended with cucumber, pepper, garlic, and olive oil.',
    cuisine: 'Spanish',
    prep_minutes: 15,
    cook_minutes: 0,
    servings: 6,
    calories: 120,
    ingredients: [
      { name: 'tomato', quantity: '6', unit: 'ripe' },
      { name: 'cucumber', quantity: '1', unit: 'peeled' },
      { name: 'bell pepper', quantity: '1', unit: 'seeded' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
      { name: 'olive oil', quantity: '3', unit: 'tbsp' },
      { name: 'vinegar', quantity: '2', unit: 'tbsp' },
      { name: 'bread', quantity: '1', unit: 'slice, soaked' },
    ],
    steps: [
      'Soak bread in water.',
      'Blend tomato, cucumber, pepper, garlic, and soaked bread.',
      'Add olive oil and vinegar while blending.',
      'Season with salt.',
      'Chill for 2 hours.',
      'Serve with diced cucumber and croutons on top.',
    ],
    tags: ['spanish', 'soup', 'cold', 'tomato', 'summer'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 120,
      protein_g: 2,
      carbs_g: 12,
      fat_g: 8,
      fiber_g: 2,
      sugar_g: 6,
      sodium_mg: 180,
    },
  },
  {
    title: 'Patatas Bravas',
    description: 'Crispy fried potato cubes with a spicy brava sauce and aioli.',
    cuisine: 'Spanish',
    prep_minutes: 10,
    cook_minutes: 10,
    servings: 4,
    calories: 240,
    ingredients: [
      { name: 'potato', quantity: '4', unit: 'cubed' },
      { name: 'olive oil', quantity: '2', unit: 'cups, for frying' },
      { name: 'smoked paprika', quantity: '1', unit: 'tsp' },
      { name: 'cayenne', quantity: '1/4', unit: 'tsp' },
      { name: 'garlic', quantity: '2', unit: 'cloves' },
      { name: 'mayonnaise', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Fry potato cubes until golden and crispy.',
      'Make brava sauce: sauté garlic, add paprika, cayenne, and broth. Thicken.',
      'Make aioli: mix mayo with garlic.',
      'Plate potatoes.',
      'Drizzle with brava sauce and aioli.',
      'Serve immediately as a tapa.',
    ],
    tags: ['spanish', 'potato', 'tapas', 'spicy', 'fried'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 240,
      protein_g: 4,
      carbs_g: 28,
      fat_g: 12,
      fiber_g: 2,
      sugar_g: 1,
      sodium_mg: 380,
    },
  },
  {
    title: 'Churros con Chocolate',
    description: 'Fried dough sticks rolled in sugar, served with thick hot chocolate for dipping.',
    cuisine: 'Spanish',
    prep_minutes: 15,
    cook_minutes: 8,
    servings: 6,
    calories: 280,
    ingredients: [
      { name: 'water', quantity: '1', unit: 'cup' },
      { name: 'butter', quantity: '2', unit: 'tbsp' },
      { name: 'flour', quantity: '1', unit: 'cup' },
      { name: 'egg', quantity: '2', unit: 'large' },
      { name: 'sugar', quantity: '1/2', unit: 'cup, for coating' },
      { name: 'cinnamon', quantity: '1', unit: 'tsp' },
      { name: 'dark chocolate', quantity: '4', unit: 'oz' },
      { name: 'cream', quantity: '1/2', unit: 'cup' },
    ],
    steps: [
      'Bring water and butter to a boil. Add flour, stir vigorously.',
      'Cool slightly, beat in eggs.',
      'Pipe churros into hot oil. Fry until golden.',
      'Roll in cinnamon sugar.',
      'Melt chocolate with cream for dipping sauce.',
      'Serve churros with thick hot chocolate.',
    ],
    tags: ['spanish', 'dessert', 'churros', 'chocolate', 'fried'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 4,
      carbs_g: 36,
      fat_g: 14,
      fiber_g: 1,
      sugar_g: 18,
      sodium_mg: 120,
    },
  },
  {
    title: 'Crema Catalana',
    description: "Catalan custard with a caramelized sugar top — Spain's answer to crème brûlée.",
    cuisine: 'Spanish',
    prep_minutes: 10,
    cook_minutes: 20,
    servings: 6,
    calories: 240,
    ingredients: [
      { name: 'milk', quantity: '2', unit: 'cups' },
      { name: 'egg yolk', quantity: '5', unit: 'large' },
      { name: 'sugar', quantity: '1/2', unit: 'cup' },
      { name: 'lemon zest', quantity: '1', unit: 'strip' },
      { name: 'cinnamon stick', quantity: '1', unit: 'small' },
      { name: 'cornstarch', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Heat milk with lemon zest and cinnamon.',
      'Whisk yolks, sugar, and cornstarch.',
      'Temper hot milk into yolk mixture.',
      'Cook until thickened. Strain into ramekins.',
      'Chill 4 hours.',
      'Sprinkle sugar on top and torch until caramelized.',
    ],
    tags: ['spanish', 'dessert', 'custard', 'catalan', 'caramelized'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 240,
      protein_g: 5,
      carbs_g: 28,
      fat_g: 12,
      fiber_g: 0,
      sugar_g: 22,
      sodium_mg: 60,
    },
  },
  {
    title: 'Pimientos de Padrón',
    description: 'Blistered green peppers from Padrón — mostly mild, but some are very spicy!',
    cuisine: 'Spanish',
    prep_minutes: 2,
    cook_minutes: 5,
    servings: 4,
    calories: 80,
    ingredients: [
      { name: 'Padrón peppers', quantity: '1', unit: 'lb' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'flaky sea salt', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Heat olive oil in a pan until very hot.',
      'Add peppers in a single layer.',
      'Cook until blistered on all sides, about 4-5 minutes.',
      'Transfer to a plate.',
      'Sprinkle with flaky sea salt.',
      'Eat by the stem — "some are hot, some are not!"',
    ],
    tags: ['spanish', 'tapas', 'peppers', 'blistered', 'quick'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 80,
      protein_g: 1,
      carbs_g: 4,
      fat_g: 7,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 380,
    },
  },
  {
    title: 'Pan con Tomate',
    description: 'Catalan toasted bread rubbed with garlic, ripe tomato, and olive oil.',
    cuisine: 'Spanish',
    prep_minutes: 5,
    cook_minutes: 2,
    servings: 4,
    calories: 160,
    ingredients: [
      { name: 'rustic bread', quantity: '4', unit: 'thick slices' },
      { name: 'ripe tomato', quantity: '2', unit: 'halved' },
      { name: 'garlic', quantity: '1', unit: 'clove, halved' },
      { name: 'olive oil', quantity: '2', unit: 'tbsp' },
      { name: 'salt', quantity: '1/4', unit: 'tsp' },
    ],
    steps: [
      'Toast bread until golden.',
      'Rub cut garlic on the warm bread.',
      'Rub cut tomato on the bread, pressing to release juice and pulp.',
      'Drizzle with olive oil.',
      'Sprinkle with salt.',
      'Serve immediately.',
    ],
    tags: ['spanish', 'bread', 'tomato', 'catalan', 'simple'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 160,
      protein_g: 3,
      carbs_g: 22,
      fat_g: 6,
      fiber_g: 2,
      sugar_g: 2,
      sodium_mg: 280,
    },
  },
];

export const spanishAdditionalRecipes = generateCuisineRecipes(additionalSpanishConfigs);
