import type { CuisineRecipeConfig } from './types';
import { generateCuisineRecipes } from './types';

const configs: CuisineRecipeConfig[] = [
  {
    title: 'Pad Thai',
    description:
      'Stir-fried rice noodles with shrimp, egg, bean sprouts, peanuts, and tamarind sauce.',
    cuisine: 'Thai',
    prep_minutes: 15,
    cook_minutes: 8,
    servings: 4,
    calories: 380,
    ingredients: [
      { name: 'rice noodles', quantity: '8', unit: 'oz, flat' },
      { name: 'shrimp', quantity: '1/2', unit: 'lb' },
      { name: 'egg', quantity: '2', unit: 'large' },
      { name: 'bean sprouts', quantity: '1', unit: 'cup' },
      { name: 'peanuts', quantity: '1/4', unit: 'cup, crushed' },
      { name: 'tamarind paste', quantity: '2', unit: 'tbsp' },
      { name: 'fish sauce', quantity: '2', unit: 'tbsp' },
      { name: 'palm sugar', quantity: '1', unit: 'tbsp' },
      { name: 'lime', quantity: '2', unit: 'wedges' },
      { name: 'green onion', quantity: '4', unit: 'cut' },
    ],
    steps: [
      'Soak rice noodles in warm water 20 minutes. Drain.',
      'Make sauce: mix tamarind, fish sauce, and palm sugar.',
      'Stir-fry shrimp in a wok until pink. Push aside.',
      'Add egg, scramble. Add noodles and sauce. Toss.',
      'Add bean sprouts and green onion. Toss 30 seconds.',
      'Serve with crushed peanuts, lime wedges, and chili flakes.',
    ],
    tags: ['thai', 'noodles', 'shrimp', 'stir-fry', 'street-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 18,
      carbs_g: 48,
      fat_g: 10,
      fiber_g: 3,
      sugar_g: 8,
      sodium_mg: 860,
    },
  },
  {
    title: 'Green Curry',
    description:
      'Aromatic Thai green curry with coconut milk, chicken, bamboo shoots, and Thai basil.',
    cuisine: 'Thai',
    prep_minutes: 15,
    cook_minutes: 15,
    servings: 4,
    calories: 360,
    ingredients: [
      { name: 'green curry paste', quantity: '3', unit: 'tbsp' },
      { name: 'coconut milk', quantity: '2', unit: 'cans (14 oz)' },
      { name: 'chicken breast', quantity: '1', unit: 'lb, sliced' },
      { name: 'bamboo shoots', quantity: '1', unit: 'cup' },
      { name: 'Thai basil', quantity: '1', unit: 'cup' },
      { name: 'fish sauce', quantity: '2', unit: 'tbsp' },
      { name: 'palm sugar', quantity: '1', unit: 'tbsp' },
      { name: 'kaffir lime leaves', quantity: '4', unit: 'leaves' },
      { name: 'Thai eggplant', quantity: '4', unit: 'quartered' },
    ],
    steps: [
      'Fry curry paste in the cream of coconut milk until fragrant.',
      'Add chicken and cook until no longer pink.',
      'Add remaining coconut milk, bamboo shoots, and eggplant.',
      'Add fish sauce, palm sugar, and kaffir lime leaves.',
      'Simmer 10 minutes until vegetables are tender.',
      'Stir in Thai basil and serve with jasmine rice.',
    ],
    tags: ['thai', 'curry', 'coconut', 'chicken', 'spicy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 360,
      protein_g: 28,
      carbs_g: 10,
      fat_g: 24,
      fiber_g: 2,
      sugar_g: 4,
      sodium_mg: 820,
    },
  },
  {
    title: 'Tom Yum Soup',
    description: 'Hot and sour Thai soup with shrimp, lemongrass, galangal, and kaffir lime.',
    cuisine: 'Thai',
    prep_minutes: 10,
    cook_minutes: 10,
    servings: 4,
    calories: 180,
    ingredients: [
      { name: 'shrimp', quantity: '1/2', unit: 'lb' },
      { name: 'lemongrass', quantity: '3', unit: 'stalks, bruised' },
      { name: 'galangal', quantity: '3', unit: 'slices' },
      { name: 'kaffir lime leaves', quantity: '4', unit: 'leaves' },
      { name: 'mushroom', quantity: '1', unit: 'cup, sliced' },
      { name: 'chili', quantity: '3', unit: "bird's eye" },
      { name: 'lime juice', quantity: '3', unit: 'tbsp' },
      { name: 'fish sauce', quantity: '2', unit: 'tbsp' },
      { name: 'cilantro', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Boil lemongrass, galangal, and kaffir lime leaves in broth for 5 minutes.',
      'Add mushrooms and chilies.',
      'Add shrimp and cook until pink, about 2 minutes.',
      'Season with fish sauce and lime juice.',
      'Remove from heat.',
      'Serve in bowls topped with cilantro.',
    ],
    tags: ['thai', 'soup', 'shrimp', 'spicy', 'sour'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 180,
      protein_g: 18,
      carbs_g: 6,
      fat_g: 8,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 860,
    },
  },
  {
    title: 'Mango Sticky Rice',
    description: 'Sweet coconut-infused sticky rice served with ripe mango slices.',
    cuisine: 'Thai',
    prep_minutes: 10,
    cook_minutes: 30,
    servings: 4,
    calories: 320,
    ingredients: [
      { name: 'sticky rice', quantity: '1.5', unit: 'cups, soaked overnight' },
      { name: 'coconut milk', quantity: '1', unit: 'can (14 oz)' },
      { name: 'sugar', quantity: '1/2', unit: 'cup' },
      { name: 'salt', quantity: '1/4', unit: 'tsp' },
      { name: 'ripe mango', quantity: '2', unit: 'sliced' },
      { name: 'toasted sesame', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Steam soaked sticky rice for 20-25 minutes.',
      'Heat coconut milk with sugar and salt until dissolved.',
      'Pour most of the coconut sauce over hot sticky rice. Let absorb 15 minutes.',
      'Slice ripe mango.',
      'Mound sticky rice on plates, arrange mango alongside.',
      'Drizzle remaining coconut sauce and sprinkle sesame seeds.',
    ],
    tags: ['thai', 'dessert', 'mango', 'coconut', 'sticky-rice'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 4,
      carbs_g: 56,
      fat_g: 10,
      fiber_g: 2,
      sugar_g: 28,
      sodium_mg: 140,
    },
  },
  {
    title: 'Red Curry',
    description: 'Rich Thai red curry with coconut milk, vegetables, and your choice of protein.',
    cuisine: 'Thai',
    prep_minutes: 15,
    cook_minutes: 15,
    servings: 4,
    calories: 340,
    ingredients: [
      { name: 'red curry paste', quantity: '3', unit: 'tbsp' },
      { name: 'coconut milk', quantity: '2', unit: 'cans (14 oz)' },
      { name: 'chicken', quantity: '1', unit: 'lb, sliced' },
      { name: 'bamboo shoots', quantity: '1/2', unit: 'cup' },
      { name: 'bell pepper', quantity: '1', unit: 'sliced' },
      { name: 'Thai basil', quantity: '1/2', unit: 'cup' },
      { name: 'fish sauce', quantity: '2', unit: 'tbsp' },
      { name: 'palm sugar', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Fry curry paste in coconut cream until oil separates.',
      'Add chicken and cook until done.',
      'Add remaining coconut milk, bamboo shoots, and bell pepper.',
      'Season with fish sauce and palm sugar.',
      'Simmer 10 minutes.',
      'Stir in Thai basil and serve with jasmine rice.',
    ],
    tags: ['thai', 'curry', 'coconut', 'chicken', 'spicy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 340,
      protein_g: 26,
      carbs_g: 8,
      fat_g: 22,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 780,
    },
  },
  {
    title: 'Som Tum',
    description: 'Spicy green papaya salad with lime, fish sauce, peanuts, and dried shrimp.',
    cuisine: 'Thai',
    prep_minutes: 15,
    cook_minutes: 0,
    servings: 4,
    calories: 120,
    ingredients: [
      { name: 'green papaya', quantity: '2', unit: 'cups, shredded' },
      { name: 'green bean', quantity: '1/2', unit: 'cup, cut' },
      { name: 'tomato', quantity: '4', unit: 'cherry, halved' },
      { name: 'peanuts', quantity: '1/4', unit: 'cup, crushed' },
      { name: 'dried shrimp', quantity: '2', unit: 'tbsp' },
      { name: 'lime juice', quantity: '2', unit: 'tbsp' },
      { name: 'fish sauce', quantity: '2', unit: 'tbsp' },
      { name: 'palm sugar', quantity: '1', unit: 'tbsp' },
      { name: 'chili', quantity: '3', unit: "bird's eye, pounded" },
    ],
    steps: [
      'Pound chilies, garlic, and dried shrimp in a mortar.',
      'Add green beans and tomatoes, pound lightly.',
      'Add shredded papaya.',
      'Season with lime juice, fish sauce, and palm sugar.',
      'Toss well, adjusting the sweet-sour-salty balance.',
      'Top with crushed peanuts and serve.',
    ],
    tags: ['thai', 'salad', 'papaya', 'spicy', 'street-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 120,
      protein_g: 6,
      carbs_g: 14,
      fat_g: 4,
      fiber_g: 3,
      sugar_g: 6,
      sodium_mg: 680,
    },
  },
  {
    title: 'Massaman Curry',
    description:
      'Mild, rich Thai curry with potatoes, peanuts, and tender braised beef in coconut milk.',
    cuisine: 'Thai',
    prep_minutes: 15,
    cook_minutes: 60,
    servings: 6,
    calories: 420,
    ingredients: [
      { name: 'massaman curry paste', quantity: '3', unit: 'tbsp' },
      { name: 'beef chuck', quantity: '1.5', unit: 'lb, cubed' },
      { name: 'coconut milk', quantity: '2', unit: 'cans (14 oz)' },
      { name: 'potato', quantity: '2', unit: 'cubed' },
      { name: 'onion', quantity: '1', unit: 'quartered' },
      { name: 'peanuts', quantity: '1/4', unit: 'cup' },
      { name: 'fish sauce', quantity: '2', unit: 'tbsp' },
      { name: 'tamarind paste', quantity: '1', unit: 'tbsp' },
      { name: 'palm sugar', quantity: '1', unit: 'tbsp' },
      { name: 'cardamom', quantity: '3', unit: 'pods' },
    ],
    steps: [
      'Fry curry paste in coconut cream. Add beef and brown.',
      'Add coconut milk, potato, onion, and cardamom.',
      'Add fish sauce, tamarind, and palm sugar.',
      'Simmer covered for 1 hour until beef is very tender.',
      'Add peanuts in the last 10 minutes.',
      'Serve with jasmine rice or roti.',
    ],
    tags: ['thai', 'curry', 'beef', 'coconut', 'mild'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 420,
      protein_g: 30,
      carbs_g: 16,
      fat_g: 28,
      fiber_g: 3,
      sugar_g: 4,
      sodium_mg: 780,
    },
  },
  {
    title: 'Thai Basil Stir-Fry',
    description:
      'Wok-fried chicken with holy basil, chilies, garlic, and a savory oyster-soy sauce.',
    cuisine: 'Thai',
    prep_minutes: 10,
    cook_minutes: 5,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'chicken thigh', quantity: '1', unit: 'lb, minced' },
      { name: 'Thai basil', quantity: '2', unit: 'cups, packed' },
      { name: 'garlic', quantity: '6', unit: 'cloves, minced' },
      { name: 'chili', quantity: '4', unit: "bird's eye, sliced" },
      { name: 'oyster sauce', quantity: '2', unit: 'tbsp' },
      { name: 'soy sauce', quantity: '1', unit: 'tbsp' },
      { name: 'fish sauce', quantity: '1', unit: 'tbsp' },
      { name: 'sugar', quantity: '1', unit: 'tsp' },
    ],
    steps: [
      'Heat oil in a wok over very high heat.',
      'Add garlic and chilies, stir-fry 15 seconds.',
      'Add minced chicken, break apart, cook until done.',
      'Add oyster sauce, soy sauce, fish sauce, and sugar.',
      'Toss in Thai basil and stir until just wilted.',
      'Serve over steamed rice with a fried egg on top.',
    ],
    tags: ['thai', 'stir-fry', 'chicken', 'basil', 'spicy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 26,
      carbs_g: 6,
      fat_g: 16,
      fiber_g: 1,
      sugar_g: 3,
      sodium_mg: 860,
    },
  },
  {
    title: 'Tom Kha Gai',
    description: 'Creamy, aromatic coconut-galangal soup with chicken, mushrooms, and lime.',
    cuisine: 'Thai',
    prep_minutes: 10,
    cook_minutes: 15,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'coconut milk', quantity: '2', unit: 'cans (14 oz)' },
      { name: 'chicken breast', quantity: '1/2', unit: 'lb, sliced' },
      { name: 'galangal', quantity: '4', unit: 'slices' },
      { name: 'lemongrass', quantity: '2', unit: 'stalks, bruised' },
      { name: 'kaffir lime leaves', quantity: '4', unit: 'leaves' },
      { name: 'mushroom', quantity: '1', unit: 'cup, sliced' },
      { name: 'lime juice', quantity: '2', unit: 'tbsp' },
      { name: 'fish sauce', quantity: '2', unit: 'tbsp' },
      { name: 'chili', quantity: '2', unit: "bird's eye" },
      { name: 'cilantro', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Bring coconut milk to a simmer with galangal, lemongrass, and kaffir lime leaves.',
      'Add chicken and mushrooms. Cook 8 minutes.',
      'Season with fish sauce, lime juice, and chilies.',
      'Taste and adjust — should be creamy, sour, salty, and spicy.',
      'Ladle into bowls.',
      'Garnish with cilantro and a drizzle of coconut cream.',
    ],
    tags: ['thai', 'soup', 'coconut', 'chicken', 'creamy'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 280,
      protein_g: 18,
      carbs_g: 8,
      fat_g: 20,
      fiber_g: 1,
      sugar_g: 3,
      sodium_mg: 780,
    },
  },
  {
    title: 'Larb',
    description: 'Spicy Laotian-Thai minced meat salad with herbs, lime, and toasted rice powder.',
    cuisine: 'Thai',
    prep_minutes: 15,
    cook_minutes: 5,
    servings: 4,
    calories: 240,
    ingredients: [
      { name: 'ground chicken', quantity: '1', unit: 'lb' },
      { name: 'shallot', quantity: '2', unit: 'minced' },
      { name: 'mint', quantity: '1/2', unit: 'cup' },
      { name: 'cilantro', quantity: '1/2', unit: 'cup' },
      { name: 'green onion', quantity: '4', unit: 'sliced' },
      { name: 'lime juice', quantity: '3', unit: 'tbsp' },
      { name: 'fish sauce', quantity: '2', unit: 'tbsp' },
      { name: 'toasted rice powder', quantity: '2', unit: 'tbsp' },
      { name: 'chili flakes', quantity: '1', unit: 'tsp' },
      { name: 'lettuce cups', quantity: '8', unit: 'leaves' },
    ],
    steps: [
      'Cook ground chicken in a pan, breaking apart. Drain excess fat.',
      'Add shallot, lime juice, and fish sauce while still warm.',
      'Add mint, cilantro, and green onion. Toss.',
      'Season with chili flakes and toasted rice powder.',
      'Serve in lettuce cups.',
      'Eat with sticky rice on the side.',
    ],
    tags: ['thai', 'salad', 'chicken', 'spicy', 'fresh'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 240,
      protein_g: 24,
      carbs_g: 6,
      fat_g: 12,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 780,
    },
  },
  {
    title: 'Thai Iced Tea',
    description:
      'Strong black tea brewed with spices, sweetened with condensed milk, and served over ice.',
    cuisine: 'Thai',
    prep_minutes: 5,
    cook_minutes: 5,
    servings: 4,
    calories: 160,
    ingredients: [
      { name: 'Thai tea mix', quantity: '1/2', unit: 'cup' },
      { name: 'water', quantity: '4', unit: 'cups' },
      { name: 'sugar', quantity: '1/4', unit: 'cup' },
      { name: 'condensed milk', quantity: '1/4', unit: 'cup' },
      { name: 'evaporated milk', quantity: '1/4', unit: 'cup' },
      { name: 'ice', quantity: '4', unit: 'cups' },
    ],
    steps: [
      'Boil water and steep Thai tea mix for 5 minutes.',
      'Strain and stir in sugar until dissolved.',
      'Cool the tea.',
      'Fill glasses with ice.',
      'Pour tea over ice.',
      'Top with a swirl of condensed and evaporated milk.',
    ],
    tags: ['thai', 'drink', 'tea', 'sweet', 'cold'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 160,
      protein_g: 3,
      carbs_g: 28,
      fat_g: 4,
      fiber_g: 0,
      sugar_g: 24,
      sodium_mg: 60,
    },
  },
  {
    title: 'Panang Curry',
    description: 'Thick, nutty Thai curry with a rich coconut-cream sauce and kaffir lime.',
    cuisine: 'Thai',
    prep_minutes: 10,
    cook_minutes: 15,
    servings: 4,
    calories: 380,
    ingredients: [
      { name: 'panang curry paste', quantity: '3', unit: 'tbsp' },
      { name: 'coconut milk', quantity: '2', unit: 'cans (14 oz)' },
      { name: 'beef', quantity: '1', unit: 'lb, sliced thin' },
      { name: 'kaffir lime leaves', quantity: '4', unit: 'shredded' },
      { name: 'fish sauce', quantity: '2', unit: 'tbsp' },
      { name: 'palm sugar', quantity: '1', unit: 'tbsp' },
      { name: 'peanuts', quantity: '2', unit: 'tbsp, crushed' },
      { name: 'Thai basil', quantity: '1/4', unit: 'cup' },
    ],
    steps: [
      'Fry curry paste in coconut cream until fragrant.',
      'Add beef and cook until browned.',
      'Add remaining coconut milk, kaffir lime, fish sauce, and sugar.',
      'Simmer 10-15 minutes until beef is tender and sauce is thick.',
      'Stir in Thai basil.',
      'Serve with rice, topped with crushed peanuts.',
    ],
    tags: ['thai', 'curry', 'beef', 'coconut', 'thick'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 380,
      protein_g: 28,
      carbs_g: 8,
      fat_g: 26,
      fiber_g: 2,
      sugar_g: 3,
      sodium_mg: 820,
    },
  },
  {
    title: 'Khao Soi',
    description: 'Northern Thai coconut curry noodle soup with crispy fried noodles on top.',
    cuisine: 'Thai',
    prep_minutes: 15,
    cook_minutes: 20,
    servings: 4,
    calories: 480,
    ingredients: [
      { name: 'egg noodles', quantity: '8', unit: 'oz' },
      { name: 'coconut milk', quantity: '2', unit: 'cans (14 oz)' },
      { name: 'curry paste', quantity: '2', unit: 'tbsp' },
      { name: 'chicken thigh', quantity: '1', unit: 'lb, bone-in' },
      { name: 'shallot', quantity: '2', unit: 'sliced' },
      { name: 'lime', quantity: '2', unit: 'wedges' },
      { name: 'pickled mustard greens', quantity: '1/2', unit: 'cup' },
      { name: 'shallot oil', quantity: '1', unit: 'tbsp' },
    ],
    steps: [
      'Fry curry paste in coconut cream. Add chicken and brown.',
      'Add coconut milk and simmer 20 minutes until chicken is tender.',
      'Cook noodles. Deep-fry some noodles until crispy for topping.',
      'Ladle curry over soft noodles.',
      'Top with crispy noodles, pickled greens, and sliced shallots.',
      'Serve with lime wedges and chili oil.',
    ],
    tags: ['thai', 'noodles', 'curry', 'coconut', 'northern-thai'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 480,
      protein_g: 24,
      carbs_g: 48,
      fat_g: 22,
      fiber_g: 3,
      sugar_g: 4,
      sodium_mg: 860,
    },
  },
  {
    title: 'Satay',
    description: 'Grilled marinated chicken skewers with creamy peanut dipping sauce.',
    cuisine: 'Thai',
    prep_minutes: 20,
    cook_minutes: 8,
    servings: 6,
    calories: 280,
    ingredients: [
      { name: 'chicken thigh', quantity: '1', unit: 'lb, cubed' },
      { name: 'coconut milk', quantity: '1/2', unit: 'cup' },
      { name: 'turmeric', quantity: '1', unit: 'tsp' },
      { name: 'coriander', quantity: '1', unit: 'tsp' },
      { name: 'cumin', quantity: '1/2', unit: 'tsp' },
      { name: 'peanut butter', quantity: '1/4', unit: 'cup' },
      { name: 'coconut milk (sauce)', quantity: '1/2', unit: 'cup' },
      { name: 'lime juice', quantity: '1', unit: 'tbsp' },
      { name: 'bamboo skewers', quantity: '12', unit: 'soaked' },
    ],
    steps: [
      'Marinate chicken in coconut milk, turmeric, coriander, and cumin for 2 hours.',
      'Thread onto skewers.',
      'Grill over medium-high heat until charred and cooked through.',
      'Make peanut sauce: heat peanut butter with coconut milk, lime, and sugar.',
      'Serve skewers with peanut sauce and cucumber relish.',
    ],
    tags: ['thai', 'grilled', 'chicken', 'peanut', 'skewers'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 22,
      carbs_g: 10,
      fat_g: 16,
      fiber_g: 2,
      sugar_g: 4,
      sodium_mg: 480,
    },
  },
  {
    title: 'Thai Fish Cakes',
    description:
      'Crispy curried fish cakes with long beans and kaffir lime, served with sweet chili sauce.',
    cuisine: 'Thai',
    prep_minutes: 15,
    cook_minutes: 8,
    servings: 4,
    calories: 200,
    ingredients: [
      { name: 'white fish', quantity: '1', unit: 'lb, minced' },
      { name: 'red curry paste', quantity: '1', unit: 'tbsp' },
      { name: 'long beans', quantity: '1/4', unit: 'cup, diced' },
      { name: 'kaffir lime leaf', quantity: '3', unit: 'shredded' },
      { name: 'egg', quantity: '1', unit: 'white' },
      { name: 'fish sauce', quantity: '1', unit: 'tsp' },
      { name: 'sweet chili sauce', quantity: '1/4', unit: 'cup' },
      { name: 'oil', quantity: '1/2', unit: 'cup, for frying' },
    ],
    steps: [
      'Blend fish, curry paste, egg white, and fish sauce in a food processor.',
      'Add long beans and kaffir lime leaf. Mix by hand.',
      'Form into small patties.',
      'Deep fry at 350°F until golden and puffy.',
      'Drain on paper towels.',
      'Serve with sweet chili sauce.',
    ],
    tags: ['thai', 'fish', 'fried', 'appetizer', 'curry'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 200,
      protein_g: 18,
      carbs_g: 8,
      fat_g: 10,
      fiber_g: 1,
      sugar_g: 3,
      sodium_mg: 580,
    },
  },
];

export const thaiRecipes = generateCuisineRecipes(configs);
