import type { CuisineRecipeConfig } from './types';
import { generateCuisineRecipes } from './types';

const configs: CuisineRecipeConfig[] = [
  {
    title: 'Pho Bo',
    description: 'Vietnamese beef noodle soup with aromatic star anise, cinnamon, and fresh herbs.',
    cuisine: 'Vietnamese',
    prep_minutes: 15,
    cook_minutes: 360,
    servings: 8,
    calories: 380,
    ingredients: [
      { name: 'beef bones', quantity: '3', unit: 'lb' },
      { name: 'rice noodles', quantity: '8', unit: 'oz' },
      { name: 'star anise', quantity: '3', unit: 'whole' },
      { name: 'cinnamon stick', quantity: '1', unit: 'small' },
      { name: 'onion', quantity: '1', unit: 'halved, charred' },
      { name: 'ginger', quantity: '3', unit: 'inches, charred' },
      { name: 'fish sauce', quantity: '2', unit: 'tbsp' },
      { name: 'bean sprouts', quantity: '2', unit: 'cups' },
      { name: 'Thai basil', quantity: '1', unit: 'cup' },
      { name: 'lime', quantity: '4', unit: 'wedges' },
    ],
    steps: [
      'Char onion and ginger under the broiler. Blanch bones.',
      'Simmer bones with star anise, cinnamon, charred onion, and ginger for 6 hours.',
      'Strain broth, season with fish sauce and sugar.',
      'Cook rice noodles and divide among bowls.',
      'Add rare sliced beef, ladle boiling broth over.',
      'Serve with bean sprouts, Thai basil, lime, hoisin, and sriracha.',
    ],
    tags: ['vietnamese', 'soup', 'beef', 'noodles', 'pho'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 24,
      carbs_g: 42,
      fat_g: 10,
      fiber_g: 2,
      sugar_g: 2,
      sodium_mg: 860,
    },
  },
  {
    title: 'Banh Mi',
    description:
      'Vietnamese baguette sandwich with pate, pickled vegetables, cilantro, and jalapeño.',
    cuisine: 'Vietnamese',
    prep_minutes: 20,
    cook_minutes: 10,
    servings: 4,
    calories: 380,
    ingredients: [
      { name: 'baguette', quantity: '4', unit: 'small' },
      { name: 'pork belly', quantity: '1/2', unit: 'lb, sliced' },
      { name: 'pate', quantity: '4', unit: 'tbsp' },
      { name: 'pickled daikon & carrot', quantity: '1', unit: 'cup' },
      { name: 'cilantro', quantity: '1', unit: 'cup' },
      { name: 'jalapeño', quantity: '2', unit: 'sliced' },
      { name: 'soy sauce', quantity: '1', unit: 'tbsp' },
      { name: 'mayonnaise', quantity: '2', unit: 'tbsp' },
    ],
    steps: [
      'Split baguette and toast.',
      'Spread mayonnaise and pate on the bread.',
      'Grill or roast pork belly until crispy.',
      'Layer pork belly on the sandwich.',
      'Add pickled daikon and carrot, jalapeño, and cilantro.',
      'Drizzle with soy sauce and serve.',
    ],
    tags: ['vietnamese', 'sandwich', 'pork', 'baguette', 'street-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 18,
      carbs_g: 42,
      fat_g: 14,
      fiber_g: 3,
      sugar_g: 6,
      sodium_mg: 860,
    },
  },
  {
    title: 'Goi Cuon',
    description: 'Fresh Vietnamese spring rolls with shrimp, pork, herbs, and rice vermicelli.',
    cuisine: 'Vietnamese',
    prep_minutes: 25,
    cook_minutes: 5,
    servings: 8,
    calories: 120,
    ingredients: [
      { name: 'rice paper wrappers', quantity: '16', unit: 'round' },
      { name: 'shrimp', quantity: '1/2', unit: 'lb, cooked & halved' },
      { name: 'pork', quantity: '1/4', unit: 'lb, cooked & sliced' },
      { name: 'rice vermicelli', quantity: '4', unit: 'oz, cooked' },
      { name: 'lettuce', quantity: '8', unit: 'leaves' },
      { name: 'mint', quantity: '1', unit: 'cup' },
      { name: 'cilantro', quantity: '1/2', unit: 'cup' },
      { name: 'hoisin peanut sauce', quantity: '1/2', unit: 'cup' },
    ],
    steps: [
      'Dip rice paper in warm water until pliable.',
      'Layer lettuce, vermicelli, pork, shrimp, and herbs.',
      'Fold sides in, roll tightly.',
      'Repeat with remaining wrappers.',
      'Make dipping sauce: hoisin, peanut butter, and sriracha.',
      'Serve fresh spring rolls with dipping sauce.',
    ],
    tags: ['vietnamese', 'spring-rolls', 'fresh', 'shrimp', 'light'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: false },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 120,
      protein_g: 8,
      carbs_g: 16,
      fat_g: 2,
      fiber_g: 1,
      sugar_g: 1,
      sodium_mg: 280,
    },
  },
  {
    title: 'Bun Cha',
    description:
      'Hanoi-style grilled pork patties and sliced pork in a sweet-sour fish sauce broth with noodles.',
    cuisine: 'Vietnamese',
    prep_minutes: 20,
    cook_minutes: 15,
    servings: 4,
    calories: 380,
    ingredients: [
      { name: 'ground pork', quantity: '1', unit: 'lb' },
      { name: 'pork belly', quantity: '1/2', unit: 'lb, sliced' },
      { name: 'rice vermicelli', quantity: '8', unit: 'oz' },
      { name: 'fish sauce', quantity: '3', unit: 'tbsp' },
      { name: 'sugar', quantity: '2', unit: 'tbsp' },
      { name: 'vinegar', quantity: '2', unit: 'tbsp' },
      { name: 'garlic', quantity: '3', unit: 'cloves' },
      { name: 'lettuce & herbs', quantity: '2', unit: 'cups' },
    ],
    steps: [
      'Season ground pork and form into patties. Marinate sliced pork belly.',
      'Grill pork patties and belly slices over charcoal until charred.',
      'Make nuoc cham: fish sauce, sugar, vinegar, garlic, and water.',
      'Cook vermicelli noodles.',
      'Serve grilled pork in a bowl of nuoc cham broth.',
      'Dip noodles and herbs into the broth as you eat.',
    ],
    tags: ['vietnamese', 'grilled', 'pork', 'noodles', 'hanoi'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 380,
      protein_g: 24,
      carbs_g: 36,
      fat_g: 14,
      fiber_g: 1,
      sugar_g: 6,
      sodium_mg: 860,
    },
  },
  {
    title: 'Com Tam',
    description: 'Broken rice plate with grilled pork chop, egg meatloaf, and fish sauce.',
    cuisine: 'Vietnamese',
    prep_minutes: 15,
    cook_minutes: 15,
    servings: 4,
    calories: 420,
    ingredients: [
      { name: 'broken rice', quantity: '2', unit: 'cups' },
      { name: 'pork chop', quantity: '4', unit: 'thin, marinated' },
      { name: 'egg meatloaf (chao)', quantity: '4', unit: 'slices' },
      { name: 'fish sauce', quantity: '2', unit: 'tbsp' },
      { name: 'sugar', quantity: '1', unit: 'tbsp' },
      { name: 'garlic', quantity: '2', unit: 'cloves, minced' },
      { name: 'scallion oil', quantity: '2', unit: 'tbsp' },
      { name: 'pickled vegetables', quantity: '1/2', unit: 'cup' },
    ],
    steps: [
      'Marinate pork chops in fish sauce, sugar, garlic, and oil.',
      'Grill pork chops until charred and cooked through.',
      'Cook broken rice.',
      'Make nuoc cham dipping sauce.',
      'Plate rice with pork chop, egg meatloaf, and scallion oil.',
      'Serve with pickled vegetables and nuoc cham.',
    ],
    tags: ['vietnamese', 'rice-plate', 'pork', 'grilled', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 420,
      protein_g: 28,
      carbs_g: 44,
      fat_g: 12,
      fiber_g: 1,
      sugar_g: 4,
      sodium_mg: 860,
    },
  },
  {
    title: 'Vietnamese Coffee',
    description:
      'Strong dark roast coffee brewed through a phin filter, mixed with sweetened condensed milk.',
    cuisine: 'Vietnamese',
    prep_minutes: 3,
    cook_minutes: 5,
    servings: 2,
    calories: 140,
    ingredients: [
      { name: 'Vietnamese coffee', quantity: '3', unit: 'tbsp, ground' },
      { name: 'condensed milk', quantity: '2', unit: 'tbsp' },
      { name: 'hot water', quantity: '1', unit: 'cup' },
      { name: 'ice', quantity: '2', unit: 'cups' },
    ],
    steps: [
      'Add condensed milk to a glass.',
      'Place phin filter on top, add coffee grounds.',
      'Pour hot water into the filter. Let drip for 5 minutes.',
      'Stir coffee and condensed milk together.',
      'Pour over ice for iced version.',
      'Stir and enjoy.',
    ],
    tags: ['vietnamese', 'drink', 'coffee', 'sweet', 'condensed-milk'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: false },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 140,
      protein_g: 3,
      carbs_g: 22,
      fat_g: 4,
      fiber_g: 0,
      sugar_g: 18,
      sodium_mg: 40,
    },
  },
  {
    title: 'Banh Xeo',
    description:
      'Crispy turmeric-tinted crepe filled with shrimp, pork, bean sprouts, wrapped in lettuce.',
    cuisine: 'Vietnamese',
    prep_minutes: 15,
    cook_minutes: 8,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'rice flour', quantity: '1', unit: 'cup' },
      { name: 'turmeric', quantity: '1', unit: 'tsp' },
      { name: 'coconut milk', quantity: '1/2', unit: 'cup' },
      { name: 'shrimp', quantity: '1/2', unit: 'lb' },
      { name: 'pork belly', quantity: '4', unit: 'oz, sliced' },
      { name: 'bean sprouts', quantity: '2', unit: 'cups' },
      { name: 'lettuce', quantity: '8', unit: 'leaves' },
      { name: 'mint', quantity: '1/2', unit: 'cup' },
    ],
    steps: [
      'Make batter: rice flour, turmeric, coconut milk, and water.',
      'Sauté shrimp and pork in a hot pan.',
      'Pour batter over, add bean sprouts. Cover and cook until crispy.',
      'Fold crepe in half.',
      'Wrap pieces in lettuce with mint.',
      'Dip in nuoc cham sauce.',
    ],
    tags: ['vietnamese', 'crepe', 'shrimp', 'crispy', 'turmeric'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 280,
      protein_g: 16,
      carbs_g: 28,
      fat_g: 10,
      fiber_g: 3,
      sugar_g: 2,
      sodium_mg: 680,
    },
  },
  {
    title: 'Che',
    description: 'Vietnamese sweet dessert soup with beans, coconut milk, and tapioca pearls.',
    cuisine: 'Vietnamese',
    prep_minutes: 15,
    cook_minutes: 20,
    servings: 6,
    calories: 180,
    ingredients: [
      { name: 'mung beans', quantity: '1/2', unit: 'cup, cooked' },
      { name: 'tapioca pearls', quantity: '1/4', unit: 'cup, small' },
      { name: 'coconut milk', quantity: '1', unit: 'can (14 oz)' },
      { name: 'sugar', quantity: '1/3', unit: 'cup' },
      { name: 'pandan extract', quantity: '1', unit: 'tsp' },
      { name: 'ice', quantity: '2', unit: 'cups' },
    ],
    steps: [
      'Cook mung beans until soft. Cook tapioca until translucent.',
      'Heat coconut milk with sugar and pandan.',
      'Combine beans and tapioca in bowls.',
      'Pour coconut milk over.',
      'Add ice for a cold version.',
      'Serve as a refreshing dessert.',
    ],
    tags: ['vietnamese', 'dessert', 'beans', 'coconut', 'sweet'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: true },
      { restriction: 'vegan', is_compliant: true },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: true },
      { restriction: 'kosher', is_compliant: true },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 180,
      protein_g: 4,
      carbs_g: 32,
      fat_g: 6,
      fiber_g: 2,
      sugar_g: 18,
      sodium_mg: 60,
    },
  },
  {
    title: 'Pho Ga',
    description: 'Vietnamese chicken noodle soup with ginger, star anise, and fresh herbs.',
    cuisine: 'Vietnamese',
    prep_minutes: 15,
    cook_minutes: 60,
    servings: 6,
    calories: 320,
    ingredients: [
      { name: 'whole chicken', quantity: '1', unit: '(3-4 lb)' },
      { name: 'rice noodles', quantity: '8', unit: 'oz' },
      { name: 'ginger', quantity: '3', unit: 'inches, sliced' },
      { name: 'star anise', quantity: '2', unit: 'whole' },
      { name: 'onion', quantity: '1', unit: 'halved' },
      { name: 'fish sauce', quantity: '2', unit: 'tbsp' },
      { name: 'bean sprouts', quantity: '2', unit: 'cups' },
      { name: 'Thai basil', quantity: '1', unit: 'cup' },
    ],
    steps: [
      'Simmer whole chicken with charred ginger, onion, and star anise for 45 minutes.',
      'Remove chicken, shred meat. Strain broth.',
      'Season broth with fish sauce.',
      'Cook rice noodles.',
      'Divide noodles and chicken among bowls.',
      'Ladle hot broth, serve with herbs and bean sprouts.',
    ],
    tags: ['vietnamese', 'soup', 'chicken', 'noodles', 'comfort-food'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 320,
      protein_g: 28,
      carbs_g: 36,
      fat_g: 6,
      fiber_g: 1,
      sugar_g: 1,
      sodium_mg: 820,
    },
  },
  {
    title: 'Cha Gio',
    description: 'Crispy Vietnamese fried egg rolls with pork, crab, and woodear mushrooms.',
    cuisine: 'Vietnamese',
    prep_minutes: 30,
    cook_minutes: 10,
    servings: 8,
    calories: 180,
    ingredients: [
      { name: 'egg roll wrappers', quantity: '24', unit: 'pieces' },
      { name: 'ground pork', quantity: '1/2', unit: 'lb' },
      { name: 'crab meat', quantity: '1/4', unit: 'lb' },
      { name: 'woodear mushroom', quantity: '1/4', unit: 'cup, soaked & minced' },
      { name: 'glass noodles', quantity: '2', unit: 'oz, soaked & cut' },
      { name: 'egg', quantity: '1', unit: 'beaten' },
      { name: 'fish sauce', quantity: '1', unit: 'tsp' },
      { name: 'oil', quantity: '2', unit: 'cups, for frying' },
    ],
    steps: [
      'Mix pork, crab, mushroom, glass noodles, egg, and fish sauce.',
      'Wrap filling in egg roll wrappers.',
      'Deep fry at 350°F until golden and crispy.',
      'Drain on paper towels.',
      'Serve with lettuce wraps, herbs, and nuoc cham.',
      'Wrap in lettuce with herbs and dip in sauce.',
    ],
    tags: ['vietnamese', 'egg-rolls', 'fried', 'pork', 'appetizer'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: false },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 180,
      protein_g: 8,
      carbs_g: 18,
      fat_g: 8,
      fiber_g: 1,
      sugar_g: 1,
      sodium_mg: 380,
    },
  },
  {
    title: 'Ca Kho To',
    description: 'Caramelized fish in a clay pot with soy, fish sauce, and coconut water.',
    cuisine: 'Vietnamese',
    prep_minutes: 10,
    cook_minutes: 20,
    servings: 4,
    calories: 280,
    ingredients: [
      { name: 'catfish fillet', quantity: '1.5', unit: 'lb, cut into steaks' },
      { name: 'coconut water', quantity: '1/2', unit: 'cup' },
      { name: 'fish sauce', quantity: '2', unit: 'tbsp' },
      { name: 'soy sauce', quantity: '1', unit: 'tbsp' },
      { name: 'sugar', quantity: '2', unit: 'tbsp, caramelized' },
      { name: 'garlic', quantity: '3', unit: 'cloves, minced' },
      { name: 'chili', quantity: '2', unit: "bird's eye" },
      { name: 'green onion', quantity: '3', unit: 'cut' },
    ],
    steps: [
      'Make caramel: melt sugar until dark amber.',
      'Add garlic and chili carefully (it will sputter).',
      'Add fish steaks, fish sauce, soy sauce, and coconut water.',
      'Simmer in a clay pot for 20 minutes until sauce is thick and glossy.',
      'Garnish with green onion and pepper.',
      'Serve with steamed rice.',
    ],
    tags: ['vietnamese', 'fish', 'caramelized', 'clay-pot', 'savory'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: true },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: true },
    ],
    nutrition: {
      calories: 280,
      protein_g: 28,
      carbs_g: 10,
      fat_g: 12,
      fiber_g: 0,
      sugar_g: 6,
      sodium_mg: 780,
    },
  },
  {
    title: 'Banh Cuon',
    description: 'Steamed rice flour sheets filled with minced pork and woodear mushrooms.',
    cuisine: 'Vietnamese',
    prep_minutes: 20,
    cook_minutes: 15,
    servings: 4,
    calories: 220,
    ingredients: [
      { name: 'rice flour', quantity: '1', unit: 'cup' },
      { name: 'tapioca starch', quantity: '1/4', unit: 'cup' },
      { name: 'ground pork', quantity: '1/2', unit: 'lb' },
      { name: 'woodear mushroom', quantity: '1/4', unit: 'cup, minced' },
      { name: 'fried shallot', quantity: '2', unit: 'tbsp' },
      { name: 'cha lua', quantity: '4', unit: 'slices (pork roll)' },
      { name: 'nuoc cham', quantity: '1/2', unit: 'cup' },
    ],
    steps: [
      'Make batter with rice flour, tapioca, and water.',
      'Sauté pork with woodear mushroom for filling.',
      'Steam thin batter sheets on a cloth over boiling water.',
      'Place filling on the steamed sheet, roll up.',
      'Cut into pieces, top with fried shallots.',
      'Serve with cha lua and nuoc cham.',
    ],
    tags: ['vietnamese', 'steamed', 'rice-flour', 'pork', 'breakfast'],
    dietary_info: [
      { restriction: 'vegetarian', is_compliant: false },
      { restriction: 'vegan', is_compliant: false },
      { restriction: 'keto', is_compliant: false },
      { restriction: 'gluten-free', is_compliant: true },
      { restriction: 'dairy-free', is_compliant: true },
      { restriction: 'nut-free', is_compliant: true },
      { restriction: 'halal', is_compliant: false },
      { restriction: 'kosher', is_compliant: false },
      { restriction: 'paleo', is_compliant: false },
    ],
    nutrition: {
      calories: 220,
      protein_g: 14,
      carbs_g: 28,
      fat_g: 6,
      fiber_g: 1,
      sugar_g: 2,
      sodium_mg: 680,
    },
  },
];

export const vietnameseRecipes = generateCuisineRecipes(configs);
